### ISSUE TITLE
Build failing at autogen.sh

### ISSUE THREAD

**Issue by Nevtep** [zeromq/libzmq#1004]
I get this output when running autogen.sh for zeromq-4.0.4
root@Faith-Desk:/usr/local/src/zeromq-4.0.4# ./autogen.sh 
perl: warning: Setting locale failed.
perl: warning: Please check that your locale settings:
    LANGUAGE = (unset),
    LC_ALL = (unset),
    LC_CTYPE = "UTF-8",
    LANG = "en_US.UTF-8"
    are supported and installed on your system.
perl: warning: Falling back to the standard locale ("C").
autoreconf: Entering directory `.'
autoreconf: configure.ac: not using Gettext
autoreconf: configure.ac: not using aclocal
autoreconf: configure.ac: tracing
autoreconf: configure.ac: subdirectory foreign/openpgm/build-staging/openpgm/pgm/ not present
autoreconf: configure.ac: not using Libtool
autoreconf: running: /usr/bin/autoconf --include=config --force
configure.ac:14: error: possibly undefined macro: AM_INIT_AUTOMAKE
      If this token and others are legitimate, please use m4_pattern_allow.
      See the Autoconf documentation.
configure.ac:47: error: possibly undefined macro: AM_PROG_CC_C_O
configure.ac:57: error: possibly undefined macro: AC_LIBTOOL_WIN32_DLL
configure.ac:58: error: possibly undefined macro: AC_PROG_LIBTOOL
configure.ac:132: error: possibly undefined macro: AC_DEFINE
configure.ac:228: error: possibly undefined macro: AC_MSG_ERROR
configure.ac:267: error: possibly undefined macro: _AC_LANG_ABBREV
configure.ac:320: error: possibly undefined macro: AC_TYPE_SIZE_T
configure.ac:321: error: possibly undefined macro: AC_TYPE_SSIZE_T
configure.ac:430: error: possibly undefined macro: AM_CONDITIONAL
autoreconf: /usr/bin/autoconf failed with exit status: 1
autogen.sh: error: autoreconf exited with status 0

**Comment by bluca** [comment]
Closing as checks for programs where added in autogen.sh
