### ISSUE TITLE
Problem when using srcfd to retrieve the IP address from multiple connected nodes

### ISSUE THREAD

**Issue by kouzinopoulos** [zeromq/libzmq#1013]
When trying to retrieve the IP address from multiple connected nodes on a push/pull application using the latest srcfd code from the master branch, zeromq only reports the IP address of the last connected node. Moreover, when that node disconnects, the application asserts at the getpeername fuction.

A code, based on test_srcfd.cpp that demonstrates the problem:

 http://pastebin.com/8DQUSkrU
http://pastebin.com/XynZ6w7z

**Comment by sigiesec** [comment]
This issue is obsolete as the code was changed by #1953 and the preferred way to access the information is now via metadata.
