### ISSUE TITLE
metadata changes cause term to hang

### ISSUE THREAD

**Issue by minrk** [zeromq/libzmq#1052]
I'm still working on making a simplified test case, but PR #999 introduced a regression that can cause `zmq_term` to hang.

Something in that change prevents the message expected by `term_mailbox.recv (&cmd, -1);` in `zmq::ctx_t::terminate` from arriving.

My test case where I can reproduce this with 100% reliability is `nosetests zmq.tests.test_monqueue` in the pyzmq test suite, which involves starting a simple polling function in a background thread, and calling `zmq_term` on the global context in the main thread. This works without issue in libzmq@55c06924c8af421351599037572c3a365851d6d8, and `zmq_term` never returns in libzmq@2db7cdc6a6ae62fa2196d6a51d2310ab51c041f8.

Hopefully I can figure out a simple test case. What's weird is I have no idea how the changes to metadata in that PR could affect socket closing or teardown, but it clearly does.

**Comment by sigiesec** [comment]
Have you been able to produce a test case that reproduces the problem?
