### ISSUE TITLE
Make of the tools directory fails when cross compiling zeromq4.0.4 for android using NDK

### ISSUE THREAD

**Issue by blair-anson** [zeromq/libzmq#1063]
The linking fails with undefined reference errors when executing the following sequence of commands...

./autogen.sh
./configure --enable-static --disable-shared --host=arm-linux-androideabi --prefix=$OUTPUT_DIR LDFLAGS="-L$OUTPUT_DIR/lib" CPPFLAGS="-fPIC -I$OUTPUT_DIR/include" LIBS="-lgcc"
make

However if you edit the Makefile in the tools directory and change to the following settings, then the make & linking succeeds 

LIBS = -lrt -lpthread -lgcc -lsupc++ -lstdc++

You may want to update the instructions on the following page for zeromq4.0.4
http://zeromq.org/build:android

**Comment by faisal00813** [comment]
The above workaround does work for armv7. But it does now work for arm64.
I have tried following commands...

`./autogen.sh`
`./configure --enable-static --disable-shared --host=aarch64-linux-android --prefix=$OUTPUT_DIR LDFLAGS="-L$OUTPUT_DIR/lib" CPPFLAGS="-fPIC -I$OUTPUT_DIR/include" LIBS="-lgcc" --with-libsodium=no --disable-curve-keygen --enable-drafts=no --enable-libunwind=no`

then edited Make file as follows
`LIBS = -lrt -lpthread -lgcc -lsupc++ -lstdc++`
did not work.

`Output was 
CXXLD    src/libzmq.la
  CXXLD    perf/local_lat
/root/Work/linux_dev/android_sdk/standalone_toolchains/arm64/bin/../lib/gcc/aarch64-linux-android/4.9.x/../../../../aarch64-linux-android/bin/ld: perf/local_lat.o: Relocations in generic ELF (EM: 62)
/root/Work/linux_dev/android_sdk/standalone_toolchains/arm64/bin/../lib/gcc/aarch64-linux-android/4.9.x/../../../../aarch64-linux-android/bin/ld: perf/local_lat.o: Relocations in generic ELF (EM: 62)
/root/Work/linux_dev/android_sdk/standalone_toolchains/arm64/bin/../lib/gcc/aarch64-linux-android/4.9.x/../../../../aarch64-linux-android/bin/ld: perf/local_lat.o: Relocations in generic ELF (EM: 62)
/root/Work/linux_dev/android_sdk/standalone_toolchains/arm64/bin/../lib/gcc/aarch64-linux-android/4.9.x/../../../../aarch64-linux-android/bin/ld: perf/local_lat.o: Relocations in generic ELF (EM: 62)
/root/Work/linux_dev/android_sdk/standalone_toolchains/arm64/bin/../lib/gcc/aarch64-linux-android/4.9.x/../../../../aarch64-linux-android/bin/ld: perf/local_lat.o: Relocations in generic ELF (EM: 62)
/root/Work/linux_dev/android_sdk/standalone_toolchains/arm64/bin/../lib/gcc/aarch64-linux-android/4.9.x/../../../../aarch64-linux-android/bin/ld: perf/local_lat.o: Relocations in generic ELF (EM: 62)
/root/Work/linux_dev/android_sdk/standalone_toolchains/arm64/bin/../lib/gcc/aarch64-linux-android/4.9.x/../../../../aarch64-linux-android/bin/ld: perf/local_lat.o: Relocations in generic ELF (EM: 62)
perf/local_lat.o: error adding symbols: File in wrong format
collect2: error: ld returned 1 exit status
make[1]: *** [perf/local_lat] Error 1
make[1]: Leaving directory `/root/Work/libs/src/libzmq'
make: *** [all-recursive] Error 1`
Any workarounds?

**Comment by bluca** [comment]
Same as https://github.com/zeromq/libzmq/issues/2894
