### ISSUE TITLE
error when I am trying to build for iphone application

### ISSUE THREAD

**Issue by mayankkuls** [zeromq/libzmq#1068]
I am trying to build for iphone application but its show error 
ignoring file /Users/mayankkulshrestha/Documents/iPhone/ZeroMQTest/ZeroMQ.framework/ZeroMQ, missing required architecture x86_64 in file /Users/mayankkulshrestha/Documents/iPhone/ZeroMQTest/ZeroMQ.framework/ZeroMQ (4 slices)
Undefined symbols for architecture x86_64

I used http://paolodenti.blog.com/2012/07/24/zeromq-ios/ this blog please help me.

**Comment by sigiesec** [comment]
Please describe more specifically what steps you have done that lead to this error, and specify the used libzmq version and your environment.

Closing this for now, feel free to reopen with more information.
