### ISSUE TITLE
Test failures on OSX, abstract_ipc and id2fd

### ISSUE THREAD

**Issue by dmeehan1968** [zeromq/libzmq#1077]
I'm getting test failure on OSX builds of latest master, although these have existed for a while in my experience.

abstract_ipc fails consistently

id2fd fails sporadically.

I've updated the open files limit for the current shell, as advised in the OSX platform notes.

abstract_ipc creates a pipe with a @ character at the beginning which seems to be the source of failure, but if I remove the @ symbol, it then hangs on the test indefinitely.

Is there a way of getting extract progress or debug information related to the test progress so that I can track down the cause?

**Comment by bluca** [comment]
Closing as it was fixed by https://github.com/zeromq/libzmq/pull/1082
