### ISSUE TITLE
python26-zmq requires libzmq.so.1 zeromq provides 1ibzmq.so.3

### ISSUE THREAD

**Issue by grantmcwilliams** [zeromq/libzmq#1084]
A salt-stack minion will not reconnect to a rebooted salt-master if using zeromq 2.19. Upgrading to zeromq 3 seems to be the solution. 

However, python26-zmq (from EPEL repository) requires libzmq.so.1 and the only libzmq.so.1 is provided by zeromq/libzmq3 packages found at http://download.opensuse.org/repositories/home:/fengshuo:/zeromq/CentOS_CentOS-5/

Choices:
1. should python26.zmq from EPEL have it's requires changed to libzmq.so.3?
2. should libzmq3 packages provide both libzmq.so.1 and libzmq.so.3?

I'm not sure what the difference between libzmq.so.1 and libzmq.so.3 so I'm looking for advice. If EPEL should change the package then I'll push the bug up that tree.

**Comment by bluca** [comment]
Closing as it was an ABI problem that is long obsolete now
