### ISSUE TITLE
architecture armv7 not supported

### ISSUE THREAD

**Issue by mayankkuls** [zeromq/libzmq#1086]
I have created a framework with the help of this blog http://paolodenti.blog.com/2012/07/24/zeromq-ios/. but when we use this for armv7 this will give an error

**Comment by bluca** [comment]
Closing as the build and tests work fine on ARMv7 now as demonstrated by OBS's builds: https://build.opensuse.org/package/binaries/home:zeromq:git-stable/libzmq?repository=openSUSE_Factory_ARM
