### ISSUE TITLE
lt-test_many_sockets and lt-test_filter_ipc fail in Docker container environment

### ISSUE THREAD

**Issue by trevorbernard** [zeromq/libzmq#1129]
I was able to recreate these same errors building on ubuntu:12.04, ubuntu:14:04 and debian:latest.

``` bash
========================================
   zeromq 4.1.0: tests/test-suite.log
========================================

# TOTAL: 56
# PASS:  54
# SKIP:  0
# XFAIL: 0
# FAIL:  2
# XPASS: 0
# ERROR: 0

.. contents:: :depth: 2

FAIL: test_many_sockets
=======================

lt-test_many_sockets: test_many_sockets.cpp:40: void test_system_max(): Assertion `(int) sockets.size () < no_of_sockets' failed.

FAIL: test_filter_ipc
=====================

lt-test_filter_ipc: test_filter_ipc.cpp:125: int main(): Assertion `ngroups != -1 && ngroups != 0' failed.
```

**Comment by blalor** [comment]
I ran into this as well, building ZeroMQ 4.1.2 from source in a Docker container.

**Comment by tswast** [comment]
I had the same issue building ZeroMQ 4.1.3 from source in a Docker container.

Relevant portion of the Dockerfile:

    FROM golang
   
    # Install build tools so we can set up ZeroMQ.
    # https://github.com/crosbymichael/build-essential-docker
    RUN apt-get update
    RUN apt-get update && apt-get install -y --no-install-recommends \
        make \
        automake \
        gcc \
        build-essential \
        g++ \
        cpp \
        libc6-dev \
        man-db \
        autoconf \
        pkg-config
    
    # Install dependencies for goczmq.
    # https://github.com/zeromq/goczmq
    WORKDIR /tmp
    RUN wget https://download.libsodium.org/libsodium/releases/libsodium-1.0.3.tar.gz \
        && wget https://download.libsodium.org/libsodium/releases/libsodium-1.0.3.tar.gz.sig \
        && wget https://download.libsodium.org/jedi.gpg.asc \
        && gpg --import jedi.gpg.asc \
        && gpg --verify libsodium-1.0.3.tar.gz.sig libsodium-1.0.3.tar.gz \
        && tar zxvf libsodium-1.0.3.tar.gz \
        && cd libsodium-1.0.3 \
        && ./configure; make check \
        && make install \
        && ldconfig
    RUN wget http://download.zeromq.org/zeromq-4.1.3.tar.gz \
        && tar zxvf zeromq-4.1.3.tar.gz \
        && cd zeromq-4.1.3 \
        && ./configure --with-libsodium; make; make check \
        && make install \
        && ldconfig

**Comment by tswast** [comment]
For docker the workaround is the install the Debian package. http://zeromq.org/distro:debian

    RUN echo deb http://httpredir.debian.org/debian/ experimental main contrib non-free >> /etc/apt/sources.list
    RUN echo deb-src http://httpredir.debian.org/debian/ experimental main contrib non-free >> /etc/apt/sources.list
    RUN apt-get update
    RUN apt-get install -y --no-install-recommends libzmq5-dev

**Comment by fuag15** [comment]
I ran into this today. What worked for me was raising the per process socket limit in the container before running the tests.

**Comment by tswast** [comment]
Thanks @fuag15 adding a RUN ulimit -n 10000 did the trick.

**Comment by bluca** [comment]
Closing as one test was fixed by https://github.com/zeromq/libzmq/pull/1260 and the other by incresing the system file limit
