### ISSUE TITLE
Can't run tests concurrently due to hardcoded port numbers

### ISSUE THREAD

**Issue by gward** [zeromq/libzmq#1140]
I stumbled across this because our build system (a local instance of OBS) uses chroot environments to build RPMs, with multiple chroots on a single host. If the zeromq 4.0.x tests happen to run concurrently in different chroots on the same host, they fail.

You can reproduce this easily without a chroot: just run "make check" twice concurrently on the same host. Sample output:

```
PASS: test_ctx_destroy
PASS: test_security_null
../config/test-driver: line 107: 19440 Aborted                 (core dumped) "$@" >
$log_file 2>&1
FAIL: test_security_curve
PASS: test_iov
PASS: test_spec_req
PASS: test_spec_dealer
../config/test-driver: line 107: 19596 Aborted                 (core dumped) "$@" >
$log_file 2>&1
FAIL: test_req_correlate
../config/test-driver: line 107: 19619 Aborted                 (core dumped) "$@" >
$log_file 2>&1
FAIL: test_req_relaxed
PASS: test_conflate
PASS: test_inproc_connect
```

(These tests all pass just fine when run in isolation.)

It's not hard to find the source of the problem:

```
$ grep zmq_bind tests/test_*.cpp
[...]
tests/test_req_correlate.cpp:    rc = zmq_bind (router, "tcp://127.0.0.1:5555");
tests/test_req_relaxed.cpp:    rc = zmq_bind (req, "tcp://127.0.0.1:5555");
[...]
tests/test_security_curve.cpp:    rc = zmq_bind (server, "tcp://127.0.0.1:9998");
[...]
```

(Credit to my colleague Jon Nelson for spotting the `zmq_bind()` calls with hardcoded port numbers.)

**Comment by brian-peloton** [comment]
Some of the tests have the same problem with unix domain sockets (both ones using "abstract" addresses and ones using the filesystem).

In case it helps anybody, my workaround is to use [unshare](http://man7.org/linux/man-pages/man1/unshare.1.html) to give each instance of each test its own localhost, IPC namespace, and tmpfs to put the filesystem sockets in.

**Comment by sigiesec** [comment]
Not sure if this is still an issue. There have been several changes to use ephemeral ports in the tests. Some test cases however need to test the use of specific ports.

If this is still an issue, could you explicitly list the tests that have the problem?

**Comment by bluca** [comment]
I've fixed all those that can be fixed, including IPC.
There's a couple hard coded connects left, all defined in testutil.hpp, simply because it's the only way to test some code paths. They use different ports so parallel test runs work fine.

**Comment by sigiesec** [comment]
Closing this issue as it has been resolved as far as possible.
