### ISSUE TITLE
ZMQ: Assertion failed: check () (msg.cpp:220)

### ISSUE THREAD

**Issue by billyhct** [zeromq/libzmq#1164]
Hi 

I am making a pub/sub sockets and it sends messages to mobile and subscribe message from mobile.
It works well throughout the day to pub and sub
and suddenly it crashes with msg.cpp 220 when I send out message in zeromq 4.0.4
I wrap it by JZMQ, and it got down the process.

Some forums say I may share the socket among the threads but:
- I have tried to make the process single threaded but still happen
- I have tried to make a lot of threads to use the same pub socket but I still hardly reproduce the issue

This is urgent and critical for the server.
Could you please help? any idea?

**Comment by bluca** [comment]
Closing as there was no answer to request for details in 2 years
