### ISSUE TITLE
segfault when called from pyzmq

### ISSUE THREAD

**Issue by dionyziz** [zeromq/libzmq#1175]
More details can be found here:

https://github.com/zeromq/pyzmq/issues/583

This causes the whole python instance to crash completely.

**Comment by sublee** [comment]
I have a similar issue.  `Bad file descriptor (src/signaler.cpp:301)`

**Comment by bluca** [comment]
Can you give us more details please?
Platform, versions? What is your code doing? Can you share a minimal example to reproduce the issue?

**Comment by sublee** [comment]
It was libzmq-4.1.6 on Ubuntu 16.04.

I guess this is a thread-safe issue.  There was my mistake.  So one zmq socket is touched in 2 threads each for `recv`/`send` and `bind`.

**Comment by bluca** [comment]
Yes, that is not allowed.
Is it working fine now? Can we close the issue then?

**Comment by sublee** [comment]
In my case, yes.  But I'm not sure @dionyziz also has same cause.

**Comment by sigiesec** [comment]
I'm closing the issue then.
@dionyziz if the issue is still unresolved for you, please reopen
