### ISSUE TITLE
ZeroMQ rpmbuild failure due to not finding README and libzmq.so.3.0.0 !!!

### ISSUE THREAD

**Issue by kamalsinghy** [zeromq/libzmq#1184]
Hi,
I am trying to build RPM package of zeromq-4.0.4.

I did following steps:
1. I download zeromq tar package.
2. After untar, use "rpmbuild -ba --nodeps zeromq.spec" command to create RPM package.
3. My OS is Ubuntu 12.04.
## After running the command "rpmbuild" as mentioned in point 2, I got the below errors:

make[1]: Leaving directory `/homes/kamals/rpmbuild/BUILD/zeromq-4.0.4'
- /usr/lib/rpm/brp-compress
- /usr/lib/rpm/brp-strip /usr/bin/strip
- /usr/lib/rpm/brp-strip-static-archive /usr/bin/strip
- /usr/lib/rpm/brp-strip-comment-note /usr/bin/strip /usr/bin/objdump
  Processing files: zeromq-4.0.4-1.x86_64
  error: File not found: /homes/kamals/rpmbuild/BUILDROOT/zeromq-4.0.4-1.x86_64/usr/lib64/libzmq.so.3.0.0
  Executing(%doc): /bin/sh -e /var/tmp/rpm-tmp.vPgA3P
- umask 022
- cd /homes/kamals/rpmbuild/BUILD
- cd zeromq-4.0.4
- DOCDIR=/homes/kamals/rpmbuild/BUILDROOT/zeromq-4.0.4-1.x86_64/usr/share/doc/zeromq-4.0.4
- export DOCDIR
- /bin/mkdir -p /homes/kamals/rpmbuild/BUILDROOT/zeromq-4.0.4-1.x86_64/usr/share/doc/zeromq-4.0.4
- cp -pr AUTHORS ChangeLog COPYING COPYING.LESSER NEWS README /homes/kamals/rpmbuild/BUILDROOT/zeromq-4.0.4-1.x86_64/usr/share/doc/zeromq-4.0.4
  cp: cannot stat `README': No such file or directory
  error: Bad exit status from /var/tmp/rpm-tmp.vPgA3P (%doc)

RPM build errors:
    File not found: /homes/kamals/rpmbuild/BUILDROOT/zeromq-4.0.4-1.x86_64/usr/lib64/libzmq.so.3.0.0
##     Bad exit status from /var/tmp/rpm-tmp.vPgA3P (%doc)

So as obvious from above output, there are two issues:
1. "error: File not found: /homes/kamals/rpmbuild/BUILDROOT/zeromq-4.0.4-1.x86_64/usr/lib64/libzmq.so.3.0.0"
However, when I checked my directory, I see below output:
zeromq-4.0.4$cd /homes/kamals/rpmbuild/BUILDROOT/zeromq-4.0.4-1.x86_64/usr/lib64/
lib64$ls -lrt
total 6236K
-rwxr-xr-x 1 kamals epbg 4632376 Sep 16 14:52 libzmq.so.3.1.0
lrwxrwxrwx 1 kamals epbg      15 Sep 16 14:52 libzmq.so.3 -> libzmq.so.3.1.0
lrwxrwxrwx 1 kamals epbg      15 Sep 16 14:52 libzmq.so -> libzmq.so.3.1.0
-rwxr-xr-x 1 kamals epbg     943 Sep 16 14:52 libzmq.la
drwxr-xr-x 2 kamals epbg    4096 Sep 16 14:52 pkgconfig
-rw-r--r-- 1 kamals epbg 1727342 Sep 16 14:52 libzmq.a
1. Regarding "README" file error:
   zeromq-4.0.4$cd /homes/kamals/rpmbuild/BUILD/zeromq-4.0.4/
   zeromq-4.0.4$ls -lrt
   total 2680K
   -rwxr-xr-x 1 kamals epbg     749 Nov 13  2013 version.sh
   -rw-r--r-- 1 kamals epbg    1160 Nov 13  2013 Makefile.am
   -rw-r--r-- 1 kamals epbg    1259 Nov 13  2013 MAINTAINERS
   -rw-r--r-- 1 kamals epbg    9850 Nov 13  2013 INSTALL
   -rw-r--r-- 1 kamals epbg    8504 Nov 13  2013 COPYING.LESSER
   -rw-r--r-- 1 kamals epbg   35149 Nov 13  2013 COPYING
   -rw-r--r-- 1 kamals epbg   16406 Nov 13  2013 configure.ac
   -rwxr-xr-x 1 kamals epbg    1539 Nov 13  2013 autogen.sh
   -rw-r--r-- 1 kamals epbg    4341 Nov 13  2013 AUTHORS
   -rw-r--r-- 1 kamals epbg   36546 Nov 13  2013 acinclude.m4
   -rw-r--r-- 1 kamals epbg   18691 Mar 10  2014 NEWS
   -rw-r--r-- 1 kamals epbg   44500 Mar 10  2014 aclocal.m4
   -rwxr-xr-x 1 kamals epbg  699238 Mar 10  2014 configure
   -rw-r--r-- 1 kamals epbg   25493 Mar 10  2014 Makefile.in
   drwxr-xr-x 2 kamals epbg    4096 Mar 10  2014 include
   drwxr-xr-x 3 kamals epbg    4096 Mar 10  2014 foreign
   drwxr-xr-x 2 kamals epbg    4096 Mar 10  2014 config
   drwxr-xr-x 4 kamals epbg    4096 Mar 10  2014 builds
   -rw-r--r-- 1 kamals epbg    4414 Mar 10  2014 zeromq.spec
   -rw-r--r-- 1 kamals epbg 1203976 Mar 10  2014 ChangeLog
   -rwxr-xr-x 1 kamals epbg   75399 Sep 16 14:51 config.status
   -rw-r--r-- 1 kamals epbg   25759 Sep 16 14:51 Makefile
   drwxr-xr-x 2 kamals epbg   12288 Sep 16 14:51 doc
   -rwxr-xr-x 1 kamals epbg  299423 Sep 16 14:51 libtool
   -rw-r--r-- 1 kamals epbg   76600 Sep 16 14:51 config.log
   drwxr-xr-x 4 kamals epbg   24576 Sep 16 14:51 src
   drwxr-xr-x 4 kamals epbg    4096 Sep 16 14:51 perf
   drwxr-xr-x 4 kamals epbg   12288 Sep 16 14:51 tests
   drwxr-xr-x 4 kamals epbg    4096 Sep 16 14:51 tools

I don't find any file in this directory in which the search was done.
Could anyone please help in this regard?

Thanks,
Kamal

**Comment by bluca** [comment]
Closing as the RPM builds are now working fine
