### ISSUE TITLE
Crash when receive the pub-sub message

### ISSUE THREAD

**Issue by linuxpham** [zeromq/libzmq#1192]
#0  __memcpy_ssse3_back ()

```
at ../sysdeps/x86_64/multiarch/memcpy-ssse3-back.S:2819
```
#1  0x00007ffff6243c21 in memcpy (__len=<optimized out>,

```
__src=<optimized out>, __dest=<optimized out>)
at /usr/include/x86_64-linux-gnu/bits/string3.h:52
```
#2  zmq::encoder_base_tzmq::v2_encoder_t::encode (this=0x7fffa4004b60,

```
data_=0x7fffc9dbe108, size_=<optimized out>) at encoder.hpp:113
```
#3  0x00007ffff6237ec3 in zmq::stream_engine_t::out_event (this=0x7fffbc0008e0)

```
at stream_engine.cpp:284
```
#4  0x00007ffff622f7b8 in zmq::session_base_t::read_activated (

```
this=0x7fffbc000ca0, pipe_=0x7fffa40049e0) at session_base.cpp:246
```
#5  0x00007ffff6219914 in zmq::io_thread_t::in_event (this=0x10738b0)

```
at io_thread.cpp:73
```
#6  0x00007ffff621899e in zmq::epoll_t::loop (this=0x1073b30) at epoll.cpp:165
#7  0x00007ffff623d526 in thread_routine (arg_=0x1073ba0) at thread.cpp:81
#8  0x00007ffff75a1e9a in start_thread (arg=0x7fffc9dbf700)

```
at pthread_create.c:308
```
#9  0x00007ffff5a1d3fd in clone ()

```
at ../sysdeps/unix/sysv/linux/x86_64/clone.S:112
```
#10 0x0000000000000000 in ?? ()

**Comment by bluca** [comment]
Closing as there was no answer to request for repro in 2 years
