### ISSUE TITLE
Error when building with CMake and MinGw on Windows

### ISSUE THREAD

**Issue by toussa** [zeromq/libzmq#1197]
Building libzmq with CMake (version 3.0) and MinGw (gcc 4.8.1-4) on Windows 7 produces the following error (with LIBZMQ_PEDANTIC enabled or not)

> ZeroMQ/src/signaler.cpp:365:87: error: cannot convert 'wchar_t_' to 'char_' for argument '1' to 'int snprintf(char_, size_t, const char_, ...)'

It corresponds to the following line in src/signaler.cpp:
`snprintf (mutex_name, MAX_PATH, L"Global\\zmq-signaler-port-%d", signaler_port);`

Here is the output of my CMake's configuration output:

> Eclipse version is set to 4.4 (). Adjust CMAKE_ECLIPSE_VERSION if this is wrong.
> Detected ZMQ Version - 4.1.0
> Checking whether SOCK_CLOEXEC is supported
> Checking whether SO_KEEPALIVE is supported
> Checking whether TCP_KEEPCNT is supported
> Checking whether TCP_KEEPIDLE is supported
> Checking whether TCP_KEEPINTVL is supported
> Checking whether TCP_KEEPALIVE is supported
> Could NOT find PythonInterp (missing:  PYTHON_EXECUTABLE) 
> Could NOT find AsciiDoc (missing:  ASCIIDOC_EXECUTABLE) 
> Configuring done

**Comment by bluca** [comment]
Closing as it was fixed by https://github.com/zeromq/libzmq/pull/1198/files
