### ISSUE TITLE
Build failure with Solaris 11 (x86) and 4.0.5 - undefined poller_t

### ISSUE THREAD

**Issue by kyle-downey** [zeromq/libzmq#1220]
From the looks of it no poller is defined. This is with an out-of-the-box "configure && make" on latest code from GitHub, with a newly-installed Solaris 11 image and GCC 4.5.

```
libtool: compile:  g++ -DHAVE_CONFIG_H -I. -I./src -pedantic -Werror -Wall -D_PTHREADS -D_REENTRANT -D_THREAD_SAFE -Wno-long-long -DZMQ_USE_epoll -fvisibility=hidden -g -O2 -MT src/libzmq_la-ctx.lo -MD -MP -MF src/.deps/libzmq_la-ctx.Tpo -c src/ctx.cpp  -fPIC -DPIC -o src/.libs/libzmq_la-ctx.o
In file included from src/socket_base.hpp:31:0,
                 from src/ctx.cpp:32:
src/poller.hpp:42:2: error: #error None of the ZMQ_USE_* macros defined
In file included from src/ctx.cpp:32:0:
src/socket_base.hpp:92:29: error: 'poller_t' has not been declared
src/socket_base.hpp:236:9: error: 'poller_t' does not name a type
src/socket_base.hpp:237:9: error: 'poller_t' does not name a type
In file included from src/ctx.cpp:33:0:
src/io_thread.hpp:64:9: error: 'poller_t' does not name a type
src/io_thread.hpp:78:9: error: 'poller_t' does not name a type
src/io_thread.hpp:81:9: error: 'poller_t' does not name a type
In file included from src/ctx.cpp:34:0:
src/reaper.hpp:62:9: error: 'poller_t' does not name a type
src/reaper.hpp:65:9: error: 'poller_t' does not name a type
src/ctx.cpp: In function 'int clipped_maxsocket(int)':
src/ctx.cpp:52:31: error: 'zmq::poller_t' has not been declared
src/ctx.cpp:52:60: error: 'zmq::poller_t' has not been declared
src/ctx.cpp:54:30: error: 'zmq::poller_t' has not been declared
*** Error code 1
make: Fatal error: Command failed for target `src/libzmq_la-ctx.lo'
```

**Comment by xaqq** [comment]
From the looks of this, the issue should be close since referenced commits have been merged.

**Comment by hamsetros** [comment]
Compilation break at this point  S11.2

src/tcp_address.cpp: In member function ‘int zmq::tcp_address_t::resolve_nic_name(const char*, bool, bool)’:
src/tcp_address.cpp:79:60: error: expected primary-expression before ‘)’ token
     for (int n = 0; n < (int) (ifc.lifc_len / sizeof lifreq);

...
changed to ->      for (int n = 0; n < (int) (ifc.lifc_len / sizeof (lifreq))  seems to be fixing this

**Comment by xaqq** [comment]
I suppose this part of the code is conditionally compiled for Solaris only?
If so, can you submit a PR with your working change, I don't have Solaris I can't test and make sure  don't break thing.

**Comment by hamsetros** [comment]
I could do that but honestly i'm not C++ coder so as You mentioned can't be sure it won't break anything else. Let's leave it as FYI or for someone who could test it

**Comment by xaqq** [comment]
Ok so I took a look. Adding parenthesis is safe here.

**Comment by xaqq** [comment]
Hopefully this is now fixed. Until next time :)
