### ISSUE TITLE
Hurd support?

### ISSUE THREAD

**Issue by gcsideal** [zeromq/libzmq#1228]
Hi,

Zeromq 4.0.5 fails to build on GNU/Hurd. Please see: https://buildd.debian.org/status/fetch.php?pkg=zeromq3&arch=hurd-i386&ver=4.0.5%2Bdfsg-2&stamp=1414079333
Do you plan to support this architecture? It would be nice to cover it.

Thanks for your work!

**Comment by gcsideal** [comment]
There's a propsed patch: https://bugs.debian.org/cgi-bin/bugreport.cgi?att=1;bug=799235;msg=39;filename=hurd_support.patch

**Comment by hintjens** [comment]
Looks fine; if you'd like to send that as a pull request, we'll merge it to master.

**Comment by bluca** [comment]
Closing as it was fixed in master
