### ISSUE TITLE
release 4.0.5 make on cygwin fails at curve_keygen

### ISSUE THREAD

**Issue by nmshaw** [zeromq/libzmq#1236]
make for release 4.0.5 on cygwin failed at tools/curve_keygen.  Found this link with details and workaround:
http://stackoverflow.com/questions/21017296/how-to-build-zeromq-on-windows-with-cygwin
Am on Windows 7 SP1 with cygwin: 1.7.32(0.274/5/3) 2014-08-13 23:06 x86_64 Cygwin
Did not have any problems for zmq 3.2.5 on cygwin.

Below are excerpts from the link:

make step crashes when it reaches curve_keygen.exe
Making all in tools
make[1]: Entering directory '/e/0MQ/zeromq-4.0.3/tools'
  CC       curve_keygen.o
  CCLD     curve_keygen.exe
../src/.libs/libzmq.a(libzmq_la-zmq.o):zmq.cpp:(.data+0x0): undefined reference to `__gxx_personality_seh0'
../src/.libs/libzmq.a(libzmq_la-zmq.o):zmq.cpp:(.xdata+0x30): undefined reference to`__gxx_personality_seh0'
../src/.libs/libzmq.a(libzmq_la-zmq.o):zmq.cpp:(.xdata+0x30): relocation truncated to fit: rva32 against undefined symbol `__gxx_personality_seh0'
../src/.libs/libzmq.a(libzmq_la-zmq.o):zmq.cpp:(.xdata+0x1c0): undefined reference to`__gxx_personality_seh0'
../src/.libs/libzmq.a(libzmq_la-zmq.o):zmq.cpp:(.xdata+0x1c0): relocation truncated to fit: rva32 against undefined symbol `__gxx_personality_seh0'
../src/.libs/libzmq.a(libzmq_la-zmq.o):zmq.cpp:(.rdata$.refptr._ZSt7nothrow[.refptr._ZSt7nothrow]+0x0): undefined reference to`std::nothrow'
../src/.libs/libzmq.a(libzmq_la-socket_base.o): In function `zmq::socket_base_t::parse_uri(char const*, std::string&, std::string&)':
...

here is a workaround:
mv tools/curve_keygen.c tools/curve_keygen.cpp
sed -i 's/.c>/&pp/' tools/Makefile.am
rm -f tools/.deps/curve_keygen.Po
./autogen.sh
make

**Comment by bluca** [comment]
Closing as it was fixed by https://github.com/zeromq/libzmq/pull/786 in master (4.2.x and 4.1.x)
