### ISSUE TITLE
No shared lib built on Cygwin

### ISSUE THREAD

**Issue by jpflori** [zeromq/libzmq#1263]
On Cygwin, you should pass the -no-undefined flag to libtool just as on MinGW.
Otherwise libtool will just not try to build a shared lib and build a (broken) static one instead and later on building pyzmq will fail.
I guess the proper way to fix this is to modify configure.ac to define an ON_CYGWIN variable and use it in src/Makefile.am to add this flag to libzmq_la_LDFLAGS as with ON_MINGW. 

See http://trac.sagemath.org/ticket/17333 for my original findings and the patch we use for Sage.

Best,
JP

**Comment by embray** [comment]
This turns out to be fixed by #1283, so this issue can be closed thanks.

**Comment by bluca** [comment]
Thanks for confirming
