### ISSUE TITLE
No documentation for ZMQ_XPUB_NODROP

### ISSUE THREAD

**Issue by rodgert** [zeromq/libzmq#1287]
Option was added in commit -

https://github.com/zeromq/libzmq/commit/96e29f145508f1cf4a5848c2c0d0fb83a976da0c

**Comment by xaqq** [comment]
A patch introducing documentation has been merged. Closing.

**Comment by memeplex** [comment]
The added documentation is not completely clear about what the user should expected without an understanding of zmq internals: how `xsend` is used by `send` and what `EAGAIN` means in this context: to retry sending until timeout. Please clarify the behavior facing the user of the library, not the developers.
