### ISSUE TITLE
zmq_getsockopt - ZMQ_IDENTITY_FD - unexported type

### ISSUE THREAD

**Issue by pebbe** [zeromq/libzmq#1290]
The C API reference for zmq_getsockopt, option ZMQ_IDENTITY_FD, states a return type of fd_t. This type is not available in the C API.

Also, this option is documented last. Options should be documented in alphabetical order.

**Comment by hintjens** [comment]
These are two separate issues. If you want to fix the man page, just send a
pull request (making an issue isn't needed). For the return type, afaics it
works the same was as ZMQ_FD (or should, if it doesn't).

**Comment by rodgert** [comment]
It does work the same as ZMQ_FD, I think the objection here is that it
calls out 'fd_t' as the type returned and this is not consistent with
the ZMQ_FD doc and not a type that is 'user accessible' in libzmq's public
interface.

**Comment by xaqq** [comment]
Support for `ZMQ_IDENTITY_FD` has been dropped in commit 7c0a644 and commit a55005f.
