### ISSUE TITLE
How to build with openPGM?

### ISSUE THREAD

**Issue by metadings** [zeromq/libzmq#1294]
A breaking change to 4.1 is also that the zmq_msg_t has a size of 48 bytes! I got killed by SIGSEGV!

What I did:

    ./configure --with-libsodium --with-pgm 
        sodium_LIBS=/home/metadings/Documents/libsodium/src/libsodium/.libs/libsodium.a
        pgm_LIBS=/home/metadings/Documents/libpgm/openpgm/pgm/ref/release-Linux-x86_64/libpgm.a

I also tried (and a lot of other combinations)

    ./configure --with-libsodium
        --with-pgm=/home/metadings/Documents/libpgm/openpgm/
        sodium_LIBS=/home/metadings/Documents/libsodium/src/libsodium/.libs/libsodium.a

The libpgm is built, however the flag pgm_LIBS is just ignored or whatever. It says "No package 'openpgm-5.2' found." How do I include the openpgm library now?

**Comment by metadings** [comment]
Again WASTED 5 hours for compilation! Can anybody help me?

**Comment by metadings** [comment]
I got it for Windows in VS2010, setting 

    (under ZeroMQ Options) openpgm = yes
    C/C++ additional includedirectories = $(ProjectDir)\..\..\..\..\..\openpgm\pgm\include\
    Linker additional librarypaths = $(ProjectDir)\..\..\..\..\..\openpgm\pgm\build\lib\Debug\
    Linker additional dependencies = libpgm.lib

Now going to Linux...

**Comment by jemc** [comment]
Thanks for posting the solution for future readers.
