### ISSUE TITLE
zmq_msg_t is now 48 instead of 32 chars

### ISSUE THREAD

**Issue by metadings** [zeromq/libzmq#1295]
A breaking change to 4.1 is also that the zmq_msg_t has a size of 48 bytes, instead of former 32 bytes.

**Comment by hintjens** [comment]
How does this break code? The previous size wasn't documented anywhere, was
it?

**Comment by metadings** [comment]
It broke my code with SIGSEGV in Marshal.FreeHGlobal...

**Comment by metadings** [comment]
Hello Pieter! I made a completely new clrzmq. Would you like to reference it?

     http://github.com/metadings/clrzmq/
     http://github.com/metadings/clrzmq-test/

**Comment by xaqq** [comment]
@hintjens This probably breaks is user-code wasn't recompiled I suppose.

@metadings Can you confirm that you recompiled your application using the up-to-date `zmq.h` header file (as opposed to just updating the `.so`)

**Comment by metadings** [comment]
Yes, I compiled it against libsodium 1.0.1, libpgm 5.2.122 and libzmq 4.2.0 for x86 and amd64.

**Comment by hintjens** [comment]
We can bring this into the zeromq organization on github. See
http://zeromq.org/docs:organization

Otherwise, you can certainly add it to the .Net bindings page.

**Comment by metadings** [comment]
WOW that is really cool. Sorry I have to tell you :)

**Comment by rodgert** [comment]
I've been meaning to ask this for a while, this seems as good a segue as
any -

Is there any reason to make sizeof(zmq_msg_t) anything smaller than the
size of the target platform's cache line size (e.g. 64 bytes on x86), you
are already paying the fetch cost for that number of bytes whether you use
all of them or not.

Increasing it would have at least two benefits -

* More messages would be 'VSM' messages, so it would reduce allocation
overhead a bit.
* Remove any chance of false sharing
<http://en.wikipedia.org/wiki/False_sharing> of things that are, by design,
pushed by value onto a ypipe_t<msg_t> which is shared between two threads.

The only downside I see is slightly increased memory consumption on memory
constrained applications.

**Comment by hintjens** [comment]
Seems like a good suggestion.

**Comment by rodgert** [comment]
I'll add it to my growing ZeroMQ/Azmq list of things to do :)

**Comment by hintjens** [comment]
:-)

**Comment by xaqq** [comment]
> The only downside I see is slightly increased memory consumption on memory constrained applications.

Would it be possible to make `sizeof(zmq_msg_t)` customizable to work around this issue?
This would allow people to chose between memory footprint vs performance.
Ideally, this would be chosen at compile time.

**Comment by hintjens** [comment]
Seems like real over-design, I can't imagine a system that can run libzmq
and yet be so constrained that these extra bytes per message would matter.
Tiny systems would instead use e.g. libzmtp.

**Comment by rodgert** [comment]
We already have architecture specific code for atomic operation primitives,
with a fallback for unknown architectures. I was thinking of doing
something similar for this falling back to the current size (or possibly
the x86 64 byte line size) when there is no definition. I am not sold
on making it tunable beyond that.

**Comment by xaqq** [comment]
> I can't imagine a system that can run libzmq and yet be so constrained that these extra bytes per message would matter.

You're probably right.

> I am not sold on making it tunable beyond that.

Fair enough :)

**Comment by rodgert** [comment]
A brief survey of CPUs cache line sizes - 

Intel Core - 64byte
ARM A9 - 32byte
ARM A15 - 64byte
SPARC T4/T5 - 32byte
IBM Power 128byte

It is safe I think to assume that IBM Power is a minority platform, which also doesn't fare any better with a 48 byte message length than a 64 byte message length and just set the message size to 64bytes for all platforms.

**Comment by metadings** [comment]
Won't you do this change to zeromq4-1 too, to avoid multiple changes since v3?
