### ISSUE TITLE
getpeername for tcp?

### ISSUE THREAD

**Issue by metadings** [zeromq/libzmq#1304]
I need getpeername for the StreamDealer project - is there a way to get this into libzmq, for transports that support it?

Possibly we can zmq_msg_get some ZMQ_SRCNAME ?

**Comment by hintjens** [comment]
You should send it as part of a message. You can get various properties for
a peer via zmq_msg_gets.

**Comment by metadings** [comment]
There is no documentation on zmq_msg_gets and also not like zmq_msg_get a simple switch - what properties do I get through it?

**Comment by hintjens** [comment]
Indeed, the zmq_msg_gets man page seems to be unfinished.

**Comment by rodgert** [comment]
The properties are whatever zap/zmtp props are exchanged during a
connection handshake (http://rfc.zeromq.org/spec:37 etc)

**Comment by rodgert** [comment]
I also think this is why a corresponding 'sets' message function doesn't
make much sense. This is per-connection metadata not per message.

**Comment by metadings** [comment]
Does actually use someone _gets? I don't think so, because there is no _sets, or am I wrong?

**Comment by rodgert** [comment]
Sorry, to clarify from my previous two messages -

This is not a generalized message metadata facility. The docs are woefully
inadequate on this (I will put together a PR to try and clarify this).

The metadata returned by zmq_msg_gets() is defined on a *PER CONNECTION*
basis. It comes from the properties exchanged between two peers during the
initial connection handshake, see the section on connection metadata in -

http://rfc.zeromq.org/spec:37

All messages from a given connection will have precisely the same metadata
attached.

Because this is PER CONNECTION  it makes no sense to have a zmq_msg_sets().

I also am not sure we even want a generalized PER MESSAGE metadata
facility, that what frames/parts are for.

**Comment by metadings** [comment]
it should be named zmq_socket_get and zmq_socket_gets

**Comment by rodgert** [comment]
That doesn't actually help. Sockets (e.g. ROUTER/DEALER) can have multiple
peers, so you can only really determine 'who' sent it at the point you have
a message.

**Comment by metadings** [comment]
Well there should be a zmq_msg_sets which actually adds a property by string name to a message... 

Are these properties per sequence-of-messages (more) or are these properties per message?

**Comment by xaqq** [comment]
These properties are **per connection**.

For example when using CURVE authentication, the ZAP handler can set a `User-Id` property for the connection. Then, `zmq_msg_gets()` will allow you to retrieve this `User-Id` property for every message sent by that client connection.

**Comment by rodgert** [comment]
I get that it seems like there *should* be an analogous sets operations to
zmq_msg_gets, but -

* as previously noted, this metadata is actually associated with the
connection on which the message was received.
* it is constructed exactly once during the initial connection handshake
* every single message delivered from that connection has a shared
reference to exactly the same underlying metadata dictionary

So, now, if there were a sets() -

* where do these properties go? Into the shared dictionary which is owned
by the connection?
* How do these get propagated to the remote peer? The wire protocol, as it
currently stands, has no way of representing that.
* If it could, how do you managed the merged view of connection +
per-message metadata? it significantly increases the implementation
complexity?

**Comment by rodgert** [comment]
Sorry, that last bit was a statement, not a question. You would have to
maintain a separate per-message bag of metadata and then present a merged
view of per-connection and per-message properties...and you would have to
revision the wire protocol. I don't think it is worth it as you can already
exchange any per-message application metadata as a frame in a multipart
message using whatever format makes sense for your application.

**Comment by hintjens** [comment]
Yes, we do eventually need a metadata setter, that could go on the socket
before a bind/connect. Or, perhaps, to the context.

**Comment by rodgert** [comment]
That would be doable, it just couldn't be zmq_msg_gets(). I will have a
look at what is involved in doing it.

**Comment by hintjens** [comment]
The existing zmq_setsockopt API is horrid. We could use this to start a new
API, e.g. zmq_sock_sets (socket, key, value) which takes string keys and
string values.

**Comment by rodgert** [comment]
Would the semantics of the API be that properties not recognized as options
become general metadata?

**Comment by hintjens** [comment]
On Sat, Jan 17, 2015 at 6:43 PM, Thomas Rodgers
<notifications@github.com> wrote:

> Would the semantics of the API be that properties not recognized as options
> become general metadata?

No idea :-)

Perhaps, zmq_sock_sets (sock, "meta", "lang=EN").

-Pieter

**Comment by rodgert** [comment]
That could work. Though, invariably the question will arise about the
existence of a corresponding zmq_sock_gets() and while that is easy enough
to support general options and getting any metadata set on the socket
pre-bind/connect, it wouldn't return the peer's metadata (which would still
need a call zmq_msg_gets). Not sure if this is a concern, but it might be
surprising.

**Comment by rodgert** [comment]
I am going to close the general parent issue here. I am looking at implementing a general sets facility, but it seems this issue isn't the place to capture that.

**Comment by rodgert** [comment]
would there be any objection to prefixing user set connection metadata
 with some consistent tag (e.g. "x:lang=EN")? This would allow them to be
easily distinguished from those that are part of the transport/mechanism.

**Comment by hintjens** [comment]
That is a good solution to the lack of namespace IMO. HTTP uses X- to
prefix application headers, I'd perhaps use the same convention. Or x:

**Comment by rodgert** [comment]
I'm good with following HTTP ( and SMTP for that matter) conventions,
anything prefixed 'X-*:' will be treated as a 'user' property, so not
passed, for instance to the mechanism for possible validation.

It raises an API consideration -

when issuing zmq_sock_sets(sock, "meta", "lang=EN") you know that "lang" is
a user property, so you could accept it as is, and convenience prefix with
"X-User:" so the actual exchanged property would be "X-User:lang=EN".

Though, later when latter calling zmq_msg_gets, you would have to supply
the right prefix. I'm sure that this will bite somebody at some point. I
could make the gets code search again with the default user prefix after
not finding the property.

Also, as has very recently become apparent, none of this is going to work
for STREAM sockets.

**Comment by hintjens** [comment]
Let's not force any particular convention onto the API.

And yes, it won't work with STREAM sockets, that's a given :)

**Comment by metadings** [comment]
So again, I need to call getpeername?

**Comment by rodgert** [comment]
It may be possible to support this property on STREAM sockets, I am still
looking at it.

**Comment by hintjens** [comment]
Ah, I was confusing ZMTP protocol metadata with TCP getpeername. Sorry.
