### ISSUE TITLE
Invalid argument (bundled/zeromq/src/stream_engine.cpp:831) 

### ISSUE THREAD

**Issue by nickponline** [zeromq/libzmq#1329]
I'm running `pyzmq==14.3.1` and after trying to connect a dealer socket

``` python
self.socket = self.context.socket(zmq.DEALER)
self.socket.setsockopt(zmq.IDENTITY, ID_KEY)
self.socket.connect(self.url)
```

Is seems to hang for about 16 minutes and then shows:

```
Invalid argument (bundled/zeromq/src/stream_engine.cpp:831)
```

It looks like the device running this code did not have internet connectivity, if that is relevant?

**Comment by sigiesec** [comment]
This is the source location of the assertion: https://github.com/zeromq/zeromq4-x/blob/1ac53ed1f75202bbe36dd0b409736f90984638e5/src/stream_engine.cpp#L831

@nickpoline What transport are you using resp. what is the value of self.url?

**Comment by bluca** [comment]
No answer, closing, open again if necessary
