### ISSUE TITLE
Assertion failed: !more (src/lb.cpp:100)

### ISSUE THREAD

**Issue by fwerner** [zeromq/libzmq#1338]
In a simple, high-throughput PUSH/PULL setup using multi-part messages the PULL client can provoke crashes of the PUSH service with *Assertion failed: !more (src/lb.cpp:100)* by closing the connection at any time.

I could only verify this issue when pushing multi-part messages and only between two machines, not locally. Furthermore, short first and long second parts seem to increase the probability of crashing the PUSH service. The test hosts are running Linux 2.6.32 and are connected by 10G ethernet. The issue has been tested and verified with the current master and v4.0.5 stable.

A minimal test case:

```c
// zmq_push_simple.c
#include <assert.h>
#include <zmq.h>

int main (void)
{
    int major, minor, patch;
    zmq_version(&major, &minor, &patch);
    printf("Current ØMQ version is %d.%d.%d\n", major, minor, patch);

    void *context = zmq_ctx_new();
    assert(context);

    void *socket = zmq_socket(context, ZMQ_PUSH);
    assert(socket);

    int rc = zmq_bind(socket, "tcp://*:5556");
    assert(rc == 0);

    char payload[16384] = {0};
    while (1) {
        int nbytes = zmq_send(socket, "HEADER", 6, ZMQ_SNDMORE);
        assert(nbytes != -1);

        nbytes = zmq_send(socket, payload, sizeof(payload) / sizeof(*payload), 0);
        assert(nbytes != -1);
    }

    zmq_close(socket);
    zmq_ctx_destroy(context);

    return 0;
}
```

```c
// zmq_pull_simple.c
#include <assert.h>
#include <zmq.h>

int main (void)
{
    int major, minor, patch;
    zmq_version(&major, &minor, &patch);
    printf ("Current ØMQ version is %d.%d.%d\n", major, minor, patch);

    void *context = zmq_ctx_new();
    assert(context);

    void *socket = zmq_socket(context, ZMQ_PULL);
    assert(socket);

    int rc = zmq_connect(socket, "tcp://<ip>:5556");
    assert(rc == 0);

    char buffer[16384];
    for (unsigned int i = 0; i < 100; i++) {
        int nbytes = zmq_recv(socket, buffer, sizeof(buffer) / sizeof(*buffer), 0);
        assert(nbytes != -1);
    }

    zmq_close(socket);
    zmq_ctx_destroy(context);

    return 0;
}
```

Result:

<pre>fwerner@client$ gcc -Wall -Wextra -pedantic -std=c99 $(pkg-config --cflags --libs libzmq) zmq_pull_simple.c -o zmq_pull_simple && ./zmq_pull_simple
Current ØMQ version is 4.2.0</pre>

<pre>fwerner@host$ gcc -Wall -Wextra -pedantic -std=c99 $(pkg-config --cflags --libs libzmq) zmq_push_simple.c -o zmq_push_simple && ./zmq_push_simple
Current ØMQ version is 4.2.0
Assertion failed: !more (src/lb.cpp:100)
Aborted (core dumped)</pre>

**Comment by mzakharo** [comment]
I would also like to add that if the client closes the connection while server is not pushing any data, the failure is not reproduced.  There seems to be a relationship between server being busy sending data and client disconnecting mid-stream.

**Comment by WarShoe** [comment]
Hi,

in my application I also see "Assertion failed: !more (lb.cpp:100)". The application has 1 client thread (it sends REQ), 1 worker thread (it does REP) and the main thread which waits when the client and the worker will finish. I was checking the stability of my application against interrupting the code.  The main() is doing something like that:

    for( run-many-times )
    {
        std::thread client(.....);
        std::thread worker(.....);
        usleep(some-time);
        pthread_kill(....,SIGINT);
        client.join();
        worker.join();
    }

And it asserts() with probability of ~1% per iteration. Is my code buggy or it is a ZMQ problem? I can post the full code if needed.

linux, ZMQ 4.0.4

**Comment by wcs1only** [comment]
This is quite similar to #1588 . Does the patch for #1588 fix this issue as well?

**Comment by fwerner** [comment]
Yes, the issue has been fixed in the current master. Thank you noting the similarity to #1588.
