### ISSUE TITLE
kernel-specific flags are not cacheable in configuration system

### ISSUE THREAD

**Issue by chickenkiller** [zeromq/libzmq#1343]
The file `acinclude.m4` implements macros to detect some kernel-specific flags, like `SOCK_CLOEXEC` for example. On versions v4.1.x and earlier, these macros do not cache their result nor use already cached variables.
When cross-compiling a project using the autotools, one often needs to rely on these cached variables to properly cross-compile by giving the right assumptions to the configuration system.
A commit on current development branch (9daf6dd7c4947ce74ca729de5c3cfe8cbc304702) fixes the problem, and it would be interesting to back-port it to zeromq-4-1 repository before v4.1.0 is released.

**Comment by chickenkiller** [comment]
I'll try to provide a pull request with that back-port when I have time, if no ones takes it over before...

**Comment by bluca** [comment]
Closing as this is now in the stable 4.2.x releases, so hopefully it's enough without a backport. Please do reopen and backport it to 4.1.x if still needed,

**Comment by se-lionelorry** [comment]
This is great as-is in 4.2.x releases. Thanks a lot!

**Comment by chickenkiller** [comment]
This is great as-is in 4.2.x releases. Thanks a lot!
