### ISSUE TITLE
How to backport the zmq_msg_gets "Peer-Address"?

### ISSUE THREAD

**Issue by metadings** [zeromq/libzmq#1347]
There is the following code in `libzmq`, which is not in `zeromq4-1`:

```c
// Compile metadata.
typedef metadata_t::dict_t properties_t;
properties_t properties;

// If we have a peer_address, add it to metadata
if (!peer_address.empty()) {
    properties.insert(std::make_pair("Peer-Address", peer_address));
}

// Add ZAP properties.
const properties_t& zap_properties = mechanism->get_zap_properties ();
properties.insert(zap_properties.begin (), zap_properties.end ());

// Add ZMTP properties.
const properties_t& zmtp_properties = mechanism->get_zmtp_properties ();
properties.insert(zmtp_properties.begin (), zmtp_properties.end ());
```

How to backport the Peer-Address to the following code in zeromq4-1?
```c
// Compile metadata.
typedef metadata_t::dict_t properties_t;
properties_t properties;
properties_t::const_iterator it;

// Add ZAP properties.
const properties_t& zap_properties = mechanism->get_zap_properties ();
it = zap_properties.begin ();
while (it != zap_properties.end ()) {
    properties.insert (properties_t::value_type (it->first, it->second));
    ++it;
}

// Add ZMTP properties.
const properties_t& zmtp_properties = mechanism->get_zmtp_properties ();
it = zmtp_properties.begin ();
while (it != zmtp_properties.end ()) {
    properties.insert (properties_t::value_type (it->first, it->second));
    ++it;
}
```

**Comment by rodgert** [comment]
I made the change, I'll submit a patch for 4.1

**Comment by metadings** [comment]
That was fast!! :-D

**Comment by metadings** [comment]
I'm going to compile that immediately.

**Comment by metadings** [comment]
Please push your patch...

**Comment by metadings** [comment]
Please push your patch...!

**Comment by rodgert** [comment]
I will do so today, been tied up with work commitments

**Comment by metadings** [comment]
Well... I don't get the address... doing a GetOption returns EINVAL, on both messages from STREAM.

**Comment by rodgert** [comment]
what transport are you using?

**Comment by rodgert** [comment]
FWIW, the test case for metadata does not cover STREAM sockets, so I have
no clue if the even works for that socket type yet, looking into it.

**Comment by metadings** [comment]
Hey, I'm writing to a STREAM socket over tcp:// ...

**Comment by metadings** [comment]
May I ask you, if a STREAM socket does return the correct ZMQ_SRCFD? I'm always getting an address 127.*.0.0

**Comment by metadings** [comment]
Now please watch the file [`StreamDealerDevice.cs`](https://github.com/zeromq/clrzmq4/blob/master/Devices/StreamDealerDevice.cs#L121), where I get the peer-address property... It returns null / EINVAL...
I'm trying this by using `./ZeroMQ.Test.exe --frontend=tcp://192.168.1.250 StreamDealer`

**Comment by rodgert** [comment]
Yes. I fully understand what the issue is. STREAM sockets do not *ever*
produce messages with metadata attached, because they bypass the the zmtp
handshake logic.  It is *by design* that zmq_msg_gets returns EINVAL if you
ask for a property which is not present (either because there is no
metadata at all or the requested property is not supported).

I am still working to determine if this is worth changing so that all
socket types produce metadata.

**Comment by metadings** [comment]
I'm sorry, I don't get the Peer-Address...

**Comment by rodgert** [comment]
With latest? I added tests for it to tests/test_stream and the data is
present (I have also stepped through this code path in a debugger).

**Comment by metadings** [comment]
I'm using zeromq4-1, or did you add it to libzmq?

**Comment by rodgert** [comment]
Should be in both now, and 'make check' will in fact segfault test_stream
if 'Peer-Address' is not returned (I will fix this particular behavior).

**Comment by metadings** [comment]
Yeah!! I'm getting the ip address now in frame 1!

**Comment by rodgert** [comment]
I just grabbed a clean clone of zeromq4-1 verified it both has the
necessary commits and builds and tests cleanly on both OSX and Linux.

**Comment by rodgert** [comment]
It *should* attach it to all frames. The test case covers this, see -

test_stream.cpp
<https://github.com/zeromq/zeromq4-1/blob/master/tests/test_stream.cpp>
line 81

**Comment by metadings** [comment]
I'm going to test this on Windows, currently have somebody writing an application on that computer.

**Comment by metadings** [comment]
I've updated libzmq and it's working just fine! However, the IP is going to be in the 2. frame (not the identity, but data frame).

**Comment by rodgert** [comment]
My observation has been that it is on the identity frame also.

**Comment by rodgert** [comment]
The relevant bits can be found starting at stream_engine.cpp:197
immediately after the if() is where the identity frame is created and
pushed to the stream socket. If there is to be a Peer-Address property for
STREAM sockets it is established here per connection.

**Comment by rodgert** [comment]
Hrm, I may have conflated 'identity' frame with the initial 0 length frame
on connect. Checking...

**Comment by rodgert** [comment]
I missed a case in stream_t::xrecv() I will submit a PR shortly

**Comment by metadings** [comment]
Yes, now there is
```C
const char *address_ipv4 = zmq_msg_gets (&msg, "Peer-Address");
```
received on both frames in a STREAM

**Comment by rodgert** [comment]
cool!

**Comment by metadings** [comment]
awesome :-)
