### ISSUE TITLE
zmq_unbind gives ENOENT when unbinding from an endpoint to which the socket was not bound

### ISSUE THREAD

**Issue by KeithHenrickson** [zeromq/libzmq#1353]
According to the libzmq documentation, the expected errno values for zmq_unbind are: EINVAL, ETERM, ENOTSOCK. However, by attempting to unbind from an endpoint to which the socket was never bound causes an ENOENT. I can see why this wouldn't be EINVAL, but that's the closest fit among the documented error codes.

```C
#include <thread> // for sleep
#include <zmq.h>

static void close_zero_linger(void *socket)
{
    int linger = 0;
    zmq_setsockopt(socket, ZMQ_LINGER, &linger, sizeof(linger));
    zmq_close(socket);
}

int main(void)
{
    void *ctx = zmq_ctx_new();

    void *server = zmq_socket(ctx, ZMQ_DEALER);

    int rc = zmq_unbind(server, "tcp://127.0.0.1:9998");
    if (rc != 0) {
        printf("ERROR IN UNBIND: %d\n", errno);
    }

    std::this_thread::sleep_for(std::chrono::seconds(1));

    close_zero_linger(server);

    zmq_ctx_term(ctx);
}
```

**Comment by metadings** [comment]
It's not EINVAL to unbind a valid connection identifier. I think it's correct to return ENOENT "No such file or directory". We need to update the docs...

You are unbinding something which you didn't bind... What's your application to do so?

**Comment by KeithHenrickson** [comment]
No intended application at all. I was troubleshooting a bug in our program (totally my fault, I had a 'magic' path that caused us to not do the bind operation in some % of cases), and I tripped over this because the ENOENT was not an expected return code on the unbind.

**Comment by marklakata** [comment]
This bug is 9 years old, but I don't see the documentation fix here : https://libzmq.readthedocs.io/en/zeromq4-x/zmq_bind.html  There is no listing of ENOENT as a possible failure code.

(I'm getting this code with ZMQ 4.3.5, but I have not discovered the root cause yet)
