### ISSUE TITLE
Recipe for target 'tools/curve_keygen' failing - Symbol Referencing Errors (OpenIndiana)

### ISSUE THREAD

**Issue by sm-tradeboox** [zeromq/libzmq#1372]
[admin@services ~/libzmq]$ uname -a
    SunOS services 5.11 joyent_20150205T075858Z i86pc i386 i86pc Solaris

    [admin@services ~/libzmq]$ ./autogen.sh 
    autoreconf: Entering directory `.'
    autoreconf: configure.ac: not using Gettext
    autoreconf: running: aclocal -I config --force -I config
    autoreconf: configure.ac: tracing
    autoreconf: running: libtoolize --copy --force
    libtoolize: putting auxiliary files in AC_CONFIG_AUX_DIR, `config'.
    libtoolize: copying file `config/ltmain.sh'
    libtoolize: putting macros in AC_CONFIG_MACRO_DIR, `config'.
    libtoolize: copying file `config/libtool.m4'
    libtoolize: copying file `config/ltoptions.m4'
    libtoolize: copying file `config/ltsugar.m4'
    libtoolize: copying file `config/ltversion.m4'
    libtoolize: copying file `config/lt~obsolete.m4'
    autoreconf: running: /opt/local/bin/autoconf --include=config --force
    autoreconf: running: /opt/local/bin/autoheader --include=config --force
    autoreconf: running: automake --add-missing --copy --force-missing
    configure.ac:45: installing 'config/compile'
    configure.ac:59: installing 'config/config.guess'
    configure.ac:59: installing 'config/config.sub'
    configure.ac:14: installing 'config/install-sh'
    configure.ac:14: installing 'config/missing'
    Makefile.am: installing 'config/depcomp'
    parallel-tests: installing 'config/test-driver'
    autoreconf: Leaving directory `.'
    [admin@services ~/libzmq]$ ./configure --prefix=/opt/usr
    checking for a BSD-compatible install... /opt/local/bin/ginstall -c
    checking whether build environment is sane... yes
    checking for a thread-safe mkdir -p... /opt/local/bin/mkdir -p
    checking for gawk... gawk
    checking whether make sets $(MAKE)... yes
    checking whether make supports nested variables... yes
    checking whether UID '100' is supported by ustar format... yes
    checking whether GID '10' is supported by ustar format... yes
    checking how to create a ustar tar archive... gnutar
    checking whether make supports nested variables... (cached) yes
    checking for gcc... gcc
    checking whether the C compiler works... yes
    checking for C compiler default output file name... a.out
    checking for suffix of executables... 
    checking whether we are cross compiling... no
    checking for suffix of object files... o
    checking whether we are using the GNU C compiler... yes
    checking whether gcc accepts -g... yes
    checking for gcc option to accept ISO C89... none needed
    checking whether gcc understands -c and -o together... yes
    checking for style of include used by make... GNU
    checking dependency style of gcc... gcc3
    checking for gcc option to accept ISO C99... -std=gnu99
    checking for g++... g++
    checking whether we are using the GNU C++ compiler... yes
    checking whether g++ accepts -g... yes
    checking dependency style of g++... gcc3
    checking for a sed that does not truncate output... /opt/local/bin/sed
    checking for gawk... (cached) gawk
    checking for pkg-config... /opt/local/bin/pkg-config
    checking pkg-config is at least version 0.9.0... yes
    checking for xmlto... /opt/local/bin/xmlto
    checking for asciidoc... /opt/local/bin/asciidoc
    checking build system type... x86_64-pc-solaris2.11
    checking host system type... x86_64-pc-solaris2.11
    checking how to print strings... print -r
    checking for a sed that does not truncate output... (cached) /opt/local/bin/sed
    checking for grep that handles long lines and -e... /opt/local/bin/grep
    checking for egrep... /opt/local/bin/grep -E
    checking for fgrep... /opt/local/bin/grep -F
    checking for ld used by gcc -std=gnu99... /usr/bin/ld
    checking if the linker (/usr/bin/ld) is GNU ld... no
    checking for BSD- or MS-compatible name lister (nm)... /opt/local/bin/nm -B
    checking the name lister (/opt/local/bin/nm -B) interface... BSD nm
    checking whether ln -s works... yes
    checking the maximum length of command line arguments... 786240
    checking whether the shell understands some XSI constructs... yes
    checking whether the shell understands "+="... yes
    checking how to convert x86_64-pc-solaris2.11 file names to x86_64-pc-solaris2.11 format... func_convert_file_noop
    checking how to convert x86_64-pc-solaris2.11 file names to toolchain format... func_convert_file_noop
    checking for /usr/bin/ld option to reload object files... -r
    checking for objdump... objdump
    checking how to recognize dependent libraries... pass_all
    checking for dlltool... dlltool
    checking how to associate runtime and link libraries... print -r --
    checking for ar... ar
    checking for archiver @FILE support... @
    checking for strip... strip
    checking for ranlib... ranlib
    checking command to parse /opt/local/bin/nm -B output from gcc -std=gnu99 object... ok
    checking for sysroot... no
    checking for mt... mt
    checking if mt is a manifest tool... no
    checking how to run the C preprocessor... gcc -std=gnu99 -E
    checking for ANSI C header files... yes
    checking for sys/types.h... yes
    checking for sys/stat.h... yes
    checking for stdlib.h... yes
    checking for string.h... yes
    checking for memory.h... yes
    checking for strings.h... yes
    checking for inttypes.h... yes
    checking for stdint.h... yes
    checking for unistd.h... yes
    checking for dlfcn.h... yes
    checking for objdir... .libs
    checking if gcc -std=gnu99 supports -fno-rtti -fno-exceptions... no
    checking for gcc -std=gnu99 option to produce PIC... -fPIC -DPIC
    checking if gcc -std=gnu99 PIC flag -fPIC -DPIC works... yes
    checking if gcc -std=gnu99 static flag -static works... no
    checking if gcc -std=gnu99 supports -c -o file.o... yes
    checking if gcc -std=gnu99 supports -c -o file.o... (cached) yes
    checking whether the gcc -std=gnu99 linker (/usr/bin/ld -64) supports shared libraries... yes
    checking whether -lc should be explicitly linked in... no
    checking dynamic linker characteristics... solaris2.11 ld.so
    checking how to hardcode library paths into programs... immediate
    checking whether stripping libraries is possible... yes
    checking if libtool supports shared libraries... yes
    checking whether to build shared libraries... yes
    checking whether to build static libraries... yes
    checking how to run the C++ preprocessor... g++ -E
    checking for ld used by g++... /usr/bin/ld -64
    checking if the linker (/usr/bin/ld -64) is GNU ld... no
    checking whether the g++ linker (/usr/bin/ld -64) supports shared libraries... yes
    checking for g++ option to produce PIC... -fPIC -DPIC
    checking if g++ PIC flag -fPIC -DPIC works... yes
    checking if g++ static flag -static works... no
    checking if g++ supports -c -o file.o... yes
    checking if g++ supports -c -o file.o... (cached) yes
    checking whether the g++ linker (/usr/bin/ld -64) supports shared libraries... yes
    checking dynamic linker characteristics... solaris2.11 ld.so
    checking how to hardcode library paths into programs... immediate
    checking whether the C compiler works... yes
    checking whether we are using Intel C compiler... no
    checking whether we are using Sun Studio C compiler... no
    checking whether we are using clang C compiler... no
    checking whether we are using gcc >= 4 C compiler... yes
    checking whether the C++ compiler works... yes
    checking whether we are using Intel C++ compiler... no
    checking whether we are using Sun Studio C++ compiler... no
    checking whether we are using clang C++ compiler... no
    checking whether we are using gcc >= 4 C++ compiler... yes
    checking whether to enable debugging information... no
    checking whether to enable code coverage... no
    checking if TIPC is available and supports nonblocking connect... no
    checking for socket in -lsocket... yes
    checking for gethostbyname in -lnsl... yes
    checking whether atomic operations can be used... yes
    checking for pthread_create in -lpthread... yes
    checking for clock_gettime in -lrt... yes
    checking whether C++ compiler supports -fvisibility=hidden... yes
    checking whether C++ compiler supports dso visibility... yes
    checking for asciidoc... yes
    checking for xmlto... yes
    checking whether to build documentation... yes
    checking whether to install manpages... yes
    checking for suitable polling system... using epoll
    checking for ANSI C header files... (cached) yes
    checking errno.h usability... yes
    checking errno.h presence... yes
    checking for errno.h... yes
    checking time.h usability... yes
    checking time.h presence... yes
    checking for time.h... yes
    checking for unistd.h... (cached) yes
    checking limits.h usability... yes
    checking limits.h presence... yes
    checking for limits.h... yes
    checking stddef.h usability... yes
    checking stddef.h presence... yes
    checking for stddef.h... yes
    checking for stdlib.h... (cached) yes
    checking for string.h... (cached) yes
    checking arpa/inet.h usability... yes
    checking arpa/inet.h presence... yes
    checking for arpa/inet.h... yes
    checking netinet/tcp.h usability... yes
    checking netinet/tcp.h presence... yes
    checking for netinet/tcp.h... yes
    checking netinet/in.h usability... yes
    checking netinet/in.h presence... yes
    checking for netinet/in.h... yes
    checking sys/socket.h usability... yes
    checking sys/socket.h presence... yes
    checking for sys/socket.h... yes
    checking sys/time.h usability... yes
    checking sys/time.h presence... yes
    checking for sys/time.h... yes
    checking ifaddrs.h usability... yes
    checking ifaddrs.h presence... yes
    checking for ifaddrs.h... yes
    checking sys/uio.h usability... yes
    checking sys/uio.h presence... yes
    checking for sys/uio.h... yes
    checking sys/eventfd.h usability... yes
    checking sys/eventfd.h presence... yes
    checking for sys/eventfd.h... yes
    checking whether SO_PEERCRED is declared... no
    checking whether LOCAL_PEERCRED is declared... no
    checking for stdbool.h that conforms to C99... yes
    checking for _Bool... no
    checking for an ANSI C-conforming const... yes
    checking for inline... inline
    checking for size_t... yes
    checking for ssize_t... yes
    checking whether time.h and sys/time.h may both be included... yes
    checking for uint32_t... yes
    checking for working volatile... yes
    checking for sodium... yes
    checking "with_norm_ext = no"... checking how to enable additional warnings for C++ compiler... -Wall
    checking how to turn warnings to errors in C++ compiler... -Werror
    checking how to enable strict standards compliance in C++ compiler... -pedantic
    checking whether compiler supports __atomic_Xxx intrinsics... yes
    checking return type of signal handlers... void
    checking for perror... yes
    checking for gettimeofday... yes
    checking for clock_gettime... yes
    checking for memset... yes
    checking for socket... yes
    checking for getifaddrs... yes
    checking for freeifaddrs... yes
    checking for fork... yes
    checking for posix_memalign... yes
    checking alloca.h usability... yes
    checking alloca.h presence... yes
    checking for alloca.h... yes
    checking whether SOCK_CLOEXEC is supported... yes
    checking whether SO_KEEPALIVE is supported... yes
    checking whether TCP_KEEPCNT is supported... no
    checking whether TCP_KEEPIDLE is supported... no
    checking whether TCP_KEEPINTVL is supported... yes
    checking whether TCP_KEEPALIVE is supported... no
    checking that generated files are newer than configure... done
    configure: creating ./config.status
    config.status: creating Makefile
    config.status: creating src/libzmq.pc
    config.status: creating doc/Makefile
    config.status: creating builds/msvc/Makefile
    config.status: creating builds/redhat/zeromq.spec
    config.status: creating src/platform.hpp
    config.status: executing depfiles commands
    config.status: executing libtool commands
    [admin@services ~/libzmq]$ make
    Making all in doc
    make[1]: Entering directory '/home/admin/libzmq/doc'
    asciidoc -d manpage -b docbook -f ./asciidoc.conf \
            -azmq_version=4.2.0 -ozmq_bind.xml zmq_bind.txt
    xmlto man zmq_bind.xml
    Note: Writing zmq_bind.3
    asciidoc -d manpage -b docbook -f ./asciidoc.conf \
            -azmq_version=4.2.0 -ozmq_unbind.xml zmq_unbind.txt
    xmlto man zmq_unbind.xml
    Note: Writing zmq_unbind.3
    asciidoc -d manpage -b docbook -f ./asciidoc.conf \
            -azmq_version=4.2.0 -ozmq_connect.xml zmq_connect.txt
    xmlto man zmq_connect.xml
    Note: Writing zmq_connect.3
    asciidoc -d manpage -b docbook -f ./asciidoc.conf \
            -azmq_version=4.2.0 -ozmq_disconnect.xml zmq_disconnect.txt
    xmlto man zmq_disconnect.xml
    Note: Writing zmq_disconnect.3
    asciidoc -d manpage -b docbook -f ./asciidoc.conf \
            -azmq_version=4.2.0 -ozmq_close.xml zmq_close.txt
    xmlto man zmq_close.xml
    Note: Writing zmq_close.3
    asciidoc -d manpage -b docbook -f ./asciidoc.conf \
            -azmq_version=4.2.0 -ozmq_ctx_new.xml zmq_ctx_new.txt
    xmlto man zmq_ctx_new.xml
    Note: Writing zmq_ctx_new.3
    asciidoc -d manpage -b docbook -f ./asciidoc.conf \
            -azmq_version=4.2.0 -ozmq_ctx_term.xml zmq_ctx_term.txt
    xmlto man zmq_ctx_term.xml
    Note: Writing zmq_ctx_term.3
    asciidoc -d manpage -b docbook -f ./asciidoc.conf \
            -azmq_version=4.2.0 -ozmq_ctx_get.xml zmq_ctx_get.txt
    xmlto man zmq_ctx_get.xml
    Note: Writing zmq_ctx_get.3
    asciidoc -d manpage -b docbook -f ./asciidoc.conf \
            -azmq_version=4.2.0 -ozmq_ctx_set.xml zmq_ctx_set.txt
    xmlto man zmq_ctx_set.xml
    Note: Writing zmq_ctx_set.3
    asciidoc -d manpage -b docbook -f ./asciidoc.conf \
            -azmq_version=4.2.0 -ozmq_ctx_shutdown.xml zmq_ctx_shutdown.txt
    xmlto man zmq_ctx_shutdown.xml
    Note: Writing zmq_ctx_shutdown.3
    asciidoc -d manpage -b docbook -f ./asciidoc.conf \
            -azmq_version=4.2.0 -ozmq_msg_init.xml zmq_msg_init.txt
    xmlto man zmq_msg_init.xml
    Note: Writing zmq_msg_init.3
    asciidoc -d manpage -b docbook -f ./asciidoc.conf \
            -azmq_version=4.2.0 -ozmq_msg_init_data.xml zmq_msg_init_data.txt
    xmlto man zmq_msg_init_data.xml
    Note: Writing zmq_msg_init_data.3
    asciidoc -d manpage -b docbook -f ./asciidoc.conf \
            -azmq_version=4.2.0 -ozmq_msg_init_size.xml zmq_msg_init_size.txt
    xmlto man zmq_msg_init_size.xml
    Note: Writing zmq_msg_init_size.3
    asciidoc -d manpage -b docbook -f ./asciidoc.conf \
            -azmq_version=4.2.0 -ozmq_msg_move.xml zmq_msg_move.txt
    xmlto man zmq_msg_move.xml
    Note: Writing zmq_msg_move.3
    asciidoc -d manpage -b docbook -f ./asciidoc.conf \
            -azmq_version=4.2.0 -ozmq_msg_copy.xml zmq_msg_copy.txt
    xmlto man zmq_msg_copy.xml
    Note: Writing zmq_msg_copy.3
    asciidoc -d manpage -b docbook -f ./asciidoc.conf \
            -azmq_version=4.2.0 -ozmq_msg_size.xml zmq_msg_size.txt
    xmlto man zmq_msg_size.xml
    Note: Writing zmq_msg_size.3
    asciidoc -d manpage -b docbook -f ./asciidoc.conf \
            -azmq_version=4.2.0 -ozmq_msg_data.xml zmq_msg_data.txt
    xmlto man zmq_msg_data.xml
    Note: Writing zmq_msg_data.3
    asciidoc -d manpage -b docbook -f ./asciidoc.conf \
            -azmq_version=4.2.0 -ozmq_msg_close.xml zmq_msg_close.txt
    xmlto man zmq_msg_close.xml
    Note: Writing zmq_msg_close.3
    asciidoc -d manpage -b docbook -f ./asciidoc.conf \
            -azmq_version=4.2.0 -ozmq_msg_send.xml zmq_msg_send.txt
    xmlto man zmq_msg_send.xml
    Note: Writing zmq_msg_send.3
    asciidoc -d manpage -b docbook -f ./asciidoc.conf \
            -azmq_version=4.2.0 -ozmq_msg_recv.xml zmq_msg_recv.txt
    xmlto man zmq_msg_recv.xml
    Note: Writing zmq_msg_recv.3
    asciidoc -d manpage -b docbook -f ./asciidoc.conf \
            -azmq_version=4.2.0 -ozmq_send.xml zmq_send.txt
    xmlto man zmq_send.xml
    Note: Writing zmq_send.3
    asciidoc -d manpage -b docbook -f ./asciidoc.conf \
            -azmq_version=4.2.0 -ozmq_recv.xml zmq_recv.txt
    xmlto man zmq_recv.xml
    Note: Writing zmq_recv.3
    asciidoc -d manpage -b docbook -f ./asciidoc.conf \
            -azmq_version=4.2.0 -ozmq_send_const.xml zmq_send_const.txt
    xmlto man zmq_send_const.xml
    Note: Writing zmq_send_const.3
    asciidoc -d manpage -b docbook -f ./asciidoc.conf \
            -azmq_version=4.2.0 -ozmq_msg_get.xml zmq_msg_get.txt
    xmlto man zmq_msg_get.xml
    Note: Writing zmq_msg_get.3
    asciidoc -d manpage -b docbook -f ./asciidoc.conf \
            -azmq_version=4.2.0 -ozmq_msg_set.xml zmq_msg_set.txt
    xmlto man zmq_msg_set.xml
    Note: Writing zmq_msg_set.3
    asciidoc -d manpage -b docbook -f ./asciidoc.conf \
            -azmq_version=4.2.0 -ozmq_msg_more.xml zmq_msg_more.txt
    xmlto man zmq_msg_more.xml
    Note: Writing zmq_msg_more.3
    asciidoc -d manpage -b docbook -f ./asciidoc.conf \
            -azmq_version=4.2.0 -ozmq_msg_gets.xml zmq_msg_gets.txt
    xmlto man zmq_msg_gets.xml
    Note: Writing zmq_msg_gets.3
    asciidoc -d manpage -b docbook -f ./asciidoc.conf \
            -azmq_version=4.2.0 -ozmq_getsockopt.xml zmq_getsockopt.txt
    xmlto man zmq_getsockopt.xml
    Note: Writing zmq_getsockopt.3
    asciidoc -d manpage -b docbook -f ./asciidoc.conf \
            -azmq_version=4.2.0 -ozmq_setsockopt.xml zmq_setsockopt.txt
    xmlto man zmq_setsockopt.xml
    Note: Writing zmq_setsockopt.3
    asciidoc -d manpage -b docbook -f ./asciidoc.conf \
            -azmq_version=4.2.0 -ozmq_socket.xml zmq_socket.txt
    xmlto man zmq_socket.xml
    Note: Writing zmq_socket.3
    asciidoc -d manpage -b docbook -f ./asciidoc.conf \
            -azmq_version=4.2.0 -ozmq_socket_monitor.xml zmq_socket_monitor.txt
    xmlto man zmq_socket_monitor.xml
    Note: Writing zmq_socket_monitor.3
    asciidoc -d manpage -b docbook -f ./asciidoc.conf \
            -azmq_version=4.2.0 -ozmq_poll.xml zmq_poll.txt
    xmlto man zmq_poll.xml
    Note: Writing zmq_poll.3
    asciidoc -d manpage -b docbook -f ./asciidoc.conf \
            -azmq_version=4.2.0 -ozmq_errno.xml zmq_errno.txt
    xmlto man zmq_errno.xml
    Note: Writing zmq_errno.3
    asciidoc -d manpage -b docbook -f ./asciidoc.conf \
            -azmq_version=4.2.0 -ozmq_strerror.xml zmq_strerror.txt
    xmlto man zmq_strerror.xml
    Note: Writing zmq_strerror.3
    asciidoc -d manpage -b docbook -f ./asciidoc.conf \
            -azmq_version=4.2.0 -ozmq_version.xml zmq_version.txt
    xmlto man zmq_version.xml
    Note: Writing zmq_version.3
    asciidoc -d manpage -b docbook -f ./asciidoc.conf \
            -azmq_version=4.2.0 -ozmq_sendmsg.xml zmq_sendmsg.txt
    xmlto man zmq_sendmsg.xml
    Note: Writing zmq_sendmsg.3
    asciidoc -d manpage -b docbook -f ./asciidoc.conf \
            -azmq_version=4.2.0 -ozmq_recvmsg.xml zmq_recvmsg.txt
    xmlto man zmq_recvmsg.xml
    Note: Writing zmq_recvmsg.3
    asciidoc -d manpage -b docbook -f ./asciidoc.conf \
            -azmq_version=4.2.0 -ozmq_proxy.xml zmq_proxy.txt
    xmlto man zmq_proxy.xml
    Note: Writing zmq_proxy.3
    asciidoc -d manpage -b docbook -f ./asciidoc.conf \
            -azmq_version=4.2.0 -ozmq_proxy_steerable.xml zmq_proxy_steerable.txt
    xmlto man zmq_proxy_steerable.xml
    Note: Writing zmq_proxy_steerable.3
    asciidoc -d manpage -b docbook -f ./asciidoc.conf \
            -azmq_version=4.2.0 -ozmq_z85_encode.xml zmq_z85_encode.txt
    xmlto man zmq_z85_encode.xml
    Note: Writing zmq_z85_encode.3
    asciidoc -d manpage -b docbook -f ./asciidoc.conf \
            -azmq_version=4.2.0 -ozmq_z85_decode.xml zmq_z85_decode.txt
    xmlto man zmq_z85_decode.xml
    Note: Writing zmq_z85_decode.3
    asciidoc -d manpage -b docbook -f ./asciidoc.conf \
            -azmq_version=4.2.0 -ozmq_curve_keypair.xml zmq_curve_keypair.txt
    xmlto man zmq_curve_keypair.xml
    Note: Writing zmq_curve_keypair.3
    asciidoc -d manpage -b docbook -f ./asciidoc.conf \
            -azmq_version=4.2.0 -ozmq_has.xml zmq_has.txt
    xmlto man zmq_has.xml
    Note: Writing zmq_has.3
    asciidoc -d manpage -b docbook -f ./asciidoc.conf \
            -azmq_version=4.2.0 -ozmq_atomic_counter_new.xml zmq_atomic_counter_new.txt
    xmlto man zmq_atomic_counter_new.xml
    Note: Writing zmq_atomic_counter_new.3
    asciidoc -d manpage -b docbook -f ./asciidoc.conf \
            -azmq_version=4.2.0 -ozmq_atomic_counter_set.xml zmq_atomic_counter_set.txt
    xmlto man zmq_atomic_counter_set.xml
    Note: Writing zmq_atomic_counter_set.3
    asciidoc -d manpage -b docbook -f ./asciidoc.conf \
            -azmq_version=4.2.0 -ozmq_atomic_counter_inc.xml zmq_atomic_counter_inc.txt
    xmlto man zmq_atomic_counter_inc.xml
    Note: Writing zmq_atomic_counter_inc.3
    asciidoc -d manpage -b docbook -f ./asciidoc.conf \
            -azmq_version=4.2.0 -ozmq_atomic_counter_dec.xml zmq_atomic_counter_dec.txt
    xmlto man zmq_atomic_counter_dec.xml
    Note: Writing zmq_atomic_counter_dec.3
    asciidoc -d manpage -b docbook -f ./asciidoc.conf \
            -azmq_version=4.2.0 -ozmq_atomic_counter_value.xml zmq_atomic_counter_value.txt
    xmlto man zmq_atomic_counter_value.xml
    Note: Writing zmq_atomic_counter_value.3
    asciidoc -d manpage -b docbook -f ./asciidoc.conf \
            -azmq_version=4.2.0 -ozmq_atomic_counter_destroy.xml zmq_atomic_counter_destroy.txt
    xmlto man zmq_atomic_counter_destroy.xml
    Note: Writing zmq_atomic_counter_destroy.3
    asciidoc -d manpage -b docbook -f ./asciidoc.conf \
            -azmq_version=4.2.0 -ozmq.xml zmq.txt
    xmlto man zmq.xml
    Note: Writing zmq.7
    asciidoc -d manpage -b docbook -f ./asciidoc.conf \
            -azmq_version=4.2.0 -ozmq_tcp.xml zmq_tcp.txt
    xmlto man zmq_tcp.xml
    Note: Writing zmq_tcp.7
    asciidoc -d manpage -b docbook -f ./asciidoc.conf \
            -azmq_version=4.2.0 -ozmq_pgm.xml zmq_pgm.txt
    xmlto man zmq_pgm.xml
    Note: Writing zmq_pgm.7
    asciidoc -d manpage -b docbook -f ./asciidoc.conf \
            -azmq_version=4.2.0 -ozmq_inproc.xml zmq_inproc.txt
    xmlto man zmq_inproc.xml
    Note: Writing zmq_inproc.7
    asciidoc -d manpage -b docbook -f ./asciidoc.conf \
            -azmq_version=4.2.0 -ozmq_ipc.xml zmq_ipc.txt
    xmlto man zmq_ipc.xml
    Note: Writing zmq_ipc.7
    asciidoc -d manpage -b docbook -f ./asciidoc.conf \
            -azmq_version=4.2.0 -ozmq_null.xml zmq_null.txt
    xmlto man zmq_null.xml
    Note: Writing zmq_null.7
    asciidoc -d manpage -b docbook -f ./asciidoc.conf \
            -azmq_version=4.2.0 -ozmq_plain.xml zmq_plain.txt
    xmlto man zmq_plain.xml
    Note: Writing zmq_plain.7
    asciidoc -d manpage -b docbook -f ./asciidoc.conf \
            -azmq_version=4.2.0 -ozmq_curve.xml zmq_curve.txt
    xmlto man zmq_curve.xml
    Note: Writing zmq_curve.7
    asciidoc -d manpage -b docbook -f ./asciidoc.conf \
            -azmq_version=4.2.0 -ozmq_tipc.xml zmq_tipc.txt
    xmlto man zmq_tipc.xml
    Note: Writing zmq_tipc.7
    rm zmq_atomic_counter_new.xml zmq_curve_keypair.xml zmq_msg_init_data.xml zmq_socket.xml zmq_recvmsg.xml zmq_msg_more.xml zmq_connect.xml zmq_version.xml zmq_z85_encode.xml zmq_inproc.xml zmq_msg_data.xml zmq_proxy.xml zmq_unbind.xml zmq_atomic_counter_inc.xml zmq_ctx_new.xml zmq_msg_init.xml zmq_atomic_counter_dec.xml zmq_msg_init_size.xml zmq_send.xml zmq_ipc.xml zmq_tcp.xml zmq_z85_decode.xml zmq_close.xml zmq_ctx_set.xml zmq_setsockopt.xml zmq_ctx_shutdown.xml zmq_socket_monitor.xml zmq_strerror.xml zmq.xml zmq_disconnect.xml zmq_has.xml zmq_msg_send.xml zmq_ctx_term.xml zmq_getsockopt.xml zmq_plain.xml zmq_msg_gets.xml zmq_errno.xml zmq_msg_close.xml zmq_null.xml zmq_msg_move.xml zmq_atomic_counter_set.xml zmq_msg_get.xml zmq_atomic_counter_value.xml zmq_msg_size.xml zmq_recv.xml zmq_ctx_get.xml zmq_pgm.xml zmq_proxy_steerable.xml zmq_sendmsg.xml zmq_send_const.xml zmq_msg_copy.xml zmq_bind.xml zmq_tipc.xml zmq_poll.xml zmq_curve.xml zmq_atomic_counter_destroy.xml zmq_msg_set.xml zmq_msg_recv.xml
    make[1]: Leaving directory '/home/admin/libzmq/doc'
    make[1]: Entering directory '/home/admin/libzmq'
      CXX      src/src_libzmq_la-address.lo
      CXX      src/src_libzmq_la-client.lo
      CXX      src/src_libzmq_la-clock.lo
      CXX      src/src_libzmq_la-ctx.lo
      CXX      src/src_libzmq_la-curve_client.lo
      CXX      src/src_libzmq_la-curve_server.lo
      CXX      src/src_libzmq_la-dealer.lo
      CXX      src/src_libzmq_la-devpoll.lo
      CXX      src/src_libzmq_la-dist.lo
      CXX      src/src_libzmq_la-epoll.lo
      CXX      src/src_libzmq_la-err.lo
      CXX      src/src_libzmq_la-fq.lo
      CXX      src/src_libzmq_la-gssapi_mechanism_base.lo
      CXX      src/src_libzmq_la-gssapi_client.lo
      CXX      src/src_libzmq_la-gssapi_server.lo
      CXX      src/src_libzmq_la-io_object.lo
      CXX      src/src_libzmq_la-io_thread.lo
      CXX      src/src_libzmq_la-ip.lo
      CXX      src/src_libzmq_la-ipc_address.lo
      CXX      src/src_libzmq_la-ipc_connecter.lo
      CXX      src/src_libzmq_la-ipc_listener.lo
      CXX      src/src_libzmq_la-kqueue.lo
      CXX      src/src_libzmq_la-lb.lo
      CXX      src/src_libzmq_la-mailbox.lo
      CXX      src/src_libzmq_la-mailbox_safe.lo
      CXX      src/src_libzmq_la-mechanism.lo
      CXX      src/src_libzmq_la-metadata.lo
      CXX      src/src_libzmq_la-msg.lo
      CXX      src/src_libzmq_la-mtrie.lo
      CXX      src/src_libzmq_la-norm_engine.lo
      CXX      src/src_libzmq_la-null_mechanism.lo
      CXX      src/src_libzmq_la-object.lo
      CXX      src/src_libzmq_la-options.lo
      CXX      src/src_libzmq_la-own.lo
      CXX      src/src_libzmq_la-pair.lo
      CXX      src/src_libzmq_la-pgm_receiver.lo
      CXX      src/src_libzmq_la-pgm_sender.lo
      CXX      src/src_libzmq_la-pgm_socket.lo
      CXX      src/src_libzmq_la-pipe.lo
      CXX      src/src_libzmq_la-plain_client.lo
      CXX      src/src_libzmq_la-plain_server.lo
      CXX      src/src_libzmq_la-poll.lo
      CXX      src/src_libzmq_la-poller_base.lo
      CXX      src/src_libzmq_la-proxy.lo
      CXX      src/src_libzmq_la-pub.lo
      CXX      src/src_libzmq_la-pull.lo
      CXX      src/src_libzmq_la-push.lo
      CXX      src/src_libzmq_la-random.lo
      CXX      src/src_libzmq_la-raw_decoder.lo
      CXX      src/src_libzmq_la-raw_encoder.lo
      CXX      src/src_libzmq_la-reaper.lo
      CXX      src/src_libzmq_la-rep.lo
      CXX      src/src_libzmq_la-req.lo
      CXX      src/src_libzmq_la-router.lo
      CXX      src/src_libzmq_la-select.lo
      CXX      src/src_libzmq_la-server.lo
      CXX      src/src_libzmq_la-session_base.lo
      CXX      src/src_libzmq_la-signaler.lo
      CXX      src/src_libzmq_la-socket_base.lo
      CXX      src/src_libzmq_la-socks.lo
      CXX      src/src_libzmq_la-socks_connecter.lo
      CXX      src/src_libzmq_la-stream.lo
      CXX      src/src_libzmq_la-stream_engine.lo
      CXX      src/src_libzmq_la-sub.lo
      CXX      src/src_libzmq_la-tcp.lo
      CXX      src/src_libzmq_la-tcp_address.lo
      CXX      src/src_libzmq_la-tcp_connecter.lo
      CXX      src/src_libzmq_la-tcp_listener.lo
      CXX      src/src_libzmq_la-thread.lo
      CXX      src/src_libzmq_la-tipc_address.lo
      CXX      src/src_libzmq_la-tipc_connecter.lo
      CXX      src/src_libzmq_la-tipc_listener.lo
      CXX      src/src_libzmq_la-trie.lo
      CXX      src/src_libzmq_la-v1_decoder.lo
      CXX      src/src_libzmq_la-v2_decoder.lo
      CXX      src/src_libzmq_la-v1_encoder.lo
      CXX      src/src_libzmq_la-v2_encoder.lo
      CXX      src/src_libzmq_la-xpub.lo
      CXX      src/src_libzmq_la-xsub.lo
      CXX      src/src_libzmq_la-zmq.lo
      CXX      src/src_libzmq_la-zmq_utils.lo
      CXXLD    src/libzmq.la
      CXX      tools/curve_keygen.o
      CXXLD    tools/curve_keygen
    Undefined                       first referenced
     symbol                             in file
    crypto_box_keypair                  src/.libs/libzmq.so
    crypto_box_afternm                  src/.libs/libzmq.so
    crypto_box_beforenm                 src/.libs/libzmq.so
    randombytes                         src/.libs/libzmq.so
    crypto_box_open                     src/.libs/libzmq.so
    crypto_box                          src/.libs/libzmq.so
    crypto_box_open_afternm             src/.libs/libzmq.so
    sodium_init                         src/.libs/libzmq.so
    crypto_secretbox_open               src/.libs/libzmq.so
    crypto_secretbox                    src/.libs/libzmq.so
    randombytes_close                   src/.libs/libzmq.so
    ld: fatal: symbol referencing errors. No output written to tools/.libs/curve_keygen
    collect2: error: ld returned 1 exit status
    Makefile:2555: recipe for target 'tools/curve_keygen' failed
    make[1]: *** [tools/curve_keygen] Error 1
    make[1]: Leaving directory '/home/admin/libzmq'
    Makefile:3384: recipe for target 'all-recursive' failed
    make: *** [all-recursive] Error 1

**Comment by hitstergtd** [comment]
@sm-tradeboox 
I see that the report has not been chased up or updated in a while, so I am closing it. However, if you are still able to reproduce the issue then I will re-open it.
