### ISSUE TITLE
zmq_socket options ZMQ_RCVHWM, ZMQ_SNDHWM ignored

### ISSUE THREAD

**Issue by RomanChebotarev** [zeromq/libzmq#1373]
Hi!
I use zeromq-4.0.5 library, from sources without any patches. My system is:

```
 ~ $ uname -a
Linux deb-dev-test 3.2.0-4-amd64 #1 SMP Debian 3.2.65-1+deb7u2 x86_64 GNU/Linux
 ~ $ cat /etc/debian_version 
7.8
```

I'm try to use ZMQ_RCVHWM & ZMQ_SNDHWM options on ZMQ_PAIR/ZMQ_PUSH sockets, but this has no effect.

Pubilsher code:

```
#include <iostream>
#include <zmq.hpp>

int main(int, char**) {
    zmq::context_t context (1);
    zmq::socket_t socket (context, ZMQ_PAIR);

    int HWM = 1;
    socket.setsockopt(ZMQ_SNDHWM, &HWM, sizeof(HWM));
    socket.setsockopt(ZMQ_RCVHWM, &HWM, sizeof(HWM));

    socket.bind("tcp://*:9876");

    int count = 0;
    while(true) {
        zmq::message_t msg(1024);
        socket.send(msg);
        std::cout << "count " << count << '\n';
        count++;
    }
}
```

Subscriber code:

```
#include <unistd.h>
#include <iostream>
#include <zmq.hpp>

int main(int, char**) {
    zmq::context_t context (1);

    zmq::socket_t socket (context, ZMQ_PAIR);
    int HWM = 1;
    socket.setsockopt(ZMQ_RCVHWM, &HWM, sizeof(HWM));
    socket.setsockopt(ZMQ_SNDHWM, &HWM, sizeof(HWM));

    socket.connect("tcp://127.0.0.1:9876");

    int count = 0;
    while(true) {
        zmq::message_t msg;
        socket.recv(&msg);
        std::cout << "count " << count << '\n';
        count++;
        usleep(1000000);
    }
}
```

I expect that the publisher will be blocked, after sending second message. But this doesn't happen.
Publisher example:

```
$ ./pub                                                                                         
count 0
count 1
count 2
count 3
******
count 385
count 386
count 387
count 388
^C
```

Subscriber at same moment:

```
roman@deb-dev-test.virtual cpp $ ./sub 
count 0
count 1
^C
```

What I do wrong, or this is bug?

**Comment by RomanChebotarev** [comment]
Bump! :-)

**Comment by reqshark** [comment]
yup +1

**Comment by hintjens** [comment]
What's the behavior on older versions of ZeroMQ, e.g. 2.x and 3.x?

**Comment by RomanChebotarev** [comment]
On version 3.2.5 I got same behavior.

On 2.2.0 I change:
```
    socket.setsockopt(ZMQ_SNDHWM, &HWM, sizeof(HWM));
    socket.setsockopt(ZMQ_RCVHWM, &HWM, sizeof(HWM));
```
to:
```
    socket.setsockopt(ZMQ_HWM, &HWM, sizeof(HWM));
``` 
And successful build source code, but got runtime error:
```
terminate called after throwing an instance of 'zmq::error_t'
  what():  Invalid argument
Aborted
```
On ```socket.setsockopt``` call.

**Comment by hintjens** [comment]
HWMs are approximate, due to several factors. There are network buffers,
you have sender + receiver pipes, and there are asynchronous readers and
writers. So "1" is a useless value to set. A good test should be, set to
100, and see how many messages the pipe will accept (it will be between 50
and 100, depending).

HWMs are intended to prevent memory overflow, rather than provide precise
control over how many messages go to a recipient.

**Comment by RomanChebotarev** [comment]
I set ```int HWM = 100;```, after them my publisher send 499 messages before stop sending. This is normal value?

> HWMs are intended to prevent memory overflow, rather than provide precise control over how many messages go to a recipient.

Ok, thank for explanation.

**Comment by hintjens** [comment]
On Sun, Apr 19, 2015 at 11:58 PM, RomanChebotarev
<notifications@github.com> wrote:

> I set int HWM = 100;, after them my publisher send 499 messages before stop sending. This is normal value?

This isn't normal.

I've written a very simple test case using CZMQ:

    #include <czmq.h>

    int main (void)
    {
        zsys_set_sndhwm (100);
        zsock_t *server = zsock_new_dealer ("tcp://127.0.0.1:9999");
        zsock_t *client = zsock_new_dealer ("tcp://127.0.0.1:9999");

        zframe_t *frame = zframe_new (NULL, 1024);
        int count = 0;
        while (true) {
            if (zframe_send (&frame, server, ZFRAME_REUSE + ZFRAME_DONTWAIT))
                break;
            count++;
        }
        printf ("Send %d messages\n", count);
        zsock_destroy (&server);
        zsock_destroy (&client);
        return 0;
    }

Which stops at exactly 100 messages as expected. HWM seems to work fine here...

**Comment by RomanChebotarev** [comment]
> I've written a very simple test case using CZMQ:

I builded czmq from sources for test your code example - yes, it working normally.

Ok, but this is not my case.

**Comment by hintjens** [comment]
OK, so next step is to figure out what the difference is between the two
cases.

I'd suggest changing your case to use the same flow as mine (one thread)
and see if you can still reproduce it like that.

**Comment by RomanChebotarev** [comment]
```
#include <unistd.h>
#include <iostream>
#include <zmq.hpp>

int main(int, char**) {
    zmq::context_t context (1);

    zmq::socket_t pub_socket (context, ZMQ_PAIR);

    int HWM = 100;
    pub_socket.setsockopt(ZMQ_SNDHWM, &HWM, sizeof(HWM));
    pub_socket.setsockopt(ZMQ_RCVHWM, &HWM, sizeof(HWM));

    pub_socket.bind("tcp://*:9876");

    zmq::socket_t sub_socket (context, ZMQ_PAIR);
    sub_socket.setsockopt(ZMQ_RCVHWM, &HWM, sizeof(HWM));
    sub_socket.setsockopt(ZMQ_SNDHWM, &HWM, sizeof(HWM));

    sub_socket.connect("tcp://127.0.0.1:9876");
    int pub_count = 0;
    int sub_count = 0;

    while(true) {
        zmq::message_t pub_msg(1024);

        std::cout << "Publishing message #" << pub_count << " ... " << std::endl;
        pub_socket.send(pub_msg);
        std::cout << "Publish success" << std::endl;
        ++pub_count;

        if(pub_count % 20 == 0)
        {
            zmq::message_t sub_msg(1024);
            std::cout << "Receiving message #" << sub_count << " ..." << std::endl;
            sub_socket.recv(&sub_msg);
            std::cout << "Receive success" << std::endl;
            ++sub_count;
            usleep(100000);
        }
    }
    return 0;
}
```
Result:
```
$ time ./pub-sub 
****
Publishing message #394 ... 
Publish success
Publishing message #395 ... 
Publish success
Publishing message #396 ... 
Publish success
Publishing message #397 ... 
Publish success
Publishing message #398 ... 
Publish success
Publishing message #399 ... 
Publish success
Receiving message #19 ...
Receive success
Publishing message #400 ... 
^C

real    0m2.497s
user    0m0.000s
sys     0m0.024s
```

**Comment by pijyoi** [comment]
@hintjens, there is a bug in your CZMQ code. zsock_new_dealer() does a connect, so both server and client are attempting to connect. If I change the C++ code so that both pub_socket and sub_socket connect, then the counter stops at 100.

@RomanChebotarev, if you really want to restrict the number of messages, then you would need to also set ZMQ_SNDBUF on your pub_socket and ZMQ_RCVBUF on your sub_socket to an appropriately small value.
The size of your pub_msg also matters.

**Comment by hintjens** [comment]
@pijyoi there's no bug. If you specify an endpoint the default action is connect. To force a bind you prefix the endpoint with '@'.

**Comment by pijyoi** [comment]
@hintjens, in your posted example, neither dealer socket has the @ prefix, so aren't both defaulting to connect?

**Comment by hintjens** [comment]
@pijyoi you're absolutely right. I misunderstood you, sorry. The server endpoint should start with '@'.

**Comment by phylake** [comment]
I'm seeing a related HWM issue where values below 1000 appear to be ignored. I put together a [test case and write up](https://github.com/phylake/zmq-hwm-test). I have also seen the broker in my example buffer all 100000 messages but I haven't been able to reproduce it reliably.

**Comment by phylake** [comment]
Did anyone run my test case?
