### ISSUE TITLE
Problem in Release Build of VS with clrzmq

### ISSUE THREAD

**Issue by MarkyMark2015** [zeromq/libzmq#1376]
We're testing with PUB/SUB Pattern. When compiling our VB.NET Solution in Debug-Mode, the subcriber works fine. When compiling in Releasemode, we get an Recieved-Status interrupt.

After looking around for hours we found that the "Optimization" Checkbox in the Project Settings / Compile is responsible for that. When you turn off the box, everything works fine.

In my opinion ZeroMQ/clrzmq should work with either compile options, as otherwise Release-distributed systems will fail.

**Comment by sigiesec** [comment]
Of course, ZeroMQ should work with or without optimization of your code.

There is not much information to really tell but this sounds like there is an issue in your VB.NET code, which is triggered by optimizing it.

Feel free to reopen the issue with more information.
