### ISSUE TITLE
Problem: Invalid string cast in win_error under _WIN32_WCE.

### ISSUE THREAD

**Issue by evoskuil** [zeromq/libzmq#1380]
In `err.cpp` the [following function](https://github.com/zeromq/libzmq/blob/master/src/err.cpp#L204) will produce unexpected results if called with `_WIN32_WCE` defined:

``` c
void zmq::win_error (char *buffer_, size_t buffer_size_)
{
    DWORD errcode = GetLastError ();
#if defined _WIN32_WCE
    DWORD rc = FormatMessage (FORMAT_MESSAGE_FROM_SYSTEM |
        FORMAT_MESSAGE_IGNORE_INSERTS, NULL, errcode, MAKELANGID(LANG_NEUTRAL,
        SUBLANG_DEFAULT), (LPWSTR)buffer_, buffer_size_ / sizeof(wchar_t), NULL );
#else
    DWORD rc = FormatMessageA (FORMAT_MESSAGE_FROM_SYSTEM |
        FORMAT_MESSAGE_IGNORE_INSERTS, NULL, errcode, MAKELANGID(LANG_NEUTRAL,
        SUBLANG_DEFAULT), buffer_, (DWORD) buffer_size_, NULL );
#endif
    zmq_assert (rc);
}
```

The `char` buffer can't be cast to `wchar_t*` (LPWSTR) given that the values originate from `wsa_error_no` as literal ANSI strings. Assuming that the wide version of `FormatMessageW` is required for `_WIN32_WCE` (and that WinCE is still in use) the resolution is to convert the ASCII text messages to UTF16 first, using [MultiByteToWideChar](https://msdn.microsoft.com/en-us/library/windows/desktop/dd319072%28v=vs.85%29.aspx). Otherwise `FormatMessageA` could be used given that the text is limited to ASCII.

**Comment by sigiesec** [comment]
It were great if we had unit tests below the API level to test such things.

**Comment by sigiesec** [comment]
@zeromq/libzmq-maintainers  Is WinCE a supported platform? Do we run tests anywhere on WinCE?

**Comment by bluca** [comment]
No tests, and don't know whether it's supported or not - @somdoron any idea if CE was supported at some point in time?

**Comment by somdoron** [comment]
no idea...
