### ISSUE TITLE
Thread safety implementation breaks Win32 XP builds

### ISSUE THREAD

**Issue by dmeehan1968** [zeromq/libzmq#1381]
Commit 6749c9b3eba1ad2d35942b37390c2947b55c4ac0

This uses condition variables which don't appear to be available on Windows XP.  Introduced in Vista.

When a project built with Win32 version of LIBZMQ is run on an XP system (despite modifying libzmq to use win32_v120 and project also), the following error message is produced:

"The procedure entry point InitializeConditionVariable could not be located in the dynamic link library KERNEL32.dll"

**Comment by dmeehan1968** [comment]
Commit bbdd8662bafa99584b78fe44e1a55b24b37cf740

This changes platform.hpp to redefine the value of _WIN32_WINNT macro to raise the minimum required version of Windows to Vista.

This is not the correct approach!

**Comment by dmeehan1968** [comment]
@somdoron Can you comment on this?

**Comment by somdoron** [comment]
@dmeehan1968 I actually note that as part of the pull request:
https://github.com/zeromq/libzmq/pull/1349

I think that for windows xp the thread safety should not be supported, so we can have a dummy implementation of the conditional variable that assert.

**Comment by dmeehan1968** [comment]
Thanks for the quick response.  The modifications to platform.hpp.in are not the correct way to do it (IMHO).  windows.hpp defines the minimum Windows platform version for ZMQ, and this needs to remain at XP, at least for now.

Are you in a position to revert the _WIN32_WINNT changes, and make condition_variable.hpp conditional on >=0x0600?

**Comment by somdoron** [comment]
I will try to do it over the weekend. For lower windows I need to create a dummy implementation, correct?

**Comment by dmeehan1968** [comment]
I think that would create the false impression that ZMQ is thread safe.  Im not sure if there is an alternative to condition variables for earlier Windows versions.

Perhaps a better approach would be to define ZMQ_THREAD_SAFE or similar, and for Windows builds lower than Vista set it to FALSE or undefined.  Then you can stub out the condition variable logic for that build, and at least developers have a define to test/build against.

**Comment by somdoron** [comment]
My plan: only client and server socket types are thread safe, so when trying to using those on windows xp you will get an assert.

**Comment by dmeehan1968** [comment]
That sounds good.  I have no current need for client/server socket types, just the existing (legacy) types, and those are unlikely to ever support thread safety as I understand it.

**Comment by rodgert** [comment]
Somewhat tangentially related, using std::condition_variable commits
future libzmq versions to C++11 conforming compilers and standard library
implementations. I don't know if there's been much discussion around the
ramifications of this for the varied platform targets currently supported.

**Comment by jemc** [comment]
@rodgert - Thanks for bringing this up - C++11 entanglement may also cause problems when cross-compiling to ARM.  I'd say these ramifications are definitely worth some research.

**Comment by rodgert** [comment]
FWIW I have been holding off on introducing any C++11isms in libzmq
PRs  (though I use it extensively elsewhere) because I suspect the scale of
supported platform breakage would prove 'unpopular'.

**Comment by rodgert** [comment]
Windows has had EVENT kernel objects and Set/ResetEvent
and WaitForSingleObject since (at least) NT4.0 which do roughly the
signaling I think you are after with std::condition_variable.

https://msdn.microsoft.com/en-us/library/ms682655(VS.85).aspx

There are also Posix condition variables -

https://computing.llnl.gov/tutorials/pthreads/#ConditionVariables

Neither of these are dependent on C++11 conformance, and it is likely this
should be in a similar in a similar way as the current support for atomics
in libzmq; through custom wrappers provided with the library.

**Comment by dmeehan1968** [comment]
@rodgert These commits don't use std::condition_variable, but create OS specific wrappers as zmq::condition_variable_t.  

The problem is that the Windows version used WinSDK ConditionVariable API calls, which are only available on Vista and later, hence breaking XP compatibility of libzmq.

It was compounded by another commit that overrode the defined minimum supported Windows SDK in order to allow their use, rather than making their implementation conditional on SDK version.

As their use is only related to proposed client/server socket types, they can be stubbed out or conditionally included so as not to break backwards compatibility with XP builds.  @somdoron is I hope working on that solution for a PR.

**Comment by rodgert** [comment]
Ok (replying from phone so I was ill positioned to review the code first).
If you've introduced a custom wrapper it should be possible to also support
pre-Vista Windows using EVENT objects if someone were so inclined.

**Comment by somdoron** [comment]
So we have two options to solve this: 
1. make windows xp the default and then if someone wants new socket types _WIN32_WINNT must be set to 0x0600.
2. make windos vista the minimum, if someone wants XP support _WIN32_WINNT must be set to 0x0501.

I think the second solution is better, what do you think?

**Comment by dmeehan1968** [comment]
@somdoron I don't think you can arbitrarily decide to deprecate platform support.  I certainly need XP for the foreseeable future.  Your second option doesn't cover it, because changing the macro will not allow the current code to compile.

Here are some solutions:

1. Leave it to someone else to restore XP compatibility because they have need for it
2. Rewrite zmq::condition_variable_t so that it does not break platform compatibility (e.g. use the EVENT api)
3. Write a variant of zmq::condition_variable_t that restores platform compatibility (conditional on XP/Vista)
4. Make use of zmq::condition_variable_t only where new features require it, and make those features conditional on minimum OS support.

The patch to platform.hpp.in needs to be removed because its masking the value set in windows.hpp.  This is the wrong approach.

You then need to find a way of making the zmq::condition_variable_t code compile conditionally.

If you provide a stub implementation for XP that is a no-op, I fear that you will cause more confusion later when people don't get the locking behaviour required by client/server sockets, and thread safety is silently lost.

There is a side issue here too, in that I understood that one of the ZMQ design philosophies was that locking should be done without resort to synchronisation techniques such as locks (hence why there is no condition_variable in the existing code base.  If there is, perhaps that should be used?

**Comment by somdoron** [comment]
@dmeehan1968 I think you misunderstood me. By default I want zeromq to support windows vista, while if you change the macro (or pre-processor) you will fallback to dummy condition_variable implementation that assert.

Regarding the current patch, I revert it, I wasn't aware of the windows.hpp. This is the solution I'm suggesting: https://github.com/somdoron/libzmq/commit/3bb19da47add0909de431deef6cdee5d559390c3

Regarding your bullets

2. It is very complicated to implement condition variable with EVENT, I tried that, anyway we can do it when compiling for windows xp, but I don't think there is a demand to both Windows XP and new sockets types.
3. How?
4. Only client & server sockets use the conditional variable.

As said, patch is removed.

Regarding the confusion, when specifically compiling for windows xp you will not be able to use the server and client sockets, which use the condition variable (only those sockets are thread safe).

Anyway, let me know if you are happy with the change and I will make a PR, also we discuss the change of the minimum windows version on the mailing list as well.

Regarding side issue, I don't agree, there is nothing in zeromq philosophy that say that locking shouldn't be done using synchronization techniques. in zeromq philosophy locking shouldn't be done at all, but that is true for the application level and not for the library. The library should do it in the most efficient way and conditional variable is the most efficient way. Another question is way zeromq need thread safety if locking shouldn't be done and sockets shouldn't be shared between threads. Anyway I think that question is beyond this issue, also there is a long discussion on this on the zeromq mailing list.

**Comment by somdoron** [comment]
I added a PR here:
https://github.com/zeromq/libzmq/pull/1383

We can change it back to windows xp later if we decide.
