### ISSUE TITLE
Problem: Travis-CI build qt-android fails due to certificate check

### ISSUE THREAD

**Issue by c-rack** [zeromq/libzmq#1386]
The Travis-CI build with BUILD_TYPE=qt-android fails due to `wget` error:

```
--2015-04-28 05:57:34--  https://download.libsodium.org/libsodium/releases/LATEST.tar.gz
Resolving download.libsodium.org... 91.121.49.42
Connecting to download.libsodium.org|91.121.49.42|:443... connected.
ERROR: The certificate of ‘download.libsodium.org’ is not trusted.
```
See https://travis-ci.org/zeromq/libzmq/jobs/60327672

As the certificate is generally valid, it might be a problem with Travis-CI not having installed the proper CA certificate. Running `wget`locally works without problems. I open this issue to discuss possible solutions:

1. Add `--no-check-certificate` to https://github.com/zeromq/libzmq/blob/master/builds/qt-android/build.sh#L34
2. Add certificate of download.libsodium.org to libzmq project and use it with the `--ca-certificate`
3. Open a ticket at https://github.com/travis-ci/travis-ci/issues and let Travis-CI add the CA certificate.

While (1) would solve the problem easily, it does not feel right to weaken the security check. Solution (2) adds a file to the project (the libsodium's certificate) that shouldn't be there. So I guess solution (3) will be the best one.
Any comments or suggestions?

**Comment by xaqq** [comment]
Did we make sure that the `ca-certificates` package is properly installed?

On Tue, Apr 28, 2015 at 9:40 AM, Constantin Rack <notifications@github.com>
wrote:

> The Travis-CI build with BUILD_TYPE=qt-android fails due to wget error:
>
> --2015-04-28 05:57:34--  https://download.libsodium.org/libsodium/releases/LATEST.tar.gz
> Resolving download.libsodium.org... 91.121.49.42
> Connecting to download.libsodium.org|91.121.49.42|:443... connected.
> ERROR: The certificate of ‘download.libsodium.org’ is not trusted.
>
> See https://travis-ci.org/zeromq/libzmq/jobs/60327672
>
> As the certificate is generally valid, it might be a problem with
> Travis-CI not having installed the proper CA certificate. Running wgetlocally
> works without problems. I open this issue to discuss possible solutions:
>
>    1. Add --no-check-certificate to
>    https://github.com/zeromq/libzmq/blob/master/builds/qt-android/build.sh#L34
>    2. Add certificate of download.libsodium.org to libzmq project and use
>    it with the --ca-certificate
>    3. Open a ticket at https://github.com/travis-ci/travis-ci/issues and
>    let Travis-CI add the CA certificate.
>
> While (1) would solve the problem easily, it does not feel right to weaken
> the security check. Solution (2) adds a file to the project (the
> libsodium's certificate) that shouldn't be there. So I guess solution (3)
> will be the best one.
> Any comments or suggestions?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/zeromq/libzmq/issues/1386>.
>



-- 
Kapp Arnaud - Xaqq

**Comment by c-rack** [comment]
Good catch. I don't think they are defined as a dependency in `.travis.yml`, but we could simply use the same method in qt-android build that is also used in default build (and works):

```
git clone git://github.com/jedisct1/libsodium.git
( cd libsodium; ./autogen.sh; ./configure; make check; sudo make install; sudo ldconfig )
```
See https://github.com/zeromq/libzmq/blob/master/ci_build.sh#L7-L8

At least this is not consistent. Either we should download from libsodium.org in both build types, or we should checkout from git repository instead. I would vote for the git checkout.

If no one objects, I will prepare a PR.
