### ISSUE TITLE
Problem during shutdown

### ISSUE THREAD

**Issue by ttuna** [zeromq/libzmq#1392]
Got some problems during shutdown with czmq:

![libzmq_2015-05-04_11-45-29](https://cloud.githubusercontent.com/assets/9136428/7451948/3e19b216-f257-11e4-9006-c022f7f8d849.jpg)

Seems that [#1144](https://github.com/zeromq/libzmq/issues/1144) isn't fixed yet.

First it would be great to fix the problem with `int nbytes = ::send (w, (char*) &dummy, sizeof (dummy), 0);` in `void zmq::signaler_t::send ()` (~line 170).

Maybe it's not sufficient to check `WSAGetLastError() != WSANOTINITIALISED` only in `zmq::signaler_t::~signaler_t ()` but also grant a proper `int zmq_ctx_term (void *ctx_)` execution.
( see [#1377](https://github.com/zeromq/libzmq/issues/1377) )

Next it could be necessary to check `WSAGetLastError() != WSANOTINITIALISED` before every `wsa_assert()`. ?!?

**Comment by hintjens** [comment]
These sound like good ideas. I can't help much, lacking a Windows
environment.

**Comment by ttuna** [comment]
Could be a similar problem as [#1307](https://github.com/zeromq/libzmq/issues/1307)

**Comment by metadings** [comment]
I believe you shouldn't `zmq_ctx_term`, if there was someone `zmq_ctx_shutdown`...

I am now setting `_contextPtr` to `IntPtr.Zero` in [`ZContext.Shutdown`](https://github.com/zeromq/clrzmq4/blob/master/ZContext.cs#L229), to avoid the `zmq_ctx_term`.
