### ISSUE TITLE
Tests fail to build when targeting Windows less than Vista

### ISSUE THREAD

**Issue by danriegsecker** [zeromq/libzmq#1396]
When targeting a version of Windows that is less than Windows Vista (_WIN32_WINNT < 0x0600) the security tests fail to build. Windows less than Vista does not support the use of inet_pton which is used in test_security_curve.cpp, test_security_plain.cpp, and test_security_null.cpp.

**Comment by bluca** [comment]
Fixed by https://github.com/zeromq/libzmq/pull/1397
