### ISSUE TITLE
Not getting CURVE running

### ISSUE THREAD

**Issue by metadings** [zeromq/libzmq#1407]
To become a CURVE server, the application sets the ZMQ_CURVE_SERVER option on the socket, 
	and then sets the ZMQ_CURVE_SECRETKEY option to provide the socket
	with its long-term secret key. 
	The application does not provide the socket with its long-term public key,
	which is used only by clients.

	To become a CURVE client, the application sets the ZMQ_CURVE_SERVERKEY option
	with the long-term public key of the server it intends to connect to,
	or accept connections from.
	The application then sets the ZMQ_CURVE_PUBLICKEY and ZMQ_CURVE_SECRETKEY options
	with its client long-term key pair.

I tried to set `CURVE_SECRETKEY` to 32 bytes and `CURVE_SERVER` to `1`, but the socket does return to `CURVE_SERVER` `= 0` and the other `CURVE_` options return `EINVAL`!

You may check if `zmq_getsockopt` `CURVE_SERVER` actually returns `1`. For me it doesn't, the server (!) fails using a `Console.WriteLine` `puts`

    CURVE I: cannot open client HELLO -- wrong server key?

**Comment by hintjens** [comment]
First check that you're building with libsodium; second check the libzmq selftests, particularly test_security_curve.cpp.

**Comment by metadings** [comment]
Don't know if there's an issue in between...

**Comment by metadings** [comment]
Back with a `PLAIN_USERNAME`, `PLAIN_PASSWORD` the client, and also `PLAIN_SERVER` on the server side does run...

**Comment by metadings** [comment]
Actually it works great using `PLAIN` :+1:

**Comment by hintjens** [comment]
So it's presumably that libzmq is compiled without libsodium support. This
is easy to check, run the selftests and watch for the test_security_xxx
tests.

**Comment by metadings** [comment]
Please, have a look into the [`amd64`](https://github.com/zeromq/clrzmq4/tree/master/amd64) and [`i386`](https://github.com/zeromq/clrzmq4/tree/master/amd64) folders, where I'm compiling the bytes down using VC2010 and GCC4.8.2 ... They are both compiled with `libsodium` and `libpgm` ;)
