### ISSUE TITLE
Problem: what to do when zmg_sendmsg cannot send msg initialized with zmg_msg_init_data and free_fn

### ISSUE THREAD

**Issue by Asmod4n** [zeromq/libzmq#1408]
Normally when i cannot send a ```zmq_msg_t``` i call ```zmq_msg_close``` on it, but in case of a msg initialized with ```zmq_msg_init_data``` and a free function: the free function gets called and frees the data which would normally get copied into a ```zmq_msg_t``` and you have to reconstruct the original data which can be quite slow.

**Comment by hintjens** [comment]
Can you make a simple reproducible test case for this?

**Comment by Asmod4n** [comment]
https://github.com/Asmod4n/czmq/blob/master/src/zchunk.c#L527 send a chunk anywhere ```zmq_sendmsg``` returns -1. ```zmq_msg_close``` then calls https://github.com/zeromq/libzmq/blob/master/src/msg.cpp#L152 which calls the free function and destroys the chunk.

Or am i missing something?

**Comment by Asmod4n** [comment]
Hm, i guess i can just ignore the rc of zmq_sendmsg since the msg is empty anyway?

**Comment by Asmod4n** [comment]
Or not, guess ill just don't use the auto deallocation.

**Comment by Asmod4n** [comment]
Got confused around zmq_send, closed. It should all work well :)
