### ISSUE TITLE
Problem: setting HWM after connect/bind fails silently

### ISSUE THREAD

**Issue by hintjens** [zeromq/libzmq#1420]
Solution: fail with noise, optionally, on all relevant setsockopts if a socket already has a bind or connect done on it.

Could be done either as an option on ctx "zmq_ctx_set (ctx, ZMQ_WHATEVER)", or compile time option (like the ZMQ_ACT_MILITANT option we already offer (--with-militant configure option).

**Comment by ricnewton** [comment]
Fixed by https://github.com/zeromq/libzmq/pull/1423

**Comment by jemc** [comment]
Thanks, @ricnewton
