### ISSUE TITLE
ZMQ Dealer(Client) not reconnect when Server Device Outages

### ISSUE THREAD

**Issue by loachfish** [zeromq/libzmq#1421]
using Router-Dealer in TCP/IP

Server & Client in two devices, and they connect with a USB LAN, whose power is surpported by Server Device. 

OS: client is Ubuntu 12.04 using epoll
       server is like Android

sequence:
1. start the client;
    the DEALER is try to connect, and trigger the timer event of  zmq_tcp_connecter.
2. power on the Server Device
    ping the server's ip is OK
3. start the Server 
    they are connected and communicate well.

case 1.
   4. stop the Server
       the Cient goto the timer event and reconnect
   5. start the Server
       the Client will connect to the Server,

case 2
   4. break the USB LAN
       client zmq io thread is epoll_wait block
   5. insert the USB LAN
      CLient and Server communicate well

case 3
   4. power off the Server Device
       client zmq io thread is epoll_wait block
  5. power on the Server Device
  6. start the Server
      cannot connected.

**Comment by hintjens** [comment]
This is most likely due to the client changing addresses, or the interface being destroyed and recreated. ZeroMQ's reconnect will not work in such cases.

You will probably need to add some heartbeating and timeout detection, and then close the socket and reconnect / rebind.

**Comment by loachfish** [comment]
if any signal will be catched when the connection broken?

**Comment by hintjens** [comment]
No, TCP hides this. You must do some form of heartbeating. Check the Guide
for ways of doing that.
