### ISSUE TITLE
Unable to install man pages when BUILD_DOC is not set

### ISSUE THREAD

**Issue by junovitch** [zeromq/libzmq#1429]
Currently, doc/Makefile uses a nested check for INSTALL_MAN inside of the BUILD_DOC check.

On the 4.1.1 release of zeromq/zeromq4-1, the default ./configure run will kick out the following config.log for man pages but no documentation build.
configure:18440: checking whether to build documentation
configure:18442: result: no
configure:18445: checking whether to install manpages
configure:18447: result: yes

That results in this doc/Makefile.in:
@BUILD_DOC_TRUE@@INSTALL_MAN_TRUE@dist_man_MANS = $(MAN_DOC)
@BUILD_DOC_TRUE@SUFFIXES = .html .txt .xml .3 .7

Resulting in this doc/Makefile:
#dist_man_MANS = $(MAN_DOC)
#SUFFIXES = .html .txt .xml .3 .7

This prevents the installation of man pages. Pull request is forthcoming.

**Comment by junovitch** [comment]
Thank you.  Should a separate pull request be submitted against zeromq/zeromq4-1 for the same fix referencing this issue?

**Comment by koobs** [comment]
Apparently czmq (at least 3.0.2) needs the same fix. No man pages are installed by default (tested with FreeBSD port, same symptoms as libzmq4 prior to the fix) cc @hintjens

**Comment by hintjens** [comment]
I guess all projects that inherited the libzmq build system will have the
same issue. For CZMQ et al we're using zproject, so any fix should be made
there.
