### ISSUE TITLE
ZMQ doesn't work with the raw socket in Linux but works in Windows

### ISSUE THREAD

**Issue by henrywoo** [zeromq/libzmq#1438]
I have a client program written with raw socket communicating with a server. It uses 'select' to poll the socket descriptor and get the message from the server. After getting message, I use a ZMQ socket to send the message out.

This works perfectly in windows. But in Linux, after I call the ZMQ 'send' function, I cannot receive message from the server any more. It seems the raw socket has been affected somehow.

The program is a multithread program but I have dealt with ZMQ carefully. The client program is running in a thread A and the ZMQ socket is only used by that thread A. I think I used ZMQ correctly as it is working well in Windows. But how comes the issue in Linux?

Anybody knows if this is normal? I am suspecting this is a ZMQ issue. As long as I remove the ZMQ 'send' function, the program works well. Anybody knows how to solve this issue? and why it is working well in Windows, not in Linux?

**Comment by hintjens** [comment]
Things can work by accident. Can you make a minimal test case that shows this not working? Thank you.

**Comment by henrywoo** [comment]
Do you know the quick answer if it is supposed to be working? The code is using PUS-SUB mode and opening socket in a local TCP address.

I will take me some time to write a test case. But i will try my best.

**Comment by xaqq** [comment]
> Do you know the quick answer if it is supposed to be working? 

From what I understand (reading from a standard socket, then writing to a ZMQ PUB socket) *should* work.

**Comment by henrywoo** [comment]
I tested it with a python chat server/client program. It works, but it is not multi-threaded.

I took much time trying to find a bug but failed, then I replaced the zmq code with nanomsg and it works very well. But I prefer zmq, because i am also using pyzmq and rzmq. I wish zmq could work in my program:'-(

**Comment by jemc** [comment]
@henrywoo - I'm not sure you've fully clarified your situation - if you can't show code that explains what you are doing, can you try explaining in more detail?

**Comment by henrywoo** [comment]
I found it doesn't work even in single thread situation. ZMQ creates more than then threads automatically for me. I dont use any multithread this time, and the code flow is like this:

```
create a raw socket A;
connect to a business server B;
STATE = 1
while (raw socket A is connected){
  if (STATE==1){
    send(Request 1);
  }else if (STATE==2){
    send(Request 2);
  }
  int ret = select(fd + 1, &readSet, &writeSet, &errorSet, &timeout);
  if (ret > 0){
      if (FD_ISSET(fd, &readSet)) {
        char buf[8192];
	    int nResult = receive( buf, sizeof(buf));
        if (buf is X){
          zmq.send(messageX)
          STATE=2
        }else if (buf is Y){
          STATE=3
        }else{...}
      }// socket is ready for reading
  }
}
```

After zmq.send(message), I cannot receive any new message!! The server side code is closed to me so that I cannot debug from server side. If I remove "zmq.send(message)", everything works fine. In Windows, this program works fine too.

**Comment by alvinwng** [comment]
I wonder if the problem has been solved now? The problem looks very similar to the problem I am trying to solve to make ZeroMQ calls while connected to the Interactive Brokers socket API. The code snippet you provided looks exactly the same as what their socket client example is doing! I would like to know other cases that one would want to use both sockets and ZeroMQ APIs, but couldn't seem to find anything out there. Please let me know if there is a solution. Thanks.

**Comment by TinkeringEngr** [comment]
Same problem :(
