### ISSUE TITLE
Support for SO_REUSEPORT

### ISSUE THREAD

**Issue by carun** [zeromq/libzmq#1443]
Hi, on BSD and Linux (since [kernel 3.9] (https://lwn.net/Articles/542629/)), SO_REUSEPORT socket option is available for TCP sockets which changes the way we write server applications.

I checked [tcp_listener.cpp](https://github.com/zeromq/libzmq/blob/master/src/tcp_listener.cpp) and I found that it is not supported in ØMQ.

Is there any plan to add this in future?

**Comment by hintjens** [comment]
There are no plans to add this. If you have a specific use case that does not work today, and SO_REUSEPORT for TCP solves your problem, you may make the change and send a patch.
