### ISSUE TITLE
Documentation issue: windows MinGW build instructions out of date

### ISSUE THREAD

**Issue by OpenTrading** [zeromq/libzmq#1444]
This is a documentation issue: with the web page:
http://zeromq.org/docs:windows-installations
which I think is out of date.

In the section "Installing using MinGW" it says:

```
The tools are 32-bit only so for now these instructions only describe how to install a 32-bit library.
```

Which is not longer true, because now they have 2 32 bit verions plus a 64bit version:

```
For use with Ruby 1.8.7 and 1.9.3:
    DevKit-tdm-32-4.5.2-20111229-1559-sfx.exe
For use with Ruby 2.0 and above (32bits version only):
    DevKit-mingw64-32-4.7.2-20130224-1151-sfx.exe
For use with Ruby 2.0 and above (x64 - 64bits only)
    DevKit-mingw64-64-4.7.2-20130224-1432-sfx.exe
```

Unfortunately neither of the 32bit versions build libzmq because
neither provide libsoldium, so configure fails  (didn't try 64).
So the windows MinGW build instructions on the web page fail.

Also the build requires you to run autogen.sh first, which needs to be
added to the instructions, especially as  autogen.sh also failed,
for both 32bit versions of the toolkit (didn't try 64).

I think configure also needed pkg-config too  (didn't try 64).

For what it's worth, this was run on a 32bit Linux system under Wine.

Thanks for supporting MSYS, and thanks **very much** for ZeroMQ!

**Comment by hintjens** [comment]
Would you like to edit the page to fix it?

**Comment by OpenTrading** [comment]
Precompiled libsodium binaries for Mingw32 and Mingw64 can be downloaded from https://download.libsodium.org/libsodium/releases/

**Comment by OpenTrading** [comment]
I think the MSVC section needs updating too, to show the new sub-directory structure of msvc, and also info about where libsodium comes from on Windows.

How to you checkout a specifc release from git? Is there any tagging convention for releases? If I want the exact code and project files to rebuild e.g. the 4_0_4 windows release, is there a way to do that?  The source in the binary distribution comes without the build files, so I can't build from them in Windows.
