### ISSUE TITLE
Test failure in test_monitor

### ISSUE THREAD

**Issue by tkoeppe** [zeromq/libzmq#1464]
Another tracking issue, uninvestigated: On Linux, x86-64, running `while true; do bin/test_monitor; done` will on rare occasions fail for me with this error:

```
libzmq/tests/test_monitor.cpp:130: int main(): Assertion `event == 0x0400' failed.
```

**Comment by jakirkham** [comment]
Now seeing [this failure]( https://travis-ci.org/conda-forge/zeromq-feedstock/builds/120497220#L805 ) on OS X as well.

**Comment by jimklimov** [comment]
Still happens with libzmq-4.2.3 development branch occasionally : e.g. https://travis-ci.org/jimklimov/libzmq/jobs/266318032 as of Commit 4a18f62 

````
lt-test_monitor: tests/test_monitor.cpp:128: int main(): Assertion `event == 0x0400' failed.
````

**Comment by bluca** [comment]
This should become a bit clearer since https://github.com/zeromq/libzmq/pull/2707

**Comment by sigiesec** [comment]
I now saw it in https://travis-ci.org/sigiesec/libzmq/jobs/267473020#L1189, this is called from https://github.com/zeromq/libzmq/blob/master/tests/test_monitor.cpp#L92

Actual event is ZMQ_EVENT_DISCONNECTED. I am not sure, should this be expected here, on the client side?

**Comment by bluca** [comment]
That event fires off when an error is raised in the stream engine:

https://github.com/zeromq/libzmq/blob/master/src/stream_engine.cpp#L994

There's a few cases where it can happen. If you can reproduce it, perhaps a debug print could be added to print the "reason"?

**Comment by bluca** [comment]
Or directly the backtrace

**Comment by sigiesec** [comment]
Unfortunately, I have never reproduced it locally, but I will try running it repeated with a debugger attached.

**Comment by sigiesec** [comment]
It has been running for the last 5 hours, but I never got this :(

**Comment by jimklimov** [comment]
Can you try to induce lags? It seems that many of ZMQ issues are more
probable on resource-constrained systems, with some sort of racing and/or
exceeded expectations on fixed timeframes that something should happen.
Perhaps run it in VM or under some other resource-capping system, with low
priority and portion of CPU time. Or load the CPU(s) with something else
with higher priority, like a SuperPI calculation ;)

2017-08-23 22:42 GMT+02:00 Simon Giesecke <notifications@github.com>:

**Comment by sigiesec** [comment]
I will try again running http://www.jam-software.com/heavyload/ in parallel.
