### ISSUE TITLE
How to edit installation instructions?

### ISSUE THREAD

**Issue by DenisGorbachev** [zeromq/libzmq#1473]
http://zeromq.org/intro:get-the-software

I found out that you need to run `sudo ldconfig` to get libzmq working with https://github.com/JustinTulloss/zeromq.node. How do I edit the installation instructions to add this information?

**Comment by c-rack** [comment]
@DenisGorbachev No 100% sure, but I think the zeromq website is a wiki. So you can create an account and edit the page on your own (maybe this special page is protected, but I have not checked).

See http://zeromq.org/community for a link to create an account.
Hope this helps.

**Comment by jemc** [comment]
Quoting from the linked page: (http://zeromq.org/intro:get-the-software)

> # To build on UNIX-like systems

> If you have free choice, the most comfortable OS for developing with ZeroMQ is probably Ubuntu.
 1. Make sure that `libtool`, `pkg-config`, `build-essential`, `autoconf`, and `automake` are installed.
  2. Check whether `uuid-dev` package, `uuid/e2fsprogs` RPM or equivalent on your system is installed.
  3. Unpack the `.tar.gz` source archive.
  4. Run `./configure`, followed by `make`.
  5. To install ZeroMQ system-wide run `sudo make install`.
  6. On Linux, run `sudo ldconfig` after installing ZeroMQ.

> To see configuration options, run `./configure --help`. Read `INSTALL` for more details.

Step 6 already includes the suggestion to run `sudo ldconfig`.
