### ISSUE TITLE
corruption in "zero-copy" raw_decoder for payloads larger than 8192 bytes

### ISSUE THREAD

**Issue by pijyoi** [zeromq/libzmq#1477]
Since commit 3679793, if the TCP server sends a message larger than 8192 bytes, the ZMQ_STREAM client will see zero-ed out bytes at the start of its message.
The number of zero-ed out bytes seems to correspond to "msgsize - 8192".

Some discussion of this was in #1447.

Test cases demonstrating the issue:
C++ version:
https://github.com/pijyoi/test_zmqstream/blob/master/zmqstream_corruption.cpp
Python version:
https://github.com/pijyoi/test_zmqstream/blob/master/tcpserver_zmqclient.py

**Comment by hintjens** [comment]
OK, confirmed on libzmq master. Thanks for making this test case, @pijyoi ... I was using zmq_recv and that doesn't show the same effect.

**Comment by jens-auer** [comment]
I can take a look at this, but I am kind of busy this week and won't have time on the weekend.

**Comment by pijyoi** [comment]
I think I found the typo in raw_decoder.cpp:
https://github.com/pijyoi/libzmq/commit/487f5eb6c423f0db7b1d9145cc69c7eaae01f795

@jens-auer , could you just verify that the fix looks right?

**Comment by jens-auer** [comment]
Hi,

that's definitely a bug. Does it fix the issue?  I wonder why it passed the tests before...

**Comment by kevinkreiser** [comment]
Tried it locally and it didn't fix #1447 
It definitely seems that #1477 is related but not exactly sure how yet.

**Comment by jens-auer** [comment]
Hi,

I've added the test case and fixed the issue. The patch proposed by @pijyoi pointed to the correct spot, but I overlooked the real error.

**Comment by pijyoi** [comment]
I have a doubt about in_progress.init() and the call to allocator.get_refcnt(). If the message is very small, then no zero copy is done but the side effect of get_refcnt() persists which is a pointer increment. 

So if we have a series of very small messages,  the pointer would be very far out of bounds. This would surely cause memory corruption other than the one fixed above?

For the raw decoder, space for only one refcnt is reserved.

Perhaps this would be the cause of #1447 ?

**Comment by jens-auer** [comment]
@pijyoi Mh, the idea was that the raw_decoder allocates a new buffer for every call to recv. So there should be a one-to-one relationship between recv-calls, messages and buffers. If that is not the case, then this is certainly an issue. I would add some asserts to shared_message_memory_allocator, e.g. check in create_refcnt that the pointer is still in the expected region. I will try to find some time tonight.

Could you run the test in #1447 with valgrind? This should show out-of-bound accesses as errors in the log.

**Comment by pijyoi** [comment]
Now I understand. I missed the part where the call to allocate() in get_buffer() resets msg_refcnt.
I created a small test receiving many small messages and create_refcnt() always returns the same address. No issue with valgrind either.
