### ISSUE TITLE
Compilation error: "dereferencing type-punned pointer"

### ISSUE THREAD

**Issue by danielhers** [zeromq/libzmq#1500]
During `make` I get the following error:

    src/zmq.cpp: In function 'int zmq_recviov(void*, iovec*, size_t*, int)':
    src/zmq.cpp:555:49: error: dereferencing type-punned pointer will break strict-aliasing rules [-Werror=strict-aliasing]
             recvmore = ((zmq::msg_t*) (void *) &msg)->flags () & zmq::msg_t::more;
                                                 ^
    cc1plus: all warnings being treated as errors
    make[1]: *** [src/src_libzmq_la-zmq.lo] Error 1

Here is the problematic line: https://github.com/zeromq/libzmq/blob/master/src/zmq.cpp#L555

**Comment by jemc** [comment]
@danielhers - Please check to make sure that #1501 resolves this issue for you.

**Comment by danielhers** [comment]
Yes, it does. Thank you!

**Comment by c-rack** [comment]
Merged PR #1501 resolved this issue. Thanks everyone!
