### ISSUE TITLE
Problem: there is no CI for OSX

### ISSUE THREAD

**Issue by bluca** [zeromq/libzmq#1502]
Hello,

Travis supports OSX builds as a opt-in beta: http://docs.travis-ci.com/user/multi-os/

I requested my CZMQ fork to be enabled, and I did some work in libzmq, zeromq4-x, zeromq4-1, zproject and czmq to get it to work.

In case you are interested in enabling it, I am going to submit a set of PRs to fix the travis config and the ci_build environment so that it works on both Linux and OSX. The only code changes are backporting a test timeout fix that is in libzmq but not in zeromq4-1 and zeromq4-x.

To enable OSX on a project, it is necessary to send an email to support@travis-ci.com with a link to the project, asking to be added.

Here is a CZMQ full run (with all the various ZMQ versions):

https://travis-ci.org/bluca/czmq/builds/73772078

**Comment by c-rack** [comment]
@bluca That is great. Thank you!
Do you also send the email to Travis team?

**Comment by bluca** [comment]
I think the owner/admin of the project has to do it, so I cannot.

**Comment by c-rack** [comment]
OK, I can send that mail once all PRs have been merged. I do not have write access to all zeromq4-x and zproject repos, so I wait until someone else has merged those PRs before sending the mail.

**Comment by c-rack** [comment]
All PRs are merged, so I have sent the mail to Travis-CI now.

**Comment by bluca** [comment]
Perfect! I have sent all I have got :-)

Once they enable OSX builds, from the next push it should run. Please comment here when that happens, so that in case there is any problem I can follow it. I have done many many test runs so it should be fine, fingers crossed :-)

**Comment by bluca** [comment]
@c-rack - any news from Travis about the OSX build?

**Comment by c-rack** [comment]
@bluca Did not get any response from Travis yet...

**Comment by bluca** [comment]
@c-rack - I see, too bad. I took the liberty of asking the support person who enabled it for my personal fork to have a look, let's hope it will help.

**Comment by carlad** [comment]
Hey there, Carla from Travis CI here. 

I just wanted to let you know that the following repos have been enabled for multi-os support:

https://travis-ci.org/zeromq/libzmq
https://travis-ci.org/zeromq/czmq
https://travis-ci.org/zeromq/zeromq4-1
https://travis-ci.org/zeromq/zeromq4-x

Please note that this feature is currently in beta so please let us know anything you feel can be improved or anything you miss.

Here's what to add in your `.travis.yml` : http://docs.travis-ci.com/user/multi-os/#Setting-.travis.yml

Apologies for the delay, and happy testing!

**Comment by bluca** [comment]
Thank you very much @carlad !

**Comment by carlad** [comment]
You're welcome!
