### ISSUE TITLE
builds/cmake directory missing from source downloads on http://zeromq.org/ 

### ISSUE THREAD

**Issue by mattbolgercsiro** [zeromq/libzmq#1505]
This is an issue with the source downloads available on the website rather than the source in master so sorry if this is the wrong place to submit this issue.

http://zeromq.org/intro:get-the-software - Stable Release 4.1.2 downloads are missing the builds cmake directory needed to build using CMake.

**Comment by hintjens** [comment]
Thanks for reporting this. There are other missing builds too. I'll fix
that.
