### ISSUE TITLE
Add ability to automatically recreate broken sessions

### ISSUE THREAD

**Issue by ksergey** [zeromq/libzmq#1506]
Some times I received ZMQ_EVENT_DISCONNECTED and should call zmq_disconnect/zmq_connect to recreate broken session. It's not convenient to have additional socket for that.

Could you please add ability to automatically recreate broken sessions?

**Comment by hintjens** [comment]
You do not need to call zmq_connect/disconnect again, unless there is some
other network or socket error happening. Do you have a test case?

On Tue, Aug 4, 2015 at 12:27 PM, Sergey Kovalevich <notifications@github.com

**Comment by ksergey** [comment]
I don't have a test case, because I can't reproduce. But in my production environment this happens few times per day.

**Comment by hintjens** [comment]
This patch on libzmq master may be the solution:
>
>
https://github.com/zeromq/libzmq/pull/1508

**Comment by ksergey** [comment]
I will test tomorrow. Thanks!

**Comment by ksergey** [comment]
I should continue to see ZMQ_EVENT_DISCONNECTED?

**Comment by ksergey** [comment]
latest git version broke my sub application. i mean my application receives data only ~30 sec after start, then data receiving stopped
