### ISSUE TITLE
Guide Python Async Server does not use "zmq_proxy"

### ISSUE THREAD

**Issue by drozzy** [zeromq/libzmq#1513]
The is about python guide http://zguide.zeromq.org/py:all#The-Asynchronous-Client-Server-Pattern.

Section "The Asynchronous Client/Server Pattern". The code does not correctly reflect the c-code.

The polling code in the `ServerTask` class:

    while True:
            sockets = dict(poll.poll())
            if frontend in sockets:
                ident, msg = frontend.recv_multipart()
                tprint('Server received %s id %s' % (msg, ident))
                backend.send_multipart([ident, msg])
            if backend in sockets:
                ident, msg = backend.recv_multipart()
                tprint('Sending to frontend %s id %s' % (msg, ident))
                frontend.send_multipart([ident, msg])

should be replaced with `proxy` call:

    zmq.proxy(frontend, backend)

Which can be found in `PyZMQ` binding's docs here: https://zeromq.github.io/pyzmq/api/zmq.html

That's it!

**Comment by hintjens** [comment]
Can you make a pull request with this change? Thanks!

**Comment by drozzy** [comment]
Since this is a guide bug, I'll open the issue there.
https://github.com/imatix/zguide/issues/576
