### ISSUE TITLE
Problem: make check fails

### ISSUE THREAD

**Issue by sappo** [zeromq/libzmq#1516]
I just compiled the lasted version of libzmq which works fine but compiling the tests is failing with the following error:
````
make[2]: *** No rule to make target `libzmq.la', needed by `tests/test_getsockopt_memset'.  Stop.
````
I also had a look at the latest successful travis build which contains the same error. Please have a look at https://travis-ci.org/zeromq/libzmq/jobs/75166865#L1173 on line 1173.

**Comment by sappo** [comment]
I went ahead and check the latests pull request #1476 from @hintjens which seems to solve this issue.

**Comment by c-rack** [comment]
Merged https://github.com/zeromq/libzmq/pull/1476 but the error you mentioned still appears:
https://travis-ci.org/zeromq/libzmq/jobs/75225393#L1174
