### ISSUE TITLE
libzmq-static uses wrong lib output name in MSVC CMake build

### ISSUE THREAD

**Issue by mattbolgercsiro** [zeromq/libzmq#1517]
CMakeLists.txt:592 
`OUTPUT_NAME "libzmq"` should be `OUTPUT_NAME "libzmq-static"` as is the case for non-MSVC block otherwise the static lib overwrites the shared lib causing link errors for subsequent targets (eg. local_lat)

**Comment by c-rack** [comment]
Closed by https://github.com/zeromq/libzmq/pull/1522
