### ISSUE TITLE
Problem: heap object deletion without assigning NULL to deleted object

### ISSUE THREAD

**Issue by reza-ebrahimi** [zeromq/libzmq#1524]
Problem: heap object deletion without assigning NULL to deleted object 
Solution: define a macro and use it in project in a unified manner, it helps avoiding double deletion and other similar memory corruption problems,

#define ZMQ_DELETE(p_object) \
	delete p_object; \
	p_object = 0;

I'll be commit the changes to master branch.

**Comment by hintjens** [comment]
Can you use a different naming style for internal macros? We use ZMQ_xxx
for API constants. It's dangerous and confusing to also use this style for
internal macros.

I suggest LIBZMQ_xxx for example.

**Comment by reza-ebrahimi** [comment]
@hintjens Your suggestion was accepted :)) 
but I would prefer to use in lower case zmq_delete, so please tell me which way we should go, my suggestion or your suggestion!

**Comment by hintjens** [comment]
We use uppercase for macros..

**Comment by reza-ebrahimi** [comment]
Ok, I'll change the newly added macro to LIBZMQ_XXX.
