### ISSUE TITLE
zmq crashes when calling shutdown with a pending inproc socket

### ISSUE THREAD

**Issue by ricnewton** [zeromq/libzmq#1544]
Test case:

void test_shutdown_during_pend ()
{
    void *ctx = zmq_ctx_new ();
    assert (ctx);

    // Connect first
    void *connectSocket = zmq_socket (ctx, ZMQ_PAIR);
    assert (connectSocket);
    int rc = zmq_connect (connectSocket, "inproc://cbb");
    assert (rc == 0);

	zmq_ctx_shutdown (ctx);

    // Cleanup
    rc = zmq_close (connectSocket);
    assert (rc == 0);

    rc = zmq_ctx_term (ctx);
    assert (rc == 0);
}

**Comment by c-rack** [comment]
Fixed by https://github.com/zeromq/libzmq/pull/1545.
