### ISSUE TITLE
zeromq-4.1.3 release autoconf fails with defaults if libsodium is not available

### ISSUE THREAD

**Issue by doj** [zeromq/libzmq#1556]
Unpacking the zeromq-4.1.3.tar.gz on a Linux system, which doesn't have libsodium installed, fails a simple autoconf:

````Shell
$ tar xfz zeromq-4.1.3.tar.gz
$ cd zeromq-4.1.3/
$ ./configure
....
checking for sodium... no
configure: error: Package requirements (libsodium) were not met:

No package 'libsodium' found
````

However if I manually disable the libsodium like:
$ ./configure --without-libsodium
the autoconf scripts is running just fine.

Looking at the autoconf help text:
````Shell
$ ./configure --help | grep -A 2 sodium
  --with-libsodium        require libzmq build with libsodium. Requires
                          pkg-config [default=no]
````

So it seems that currently the default autoconf behavior is to require libsodium. I expect that autoconf does not stop if libsodium is not found on the system and it's not explicitely disabled with the --without-libsodium configuration argument.

**Comment by doj** [comment]
fixing this issue is as simple as:

````patch
--- a/configure.ac
+++ b/configure.ac
@@ -418,7 +418,7 @@ have_sodium_library="no"
 AC_ARG_WITH([libsodium], [AS_HELP_STRING([--with-libsodium],
     [require libzmq build with libsodium. Requires pkg-config [default=no]])],
     [require_libsodium_ext=$withval],
-    [require_libsodium_ext=yes])
+    [require_libsodium_ext=no])
 
 # conditionally require libsodium package
 if test "x$require_libsodium_ext" != "xno"; then
````

**Comment by hintjens** [comment]
I think the goal here is to force security into the build by default.

**Comment by jemc** [comment]
I would agree - so what needs fixing is the autoconf help text, not the default behavior.
