### ISSUE TITLE
Request to increase FD_SETSIZE again

### ISSUE THREAD

**Issue by slishak** [zeromq/libzmq#1559]
I am having a very similar problem to https://github.com/zeromq/libzmq/issues/1165. I'm using an IPython cluster, and after about 140 engines have connected, ipcontroller exits with the following message:

Assertion failed: fds.size () <= FD_SETSIZE (bundled\zeromq\src\select.cpp:79)

I'm using pyzmq 14.7.0, which is bundled with libzmq 4.1.2. From https://github.com/zeromq/libzmq/pull/1166, I understand that libzmq 4.1 should have FD_SETSIZE increased to 4096 from 1024.

I think the difference between my problem and the original problem is that I have `c.IPControllerApp.use_threads = True` in my ipcontroller_config.py. I guess that means I have four times as many socket connections per process, as otherwise there would be four scheduler processes. The reason it's set up this way is that I'm deploying the IPython cluster to another cluster - I don't want any job (including controllers and engines) to utilise more than one CPU, and I was hoping the GIL would mean that if I use threads, this could be ensured (please correct me if I'm wrong, as I'm aware the schedulers are not actually Python processes by default).

Do you think it's a good idea to further raise the limit as @hintjens suggested? Or is my use case asking for too much? In theory I have enough resource to start over a thousand engines, and I would like to try this, but I'd assume this is well above the intended usage of the IPython cluster.

I haven't experimented with increasing FD_SETSIZE myself as I'm one of those previously mentioned Windows users who are reluctant to spend time playing with compilers...

**Comment by hintjens** [comment]
Well, to start with experiment with a higher FD_SETSIZE (it's a single
change in the project settings), to see if it fixes your case. If it does,
we can discuss raising it again (I've never seen proof that the limit
should be anything less than the OS maximum).

**Comment by slishak** [comment]
As expected, I'm encountering some compilation issues... I'm trying to compile libzmq using Visual C++ 2008, but I'm getting a similar message to https://github.com/zeromq/zeromq4-x/issues/5

```
c:\users\sam.lishak\documents\libzmq-master\include\zmq.h(88) : fatal error C1083: Cannot open include file: 'stdint.h': No such file or directory
```

I tried to follow the advice here http://stackoverflow.com/questions/126279/c99-stdint-h-header-and-ms-visual-studio and download the header from Google Code, but using that caused conflicts with the already existing stdint.hpp in libzmq.

**Comment by hintjens** [comment]
Can you try removing the stdint.h you downloaded, and then edit zmq.h to
use the same construct as stdint.hpp, lines 39-70?

**Comment by slishak** [comment]
That fixed it and allowed the code to compile, however it's now failing to link with a load of unresolved external symbols. Any ideas?

```
1>Linking...
1>   Creating library ../../../../lib/libzmq.lib and object ../../../../lib/libzmq.exp
1>raw_decoder.obj : error LNK2019: unresolved external symbol "public: __thiscall zmq::shared_message_memory_allocator::~shared_message_memory_allocator(void)" (??1shared_message_memory_allocator@zmq@@QAE@XZ) referenced in function __unwindfunclet$??0raw_decoder_t@zmq@@QAE@I@Z$0
1>v2_decoder.obj : error LNK2001: unresolved external symbol "public: __thiscall zmq::shared_message_memory_allocator::~shared_message_memory_allocator(void)" (??1shared_message_memory_allocator@zmq@@QAE@XZ)
1>raw_decoder.obj : error LNK2019: unresolved external symbol "public: __thiscall zmq::shared_message_memory_allocator::shared_message_memory_allocator(unsigned int,unsigned int)" (??0shared_message_memory_allocator@zmq@@QAE@II@Z) referenced in function "public: __thiscall zmq::raw_decoder_t::raw_decoder_t(unsigned int)" (??0raw_decoder_t@zmq@@QAE@I@Z)
1>raw_decoder.obj : error LNK2019: unresolved external symbol "public: unsigned int __thiscall zmq::shared_message_memory_allocator::size(void)const " (?size@shared_message_memory_allocator@zmq@@QBEIXZ) referenced in function "public: virtual void __thiscall zmq::raw_decoder_t::get_buffer(unsigned char * *,unsigned int *)" (?get_buffer@raw_decoder_t@zmq@@UAEXPAPAEPAI@Z)
1>v2_decoder.obj : error LNK2001: unresolved external symbol "public: unsigned int __thiscall zmq::shared_message_memory_allocator::size(void)const " (?size@shared_message_memory_allocator@zmq@@QBEIXZ)
1>raw_decoder.obj : error LNK2019: unresolved external symbol "public: unsigned char * __thiscall zmq::shared_message_memory_allocator::allocate(void)" (?allocate@shared_message_memory_allocator@zmq@@QAEPAEXZ) referenced in function "public: virtual void __thiscall zmq::raw_decoder_t::get_buffer(unsigned char * *,unsigned int *)" (?get_buffer@raw_decoder_t@zmq@@UAEXPAPAEPAI@Z)
1>v2_decoder.obj : error LNK2001: unresolved external symbol "public: unsigned char * __thiscall zmq::shared_message_memory_allocator::allocate(void)" (?allocate@shared_message_memory_allocator@zmq@@QAEPAEXZ)
1>raw_decoder.obj : error LNK2019: unresolved external symbol "public: unsigned char * __thiscall zmq::shared_message_memory_allocator::release(void)" (?release@shared_message_memory_allocator@zmq@@QAEPAEXZ) referenced in function "public: virtual int __thiscall zmq::raw_decoder_t::decode(unsigned char const *,unsigned int,unsigned int &)" (?decode@raw_decoder_t@zmq@@UAEHPBEIAAI@Z)
1>raw_decoder.obj : error LNK2019: unresolved external symbol "public: static void __cdecl zmq::shared_message_memory_allocator::call_dec_ref(void *,void *)" (?call_dec_ref@shared_message_memory_allocator@zmq@@SAXPAX0@Z) referenced in function "public: virtual int __thiscall zmq::raw_decoder_t::decode(unsigned char const *,unsigned int,unsigned int &)" (?decode@raw_decoder_t@zmq@@UAEHPBEIAAI@Z)
1>v2_decoder.obj : error LNK2001: unresolved external symbol "public: static void __cdecl zmq::shared_message_memory_allocator::call_dec_ref(void *,void *)" (?call_dec_ref@shared_message_memory_allocator@zmq@@SAXPAX0@Z)
1>session_base.obj : error LNK2019: unresolved external symbol "public: __thiscall zmq::socks_connecter_t::socks_connecter_t(class zmq::io_thread_t *,class zmq::session_base_t *,struct zmq::options_t const &,struct zmq::address_t *,struct zmq::address_t *,bool)" (??0socks_connecter_t@zmq@@QAE@PAVio_thread_t@1@PAVsession_base_t@1@ABUoptions_t@1@PAUaddress_t@1@3_N@Z) referenced in function "private: void __thiscall zmq::session_base_t::start_connecting(bool)" (?start_connecting@session_base_t@zmq@@AAEX_N@Z)
1>socket_base.obj : error LNK2019: unresolved external symbol "public: __thiscall zmq::client_t::client_t(class zmq::ctx_t *,unsigned int,int)" (??0client_t@zmq@@QAE@PAVctx_t@1@IH@Z) referenced in function "public: static class zmq::socket_base_t * __cdecl zmq::socket_base_t::create(int,class zmq::ctx_t *,unsigned int,int)" (?create@socket_base_t@zmq@@SAPAV12@HPAVctx_t@2@IH@Z)
1>socket_base.obj : error LNK2019: unresolved external symbol "public: __thiscall zmq::server_t::server_t(class zmq::ctx_t *,unsigned int,int)" (??0server_t@zmq@@QAE@PAVctx_t@1@IH@Z) referenced in function "public: static class zmq::socket_base_t * __cdecl zmq::socket_base_t::create(int,class zmq::ctx_t *,unsigned int,int)" (?create@socket_base_t@zmq@@SAPAV12@HPAVctx_t@2@IH@Z)
1>socket_base.obj : error LNK2019: unresolved external symbol "public: __thiscall zmq::mailbox_safe_t::mailbox_safe_t(class zmq::mutex_t *)" (??0mailbox_safe_t@zmq@@QAE@PAVmutex_t@1@@Z) referenced in function "protected: __thiscall zmq::socket_base_t::socket_base_t(class zmq::ctx_t *,unsigned int,int,bool)" (??0socket_base_t@zmq@@IAE@PAVctx_t@1@IH_N@Z)
1>socket_base.obj : error LNK2019: unresolved external symbol "public: void __thiscall zmq::mailbox_safe_t::add_signaler(class zmq::signaler_t *)" (?add_signaler@mailbox_safe_t@zmq@@QAEXPAVsignaler_t@2@@Z) referenced in function "public: int __thiscall zmq::socket_base_t::add_signaler(class zmq::signaler_t *)" (?add_signaler@socket_base_t@zmq@@QAEHPAVsignaler_t@2@@Z)
1>socket_base.obj : error LNK2019: unresolved external symbol "public: void __thiscall zmq::mailbox_safe_t::remove_signaler(class zmq::signaler_t *)" (?remove_signaler@mailbox_safe_t@zmq@@QAEXPAVsignaler_t@2@@Z) referenced in function "public: int __thiscall zmq::socket_base_t::remove_signaler(class zmq::signaler_t *)" (?remove_signaler@socket_base_t@zmq@@QAEHPAVsignaler_t@2@@Z)
1>v2_decoder.obj : error LNK2019: unresolved external symbol "public: __thiscall zmq::shared_message_memory_allocator::shared_message_memory_allocator(unsigned int)" (??0shared_message_memory_allocator@zmq@@QAE@I@Z) referenced in function "public: __thiscall zmq::v2_decoder_t::v2_decoder_t(unsigned int,__int64)" (??0v2_decoder_t@zmq@@QAE@I_J@Z)
1>v2_decoder.obj : error LNK2019: unresolved external symbol "public: void __thiscall zmq::shared_message_memory_allocator::inc_ref(void)" (?inc_ref@shared_message_memory_allocator@zmq@@QAEXXZ) referenced in function "private: int __thiscall zmq::v2_decoder_t::size_ready(unsigned __int64,unsigned char const *)" (?size_ready@v2_decoder_t@zmq@@AAEH_KPBE@Z)
1>v2_decoder.obj : error LNK2019: unresolved external symbol "public: unsigned char * __thiscall zmq::shared_message_memory_allocator::data(void)" (?data@shared_message_memory_allocator@zmq@@QAEPAEXZ) referenced in function "private: int __thiscall zmq::v2_decoder_t::size_ready(unsigned __int64,unsigned char const *)" (?size_ready@v2_decoder_t@zmq@@AAEH_KPBE@Z)
1>v2_decoder.obj : error LNK2019: unresolved external symbol "public: void __thiscall zmq::shared_message_memory_allocator::deallocate(void)" (?deallocate@shared_message_memory_allocator@zmq@@QAEXXZ) referenced in function "public: virtual __thiscall zmq::decoder_base_t<class zmq::v2_decoder_t,class zmq::shared_message_memory_allocator>::~decoder_base_t<class zmq::v2_decoder_t,class zmq::shared_message_memory_allocator>(void)" (??1?$decoder_base_t@Vv2_decoder_t@zmq@@Vshared_message_memory_allocator@2@@zmq@@UAE@XZ)
1>../../../../lib/libzmq.dll : fatal error LNK1120: 16 unresolved externals
```

**Comment by hintjens** [comment]
Can you resend this thread to zeromq-dev?

I don't have a Windows environment to test on, yet these are basic
errors... I'd expect someone to know what's going on.

**Comment by slishak** [comment]
I didn't get a response on the mailing list, so I looked into it myself. Turns out it was pretty simple - there were a load of cpp files missing from the project that weren't getting compiled. I added them all and then it linked successfully. I'll now have a look at changing FD_SETSIZE.

**Comment by slishak** [comment]
I increased FD_SETSIZE by a factor of 4 to 16384 and rebuilt pyzmq using this new libzmq. Following this, I can start an IPython cluster with 250 workers easily. I sent 10000+ jobs to this cluster (each job was wait for one second) and didn't encounter any problems at all. Based on this, is there any reason FD_SETSIZE shouldn't be set to this (or even higher) by default?

**Comment by hintjens** [comment]
Personally, I'd like to set it to 64K. There is no solid argument for using
smaller values, except perhaps sanity checking. ZeroMQ limits a single
context to 1K sockets by default. That's a runtime limit, so FD_SETSIZE
should be IMO as high as possible.

Feel free to send a pull request with the change.

**Comment by slishak** [comment]
Sorry for the late response. I'm a bit new to GitHub and I'm not sure how many places in this repository the new limit needs to be set in. Is there anyone more experienced who could take care of it? 64K sounds good to me.

**Comment by slishak** [comment]
Sorry to be so persistent about this, but is it possible for someone else to make this change? I tried to do it myself, but was unable due to security policies at my workplace.

**Comment by slishak** [comment]
Just to update this - I've been using a version of libzmq I've build myself with FD_SETSIZE set to 64K using VS2008, but I'm getting some strange behaviour. It works fine when I use libzmq within a python process using ipyparallel, but if I load Python in .NET and run the same code in that Python interpreter, I get a StackOverflowException somewhere in zmq_poll (I don't get a stack trace with the error). Strangely, if I build libzmq in the debug configuration, everything works fine. If I build in release configuration, it works with FD_SETSIZE set to 32K, however at some value between that and 64K it stops working. I am not trying to create a particularly large IPython cluster (only 12 engines) so I don't think I'm reaching the socket limit. Do you have any ideas as to what could be causing that, or is it just completely crazy and probably something I'm doing wrong?

**Comment by hintjens** [comment]
Try building with a larger stack size, could be zmq_poll is using a stack
array that becomes too large.

Would you be able to send a pull request for the MSVC project files (you
can do this from home under your own Github account)?

**Comment by slishak** [comment]
I'm going to stick to 32K for now for my own builds. I'm not sure there's much advantage in upping that to 64K, considering it's currently much smaller (and nobody else seems to mind) and that way I don't need to mess with the stack size!

If I get time I'll take a look at doing it from home, but I won't have MSVC so without building it, I can't know if the same problems will occur under different compiler versions (I don't know how marginal 32K is for FD_SETSIZE). Unfortunately I can't really justify investigating this at work for every version of MSVC, seeing as what I have now seems to work!

**Comment by slishak** [comment]
(Finally) created a pull request to fix this for VS2008 (and all other builds where FD_SETSIZE is referenced) in #2035

**Comment by bluca** [comment]
Closing as it was fixed by https://github.com/zeromq/libzmq/pull/2035
