### ISSUE TITLE
PUB and REQ Socket connection memory leak 

### ISSUE THREAD

**Issue by sasatutus** [zeromq/libzmq#1565]
Hi,

Wen I create a connection between a PUB and REQ socket via tcp, there is a memory leak or better said accumulation of memory during runtime on the PUB side. I know that such connection shouldn't be created but if someone does that by mistaking ports, this could cause the PUB side to crash after a while. It seams like a huge security issue to me.

My code

PUB Side
```
    zmq::context_t context;

    zmq::socket_t socket(context, ZMQ_PUB);

    socket.bind("tcp://127.0.0.1:5555");

    s_iterate = true;

    while (s_iterate)
    {
        Sleep(10000);
    }

    std::cout << "Processing ending" << std::endl;

```

REQ Side

```
    zmq::context_t context;

    std::auto_ptr<zmq::socket_t> socket;

    socket.reset(new zmq::socket_t(context, ZMQ_REQ));

    bool connected = false;
    while (!connected)
    {
        try
        {
            socket->connect("tcp://127.0.0.1:5555");

            connected = true;
        }
        catch (...)
        {
            std::cout << "Connect failed" << std::endl;
            socket.reset(new zmq::socket_t(context, ZMQ_REQ));
        }
    }
    
    int timeOut = 10000;
    socket->setsockopt(ZMQ_RCVTIMEO, &timeOut, sizeof(timeOut));

    s_iterate = true;
    
    while (s_iterate)
    {
        try
        {
            zmq::message_t messageData;
            socket->recv(&messageData);
        }
        catch (...)
        {
            std::cout << "Message receive failed" << std::endl;
        }
    }

    std::cout << "Processing ending" << std::endl;
```

**Comment by wcs1only** [comment]
So while looking at a separate issue, I ran down the cause of the unbounded memory usage.  When the connection fails, command_t::pipe_term event is created and sent to the socket publisher pipe to clean up the socket. The zmq::socket_base_t::process_commands method will pick up this pipe_term and send a pipe_term_ack which will properly deallocate the pipe. The problem I was encountering is that the process_commands method only gets called when a message is sent/received over the socket. 

Try your code again, but this time periodically send a blank message through the publisher. Each time you send a message process_commands should get called on the publisher and clean up the pipes for the failed connections. See also #954.

**Comment by hintjens** [comment]
@wcs1only This fix cause a heap corruption, visible in tests/test_shutdown_stress.cpp. You should be able to reproduce that quite easily, as it happens systematically. As this broke all upstream CI, I've reverted the patch in the meantime.

**Comment by wcs1only** [comment]
Oh, I'm sorry. Several of the tests were broken in my build environment, so I missed this one. I should have some time to take a look over the holidays.

**Comment by neel-parikh** [comment]
@wcs1only 
Did you happen to fix this problem?
Thanks.

**Comment by simmel** [comment]
@wcs1only This is still a problem on 4.3.1
