### ISSUE TITLE
disconnect does not clear assigned rId for re-use

### ISSUE THREAD

**Issue by raspine** [zeromq/libzmq#1572]
I'm using the router socket and assign a rId upon connect.
When making a disconnect it would be handy if my previously assigned rId would be freed for re-use.
Right now I'm hitting at router.cpp line 411 when attempting to re-connect:

```
zmq_assert(false); //  Not allowed to duplicate an existing rid
```

**Comment by hintjens** [comment]
Can you make a minimal test case, and post that to zeromq-dev? Thanks.

**Comment by raspine** [comment]
OK done.

**Comment by sigiesec** [comment]
@raspine Sorry, I cannot find the mail in the mailing list archives. Does the issue still persist?
