### ISSUE TITLE
ROUTER routing breaks after reconnect

### ISSUE THREAD

**Issue by jkarneges** [zeromq/libzmq#1575]
1) ROUTER in program A is set to connect to a bind socket in program B.
2) Both programs are started, and the connection is established.
3) A determines B's socket identity out-of-band, so that it is able to send 
messages to B via the ROUTER socket.
3) B is terminated and the connection is lost.
4) B is started again, and the connection is re-established.
5) A determines B's socket identity out-of-band. However, sending via the ROUTER socket with this identity goes into a black hole.

It seems this problem does not happen if B retains the same socket 
identity across reconnects. However, if it uses a random identity (to be 
discovered out-of-band by A), then routing will never work again after 
the first restart of B. The A program must be restarted in order to make 
things right again.

My guess is that each connect queue on a ROUTER socket is somehow bound 
for life against the first identity it sees.

**Comment by hintjens** [comment]
Can you make a minimal test case for this?

**Comment by jkarneges** [comment]
https://gist.github.com/jkarneges/197d642a4773c60ba6bb

To try it, run both bind.py and connect.py (order of launch doesn't matter). Every 3 seconds, connect.py will send a message via ROUTER and bind.py will print the message. Just before sending, a REQ/REP exchange is used to determine the ROUTER identity to send to.

To reproduce the bug, simply restart bind.py and see how ROUTER messages are no longer received.

**Comment by djelenc** [comment]
Justin, try setting router_handover socket option on the router socket. I'd
try this myself but I'm currently not at my working computer.

Best,
David

**Comment by CoderHaha** [comment]
Thus I know there are JeroMQ and ZeroMQ-iOS,but I can��t build them with Xcode 6.4 or Android Studio.


Any one who can tell me the right way to build libZMQ with no worring about the version of the IDEs? 

Thanks .

**Comment by jkarneges** [comment]
Hi @djelenc, that setting doesn't seem to be enough. The documentation for ZMQ_ROUTER_HANDOVER suggests it is intended for ROUTER sockets using bind. In my case, the issue is on the connect side, so perhaps the logic is not applied.

**Comment by jkarneges** [comment]
I'm trying to make a fix but I'm lost in the code. Any suggestion?

In router.cpp there's a line in xhas_in():
```
TODO: handle the situation when the peer changes its identity.
```

I tried putting some code right there that calls set_identity() on the pipe to set the new identity, as well as reinsert into outpipes so the mapping is updated. I also put this same code in xrecv() which has a similar behavior. However, neither of my code blocks are actually invoked. So, I think merely reconnecting does not cause an identity message to be received, or at least not at this layer in the stack.

My other thought was to figure out where the disconnect code is handled. Basically, if the socket recv() returns <= 0 then null out the currently known identity, so that the pipe remains but it reverts to the initial state.

**Comment by hurtonm** [comment]
Hi @jkarneges Ithink thhe following words from the zmq_setsockopt explains the behaviour: "All options, with the exception of ZMQ_SUBSCRIBE, ZMQ_UNSUBSCRIBE and ZMQ_LINGER, only take effect for subsequent socket bind/connects."

**Comment by hurtonm** [comment]
@jkarneges I would like to help you make the fix but to do this I need to understand what the bug is and how do you plan to fix it. Maritn

**Comment by jkarneges** [comment]
Thanks @hurtonm. I believe the bug is that an existing connect pipe cannot be renamed by a future peer. The fix would be to allow this, at least if there isn't another pipe with the same name.

So, if an identity message is received over a pipe, and there is no other pipe with this name, then set the identity of the pipe to this new identity.

**Comment by hurtonm** [comment]
After B has been restarted a new connection is set up and as you say, you use different ID. So new pipe with a new ID is used. So there should be no confusion. Or do you think it does not happen like this?

**Comment by jkarneges** [comment]
It doesn't appear to happen like this. When connect() is used, a pipe is created that lives forever. It is not destroyed and recreated simply because of a reconnect.

This is in contrast with bind(), where a dropped connection probably destroys the pipe.

Of course I am not very familiar with libzmq's code, but this is the sense I get from the code (and the behavior, of course).

**Comment by hurtonm** [comment]
Seems like the bug.
As a workaround, try to set ZMQ_IMMEDIATE option to 1 on the A's side.

**Comment by jkarneges** [comment]
Thanks! That does work. I'll use that in my application for now.

Of course I hope we can still fix the real bug.
