### ISSUE TITLE
The libzmq is crashed when connect to a boardcast address

### ISSUE THREAD

**Issue by pengweichu** [zeromq/libzmq#1581]
Hello, when I use libzmq connect to a boardcast address for example 192.168.1.255, the zmq is crashed.

That because in zmq::fd_t zmq::tcp_connecter_t::connect () function, this line:

 const int rc = getsockopt (s, SOL_SOCKET, SO_ERROR, (char*) &err, &len);

The rc is 10049 cause wsa_assert_no to execute zmq::zmq_abort.

How to avoid this issue (some times the user enter the boardcaset IP)?

**Comment by c-rack** [comment]
Just googled around and found that return code 10049 means "Address not available":
https://msdn.microsoft.com/en-us/library/windows/desktop/ms740668%28v=vs.85%29.aspx#WSAEADDRNOTAVAIL

I would recommend to validate the address entered by the user before passing it to zmq.

**Comment by pengweichu** [comment]
@c-rack We have been use the regex expression to validated the IP, the 192.168.1.255 is a valid IP, but still crash the ZMQ.

**Comment by c-rack** [comment]
Yes, adding `WSAEADDRNOTAVAIL` to the list of excluded error codes in https://github.com/zeromq/libzmq/blob/master/src/tcp_connecter.cpp#L350-L362 should do the trick. Feel free to send a PR.

**Comment by pengweichu** [comment]
@c-rack What's the PR ?

**Comment by djelenc** [comment]
PR stands for pull request; you create a fork of libzmq, fix the problem and send the patch back to the libzm repositry via pull request. Here's a [nice overview](http://yangsu.github.io/pull-request-tutorial/) of the process.

**Comment by c-rack** [comment]
On Linux, the constant is named `EADDRNOTAVAIL`.

**Comment by pengweichu** [comment]
Thanks, I will try send the PR.
