### ISSUE TITLE
zmq assertion in signaler.cpp:292

### ISSUE THREAD

**Issue by ymax** [zeromq/libzmq#1583]
After updating to the recent version i've began to get this error (the program was run under valgrind, ubuntu 14.04):

> Resource temporarily unavailable (/home/ymax/Projects/tester/zeromq-latest/src/signaler.cpp:292)
> ==14071==    by 0x74B4CC8: raise (raise.c:56)
> ==14071==    by 0x74B80D7: abort (abort.c:89)
> ==14071==    by 0x641801: zmq::zmq_abort(char const*) (err.cpp:84)
> ==14071==    by 0x65029C: zmq::signaler_t::recv() (signaler.cpp:292)
> ==14071==    by 0x642198: zmq::mailbox_t::recv(zmq::command_t*, int) (mailbox.cpp:87)
> ==14071==    by 0x654F99: zmq::socket_base_t::process_commands(int, bool) (socket_base.cpp:1256)
> ==14071==    by 0x65443C: zmq::socket_base_t::send(zmq::msg_t*, int) (socket_base.cpp:985)
> ==14071==    by 0x633763: s_sendmsg(zmq::socket_base_t*, zmq_msg_t*, int) (zmq.cpp:348)
> ==14071==    by 0x633898: zmq_send (zmq.cpp:373)
> ...

Looking into sources I've found the possible cause:
the assertion happens here:
```c
void zmq::signaler_t::recv ()
{
    //  Attempt to read a signal.
#if defined ZMQ_HAVE_EVENTFD
    uint64_t dummy;
    ssize_t sz = read (r, &dummy, sizeof (dummy));
    errno_assert (sz == sizeof (dummy));
```
And the creation point of socket is:
```c
zmq::signaler_t::signaler_t ()
{
    //  Create the socketpair for signaling.
    if (make_fdpair (&r, &w) == 0) {
        unblock_socket (w);
        unblock_socket (r);
    }
```
Here we intentionally put socket into non-blocking state. And in this case read can return -1. From man of eventfd: 
> If the eventfd counter is zero at the time of the call to read(2) then the call either blocks... or fails with the error EAGAIN if the file descriptor has been made nonblocking.

**Comment by ymax** [comment]
Here is the patch:
https://gist.github.com/ymax/35a46c13edb635f698df#file-signaler-patch

**Comment by c-rack** [comment]
Thanks. Could you please send your patch as a pull request?

**Comment by ymax** [comment]
Added.
