### ISSUE TITLE
First message never received when SUB binds and PUB connects (LIBZMQ-248)

### ISSUE THREAD

**Issue by memeplex** [zeromq/libzmq#1594]
In zmq 4.1.2 I've been bitten by this old issue:

https://zeromq.jira.com/browse/LIBZMQ-248
https://zeromq.jira.com/browse/LIBZMQ-270

I'm not sure whether it has been ported to the new tracker or not (I wasn't able to find it here), but it seems to me as an important albeit forgotten issue.

**Comment by hintjens** [comment]
Are you sending immediately after connect? Then this is known behavior.
Connect takes a few msec during which there is no outgoing pipe.

**Comment by memeplex** [comment]
It's not that typical behavior you mention but an asymmetry regarding sub binds vs sub connects. It's very well described in the above jira links.

**Comment by memeplex** [comment]
BTW, it happens no matter how much you wait after subscribing to start sending, all messages before the first receive are lost.

**Comment by hintjens** [comment]
Sorry, my mistake.

Maybe it's worth raising this on zeromq-dev again then.

**Comment by bluca** [comment]
Closing as this is the same as https://github.com/zeromq/libzmq/issues/2267 and I'm trying to consolidate issues
