### ISSUE TITLE
Compiling for a 32-bit system via cmake causes test_heartbeat to fail intermittently

### ISSUE THREAD

**Issue by knierenhausen** [zeromq/libzmq#1601]
## Description

Setting the `-m32` flag in the top level `CMakeLists.txt` will cause `test_heartbeat` to fail intermittently

## Reproducing the Bug
1. Clone the repository

        git clone https://github.com/zeromq/libzmq.git
1. In the top level `CMakeLists.txt` add the following lines to compile for a 32-bit machine:

        set( CMAKE_C_FLAGS "-m32" )
        set( CMAKE_CXX_FLAGS "-m32" )
1. Create a make directory within the libzmq directory, and initialize cmake

        mkdir cmake-make
        cd cmake-make
        cmake ..
1. Compile libzmq with make

        make
1. Run `test_heartbeat` test several times and you'll see intermittent failures

        ./bin/test_heartbeats

## Expected v Actual
This is the expected result of running `./bin/test_heartbeats` multiple times:
```
$ ./bin/test_heartbeats 
$ ./bin/test_heartbeats 
$ ./bin/test_heartbeats 
$ ./bin/test_heartbeats 
$ ./bin/test_heartbeats 
$ ./bin/test_heartbeats 
$ ./bin/test_heartbeats 
$ ./bin/test_heartbeats 
$ ./bin/test_heartbeats 
$ ./bin/test_heartbeats 
```
This is the actual output:
```
$ ./bin/test_heartbeats 
$ ./bin/test_heartbeats 
Assertion failed: state == connected (/home/usr/libzmq/src/curve_server.cpp:134)
Aborted
$ ./bin/test_heartbeats 
$ ./bin/test_heartbeats 
$ ./bin/test_heartbeats 
Assertion failed: state == connected (/home/usr/libzmq/src/curve_server.cpp:134)
Aborted
$ ./bin/test_heartbeats 
Assertion failed: state == connected (/home/usr/libzmq/src/curve_server.cpp:134)
Aborted
$ ./bin/test_heartbeats 
Assertion failed: state == connected (/home/usr/libzmq/src/curve_server.cpp:134)
Aborted
$ ./bin/test_heartbeats 
$ ./bin/test_heartbeats 
$ ./bin/test_heartbeats 
```
## Distro Information
In case this helps here's my distro information:
```
DISTRIB_ID=LinuxMint
DISTRIB_RELEASE=17.2
DISTRIB_CODENAME=rafaela
DISTRIB_DESCRIPTION="Linux Mint 17.2 Rafaela"
NAME="Ubuntu"
VERSION="14.04.3 LTS, Trusty Tahr"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 14.04.3 LTS"
VERSION_ID="14.04"
```

## Deeper Dive
This seems to be an issue with timing when establishing a handshake between the curve client and server that are mocked up in test [test_heartbeat_notimeout(1)](https://github.com/zeromq/libzmq/blob/master/tests/test_heartbeats.cpp#L324). I explored a little bit here, and found that adjusting the `msleep`'s can change intermittent failures, but not too sure beyond that.

Also note this may be related to issue #1538

**Comment by hitstergtd** [comment]
Closing issue as it was resolved by PR #1652.
