### ISSUE TITLE
zmq::shared_message_memory_allocator::deallocate does not honor reference count

### ISSUE THREAD

**Issue by maxkozlovsky** [zeromq/libzmq#1610]
zmq::shared_message_memory_allocator::deallocate will free the buffer unconditionally even if there are references outstanding.  This can cause memory corruption during context termination when somebody holds on a message reference.

Here is suggested change:
<pre><code>
diff --git a/src/decoder_allocators.cpp b/src/decoder_allocators.cpp
index 7480d40..3b11130 100644
--- a/src/decoder_allocators.cpp
+++ b/src/decoder_allocators.cpp
@@ -96,10 +96,10 @@ unsigned char* zmq::shared_message_memory_allocator::allocate ()
 
 void zmq::shared_message_memory_allocator::deallocate ()
 {
-    std::free (buf);
-    buf = NULL;
-    bufsize = 0;
-    msg_refcnt = NULL;
+       zmq::atomic_counter_t* c = reinterpret_cast <zmq::atomic_counter_t*> (buf);
+       if (buf && !c->sub(1))
+           std::free (buf);
+       release();
 }
  unsigned char* zmq::shared_message_memory_allocator::release ()
</code></pre>

**Comment by hintjens** [comment]
Would you like to send a pull request?

**Comment by maxkozlovsky** [comment]
Sure, on Monday.

**Comment by hintjens** [comment]
:-) Thanks.
