### ISSUE TITLE
Problem: new socket types aren't properly documented as rfc

### ISSUE THREAD

**Issue by sappo** [zeromq/libzmq#1612]
Recently there is a lot of chatter about the new ZMQ_SERVER and ZMQ_CLIENT sockets. Sadly the documentation for those is not existent when excluding code comments (and I really hate reading c++ code, sry). All zeromq sockets are described as RFC which is missing for those two.

It would be nice if someone with the knowledge on how they work and what they actually are could create a rfc.

Thanks in advance!

**Comment by hintjens** [comment]
I've made man pages for these in zmq, no RFC yet. See zmq_socket.txt.

**Comment by sappo** [comment]
That's really helpful thanks. 

libzmq really badly needs a czmq like README documentation. This would make finding these things a lot easier and be an infinite improvement ;)

**Comment by hintjens** [comment]
Good idea. I think the existing man page structure doesn't work, we have
lots of tiny man pages for things no-one needs, and then a few massive
pages with all the core detail...

**Comment by hintjens** [comment]
Ugh. I actually wrote an RFC 41, and forgot to push it to the repo, and
then my laptop was stolen. I'll do it again later this week.

**Comment by metadings** [comment]
Why did you name them so common, "server" and "client"... Usually we have

	REQ - ROUTER - DEALER - REP
	PUSH - PULL
	PUB - SUB

Now I thought, that I also **could** connect PUSH to a ROUTER and PULL to a DEALER (by sending back an empty message); however, why are you abandoning these verbs?

**Comment by hintjens** [comment]
We have this vague idea of a new ZeroMQ API that is threadsafe and simpler.
This means new names, not breaking old ones.

Client-server makes sense for the many cases we now solve using zproto.

If we abandon the old names it'll be in many years when we're all happy
with the new ones...

I covered this in http://hintjens.com/blog:84 and we discussed it on the
zeromq-dev list a few times.

**Comment by sappo** [comment]
@hintjens uff, that's really messed up :(

Is it possible to pull the most important man files into one README with gitdown for starters?

**Comment by hintjens** [comment]
That is a good idea... we can't use the same process as CZMQ as the man
pages are not pulled from the header file... /thinks...

**Comment by metadings** [comment]
Well, I have just a `RouterDealerDevice` and I'm connecting them using `new ZSocket(ZSocketType.REP)` and `new ZSocket(ZSocketType.REQ)`; no need for threadsafety...

**Comment by metadings** [comment]
Well, I have just a `RouterDealerDevice` and I'm connecting them using `new ZSocket(ZSocketType.REP)` and `new ZSocket(ZSocketType.REQ)`; no need for threadsafety...

**Comment by sappo** [comment]
@metadings I'm pretty sure this is the wrong thread/issue for this discussion

**Comment by sappo** [comment]
@hintjens how about a different asciidoc.conf to convert the txt files into a different format?

**Comment by hintjens** [comment]
Yes, that'd work. Let me look at this later, I'm in a workshop till Friday.
Will you ping me on this next week?

**Comment by sappo** [comment]
Sure, I'll do that.

**Comment by sappo** [comment]
ping @hintjens. Let me know if there's anything that I can do to support you.

**Comment by hintjens** [comment]
I'll rewrite the RFC today.
