### ISSUE TITLE
Enable static libraries under mingw-w64

### ISSUE THREAD

**Issue by jeroenooms** [zeromq/libzmq#1614]
When building libzqm on `mingw-w64` with `--enable-static`, the `./configure` fails with:

```
 Building static libraries is not supported under MinGW32
```

This [old post](http://grokbase.com/t/zeromq/zeromq-dev/136sg6zk4s/build-zmq-as-static-library-under-mingw) on the mailing list suggests that this is a limitation of mingw32. This is completely silly, package repositories such as [msys2](http://repo.msys2.org/mingw/x86_64/) have hundreds of libraries and almost all of them include static libraries. 

It seems that this limitation is actually hardcoded in your [autoconf script](https://github.com/zeromq/libzmq/blob/500269955df78b4e013224adfcef2ff63c1de5c9/configure.ac#L267-L269). I was wondering if we can look into fixing this? The same [old post](http://grokbase.com/t/zeromq/zeromq-dev/136sg6zk4s/build-zmq-as-static-library-under-mingw) suggests a workaround but I was unable to get that to work. It would be nice to fix this properly once and for all. Maybe @Alexpux or @mingwandroid can help out with a word of advice if we get stuck.

**Comment by jeroenooms** [comment]
Actually setting `-DZMQ_STATIC` in `CPPFLAGS` seems to do the job. Here is a PR: https://github.com/zeromq/libzmq/pull/1615

**Comment by AbhishekRamamurthy** [comment]
I tried your suggestion but linking zmq library with static enabled fails.

x86_64-w64-mingw32-g++-posix -v ../Thread_test.cpp -o thread.exe -std=gnu++11 -static-libgcc -static-libstdc++ -DZMQ_STATIC -static -pthread -levent -lws2_32 -lzmq

/usr/bin/x86_64-w64-mingw32-ld: cannot find -lzmq
collect2: error: ld returned 1 exit status

But dynamic linking works, I need it static as I don't want install zmq libraries again on windows.

Any suggestions on this ?

**Comment by bluca** [comment]
I'm not familiar with Windows or mingw but on Linux gcc's linker usually prefers to link dynamically, instead of -lzmq try the full path to the static lib

**Comment by jeroen** [comment]
Your error says `cannot find -lzmq` so that means you need to pass a `-L` flag to the path where `libzmq.a` is located for example:

   -L/some/special/path -lzmq

Or you can use `pkg-config --libs zeromq`

**Comment by AbhishekRamamurthy** [comment]
@bluca , I'm trying to cross-compile from linux to windows

@jeroen , I tried compiling with explicitly providing libzmq.dll.la. But when the code is executed in windows, it Throws me an error saying libzmq.dll not found.

**Comment by AbhishekRamamurthy** [comment]
-lzmq.dll fixed my problem, thanks for the suggestion guys .
