### ISSUE TITLE
Problem: libzmq is not CI tested on AppVeyor

### ISSUE THREAD

**Issue by sappo** [zeromq/libzmq#1622]
@zeromq/core I've created a zeromq team at appveyor to CI test czmq and provided access to the owners of the zeromq project. To verify everything is working as expected I need an owner to sign in with their github account at appveyor and add libzmq.

**Comment by c-rack** [comment]
@sappo Will try it out today again. Have not had the tim eto do it earlier.

Related to https://github.com/zeromq/libzmq/pull/1619

**Comment by sappo** [comment]
That's great, though there is one small issue. It seems you're no longer part of the owners or now core team of zeromq. @hintjens I guess this did happen by accident during the transition?!

**Comment by c-rack** [comment]
Thanks, that perfectly explains why my previous attempt was not successful. I'll send a request to join core team.

**Comment by c-rack** [comment]
Now being a core team member (thanks!), I could log-in as _zeromq_ user on appveyor and add libzmq to the list of porjects:
https://ci.appveyor.com/project/zeromq/libzmq
