### ISSUE TITLE
Version 4.1.3 packages incorrect stdint.hpp 

### ISSUE THREAD

**Issue by cwacekINV** [zeromq/libzmq#1630]
The currently available source archive of libzmq (http://download.zeromq.org/zeromq-4.1.3.tar.gz) packages an incorrect version of the stdint.hpp file. In it, line 39 is: `#elif defined _MSC_VER && _MSC_VER < 1500`. That should be a 1600 as seen [on master](https://github.com/zeromq/libzmq/blob/master/src/stdint.hpp#L39), since MSVC only started providing stdint.h with Visual Studio 2010. 

This is breaking builds of ZeroMQ with Visual Studio 2008 (which is all Python 2.7 builds). I have looked through the git history and the offending line *never* said 1500, so I'm not sure where this came from.

**Comment by minrk** [comment]
The relevant change is zeromq/zeromq4-1#42, which was apparently based on incorrect information.
