### ISSUE TITLE
ZeroMQ over SDP/InfiniBand - automatic conversion from TCP to SDP fails

### ISSUE THREAD

**Issue by shadless1** [zeromq/libzmq#1633]
I'd like to evaluate ZMQ over SDP/Infiniband (56Gb).
I configured automatic conversion from TCP to SDP (AF_INET to AF_INET_SDP) and successfully ran iperf3 over SDP. 
The problem is ZeroMQ omits my configuration and uses TCP over IPoIB instead.
Any ideas why it happens?

Regards,
Adam

**Comment by hitstergtd** [comment]
Adam:
* Is this still a concern to you?
* Could you please provide a test case or refer to an existing test case where this happens?

**Comment by sigiesec** [comment]
Closing this issue due to missing information and inactivity. Feel free to reopen it with more information :)
