### ISSUE TITLE
Handle sodium_init() return value

### ISSUE THREAD

**Issue by ismail** [zeromq/libzmq#1635]
With the latest libsodium 1.0.6 zeromq fails to compile

```
src/curve_client.cpp: In constructor 'zmq::curve_client_t::curve_client_t(const zmq::options_t&amp;)':
src/curve_client.cpp:61:18: error: ignoring return value of 'int sodium_init()', declared with attribute warn_unused_result [-Werror=unused-result]
     sodium_init();
```

Same applies to src/curve_server.cpp, code already has a todo for this. Just wanted to let you know that this is now a compile error.

For openSUSE I am adding  a patch something like

```
- sodium_init();
+ zeromq_assert (sodium_init() != -1);
```

**Comment by c-rack** [comment]
See https://github.com/zeromq/libzmq/issues/1632
It is fixed in master branch long time ago and recently backported to 4-1.
Could you please try with libzmq from master branch and check if problem persists?

**Comment by ismail** [comment]
Ok so we did the same fix in the end, so no need to retest. Thanks!
