### ISSUE TITLE
Configuration fails due to missing pkg-config on OS X

### ISSUE THREAD

**Issue by Gacko** [zeromq/libzmq#1642]
I just tried to install the 4.1.3 release. This fails due to the following error:

```
configure: error: in `/Users/myuser/Downloads/zeromq-4.1.3':
configure: error: The pkg-config script could not be found or is too old.  Make sure it
is in your PATH or set the PKG_CONFIG environment variable to the full
path to pkg-config.

Alternatively, you may set the environment variables sodium_CFLAGS
and sodium_LIBS to avoid the need to call pkg-config.
See the pkg-config man page for more details.

To get pkg-config, see <http://pkg-config.freedesktop.org/>.
See `config.log' for more details
```

I don't have pkg-config installed since http://zeromq.org/docs:source-git says I do not need it for released source packages and installing 4.0.7 works fine.

Do I really need pkg-config or is this a mistake of you?

**Comment by bluca** [comment]
As the doc says if you don't have pkg-config you'll need to set the sodium flags manually.
