### ISSUE TITLE
IPv6 link local addresses are not handled properly

### ISSUE THREAD

**Issue by syenna** [zeromq/libzmq#1661]
ZeroMQ library is not handling the IPv6 link local addresses properly when creating sockets. IPv6 link local addresses include % followed by an interface name. This is not considered by the ZeroMQ library in handling the socket address passed. tcp_address.cpp and socket_base.cpp need to be modified to solve this issue.

**Comment by syenna** [comment]
Pull request #1659 fixes this issue. It is already merged on to the libzmq master branch. This fix needs to be backported to the stable branch zeromq4-1.

**Comment by hintjens** [comment]
Backported to 4-1 stable, thanks. :)

**Comment by syenna** [comment]
I do not see the changes on 4-1 stable yet. Am I missing something here? Please let me know.

**Comment by hintjens** [comment]
Ah, sorry, didn't merge yet... hang on... :-) ok, done.

**Comment by syenna** [comment]
Thanks!
Next comes changes for czmq... I will work on them.
