### ISSUE TITLE
Packaging: outdated autotools

### ISSUE THREAD

**Issue by jdemeyer** [zeromq/libzmq#1666]
When compiling ZeroMQ on this `ppc64le` system:

```
Linux sardonis 3.19.0-15-generic #15-Ubuntu SMP Thu Apr 16 23:32:13 UTC 2015 ppc64le ppc64le ppc64le GNU/Linux
```

`./configure` fails with

```
UNAME_MACHINE = ppc64le
UNAME_RELEASE = 3.19.0-15-generic
UNAME_SYSTEM  = Linux
UNAME_VERSION = #15-Ubuntu SMP Thu Apr 16 23:32:13 UTC 2015
configure: error: cannot guess build type; you must specify one
```

Using up-to-date versions of autotools fixes this problem and allow ZeroMQ to compile and pass the test suite on `ppc64le`.

**Comment by jdemeyer** [comment]
Note that this does not require a change to the ZeroMQ sources, but to the source tarball packaging process.

**Comment by bluca** [comment]
The source distributable tarball is now created on Ubuntu LTS 14.04 which should be enough. If it's not then simply regenerate locally with autogen.sh.
