### ISSUE TITLE
why zmq_poll only support select or poll, not epoll?

### ISSUE THREAD

**Issue by europelee** [zeromq/libzmq#1667]
in src/poller.cpp:
 #if defined ZMQ_USE_KQUEUE
#include "kqueue.hpp"
#elif defined ZMQ_USE_EPOLL
#include "epoll.hpp"
#elif defined ZMQ_USE_DEVPOLL
#include "devpoll.hpp"
#elif defined ZMQ_USE_POLL
#include "poll.hpp"
#elif defined ZMQ_USE_SELECT
#include "select.hpp"
#else
#error None of the ZMQ_USE_* macros defined
#endif

#if defined ZMQ_USE_SELECT
#define ZMQ_POLL_BASED_ON_SELECT
#else
#define ZMQ_POLL_BASED_ON_POLL //my system support epoll, but zmq_poll use poll!!!
#endif

and src/zmq.cpp:
zmq_poll function, only handle: ZMQ_POLL_BASED_ON_POLL,ZMQ_POLL_BASED_ON_SELECT
 so in my machine, zmq_poll would use poll

**Comment by somdoron** [comment]
For io libzmq will use epoll. as zmq_poll is not suppose to work with a lot of sockets you doesn't really need epoll. To clarify with zmq_poll you only poll on zeromq sockets, which is usually a few

**Comment by europelee** [comment]
ok, i see, you mean that libzmq use epoll for raw sockets internally, and for libzmq users, because they only use  libzmq API 'zmq_poll' which just poll a few zeromq sockets(but they map to many raw sockets internally) , so poll is enough for zmq_poll?

**Comment by somdoron** [comment]
yes.
