### ISSUE TITLE
MSVC 2013 dll build broken

### ISSUE THREAD

**Issue by ttuna** [zeromq/libzmq#1678]
Hello ...

It seems that timer.cpp is missing in project src files and iphlpapi.lib should be added to avoid unresolved symbols for if_nametoindex().

Cheers

**Comment by hitstergtd** [comment]
@ttuna,

Does the referenced commit by @tom-seddon fix the issue for you?

**Comment by evoskuil** [comment]
I verified all msvc 2013 builds as of #1988.

**Comment by hitstergtd** [comment]
I an closing this issue but if it still persists let us know here by leaving a comment and I will reopen it. Thanks to @evoskuil too for updating the MSVC files!

**Comment by ttuna** [comment]
Sorry for the delayed answer. 
MSVC builds are working again for me now. Thanks to all contributors!
