### ISSUE TITLE
zmq_send/recv overflow with sizes larger than INT_MAX

### ISSUE THREAD

**Issue by minrk** [zeromq/libzmq#1697]
Problem:

1. zmq_send/recv, etc. operations return a number of bytes in `rc` or `-1` for errors
2. this value is an `int`
3. the operations support sizes larger than `INT_MAX`

So if you send or receive messages larger than `INT_MAX`, `rc` will overflow and have an invalid negative value.

**Comment by c-rack** [comment]
Good catch. It does not make sense to return an `int` if length is `size_t`.

Two possible solutions come into my mind:
1. Change return type from `int` to `size_t`
2. Implement a check in `zmq_send` / `zmq_recv` that fails with `-1` if `len_ >= INT_MAX`

Both will be break backwards-compatibility, however.
Any further ideas or suggestions?

**Comment by minrk** [comment]
I don't think there is a way to fix it without breaking backward-compatibility other than adding *new* APIs that don't have this problem.

If we use `size_t`as the returntype, a different value would need to be used to signal failure since `-1` would be unavailable.

I'd also be okay truncating the return value if it's larger than INT_MAX. I've never actually used the size-as-return-value, since it can never contain any useful information.

**Comment by bluca** [comment]
Given it has never worked, IMHO truncating to INT_MAX is a good solution until API is broken for other reasons :+1:

**Comment by minrk** [comment]
#1719 truncates rc to INT_MAX
