### ISSUE TITLE
MinGW32 build support (to confirm, or remove)

### ISSUE THREAD

**Issue by CrackHD** [zeromq/libzmq#1703]
I am wondering how to compile this under mingw32 (i need exactly mingw, not msvc - msvc is fine). **I need to build libzmq statically**. What i've tried is downloaded source tarball and extracted to folder, then executed commands in **cmd.exe** (i use TDM-GCC-32, 5.1, Wine_x86):

```
cd builds/mingw32
mingw32-make -f Makefile.mingw32
```

This prints an error in **tcp_address.cpp:441** saying that **if_nametoindex()** is not defined. Having no information about this issue i've only patched it (comment out expr) and it's fixed now (while zmq is damaged now as i think).

Next problem was undefined `CONDITION_VARIABLE` type. I fixed this error by altering **CFLAGS** in makefile and adding options in the middle:

```
-std=c++0x -D_WIN32_WINNT=_WIN32_WINNT_VISTA 
```

I am sure it's incorrec but i only experimenting.

However, i am still having another error raised after 2 minutes of compile. [stdout log](http://pastebin.com/UgRXMcFJ). And here's **stderr** output:

```
removing this because it was completely useless as i was using invalid environment outside msys
```

It basically fails because of **_undefined**_ references to functions. What i am doing wrong?

**I also don't understand how to specify libsodium location for build (headers or libs)**

**Comment by CrackHD** [comment]
I executed "./autogen.sh" on Ubuntu (with all dev tools needed) and moved modified files to my Windows. I also installed DevKit for Ruby as instructed [on zeromq.org page](http://zeromq.org/build:mingw) and runned "devkitvars.bat". 

After that i opened "libzmq" source directory and trying command "./configure" (under devkit's SH shell). But fails.

c:\devkit_x86\mingw\bin\../lib/gcc/i686-w64-mingw32/4.7.2/../../../../i686-w64-m
ingw32/include/netioapi.h:44:3: error: 'SOCKADDR_INET' does not name a type
c:\devkit_x86\mingw\bin\../lib/gcc/i686-w64-mingw32/4.7.2/../../../../i686-w64-m
ingw32/include/netioapi.h:56:3: error: 'SOCKADDR_INET' does not name a type
c:\devkit_x86\mingw\bin\../lib/gcc/i686-w64-mingw32/4.7.2/../../../../i686-w64-m
ingw32/include/netioapi.h:64:3: error: 'SOCKADDR_INET' does not name a type
c:\devkit_x86\mingw\bin\../lib/gcc/i686-w64-mingw32/4.7.2/../../../../i686-w64-m
ingw32/include/netioapi.h:79:3: error: 'SOCKADDR_INET' does not name a type
c:\devkit_x86\mingw\bin\../lib/gcc/i686-w64-mingw32/4.7.2/../../../../i686-w64-m
ingw32/include/netioapi.h:152:3: error: 'SOCKADDR_INET' does not name a type
c:\devkit_x86\mingw\bin\../lib/gcc/i686-w64-mingw32/4.7.2/../../../../i686-w64-m
ingw32/include/netioapi.h:250:3: error: 'SOCKADDR_INET' does not name a type
c:\devkit_x86\mingw\bin\../lib/gcc/i686-w64-mingw32/4.7.2/../../../../i686-w64-m
ingw32/include/netioapi.h:251:3: error: 'SOCKADDR_INET' does not name a type
c:\devkit_x86\mingw\bin\../lib/gcc/i686-w64-mingw32/4.7.2/../../../../i686-w64-m
ingw32/include/netioapi.h:254:3: error: 'SOCKADDR_INET' does not name a type
c:\devkit_x86\mingw\bin\../lib/gcc/i686-w64-mingw32/4.7.2/../../../../i686-w64-m
ingw32/include/netioapi.h:273:3: error: 'SOCKADDR_INET' does not name a type
c:\devkit_x86\mingw\bin\../lib/gcc/i686-w64-mingw32/4.7.2/../../../../i686-w64-m
ingw32/include/netioapi.h:382:9: error: 'PSOCKADDR_IN6' does not name a type
c:\devkit_x86\mingw\bin\../lib/gcc/i686-w64-mingw32/4.7.2/../../../../i686-w64-m
ingw32/include/netioapi.h:384:9: error: 'PSOCKADDR_IN6' does not name a type
c:\devkit_x86\mingw\bin\../lib/gcc/i686-w64-mingw32/4.7.2/../../../../i686-w64-m
ingw32/include/netioapi.h:387:3: error: 'PSOCKADDR_IN6_PAIR' has not been declar
ed
c:\devkit_x86\mingw\bin\../lib/gcc/i686-w64-mingw32/4.7.2/../../../../i686-w64-m
ingw32/include/netioapi.h:454:9: error: 'SOCKADDR_INET' does not name a type
c:\devkit_x86\mingw\bin\../lib/gcc/i686-w64-mingw32/4.7.2/../../../../i686-w64-m
ingw32/include/netioapi.h:455:9: error: 'SOCKADDR_INET' does not name a type
c:\devkit_x86\mingw\bin\../lib/gcc/i686-w64-mingw32/4.7.2/../../../../i686-w64-m
ingw32/include/netioapi.h:458:3: error: 'SOCKADDR_INET' has not been declared
In file included from c:\devkit_x86\mingw\bin\../lib/gcc/i686-w64-mingw32/4.7.2/

**Comment by CrackHD** [comment]
I need kind of reply because time is money for me and i sped days on this already.

**Comment by arohr** [comment]
Hi

I was able to compile zeromq 3.2.5 using the MSYS console
(from Ruby DevKit http://rubyinstaller.org/downloads/):

./configure
make

everything compiles except a test which uses nanosleep, which is not available under windows (I 
believe). Nevertheless libzmq.dll is built and can be found in src/.libs. But I don't known if it's 
possible to build a static lib.

other info: http://zeromq.org/build:mingw

andy


Am 14.01.2016 um 19:31 schrieb Crackhead:

**Comment by CrackHD** [comment]
I appreciate your info, it helped me a lot with libzqm-3.2.5. 

It was only needed to patch "test_monitor" (remove all test code and leave `return 0` only) and "test_delay" (include `windows.h`, and use `Sleep(1)` instead of **nanosleep** function)

However, building latest 4.x release fails and this still needs to be resolved. If you additionally [install pkg-config](http://stackoverflow.com/questions/1710922/how-to-install-pkg-config-in-windows) to DevTools folder, and then do
```
./configure --without-libsodium
make
```
It only gives a message:
```
DPATH="${ZSH_VERSION+.}:" && cd . && /bin/sh /c/zeromq-4.1.4/config/missing acl
cal-1.14 -I config
c/zeromq-4.1.4/config/missing: line 81: aclocal-1.14: command not found
ARNING: 'aclocal-1.14' is missing on your system.
        You should only need it if you modified 'acinclude.m4' or
        'configure.ac' or m4 files included by 'configure.ac'.
        The 'aclocal' program is part of the GNU Automake package:
        <http://www.gnu.org/software/automake>
        It also requires GNU Autoconf, GNU m4 and Perl in order to run:
        <http://www.gnu.org/software/autoconf>
        <http://www.gnu.org/software/m4/>
        <http://www.perl.org/>
ake: *** [aclocal.m4] Error 127
```

1. I've tried downloading **libsodium** release and unpacking it to a folder, and then specifying its path to `--with-libsodium=`, but it still fails with message **No package libsodium found**.
2. Missing option to configure/make **libzmq.a** (static) instead of **libzmq.dll** (shared).

**Comment by gajanak** [comment]
The cmake build system works with mingw compiler out of the box.
You only need to remove 
`SET_TARGET_PROPERTIES( ${test} PROPERTIES LINK_FLAGS "/LIBPATH:../bin/Win32/Debug/v120/dynamic" )`
in tests/CMakeLists.txt

**Comment by CrackHD** [comment]
Cmake is not too much familiar to me. On windows-msvc there are no reason to use it (just configure script). I've tried running Cmake GUI but it thrown me a bunch of error messages (and i failed to compile withing Code::blocks).

Related to the problems i mentioned in previous post.
1. libsodium seems to be expected only in a directory one lever higher that libzmq stored in. Relatively to "build" folder, its path is "../../libsodium/".

Ill try to build it with cmake again in few days or a week.

**Comment by hitstergtd** [comment]
@CrackHD 
Did you have any luck? Is this still an issue?

**Comment by CrackHD** [comment]
@hitstergtd i think this should be closed now as low-quality of original post/experience.
