### ISSUE TITLE
Reconnect over req-rep does not seem to work

### ISSUE THREAD

**Issue by hintjens** [zeromq/libzmq#172]
To reproduce: start piclient, then start hwserver. Now kill hwserver, and restart it. piclient should reconnect automatically and work again. It doesn't. Any help welcome...

https://gist.github.com/845127

**Comment by SachinKung** [comment]
why close issue , and how to fix this bug?

**Comment by SachinKung** [comment]
> To reproduce: start piclient, then start hwserver. Now kill hwserver, and restart it. piclient should reconnect automatically and work again. It doesn't. Any help welcome...
> 
> https://gist.github.com/845127

the client  is blocked，must be kill by CTRL+C

**Comment by SachinKung** [comment]
please reopen this issue.

**Comment by marekschor** [comment]
REQ / REP communication solution

Set ZMQ_REQ_CORRELATE to 1 and ZMQ_REQ_RELAXED also to 1. It will definitely help. Use ZMQ version 4.2 and higher for these settings.

Here are the solution authors pages: https://www.ckamm.de/~kamm/projects/index.static/2013/09/25/improving-req-sockets-in-zmq-4/index.html

Read more in the manual: http://api.zeromq.org/4-2:zmq-setsockopt

**Comment by ng5** [comment]
I was not able to get ZMQ_REQ_CORRELATE & ZMQ_REQ_RELAXED. I'm using latest zmq (4.3.4).
I ended up reconnecting explicitly. 

```
//  Hello World client
#include <stdio.h>
#include <zmq.h>

void *reconnect(void *context, void *requester, short destroy) {
    if (destroy) {
        zmq_close(requester);
        requester = zmq_socket(context, ZMQ_REQ);
    }
    int max = 5000;
    zmq_setsockopt(requester, ZMQ_SNDTIMEO, &max, sizeof(max));
    zmq_setsockopt(requester, ZMQ_RCVTIMEO, &max, sizeof(max));
    zmq_connect(requester, "tcp://localhost:5555");
    return requester;
}
int main(void) {
    printf("Connecting to hello world server...\n");
    void *context = zmq_ctx_new();
    void *requester = zmq_socket(context, ZMQ_REQ);
    reconnect(context, requester, 0);
    for (int index = 0; index != 100; index++) {
        char buffer[10];
        int status = zmq_send(requester, "Hello", 5, 0);
        while (status < 0) {
            requester = reconnect(context, requester, 1);
            status = zmq_send(requester, "Hello", 5, 0);
        }
        printf("sent count %d\n", index);
        status = zmq_recv(requester, buffer, 10, 0);
        if (status < 0) {
            index--;
        }
        printf("recv count %d\n", index);
    }
    zmq_close(requester);
    zmq_ctx_destroy(context);
    return 0;
}
```
