### ISSUE TITLE
Memory Leak in the following code

### ISSUE THREAD

**Issue by zerojiu** [zeromq/libzmq#1726]
```
#include <zmq/zmq.h>
#include <iostream>

int main()
{
    std::string monitorAddress = "inproc://monitor.rep9ac611c6-f17a-4fcc-8641-2d0170dfa2d7";
    void *ctx = zmq_ctx_new();
    void * m_pairsocket = NULL;
    while (m_pairsocket == NULL)
    {
        m_pairsocket = zmq_socket(ctx, ZMQ_PAIR);
        zmq_connect(m_pairsocket, monitorAddress.c_str());
        zmq_close(m_pairsocket);
        m_pairsocket = NULL;
        Sleep(10000);
        std::cout << "socket close" << std::endl;
    }
    getchar();
    return 0;
}
```

as the code above, the program's handles is continue increasing. and in the source code of libzmq, there is code as follow in own.cpp:

```
void zmq::own_t::check_term_acks ()
{
    if (terminating && processed_seqnum == sent_seqnum.get () &&
          term_acks == 0) {

        //  Sanity check. There should be no active children at this point.
        zmq_assert (owned.empty ());

        //  The root object has nobody to confirm the termination to.
        //  Other nodes will confirm the termination to the owner.
        if (owner)
            send_term_ack (owner);

        //  Deallocate the resources.
        process_destroy ();
    }
}
```

when a socket connect fails and we try to close socket,  we find the condition of 

```
processed_seqnum == sent_seqnum.get () &&term_acks == 0 
```

never meets
This lead to resouce leak of handles.

**Comment by hitstergtd** [comment]
@JerkWisdom -
* Could you give more details as to the platform?
* Judging from the call to `Sleep` I presume this is on Windows?

**Comment by opedroso** [comment]
Yes, it is Windows. Here is the stack of the leaked memory block:
```
libzmq-v120-mt-gd-4_2_0.dll  std::_Allocate<zmq::socket_base_t *> : [c:\program files (x86)\microsoft visual studio 12.0\vc\include\xmemory0 Line 28]
libzmq-v120-mt-gd-4_2_0.dll  std::allocator<zmq::socket_base_t *>::allocate : [c:\program files (x86)\microsoft visual studio 12.0\vc\include\xmemory0 Line 578]
libzmq-v120-mt-gd-4_2_0.dll  std::_Wrap_alloc<std::allocator<zmq::socket_base_t *> >::allocate : [c:\program files (x86)\microsoft visual studio 12.0\vc\include\xmemory0 Line 847]
libzmq-v120-mt-gd-4_2_0.dll  std::vector<zmq::socket_base_t *,std::allocator<zmq::socket_base_t *> >::_Reallocate : [c:\program files (x86)\microsoft visual studio 12.0\vc\include\vector Line 1588]
libzmq-v120-mt-gd-4_2_0.dll  std::vector<zmq::socket_base_t *,std::allocator<zmq::socket_base_t *> >::_Reserve : [c:\program files (x86)\microsoft visual studio 12.0\vc\include\vector Line 1617]
libzmq-v120-mt-gd-4_2_0.dll  std::vector<zmq::socket_base_t *,std::allocator<zmq::socket_base_t *> >::push_back : [c:\program files (x86)\microsoft visual studio 12.0\vc\include\vector Line 1257]
libzmq-v120-mt-gd-4_2_0.dll  zmq::array_t<zmq::socket_base_t,0>::push_back : [x:\3rdparty\libzmq\src\array.hpp Line 122]
libzmq-v120-mt-gd-4_2_0.dll  zmq::ctx_t::create_socket : [x:\3rdparty\libzmq\src\ctx.cpp Line 390]
libzmq-v120-mt-gd-4_2_0.dll  zmq_socket : [x:\3rdparty\libzmq\src\zmq.cpp Line 255]
test_timers.exe  main : [x:\3rdparty\libzmq\tests\test_timers.cpp Line 11]
test_timers.exe  __tmainCRTStartup : [f:\dd\vctools\crt\crtw32\dllstuff\crtexe.c Line 626]
test_timers.exe  mainCRTStartup : [f:\dd\vctools\crt\crtw32\dllstuff\crtexe.c Line 465]
kernel32.dll  BaseThreadInitThunk : [{FUNC}BaseThreadInitThunk Line 0]
```

**Comment by bjovke** [comment]
@JerkWisdom @hitstergtd @opedroso There is a leak in this code. Each socket created never gets destroyed.

There are two pipes created for "inproc" socket, one is attached to socket and one should be attached to the socket on the other side which binds (which is never created in this example). When` zmq_close()` is called, the attached pipe sends terminate request to the other pipe but the other pipe never responds and attached pipe doesn't get destroyed. Socket is destroyed when it's attached pipe is destroyed and in this case it is never destroyed.

If you look at the [documentation](http://api.zeromq.org/2-1:zmq-inproc), there's this:

- `The name must have been previously created by assigning it to at least one socket within the same ØMQ context as the socket being connected.`

So it is mandatory to first create socket which binds to the same "inproc" socket and then call connect on the client socket. When bind socket is present, `zmq_close()` will cleanup properly and really destroy the socket.

**Comment by bjovke** [comment]
Hm, the solution I wrote still leaks RAM and does not properly close sockets.
See #792.

**Comment by bjovke** [comment]
@JerkWisdom I've looked at this in more detail.
In order for socket to be really closed it must successfully connect to the other side (bind socket). Furthermore, for inproc transport bind side of the socket must process the connection, so it must bind after client socket connection or be located in separate thread than socket which is connecting.
Please see test `test_inproc_connect.cpp` in test directory and `test_multiple_threads ();` code in it.
