### ISSUE TITLE
Is Router-To-Dealer combination valid?

### ISSUE THREAD

**Issue by reza-ebrahimi** [zeromq/libzmq#1728]
I want to send from Router socket to Dealer socket in my server application, but it fails...
```
RouterSocket->recv() 

... Process Received Message...

RouterSocket->send() --> send response to dealer connection

DealerSocket->recv() --> ? receive from router socket but it remains blocking forever.
```

**Comment by c-rack** [comment]
The combination is valid, at least according to the spec:
http://rfc.zeromq.org/spec:37#toc16

Could you please provide a minimal test case (i.e. a single file C source code) that reproduces the problem? The files in the `tests` folder might be a good starting point for that.

**Comment by hintjens** [comment]
Router sockets use a special routing-id frame that you receive as the first
part of a message, and must re-send as the first part of a reply. If you
don't do this, the message gets discarded and the dealer will wait forever.

**Comment by reza-ebrahimi** [comment]
@hintjens How to specify a client with Router socket and send data to it? please provide me a minimal example, examples in internet was unclear.

**Comment by hintjens** [comment]
Please read the Guide, it is explained in exhaustive detail.

**Comment by reza-ebrahimi** [comment]
@hintjens I read it and I think that was unclear, there is many talks about identity of sockets, but no clear example about that.

**Comment by reza-ebrahimi** [comment]
My current problem is:

I have a ```Dealer``` socket conntected to ```Router``` socket with port ```5590```:

```
	zmq::socket* frontendSocket = new zmq::socket(context, ZMQ_ROUTER);
	frontendSocket->bind("tcp://*:5590", "FrontendRouter");
	
	zmq::socket* backendSocket = new zmq::socket(context, ZMQ_ROUTER);
	backendSocket->bind("inproc://backend", "BackendRouter");

	zmq::proxy(*frontendSocket, *backendSocket, *backendSocket);
```
and in another thread:
```
	zmq::socket* dealerSocket = new zmq::socket(context, ZMQ_DEALER);
    dealerSocket->setsockopt(ZMQ_IDENTITY, identity.c_str(), identity.length());
	dealerSocket->connect("inproc://backend");
```
so when I send a message from ```dealerSocket``` I receive it in its ```recv``` method inside ```while``` loop.

**Comment by msteinhoff** [comment]
What do you try to achieve there? In this code you only recv() messages, but where are they sent?

Messages from a router socket have a routing id in the first frame. When you receive or send such messages over the dealer socket, you have to manage the routing id manually. This is explained in the guide.
