### ISSUE TITLE
Can't set ZMQ_ROUTER_HANDOVER socket option

### ISSUE THREAD

**Issue by reza-ebrahimi** [zeromq/libzmq#1731]
Can't set ZMQ_ROUTER_HANDOVER socket option, it throw an exception with message "Invalid argument",

```		
int isHandOver = 1;
try {
    m_socket.setsockopt(ZMQ_ROUTER_HANDOVER, &isHandOver, sizeof(int));
} catch(std::exception &ex) {
    const char* error = ex.what();
    printf("%s", error); // prints "Invalid argument"
}
```

**Comment by c-rack** [comment]
The option `ZMQ_ROUTER_HANDOVER` is only valid for sockets of type `ZMQ_ROUTER`. In your example, it is not clear what type of socket you are using. Could you please provide a minimal example / test case that reproduces the problem?

You might use https://github.com/zeromq/libzmq/blob/master/tests/test_router_handover.cpp as an example / starting point.

**Comment by reza-ebrahimi** [comment]
@c-rack Thanks for your Hint, The problem is I set ```ZMQ_DEALER``` socket option,

I have another question, I have a ```Dealer``` socket that connected to a ```Router``` socket, so the problem is when I send messages inside a ```for``` loop with same ```Dealer``` and ```Router``` identity, it works fine, but when generate unique identities in ```Dealer``` socket side, it give me an ```access violation``` exception, but I have to solve this problem with sleep ```Dealer``` socket for 10ms after sending,

```
for (int i = 0; i < 10; i++)
{
    dealerSocket->send(&msg);
    Sleep(10); // <--
}
```

In another way I want to write a new connection arrival mechanism to register new clients, I have to simulate new clients using ```Dealer``` socket inside a ```for``` loop.

**Comment by c-rack** [comment]
Could you please close this issue as resolved and open another one with your second problem? This makes tracking the issues easier. Thanks.
