### ISSUE TITLE
Cannot compile because of "unresolved external symbol"

### ISSUE THREAD

**Issue by sunkin351** [zeromq/libzmq#1732]
MSVC gives me the following error when compiling:

LNK2019	unresolved external symbol `"public: __cdecl zmq::radio_t::radio_t(class zmq::ctx_t *,unsigned int,int)" (??0radio_t@zmq@@QEAA@PEAVctx_t@1@IH@Z)` referenced in function `"public: static class zmq::socket_base_t * __cdecl zmq::socket_base_t::create(int,class zmq::ctx_t *,unsigned int,int)" (?create@socket_base_t@zmq@@SAPEAV12@HPEAVctx_t@2@IH@Z)`	libzmq	...\libzmq-master\builds\msvc\vs2015\libzmq\socket_base.obj

And then there is another one which is the exact same except it's for the symbol 
`"public: __cdecl zmq::dish_t::dish_t(class zmq::ctx_t *,unsigned int,int)" (??0dish_t@zmq@@QEAA@PEAVctx_t@1@IH@Z)`

**Comment by hintjens** [comment]
There are new classes and the MSVC project files don't reflect them yet.
I'll fix that now.

**Comment by hintjens** [comment]
OK, this is fixed on libzmq master now. Thanks for reporting the problem.
