### ISSUE TITLE
Problem: send inside a loop causes access violation in Dealer to Router pattern

### ISSUE THREAD

**Issue by reza-ebrahimi** [zeromq/libzmq#1733]
I have a Dealer socket that connected to a Router socket, so the problem is when I send messages inside a for loop with same Dealer and Router identity, it works fine, but when generate unique identities in Dealer socket side, it give me an access violation exception, but I have to solve this problem with sleep Dealer socket for 10ms after sending,

```
for (int i = 0; i < 10; i++)
{
    dealerSocket->send(&msg);
    Sleep(10); // <--
}
```

In another way I want to write a new connection arrival mechanism to register new clients, I have to simulate new clients using Dealer socket inside a for loop

**Comment by UsamaMehboob** [comment]
I am not sure why this is not working for you. I tried this and it works
for (i=0; i<10;i++){
        void *context = zmq_ctx_new();
    void *client = zmq_socket(context, ZMQ_DEALER);
    s_set_id(client);
    zmq_connect (client, "tcp://localhost:5555");
        s_sendmore(client, "");
        s_send(client, "Hi Boss");
    }
