### ISSUE TITLE
MSVC code analysis reveals 9 issues with "udp_address.hpp"

### ISSUE THREAD

**Issue by sunkin351** [zeromq/libzmq#1738]
All of the issues referring to line 76, 3 issues compiling 3 files:

C2236 `unexpected token 'struct'. Did you forget a ';'? (compiling source file ..\..\..\..\src\address.cpp)`

C2332 `'struct': missing tag name (compiling source file ..\..\..\..\src\address.cpp)`

C2027 `use of undefined type 'zmq::udp_address_t::<unnamed-tag>' (compiling source file ..\..\..\..\src\address.cpp)`

Files:
address.cpp
session_base.cpp
socket_base.cpp

**Comment by sunkin351** [comment]
Off-topic comment: Can we attempt building the project with changes before uploading to gitlab?

**Comment by hintjens** [comment]
Can you send a pull request with fixes?

**Comment by sunkin351** [comment]
I cannot. I have no idea how to fix this.

**Comment by sunkin351** [comment]
I am getting all kinds of errors from udp_address.cpp as well... Are these even complete? Why did the creator of these files not bother to try to build the project with these before uploading them???

**Comment by sunkin351** [comment]
Ok, I lied... all issues regarding udp_address.hpp/.cpp have been resolved. Issuing pull request.
