### ISSUE TITLE
[4.1.4 onwards] if_nametoindex requires minimum windows version vista (_WIN32_WINNT >= 0x0600)

### ISSUE THREAD

**Issue by CommanderBubble** [zeromq/libzmq#1752]
As the title states, the function if_nametoindex requires a minimum windows version of vista (see [here](https://msdn.microsoft.com/en-us/library/windows/desktop/bb408409%28v=vs.85%29.aspx)) and currently it is defined as _WIN32_WINNT 0x0501 in windows.hpp for 4.1.4.

this appears to be rectified in the current build, so shouldn't this be backported? i pulled down 4.1.4 stable yesterday and was unable to build due to this

**Comment by hintjens** [comment]
Yes, you can make a pull request to backport this to zeromq4-1 stable, if
you like. (Check it's not already been backported to the github repo first).

**Comment by CommanderBubble** [comment]
additionally, can the newer client-server socket type be disabled at build time? if not, then the minimum version for _WIN32_WINNT needs to be bumped to 0x0600 even in mingw, as this by default defines it as 0x0501, but the preprocessor will only bump it to 0x0501 minimum regardless
