### ISSUE TITLE
Problem: test_radio_dish times out on OSX

### ISSUE THREAD

**Issue by bluca** [zeromq/libzmq#1761]
This test consistently fails on Travis on OSX. Having the CI script run the binary manually only shows the SIGALARM going off. Unfortunately there is limited debugging I can do via Travis, since I do not have an OSX machine :-(

```+DYLD_LIBRARY_PATH=:/Users/travis/build/bluca/libzmq/tmp/lib
+tests/.libs/test_radio_dish
./ci_build.sh: line 30: 34571 Alarm clock: 14   DYLD_LIBRARY_PATH=$DYLD_LIBRARY_PATH:${BUILD_PREFIX}/lib tests/.libs/test_radio_dish
```

Is there anybody with an OSX machine that can confirm and reproduce this issue?

**Comment by msteinhoff** [comment]
Running make check on OS X:

```
./config/test-driver: line 107: 25727 Alarm clock: 14         "$@" > $log_file 2>&1
FAIL: tests/test_radio_dish
```

**Comment by bluca** [comment]
Thanks! So it is definitely not a CI issue.

@somdoron any clue on why radio-dish could have problem on OSX?

**Comment by somdoron** [comment]
I will check this out tomorrow

**Comment by bluca** [comment]
:+1:

**Comment by bluca** [comment]
@somdoron - ehrm, I think I accidentally fixed it :-D I was looking at a Valgrind read-after-free report, and it looks like the fix for it also solves the OSX problem, at least it does on Travis. Wasn't my intention of stepping on your toes, sorry!

**Comment by msteinhoff** [comment]
If you want to cross check, I can do a fresh compile from master. Is the fix already pushed to libzmq master?

**Comment by bluca** [comment]
@msteinhoff - just merged. A cross check would be great, thanks!

**Comment by msteinhoff** [comment]
Okay, give me a sec :)

**Comment by msteinhoff** [comment]
Radio dish test passes now, looks good :+1:

**Comment by somdoron** [comment]
@bluca I can confirm it solved the issue on mac

**Comment by somdoron** [comment]
thanks :-)

**Comment by bluca** [comment]
Awesome, an accidental fix for a platform that I don't even have :-D Thanks for checking!

@somdoron - sorry again for stepping on your toes :-)

Would be interesting to know exactly why it was causing problems on OSX but not on Linux. I guess with a read-after-free we are in the realm of undefined behaviour, and while it happened to work with gcc, it didn't with Apple's fork of Clang. Fun times!
