### ISSUE TITLE
test_many_sockets fails on platforms with open file limits higher than 65536

### ISSUE THREAD

**Issue by nmoadev** [zeromq/libzmq#1788]
[test_many_sockets.cpp:39](https://github.com/zeromq/libzmq/blob/master/tests/test_many_sockets.cpp#L39)
Sets an expectation that the maximum number of sockets that can be created is:
```c++
const int no_of_sockets = 2 * 65536;
```

However, on system with a limit of open files per process higher than 65536, this test fails because the loop  which follows the aforementioned declaration creates many more sockets. This problem was observed on a Docker image derived from `ubuntu:wily` with a file limit of 1048576:
```bash
$ ulimit -n
1048576
```

Dockerfile for reproducing the issue
```dockerfile
FROM ubuntu:wily

ENV zmq_version 4.1.4
ENV zmq_dir /zeromq-${zmq_version}

RUN apt-get update
RUN apt-get install -y \
  autoconf \
  automake \
  curl \
  g++ \
  libtool \
  pkg-config \
  uuid-dev 
  
# ZMQ installation
RUN mkdir -p $zmq_dir \
  && curl -SL http://download.zeromq.org/zeromq-${zmq_version}.tar.gz \
  | tar -xzC / \
  && cd $zmq_dir \
  && ./configure --without-libsodium \
  && make
```

**Comment by hintjens** [comment]
Would you send a pull request to fix the test case?

**Comment by hitstergtd** [comment]
@nmoadev,
Thanks for the report! Pull request #1889 should have solved this issue. Closing the issue; please let us know if the issue persists and we will re-open it.
