### ISSUE TITLE
Undefined macro ZMQ_XPUB_VERBOSE_UNSUBSCRIBE

### ISSUE THREAD

**Issue by sunkin351** [zeromq/libzmq#1812]
ZMQ_XPUB_VERBOSE_UNSUBSCRIBE is undefined in zmq.h

**Comment by bluca** [comment]
Was renamed to: ZMQ_XPUB_VERBOSER

**Comment by sunkin351** [comment]
Understood, It becomes problematic when the bindings are not being updated quite as frequently. zmqpp needs to be updated to reflect this in `socket_options.hpp`.

**Comment by hintjens** [comment]
See the zmq_setsockopt man page, as the semantics changed a little (you
don't need to set ZMQ_XPUB_VERBOSE as well).

**Comment by hintjens** [comment]
These are draft API pieces, still liable to change if we see issues with
them. Sorry about that.

**Comment by sunkin351** [comment]
Quick question, are you guys the ones keeping zmqpp up to date or is that someone else?

**Comment by hintjens** [comment]
Look at the commits, you'll see who maintains it.
https://github.com/zeromq/zmqpp/graphs/contributors
Looks like xaqq is currently the main contributor.
