### ISSUE TITLE
C1021 on zmq_utils.h Line 31 from VS2015

### ISSUE THREAD

**Issue by sunkin351** [zeromq/libzmq#1816]
Invalid Preprocessor command `#warning`

If there is something like this preprocessor in another compiler, it needs to be a preprocessor conditional to not be read by MSVC...

This is the last thing keeping me from building the zmqpp bindings.

**Comment by sunkin351** [comment]
Might i recommend using the `#error` macro? (Hidden in a conditional) Or does that not suite your purpose?

**Comment by rcane** [comment]
Although using `#error` would print the message to the log, it would still stop the compilation. The most appropriate way of dealing with this is to use 

`#pragma` message( "zmq_utils.h is deprecated..." )`

This will print out the message but will not terminate the compilation.

**Comment by hitstergtd** [comment]
@sunkin351,
Thanks for the report! Closing this issue. See #1885.
