### ISSUE TITLE
Test failures while running make check on OSX

### ISSUE THREAD

**Issue by indradhanush** [zeromq/libzmq#1821]
I just updated my `libzmq` code from upstream, and then did the following:

```
./autogen.sh
./configure --with-libsodium
make check
```

The last step produced the following test failures (output from `test-suite.log`):

```
====================================
   zeromq 4.2.0: ./test-suite.log
====================================

# TOTAL: 79
# PASS:  76
# SKIP:  0
# XFAIL: 2
# FAIL:  1
# XPASS: 0
# ERROR: 0

.. contents:: :depth: 2

XFAIL: tests/test_req_correlate
===============================



Assertion failed: (rc != -1), function s_recv_seq, file tests/testutil.hpp, line 246.

XFAIL: tests/test_req_relaxed
=============================

Assertion failed: (rc != -1), function s_recv_seq, file tests/testutil.hpp, line 246.

FAIL: tests/test_shutdown_stress
================================

Invalid argument (src/stream_engine.cpp:134)
```

**Comment by indradhanush** [comment]
I'd be happy to send a patch for this, if someone could help me with getting started on this issue.

**Comment by bluca** [comment]
Hi,

The XFAILed tests are expected to fail.

The test_shutdown_stress is failing likely because of file/processes limits. It creates 700 threads, for 10 times in a row.

On the OSX CI, we set the following and then the test passes:

    sudo sysctl -w kern.maxfiles=64000
    sudo sysctl -w kern.maxfilesperproc=64000
    sudo launchctl limit maxfiles 64000 64000
    ulimit -n 64000

Could you set those and try again, please?

**Comment by indradhanush** [comment]
Hi @bluca,

I can confirm that after setting the above params, the tests pass.

Although, I am curious, why are the `XFAIL` tasks expected to fail?

**Comment by bluca** [comment]
See https://github.com/zeromq/libzmq/pull/1730 for more information.

**Comment by indradhanush** [comment]
Thanks. Closing this as the problem is solved.
