### ISSUE TITLE
zmq failing on os x 10.10.5

### ISSUE THREAD

**Issue by chrisscastaneda** [zeromq/libzmq#1835]
ran into issues trying to install ijavascript for jupyter notebooks via npm on mac os x (10.10.5).  npm spits out an error indicating that it's "most likely a problem with the zmq package". i get a similar message when i try to install zmq independently (i.e. sudo npm install -g zmq).  below is the error output from npm and attached is the log file requested. 

`
$ sudo npm install -g ijavascript
\
> zmq@2.14.0 install /Users/chriscastaneda-barajas/.npm-packages/lib/node_modules/ijavascript/node_modules/jmp/node_modules/zmq
> node-gyp rebuild

  CXX(target) Release/obj.target/zmq/binding.o
  SOLINK_MODULE(target) Release/zmq.node
ld: library not found for -lgcc_s.10.5
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [Release/zmq.node] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:270:23)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Darwin 14.5.0
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/chriscastaneda-barajas/.npm-packages/lib/node_modules/ijavascript/node_modules/jmp/node_modules/zmq
gyp ERR! node -v v4.3.2
gyp ERR! node-gyp -v v3.0.3
gyp ERR! not ok 
npm ERR! Darwin 14.5.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "-g" "ijavascript"
npm ERR! node v4.3.2
npm ERR! npm  v2.14.12
npm ERR! code ELIFECYCLE

npm ERR! zmq@2.14.0 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the zmq@2.14.0 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the zmq package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls zmq
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/chriscastaneda-barajas/Dropbox/SkunkWorks/npm-debug.log
`

[npm-debug.log.txt](https://github.com/zeromq/libzmq/files/157872/npm-debug.log.txt)

**Comment by hitstergtd** [comment]
@chrisscastaneda,

Could you please try the following:

```
brew install zmq
npm install -g zmq
```

The above works on OS X El Capitan; please do let us know if it works for you.

**Comment by hitstergtd** [comment]
@chrisscastaneda,
Thanks for the report!

I am closing the issue as the instructions in my above post should successfully resolve the reported issue. If that is not the case, please do leave a follow-up here and I will re-open it again.

**Comment by yaoyuande** [comment]
I also encountered this mistake,
brew install zmq    , succeed.
But  npm install -g zmq   still failed

**Comment by yaoyuande** [comment]
@hitstergtd Can you help me?
