### ISSUE TITLE
Question: libzmq 4.2 release date?

### ISSUE THREAD

**Issue by vlad-dragos** [zeromq/libzmq#1855]
I was just curious when the "stable" 4.2 version will be released. I'm eager to test the new SERVER/CLIENT sockets.

**Comment by hintjens** [comment]
We'll release a stable 4.1.x update, then a 4.2. In any case the new socket
types won't be marked as stable for some time (they'll be published as
'draft' within the 4.2 release, subject to change, and not built by default
for tarballs).

tl;dr best thing would be to work off libzmq master and start using the
client/server sockets now. CZMQ already supports them.

**Comment by vlad-dragos** [comment]
I'm actually using PyZMQ which, from what I can see from the change log, also has support for the new sockets. I will build from master and go from there. Thank you for answering so quickly.
