### ISSUE TITLE
asyncio: socket.RCVTIMEO = timeout and  socket.setsockopt( zmq.RCVTIMEO, timeout) do not work

### ISSUE THREAD

**Issue by thehesiod** [zeromq/libzmq#1856]
a work-around seems to be to use a piece of code like this:

```python
        with aiohttp.Timeout(timeout):  # asyncio.timeout missing from 3.5.x
            await in_queue.recv()
```

since its really easy to implement I suggest zmq properly handle this natively as documented.

**Comment by hintjens** [comment]
This is not a libzmq issue, please raise it in the correct project, thanks.

**Comment by thehesiod** [comment]
logged as https://github.com/zeromq/pyzmq/issues/825
