### ISSUE TITLE
Failed to compile with VS2013

### ISSUE THREAD

**Issue by pengweichu** [zeromq/libzmq#1865]
I have checkout the last libzmq code but can't compile it:

Microsoft (R) Build Engine version 12.0.40629.0
[Microsoft .NET Framework, version 4.0.30319.42000]
Copyright (C) Microsoft Corporation. All rights reserved.

Build started 3/23/2016 1:57:45 PM.
     1>Project "C:\Stacks\zmq\libzmq\builds\msvc\vs2013\libzmq.sln" on node 1 (default targets).
     1>ValidateSolutionConfiguration:
         Building solution configuration "DynDebug|Win32".
     1>Project "C:\Stacks\zmq\libzmq\builds\msvc\vs2013\libzmq.sln" (1) is building "C:\Stacks\zmq\libzmq\builds\msvc\vs2013\libzmq\libzmq.vcxproj" (2) on node 1 (default targets).
     2>C:\Stacks\zmq\libzmq\builds\msvc\vs2013\libzmq\libzmq.vcxproj(67,5): error MSB4019: The imported project "C:\Stacks\zmq\libzmq\builds\msvc\vs2013\libzmq\libzmq.props" was not found. Confirm that the path in the <Import> declaration is correct, and that the file exists on disk.
     2>Done Building Project "C:\Stacks\zmq\libzmq\builds\msvc\vs2013\libzmq\libzmq.vcxproj" (default targets) -- FAILED.
     1>Project "C:\Stacks\zmq\libzmq\builds\msvc\vs2013\libzmq.sln" (1) is building "C:\Stacks\zmq\libzmq\builds\msvc\vs2013\remote_lat\remote_lat.vcxproj" (3) on node 1 (default targets).
     3>C:\Stacks\zmq\libzmq\builds\msvc\vs2013\remote_lat\remote_lat.vcxproj(64,5): error MSB4019: The imported project "C:\Stacks\zmq\libzmq\builds\msvc\vs2013\remote_lat\remote_lat.props" was not found. Confirm that the path in the <Import> declaration is correct, and that the file exists on disk.
     3>Done Building Project "C:\Stacks\zmq\libzmq\builds\msvc\vs2013\remote_lat\remote_lat.vcxproj" (default targets) -- FAILED.
     1>Project "C:\Stacks\zmq\libzmq\builds\msvc\vs2013\libzmq.sln" (1) is building "C:\Stacks\zmq\libzmq\builds\msvc\vs2013\local_thr\local_thr.vcxproj" (4) on node 1 (default targets).
     4>C:\Stacks\zmq\libzmq\builds\msvc\vs2013\local_thr\local_thr.vcxproj(64,5): error MSB4019: The imported project "C:\Stacks\zmq\libzmq\builds\msvc\vs2013\local_thr\local_thr.props" was not found. Confirm that the path in the <Import> declaration is correct, and that the file exists on disk.
     4>Done Building Project "C:\Stacks\zmq\libzmq\builds\msvc\vs2013\local_thr\local_thr.vcxproj" (default targets) -- FAILED.
     1>Project "C:\Stacks\zmq\libzmq\builds\msvc\vs2013\libzmq.sln" (1) is building "C:\Stacks\zmq\libzmq\builds\msvc\vs2013\inproc_lat\inproc_lat.vcxproj" (6) on node 3 (default targets).
     6>C:\Stacks\zmq\libzmq\builds\msvc\vs2013\inproc_lat\inproc_lat.vcxproj(64,5): error MSB4019: The imported project "C:\Stacks\zmq\libzmq\builds\msvc\vs2013\inproc_lat\inproc_lat.props" was not found. Confirm that the path in the <Import> declaration is correct, and that the file exists on disk.
     6>Done Building Project "C:\Stacks\zmq\libzmq\builds\msvc\vs2013\inproc_lat\inproc_lat.vcxproj" (default targets) -- FAILED.
     1>Project "C:\Stacks\zmq\libzmq\builds\msvc\vs2013\libzmq.sln" (1) is building "C:\Stacks\zmq\libzmq\builds\msvc\vs2013\local_lat\local_lat.vcxproj" (7) on node 1 (default targets).
     7>C:\Stacks\zmq\libzmq\builds\msvc\vs2013\local_lat\local_lat.vcxproj(64,5): error MSB4019: The imported project "C:\Stacks\zmq\libzmq\builds\msvc\vs2013\local_lat\local_lat.props" was not found. Confirm that the path in the <Import> declaration is correct, and that the file exists on disk.
     7>Done Building Project "C:\Stacks\zmq\libzmq\builds\msvc\vs2013\local_lat\local_lat.vcxproj" (default targets) -- FAILED.
     1>Project "C:\Stacks\zmq\libzmq\builds\msvc\vs2013\libzmq.sln" (1) is building "C:\Stacks\zmq\libzmq\builds\msvc\vs2013\inproc_thr\inproc_thr.vcxproj" (5) on node 2 (default targets).
     5>C:\Stacks\zmq\libzmq\builds\msvc\vs2013\inproc_thr\inproc_thr.vcxproj(64,5): error MSB4019: The imported project "C:\Stacks\zmq\libzmq\builds\msvc\vs2013\inproc_thr\inproc_thr.props" was not found. Confirm that the path in the <Import> declaration is correct, and that the file exists on disk.
     5>Done Building Project "C:\Stacks\zmq\libzmq\builds\msvc\vs2013\inproc_thr\inproc_thr.vcxproj" (default targets) -- FAILED.
     1>Done Building Project "C:\Stacks\zmq\libzmq\builds\msvc\vs2013\libzmq.sln" (default targets) -- FAILED.
     1>Project "C:\Stacks\zmq\libzmq\builds\msvc\vs2013\libzmq.sln" (1) is building "C:\Stacks\zmq\libzmq\builds\msvc\vs2013\remote_thr\remote_thr.vcxproj" (8) on node 4 (default targets).
     8>C:\Stacks\zmq\libzmq\builds\msvc\vs2013\remote_thr\remote_thr.vcxproj(64,5): error MSB4019: The imported project "C:\Stacks\zmq\libzmq\builds\msvc\vs2013\remote_thr\remote_thr.props" was not found. Confirm that the path in the <Import> declaration is correct, and that the file exists on disk.
     8>Done Building Project "C:\Stacks\zmq\libzmq\builds\msvc\vs2013\remote_thr\remote_thr.vcxproj" (default targets) -- FAILED.

Build FAILED.

       "C:\Stacks\zmq\libzmq\builds\msvc\vs2013\libzmq.sln" (default target) (1) ->
       "C:\Stacks\zmq\libzmq\builds\msvc\vs2013\libzmq\libzmq.vcxproj" (default target) (2) ->
         C:\Stacks\zmq\libzmq\builds\msvc\vs2013\libzmq\libzmq.vcxproj(67,5): error MSB4019: The imported project "C:\Stacks\zmq\libzmq\builds\msvc\vs2013\libzmq\libzmq.props" was not found. Confirm that the path in the <Import> declaration is correct, and that the file exists on disk.

       "C:\Stacks\zmq\libzmq\builds\msvc\vs2013\libzmq.sln" (default target) (1) ->
       "C:\Stacks\zmq\libzmq\builds\msvc\vs2013\remote_lat\remote_lat.vcxproj" (default target) (3) ->
         C:\Stacks\zmq\libzmq\builds\msvc\vs2013\remote_lat\remote_lat.vcxproj(64,5): error MSB4019: The imported project "C:\Stacks\zmq\libzmq\builds\msvc\vs2013\remote_lat\remote_lat.props" was not found. Confirm that the path in the <Import> declaration is correct, and that the file exists on disk.

       "C:\Stacks\zmq\libzmq\builds\msvc\vs2013\libzmq.sln" (default target) (1) ->
       "C:\Stacks\zmq\libzmq\builds\msvc\vs2013\local_thr\local_thr.vcxproj" (default target) (4) ->
         C:\Stacks\zmq\libzmq\builds\msvc\vs2013\local_thr\local_thr.vcxproj(64,5): error MSB4019: The imported project "C:\Stacks\zmq\libzmq\builds\msvc\vs2013\local_thr\local_thr.props" was not found. Confirm that the path in the <Import> declaration is correct, and that the file exists on disk.

       "C:\Stacks\zmq\libzmq\builds\msvc\vs2013\libzmq.sln" (default target) (1) ->
       "C:\Stacks\zmq\libzmq\builds\msvc\vs2013\inproc_lat\inproc_lat.vcxproj" (default target) (6) ->
         C:\Stacks\zmq\libzmq\builds\msvc\vs2013\inproc_lat\inproc_lat.vcxproj(64,5): error MSB4019: The imported project "C:\Stacks\zmq\libzmq\builds\msvc\vs2013\inproc_lat\inproc_lat.props" was not found. Confirm that the path in the <Import> declaration is correct, and that the file exists on disk.

       "C:\Stacks\zmq\libzmq\builds\msvc\vs2013\libzmq.sln" (default target) (1) ->
       "C:\Stacks\zmq\libzmq\builds\msvc\vs2013\local_lat\local_lat.vcxproj" (default target) (7) ->
         C:\Stacks\zmq\libzmq\builds\msvc\vs2013\local_lat\local_lat.vcxproj(64,5): error MSB4019: The imported project "C:\Stacks\zmq\libzmq\builds\msvc\vs2013\local_lat\local_lat.props" was not found. Confirm that the path in the <Import> declaration is correct, and that the file exists on disk.

       "C:\Stacks\zmq\libzmq\builds\msvc\vs2013\libzmq.sln" (default target) (1) ->
       "C:\Stacks\zmq\libzmq\builds\msvc\vs2013\inproc_thr\inproc_thr.vcxproj" (default target) (5) ->
         C:\Stacks\zmq\libzmq\builds\msvc\vs2013\inproc_thr\inproc_thr.vcxproj(64,5): error MSB4019: The imported project "C:\Stacks\zmq\libzmq\builds\msvc\vs2013\inproc_thr\inproc_thr.props" was not found. Confirm that the path in the <Import> declaration is correct, and that the file exists on disk.

       "C:\Stacks\zmq\libzmq\builds\msvc\vs2013\libzmq.sln" (default target) (1) ->
       "C:\Stacks\zmq\libzmq\builds\msvc\vs2013\remote_thr\remote_thr.vcxproj" (default target) (8) ->
         C:\Stacks\zmq\libzmq\builds\msvc\vs2013\remote_thr\remote_thr.vcxproj(64,5): error MSB4019: The imported project "C:\Stacks\zmq\libzmq\builds\msvc\vs2013\remote_thr\remote_thr.props" was not found. Confirm that the path in the <Import> declaration is correct, and that the file exists on disk.

    0 Warning(s)
    7 Error(s)

Time Elapsed 00:00:00.43

**Comment by hintjens** [comment]
Before you can build, run .\configure.bat.

**Comment by hitstergtd** [comment]
@pengweichu,
Thanks for the report. Did @hintjens suggestion solve the issue?

Please let us know, so that we can update the issue status appropriately.

**Comment by sunkin351** [comment]
Idk about the OP, but I can compile with vs2015 quite nicely, not so much as a single warning either.

**Comment by hitstergtd** [comment]
@sunkin351 
OK, thanks. I will perform a vs2015 build to confirm and then close the issue down.

**Comment by hitstergtd** [comment]
@pengweichu @sunkin351 
Performed VS2013 and VS2015 builds and it is fine. Closing issue.

**Comment by ivihovsky** [comment]
I have the same issue but for VC-2010 and I cannot find file configure.bat to run command run .\configure.bat.
I can see that I have libzmq.props file for 2015 only. May I copy it for 2010?
Otherwise where am I supposed to look for libzmq.props or configure.bat?
Thank you
