### ISSUE TITLE
change to zmq_utils.h breaks MSVC pyzmq (easy fix)

### ISSUE THREAD

**Issue by gnieboer** [zeromq/libzmq#1867]
The new zmq_utils.hpp using the #warning syntax to emit the deprecation warning, however msvc uses a different syntax.  Recommend the following:

```
#ifndef _MSC_VER
#warning(zmq_utils.h is deprecated.All its functionality is provided by zmq.h.)
#else
#pragma message("Warning: zmq_utils.h is deprecated. All its functionality is provided by zmq.h.")
#endif
```

**Comment by c-rack** [comment]
Thanks. Would you mind to submit a pull request with this change?

**Comment by gnieboer** [comment]
See pull request #1871

**Comment by bluca** [comment]
Closing as this is now fixed. Thanks for sending the PR!
