### ISSUE TITLE
Failing tests Windows7 msys2/mingw64

### ISSUE THREAD

**Issue by kunapulir** [zeromq/libzmq#1870]
While compiling libzmq master on Windows7 using msys2/mingw64 I ran into the following XPASS errors:

XPASS: tests/test_req_correlate
===============================

XPASS tests/test_req_correlate.exe (exit status: 0)

XPASS: tests/test_req_relaxed
=============================

XPASS tests/test_req_relaxed.exe (exit status: 0)

============================================================================
Testsuite summary for zeromq 4.2.0
============================================================================
# TOTAL: 70
# PASS:  68
# SKIP:  0
# XFAIL: 0
# FAIL:  0
# XPASS: 2
# ERROR: 0
============================================================================
See ./test-suite.log
Please report to zeromq-dev@lists.zeromq.org
============================================================================
Makefile:3944: recipe for target 'test-suite.log' failed
make[4]: *** [test-suite.log] Error 1
make[4]: Leaving directory '/d/gows/src/github.com/zeromq/libzmq/zeromq-4.2.0/_build/sub'
Makefile:4050: recipe for target 'check-TESTS' failed
make[3]: *** [check-TESTS] Error 2
make[3]: Leaving directory '/d/gows/src/github.com/zeromq/libzmq/zeromq-4.2.0/_build/sub'
Makefile:4899: recipe for target 'check-am' failed
make[2]: *** [check-am] Error 2
make[2]: Leaving directory '/d/gows/src/github.com/zeromq/libzmq/zeromq-4.2.0/_build/sub'
Makefile:3830: recipe for target 'check-recursive' failed
make[1]: *** [check-recursive] Error 1
make[1]: Leaving directory '/d/gows/src/github.com/zeromq/libzmq/zeromq-4.2.0/_build/sub'
Makefile:4817: recipe for target 'distcheck' failed
make: *** [distcheck] Error 1

**Comment by bluca** [comment]
Those are expected, hence why they are marked as xfail (which in autotools means they are expected to fail). Please see https://github.com/zeromq/libzmq/pull/1730 for more information.

**Comment by kunapulir** [comment]
Thanks for the quick response. I can understand XFAIL means expected to fail. But what's with XPASS?

**Comment by bluca** [comment]
Mh, good question! Those tests are definitely marked as XFAIL.

I'm really not an expert on Windows, so I cannot say why they are marked as XPASS. Maybe that's how the mingw port of autotools works? Hopefully someone familiar with that environment can chip in.

**Comment by hitstergtd** [comment]
@kunapulir, @bluca:
Probably due to to change 625b6187767451444fb68035883f442393b87f9f, as it seems to fix `ZMQ_REQ_CORRELATE` and also removes those tests from `XFAIL`.

@kunapulir:
Please try the latest libzmq master, as it contains the above mentioned change.

**Comment by hitstergtd** [comment]
Issue fixed as described above.
