### ISSUE TITLE
Problem: API has mix of draft and stable

### ISSUE THREAD

**Issue by hintjens** [zeromq/libzmq#1876]
We would like to ship a 4.2 stable that includes draft APIs, e.g. client/server/radio/dish.

Solution: this is a sketch of several pieces taken from zproject. This issue is for discussion.
- break zmq.h, internally, into classes and mark each as draft/stable using tags in comments
- add documentation for each method directly into zmq.h, as alternative to hand-written man pages (we can generate selectively)
- adapt zproject's `mkman` tool for this.
- consider sample/test code that can be included in each man page (like zproject)

**Comment by msteinhoff** [comment]
Hm, I only understand half, but wouldn't this be a nice opportunity to introduce zproject into libzmq?

**Comment by somdoron** [comment]
I like the splitting the file suggestion.

It might be not related but I would like to see the zmq API replaced by the CZMQ API one day. It least for zsock, zframe and zmsg API.

**Comment by hintjens** [comment]
Using zproject for libzmq is... not a bad idea at all... 

As regards APIs, I think the current process of slowly bringing CZMQ-level functionality into libzmq is good, especially if we have all the tooling for testing & documenting it.

**Comment by bluca** [comment]
This was solved a while ago with the introduction of the build time draft switch.
