### ISSUE TITLE
How could I clear the send queue of a DEALER socket  ?

### ISSUE THREAD

**Issue by pengweichu** [zeromq/libzmq#1890]
I would like to know how could I clear the send queue of  a DEALER socket.

In my app create a lot of DEALER sockets to connect a lot of servers and send messages to them(per server per socket). I'm using one thread to manage these DEALER sockets(in the thread loop use zmq:poll to monitor the events).

My question is for the keep-alive, each socket send the "keep-alive" message in every 5 secs and expect server replied it, there has a mKeepAlivePending flag which will be set to true after send the keep-alive message, and set to false after received response. If the mKeepAlive flag is true, the app won't continue send keep-alive message.

If the server is down before received the keep-alive message from my app, then message will be stored into send queue and resend it automatically once server is restart, this is fine.

But after server received keep-alive message and before replied to my app, the server is down(crashed), then in my app, the mKeepAlivePending flag is always true, so the keep-alive will doesn't send again - this mean my app will never know the server is restart, in the case, my have below options:
1. My app continue to send the keep-alive message if it don't received server reply, there has a big problem - if the server is down in a few hours, or 1 day, two days, a lot of message will be stored into the queue.
2. If I set the ZMQ_SNDHWM option, the thread will be blocked once the high water mark is reached, but in my app, I use only 1 thread to manage the ZMQ sockets, once the thread is blocks, the app can't manage other servers. If I create the thread for each DEALER socket, it will cost the performance - there has about 100 -200 servers.

Above all, I have two questions:
1. Does there has any way to clear the send queue of the DEALER socket ? 
2. Does there has any way to let the thread don't blocks with ZMQ_SNDHWM option on DEALER socket ?

Thanks!

**Comment by sigiesec** [comment]
Regarding your second question: Use the ZMQ_DONTWAIT flag when calling zmq_send as described at http://api.zeromq.org/4-1:zmq-send

**Comment by bluca** [comment]
ZMQ_DONTWAIT as Simon said will help, and also using the protocol's heartbeat option will help for the other problem by automatically dropping queues of disconnected peers, without having to do it at the application level. Hence closing.
