### ISSUE TITLE
Large Send data integrety issue

### ISSUE THREAD

**Issue by sunkin351** [zeromq/libzmq#1899]
I am working on a file transfer system built on top of libzmq using the zmqpp bindings on the Windows platform, and have run into a small (Or large, depending on how you look at it) issue to where a file is corrupted during transport. I am not testing this across computers (yet). 

Simply connecting a client thread to a server thread, successfully reading a file into memory, sending it over this connection, and writing it back to disk in a different location. This works fine on a 12 byte text file. However, I test it on a 95KB *.pdf file, and I cannot open the copy due to corruption of data.

I have set up this project over about a dozen source files. If you like, I can post it here via zip file.

**Comment by hintjens** [comment]
I suggest you add a simple checksum and sequence nbr to each block and
assert if you get a checksum or sequence error.

**Comment by sunkin351** [comment]
So you do suggest that I split the file into smaller pieces...
how small?

**Comment by hintjens** [comment]
Please read chapter 7 of the guide, which explains this in detail.

**Comment by sunkin351** [comment]
Nvm, Just set up a test to see if it was actually something with the library. Passed with flying colors. Must be something I am doing with the file data...
