### ISSUE TITLE
OpenPGM support in CMakeFile.txt

### ISSUE THREAD

**Issue by hitstergtd** [zeromq/libzmq#1904]
Add OpenPGM support in the CMAKE build infrastructure.
- OpenPGM support already exists for MSVC builds
- Needs to be added for Linux / FreeBSD / OS X
- See the `WITH_OPENPGM` related references in `src/CMakeFile.txt`

**Comment by bluca** [comment]
Fixed by https://github.com/zeromq/libzmq/pull/2183
