### ISSUE TITLE
TIPC build support in CMakeFile.txt

### ISSUE THREAD

**Issue by hitstergtd** [zeromq/libzmq#1905]
Add Linux-only TIPC build support in the CMAKE build infrastructure.

* See `WITH_VMCI` build option in `src/CMakeFile.txt` for a template
* Update `tests/CMakeFile.txt` to use a `WITH_TIPC` variable

**Comment by bluca** [comment]
Closing, as this was fixed with https://github.com/zeromq/libzmq/pull/1910 (didn't even realize there was this issue open :-) )

**Comment by hitstergtd** [comment]
@bluca - Thanks!
