### ISSUE TITLE
Increase Test Coverage from ~75% to higher

### ISSUE THREAD

**Issue by hitstergtd** [zeromq/libzmq#1907]
**Problem:**
Existing test coverage (as per Coveralls.io) hovers around ~75% and should be much higher.

**Solution:**
- Analyse results of:
  - `./configure --enable-code-coverage`
  - `make check-code-coverage` by using `lcov(1)` and `genhtml(1)`.
- Check effectivity of existing tests in `tests/`
- Write more tests or amend existing ones to increase test coverage

**Comment by somdoron** [comment]
can you tell which part of the projects are not covered?

**Comment by hitstergtd** [comment]
@somdoron -
I will put up the report this weekend, which displays parts which are not covered. I think it is more to do with code paths which are not walked (testing of error conditions, corner cases, etc.), and it would be good to do that because we seem to have some sticky issues (mailbox related, timeouts, hangs, etc.), which haven't had a conclusive outcome.

I am also using it contrast with the Coverity scans I have been working on. If you are interested, I would be more than happy to share them with you. I will add you to them if you like?

**Comment by somdoron** [comment]
yes please. I think it is a nice badge to put on the libzmq readme, and 75 is low, but we need to check how much it is real...

**Comment by hitstergtd** [comment]
Doron, definitely.

Both - having a good test coverage level and the Coverity badge. I am fairly certain that the Test coverage could simply be improved by augmenting the existing tests wherever possible to test some of the less travelled paths, e.g. deliberately triggering error states and catching them with assertions, etc.

I am putting up the LCOV report here:
<https://people.freebsd.org/~hmp/zeromq/libzmq/lcov-report-18042016/>

Unfortunately, code coverage does not seem to work well on OSX, so I had to run it on Linux. The report is the final output of the `make check-code-coverage` command, which can be enabled by running ./configure with the `--enable-check-code-coverage` option.

See the the similarity in the numbers? I believe it is the same thing that the Coveralls.io service does.

**Comment by bluca** [comment]
You can check on coveralls: https://coveralls.io/builds/5983858
It just uses the gcov output from one of the ci runs as you can see on Travis.
Because of this, all the paths from other oses like Windows will appear as not covered of course

**Comment by hitstergtd** [comment]
@bluca,

Thanks, I kept looking for the link!

Yeah those reports are good as a first glance, but I find their output not be as easy as the original lcov output. Nevertheless, the main advantage is that they allow us to constantly keep our eyes on them.

**Comment by bluca** [comment]
Besides the parts that are ifdef'ed out, I think the real weak spot is IPv6. There is no coverage besides some small tests I added a short while ago. We've already been bitten by that badly, as a public API was broken between stable releases: https://github.com/zeromq/zeromq4-1/issues/114

**Comment by hitstergtd** [comment]
On that note, there are no tests for OpenPGM, either. The Windows stuff could surely receive a boost.

**Comment by hitstergtd** [comment]
Maybe we also need to look at re-tooling the test approach and ensure we have full coverage on all the available public API flags, parameters, etc.

**Comment by bluca** [comment]
Let's start small :-) For example, I think the ipv6 test utility is broken on Windows. Would be nice if a WIndows developer could confirm and eventually fix it, and then we can start adding more v6 tests.

**Comment by hitstergtd** [comment]
@bluca 
Ack. :-) Which IPv6 test utility are you referring to, `test_unbind_wildcard`? I will attempt a stab at that.

**Comment by bluca** [comment]
Yes the one used by those tests, is_ipv6_available() in tests/testutil.hpp

**Comment by hitstergtd** [comment]
OK. I have a Windows box ready anyway, so I will put it on my list.
