### ISSUE TITLE
Assertion failed. mailbox.cpp:84

### ISSUE THREAD

**Issue by proalgo** [zeromq/libzmq#1908]
Hi. I'm relatively new to ZeroMQ, working on a project that utilizes PUB-SUB pattern. Multiple clients subscribe with a central server, awaiting notifications etc. Both, clients and the server utilize the monitor to watch out for the events. 

Everything runs fine when initially starting the central server and then the clients, which subscribe with the server. Problems begin when more than one client is started before the server is started. Occasionally the assertion in the mailbox.cpp:84 is thrown. Why? It seems something is wrong with the mailbox queue. This bug is guaranteed to occur when starting the server, then its clients and then shutting down the server and starting it again. 

How such assertion could be prevented? I do not have a guarantee that the server will be always started before the clients.
Best!

**Comment by somdoron** [comment]
you are probably using the socket from multiple threads which is no supported by the pub/sub sockets. You can use radio-dish sockets (very similar to pubsub) which you can use from multiple threads.

**Comment by hitstergtd** [comment]
@proalgo 

Thanks for the report. In order for the project to classify it properly, could you please:

* Tell us about your platform (Windows, Linux, etc.)
* Provide a test case which leads to this issue

**Comment by bluca** [comment]
Closing as there was no reply in half a year
