### ISSUE TITLE
Linger -1 is still not working correctly

### ISSUE THREAD

**Issue by thehesiod** [zeromq/libzmq#1922]
https://github.com/zeromq/libzmq/issues/919 noted that https://github.com/zeromq/libzmq/pull/1511 seemed to fix the issue, however based on more testing it seems the fix is not complete.  In a scenario I have, a stable PULL socket, with multiple dynamic PUSH sockets, the last message may not get sent before close().  I have validated that by sending HWM +1 messages of size SNDBUF that the last message will then get delivered.  This is a really bad issue as it involves data loss. I'll try to get a testcase extracted from my application soon.  I'm guessing there's some extra OS level buffering that's not being accounted for.

**Comment by bluca** [comment]
Hi,

A minimal test case would be definitely very useful to hunt this down. On what platform are you experiencing this?

**Comment by thehesiod** [comment]
I'm working on it, unfortunately it's proving difficult to reproduce outside my application this time.

**Comment by thehesiod** [comment]
looks like histergtd may have reproduced it: https://github.com/zeromq/libzmq/issues/1264.

**Comment by hitstergtd** [comment]
@thehesiod - thanks, I will put up the test case as a gist, which is based on the original in #1264.

**Comment by thehesiod** [comment]
@hitstergtd cool! btw I just reproduced mine in a test app as well (finally!)  I'll try whittling it down to a more manageable size/scenario.

**Comment by hitstergtd** [comment]
Excellent!

**Comment by thehesiod** [comment]
@hitstergtd Mine is proving elusive to fully understand, may take me some time :(  This is a really really difficult bug to make a testcase for.

**Comment by thehesiod** [comment]
I got it!  HOLY COW was this hard to figure out how to get it to reproduce in a testcase.  And of course it always happens in our app :)  The trick it seems is sending the right amount of data, and having the right delay between the receiver and senders, furthermore, it seems only linux based systems are affected.  It does not reproduce on my mac. The below testcase works by having one PULL socket, and multiple PUSH sockets in a ProcessPool.  It will send several large chunks of data, and at the end send a small Terminator.  The receiver is told how many terminators to expect, so if it hangs it means one or more terminators didn't make it due to LINGER not working correctly.  Not a workaround in there is if you set SEND_EMPTY_MSG to True, it will try to flush out the HWM / SNDBUF.  This seems to cause the Terminator to get flushed out.  So the end result is that LINGER appears to still not be obeyed on certain systems.  This is a really important issue for us to get resolved. Thanks!

Here's the system it reproduces on:
```
bash-4.3# uname -a
Linux b4ebe434f01e 4.4.5-15.26.amzn1.x86_64 #1 SMP Wed Mar 16 17:15:34 UTC 2016 x86_64 GNU/Linux
bash-4.3# cat /etc/*release*
PRETTY_NAME="Debian GNU/Linux 8 (jessie)"
NAME="Debian GNU/Linux"
VERSION_ID="8"
VERSION="8 (jessie)"
ID=debian
```

versions of zmq:
```python
>>> zmq.zmq_version_info()
(4, 1, 5)
>>> zmq.pyzmq_version_info()
(15, 3, 0, inf)
```

And the magic code :)
```python
#!/usr/bin/env python3.5
import zmq.asyncio
import zmq
import asyncio
import pickle
import concurrent.futures
import logging
import time
import tempfile
import traceback

class Terminator:
    pass

# NOTE: setting this to true causes the Terminators to get flushed out
SEND_EMPTY_MSG = False
_SEND_BUFFER_SIZE = 16 * 1024

class _EmptyMsg:
    def __init__(self):
        self.dummy = 'a' * _SEND_BUFFER_SIZE

class SocketCtx:
    def __init__(self, socket_type, high_water_mark: int, socket_name: str, connect_method_name: str, zmq_ctx: zmq.asyncio.Context = None):
        """
        Creates a ZMQ socket context object which ensures that `Terminator` is received last.

        :param socket_type: type of socket
        :param high_water_mark: high water mark
        :param socket_name: name to pass to connect_method
        :param connect_method_name: either "bind" or "connect"
        :param zmq_ctx: zmq.asyncio.Context to use (will not destroy during aexit).  Pass None to have this class construct and own the context.
        """
        self._zmq_ctx = zmq_ctx
        self._socket = None
        self._socket_type = socket_type
        self._socket_name = socket_name
        self._high_water_mark = high_water_mark
        self._connect_method_name = connect_method_name
        self._pending_terminator = None
        self._our_ctx = zmq_ctx is None

    @property
    def name(self):
        return self._socket_name

    async def __aenter__(self):
        assert not self._socket

        if self._our_ctx:
            self._zmq_ctx = zmq.asyncio.Context()

        self._socket = self._zmq_ctx.socket(self._socket_type)
        self._socket.RCVHWM = self._socket.SNDHWM = self._high_water_mark

        getattr(self._socket, self._connect_method_name)(self._socket_name)

        return self

    async def __aexit__(self, exc_type, exc_val, exc_tb):
        try:
            if self._socket:
                if self._socket_type == zmq.PULL:
                    # pull everything from our in_queue so we don't hang on socket.close()
                    try:
                        while True:
                                await self.recv_pyobj_noblock()
                    except zmq.error.Again:
                        pass
                elif self._socket_type == zmq.PUSH and SEND_EMPTY_MSG:
                    for i in range(self._high_water_mark + 1):
                        await self.send_pyobj(_EmptyMsg())
        finally:
            if self._our_ctx:
                self._zmq_ctx.destroy()  # will close all sockets associated with context and linger until all data sent
                self._zmq_ctx = None
                self._socket = None
            elif self._socket:
                self._socket.close()
                self._socket = None

    async def send_terminator(self, **attributes):
        terminator = Terminator()
        for n, v in attributes.items():
            setattr(terminator, n, v)

        return await self.send_pyobj(terminator)

    async def recv(self, *args, **kwargs):
        return await self._socket.recv(*args, **kwargs)

    async def _recv_pyobj(self, *args, **kwargs):
        # this method will filter out _EmptyMsgs
        while True:
            data = await self.recv(*args, **kwargs)
            pyobj = pickle.loads(data)
            if pyobj.__class__ is _EmptyMsg:
                continue
            return pyobj

    async def recv_pyobj_noblock(self):
        # If self._pending_terminator is set, will return all pending messages in the socket's in-queue and
        # then return the terminator last.  Otherwise will raise zmq.error.Again if there are no more pending messages.
        try:
            return await self._recv_pyobj(zmq.NOBLOCK)
        except zmq.error.Again:
            if self._pending_terminator:
                pyobj = self._pending_terminator
                self._pending_terminator = None
                return pyobj
            raise

    async def recv_pyobj(self, *args, **kwargs):
        if self._pending_terminator:
            return await self.recv_pyobj_noblock()

        pyobj = await self._recv_pyobj(*args, **kwargs)

        # If we got a Terminator, we store this off and first try to send any messages
        # that are available in the socket queue before returning the Terminator.
        if pyobj.__class__ is Terminator:
            self._pending_terminator = pyobj
            return await self.recv_pyobj_noblock()

        return pyobj

    async def send(self, data):
        return await self._socket.send(data)

    async def send_pyobj(self, obj):
        pyobj = pickle.dumps(obj)
        result = await self._socket.send(pyobj)
        return result


def sender(socket_name):
    loop = zmq.asyncio.ZMQEventLoop()
    asyncio.set_event_loop(loop)

    async def doit():
        async with SocketCtx(zmq.PUSH, 2, socket_name, 'connect') as zmq_socket:
            obj = {'a': 'a' * 229114}

            total_sent = 0
            try:
                for i in range(5):
                    await zmq_socket.send_pyobj(obj)
                    total_sent += 1
                    time.sleep(0.5)
                await zmq_socket.send_pyobj(Terminator())
                total_sent += 1
            except Exception as e:
                print(e)

            print("total sent:", total_sent)
            return total_sent

    result = loop.run_until_complete(doit())
    return result


async def receiver(connected_event: asyncio.Event, socket_name, num_terminators):
    async with SocketCtx(zmq.PULL, 2, socket_name, 'bind') as zmq_socket:
        connected_event.set()

        total_received = 0
        while True:
            try:
                pyobj = await zmq_socket.recv_pyobj()
                print("Rcv:", pyobj.__class__, total_received, num_terminators)
                total_received += 1

                if isinstance(pyobj, Terminator):
                    num_terminators -= 1
                    if num_terminators == 0:
                        break

                time.sleep(0.4)

            except:
                traceback.print_exc()

    print("total received:", total_received)
    return total_received


async def ooo_test(loop):
    with tempfile.TemporaryDirectory() as temp_dir:
        socket_name = "ipc://" + temp_dir + "/foobar"
        connected_event = asyncio.Event()

        num_sends = 25
        recvr_task = asyncio.ensure_future(receiver(connected_event, socket_name, num_sends))
        await connected_event.wait()

        num_procs = 6
        executor = concurrent.futures.ProcessPoolExecutor(num_procs)
        total_sent = await asyncio.gather(*[loop.run_in_executor(executor, sender, socket_name) for _ in range(num_sends)])
        print("shutting down")
        executor.shutdown()
        print("total sent:", sum(total_sent))

        await recvr_task

if __name__ == '__main__':
    _loop = zmq.asyncio.ZMQEventLoop()
    asyncio.set_event_loop(_loop)
    logging.captureWarnings(True)

    _loop.run_until_complete(ooo_test(_loop))
```

**Comment by hitstergtd** [comment]
@thehesiod,
Wow that's a big example! It's good you managed to reproduce the issue. It seems I am able to reproduce a hang with much less, on Windows, so it's not just Linux that it happens on. I will post the test case soon; it's based on the code from PR #1264. :)

**Comment by thehesiod** [comment]
ping, any update guys?

**Comment by thehesiod** [comment]
interesting update, this seems to work correctly in the latest pyzmq

**Comment by bluca** [comment]
great! can we close the issue now, then?

**Comment by thehesiod** [comment]
ya, I'll close for now and re-open if it pops up again

**Comment by thehesiod** [comment]
crap, I just remembered that it doesn't happen on OSX, so it's still happening in on ubuntu/debian.  re-opening

**Comment by omaralvarez** [comment]
I am also having this issue on Debian 8 with 4.0.5, the last message is lost due to this bug. I am working with fairly large message sizes, 4 MB more or less. If I sleep before zmq_close() and zmx_term_ctx(), the problem is solved, but this workaround is not great. I still have to test the latest version, is this issue fixed in it? Is it being worked on?

**Comment by bluca** [comment]
Please do check on libzmq master (if you don't want to rebuild you can get deb 8 packages from http://download.opensuse.org/repositories/network:/messaging:/zeromq:/git-stable/Debian_8.0/ )

**Comment by thehesiod** [comment]
ya I wish a core dev would look into this, it's a pretty serious issue IMHO.  We have a hack right now where we flush the 0MQ buffers with junk messages to ensure the real messages get sent.

**Comment by omaralvarez** [comment]
I will test as soon as I can and get back to you guys. Thanks!

**Comment by omaralvarez** [comment]
I have just finished testing 4.2.2, now I have the opposite problem, when I want to close the socket and terminate the context, it just waits eternally. This is the way I am doing it:

```c
printf("Terminating ZMQ context\n");
zmq_close(sim->sender);
zmq_ctx_term(context);
```

**Comment by bluca** [comment]
can you share your code, or a minimal example that reproduces it?

**Comment by omaralvarez** [comment]
Scratch what I said, I need to test further, jzmq is not playing well with 4.2.2, so I'm not sure if it is fixed or not. Tomorrow I'll test further, if I can make it work with jzmq.

**Comment by bluca** [comment]
I would recommend trying to reproduce without bindings, as it will help a lot to reduce complexity and making sure in which layer the problem is

**Comment by thehesiod** [comment]
@kyllingstad seems to have a c example here: https://github.com/zeromq/libzmq/issues/1264

**Comment by bluca** [comment]
I cannot reproduce with that example on Debian with libzmq master unfortunately. Tried a few variations, including sending 4 MB of data, but nothing

**Comment by thehesiod** [comment]
I'll try translating my python example to native

**Comment by bluca** [comment]
Thanks

**Comment by omaralvarez** [comment]
Results are in, `libzmq3-dev_4.2.2+git20170510-0_amd64.deb`works for me. Actually the eternal blocking was correct, my server code was crashing due to jzmq, which left buffers full of unsent messages. With this version it properly waits until everything has been sent to my ZMQ server and then destroy the context.

Now my issue is not having a jzmq version compatible with 4.2.2, which means compiling from source that did not also go well for me. Had to disable tests, and not completely sure it was correctly compiled.

**Comment by bluca** [comment]
IIRC 4.2.x is API-compatible with 4.0.x so it should be fine after rebuilding.
But you'll want to ask that on the mailing list or on the jzmq repository, I'm not familiar with it. I think they were looking for contributors and maintainers if you'd like to help.

**Comment by omaralvarez** [comment]
The issue is not a showstopper it looks for libzmq.so.3, which is not there since now it is libzmq.so.5. I would love to help, but I am more of a C/C++ developer. I will try to help with everything I can. Thanks again!

**Comment by bluca** [comment]
Strange as the jzmq travis CI script runs the latest libzmq and builds fine:

https://travis-ci.org/zeromq/jzmq/jobs/209335374
https://github.com/zeromq/jzmq/blob/master/.travis.yml

But again please ask there as I'm not familiar with it

**Comment by omaralvarez** [comment]
`mvn install --quiet -DskipTests=true` also builds fine for me, as I said disabling tests works. The Maven central repository jar is what has issues with the new ZMQ versions (what looks for old .so). I have already hit them up, I hope the project is still alive.

**Comment by thehesiod** [comment]
cool, trying my python example right now w/ latest debian build

**Comment by thehesiod** [comment]
hmm, first issue I ran into is that the debs from that folder don't have the pkg-config info in them so it's not getting detected by pyzmq, seeing if I can hack around it.

**Comment by bluca** [comment]
pkg-config is there, in libzmq3-dev

**Comment by thehesiod** [comment]
ah ok, used 5, so I tried a build from the official 4.2.2 source and it doesn't seem to have fixed the issue.  Going to try that dev version next

**Comment by bluca** [comment]
no that's the dev package, with headers, symlink, pkgconfig, manpages, you need it to build

you need both libzmq5 and libzmq3-dev to build

**Comment by thehesiod** [comment]
i c, will try with both then :)

**Comment by thehesiod** [comment]
nope, same issue with that build, don't get all the terminators, if I enable `SEND_EMPTY_MSG` to flush out the buffers it works

**Comment by thehesiod** [comment]
let me try a few tweaks to the script to explicitly close the 0mq context

**Comment by thehesiod** [comment]
ya, updated script for best practices managing 0mq context and issue still occurs :(  Note that I call socket.close, the context.destroy, and verified LINGER is -1. Man translating this to c is going to be some work.   @bluca would it be possible to for you to take a look if I make a docker container where you can replace the libzmq to debug?  should be pretty easy, basically when `zmq_ctx_destroy` is called by `pyzmq` see why one or more of them isn't flushing the terminator,  I'm going to do another experiment where I make the Terminator really big to see if that helps.

**Comment by thehesiod** [comment]
so none of the following helped:
- setting `Terminator` size to 8k did not help
- adding a `time.sleep(1)` after `socket.close()` 
- adding a `time.sleep(1)` after `Context.destroy()`
- adding `asyncio.sleep(1)` after sending terminator

this is pretty weird, I'll continue investigating

**Comment by bluca** [comment]
The thing is we really want to take bindings out of the picture, to reduce the scope. It's not just the shutdown, but how it gets there

And it also means we can then add a new test case to avoid regressions

**Comment by thehesiod** [comment]
so this is my attempt at translating the pyzmq issue into native code, unfortunately it doesn't reproduce so I may need to bump this back to @minrk .  I wasn't able to reproduce the whole asyncio message loop because that would be craziness :)  I'm now wondering if this is now a polling issue in pyzmq.

```cpp
#include <unistd.h>
#include <sys/types.h>
#include <errno.h>
#include <stdio.h>
#include <sys/wait.h>
#include <stdlib.h>
#include <stdexcept>
#include <time.h>
#include <zmq.hpp>
#include <string>
#include <vector>
#include <thread>
#include <chrono>
#include <iostream>
#include <mutex>


typedef void (*WorkerFuncPtr)();

#define NUM_PROCS 6
#define NUM_ITERS 4
#define NUM_TERMINATORS  NUM_PROCS * NUM_ITERS

#define TEMP_PATH "/tmp/foobar"
#define SOCKET_NAME "ipc:///tmp/foobar"

inline bool path_exists(const char* name) {
    return access(name, F_OK) != -1 ;
}

void ensure_send(void* socket, zmq::message_t& msg)
{
    // pyzmq uses a poller to only send when we can, see: http://api.zeromq.org/4-2:zmq-poll
    int rc = 0;
    while(1)
    {
        int val = 0;
        size_t val_size = sizeof(val);
        rc = zmq_getsockopt(socket, ZMQ_EVENTS, &val, &val_size);
        if (rc != 0)
        {
            std::cout << "Error setting ZMQ_SNDHWM" << rc << " " << zmq_errno() << std::endl;
            throw std::runtime_error("Error setting ZMQ_SNDHWM");
        }
        
        if(val & POLL_OUT)
        {
            break;
        }
        
        std::this_thread::sleep_for(std::chrono::milliseconds(100));
    }
    
    int nbytes = zmq_msg_send(&(msg.msg), socket, ZMQ_DONTWAIT);
    if (nbytes < 0)
    {
        int rc = zmq_errno();
        if (rc != 0)
        {
            std::cout << "Error sending message rc: " << rc << std::endl;
            throw std::runtime_error("Error sending message");
        }
    }
}

void ensure_hwm(void* socket)
{
    int val = 2;
    int rc = zmq_setsockopt(socket, ZMQ_SNDHWM, &val, sizeof(val));
    if (rc != 0)
    {
        std::cout << "Error setting ZMQ_SNDHWM" << rc << " " << zmq_errno() << std::endl;
        throw std::runtime_error("Error setting ZMQ_SNDHWM");
    }
    
    rc = zmq_setsockopt(socket, ZMQ_RCVHWM, &val, sizeof(val));
    if (rc != 0)
    {
        std::cout << "Error setting ZMQ_RCVHWM " << rc  << " " << zmq_errno() << std::endl;
        throw std::runtime_error("Error setting ZMQ_RCVHWM");
    }
    
}

void sender()
{
    std::string obj_bytes(229139, 'a');
    std::string term_bytes(41, 't');
    
    try
    {
        void* context = zmq_ctx_new();
        void* socket = zmq_socket(context, ZMQ_PUSH);
        
        ensure_hwm(socket);

        int rc = zmq_connect(socket, SOCKET_NAME);
        if (rc != 0)
        {
            std::cout << "Error connecting to socket rc:" << rc << " " << zmq_errno() <<std::endl;
            throw std::runtime_error("Error connecting to socket");
        }
        
        for(int i = 0; i < NUM_ITERS; ++i)
        {
            std::cout << "Sndr iter: " << i << "/" << NUM_ITERS << std::endl;
            
            for(int j = 0; j < 5; ++j)
            {
                zmq::message_t msg(obj_bytes.c_str(), obj_bytes.length());
                ensure_send(socket, msg);
            }
            
            std::cout << "Sending terminator" << std::endl;
            zmq::message_t msg2(term_bytes.c_str(), term_bytes.length());
            
            ensure_send(socket, msg2);
        }
        
        std::this_thread::sleep_for(std::chrono::seconds(5));
        rc = zmq_close (socket);
        if(rc != 0)
        {
            std::cout << "Error destroying context rc:" << rc << " " << zmq_errno() <<std::endl;
            throw std::runtime_error("Error closing socket");
        }

        rc = zmq_ctx_destroy(context);
        if(rc != 0)
        {
            std::cout << "Error destroying context rc:" << rc << " " << zmq_errno() <<std::endl;
            throw std::runtime_error("Error destroying context");
        }
        
        std::cout << "Exiting sender" << std::endl;
    }
    catch(std::exception& e)
    {
        std::cout << "Error in sender " << e.what() << std::endl;
        throw;
    }
}

void receiver(std::mutex* mutex)
{
    try
    {
        zmq::context_t context(1);
        zmq::socket_t socket(context, ZMQ_PULL);
        
        ensure_hwm(socket);
        
        socket.bind(SOCKET_NAME);
        
        std::cout << "Receiver ready" << std::endl;
        mutex->unlock();
        
        int total_received = 0;
        int num_terminators = NUM_TERMINATORS;
        
        while(1)
        {
            zmq::message_t msg;
            bool success = socket.recv(&msg);
            if(!success) {
                throw std::runtime_error("Error receiving message");
            }
            
            char* data = static_cast<char*>(msg.data());
            total_received += 1;
            
            if(data[0] == 't')
            {
                num_terminators -= 1;
            }

            std::cout << "Rcv: " << data[0] << " size:" << msg.size() << " rcv'd: " << total_received << " waiting terms: " << num_terminators << "/" << NUM_TERMINATORS << std::endl;

            if(num_terminators == 0)
            {
                break;
            }
            
            std::this_thread::sleep_for(std::chrono::milliseconds(100));
        }
        
        socket.close();
        context.close();
        std::cout << "Total received: " << total_received << std::endl;
    }
    catch(std::exception& e)
    {
        std::cout << "Error in receiver " << e.what() << std::endl;
        throw;
    }
}

pid_t fork_method(WorkerFuncPtr funcPtr)
{
    pid_t childPID = fork();
    if(childPID >= 0) // fork was successful
    {
        if(childPID == 0) // child process
        {
            funcPtr();
            exit(0);
        }
        else //Parent process
        {
            return childPID; // fall through
        }
    }
    else // fork failed
    {
        throw std::runtime_error("Error forking");
    }
}



int main(int argc, const char * argv[])
{
    try {
        if(path_exists(TEMP_PATH)) {
            unlink(TEMP_PATH);
        }

        std::mutex mutex;
        mutex.lock();
        
        std::thread rcvThread(receiver, &mutex);
        
        // wait for receiver to be ready, should use event
        mutex.lock();
        
        std::vector<pid_t> workers;
        for(int i = 0; i < NUM_PROCS; ++i)
        {
            workers.push_back(fork_method(sender));
        }
        
        std::cout << "Waiting for sends to complete" << std::endl;
        for (auto pid : workers) {
            int status = 0;
            while (-1 == waitpid(pid, &status, 0));
            if (!WIFEXITED(status) || WEXITSTATUS(status) != 0) {
                std::cout << "Process " << pid << " failed with status: " << status << std::endl;
                exit(1);
            }
        }
        
        std::cout << "Waiting to receive all terminators" << std::endl;
        rcvThread.join();
    } catch (std::exception& e) {
        std::cout << "Error occurred " << e.what() << std::endl;
    }

    return 0;
}
```

**Comment by thehesiod** [comment]
ok opened https://github.com/zeromq/pyzmq/issues/1015, will see what @minrk is able to find.  Let me know if I can help in any way!

**Comment by thehesiod** [comment]
I got it to reproduce with native code!  Sorry @minrk for the bother.  I've updated the native example to remove a sleep I had put before the sender's socket close.  @bluca mind taking a look?

**Comment by bluca** [comment]
thanks, i'll have a look later

**Comment by bluca** [comment]
fails to build for me:

```
test.cpp: In function ‘void ensure_send(void*, zmq::message_t&)’:
test.cpp:54:37: error: ‘zmq_msg_t zmq::message_t::msg’ is private within this context
     int nbytes = zmq_msg_send(&(msg.msg), socket, ZMQ_DONTWAIT);
                                     ^~~
In file included from test.cpp:9:0:
zmq.hpp:388:19: note: declared private here
         zmq_msg_t msg;
                   ^~~
```

**Comment by bluca** [comment]
I've "translated" that test into a libzmq unit test (eg: C only, no cppzmq bindings, no forks).
I think I've captured all the points, including the sleeps, but it passes just fine.

Did I miss something?

https://gist.github.com/bluca/3afe928d0d0ad65b3b32bdc4453af250

**Comment by thehesiod** [comment]
ya I had to hack the hpp to not have `msg` private, I'll fix that so you can try my test.

**Comment by bluca** [comment]
Do you see instead what's missing in the unit test? I'd rather have that so that it can be added to the suite, and it can remove the additional bindings from the picture

**Comment by thehesiod** [comment]
well first I want you to be able to repro the problem, then we can get your unittest to repro :)

**Comment by thehesiod** [comment]
ok, see: https://gist.github.com/thehesiod/281b539147affedd5cc942880c5fa311

steps to build + run:
```
 docker run --rm -ti debian
 apt-get update
 apt-get install -y clang wget libsodium13 libunwind8 libpgm-5.1-0 vim
 cd /tmp
 wget http://download.opensuse.org/repositories/network:/messaging:/zeromq:/git-stable/Debian_8.0/amd64/libzmq5_4.2.2+git20170510-0_amd64.deb
 wget http://download.opensuse.org/repositories/network:/messaging:/zeromq:/git-stable/Debian_8.0/amd64/libzmq3-dev_4.2.2+git20170510-0_amd64.deb
 dpkg -i libzmq3-dev_4.2.2+git20170510-0_amd64.deb libzmq5_4.2.2+git20170510-0_amd64.deb
 clang++ -std=c++11 -lzmq -lpthread test.cpp -o test
```

**Comment by thehesiod** [comment]
on my docker w/ 4 CPUs it hangs since it doesn't receive all the terminators.  I have a feeling it's related to using multiple processes

**Comment by bluca** [comment]
The contexts are different, so don't think so, also seems to work fine over tcp
I don't see any different with the C unit test, so it might very well be down to the cppzmq binding

**Comment by thehesiod** [comment]
I don't think so, like i said it repros with python which doesn't use the cppzmq binding.  OK I'll remove the cpp binding, gimme a few minutes.

**Comment by thehesiod** [comment]
ok updated my gist, removed the hpp and wrote my own simple wrappers based on the hpp

**Comment by thehesiod** [comment]
hah, you were right, it's not related to forked processes, I just updated the gist again to support threaded senders and it still happens.

**Comment by thehesiod** [comment]
btw, I just tried your test and it hung in my docker container

**Comment by bluca** [comment]
interesting, I'll try to run it a few more times

**Comment by thehesiod** [comment]
btw increasing the receiver sleep between receives may help, here's my docker proc info (x4) btw:
```
root@77cffe6c5abe:/tmp# cat /proc/cpuinfo
processor	: 0
vendor_id	: GenuineIntel
cpu family	: 6
model		: 70
model name	: Intel(R) Core(TM) i7-4870HQ CPU @ 2.50GHz
stepping	: 1
cpu MHz		: 2493.995
cache size	: 6144 KB
physical id	: 0
siblings	: 1
core id		: 0
cpu cores	: 1
apicid		: 0
initial apicid	: 0
fpu		: yes
fpu_exception	: yes
cpuid level	: 13
wp		: yes
flags		: fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ss ht pbe syscall nx pdpe1gb lm constant_tsc rep_good nopl xtopology nonstop_tsc eagerfpu pni pclmulqdq dtes64 ds_cpl ssse3 sdbg fma cx16 xtpr pcid sse4_1 sse4_2 movbe popcnt aes xsave avx f16c rdrand hypervisor lahf_lm abm fsgsbase bmi1 avx2 bmi2 erms xsaveopt arat
bugs		:
bogomips	: 4987.99
clflush size	: 64
cache_alignment	: 64
address sizes	: 39 bits physical, 48 bits virtual
power management:
```

**Comment by thehesiod** [comment]
ya, removing the receive sleep makes the issue go away.

**Comment by thehesiod** [comment]
Oh and just in case this affected anything (I've seen this before), I added a printf to your test case in the receiver to let me know if it hung.

**Comment by thehesiod** [comment]
any updates?

**Comment by bluca** [comment]
Sorry, didn't have time to dive in just yet

**Comment by thehesiod** [comment]
btw I've just found in our prod system my workaround of setting the buffer size and flushing data that is larger than the buffer size still occasionally results in messages not getting flushed :(

**Comment by isedev** [comment]
This reproduces it the issue for me:
```
#!/bin/env python

import sys
import zmq
import time
import multiprocessing as mp

def producer(pid, path):
    ctx = zmq.Context()
    sock = ctx.socket(zmq.PUSH)
    sock.set(zmq.SNDBUF, 128 * 1024)
    sock.set(zmq.SNDHWM, 2)
    sock.bind(path)
    count = 0
    msg = b'0' * 28 * 1024
    for i in range(128):
        sock.send(msg)
        count += 1
    sock.close()
    print("producer {}: sent {} messages".format(pid, count))
    
def consumer(pid, path):
    ctx = zmq.Context()
    sock = ctx.socket(zmq.PULL)
    sock.set(zmq.RCVBUF, 128 * 1024)
    sock.set(zmq.RCVHWM, 2)
    sock.set(zmq.RCVTIMEO, 3000)
    sock.connect(path)
    count = 0
    while True:
        try:
            msg = sock.recv_string()
        except zmq.error.Again:
            break
        count += 1
        time.sleep(0.1)
    sock.close()
    print("consumer {}: received {} messages".format(pid, count))

if __name__ == '__main__':
    path = 'ipc:///tmp/exp/pushpull'
    p1 = mp.Process(target=producer, args=(1, path))
    c1 = mp.Process(target=consumer, args=(1, path))
    c2 = mp.Process(target=consumer, args=(2, path))
    p1.start()
    c1.start()
    c2.start()
    p1.join()
    c1.join()
    c2.join()
```
Output:

> producer 1: sent 128 messages
> consumer 1: received 63 messages
> consumer 2: received 63 messages

Python 3.6.5
pyzmq 17.0.0
libzmq.so.5.0.2
on Fedora 26

**Comment by thehesiod** [comment]
@isedev make sure to call http://pyzmq.readthedocs.io/en/latest/api/zmq.html#zmq.Context.destroy as I think destroy is what is supposed to flush the messages per the `LINGER` setting.
But ya I'm still seeing this too.

**Comment by thehesiod** [comment]
thanks for the better test case!  Hopefully @bluca can try with yours and find the underlying issue.  Would be really nice to have this fixed.

**Comment by bluca** [comment]
Please provide the example using just libzmq, no bindings/wrappers

**Comment by thehesiod** [comment]
@bluca looks like my original test still hangs: https://github.com/zeromq/libzmq/issues/1922#issuecomment-301324624   I updated the steps for the current jessie release

**Comment by isedev** [comment]
Not sure if this is relevant, but same result against the head of the master branch.

**Comment by smokes2345** [comment]
I'm seeing the issue in python much like @isedev  and using some of the pyzmq samples, has there been any progress?

**Comment by thehesiod** [comment]
This is still an issue to my understanding

**Comment by thehesiod** [comment]
posting so this doesn't auto close, kinda bizarre behavior to close bugs that multiple people have reported with multiple test cases

**Comment by bluca** [comment]
It's a bot, it doesn't have a behaviour - the policy as it says is that if nothing happens (not even a comment) within a year, a 2 months countdown is started. Feel free to send a PR to fix the issue.

**Comment by thehesiod** [comment]
I'm closing then to let someone else handle this
