### ISSUE TITLE
Assertion failed: nbytes == sizeof dummy (src/signaler.cpp:202)

### ISSUE THREAD

**Issue by paddor** [zeromq/libzmq#1930]
I'm getting the following error most every time (not always) when running CZTop's test suite on Rubinius at process exit:

```
Assertion failed: nbytes == sizeof dummy (src/signaler.cpp:202)
```

Then the process hangs and hogs the CPU. Any ideas?

**Comment by somdoron** [comment]
What socket type are you using ? Which os? any chance you are using the
socket from multiple threads?

**Comment by paddor** [comment]
Both OSX and Linux. See [here](https://travis-ci.org/paddor/cztop/jobs/126188627). I'm not using the same socket from different threads.

**Comment by somdoron** [comment]
can you provide stack trace?

**Comment by paddor** [comment]
It seems to happen because of the poller specs (CZTop::Poller is based purely on `zmq_poller_*()`). I start the poller specs alone using: `/Users/paddor/.rubies/rbx-brew/bin/rbx -I/Users/paddor/.gem/rbx/2.2.2/gems/rspec-support-3.4.1/lib:/Users/paddor/.gem/rbx/2.2.2/gems/rspec-core-3.4.2/lib /Users/paddor/.gem/rbx/2.2.2/gems/rspec-core-3.4.2/exe/rspec spec/cztop/poller_spec.rb` and it happens sometimes.

The sockets used in the poller specs are mainly PUSH and PULL, but also some DEALER. And one spec uses SERVER/CLIENT. See [here](https://github.com/paddor/cztop/blob/master/spec/cztop/poller_spec.rb).

I'm working on getting a stack trace. Just recompiling ZMQ and CZMQ from master, then running `rbx -d ...` to get more debug information.

**Comment by paddor** [comment]
Sorry, can't get a stack trace from Rubinius, because when this error happens, it just hangs and doesn't react to anything. No stack trace when I `kill -9` it.

**Comment by somdoron** [comment]
that going to be hard...

can you try to reproduce with branch? I'm trying to figure out the errno

https://github.com/somdoron/libzmq/tree/Signaler

**Comment by hitstergtd** [comment]
@paddor / @somdoron,
Perhaps a partial dtrace (OS X) or strace (Linux) can help with this issue?

**Comment by somdoron** [comment]
@paddor few questions just to make sure:

1. Are all sockets disposed before the process exits?
2. The poller get disposed before the process exits?

**Comment by somdoron** [comment]
3. Are you closing the socket before removing it from the poller?

**Comment by paddor** [comment]
Now it has also happened on JRuby, see [here](https://travis-ci.org/paddor/cztop/jobs/127831351).

@somdoron I'll try to reproduce with your branch and try to use dtrace.

I don't know if all sockets and the poller are disposed before the process exits. I'll check.

Actually I don't remove any sockets from the poller in the specs. Should I? Only the specs about removing sockets actually remove a few sockets from the poller.

**Comment by paddor** [comment]
@somdoron Okay, I used your branch, but same error. It ends like this:

```

Finished in 0.39204 seconds (files took 1.99 seconds to load)
79 examples, 0 failures

Assertion failed: nbytes == sizeof dummy (src/signaler.cpp:203)
```

I don't know how to use `dtrace` itself (it wants me to specify probes?) and I'm having trouble starting Rubinius with `dtruss` (which uses the DTrace system). I'm on it...

**Comment by paddor** [comment]
I used the method of attaching `dtruss` to a shortly before started process (`rbx ... spec/.../poller_spec.rb & sudo dtruss -p $!`). After many many tries, it worked (well, failed).

See [this gist](https://gist.github.com/paddor/dcae4ff9f28f27597025986ae99c9f9d). It starts with the end of the test suite.

**Comment by somdoron** [comment]
> Actually I don't remove any sockets from the poller in the specs. Should I? Only the specs about removing sockets actually remove a few sockets from the poller.

You should remove the socket from poller before closing the socket.
If you close the poller first that is not a problem.
It is actually relevant only for thread safe sockets.

I think I found it, just made a commit to the previous repository that might help, can you check?

https://github.com/somdoron/libzmq/tree/Signaler

**Comment by somdoron** [comment]
@paddor I was able to reproduce it with libzmq, it happens when you close a thread safe socket without first remove it from the poller and then close the poller.

I'm sending a PR now, confirm it solve your problem.

**Comment by paddor** [comment]
That sounds great!

So should it not happen anymore or do I have to make sure I remove thread-safe sockets from the poller before the process exits?

With your change, I'm getting this every few tries (process hangs too, has to be killed forcefully):

```
[...]
Finished in 0.43008 seconds (files took 1.68 seconds to load)
79 examples, 0 failures

Invalid argument (./src/mutex.hpp:123)
```
The relative line seems to be [src/mutex.hpp:123](https://github.com/somdoron/libzmq/blob/master/src/mutex.hpp#L123).

**Comment by somdoron** [comment]
Ahh that new bug i guess. Working on that.

No you dont have to remove the socket from poller

**Comment by paddor** [comment]
Thank you very much for your effort. :)

**Comment by somdoron** [comment]
by the way, any chance for stack trace?

**Comment by paddor** [comment]
It's really difficult. I'm trying to use the trick explained [here](http://itreallymatters.net/post/29549982905/generating-thread-dumps-for-ruby-scripts#.VyubXsd6REo).

**Comment by somdoron** [comment]
anyway, try to check with following repository, might solved that, I'm not sure:

https://github.com/somdoron/libzmq

**Comment by somdoron** [comment]
@paddor thanks to @bluca now zeromq prints the stacktrace on assert. 
Make sure to install libunwind before configuring libzmq.

So it should be easier to debug the issue.

**Comment by paddor** [comment]
Using the newly released Rubinius 3.30 (and your fork of libzmq) it looks like the `Assertion` doesn't occur anymore.

**Comment by somdoron** [comment]
@paddor can we close this?

**Comment by somdoron** [comment]
@paddor my patch is no good, but I might still works because another patch, can you retest with zeromq/master latest? also try to test with libunwind installed, this will print stacktrace as well.

**Comment by paddor** [comment]
Sure, I just tried again. It looks pretty stable. I've been running the relevant test suite in a loop for the last 2 minutes. No `Assertion` so far. I'll close this issue. Thanks a lot for your help. :)

**Comment by Wilmord** [comment]
I use libzmq 4.0.4, Which version is this fix for?

**Comment by Wilmord** [comment]
> From 4.2.0 and up

Thanks for response. I am facing this problem while receiving message from socket on windows 7.  
![image](https://user-images.githubusercontent.com/10158000/51179624-65adf000-18c6-11e9-8fdc-16ce7a1c96b8.png)
****

It was working before I did not change anything and it is giving assert now. I think that it is timing. 
So if I assume that I will not see this problem If I upgrade the version, right?

**Comment by bluca** [comment]
Possibly but I can't know for sure, the best way is to try and see what happens
