### ISSUE TITLE
Next release

### ISSUE THREAD

**Issue by tatraian** [zeromq/libzmq#1935]
Hello, 

I plan to use heartbeat functionality of ZeroMQ. As I see it is a new feature in 4.2. Do you know when you plan to release 4.2?

Thanks

**Comment by somdoron** [comment]
It is a great question, I will try to catch up with Pieter on the version and the process.

**Comment by tatraian** [comment]
And an additional question. Does Heartbeat functionality send monitor event if connection lost?

**Comment by somdoron** [comment]
I'm not sure... can you test?

**Comment by hitstergtd** [comment]
I believe it does. Please see:
* Original patch - cbb3b176a62dbd6da15d6c1a82e0dd6d01eb9e17
* The tests for Heartbeats - in `tests/test_heartbeats.cpp` (look for `ZMQ_EVENT_DISCONNECTED`)

**Comment by hitstergtd** [comment]
Please do open a new issue related to your specific question, if you are still having problems. Thanks!
