### ISSUE TITLE
Tag name is wrong

### ISSUE THREAD

**Issue by rikvdh** [zeromq/libzmq#1980]
The release says: v4.0.2-test

**Comment by bluca** [comment]
That's because it was a test :-)
@sappo shall we delete it to all confusion?

**Comment by rikvdh** [comment]
But the name should be v4.2.0-test instead of v4.0.2-test. ;-)

**Comment by bluca** [comment]
Yeah there's also that :-)

**Comment by sappo** [comment]
Yes we should delete it.
Am 11.05.2016 9:27 vorm. schrieb "Luca Boccassi" <notifications@github.com>:

**Comment by sappo** [comment]
Done!

**Comment by bluca** [comment]
Thanks!
