### ISSUE TITLE
Problem: MSVC build configuration inflexible and broken.

### ISSUE THREAD

**Issue by evoskuil** [zeromq/libzmq#1985]
This  relates to [another issue](https://github.com/zeromq/libzmq/issues/1963) but is more extensive.

There are several problems in the MSVC builds presently:

`configure.bat` is defining `HAVE_LIBSODIUM` which is no longer used in the sources, it should define `ZMQ_USE_LIBSODIUM`.

`configure.bat` effectively *requires* use of libsodium if it is found. For this reason the GUI option for selecting use of libsodium was removed. So presently the only way to disable libsodium is to remove the sibling directory or edit the `platform.hpp`

`configure.bat` provides a command line switch in autoconfigure style for enabling or disabling `ZMQ_BUILD_DRAFT_API` and therefore there is also no GUI option provided for it.

The implementation of `configure.bat` does not support similar options for enable/disable of:
* `ZMQ_USE_TWEETNACL`
* `ZMQ_USE_LIBSODIUM`
* `ZMQ_HAVE_OPENPGM`
* `HAVE_LIBGSSAPI_KRB5`
* `ZMQ_STATIC`
* `DLL_EXPORT`

These options (with the exception of the recently-added `ZMQ_USE_TWEETNACL`) are configured via the GUI (and `ZMQ_STATIC` and `DLL_EXPORT` are also controllable via the build command line).

Finally, `ZMQ_HAVE_CURVE` should be set any time that `ZMQ_USE_TWEETNACL` or `ZMQ_USE_LIBSODIUM` is set, however there is no way for `configure.bat` to perform this configuration without knowledge of the intended NaCl configuration.

To resolve these problems `configure.bat` needs to either go away or become much more robust. If it is to become more robust, with a full set of configuration options, the GUI options will be overridden and would therefore need to be removed. Otherwise it could simply go away and `platform.hpp` can become static for Windows (as was previously the case).

The change to a dynamic `platform.hpp` was made to enable build of ZMQ *without* libsodium. The original configuration had hard-coded the enable of libsodium into the `libzmq.props` file. With this removed the option is preserved in the GUI.

The autoconfigure technique doesn't apply well in the case of MSVC projects. One of ht benefits of the solutions is the ability for the GUI to expose options. These options can be saved via the GUI or applied at the build command line. The extra step of running a `configure.bat` eliminates this benefit and due to inflexibility will require building up the same options on its command line - which is itself a UI.

I've got a set of commits pending that resolve this and several other issues in the MSVC builds, preserves the GUI and command line build options, eliminates the need to run `configure.bat` and preserves the ability to build with or without libsodium, regardless of its detected presence.

**Comment by hitstergtd** [comment]
@evoskuil, @somdoron,
Since our Cmake based Windows builds work so well, shouldn't we just get rid of the version specific .sln files? It seems like carrying added cruft which constantly requires updating with rest of the build system. Just a suggestion.

**Comment by evoskuil** [comment]
Hi @hitstergtd 

The MSVC solutions provide a GUI environment that is very useful for navigating the sources, exposing options to users, and debugging. The standardized outputs of the MSVC builds are also used to generate NuGet packaging via `package.gsl` (although with some effort this would be applied to the CMake outputs).

I designed the projects and solutions to be very minimal and largely static. The only files that require an edit when files are added/removed are the `.vcxproj` files (the `.filters` are entirely optional). When configuration options change the corresponding `.props` and `.xml` file require an update. The project `.props` files are really the only necessary customization, although the `.xml` files provide exposure for settings in the UI.

Unfortunately the GUI friendliness tends to lead to commits directly out of the GUI, which does create a lot of cruft. I'll be reverting a bunch of that cruft shortly. These files should only be committed from manual edits.

I do understand that given the additional artifacts and distinct paradigm, changes can be misapplied and artifacts can drift. I avoid this problem in my own projects by generating all build artifacts for all supported build environments. But even without this the current design, if followed, requires very little manual upkeep. The libsodium repository uses the same build system and has kept it immaculate for a long time. And I do think the cost of doing so is worth the benefits to those who use the solutions.

**Comment by hitstergtd** [comment]
@evoskuil,
Thanks for the detailed breakdown on the problem. I agree with you and if your changes are making this problem simpler to tackle then that's a great step forward. I have just refrained from changing the .sln files whenever I have added files to the project because I don't have older MSVC versions to test and that was the reason I was concerned. We can probably modify the AppVeyor environment to build from the .sln files as well to make sure that they work.

**Comment by evoskuil** [comment]
@hitstergtd 

I find that generation of the other versions from the most recent version of VS is sufficient for all versions except for vs2008. I've recommended in the past that vs2008 support be dropped for this reason. I have my own tools that do this locally for `libzmq`, which is how in the past I've kept them from drifting.

The solution files don't need to change unless there is a add/remove of a project (which I haven't seen in 2 years working on `libzmq`). The project and filters file changes are identical across versions (except vs2008).

Building the VS solutions in AppVeyor would go along way to keeping this problem in check.

**Comment by evoskuil** [comment]
It's important to keep in mind that the reason for maintaining MSVC projects is to enable use of Visual Studio. As such we should never prioritize command line building at the expense of features exposed by the environment. At the same time it should always be possible to build from the command line, but this should be kept simple. Batch files really suck when they get beyond trivial.

**Comment by hitstergtd** [comment]
My thoughts are exactly the same, and I would agree that we should drop VS2008 support too. If anyone is interested in building ZeroMQ on Windows, they've three other MSVC versions to choose from out of the box and a fully up to date CMake build. Adding to AppVeyor is definitely something we should do at some point.

@somdoron and @bluca,
Do you guys concur with the above?

**Comment by hitstergtd** [comment]
Agreed @evoskuil.

**Comment by evoskuil** [comment]
Actually **four** other versions to choose from.

**Comment by bluca** [comment]
Sounds sensible to me! But I'm not a Windows user so I don't have a strong opinion on the subject :-)

**Comment by hitstergtd** [comment]
Yes, four other versions. :+1:

**Comment by evoskuil** [comment]
Resolved by #1988
