### ISSUE TITLE
Problem: precompiled header includes are limited to msvc.

### ISSUE THREAD

**Issue by evoskuil** [zeromq/libzmq#1990]
I'm not aware of the rationale for this but I don't see why the pch wouldn't be applicable to non-msvc builds. Are the other builds designed to use pch?

https://github.com/zeromq/libzmq/blob/master/src/precompiled.hpp#L33-L105

**Comment by sunkin351** [comment]
tbh, I have not heard of other compilers making use of precompiled headers. And even if some of the other compilers did, I doubt they would be using the MSVC version.

**Comment by evoskuil** [comment]
Other compilers do provide pch support and the technique is basically the same. For example:

https://gcc.gnu.org/onlinedocs/gcc/Precompiled-Headers.html

**Comment by hitstergtd** [comment]
AFAIK, PCH support in Intel ICC is not compatible with MSVC PCH. So I wonder if supporting PCH in multiple compilers is likely to become a headache, or not.

**Comment by sunkin351** [comment]
My point exactly. I would also think that Unix and Windows compilers would have different symbols in the pch.

**Comment by evoskuil** [comment]
i don't follow. The sources are just existing headers/includes. There is no possibility of incompatibility in the sources.

**Comment by evoskuil** [comment]
See top part of https://github.com/zeromq/libzmq/pull/1992#issuecomment-219212871 for more detail.

**Comment by sunkin351** [comment]
There actually is because compiler directives are a thing, making it so that you can exclude source code based on the OS you are building for. I am very sure libzmq uses this to stay cross-platform.

**Comment by evoskuil** [comment]
@sunkin351 There is no need to exclude source code that is precompiled by one compiler and not by another. In fact it is already merged and working - libzmq is not excluding the `precompiled.cpp/hpp` from compilation. Furthermore it is entirely feasible to implement precompilation in multiple compilers using the same header (or otherwise). My only question in this issue was whether any of the other supported compilers were already configured to do so.

**Comment by evoskuil** [comment]
@hitstergtd I would not consider this a Windows/MSVC build problem. Those builds are fully utilizing precompiled header configuration. This is an issue of the other builds not being configured to use the pch.

**Comment by hitstergtd** [comment]
Ok I will remove the label. I thought so too.
