### ISSUE TITLE
pyzmq

### ISSUE THREAD

**Issue by zhjun2512** [zeromq/libzmq#1993]
import time
import zmq

context = zmq.Context()
socket = context.socket(zmq.REP)
socket.bind("tcp://*:5555")

while True:
    message = socket.recv()
    print("Received request: %s" % message)
    time.sleep(1)
    socket.send(b"World")

This is a hello world server
socket.recv() get a message,but don't get client ip
when server call socket.send(b"world")
how get client ip?

**Comment by sunkin351** [comment]
You cant get the IP of a client unfortunately. (I don't think) What do you need the IP for exactly?

**Comment by hitstergtd** [comment]
#### You could:

1. Try your luck by inquiring the `SRCFD` property of the received message.
2. Attempt to get a Python socket object based on FD obtained from step 1, but this step is dependent on the version of Python you are using:
  * **Python v2** - it is not possible to create a socket object from the actual underlying socket descriptor; you will need to create it using the `fromfd()` method of the socket class, which duplicates the underlying socket descriptor.
  * **However, in Python 3** - you can specify the `fileno` parameter to the `socket()` method of the socket class, and it will return a socket object based on the actual underlying socket descriptor.

3. Call the `getpeername()` method of the socket object from step 2; usual platform-specific `getpeername` caveats apply; it may not even be supported on your platform. The return value is a tuple for IP-based sockets. See Python documentation for the socket module.

#### Examples:
Examples assume your ZeroMQ sockets are TCP on IPv4.

**Python 2:** 
```python
import zmq
import socket as s
# ...
message = socket.recv()
src_fd = message.get(zmq.SRCFD)
print "Socket descriptor of received message: %d" % src_fd
# below returns a new fd, duplicated from src_fd
# socket.error exception will be raised if src_fd is -1 [Errno 9]
src_sock = s.fromfd(src_fd, s.AF_INET, s.SOCK_STREAM)
print "Peer address: %s" % src_sock.getpeername()
# 
```

**Python 3:** 
```python
import zmq
import socket as s
# ...
message = socket.recv()
src_fd = message.get(zmq.SRCFD)
print("Socket descriptor of received message: %d" % src_fd)
# below does not duplicate the underlying socket, as opposed to Python v2...
# src_fd might be -1, in which case ValueError exception will be thrown
src_sock = s.socket(fileno=src_fd)
print ("Peer address: %s" % src_sock.getpeername())
```

#### Please Remember:
The message property `ZMQ_SRCFD` is deprecated from version 4.2+ of the underlying library, i.e. libzmq, so it is expected that newer releases may a return value of `-1` when calling `message.gets()`. It is also important to know that this value could provide socket descriptor IDs, that you weren't expecting.

Copied one of the PyZMQ maintainers (@minrk), in case he can shed light on the matter.

Hope that helps. Closing this issue; if you need more help with this or having any issues, I suggest raising it with the [PyZMQ project](https://github.com/zeromq/pyzmq/).

**Comment by zhjun2512** [comment]
Thank you
