### ISSUE TITLE
Commit used for release

### ISSUE THREAD

**Issue by hevy-CC4477** [zeromq/libzmq#1999]
Hi,

How can I know which commit was used for 4.1.4 release ?

Best,

**Comment by bluca** [comment]
The 4.1 release was made from this repository: https://github.com/zeromq/zeromq4-1

If you are asking for the corresponding commit in this repo, it might be a bit hard to correlate, and I don't think we have an answer at this point unfortunately, you'd have to go through the history to find out

**Comment by hevy-CC4477** [comment]
Thanks, I did not see that you did specific repositories for release.
I am not sure to understand why.
