### ISSUE TITLE
Problem: zmq_poll documentation is incorrect on 3 points.

### ISSUE THREAD

**Issue by evoskuil** [zeromq/libzmq#2006]
According to [documentation](http://api.zeromq.org/2-1:zmq-poll):

> If none of the requested events have occurred on any zmq_pollitem_t item, zmq_poll() shall wait timeout microseconds for an event to occur on any of the requested items.

[Sleep](https://msdn.microsoft.com/en-us/library/windows/desktop/ms686298%28v=vs.85%29.aspx) accepts milliseconds and [usleep](http://linux.die.net/man/3/usleep) accepts microseconds, so clearly the implementation of `zmq_poll` is based on a millisecond timeout parameter:

``` c
int zmq_poll (zmq_pollitem_t *items_, int nitems_, long timeout_)
{
    //  TODO: the function implementation can just call zmq_pollfd_poll with
    //  pollfd as NULL, however pollfd is not yet stable.
#if defined ZMQ_POLL_BASED_ON_POLL
    if (unlikely (nitems_ < 0)) {
        errno = EINVAL;
        return -1;
    }
    if (unlikely (nitems_ == 0)) {
        if (timeout_ == 0)
            return 0;
#if defined ZMQ_HAVE_WINDOWS
        Sleep (timeout_ > 0 ? timeout_ : INFINITE);
        return 0;
#elif defined ZMQ_HAVE_ANDROID
        usleep (timeout_ * 1000);
        return 0;
#else
        return usleep (timeout_ * 1000);
#endif
    }
    ...
}
```

> If the value of timeout is -1, zmq_poll() shall block indefinitely until a requested event has occurred on at least one zmq_pollitem_t.

This works for `Sleep` but `usleep` accepts an unsigned value. As such any negative is implicitly cast to a positive, resulting in an unintended timeout. Also, it is the case that _any_ negative value will result in an infinite sleep (on Windows), the feature is not limited to -1.

> The resolution of timeout is 1 millisecond.

The 1 millisecond resolution mentioned above is accurate for Windows but not for other platforms where the resolution should be 1 microsecond (based on `usleep` parameterization).

> For standard sockets, this flag is passed through zmq_poll() to the underlying poll()

The implementation is not (no longer?) based on the `poll` call. Although the following caveat leaves open the possibility of undocumented limitations, it would be better to document/fix the actual limitations as they are known.

> The zmq_poll() function may be implemented or emulated using operating system interfaces other than poll(), and as such may be subject to the limits of those interfaces in ways not defined in this documentation.

**Comment by evoskuil** [comment]
It's also worth noting that, according to `usleep` documentation, a failure will result on [some systems](http://www.sde.cs.titech.ac.jp/~gondow/dwarf2-xml/HTML-rxref/app/gcc-3.3.2/lib/gcc-lib/sparc-sun-solaris2.8/3.3.2/include/sys/types.h.html) when the `zmq_poll` timeout parameter exceeds 1,000 (1 second) as it causes `usleep` to be called with a value in excess of 1,000,000.
```c
290 /*
291  * Type useconds_t is an unsigned integral type capable of storing
292  * values at least in the range of zero to 1,000,000.
293  */
294 typedef uint_t		useconds_t;	/* Time, in microseconds */
```
But at most the data type `uint_t` accepts 32 bits, so the implicit cast of the `long` timeout parameter results in an overflow possibility even on systems that aren't limited to 1 second sleep. In the case of a -1 timeout parameter `usleep` is actually parameterized with max unsigned int (2^32) or ~4,295 seconds. It's a long time (1.2 hrs), but it's not infinite.

**Comment by somdoron** [comment]
Sleep is only used if empty set.
Previous versions of ZeroMQ used micro seconds, now it is milliseconds.

**Comment by evoskuil** [comment]
> Sleep is only used if empty set.
I don't get your point here.

> now it is milliseconds.
Right, that particular point is about incorrect documentation.

**Comment by evoskuil** [comment]
I've moved my second comment above to an [independent issue](https://github.com/zeromq/libzmq/issues/2007), as it is a bug (vs. documentation).
