### ISSUE TITLE
Problem: unsafe use of usleep can create unexpected results.

### ISSUE THREAD

**Issue by evoskuil** [zeromq/libzmq#2007]
According to `usleep` documentation, a failure will result on [some systems](http://www.sde.cs.titech.ac.jp/~gondow/dwarf2-xml/HTML-rxref/app/gcc-3.3.2/lib/gcc-lib/sparc-sun-solaris2.8/3.3.2/include/sys/types.h.html) when the `zmq_poll` timeout parameter exceeds 1,000 (1 second) as it causes `usleep` to be called with a value in excess of 1,000,000.

``` c
290 /*
291  * Type useconds_t is an unsigned integral type capable of storing
292  * values at least in the range of zero to 1,000,000.
293  */
294 typedef uint_t      useconds_t; /* Time, in microseconds */
```

But at most the data type `uint_t` accepts 32 bits, so the implicit cast of the `long` timeout parameter (on a 64 bit system) results in an overflow possibility even on systems that aren't limited to 1 second sleep. For example, a `long` parameter (after being multiplied by 1000) of 2^32 is cast to an `unsigned int` of 0, resulting in _no_ sleep.

In the case of a -1 timeout parameter (after being multiplied by 1000) `usleep` is actually parameterized with max `unsigned int` (2^32-1) or ~4,295 seconds. It's a long time (1.2 hrs), but it's not infinite.

**Comment by sunkin351** [comment]
So... usleep doesn't have a 64-bit function overload?

**Comment by sunkin351** [comment]
You could use std::chrono's this_thread::sleep_for(std::chrono::miliseconds(NumberOfMilliseconds)) to achieve what you want without usleep.

**Comment by evoskuil** [comment]
@sunkin351 According to documentation `usleep` is unsigned, 32 bit, and limited on some platforms to 100,000 usecs (we are using it as signed, 64 bit, and unlimited usecs).

[std::this_thread::sleep_for](http://en.cppreference.com/w/cpp/thread/sleep_for) requires at least C++11.

**Comment by evoskuil** [comment]
@hitstergtd I wouldn't consider this a documentation issue (that's covered in another issue). Even if that documentation was corrected, this is a bug internal to the implementation.

**Comment by hitstergtd** [comment]
@evoskuil I know it isn't a documentation issue, but it is useful documentation for later on-lookers and lurkers who would like to glean more information on how things work. It is common to see a lot of good explanations, like yours, go down the bin and not become easily searchable. Maybe the label should be re-labelled; any thoughts? :)

**Comment by evoskuil** [comment]
Okay, I thought the tag implied a need to correct the docs. No biggie.

**Comment by hitstergtd** [comment]
Understood. But I can see why you might hold that view. So if you have a different name for this label, that'd be great.

**Comment by evoskuil** [comment]
Maybe `Information`?
