### ISSUE TITLE
[Problem] zmq_bind 'epgm://eth2;239.192.1.1:5555' for 'ODP_S_L_RES_TX': Invalid argument

### ISSUE THREAD

**Issue by PKUKitty** [zeromq/libzmq#2012]
I came across the problem at zmq_bind function for multicast in Linux(Redhat 6.5);  the multicast address is 'epgm://eth2;239.192.1.1:5555'; but the return error of zmq_bind is Invalid argument;
I do not kown where is the problem, and how to set up the network for multicast; tks

**Comment by somdoron** [comment]
Is that the result for all addresses? did you try without the interface name?
