### ISSUE TITLE
libzmq terminates process, when PUSH sockets frequently recreated

### ISSUE THREAD

**Issue by tr1cks** [zeromq/libzmq#2016]
We use libzmq-3.2.5 (builded with VS2010 or VS2013 doesn't matter) in Java application through jzmq-3.1.0. Server is Windows Server 2008 R2 or Windows Server 2012. We noticed that our Tomcat service in some situations dies. Investigation of this problem shows that it happens when:
1. Our service successfully establishing real-time data stream through zmq to other side on it's request.
2. Our service doesn't send data, because currently haven't them. Other side decide to make new request of data stream, that recreate zmq push socket on our side.
3. If it happens concurrently for multiple sockets, libzmq can terminate our service.

Unfortunately we can reproduce it only on our stand and not on unit test. But after adding logging to the file on asserts from err.hpp, we found that it happens in tcp.cpp at method zmq::tune_tcp_socket at setsockopt invocation, that failed with WSAEINVAL error code. Socket descriptor is greater than zero.

Problem reproducing at trunk versions of zmq and jzmq. And looks like that problem was already mention here http://comments.gmane.org/gmane.network.zeromq.devel/26499. Have you any news about this?

**Comment by bluca** [comment]
Should be the same as https://github.com/zeromq/libzmq/issues/2334 fixed by https://github.com/zeromq/libzmq/pull/2492
