### ISSUE TITLE
a named client of the router server crash and immediately connect.  the router server will not receive message.

### ISSUE THREAD

**Issue by shengdoushi** [zeromq/libzmq#2019]
a named client connect (as tcp) to the router socket, and router socket receive message slowly. when a named client crash, router socket's command_t::pipe_term_ack will not receive immediately, except all msg all received.  so at this time, client reconnect, and will find a same name socket in router's outpipes, so place it in anonymous_pipes, and will not handle the new client messages, but save all new client's message in memory.

I view zmq source:  when socket disconnect, zmq io thread put it as a normal msg (as type type_delimiter). so router socket will receive it  after the other content msg.

how I solve this problem?

**Comment by somdoron** [comment]
Use router handover option.

**Comment by shengdoushi** [comment]
which is handover option option? 

I just see three router's option :  ZMQ_ROUTER_RAW, ZMQ_ROUTER_MANDATORY, ZMQ_PROBE_ROUTER.

**Comment by somdoron** [comment]
ZMQ_ROUTER_HANDOVER

It might not be available in your version

**Comment by shengdoushi** [comment]
yes, my version is 4.0.4, there's no ZMQ_ROUTER_HANDOVER option.  i will try another version .
