### ISSUE TITLE
Allow multiple recipients with ROUTER socket

### ISSUE THREAD

**Issue by ZhukovAlexander** [zeromq/libzmq#2027]
Hi all
IMHO, this would be good to be able to use some kind of routing rules when specifying receiver identity. This rules could include:
- _a list of comma separated destinations, e.g._ `"foo,bar,baz"`
- _send all rule, e.g._ `"*"`
- _exclude rule (send to all, except), e.g._ `"-foo"`

Here is an example (in python)

``` python
import zmq

context = zmq.Context.instance()
router= context.socket(zmq.ROUTER)
router.bind("ipc://routing.ipc")

identities = [b'id:1', b'id:2', 'id:3']

# send to both id:1 and id:2 logical destinations
router.send_multipart([b"id:1,id:2", b"Hello to id:1 and id:2!"])

#send to all logical destinations
router.send_multipart([b"*", b"Hello everyone!"])

#send to all logical destinations, except id:2
router.send_multipart([b"-id:2", b"Hello all, except id:2"])
```

I wonder, if it's something, that could be implemented in libzmq? Does it make sense to have such a feature?

**Comment by sunkin351** [comment]
It would be very interesting to see such a feature implemented, though it would increase application/library logic to an unwanted degree. Personally, I can think of a couple different ways to do what you want without altering the library to accommodate. (Though I am a c++ programmer so I don't quite know if what I am thinking of is possible in python.)

**Comment by ZhukovAlexander** [comment]
@sunkin351, sure, this is quite possible to implement as an additional API layer on top of ```pyzmq```.
Though, one of my primary concerns is performance.

**Comment by sunkin351** [comment]
Is it possible for you to switch to a faster language than python, seeing that your concern is performance?

**Comment by sunkin351** [comment]
Speaking of which, now that you have given me the idea, I think I am going to implement this abstraction in C++ according to your specification above using the zmqpp binding. (Probably gonna use whitespaces rather than commas to separate identities I think though.) I will let you know how it goes if you want. :P

**Comment by ZhukovAlexander** [comment]
Is there a way to use ```zmqpp``` together with ```pyzmq```?

**Comment by somdoron** [comment]
Another approach is to use groups, and / remove client from a group and then send to a group.

However I think it should be another layer on top of libzmq.

**Comment by sunkin351** [comment]
> Is there a way to use zmqpp together with pyzmq?

Can python use C++ dynamic linking? Its different than C dynamic linking, which you are using with libzmq in pyzmq...

**Comment by ZhukovAlexander** [comment]
@sunkin351, I'm pretty sure that's possible.

**Comment by sunkin351** [comment]
I am not sure, because of c++ name mangling. Each c++ compiler has their own way of doing it, unlike C, which has a standard to it.

**Comment by ZhukovAlexander** [comment]
Ok, so after some digging into the documentation, I've found that [PUB/SUB does have a prefix matching](http://api.zeromq.org/4-1:zmq-setsockopt) (see, ZMQ_SUBSCRIBE option), which, pretty much, accomplishes what I described.
