### ISSUE TITLE
Using udp pub/sub (radio/dish)

### ISSUE THREAD

**Issue by rodolfo-picoreti** [zeromq/libzmq#2029]
Hi, 

How can I enable the radio dish support on zeromq? I'm getting the following error when compiling:

> error: ‘ZMQ_RADIO’ was not declared in this scope

The code:
```cpp
#include "zmq.hpp"
 
int main (int argc, char* argv[]) {
   zmq::context_t context (1);
   zmq::socket_t publisher (context, ZMQ_RADIO);
   publisher.connect("udp://127.0.0.1:5556");
   ...
}
```

**Comment by bluca** [comment]
Are you building with `--enable-drafts=yes` ?

**Comment by rodolfo-picoreti** [comment]
No... It worked now, thanks!
