### ISSUE TITLE
Make dropping of messages observable

### ISSUE THREAD

**Issue by sigiesec** [zeromq/libzmq#2037]
I would like to be able to observe when messages are dropped (in particular by ROUTER sockets, when the HWM for a peer has been reached).

The overall goal is not to set up a reliable communication in the sense that it guarantees that no messages are lost (I could use sequence numbers, the clone pattern, etc. if I wanted to do that), but I would merely have a limited reliability guarantee that no messages are lost without notice, i.e. if no connection problems are reported AND no messages are dropped deliberately by ZeroMQ, then it is reasonable to assume that no messages are lost.

I can imagine several options for this:
a) asynchronously via the socket monitor
a1) add events ZMQ_EVENT_ABOVE_SNDHWM and ZMQ_EVENT_BELOW_SNDHWM with the peer identity as an attribute (i.e. which would allow reacting somewhat proactively to a HWM situation, and prevent messages being dropped)
a2) add an event ZMQ_EVENT_MESSAGE_DROPPED, with the peer identity as an attribute
b) synchronously by adding some flag ZMQ_MANDATORY, and returning an error (EAGAIN?) on a call to zmq_send

**Comment by sunkin351** [comment]
I would use this. +1

**Comment by somdoron** [comment]
The described behavior already exist within router. when used with ZMQ_NOBLOCK send will return EAGAIN if the watermark has reached. when used with ZMQ_ROUTER_MANDATORY it will return error when the peer does not exist.

Each socket behave differently when watermark is reached.

**Comment by sigiesec** [comment]
@somdoron are you really sure? I cannot reproduce that with either 3.2.5 nor 4.1.5. Even when setting ZMQ_DONTWAIT on the call to zmq_msg_send, it never returns -1 with errno==EAGAIN but still silently drops messages.

I also cannot read this from the documentation, but I must admit it is not completely clear for me:
> ZMQ_DONTWAIT
> For socket types (DEALER, PUSH) that block when there are no available peers (or all peers have full high-water mark), specifies that the operation should be performed in non-blocking mode. If the message cannot be queued on the socket, the zmq_msg_send() function shall fail with errno set to EAGAIN.

The first sentence only mentions DEALER and PUSH socket types. It is unclear whether the second sentence only refers to those situations mentioned in the first sentence (which I thought) or if it applies to any socket type.

**Comment by sigiesec** [comment]
Ok, I see now, ZMQ_ROUTER_MANDATORY must also be set to true in order to get the EAGAIN error (not only for EHOSTUNREACH). And this behaviour did not exist in ZeroMQ 3.2.5.

**Comment by bluca** [comment]
Closing as this is already possible as described
