### ISSUE TITLE
ZMQ_SERVER and ZMQ_CLIENT was not declared in this scope

### ISSUE THREAD

**Issue by rhymerjr** [zeromq/libzmq#2048]
I see this on my Debian 8!
Compiled from development master:
g++ (Debian 4.9.2-10) 4.9.2
automake (GNU automake) 1.14.1
autoconf (GNU Autoconf) 2.69

**Comment by somdoron** [comment]
Did you get from git? 

Which file cause the issue?

**Comment by rhymerjr** [comment]
Yes I got it from git! I did:
git clone https://github.com/zeromq/libzmq


My test code is:

#include <iostream>
#include <string>
#include <zmq.h>
#include <string.h>
#include <stdio.h>
#include <unistd.h>
#include <signal.h>

#include "proto_MCP.pb.h"
#include <google/protobuf/descriptor.h>
#include <google/protobuf/dynamic_message.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/io/zero_copy_stream_impl.h>
#include <google/protobuf/stubs/common.h>

int main (void)
{
    GOOGLE_PROTOBUF_VERIFY_VERSION;

    void *context = zmq_ctx_new ();
    void *client = zmq_socket (context, ZMQ_CLIENT);
   ...
   ...

The error message comes at funtion zmq_socket()...
Now I see that I got the same error for the function zmq_msg_set_routing_id() 

Error message is:

client.cpp: In function ‘int main()’:
client.cpp:20:41: error: ‘ZMQ_CLIENT’ was not declared in this scope
     void *client = zmq_socket (context, ZMQ_CLIENT);
                                         ^
client.cpp:137:51: error: ‘zmq_msg_set_routing_id’ was not declared in this scope
           zmq_msg_set_routing_id (&msg, routing_id);


My compile command is:
g++ -g -lzmq -lprotobuf -std=c++0x client.cpp  proto_MCP.pb.cc -o client

**Comment by somdoron** [comment]
You need to compile libzmq with draft

**Comment by rhymerjr** [comment]
I did the followings:

./autogen.sh
./configure --enable-drafts=yes
make -j 4
make check && make install && ldconfig

But no luck with: g++ -g -lzmq client.cpp -o client

Only works by this: g++ -g -lzmq -DZMQ_BUILD_DRAFT_API=1 client.cpp -o client
Is this OK or I did something wrong?

**Comment by bluca** [comment]
You can do everything manually, but you really should to use pkg-config, as with most libraries that's how you get build flags:

g++ `pkg-config --libs --cflags libzmq` ...

**Comment by ambitslix** [comment]
What about if you install in non-standard location?

**Comment by bluca** [comment]
```
PKG_CONFIG_PATH=/path/to/nonstandard/pkgconfig g++ `pkg-config --libs --cflags libzmq`
```

**Comment by rhymerjr** [comment]
Ok, it works!
Thank you for everyone!

**Comment by Asmod4n** [comment]
@bluca whats the pkg-config equivalent for Windows?
I am currently writing a mruby binding and have a hard time to check if it was build with ZMQ_BUILD_DRAFT_API

**Comment by evoskuil** [comment]
There is no pkg-config equivalent for Windows.

**Comment by bluca** [comment]
Sorry I'm really not familiar with Windows and Visual Studio, so I'll defer to @evoskuil and other Windows devs

**Comment by Asmod4n** [comment]
Guess ill open a new issue then.
