### ISSUE TITLE
ZMQ_RADIO Fedora 23

### ISSUE THREAD

**Issue by ambitslix** [zeromq/libzmq#2049]
OS: Fedora 23

I built master this way:

./autogen.sh
LIBS=-ldl ./configure --prefix=$PREFIX --enable-drafts=yes
make && make install

However when building a simple application:

sf-client.cpp:175:36: error: ‘ZMQ_RADIO’ was not declared in this scope
     void *radio = zmq_socket (ctx, ZMQ_RADIO);

As a workaround I had to set in my source code:

#define ZMQ_BUILD_DRAFT_API

Am I doing the right thing?

Thanks, Mark

**Comment by bluca** [comment]
Use pkg-config, the standard in *nix environments to get build flags:

```
g++ `pkg-config --libs --cflags libzmq` ...
```

If you are using autotools or cmake, there are equivalent macros available.
