### ISSUE TITLE
[Problem] PGM receivers receive other groups data even the receiver did not join that group

### ISSUE THREAD

**Issue by RogerFederer03** [zeromq/libzmq#2056]
Description of problem:
When two or more processes listen for multicast messages by using epgm on the same port
(different multicast groups) they all receive messages sent to the same port.

Steps to Reproduce:
1. on host1 run pgm_receiver "10.1.1.48;239.211.0.83:10083"
2. on host1 run pgm_receiver "10.1.1.48;239.211.0.84:10083"
3. on host2 run pgm_sender   "10.1.1.27;239.211.0.83:10083"
4. type something and hit "enter"

Actual results:
both receiver have reveived the message

Expected results:
only the first process reveices the message
#### The is the receiver:

```
#include <iostream>
#include <string>
#include <zmq.hpp>

using namespace std;

int main(int argc, char** argv)
{
  if(argc < 2){
    cerr << "Not enough args: " << argc << endl;
    return 1;
  }

  string address = argv[1];
  std::string filter("");

  cout << "starting in receive mode" << endl;
  zmq::context_t m_context(1);
  zmq::socket_t m_socket(m_context, ZMQ_SUB);

  string full_address = "epgm://" + address;
  cout << "Binding to " << full_address << endl;

  m_socket.bind(full_address);
  m_socket.setsockopt(ZMQ_SUBSCRIBE, filter.c_str(), filter.length());

  zmq::message_t msg;

  while(1){
    if(!m_socket.recv(&msg,0)){
      cerr << "Error receiving!" << endl;
      return 1;
    }
    string data(static_cast<char*>(msg.data()), msg.size());
    cout << "Message contents: " << data << endl;
  }

  return 0;
}
```
#### This is the sender:

```
#include <iostream>
#include <string>
#include <zmq.hpp>

using namespace std;

int main(int argc, char** argv)
{
  if(argc < 2){
    cerr << "Not enough args: " << argc << endl;
    return 1;
  }

  string address = argv[1];
  string message;

  cout << "starting in send mode" << endl;
  zmq::context_t m_context(1);
  zmq::socket_t m_socket(m_context, ZMQ_PUB);

  string full_address = "epgm://" + address;
  cout << "Binding to " << full_address << endl;
  m_socket.bind(full_address);

  while(1){
    getline(cin, message);
    zmq::message_t msg(const_cast<char*>(message.c_str()), message.size());
    if(!m_socket.send(msg)){
      cerr << "Error sending!" << endl;
      return 1;
    }
    cout << "send successful" << endl;
  }

  return 0;
}

```

**Comment by RogerFederer03** [comment]
Any solutions for that ?

**Comment by rbh02** [comment]
i tried to replicate the above problem and yes both receivers do receive the messages.

**Comment by danleepw** [comment]
I am facing the same problem. May i know any update about this issue? It seems that openpgm won't bind corresponding multicast address on the udp sockets. So, both sockets receive data from both multicast groups.

Do we have any workaround of this issue?

**Comment by jamesdillonharvey** [comment]
I fixed this with a submission to openpgm. 

https://github.com/steve-o/openpgm/pull/52

Define DISABLE_IP_MULTICAST_ALL and hopefully you should get only the traffic you want.

**Comment by bluca** [comment]
Great, thanks. Looks like it's a PGM issue with a build time option so nothing we can do about it, so I'll close this.
