### ISSUE TITLE
Issue a note when another process binds to the same IPC endpoint

### ISSUE THREAD

**Issue by dsuch** [zeromq/libzmq#2059]
Hello,

I have just spent a couple of hours trying to understand why if I bind more than one process to a single IPC endpoint then only the last one actually seems to work, which in the end turned out to be the case explained by @hintjens here:

https://stackoverflow.com/questions/5762809/problems-with-inverted-pub-sub-with-zeromq/13487646#13487646

In hindsight, it's not that I am surprised that I cannot do it - I would like to but if it is not possible then that is OK.

But I just find it confusing and counter-productive that it happens silently - with TCP I have a nice traceback indicating that I cannot bind to the same socket (which is great) and it is surprising that with IPC the behaviour is different.

Again, I understand that this is by design but I would suggest warning/letting a user know about it instead of doing it silently. Naturally, there could be a flag added that would turn these notifications off.

Regards.

**Comment by bluca** [comment]
The problem is that unlike TCP where you get an error on bind I think nothing happens with IPC, so it can't be reliably and easily detected. Updating the documentation to clarify this would be the right thing IMHO.
