### ISSUE TITLE
ZeroMQ will crash in void zmq::select_t::loop ()

### ISSUE THREAD

**Issue by tongjiliubo2005** [zeromq/libzmq#2060]
When I use zmq in windows platform with the latest version, it will crash in function loop at line                
 if (FD_ISSET (fd_entry.fd, &local_fds_set.write)) {
          fd_entry.events->out_event ();
          --rc;
}
and I debug it in VS2013, and found that family_entry.fd_entries was changed by some other thread
while in the for loop. and the local value fd_entry will become timeout and the pointer events will be dirty, so this line will crash.

I suggest we should use reference replace it. 
we can define it as "fd_entry_t& fd_entry = family_entry.fd_entries [i]; " to avoid the crash.

**Comment by bluca** [comment]
Are the same sockets being used from different threads?
