### ISSUE TITLE
zmq_disconnect() causes application crash

### ISSUE THREAD

**Issue by rhymerjr** [zeromq/libzmq#2062]
It happens when ZMQ_CLIENT connects to multiple ZMQ_SERVER and zmq_disconnect() called only once to disconnect from the specified target server.

So, what I did:

zmq_connect (socket_bulkservice, "tcp://10.38.200.188:6661");
zmq_connect (socket_bulkservice, "tcp://10.38.200.188:6662");
zmq_connect (socket_bulkservice, "tcp://10.38.200.188:6663");
zmq_connect (socket_bulkservice, "tcp://10.38.200.188:6664");

I have a recevier thread where I process incoming messages asynchronously and
if the server sends a disconnect request to the client I call zmq_disconnect() only once.

for example : zmq_disconnect (socket_bulkservice, "tcp://10.38.200.188:6661")

and the result is that the whole process will crash!
Is this a normal behavior?

As I understand it, if I call zmq_disconnect(), it shall disconnect from the specified endpoint
and thereafter impossible to send any messages to that endpoint.
But all of the other endpoints must stay in alive and can send/recv messages to and from it!
So it should work?

**Comment by bluca** [comment]
What platform? Could you please provide a minimal test case that reproduces the problem? I tried but I cannot reproduce that on Linux by adding another server to test_client_server.cpp.

**Comment by rhymerjr** [comment]
I'm working on Debian Jessie!

I can share with you the followings:

[recv_thread.txt](https://github.com/zeromq/libzmq/files/365985/recv_thread.txt)
[main_process.txt](https://github.com/zeromq/libzmq/files/365988/main_process.txt)
[p_server_base_mgmt.txt](https://github.com/zeromq/libzmq/files/365987/p_server_base_mgmt.txt)

**main_process.txt:** contains the forked main process what is creating the socket and starting the receiver thread

**recv_thread.txt:** contains the receiver thread. Please look the excluded part of the code!
From "else if( blk.mtype()==blk.BLK_SERVER_EVENT && blk.has_srv_event())"

**p_server_base_mgmt.txt:** server side test code. I started it the following way:
p_server_base_mgmt 6661, p_server_base_mgmt 6662, p_server_base_mgmt 6663, p_server_base_mgmt 6664

**Comment by bluca** [comment]
Would it be possible for you to produce a single, buildable and runnable test case that can reproduce the problem on the model of the existing tests like https://github.com/zeromq/libzmq/blob/master/tests/test_client_server.cpp ?

**Comment by somdoron** [comment]
also some kind of crash report or stacktrace will help

**Comment by rhymerjr** [comment]
OK, I'm unable to reproduce problem by several tests! I'm still investigating...
Is it possible that SIGPIPE causes the issue... ? Will try it soon.

**Comment by rhymerjr** [comment]
Some other part of my code did something wrong I think.
I'm closing this issue because I can't reproduce the problem!
Thanks!
