### ISSUE TITLE
Will the NAT64(IPv6-only Networks) does not support ?

### ISSUE THREAD

**Issue by Jeyamahesan** [zeromq/libzmq#2063]
As per [apple compliance](https://developer.apple.com/news/?id=05042016a), I did the work in accordance with the [procedure](https://developer.apple.com/library/mac/documentation/NetworkingInternetWeb/Conceptual/NetworkingOverview/UnderstandingandPreparingfortheIPv6Transition/UnderstandingandPreparingfortheIPv6Transition.html#//apple_ref/doc/uid/TP40010220-CH213-SW1) but zmq is not connecting and not receiving any data.also it's not showing any errors.Will the NAT64 (IPv6-only Networks) does not support?

Below is the code used to connect,

```
//Objective-C Code Snippet

ZMQContext *zmqContext
ZMQSocket *requestSocket;

/* set up the REQ socket */
requestSocket = [zmqContext socketWithType:ZMQ_REQ];

[requestSocket connectToEndpoint:[NSString stringWithFormat:@"tcp://%@:%lu", ipAddress, (unsigned long)port]];


//In ZMQSocket.h

- (BOOL)connectToEndpoint:(NSString *)endpoint_ {
    self.endpoint = endpoint_;
    const char *addr = [endpoint_ UTF8String];
    int err = zmq_connect(self.socket, addr);
    if (err) {
        ZMQLogError(self, @"zmq_connect");
        @throw [[ZMQException alloc] initWithCode:[[NSString alloc] 
                                                   initWithUTF8String:zmq_strerror(zmq_errno())] 
                                             code:zmq_errno()];
    }
    return YES; 
}

```

Note : I'm using the latest version of zeromq v4.2.0

**Comment by bluca** [comment]
Are you connecting to an IPv6 endpoint? If so, have you enabled IPv6 on the socket before doing that?

**Comment by Jeyamahesan** [comment]
I'm not connecting to IPv6 endpoint, I’m connecting to IPv4 host only, but my network is DNS64/NAT64 network, which is an Pv6-only network that continues to provide access to IPv4 content through translation. Simply, my provider network is IPv4 and I’m translating it to IPv6 network as per [apple compliance](https://developer.apple.com/news/?id=05042016a).

**Comment by bluca** [comment]
The ZMQ connection is just TCP, nothing particular, so I suggest to check the configuration on your hosts and networks.

**Comment by bluca** [comment]
Any updates? Also note that libzmq uses low level BSD socket APIs when connecting over TCP. As a general-purpose library.

If you wish to add support for Apple specific APIs, this could be achieved with build-time detection as we do currently for Windows. Please feel free to send a PR to implement it.
