### ISSUE TITLE
question about ZMQ_SUBSCRIBE 

### ISSUE THREAD

**Issue by zhangtaozt3601** [zeromq/libzmq#2068]
ZMQ_SUBSCRIBE: Establish message filter
A non-empty option_value shall subscribe to all messages beginning with the specified prefix. 

Why only prefix? Why have no other subscribe mode, such as wildcards?
For example, message's prefix is "AABBCC" or "AADDCC", I want subscribe "****CC" to receive both.

**Comment by somdoron** [comment]
I guess it is going back to performance, pubsub should support hundred of thousands (or more) of subscriptions, matching algorithm must be super fast. prefix matching is fast, wildcard or regex are not.

However you can checkout malamute, I think malamute is using regex.

**Comment by zhangtaozt3601** [comment]
Thank you very much.

**Comment by bluca** [comment]
Closing for housekeeping since question was answered.

**Comment by akzi** [comment]
the filter work at sub socket,or at the pub socket.if sub don't call `ZMQ_SUBSCRIBE` to subscribe any thing ,msg will send to pub tcp layer socket ?

**Comment by bluca** [comment]
At the pub socket
