### ISSUE TITLE
Installing ZMQ (ZeroMQ) on Mac OS X El Capitan?

### ISSUE THREAD

**Issue by vatnoise** [zeromq/libzmq#2075]
Hi,
Wasn't really sure on which GitHub repository to open this but hopefully this is the best suited one.

I'm trying to install ZMQ (ZeroMQ) onto OS X 10.11.5 and attach it to PHP.

So far initially I was getting errors like

```
PHP Warning:  PHP Startup: Unable to load dynamic library '/Applications/AMPPS/php-5.4/lib/extensions/ext/zmq.so' - dlopen(/Applications/AMPPS/php-5.4/lib/extensions/ext/zmq.so, 9): no suitable image found.  Did find:\n\t/Applications/AMPPS/php-5.4/lib/extensions/ext/zmq.so: mach-o, but wrong architecture in Unknown on line 0
```

and

```
PHP Warning:  PHP Startup: Invalid library (maybe not a PHP library) 'zmq.so' in Unknown on line 0 
```

But I think I finally managed to beat those compiling zmq.so for PHP with:

```
phpize
CFLAGS="-arch i386" LDFLAGS="-arch i386" ./configure
make
make install
```

Now after compiling the ZMQ library I ended up with files in `/usr/local/lib` like:

```
-rwxr-xr-x   1 root           647564  1 Aug 12:58 libzmq.5.dylib
-rw-r--r--   1 root         23457584  1 Aug 12:58 libzmq.a
lrwxr-xr-x   1 root               14  1 Aug 12:58 libzmq.dylib -> libzmq.5.dylib
-rwxr-xr-x   1 root              936  1 Aug 12:58 libzmq.la
```

But now when I try to launch apache2 it says:

```
dyld: lazy symbol binding failed: Symbol not found: _zmq_version
  Referenced from: /Applications/AMPPS/php-5.4/lib/extensions/ext/zmq.so
  Expected in: flat namespace

dyld: Symbol not found: _zmq_version
  Referenced from: /Applications/AMPPS/php-5.4/lib/extensions/ext/zmq.so
  Expected in: flat namespace
```

So as apache now seems to recognise zmq.so I think it's not a problem with the PHP extension but maybe with something within the system that links the library and the extension?

I've also tried to install the library using `brew install zmq` and it still has the above error of sybmol not being found.

**Comment by bluca** [comment]
I'm really not familiar with PHP and how it works, the only thing I could think off the top of my head is making sure the library files are in the right path.

In general the OSX build seems to be working fine, so it does look specific to the combination of apache + php + php extension + zmq library, so unfortunately I can't be of much help.

But if you do find an issue with our build system please do send a PR to fix it.

**Comment by somdoron** [comment]
You can try the pyzmq repo,  they might be able to help...

**Comment by phuong17889** [comment]
same problem with osx 10.13.3 and AMPPS using php 5.6 :(

**Comment by maxalmonte14** [comment]
I think this can help

https://gist.github.com/mathiasverraes/b66f6117e5cfc92c3fbae37c1d0a3f26
