### ISSUE TITLE
SUB socket receives empty frames - Question

### ISSUE THREAD

**Issue by peske** [zeromq/libzmq#2077]
Although I'm using clrzmq it internally uses libzmq, so I believe that I can get help here.

I have problem with establishing PUB/SUB communication. The problem arises when SUB socket subscribes for all the messages (`subscriberSocket.SubscribeAll()` or `subscriberSocket.Subscribe("")`). If I do so subscriber gets only empty frames. It gets the right number of messages (all the messages sent by the publisher), and all the messages do have the right number of frames (if publisher sends two frame message the subscriber receives two frame message), but **all the frames are empty**.

On the other side, if I subscribe for some term everything works fine. For example if `subscriberSocket.Subscribe("123")` it will get all the appropriate messages (i.e. "12345").

Can you help me with this? Where to start looking for the solution?

Thanks!

**Comment by somdoron** [comment]
Sounds weird,  can you make minimal example tgar reproduce?

**Comment by peske** [comment]
Doron, you're obviously everywhere! I've expected your answer at https://github.com/zeromq/netmq/issues/598, not here :)

Anyway, believe or not, your comment here helped. I've created simplest code snippet to demonstrate the problem, but it turned out that it works. After that I've gone through all my previous code and finally found the problem - it's caused by lazy loading of `IEnumerable`. The problem was at subscriber side, after the message is received. The message itself arrives OK, with all frames with the data. But for the reasons I can't explain here (to better utilize inheritance and polymorphism), I have the following method that "unpacks" the message and returns enumeration of byte arrays, each representing a single frame:

```
protected virtual IEnumerable<byte[]> Unpack(ZMessage message) => message.Select(f => f.Read());
```

If the enumeration is not enumerated _soon enough_, all byte arrays become empty (probably due to some memory cleanup when ZMessage gets out of scope), and my code gets enumeration of empty arrays.

Interesting thing is why I was successfully getting the arrays when there's a subscription term: In this case my code soon after needs to check the first frame (byte array), so the enumeration gets enumerated _soon enough_, and I'm getting all the arrays as expected.

Crazy error, right? The solution is simple: instead returning enumeration my code now returns list:

```
protected virtual IEnumerable<byte[]> Unpack(ZMessage message) => message.Select(f => f.Read()).ToList();
```

Thanks again for helping everywhere! :)

**Comment by peske** [comment]
I apologize for posting this issue here - it turned out to be .NET related, not libzmq.

**Comment by somdoron** [comment]
:-)
