### ISSUE TITLE
There should be one branch per major.minor version series

### ISSUE THREAD

**Issue by aalex** [zeromq/libzmq#2085]
It would be simpler if there was one branch per major.minor series.

Example branches:

master
2.2
3.1
etc.
This way, it would be easy to checkout the latest version for a given major.minor series. (the micro version number are for bug fixes - if using semantic versioning - http://semver.org )

**Comment by bluca** [comment]
There are forks for older releases, please see my other comment: https://github.com/zeromq/libzmq/issues/2086#issuecomment-241099704
