### ISSUE TITLE
There should be one git tag per release

### ISSUE THREAD

**Issue by aalex** [zeromq/libzmq#2086]
In this git reposiroty, there should be one git tag per release.

**Comment by bluca** [comment]
There are, historically libzmq has forked for each major release, so you can find all the past tags on their respective repository in the github org:

https://github.com/zeromq/zeromq4-1
https://github.com/zeromq/zeromq4-x
https://github.com/zeromq/zeromq3-x

etc.

From the next release onward we will follow the C4 process and have only one release from this repository, so future tags will appear here.
