### ISSUE TITLE
ZMQ_MORE vs ZMQ_SNDMORE

### ISSUE THREAD

**Issue by kentlinux** [zeromq/libzmq#2101]
Hi!

I use C++ binding (zmq.hpp) to ZMQ version 4.1.4.

And as I understand there are 2 bugs:

1) There is no method to set property ZMQ_MORE to the message_t class.

2) Flag ZMQ_SNDMORE ignored in socket_t::send(message_t &msg_, int flags_ = 0).
Method socket_t::send(const void *buf_, size_t len_, int flags_ = 0) works fine!

**Comment by hnwyllmm** [comment]
1) ZMQ_SNDMORE is an internal flag for msg_t.
2)
see zmq::socket_base_t::send:
//  At this point we impose the flags on the message.
    if (flags_ & ZMQ_SNDMORE)
        msg_->set_flags (msg_t::more);


my zmq version is 4.1.5, but you can check your version.





在 2016-09-07 15:46:38，"Vladimir Kobylyanskiy" <notifications@github.com> 写道：


Hi!

I use C++ binding (zmq.hpp) to ZMQ version 4.1.4.

And as I understand there are 2 bugs:

1) There is no method to set property ZMQ_MORE to the message_t class.

2) Flag ZMQ_SNDMORE ignored in socket_t::send(message_t &msg_, int flags_ = 0).
Method socket_t::send(const void *buf_, size_t len_, int flags_ = 0) works fine!

**Comment by bluca** [comment]
Hi,

ZMQ_SNDMORE is a flag used when sending a message, and it's fully supported by the zmq_msg_send/zmq_send APIs: http://api.zeromq.org/4-1:zmq-msg-send http://api.zeromq.org/4-1:zmq-send

ZMQ_MORE is a flag used to check if an existing message is part of a multi-part message or not with the zmq_msg_get API: http://api.zeromq.org/4-1:zmq-msg-get

zmq.hpp is in a different repository, so if you have issues with those bindings please open a ticket at https://github.com/zeromq/cppzmq
