### ISSUE TITLE
Problem: zmq_connect with IPv6 "source:port;dest:port" format is broken

### ISSUE THREAD

**Issue by Prachi2807** [zeromq/libzmq#2107]
Following is the snippet of code : 

_void* ctx= zmq_ctx_new();
 void* socket =zmq_socket(ctx,ZMQ_DEALER);
 int opt = 1;
 zmq_setsockopt(socket, ZMQ_IPV6, &opt, sizeof(int));
 int rc1=zmq_bind(socket,"tcp://[::ffff:127.0.0.1]:5559");
assert(rc1==0);
 rc1=zmq_connect(socket,"tcp://[::ffff:127.0.0.1:5552];[::ffff:127.0.0.1]:5558");
assert(rc1==0);
zmq_close(socket);
 zmq_ctx_destroy(ctx);_

output : 
**int main(): Assertion `rc1==0' failed.
Aborted (core dumped)**

Can u tell why it's happening? With IPV4 addresses its working fine.

**Comment by bluca** [comment]
Also you can't both bind and connect the same socket

**Comment by Prachi2807** [comment]
Libzmq version - zeromq-4.1.4

OS - Linux  Version 2.6.32-504.30.3.el6.x86_64 x86_64

**Comment by Prachi2807** [comment]
But when I tried the same code with IPV4 address, its working fine.

**Comment by bluca** [comment]
First of all, there was a new release and there were a couple ipv6 fixes, check 4.1.5.
Then, what is the point of both binding and connecting a socket? Have you tried with 2 different sockets?

**Comment by Prachi2807** [comment]
_void* ctx= zmq_ctx_new();
 void* socket2=zmq_socket(ctx,ZMQ_DEALER);
 int opt = 1;
 zmq_setsockopt(socket2, ZMQ_IPV6, &opt, sizeof(int));
 int rc1=zmq_connect(socket2,"tcp://[::ffff:127.0.0.1]:15000;[::ffff:127.0.0.1]:5558");
 if(rc1!=0)
        printf ("Error occurred during zmq_init(): %s\n", zmq_strerror (errno));
// assert(rc1==0);
 zmq_close(socket2);
 zmq_ctx_destroy(ctx);
 return 0;_

I tried in zeromq-4.1.5
The error now is coming :
**Error occurred during zmq_init(): Invalid argument**

**Comment by Prachi2807** [comment]
Correction :
This is the output   
**Error occurred during zmq_connect(): Invalid argument**

**Comment by bluca** [comment]
Yes I can reproduce the problem in a simple test, thanks for the report. I can have a look early next week as I'm travelling this weekend.

**Comment by Prachi2807** [comment]
Found the issue :
in the file **socket_base.cpp**
inside the function 
_int zmq::socket_base_t::connect (const char *addr_)
{
 1  const char *check = address.c_str ();
  2         if (isalnum (*check) || isxdigit (*check) || *check == '[') {
  3             check++;
  4             while (isalnum  (*check)
  5                 || isxdigit (*check)
  6                 || *check == '.' || *check == '-' || *check == ':'|| *check == ';'
  7                 || *check == ']')
  8             {
  9                check++;
 10             }
 11         }
}_

for zmq_connect with source ipv6addr:port 
value of check = [::ffff:127.0.0.1]:15000;[::ffff:127.0.0.1]:5558
in Line 2, first check is there for '[' and then it will go inside the while loop
in while loop , it will check for alpnum, hexadecimal digit, '.' , '-' , ':', ';', ']'
for the second  square bracket '['  in check ([::ffff:127.0.0.1]:15000;**[**::ffff:127.0.0.1]:5558) will fail, as in the while loop no check is there for opening square bracket.
so  , the correction will be to add opening square bracket as below

 _while (isalnum  (*check)
                || isxdigit (*check)
                **|| *check == '['**
                || *check == '.' || *check == '-' || *check == ':'|| *check == ';'
                || *check == ']')_

**Comment by bluca** [comment]
Yes I found that, unfortunately there's bigger problems than that, bouncing messages with multiple connects seems broken as well, I'll dig deeper on Monday

**Comment by bluca** [comment]
Ah, a silly oversight! Went back and checked again, and the ";" delimiter is to separate source and destination addresses when connecting, not for multiple endpoints: http://api.zeromq.org/4-1:zmq-tcp

For multiple endpoints simply do multiple zmq_connect calls.

That said, the source;dest is indeed broken with IPv6, will send a PR to fix it.

**Comment by Prachi2807** [comment]
Yeah dts wt I told you,  for zmq_connect with source<Ip:port> and
destination<Ip:port>, it was failing. Now , the problem is fixed. That's
good.
