### ISSUE TITLE
Problem: zmq_poll only supports some sockets

### ISSUE THREAD

**Issue by minrk** [zeromq/libzmq#2109]
Users shouldn't have to know whether a socket is threadsafe in order to tell which poll APIs can be used.

Implementing zmq_poll on top of zmq_poller (when available) should solve the issue, and provide a nicer transition path for people already using zmq_poll in their applications.

The only impediment to that is that zmq_poller only returns one event, but this can be fixed as well (#2108).

**Comment by bluca** [comment]
@minrk @somdoron @sigiesec I'm thinking of reverting this, for 2 reasons:

1) Performance of zmq_poll on top of zmq_poller is quite bad, as it has to recreate the poller every time, and there's lots of overhead
2) Many users of zmq_poll want to keep using that, so it's unlikely to go away, like the old socket types

Yes, it's annoying for users of new sockets to be restricted to zmq_poller only, but that was the intention anyway. To use them, application code has to be changed in any case. And those types are still drafts.

Thoughts?

**Comment by somdoron** [comment]
We can avoid the creation of zmq_poller internally by checking if there is any thread safe socket, and revert to old algorithm.

Anyway, I'm favor of reverting this, and direct thread safe sockets users to zmq_poller API.

**Comment by minrk** [comment]
As long as zmq_poller is strictly more functional (accepts at least every socket type zmq_poll does), I've no objection, though I think @somdoron's proposal is better for users (I know it is for me and mine).

> Yes, it's annoying for users of new sockets to be restricted to zmq_poller only, but that was the intention anyway.

I feel like this doesn't take users of language bindings into account. When a new socket type is only the addition of new constants for existing APIs, end users can adopt them without any help from bindings (and optimistic support from bindings is easy and low-risk). A new usually-not-available API like zmq_poller behind ZMQ_DRAFT means that these sockets are much less likely to be usable from a language other than C while the API remains in draft. Reverting this means that draft sockets will not be pollable in pyzmq until pyzmq adds a duplicate implementation of polling with zmq_poller (i.e. not before zmq_poller comes out of draft). All that said, other more important issues like #2941 make the draft sockets approximately unusable in Python or node.js, anyway. But it seems to me like the draft sockets aren't intended to be used from any language other than C, so maybe that doesn't matter so much.

**Comment by bluca** [comment]
> As long as zmq_poller is strictly more functional (accepts at least every socket type zmq_poll does)

Yes, I cannot think of any reason why that should not work, so it should be fine.

> I feel like this doesn't take users of language bindings into account. When a new socket type is only the addition of new constants for existing APIs, end users can adopt them without any help from bindings (and optimistic support from bindings is easy and low-risk). A new usually-not-available API like zmq_poller behind ZMQ_DRAFT means that these sockets are much less likely to be usable from a language other than C while the API remains in draft. Reverting this means that draft sockets will not be pollable in pyzmq until pyzmq adds a duplicate implementation of polling with zmq_poller (i.e. not before zmq_poller comes out of draft). All that said, other more important issues like #2941 make the draft sockets approximately unusable in Python or node.js, anyway. But it seems to me like the draft sockets aren't intended to be used from any language other than C, so maybe that doesn't matter so much.

Sorry if that causes issues! But I don't think it's very feasible to support hybrid builds - there's quite a few places where, if drafts are disabled, the codepath is completely different (this includes zmq_poll by the way - it redirects to zmq_poller only in draft builds already). Trying to use draft APIs or sockets in a standard build is not something that anybody should try, let alone to support. These are intended as a preview for developers, not for production.

I think the best thing we can all do is try to finish up the poller API, at which point the new sockets can be declared stable.

**Comment by bluca** [comment]
That said, I'll implement @somdoron suggestion, for now it will do
