### ISSUE TITLE
Problem: build break, osx/clang/gcc.

### ISSUE THREAD

**Issue by evoskuil** [zeromq/libzmq#2118]
```
No rule to make target `src/pollset.cpp', needed by `src/src_libzmq_la-pollset.lo'.
```

https://travis-ci.org/libbitcoin/libbitcoin-server/jobs/161298679#L543

**Comment by evoskuil** [comment]
I see this is outstanding: https://github.com/zeromq/libzmq/pull/2113

**Comment by bluca** [comment]
Fixed by merging https://github.com/zeromq/libzmq/pull/2113
