### ISSUE TITLE
pkg-config config should optionally require libpgm and libsodium

### ISSUE THREAD

**Issue by Meijuh** [zeromq/libzmq#2132]
The files:

 - https://github.com/zeromq/libzmq/blob/master/src/libzmq.pc.in, and
 - https://github.com/zeromq/libzmq/blob/master/src/libzmq.pc.cmake.in

should optionally require libpgm and libsodium (whether or not ZMQ was configured to use those).

**Comment by bluca** [comment]
pkg-config files are for building against a project, not for runtime dependencies. Could you be more specific on the reason why they should?

**Comment by Meijuh** [comment]
Well, for example, I am trying to do a static build against ZMQ (LDFLAGS="-all-static").
The packages distributed in Ubuntu/Debian are compiled against libsodium and libpgm.
Assuming I installed those packages with aptitude; when I run `PKG_CHECK_MODULES([libzmq])` it should tell me that I have to link with -lsodium and -lpgm.
In the end, `ar` should make one statically linked binary (for my project) that not only include objects from libzmq.a, but also from libsodium.a and libpgm.a, right?

**Comment by bluca** [comment]
I see your point. Perhaps then the correct thing to do is to add those libraries to the Requires.private field, if building against them, as per pkg-config guidelines: https://people.freedesktop.org/~dbn/pkg-config-guide.html

**Comment by Meijuh** [comment]
On second  thought, why doesn't Ubuntu/Debian install a libzmq.la?

**Comment by bluca** [comment]
https://lintian.debian.org/tags/non-empty-dependency_libs-in-la-file.html

It seems to me pkgconfig is the right way to go, I'll put together a PR
