### ISSUE TITLE
Problem getting Identity with ZMQ_STREAM in 4.1.5

### ISSUE THREAD

**Issue by aaronovz1** [zeromq/libzmq#2133]
There seems to be an issue using ZMQ_STREAM in 4.1.5 or the documentation on how to use it is not clear. The problem I am seeing is that I cannot get the identity of the client through zmq_getsockopt after I call connect to connect to a regular TCP server. I tried waiting 1 second after the connect call but I still get no data. The only way I can get the identity is to wait for the first message to be received and save it off from message part and then prepend that to every message I send to the server.

Is this expected behavior?

**Comment by bluca** [comment]
I'm not especially familiar with the ZMQ_STREAM type, but in general note that socket connects are asynchronous, there's no guarantee (intentionally) of when it will be established.

**Comment by aaronovz1** [comment]
This seems to be the case as the only accurate way is to wait for the first zero-length message which means connection is established as per doc

> When a connection is made, a zero-length message will be received by the application. Similarly, when the peer disconnects (or the connection is lost), a zero-length message will be received by the application.

For other socket types - is there a way to determine if connection is established?

**Comment by bluca** [comment]
No, again this is by design. You need your own protocols to detect clients on top of the library (initial handshake, etc)
