### ISSUE TITLE
Problem: 2 connects with same sourceip:port to different destip:port fail

### ISSUE THREAD

**Issue by Prachi2807** [zeromq/libzmq#2151]
_send.cpp_

***********************************************************************************
void *ctx=zmq_ctx_new();
**void *sock1=zmq_socket(ctx,ZMQ_DEALER);
int rc=zmq_connect(sock1,"tcp://127.0.0.1:5500;127.0.0.1:5558");**

**void *sock2=zmq_socket(ctx,ZMQ_DEALER);
rc=zmq_connect(sock2,"tcp://127.0.0.1:5500;127.0.0.1:6611");**

***********************************************************************************
is this possible??

**Comment by somdoron** [comment]
Did you try? I think it depends on the OS

**Comment by Prachi2807** [comment]
I have tried it . but the first one is only getting connected.
After i stop the server on 5558 , then only it will go and connect to the 6611.

whereas in TCP implementation , it both the connections are connected at the same time.

**Comment by Prachi2807** [comment]
is anyone looking into it ??
I need the solution to it,

**Comment by bluca** [comment]
What's the OS?

**Comment by Prachi2807** [comment]
OS - Linux Version 2.6.32-504.30.3.el6.x86_64 x86_64

**Comment by Prachi2807** [comment]
Hey , have you tried?

**Comment by bluca** [comment]
No haven't had time, might have some during the weekend

**Comment by bluca** [comment]
Found the issue, on connect the SO_REUSEADDR flag is not set on the socket if a source address is passed before binding, so the second connect would never complete as the bind will always return EADDRINUSE.

Will send a fix shortly. Thanks for the report!

**Comment by Prachi2807** [comment]
Thanks for the fix :+1:
