### ISSUE TITLE
terminate called after throwing an instance of 'std::bad_alloc'   what():  std::bad_alloc

### ISSUE THREAD

**Issue by sumeimin** [zeromq/libzmq#2153]
When i use hundreds of push-pull models, I push msg constantly,the memory using increasing until the problem happens.

**Comment by hnwyllmm** [comment]
On Linux or Windows, or other OS?
Do the pullers work normally?
Could you send the demo code?

**Comment by sumeimin** [comment]
On window， the puller work well. wait for moment, i will send you de demo code.

**Comment by bluca** [comment]
No follow-up in more than a year, closing.
