### ISSUE TITLE
Remove an unnecessary null pointer check

### ISSUE THREAD

**Issue by elfring** [zeromq/libzmq#2155]
[An extra null pointer check is not needed](https://isocpp.org/wiki/faq/freestore-mgmt#delete-handles-null "Do I need to check for NULL before delete p?") in [the destructor for the class "zmq::mtrie_t"](https://github.com/zeromq/libzmq/blob/3683a96fcbf25c4bc04ac4b002a1b1550db99767/src/mtrie.cpp#L49 "Destructor for zmq::mtrie_t").

**Comment by c-rack** [comment]
Would you please send a pull request to fix it?

**Comment by c-rack** [comment]
Fixed by merging https://github.com/zeromq/libzmq/pull/2157
