### ISSUE TITLE
Apparent queuing on PUB/SUB fan-in despite HWM=1‏

### ISSUE THREAD

**Issue by mato** [zeromq/libzmq#216]
Originally reported by "Brian TheLion",  rossabri@hotmail.com, original text follows:

I'm working on a real-time vision system that uses zeromq to connect its major computational components. The components run at or near frame rate. I began to notice considerable desynchronization at the system endpoint, where there is a fair amount of fan-in over PUB/SUB sockets. There was often several seconds worth of lag between the output of one component and that of another, despite having started the same computation at the same time. This could not be attributed to component performance.

I cooked up a little example of the effect: http://pastebin.com/KcAzxM3U

The latency of messages is basically unbounded despite HWM=1. We would expect the HMW to prevent old data from building up in the system queues.

**Comment by dimovnike** [comment]
I am experiencing the same issue in PHP, with libzmq 4.2.3. Is there a fix or a workaround for this problem?

**Comment by dimovnike** [comment]
Also its worth mentioning that i tested with HWM=10 and 100, while sending hundred of messages per second. The result is the same.

**Comment by dimovnike** [comment]
turns out, messages are stored in TCP buffers. That's why only small messages show this behavior.
