### ISSUE TITLE
Assertion failed: !more (src/fq.cpp:117)

### ISSUE THREAD

**Issue by rldp** [zeromq/libzmq#2163]
see attachment for a minimal test case.

[zmq_disconnect_sub.tar.gz](https://github.com/zeromq/libzmq/files/533474/zmq_disconnect_sub.tar.gz)

# Test case

> created PUB socket
> bound PUB socket to endpoint tcp://*:23456
> created SUB socket
> subscribed SUB socket to ""
> connected SUB socket to endpoint tcp://localhost:23456
> waiting for connection to take place...
> sent part 1 of message: data in first frame
> sent part 2 of message: data in second frame
> before zmq_disconnect, zmq_poll=1
> disconnected SUB socket
> after zmq_disconnect, zmq_poll=1 (surprising?)
> receiving part 1 of message: &lt;data in first frame&gt;
> receiving part 2 of message: Assertion failed: !more (src/fq.cpp:117)
> Aborted (core dumped)

# Variations

## with a SUB socket connected to two PUB sockets

same problem

## with a DEALER-DEALER connection

The zmq_disconnect drops the message (as expected?)

# Environment

Problem verified with

* zeromq
  * 4.1.4
  * 4.1.5
  * trunk
* system
  * RHEL 6.8 x86_64
  * Ubuntu 16.04 x86_64

# Note about the SUB socket specification

https://rfc.zeromq.org/spec:29/PUBSUB describes what happens when the PUB
socket disconnects:

> SHALL create a queue when a publisher connects to it. If this publisher
> disconnects, the SUB socket SHALL destroy its queue and SHALL discard any
> messages it contains.

not what should happen when the SUB socket disconnects.

(but then I'm not familiar with this level of detail of zeromq)

**Comment by somdoron** [comment]
I think there is a bug with the disconnect, in following line try to change it to true and see if the bug is fixed:

https://github.com/zeromq/libzmq/blob/master/src/socket_base.cpp#L1080

I 'm not what other thing that effect so we might need a special option to enable the fix.

**Comment by rldp** [comment]
The suggested change doesn't prevent the assertion from failing.

Performed the following steps:
- make uninstall
- made the suggested change in src/socket_base.cpp:1080
- make && make check
- no errors reported
- make install
- ran the test case from above
- got: Assertion failed: !more (src/fq.cpp:118)

**Comment by rldp** [comment]
the changes from 

https://github.com/somdoron/libzmq/commit/5b0c7144df423b22a75c25e5e3c0d83ff70eb006
https://github.com/somdoron/libzmq/commit/3775d0853a8c1f1c3854a94c7fe12e78046faeca

seem to fix the problem: no more assertion raised.

Thanks.

**Comment by somdoron** [comment]
More recent fix here:

https://github.com/somdoron/libzmq/commit/07fe8644cae38132c4259bfee3d67c37bfe06797

I however, my opinion is that this behavior shouldn't be supported. I think it is application error, you shouldn't disconnect if you are currently receiving message multipart message, read to end and then call disconnect. Also same issue can still happen during sending multipart message. Bottom line only call Disconnect if you are not during sending or receiving multi-part.

Most binding has support to retrieve all frames.

The fix is too complicated and actually touching the core of the library, for a behavior I don't think we should support. You can use the fix, but I'm currently not going to make a PR.

**Comment by rldp** [comment]
thanks! You fixed more than what was reported (copied from above:)

```
...
before zmq_disconnect, zmq_poll=1
disconnected SUB socket
after zmq_disconnect, zmq_poll=1 (surprising?)
receiving part 1 of message: <data in first frame>
receiving part 2 of message: Assertion failed: !more (src/fq.cpp:117)
```

**Comment by sourcedelica** [comment]
Could this also happen if the publisher disconnects?  I'm seeing the same problem but in my case it's not possible for a socket read to happen if the SUB socket has been disconnected (and I'm not seeing a disconnect in the logs before the crash).

**Comment by lukaszsamson** [comment]
I'm seeing the same assert fails on DEALER connected to ROUTER when receiving (v4.3.2, macos 10.15.4).
```
* thread #30, name = '10_dirty_io_sch', stop reason = signal SIGABRT
    frame #0: 0x00007fff7331f33a libsystem_kernel.dylib`__pthread_kill + 10
    frame #1: 0x00007fff733dbe60 libsystem_pthread.dylib`pthread_kill + 430
    frame #2: 0x00007fff732a6808 libsystem_c.dylib`abort + 120
    frame #3: 0x000000005f9d06e9 libzmq.5.dylib`zmq::zmq_abort(char const*) + 9
    frame #4: 0x000000005f9d0ae0 libzmq.5.dylib`zmq::fq_t::recvpipe(zmq::msg_t*, zmq::pipe_t**) + 240
    frame #5: 0x000000005f9f6fa7 libzmq.5.dylib`zmq::socket_base_t::recv(zmq::msg_t*, int) + 167
    frame #6: 0x000000005fa1306f libzmq.5.dylib`zmq_recvmsg + 47

```
