### ISSUE TITLE
How to build binary package (.deb)

### ISSUE THREAD

**Issue by superuzir** [zeromq/libzmq#2165]
Hi all! Guys, I need your help!

What is the common way to build binary package for debian? debuild does not find debian/rules, because they are in the packaging/ subfolder. If I cd to packaging and run debuild from there, then configure.ac is not found.
I'm trying to figure this out because don't want to `sudo make install` library into system but use .deb package instead. May be there is some option to configure or target for make to create .deb package?
Also there are a bunch of projects based on ZeroMQ which use this project structure, and some of them (latest versions) are not present in distrib repos, so the only way to get .deb is to build it by yourself.

Maybe it is better to give an example in INSTALL or README.md

**Comment by bluca** [comment]
Hi,

First of all we automatically build packages for the main distributions on OBS on each commit/merge:

https://build.opensuse.org/project/show/home:zeromq:git-stable

If you want to rebuild locally, simply symlink ./packaging/debian to ./debian
We have to keep those directories out of the way to avoid causing problems for downstream distribution mainteiners.

**Comment by superuzir** [comment]
Yeah, thank you!
