### ISSUE TITLE
zmq_msg_init_data does not free allocated data for me

### ISSUE THREAD

**Issue by kouzinopoulos** [zeromq/libzmq#2166]
It seems there is a problem with zmq_msg_init_data (or i am lacking an understanding on how it is supposed to work)

The following code never calls either helper function (CustomCleanup or my_free) to free std::string* messageString or void *data respectively, resulting in a memory leak (tested against v4.1.5):

    void CustomCleanup(void *data, void *hint)
    {
      cout << "free1" << endl;
      delete static_cast<std::string*>(hint);
    }

    void my_free (void *data, void *hint)
    {
        cout << "free2" << endl;
        free (data);
    }

    int main()
    {
        zmq::context_t context (1);
        zmq::socket_t socket (context, ZMQ_PUSH);
        socket.bind ("tcp://*:5555");

        std::string* messageString = new string("ABCDEFG");
        cout << "Serialized message size: " << messageString->length() << " " << messageString->c_str() << endl;

        zmq_msg_t msg;
        int rc = zmq_msg_init_data (&msg, messageString, messageString->length(), CustomCleanup, messageString); assert (rc == 0);
        zmq_send (socket, &msg, 7, 0);

        cout << "Serialized message size: " << messageString->length() << " " << messageString->c_str() << endl;

        void *data = malloc (6);
        assert (data);
        memcpy (data, "ABCDEF", 6);
        zmq_msg_t msg2;
        int rc2 = zmq_msg_init_data (&msg2, data, 6, my_free, NULL); assert (rc2 == 0);
        zmq_send (socket, &msg2, 6, 0);
    }

**Comment by hnwyllmm** [comment]
I think you can't send an C++ object like string. String has a memory pointer to the heap and it surely can not be access on the remote process.
The memory must can be used by memcpy to operate .







On 10/18/2016 21:00， Charis Kouzinopoulos<notifications@github.com>wrote：

It seems there is a problem with zmq_msg_init_data (or i am lacking an understanding on how it is supposed to work)

The following code never calls either helper function (CustomCleanup or my_free) to free std::string* messageString or void *data respectively, resulting in a memory leak (tested against v4.1.5):

void CustomCleanup(void *data, void *hint)
{
  cout << "free1" << endl;
  delete static_cast<std::string*>(hint);
}

void my_free (void *data, void *hint)
{
    cout << "free2" << endl;
    free (data);
}

int main()
{
    zmq::context_t context (1);
    zmq::socket_t socket (context, ZMQ_PUSH);
    socket.bind ("tcp://*:5555");

    std::string* messageString = new string("ABCDEFG");
    cout << "Serialized message size: " << messageString->length() << " " << messageString->c_str() << endl;

    zmq_msg_t msg;
    int rc = zmq_msg_init_data (&msg, messageString, messageString->length(), CustomCleanup, messageString); assert (rc == 0);
    zmq_send (socket, &msg, 7, 0);

    cout << "Serialized message size: " << messageString->length() << " " << messageString->c_str() << endl;

    void *data = malloc (6);
    assert (data);
    memcpy (data, "ABCDEF", 6);
    zmq_msg_t msg2;
    int rc2 = zmq_msg_init_data (&msg2, data, 6, my_free, NULL); assert (rc2 == 0);
    zmq_send (socket, &msg2, 6, 0);
}

**Comment by bluca** [comment]
As the documentation says, the callbacks are asynchronous. Most likely that program is exiting before the background thread has time to do so.

**Comment by kouzinopoulos** [comment]
The code above is extracted from a much bigger project that sends 10k objects of more than 100 GB in size over a network in a period of tens of minutes and CustomCleanup is never called, resulting in the system eventually running out of memory and killing the program. 

Even if a large sleep is added in the end of the posted code ( e.g. sleep(100); ) does not allow the background thread to eventually call the de-allocation functions.

**Comment by bluca** [comment]
Are you sure the data is actually being sent? If the socket is blocked because of HWM for example, it won't get sent and won't get freed.

**Comment by kouzinopoulos** [comment]
Yes, the data is actually sent

**Comment by bluca** [comment]
Ok, I can't tell from a quick view what's wrong with your example, I'll try to find time to run it later this week

**Comment by maxkozlovsky** [comment]
Hi,

The code example posted sends messages on a PUSH socket without a PULL
socket connected. The messages will not be sent until a PULL socket
connects. If a connected PULL socket is added you'll see calls to free.

Max

**Comment by kouzinopoulos** [comment]
Example PULL socket connected. The free function is not called:

    int main()
    {
        zmq::context_t context (1);
        zmq::socket_t socket (context, ZMQ_PULL);
        socket.connect ("tcp://127.0.0.1:5555");

        zmq::message_t message;
        socket.recv(&message);

        cout << "Message received" << endl;
    }

**Comment by kouzinopoulos** [comment]
Problem solved when substituting zmq_send() with zmq_msg_send(), closing this report
