### ISSUE TITLE
tests fail on 4.2.0 on aarch64 (ARMv8)

### ISSUE THREAD

**Issue by vielmetti** [zeromq/libzmq#2167]
Environment: ARMv8 96 core server, libzmq master, Ubuntu 16.04.

Build succeeds but tests fail, as follows:

```
====================================
   zeromq 4.2.0: ./test-suite.log
====================================

# TOTAL: 85
# PASS:  73
# SKIP:  0
# XFAIL: 0
# FAIL:  12
# XPASS: 0
# ERROR: 0

.. contents:: :depth: 2

FAIL: tests/test_msg_ffn
========================

lt-test_msg_ffn: tests/test_msg_ffn.cpp:48: int main(): Assertion `rc == 0' failed.
FAIL tests/test_msg_ffn (exit status: 134)

FAIL: tests/test_stream_empty
=============================

lt-test_stream_empty: tests/test_stream_empty.cpp:43: int main(): Assertion `rc >= 0' failed.
FAIL tests/test_stream_empty (exit status: 134)

FAIL: tests/test_unbind_wildcard
================================

lt-test_unbind_wildcard: tests/test_unbind_wildcard.cpp:36: int main(): Assertion `rc == 0' failed.
FAIL tests/test_unbind_wildcard (exit status: 134)

FAIL: tests/test_spec_req
=========================

lt-test_spec_req: tests/test_spec_req.cpp:41: void test_round_robin_out(void*): Assertion `rc == 0' failed.
FAIL tests/test_spec_req (exit status: 134)

FAIL: tests/test_spec_rep
=========================

lt-test_spec_rep: tests/test_spec_rep.cpp:45: void test_fair_queue_in(void*): Assertion `rc == 0' failed.
FAIL tests/test_spec_rep (exit status: 134)

FAIL: tests/test_spec_dealer
============================

lt-test_spec_dealer: tests/test_spec_dealer.cpp:41: void test_round_robin_out(void*): Assertion `rc == 0' failed.
FAIL tests/test_spec_dealer (exit status: 134)

FAIL: tests/test_spec_router
============================

lt-test_spec_router: tests/test_spec_router.cpp:45: void test_fair_queue_in(void*): Assertion `rc == 0' failed.
FAIL tests/test_spec_router (exit status: 134)

FAIL: tests/test_spec_pushpull
==============================

lt-test_spec_pushpull: tests/test_spec_pushpull.cpp:41: void test_push_round_robin_out(void*): Assertion `rc == 0' failed.
FAIL tests/test_spec_pushpull (exit status: 134)

FAIL: tests/test_req_correlate
==============================

lt-test_req_correlate: tests/test_req_correlate.cpp:56: int main(): Assertion `rc == 0' failed.
FAIL tests/test_req_correlate (exit status: 134)

FAIL: tests/test_req_relaxed
============================

lt-test_req_relaxed: tests/test_req_relaxed.cpp:74: int main(): Assertion `rc == 0' failed.
FAIL tests/test_req_relaxed (exit status: 134)

FAIL: tests/test_conflate
=========================

lt-test_conflate: tests/test_conflate.cpp:49: int main(int, char**): Assertion `rc == 0' failed.
FAIL tests/test_conflate (exit status: 134)

FAIL: tests/test_issue_566
==========================

lt-test_issue_566: tests/test_issue_566.cpp:52: int main(): Assertion `rc != -1' failed.
FAIL tests/test_issue_566 (exit status: 134)


```

See https://gist.github.com/4f216109aba378bb7c3ad22d4e5d14ff

This build failure blocks a build of `pipelinedb`.

**Comment by vielmetti** [comment]
Also seen on 4.1.5, details at https://github.com/zeromq/zeromq4-1/issues/151

**Comment by bluca** [comment]
Hi, thanks for the report.

The tests seem to work on OBS, running on the OpenSUSE armv7l and aarch64 factory builds:

https://build.opensuse.org/package/live_build_log/home:zeromq:git-stable/libzmq/openSUSE_Factory_ARM/armv7l
https://build.opensuse.org/package/live_build_log/home:zeromq:git-stable/libzmq/openSUSE_Factory_ARM/aarch64

But those are running on Qemu, not real hardware.

I do have a Raspberry PI 3 with an experimental aarch64 Fedora installation, so I can try to give it a shot tomorrow.

As always, sending pull requests is the easiest and quickest way to get bugs fixed :-)

**Comment by vielmetti** [comment]
Thanks @bluca - is it possible to rerun the tests individually, with more debug output? I'm not sure what is actually failing in these cases.

**Comment by jacobsmith928** [comment]
@bluca please let me know if you (or other testers) would like access to a real ARMv8 environment, same as @vielmetti. Happy to provide it on demand.

**Comment by bluca** [comment]
@vielmetti you can run individual tests with GDB. If you are building libzmq master with autotools (the default), something like:

```LD_LIBRARY_PATH=src/.libs gdb tests/.libs/test_foo_bar```

@jacobsmith928 that would be fantastic and a great help, thank you very much for the offer! Please drop me an email, luca.boccassi at gmail

**Comment by bluca** [comment]
@jacobsmith928 - thanks for the access to the armv8 cloud on packet.net!

@vielmetti - tested on Ubuntu 16.04 aarch64 running on Cavium ThunderX CN8890, and all tests pass. Did you by any chance run the tests in parallel with make check -jX or similar? Because that's not supported, many test share the same TCP port so they'll clash.

**Comment by vielmetti** [comment]
Thanks @bluca - all tests pass when I run them sequentially. I added a PR to update the docs accordingly.

**Comment by bluca** [comment]
Merged, thanks! Could you please send one to the zeromq4-1 repo as well when you have time?

**Comment by vielmetti** [comment]
Documentation patch also sent to zeromq4-1, thanks!
