### ISSUE TITLE
More explicit docs for setsockopt() with strings regarding NUL-termination

### ISSUE THREAD

**Issue by rotty** [zeromq/libzmq#2169]
As far as I can glance from the implementation, `setsockopt()` does not require NUL-termination of string options (e.g. `ZMQ_PLAIN_PASSWORD`). This is quite nice behavior for rust language bindings, as rust strings are not NUL-terminated, but a sequence bytes of UTF-8 encoded string, along with the length in bytes.

However, I could not find documentation of NUL-termination being optional, so I feel a bit uncomfortable relying on that in the bindings. Even if I strongly assume this is more-or-less intended, and will not change easily, I'd like to see this documented explicitly.

Adding something along the following lines near the beginning of `zmq_setsockopt(3)` might suffice:

> When the option value type is listed as "character string", an optionally NUL-terminated string is expected, unless more specific requirements are given for that option.

**Comment by bluca** [comment]
The setsockopt itself mimicks the BSD socket API so as you say it does not require null termination, as it takes an explicit size.

However we would need to check each and every internal client of the get/setsockopt, to make sure that when a string is passed, nowhere in the code there are assumption about this.

If it is all safe, then by all means please send a PR to update the docs with your suggestion and we'll merge it.

**Comment by rotty** [comment]
I'm not sure why internal clients need to be checked, can you elaborate? I'm not talking about preserving embedded NUL-bytes across a `setsockopt()`, `getsockopt()` sequence, but only that it is safe to pass a non-NUL terminated string without embedded NUL bytes to setsockopt(). Checking the implementation of  `zmq_setsockopt()` alone would suffice to ensure that property, I think.

If we want to guarantee preserving embedded NUL bytes, more checking indeed needs to be done. I am not sure, however, if *that* guarantee should be part of the API contract. If there is consensus this is an additionally desired property, I can try to extend the scope of the resulting PR to include it, however.

**Comment by bluca** [comment]
Sorry, I replied from the phone so I wasn't clear and I didn't look at the code.

What I was concerned about was possible use of char pointers, but I've now seen that all the strings are saved in std:string types and the content is used via c_str() in other modules, so we are completely fine.

Personally I'm OK with adding this to the docs if it helps users or writers of bindings, but in the future we'll need to take care in using the same mechanism if more string parameters are added. I don't think it will be a problem, so please do send the correction to the doc. Thanks!

**Comment by rotty** [comment]
I'll try to come up with a minimal addition to documentation, which extends the API contract just enough so that the current implementation of rust-zmq is safe, which relies on the fact that it need not NUL-terminate any strings passed to zmq_setsockopt() to avoid allocating a copy with the added NUL character just for the API call.

**Comment by bluca** [comment]
Fixed by https://github.com/zeromq/libzmq/issues/2216
