### ISSUE TITLE
clock_gettime is now defined in macOS 10.12 SDK

### ISSUE THREAD

**Issue by robertcastle** [zeromq/libzmq#2175]
System Info: macOS 10.11, Xcode 8 with macOS 10.12 SDK
libZMQ version: commit 2e9264354c54936b5025bebf7a9aa8f2e624efe7

Problem:
- Prior to macOS 10.12 `clock_gettime` was not defined, requiring a custom implementation in libZMQ.
- When using macOS 10.12 libzmq should use the system `clock_gettime`, but when targeting 10.11 or earlier it should use the custom implementation.

How to Reproduce:
- Install Xcode 8 on macOS 10.11, then build and run tests
- Target 10.11 when building on macOS 10.12 

Tests will fail with `dyld: lazy symbol binding failed: Symbol not found: _clock_gettime`

Solution: 
Rename the custom implementation of `clock_gettime` for macOS and wrap all usage in preprocessor macros to only enable the alternative version when using macOS 10.11 or earlier.

**Comment by bluca** [comment]
Well if you target 10.11 and then use the library on 10.12, it's obvious it will fail, right? You need to target 10.11 and run on 10.11, or target 10.12 and run on 10.12.

When cross-compiling obviously unit tests won't work, as the library is built for a foreign system. That's why the test run is not part of the all-inclusive make call, but you have to specifically call make check.

Or did I misunderstand your report?

**Comment by robertcastle** [comment]
Hi, I failed to explain clearly enough. 

The issue is not trying to run software for one platform on another. I would expect that to fail.

The issues are:

1. In 10.11 and earlier there was no `clock_gettime` defined, so ZMQ defines its own version. Now that 10.12 defines `clock_gettime`, it will conflict with the one defined in ZMQ.
2. Because of how Apple ships their SDKs and expects developers to work, you can end up with the latest Xcode (Xcode 8) on a 10.11 machine. Xcode 8 only ships with the 10.12 SDK, so you have to compile for 10.11 using the 10.12 SDK. This is entirely normal. This is the situation I am in. It is also highly probably that developers on 10.12 will need to develop apps that work with earlier versions of macOS.

The code will build, because it finds the `clock_gettime` define in the system header, but when an app is run on 10.11 or earlier it will fail, as the implementation is not actually available. You get the lazy binding error.

There is a discussion about the issue here on another project: https://github.com/Homebrew/homebrew-core/issues/2674

The solution is 2 fold.
1. rename the custom implementation of `clock_gettime` so it will not conflict
2. Only use the custom implementation when the macOS target is 10.11 or earlier.

**Comment by bluca** [comment]
Thanks for the PR, merged it. But for the record, I think there's a bit more to do.

First of all on OSX we use autoconf and cmake, and both can detect if a function is available or not, so rather than hard-coding the platform version a macro should be used instead to detect if clock_gettime is available or not.

For the SDK problem, it's hard to believe that Apple ships such broken stuff. Well maybe not too hard :-)
If you want to build for version Y, which is not compatible with version X, then you can't build for version X. This is basic stuff. Is it really not possible to add the SDK for 10.11 in Xcode 8 and use it to build? That seems too ridiculous even for Apple!

**Comment by robertcastle** [comment]
Agreed, cmake and autoconf may need to adjustment to handle the issue.

For future reference:

Adding `-Wl,-no_weak_imports` to the LDFLAGS is also a way around it according to an Apple Engineer (https://github.com/Homebrew/homebrew-core/issues/3727), but the alternative still needs to made available on 10.11 and earlier.

This is how Apple defines `clock_gettime` in `time.h`

```
#if !defined(_DARWIN_FEATURE_CLOCK_GETTIME) || _DARWIN_FEATURE_CLOCK_GETTIME != 0
#if __DARWIN_C_LEVEL >= 199309L
#if __has_feature(enumerator_attributes)
#define __CLOCK_AVAILABILITY __OSX_AVAILABLE(10.12) __IOS_AVAILABLE(10.0) __TVOS_AVAILABLE(10.0) __WATCHOS_AVAILABLE(3.0)
#else
#define __CLOCK_AVAILABILITY
#endif

__CLOCK_AVAILABILITY
int clock_gettime(clockid_t __clock_id, struct timespec *__tp);
```

And here is how they suggest handling availability of functions: [Availability.h](http://opensource.apple.com/source/xnu/xnu-2050.22.13/EXTERNAL_HEADERS/Availability.h)

**Comment by rgbkrk** [comment]
I'm running into an issue where an application is built on Sierra then run on El Capitan (https://github.com/electron/electron/issues/8068#issuecomment-262846787), the error message I end up with is:

```
Dyld Error Message:
  Symbol not found: _clock_gettime
  Referenced from: /Applications/nteract.app/Contents/Resources/app.asar.unpacked/node_modules/zeromq/build/Release/zmq.node
  Expected in: /usr/lib/libSystem.B.dylib

Thread 0 Crashed:: CrRendererMain  Dispatch queue: com.apple.main-thread
0   dyld                          	0x00007fff6e79d075 dyld_fatal_error + 1
1   dyld                          	0x00007fff6e7a0094 dyld::fastBindLazySymbol(ImageLoader**, unsigned long) + 139
2   libdyld.dylib                 	0x00007fff84d08262 dyld_stub_binder + 282
3   ???                           	0x00000001144760a0 0 + 4635189408
4   zmq.node                      	0x000000011439da35 zmq::clock_t::clock_t() + 37
5   zmq.node                      	0x000000011439db85 zmq::clock_t::clock_t() + 21
6   zmq.node                      	0x00000001143e8607 zmq::poller_base_t::poller_base_t() + 55
```

**Comment by rgbkrk** [comment]
> It is also highly probably that developers on 10.12 will need to develop apps that work with earlier versions of macOS.

Exactly the case we're in.

**Comment by bluca** [comment]
Didn't the PR referenced fix this?

**Comment by rgbkrk** [comment]
Perhaps I'm reading the PR wrong, just so I'm clear -- is this only setting up a compile time target? What if I build on a newer system and want to support older systems?

I'll revisit this tomorrow, thanks @bluca and @robertcastle.

**Comment by bluca** [comment]
Backward compatibility at the system library ABI level is very tricky, for example usually a build against a newer libc is highly unlikely to work on a system with an old one, if a symbol that's changed is used.
With system libraries/compilers usually there's forward compatibility (compile against the old version and run with newer), but not backward.

Of course if you can send a PR to make both safely work it would be most welcome!

**Comment by minrk** [comment]
@rgbkrk to target older OS X than the build machine, you should be careful to set MACOSX_DEPLOYMENT_TARGET, which should properly select SDKs, etc. for deployment on older systems. That ought to cause things like this to be triggered during build.

**Comment by rgbkrk** [comment]
Thank you so much @minrk! We can now ship nteract and Hydrogen. 🙇

**Comment by bluca** [comment]
Nice!

Given between that and the PR: https://github.com/zeromq/libzmq/pull/2176 this should be solved, I'll close the issue for now. Please reopen if you encounter more problems.

**Comment by rgbkrk** [comment]
Thank you @bluca!
