### ISSUE TITLE
Problem: can't automatically deploy RC tarballs/zips via Travis

### ISSUE THREAD

**Issue by bluca** [zeromq/libzmq#2185]
Given the version comes from include/zmq.h, where we can't add -rcX, when we tag an rcX release the tarball/zip will not have the -rcX suffix.

A possible solution could be to change the version.sh script to read the latest git tag and look at include/zmq.h only as a fallback.

**Comment by bluca** [comment]
@sappo any other idea besides looking at git tag in version.sh?

**Comment by sappo** [comment]
No idea sorry. But as this seems to complicate things I would avoid rc releases at all. Is this something you need for debian packaging?

**Comment by bluca** [comment]
No I don't need it, I did them just because it seems it was part of the process for previous major releases.

I'll have a brief look at version.sh, if it can't be fixed easily then we can indeed skip them next time :-)

**Comment by sappo** [comment]
@bluca how did you fix it?

**Comment by bluca** [comment]
Manually :-) Downloaded the tarballs and hasums, renamed, re-uploaded

**Comment by sappo** [comment]
I'm a bit confused can you double check if the version.sh is no longer generated by zproject. If that's the case I'll prepare a fix.

**Comment by bluca** [comment]
Yes it is generated by zproject in czmq et al

**Comment by sappo** [comment]
Are you sure? Have a closer look at the file - there's still version 3.0.3 in it as version backup

**Comment by bluca** [comment]
Mh you are indeed right!
Deleted the file and run gsl project.xml, and it's not recreated. Good catch!

**Comment by sappo** [comment]
I found the reason: https://github.com/zeromq/zproject/pull/494/files

Pieter removed it - I'm note sure about the reason.

**Comment by sappo** [comment]
Found his reason
https://github.com/zeromq/zproject/pull/494/commits/2993efe965c2f5bc740e28c226b74e57177e59b5

Seems very valid - do you know where version.sh is still used?

**Comment by sappo** [comment]
Sorry for the spam - According to my grep's it is no longer used in czmq and zyre and thus we can simply remove it.

Regarding the RC releases. If we would like to support them we should add an RC field in the project XML and concat a version string that is used by the code generation.

**Comment by bluca** [comment]
Ah good point! I guess one of the issues with zproject is that if a file is generated first, and then later removed, rebuilding does not remove them, they linger.

Yes your point about RC in project XML makes a lot of sense to me, I agree it would be the right way.

**Comment by sappo** [comment]
I'll have a look at it this afternoon. Shouldn't be too complicated the version references in the gsl files are manageable.

**Comment by bluca** [comment]
We don't do RCs anymore, so I'll close this
