### ISSUE TITLE
multiple definition of randombytes_close/randombytes

### ISSUE THREAD

**Issue by duzy** [zeromq/libzmq#2202]
I'm using libzmq and libsodium APIS, but got multiple definition errors while linking to `-lzmq -lsodium`:

```
/opt/lib/libsodium.a(libsodium_la-randombytes.o): In function `randombytes_close':
/opt/libsodium/src/libsodium/randombytes/randombytes.c:169: multiple definition of `randombytes_close'
/opt/lib/libzmq.a(src_libzmq_la-tweetnacl.o):/opt/libzmq/src/tweetnacl.c:939: first defined here
/opt/lib/libsodium.a(libsodium_la-randombytes.o): In function `randombytes':
/opt/libsodium/src/libsodium/randombytes/randombytes.c:179: multiple definition of `randombytes'
/opt/lib/libzmq.a(src_libzmq_la-tweetnacl.o):/opt/libzmq/src/tweetnacl.c:913: first defined here
```

I'm trying to change the names by myself to solve it quickly. But looking the core devs to have a look at this. Or maybe I did something wrong and please let me know. Thanks so much.

**Comment by duzy** [comment]
https://github.com/duzy/libzmq/commit/6038f719904e288f422255635b9eba4512bf6262

**Comment by bluca** [comment]
Are you using ```--with-libsodium``` to build libzmq?
Also there is a pkgconfig file, is recommended to use that rather than manually adding flags

**Comment by duzy** [comment]
@bluca Yes, I'm using libsodium.

I changed the symbols in libzmq, you might want to check https://github.com/duzy/libzmq/commit/6038f719904e288f422255635b9eba4512bf6262 .

**Comment by bluca** [comment]
Are you really sure? Could you please upload to gist/pastebin the full ./configure and make log? Because they are supposed to clash, that's intended, since they implement the same API, that's the point. At build time if libsodium is included, tweetnacl will be disabled.

**Comment by duzy** [comment]
@bluca I'm 1000% sure. Configure is fine for both (enabled static libs only). Won't crash, error when linking the client program. If a client program is not linking (a.k.a not using the API from libsodium directly) to the symbols `randombytes_close`, `randombytes` from libsodium, it should be linked correctly, or link error is raised.

It's an implementation error by defining `randombytes_close` and `randombytes` in both libzmq and libsodium without hiding the symbols. Maybe you're supposed to hide the symbols (a.k.a https://gcc.gnu.org/wiki/Visibility), but this will fail when using ZMQ with static linkage. Since all symbols are in the client program space when statically linked.

**Comment by bluca** [comment]
The symbols are compiled out directly when using libsodium as you can see in both the header and body, so unless ZMQ_USE_TWEETNACL is defined they won't be compiled at all. That is why I was asking for the configure and make log, to see what was going on there.

**Comment by bluca** [comment]
Also not only the definitions are ifdef'd out, the whole source files are not included in the build as you can see in Makefile.am:

```
if USE_TWEETNACL
src_libzmq_la_SOURCES += \
        src/tweetnacl.c \
        src/tweetnacl.h
endif
```

And as you can see in the build log:

https://gist.github.com/bluca/dced45fca317a648ba2b6e99301f4eed

No trace of tweetnacl files being built, but then when not using --with-libsodium:

https://gist.github.com/bluca/104068613e874bf3d5d80adc3b5c01a7

```
CC       src/src_libzmq_la-tweetnacl.lo
```

**Comment by duzy** [comment]
@bluca Ahhh, I see. The TWEETNACL was compiled for me obviously. I didn't make any special choices for that. So it's all going default.

Anyway, I think even if it was enabled. I should not have link time complaining. 

You might try building static libs only instead of the shared ones. I believe it won't duplicate such error if you're debugging with shared ones.

E.g. apply `--disable-shared --enable-static` for both libs.

**Comment by bluca** [comment]
Finally, your commit doesn't even build when using --with-libsodium:

```
src/curve_server.cpp: In member function 'int zmq::curve_server_t::produce_welcome(zmq::msg_t*)':
src/curve_server.cpp:332:39: error: 'random_bytes' was not declared in this scope
     random_bytes (cookie_nonce + 8, 16);
                                       ^
Makefile:3301: recipe for target 'src/src_libzmq_la-curve_server.lo' failed
make[1]: *** [src/src_libzmq_la-curve_server.lo] Error 1
make[1]: *** Waiting for unfinished jobs....
src/ctx.cpp: In destructor 'zmq::ctx_t::~ctx_t()':
src/ctx.cpp:137:25: error: 'random_bytes_close' was not declared in this scope
     random_bytes_close ();
                         ^
Makefile:3287: recipe for target 'src/src_libzmq_la-ctx.lo' failed
make[1]: *** [src/src_libzmq_la-ctx.lo] Error 1
src/curve_client.cpp: In member function 'int zmq::curve_client_t::produce_initiate(zmq::msg_t*)':
src/curve_client.cpp:332:38: error: 'random_bytes' was not declared in this scope
     random_bytes (vouch_nonce + 8, 16);
                                      ^
Makefile:3294: recipe for target 'src/src_libzmq_la-curve_client.lo' failed
```

https://gist.github.com/bluca/c92513dc54508a7f7e17f6b375d57a24

**Comment by bluca** [comment]
I see, that's why 2 days ago I asked if you were using --with-libsodium: https://github.com/zeromq/libzmq/issues/2202#issuecomment-259066113

If you use --with-libsodium, then your problem should be fixed.

**Comment by duzy** [comment]
The options for libzmq is like this: ` --prefix=/opt --disable-shared --enable-static --with-pgm`, but the libsodium was built and installed to the same prefix at `/opt`. So I think `--with-libsodium` was implicitly applied.

PS: The sodium configure options: ` --prefix=/opt --disable-shared --enable-static`

**Comment by bluca** [comment]
The change in default was highlighted in the NEWS file and in the release notes:

```
Security with Curve is now available by default thanks to Tweetnacl sources:
https://tweetnacl.cr.yp.to/index.html
Libsodium is still fully supported but has to be enabled with the build flag
--with-libsodium. Distribution and package maintainers are encouraged to use
libsodium so that the security implementation can be audited and maintained
separately.
```

https://github.com/zeromq/libzmq/releases/tag/v4.2.0
https://github.com/zeromq/libzmq/blob/v4.2.0/NEWS#L23


I'm sorry it caused you some issues. Is your build/link problem solved now when using this option?

**Comment by duzy** [comment]
I think I understand what you're saying now. The libzmq configure was not looking into the *prefix* (/opt) path for sodium automatically (the old version did so). The new version requires a explicit `--with-libsodium` to enable sodium instead of Tweetnacl. So that when I'm using both libs at the same time without a explicit `--with-libsodium`, the symbol conflict errors are complaint.

I'll try adding `--with-libsodium` instead.

By the way, comparing the two options of *Tweetnacl* and *libsodium* for Curve, which one should be preferred for security?

**Comment by bluca** [comment]
libsodium is preferred as it's externally maintained, with security fixes and so on taken care of by your distribution's security team.
tweetnacl comes from https://tweetnacl.cr.yp.to/ but as the source is integrated in our tree, security fixes might be delayed.

Please let me know if using ```--with-libsodium``` fixes the issue so we can close this ticket.

**Comment by duzy** [comment]
Well, it looks like the `--with-libsodium` is not working for me:

```
checking for sodium... no
./configure: line 421: test: then: integer expression expected
configure: error: run
./configure: line 310: return: then: numeric argument required
./configure: line 320: exit: then: numeric argument required
The command '/bin/sh -c cd /opt/_/libzmq && ./configure --prefix=/opt --disable-shared --enable-static --with-pgm --with-libsodium' returned a non-zero code: 2
Makefile:2: recipe for target 'build' failed
```

The configure can't see my sodium previously installed inside `/opt`.

**Comment by bluca** [comment]
If you don't use the standard installation path, then you need to pass PKG_CONFIG_PATH as another argument to configure.
Remember that in autotools, --prefix does NOT tell the system where to pick the dependencies, only where to INSTALL your files.

```
PKG_CONFIG_PATH=$PKG_CONFIG_PATH:/opt/lib/pkgconfig
```

Assuming the libsodium pkg config is in /opt/lib/pkgconfig. Adjust as needed.

**Comment by duzy** [comment]
@bluca This works for me know (with the official master branch). The configure now is like this:

```
PKG_CONFIG_PATH=$PKG_CONFIG_PATH:/opt/lib/pkgconfig ./configure --prefix=/opt --disable-shared --enable-static --with-pgm --with-libsodium
```

But I'd like to suggest that when `--with-libsodium` is explicit specified and sodium was in the `/opt`, the configure should looking into the *prefix* (`/opt`) too. Just as I experienced some projects using *autoconf* is doing similar search.

That will eliminate the needs of using the *PKG_CONFIG_PATH* trick when compiling with libsodium. Since *sodium* should be preferred.

For now it looks like I have to always use the PKG_CONFIG_PATH for sodium.

**Comment by duzy** [comment]
Just rebuilt my everything with the PKG_CONFIG_PATH-fixed ones, everything works for me again anyway. Disregarding the inconveniences of configure.

Thanks @bluca . I'm wondering if adding this line to `configure.ac:61` is a good idea:

```
PKG_CONFIG_PATH=$PKG_CONFIG_PATH:${prefix}/lib/pkgconfig
```

Or a better variant with some checks.

Thanks anyway. Regards.

**Comment by bluca** [comment]
Thanks for confirming it works, closing now.

Autotools supports the standard system paths for libraries, if you override that and have a private one then it will have to be specified. We cannot realistically check for every possible non-standard paths, as things would be tricky and also could be broken in unexpected way.

The standard *nix way is that unless the default path is used, it has to be manually specified with either pkg-config or CPP/LDFLAGS (-I/opt/include -L/opt/lib for example).

Changing this expected behaviour could trip users relying on the standard way it works, by picking up unintended libraries.

**Comment by duzy** [comment]
Thanks for the tip, it helps for me.
