### ISSUE TITLE
zmq_bind with MultiThreading

### ISSUE THREAD

**Issue by Prachi2807** [zeromq/libzmq#2204]
Hi, 
I have one requirement as follows:
Suppose there is  a main thread that binds on some port , for ex = 15000.
and there are 4 separate threads, 
If any client connects on main thread at 15000 , is there any  way that the connections (FDs) can be given to the other thread, so that , they will receive the message from the clients
or, is it possible that all threads can bind on same 15000 ports.
This is to separate the traffic at main thread.
Note : ALL the clients will connect to 15000 only , so its not like that i can do zmq_bind on diff ports for diff threads.

**Comment by Prachi2807** [comment]
Is anyone looking into it? Any Suggestions?

**Comment by bluca** [comment]
File descriptors cannot be moved, no, a core part of the design is to hide such low level implementations.

I would suggest to read the guide, where there are plenty examples of possible designs for master-worker implementations: http://zguide.zeromq.org/page:all for example, you can use inproc sockets which are very low level to distribute the work from the master thread to the workers.

**Comment by Prachi2807** [comment]
There is one mtserver.c example in the zguide, that will distribute the work to the worker threads (using inproc).But still , all the messages will come to one master socket only , therfore, high chances of single point of failure. I want when the connection itself is coming for connecting , that time only the master thread should be able to give connections to worker thread, so that msg come to worker directly.

**Comment by bluca** [comment]
You could use a dealer-dealer approach for your master thread, so you can have as many as you want. So you have your remote distributor being a bound dealer socket, and as many master thread as you wish with a dealer connected socket. Then if one of the dealer connected sockets dies, the work will simply shift to the others.

Or you could add an ID to each piece of work, and distribute it with pub-sub. Then it would be duplicated, but your logic can use the ID to de-duplicate.

There are many possibilities, but again this kind of logic belongs in the application using the various patterns, not in the library.

**Comment by bluca** [comment]
Closing as it cannot be implemented and the guidelines in zguide provide a supported alternative
