### ISSUE TITLE
OpenPGM receive is broken on macOS

### ISSUE THREAD

**Issue by nlyan** [zeromq/libzmq#2205]
Receiving messages on macOS (10.11 and 10.12 tested) with OpenPGM (using the latest versions from brew) seems to be broken. The machine I'm testing on is receiving packets but they are not being delivered to ZMQ. The same code has been testing on Linux and Windows and works fine.

Is this a known issue? Is this a problem with OpenPGM or ZMQ?

**Comment by bluca** [comment]
I've had other reports that PGM is broken on OSX, so not sure there's anything we can do :-/
