### ISSUE TITLE
CMake missing option for ZMQ_HAVE_NORM

### ISSUE THREAD

**Issue by ilovezfs** [zeromq/libzmq#2207]
It appears that there's no way to build with the norm option if using CMake. Is this intentional or an oversight of some kind?

**Comment by bluca** [comment]
Simply no one has implemented it yet. If you need it please do send a PR and we'll merge it

**Comment by ilovezfs** [comment]
I don't need it. It just means I cannot convert the Homebrew formula to use CMake without dropping the norm option, but I have no idea if the norm option is useful.

**Comment by bluca** [comment]
Although we do our best to equally support all build systems, truth is the most complete is autotools. It's what we use for the release distributable tarballs and most of the CI. I'm not even sure proper ABI versioning is in cmake, I'd have to check. Or course any contribution to make the situation better is most welcome.
I would recommend keeping it for anything that has to be distributed to the public, like the homebrew formula.

**Comment by ilovezfs** [comment]
Will do! Thanks for the guidance :)

**Comment by mjvankampen** [comment]
Fixes by #3951
