### ISSUE TITLE
setsockopt ZMQ_TOS doesn't work for IPv6

### ISSUE THREAD

**Issue by saifhhasan** [zeromq/libzmq#2208]
To set `Type Of Service` for IP layer packets ZMQ provides `ZMQ_TOS` socket option. However this only works for v4 sockets. Considering things are moving to IPv6 heavily (especially within enterprise networks), ZMQ should support setting `traffic class` for v6 based on `ZMQ_TOS`.

There is a subtle difference between v4 and v6 in terms of the positioning of field but TOS has same meaning in both v4 and v6. Linux provides following APIs for v4/v6 to set TOS field value.
```
// For v4
setsockopt(fd, IPPROTO_IP, IP_TOS, tos, sizeof(tos));

// For v6
setsockopt(fd, IPPROTO_IPV6, IPV6_TCLASS, tos, sizeof(tos));
```

Ask for this issue is to extend `ZMQ_TOS` to support ipv6 `traffic class` as well.

**Comment by bluca** [comment]
Do you have a use case or a way to test that it would work properly if implemented?

**Comment by saifhhasan** [comment]
Yes. Here at Facebook we build `Link State Routing Protocol` on the top of `ZeroMQ` transport (IPv6 only communication). It is very critical for us to distinguish control plane traffic from ordinary traffic to not hammer communications between routing daemon even under heavy network load.

We have internally carried out the patch and it is working well. Trying to send it upstream. Happy to take back your feedback and iterate as per the requirements.

OpenR: https://code.facebook.com/posts/1142111519143652/introducing-open-r-a-new-modular-routing-platform/

**Comment by bluca** [comment]
Great! If you have already done the work, then please do send a PR and we'll merge it. Your diff looks good, the only thing you'll want to make sure is that if IPv6 is not enabled it doesn't cause a failure. Thanks!

**Comment by bluca** [comment]
Fixed by https://github.com/zeromq/libzmq/pull/2209
