### ISSUE TITLE
zmq_msg_send and zmq_poll return whey they shouldn't (MacOS)

### ISSUE THREAD

**Issue by rbx** [zeromq/libzmq#2218]
I am having an issue using `zmq_msg_send` and `zmq_poll` on MacOS.

When using `zmq_poll` with `ZMQ_POLLOUT`, it triggers and `zmq_msg_send` allows me to send messages even when nobody is connected (socket is binding). The sending does not actually send/queue anything.
I have tested it on a PUSH socket with ZeroMQ versions 4.1.3 and 4.2.0.

The following is a minimal code to reproduce the problem:
```C++
#include <iostream>
#include <cassert>
#include "zmq.h"

int main()
{
    void* ctx = zmq_ctx_new();
    void* socket = zmq_socket(ctx, ZMQ_PUSH);
    int rc = zmq_bind(socket, "tcp://127.0.0.1:5555"); assert(rc == 0);

    zmq_pollitem_t items[1];
    items[0].socket = socket;
    items[0].fd = 0;
    items[0].events = ZMQ_POLLOUT;

    int counter = 0;

    while (true)
    {
        rc = zmq_poll(items, 1, 1000);
        std::cout << "zmq_poll => " << rc << std::endl;

        if (items[0].revents & ZMQ_POLLOUT)
        {
            zmq_msg_t msg;
            rc = zmq_msg_init_size(&msg, 1000); assert(rc >= 0);
            int nbytes = zmq_msg_send(&msg, socket, 0);
            std::cout << "sent msg nr. " << ++counter << " (" << nbytes << " bytes)." << std::endl;
        }
    }

    zmq_close(socket);
    zmq_ctx_term(ctx);

    return 0;
}

```
```
clang++ zmq-poll-send.cxx -o zmq-poll-send -lzmq
```

When running the executable by itself (without a receiver) on a Linux system (Ubuntu 16.10 + GCC 6.2.0), it does the right thing. No queue is created (binding socket without connected peers) and sending cannot be done:
```
zmq_poll => 0
zmq_poll => 0
zmq_poll => 0
zmq_poll => 0
...
```

But when running it on MacOS (10.12.1 + Apple LLVM version 8.0.0 (clang-800.0.42.1)), poll (mostly) reports that the sending can be done and `zmq_msg_send` "sends" it:
```
zmq_poll => 0
zmq_poll => 1
sent msg nr. 1 (1000 bytes).
zmq_poll => 1
sent msg nr. 2 (1000 bytes).
zmq_poll => 1
sent msg nr. 3 (1000 bytes).
zmq_poll => 1
sent msg nr. 4 (1000 bytes).
zmq_poll => 1
sent msg nr. 5 (1000 bytes).
zmq_poll => 1
sent msg nr. 6 (1000 bytes).
zmq_poll => 1
sent msg nr. 7 (1000 bytes).
zmq_poll => 1
sent msg nr. 8 (1000 bytes).
zmq_poll => 1
sent msg nr. 9 (1000 bytes).
zmq_poll => 1
sent msg nr. 10 (1000 bytes).
zmq_poll => 1
sent msg nr. 11 (1000 bytes).
zmq_poll => 1
sent msg nr. 12 (1000 bytes).
zmq_poll => 1
sent msg nr. 13 (1000 bytes).
zmq_poll => 1
sent msg nr. 14 (1000 bytes).
zmq_poll => 1
sent msg nr. 15 (1000 bytes).
zmq_poll => 1
sent msg nr. 16 (1000 bytes).
zmq_poll => 1
sent msg nr. 17 (1000 bytes).
zmq_poll => 0
zmq_poll => 1
sent msg nr. 18 (1000 bytes).
zmq_poll => 1
sent msg nr. 19 (1000 bytes).
...
```
My hope was that at least the messages would go into queue (although it should not exist yet since no peers are connected), but this goes on over the default queue size of 1000. And if i connect a receiver the already sent messages do not arrive (new ones do). So the messages are lost!

**Comment by bluca** [comment]
Without looking at the code in details yet, the first question that pops up in my head is: could it be down to the poller implementation? On OSX the default in kqueue, while on Linux is epoll.

Could you please try and see if you can reproduce the problem on Linux when using kqueue? ```./configure --with-poller=kqueue```

Also when using 4.2.0 there's a new poller implementation which is DRAFT, so if you built with draft try with ```--enable-drafts=no``` if the draft api were enabled, to try and rule out the initial first suspects.

**Comment by rbx** [comment]
Thanks for the suggestions. I have now tried both kqueue on Linux and made sure drafts are disabled on MacOS. The picture remains the same - Linux is OK, MacOS sends prematurely.

**Comment by bluca** [comment]
Ok, thanks for helping rule that out. I can try and have a look in the code later, but unfortunately I don't have an OSX setup available so it will be a bit of a pain.
I know other folks around here have a macbook so hopefully we'll get some help :-)

**Comment by rbx** [comment]
This appears to be related: https://github.com/curl/curl/issues/1057.

**Comment by bluca** [comment]
Interesting, thanks for the pointer.

Could you please try using select?  ```./configure --with-poller=select```

If it solves the problem then I guess we can check for the broken OSX version in acinclude.m4 and make it default for OSX. It's less performant though...

**Comment by rbx** [comment]
Running `./configure --with-poller=select` gives me:
```
configure: Choosing polling system from 'select'...
configure: error: None of 'select' are valid pollers on this platform
```

**Comment by bluca** [comment]
```
error: ‘NULL’ undeclared (first use in this function)
```

wat

Could you please try with this patch:

```
--- a/acinclude.m4
+++ b/acinclude.m4
@@ -891,6 +891,7 @@ AC_DEFUN([LIBZMQ_CHECK_POLLER_SELECT], [{
 #else
 #include <sys/select.h>
 #endif
+#include <stdio.h>
         ],[[
 fd_set t_rfds;
 struct timeval tv;
```

**Comment by rbx** [comment]
I tried adding <stdio.h> and then <stddef.h>, but ./configure still has the same output.
I then tried to get a clean download and change `NULL` to `0` (before running ./configure).
But after ./configure the config.log still contains:
```
configure:20300: Choosing polling system from 'select'...
configure:20541: gcc -o conftest -g -O2 -std=gnu11 -Wno-uninitialized -D_DARWIN_C_SOURCE -D_REENTRANT -D_THREAD_SAFE -Wno-long-long   conftest.c -lpthread  >&5
conftest.c:47:20: error: use of undeclared identifier 'NULL'
select(1, &t_rfds, NULL, NULL, &tv);
                   ^
conftest.c:47:26: error: use of undeclared identifier 'NULL'
select(1, &t_rfds, NULL, NULL, &tv);
```
Am i changing the wrong file or need to run something extra ?

**Comment by bluca** [comment]
Yes, you need to regenerate the configure script with ```./autogen.sh```

**Comment by bluca** [comment]
But I just checked and it doesn't even build. Let me deal with that, a few minutes and I'll get back

**Comment by bluca** [comment]
https://github.com/zeromq/libzmq/pull/2225 fixes using and building with select as the poller

**Comment by rbx** [comment]
Thank you for the fix, I tried to take your branch and now select is properly chosen:
```
configure: Choosing polling system from 'select'...
configure: Using 'select' polling system
```

Unfortunately, the polling/send problem still remains even with select (I double checked to make sure I use the right library and by putting a test output inside of zmq code for select).

**Comment by bluca** [comment]
Thanks for testing. Any chance you could please try with the other pollers to see if any solves the issue? ```kqueue epoll devpoll pollset poll select``` (some might not be available on OSX)

**Comment by rbx** [comment]
Available for me where `kqueue (default)`, `poll`, `select`. All with the same problem.

I have had another machine that exhibited the same problem, but also two machines (MacOS 10.12.1 and same compiler) that were fine. So I am puzzled as to what is causing this.

**Comment by bluca** [comment]
I'm afraid I'm out of high-level ideas, and the only thing left is firing up GDB and having a look at what's actually happening. Would you be able to do that?

**Comment by rbx** [comment]
With Xcode debugger I followed it up through zmq_poller_wait_all() to poll(), where the arguments have the right values (pollfds), and poll() returns 1 (should be 0). It doesn't let me go deeper into poll() though. 

Take this with a grain of salt, since I'm not very familiar with zmq code base...

**Comment by bluca** [comment]
Right, so this seems to confirm that it's a problem with the system call on OSX. Thanks for checking.
If this is the case, I'm not sure if there's anything we can do! I can try to see if others have the same problem, the discussion you linked earlier will be the starting point.
