### ISSUE TITLE
ZMQ_SOCKS_PROXY does not resolve endpoint hostnames via the socks5 proxy

### ISSUE THREAD

**Issue by justusranvier** [zeromq/libzmq#2226]
When a socks5 proxy is set, then dns resolution should occur via the proxy rather than via the normal method.

This is especially necessary in cases where normal dns resolution will fail, such as if the endpoint is a Tor .onion address.

**Comment by bluca** [comment]
Unless I'm mistaken, the socks connecter doesn't even do name resolution:

https://github.com/zeromq/libzmq/blob/master/src/socks.cpp#L158

Do you have a use case / test case where this problem was verified? If I took an initial stab at it, would you be able to test it?

Should be doable to make it use a custom server via libresolv, although a bit of a pain as AFAIK the interface varies wildly between platforms (and wouldn't even know where to begin for Windows).

**Comment by justusranvier** [comment]
I found the problem by using a Tor daemon as a SOCKS5 proxy.

My ability to connect to remote endpoints was determined by whether or not the dns server specified in /etc/resolv.conf was capable of resolving the endpoint hostname.

Trying to connect to a .onion endpoint works if /etc/resolv.conf specifies the Tor daemon as the dns server, and fails if it uses a non-Tor DNS server (e.g 8.8.8.8)

Looking at the zmq code, I believe the problem is the calls to getaddrinfo, which will only return a resolved ip address if the local system is capable of resolving the name. In the case of Tor especially that's usually not going to work.

Socks5 servers allow the client to specify the destination server either as an ipv4 or v6 address, or as an unresolved hostname which the server must resolve itself, and this is what zeromq should do, at a minimum in the case where the hostname can't be resolved by getaddrinfo.

https://www.ietf.org/rfc/rfc1928.txt

**Comment by bluca** [comment]
I was working on overriding the default dns server in the encoder but it is tricky for portability.

But if socks5 supports sending a domain name then I'll do that instead, much simpler.

**Comment by bluca** [comment]
On the other hand, this is what it already does:

```
    hints.ai_flags = AI_NUMERICHOST;

    const int rc = getaddrinfo (req.hostname.c_str (), NULL, &hints, &res);
    if (rc == 0 && res->ai_family == AF_INET) {
        struct sockaddr_in *sockaddr_in =
            reinterpret_cast <struct sockaddr_in *> (res->ai_addr);
        *ptr++ = 0x01;
        memcpy (ptr, &sockaddr_in->sin_addr, 4);
        ptr += 4;
    }
    else
    if (rc == 0 && res->ai_family == AF_INET6) {
        struct sockaddr_in6 *sockaddr_in6 =
            reinterpret_cast <struct sockaddr_in6 *> (res->ai_addr);
        *ptr++ = 0x04;
        memcpy (ptr, &sockaddr_in6->sin6_addr, 16);
        ptr += 16;
    }
    else {
        *ptr++ = 0x03;
        *ptr++ = (unsigned char) req.hostname.size ();
        memcpy (ptr, req.hostname.c_str (), req.hostname.size ());
        ptr += req.hostname.size ();
    }
```

The getaddrinfo is set to not do a lookup, so it should fail with a hostname, which means the third branch of the if/else block will run.

**Comment by bluca** [comment]
Would you be able to rebuild with some debugs to confirm if that code is being used, or alternatively through wireshark to see what's actually on the wire?

**Comment by justusranvier** [comment]
I can rebuild and run a different branch, yes

**Comment by justusranvier** [comment]
This bug is probably invalid because I've never successfully set ZMQ_SOCKS_PROXY. It only appeared as if I was using the proxy successfully because some firewall rules that set up transparent proxying were allowing the connection to succeed.

**Comment by bluca** [comment]
Ok, does it work once the firewall has been fixed?

**Comment by justusranvier** [comment]
I won't know if it works for a while, because the real problem is that we're using the czmq wrapper to set up the socket, so zmq_setsockopt isn't going to work at all.

**Comment by bluca** [comment]
There are APIs for that in CZMQ, zsock_set_socks_proxy and zsock_socks_proxy

**Comment by justusranvier** [comment]
With czmq-4.0.1 I am able to set the proxy server and connecting to .onion endpoints does work even when the local system can not resolve them.
