### ISSUE TITLE
troubleshooting curve connections

### ISSUE THREAD

**Issue by amirtuval** [zeromq/libzmq#2227]
Hi,

I have successfully been able to use curve to encrypt the communication between client and server.
It works great.

My main concern is that when the curve handshake fails for some reason, it is very hard to troubleshoot.
For example, if the client has the wrong server public key, the client will timeout with an EAGAIN error - exactly the same behavior as if the server is down or if there's no network, so it is very hard to figure out the root cause is the wrong certificate.

The only thing I've been able to see, is that the server writes "CURVE I: cannot open client HELLO -- wrong server key?" to stdout, but that seems more of a debug message than anything else, and would probably be removed in future versions. (The code says //  Temporary support for security debugging - curve_server.cpp:314).
Also, this is running on both windows and linux. On windows it's running as a windows service, so writing to stdout is not a good solution.

What I'd like to have is some programatic interface that tells me handshake failed, so I can decide what to do (like write to application log file, prompt the user etc.).
This can be in the form of an error or an exception, or in the form of an event, like a zmonitor "Handshake Failed" event.

Is there something like this that is already implemented that I missed? Any advice on this would be appreciated.

Thanks
Amir

**Comment by bluca** [comment]
I don't think there is such a feature yet, but if you could send a PR to implement it it would be most welcome.

In general we don't use exceptions, so a zmonitor event as you suggested would probably be the best solution.

**Comment by vtellier** [comment]
Hi,

I've been exactly into the same use case, (see [stackoverflow](http://stackoverflow.com/questions/41380623/zmq-encryption-how-to-know-when-the-handshake-failed/41381693)).

I tried to enter a bit (just a bit) into the code of libzmq and it looks like the ERROR command of [CurveZMQ protocol](https://rfc.zeromq.org/spec:26/CURVEZMQ/) is already fully implemented.
So actually what is missing is to broadcast the event to the user? I'm asking because this feature is more than a nice to have for me, so I would be happy to try to implement it.

When thinking about it, we have the [zmq_socket_monitoring](http://api.zeromq.org/4-2:zmq-socket-monitor) which is really network related.
Would it not make more sense to add another layer of monitoring just above, which would provide information only related the "internal ZMQ layers" (can't find a better name):
Beyond the encryption handshakes, it might also provide information depending on the configuration of the ZMQ socket. For instance, a ROUTER could notify about a routing fail due to wrong identity, or when it drops messages due to HWM reached.
This is just an idea of course, so far I just miss the handshakes state.

**Comment by bluca** [comment]
That could also work, but I think it would be easier to use the existing monitoring infrastructure. Less code to write, less duplication, less bugs.

Also from the point of view of a user, it would be more intuitive I think to have all the socket monitoring happen through the same API. Then it becomes easier to integrate into existing application, as the only thing needed is to add the new bit to the mask.

In the end the monitor API is to get socket events, and the curve events are socket events so it wouldn't be out of place.

But if you decide to implement it it's of course up to you, the only request from the maintainers is to add the new APIs behind the DRAFT flag, everything else is up to you.

**Comment by vtellier** [comment]
@bluca When the client has a wrong server public key, the connection is closed (_silent_ error) and the client retries to connect, which leads to an endless reconnection loop.

To me this sounds wrong as the public key on the client side won't change, so the reconnections attempt will _always_ fail.

On the server side I'd like to consider handshake fails as _hard_ error (described on _[ZmqCurve](https://rfc.zeromq.org/spec:26/CURVEZMQ/) > General design_), and so send an ERROR command back to the client. What do you think about it?

**Comment by bluca** [comment]
That would be an API and protocol backward compatibility breakage, so unfortunately I don't think we can do it.

Also although the public key on the client won't change, it might change on the server side (key cycling etc etc)

**Comment by bluca** [comment]
For an example use case, consider a situation where in a cloud environment a new certificate is deployed and the applications are restarted to pick it up. The client and server reside on different instances, maybe different geographies, so synchronization is tricky.

Such a change in the protocol would mean that, unless care is exercised in restarting the client application strictly after the server application, race conditions and random failures might happen.

On the other hand with the protocol as it currently stands, the order does not matter and the client application simply tries again until it succeeds.

**Comment by vtellier** [comment]
Yes, that's perfectly fine for me :)

**Comment by bluca** [comment]
@amirtuval please let us know if the new monitor events that vtellier implemented solve your problem so that we can close this issue

**Comment by vtellier** [comment]
So far the solution I submitted doesn't covers 100% because the failure is not signaled on the client side.

I working on it now, will submit a PR soon.

**Comment by vtellier** [comment]
Here we go #2283 . On my application, I get it as expected:

- When having a wrong key: both client and server signal a handshake failure
- When having all good keys: both client and server signal a handshake success

Hopefully this is enough and works all good everywhere else.

**Comment by amirtuval** [comment]
Hey Guys

Thank you very much for this.
I'll do my best to test this. It'll probably take me some time, but I'll update you when I get some results.

Thanks

**Comment by sigiesec** [comment]
As I understand this, this was fixed by #2645. Please reopen if this ticket addresses something beyond the current solution.
