### ISSUE TITLE
4.2.0 version of the ZMQ crazy use of network I/O

### ISSUE THREAD

**Issue by YPeng123** [zeromq/libzmq#2232]
在windows 环境下，使用了monitor后，消耗了大量网络I/O资源。上传和下载速度都高达13MB/s。
In the windows environment, the use of the monitor, a large number of network consumption of I/O resources. Upload and download speeds up to 13MB/s.

**Comment by YPeng123** [comment]
![image](https://cloud.githubusercontent.com/assets/24284021/20780387/66d6dbaa-b7b5-11e6-8f32-8bcaaf7a2ad1.png)
在上面的图片中显示了出现问题的情况，两个进程登陆了相同的后台服务器，出现问题的进程使用的是4.2.0版本的libzmq.dll，没出问题的进程使用的是4.1.5版本的libzmq.dll。
可以看出，网络I/O高达26MB/s。
In the picture above shows the case of problems, the two process landing the same backend server, use the process of the problem is the 4.2.0 version of libzmq.dll, no problem is the process of using the 4.1.5 version of libzmq.dll.
It can be seen that the network 26MB/s up to I/O.

**Comment by bluca** [comment]
Would you be able to upload to gist or pastebin a small test case that reproduces the problem?

**Comment by hnwyllmm** [comment]
what's the pattern of ZMQ sockets you use? monitor socket does not use network

**Comment by bluca** [comment]
No answer in 2 years, closing for housekeeping
