### ISSUE TITLE
Problem: missing CLOEXEC flag on eventfd and epoll instances

### ISSUE THREAD

**Issue by rtlfu** [zeromq/libzmq#2242]
on Linux, libzmq is leaking file descriptors when fork+exec for lack of CLOEXEC flag.

See
https://github.com/zeromq/libzmq/blob/master/src/epoll.cpp#L51
https://github.com/zeromq/libzmq/blob/master/src/signaler.cpp#L384

On other platforms, a possible candidate is
https://github.com/zeromq/libzmq/blob/master/src/signaler.cpp#L640

**Comment by bluca** [comment]
The flag is set for other sockets:
https://github.com/zeromq/libzmq/blob/master/src/ip.cpp#L51

So it sounds like the correct thing to set it for those too.
Would you be able to send a PR?

**Comment by rtlfu** [comment]
I have yet to figure out how to do a PR?!

**Comment by bluca** [comment]
Do you need some tips on how to set everything up? Github's documentation should be a good starting point
