### ISSUE TITLE
zmq_disconnect does not work, socket still established

### ISSUE THREAD

**Issue by wumuzi520** [zeromq/libzmq#2243]
PUSH/PULL mode， when I disconnect a address use zmq_disconnect, the socket still established. why?

**Comment by bluca** [comment]
What do you mean by established? Can messages still be sent? Could you provide a minimal test case that reproduces the problem?

**Comment by wumuzi520** [comment]
netstat -anp|grep 7000

**Comment by wumuzi520** [comment]
$ netstat -anp|grep 7000
tcp        0      0 10.11.6.129:7000            0.0.0.0:*                   LISTEN      380/./sentryd
tcp        0      0 10.11.6.129:34090           10.11.6.113:7000            ESTABLISHED 380/./sentryd
tcp        0      0 10.11.6.129:59993           10.11.8.67:7000             ESTABLISHED 380/./sentryd
tcp        0      0 10.11.6.129:46419           10.19.17.153:7000           ESTABLISHED 380/./sentryd

I disconnect address 10.11.8.67:7000， but the session still be captured by netstat

**Comment by bluca** [comment]
The sockets commands are handled asynchronously, so that's expected. Are messages still going through?

**Comment by wumuzi520** [comment]
Messages can not go through, but I want to make it gone when I disconnect an address. so, what should I do?

**Comment by bluca** [comment]
Nothing. It will happen in due time when all the internal bits have been torn down.

Part of the usefulness of zmq is that these low level details are handled for you

**Comment by wumuzi520** [comment]
We often use 'netstat' or 'ss' shell commands to see which connections is still keepping. If the zmq_disconnect can not make connection closed, I can not make a judgment weather the connection is really disconnect.

**Comment by bluca** [comment]
It can and it does. It's asynchronous.

You can make it happen quicker by setting ZMQ_LINGER to 0 on the socket, but I recommend NOT to and to just let it work its way through

**Comment by wumuzi520** [comment]
Ok thanks! I'm very appreciate for you!

**Comment by bluca** [comment]
You are very welcome. If you have any other issue please open another ticket, closing this now since it's solved.
