### ISSUE TITLE
4.2.0 problem with boost.fiber

### ISSUE THREAD

**Issue by wanghengwei** [zeromq/libzmq#2246]
Hi,
When I used zmq 4.2.0 in Boost.Fiber, it always crashed, but it is ok if using zmq 4.1.3
Code:
```
#include <zmq.h>
#include <boost/fiber/all.hpp>

namespace fibers = boost::fibers;

void *ctx;

void foo() {
	// It won't crash if replacing ZMQ_REP with ZMQ_SERVER
	auto sock = zmq_socket(ctx, ZMQ_REP);
	int r = zmq_bind(sock, "inproc://test");
	BOOST_ASSERT(r == 0);
	zmq_msg_t msg;
	zmq_msg_init(&msg);
	zmq_msg_recv(&msg, sock, ZMQ_DONTWAIT);
	zmq_msg_close(&msg);
	zmq_close(sock);
}

int main() {
	ctx = zmq_ctx_new();

	fibers::fiber f(foo);
	f.join();

	printf("OK\n");
	return 0;
}
```
The stack traceback seems random:
![3](https://cloud.githubusercontent.com/assets/2122673/21044111/3f353f0c-be35-11e6-91de-195c37a00f27.PNG)
![4](https://cloud.githubusercontent.com/assets/2122673/21044117/4371d120-be35-11e6-8308-719702b3ce3f.PNG)

My environment:
OS: Windows 10
Compiler: MSVC 14 32bit
Boost: 1.62 or 1.63-b1 static lib
libzmq: tag 4.2.0 or master(519940d)

**Comment by bluca** [comment]
How does the client code looks like? Do you have a minimal repro for that?

**Comment by wanghengwei** [comment]
No client. It will crash as long as invoking `zmq_bind` or `zmq_connect` in fiber, e.g.
```
#include <zmq.h>
#include <boost/fiber/all.hpp>

int main() {
	auto ctx = zmq_ctx_new();

	boost::fibers::fiber([ctx]() {
		auto sock = zmq_socket(ctx, ZMQ_REP);
		zmq_bind(sock, "inproc://test");
	}).join();

	printf("OK\n");
	return 0;
}
```

**Comment by bluca** [comment]
I don't really know what fiber is, what does that do? Does it spawn another thread or something like that?

**Comment by wanghengwei** [comment]
It is like coroutine, it does not spawn new native thread.

http://www.boost.org/doc/libs/1_62_0/libs/fiber/doc/html/fiber/overview.html

> Boost.Fiber provides a framework for micro-/userland-threads (fibers) scheduled cooperatively.

**Comment by bluca** [comment]
The fact that you mention that it doesn't happen with ZMQ_SERVER, which is thread-safe, suggests using that library in that way causes a data sharing issue. ZMQ_REP/Q sockets CANNOT be used from multiple threads.

**Comment by wanghengwei** [comment]
and it doesn't happen for zeromq-4.1.x branch

**Comment by wanghengwei** [comment]
I found out the problem:
```
if (WIN32)
    #   Socket limit is 16K (can be raised arbitrarily)
    add_definitions (-DFD_SETSIZE=16384)
...
```
This definition cause the size of fd_set is too big to exceed the stack of coroutine, so that the context of coroutine is destroyed.

**Comment by bluca** [comment]
How are you building the library? Visual studio, cmake...?

**Comment by bluca** [comment]
You can override that definition easily:

```CPPFLAGS=-DFD_SETSIZE=xyz```

**Comment by bluca** [comment]
Closing since this can be solved by changing the build flag. Please reopen if that's not enough to fix the problem.
