### ISSUE TITLE
Crash from PUB socket on heavy workload

### ISSUE THREAD

**Issue by sublee** [zeromq/libzmq#2252]
I've been making a game server with ZeroMQ's Pub/Sub messaging pattern.  I got a critical problem by using `PUB`/`SUB` sockets.  Sometimes my processes are aborted with assertion failure from ZeroMQ:

```
Assertion failed: erased == 1 (src/mtrie.cpp:297)
```

I tried with pyzmq-16.0.2 over libzmq-4.2.0. 
 
In my case, a `SUB` socket binds to an address then a `PUB` socket connects to the address.  All of `PUB` sockets and `SUB` sockets in a cluster connect with each others.  They makes a fully connected network among 500+ server processes.

A `SUB` socket frequently subscribes or unsubscribes their topics.  The topics in a cluster grow up since the cluster started.  At a moment when I checked, one of `SUB` sockets is subscribing 3000+ topics.

I saw 3 aborting scenarios:

1. When a `SUB` socket closes, some `PUB` sockets abort.  Perhaps it is a concurrency bug from [pyzmq](https://github.com/zeromq/pyzmq) what I'm using.  I reproduced it by a test case.  And I think [I fixed it](https://github.com/what-studio/pyzmq/commit/94ab0a88dbef7d0f33b34cdf18e55487735dde01).
2. When a `PUB` socket joins to a mature cluster it aborts almost immediately.  A mature cluster means there are already so many subscribing topics and subscribe/unsubscribe synchronization messages.
3. A `PUB` socket on a weak host machine (e.g. AWS EC2 t2.medium), sometimes aborts.  I'm not sure what is the point.

Unfortunately, I couldn't reproduce the last 2 scenarios by a small code.  But my server still has been aborted.

The assertion failure occurs when a `PUB` socket tries to remove a pipe to a `SUB` socket but there's no matched pipe.  I'm wondering if ZeroMQ guarantees the consistency of subscribe/unsubscribe synchronizations between busy `PUB` and `SUB` sockets.

**Comment by bluca** [comment]
Are you using a socket from multiple threads? That is usually the prime
cause of crashes.

Also, usually the PUB binds and the SUB connects, although it should
work the other way around as well.

In these cases a minimal code snippet that reproduces the problem is the
best way to get to a resolution

**Comment by sublee** [comment]
@bluca I have a code snippet using PyZMQ and gevent which reproduces the first scenario.

https://github.com/what-studio/pyzmq/blob/pubsub-crash/zmq/tests/test_pubsub.py#L50

I think I already fixed this issue by [patching PyZMQ](https://github.com/what-studio/pyzmq/commit/94ab0a88dbef7d0f33b34cdf18e55487735dde01).  But I still have more crash issues.  Maybe PyZMQ with gevent doesn't guarantee greenlet(thread in gevent) safety.

**Comment by bluca** [comment]
Sorry but I'm not familiar with gevent. In general sockets must be created, used and destroyed from the same thread as the documentation says. If that use case does not respect this constraint then my guess is on that being the issue. Please do report back if you are able to find more about gevent

**Comment by sublee** [comment]
@bluca Okay.  I'll test more.

**Comment by bluca** [comment]
Reopening as there were than one issue tracked here

**Comment by minrk** [comment]
sorry, auto-closed by the PR.

**Comment by bluca** [comment]
Yes no worries :-) It's good to keep track

By the way, do you have any insight on the gevent issue we were speaking about?

**Comment by minrk** [comment]
I'm not quite sure how this could be a threadsafety issue, as gevent uses 'green threads' (aka cooperative multitasking in a single thread), so there should be no concurrent C calls. The main thing the use of gevent ought to guarantee is that this can be reproduced in a single-threaded program. There is a chance, however, that there could be a delay between an event being triggered and the event being handled. I'm not familiar with the relevant inner workings of this part of zmq, though.

**Comment by sublee** [comment]
So @minrk you don't think we should lock every ZMQ operations for gevent.

**Comment by sublee** [comment]
@bluca Even though when a `PUB` socket is in mute state, does it never drop `SUBSCRIBE`, `UNSUBSCRIBE`, or disconnection events from `SUB` sockets?

**Comment by bluca** [comment]
Don't remember off the top of my head, will have to check

**Comment by sublee** [comment]
@bluca Thank you!  I'll wait for you.

**Comment by sublee** [comment]
Here's a code to reproduce the second scenario:

```python
# -*- coding: utf-8 -*-
from collections import defaultdict
import random
import time

import gevent.monkey; gevent.monkey.patch_time()  # noqa
import zmq.green as zmq


# Number of SUB sockets at least 2.
n = 2
# Number of topics.
m = 1000


t = time.time()
c = zmq.Context()
p = c.socket(zmq.PUB)
p.set(zmq.RCVHWM, 1000)  # It doesn't matter to lead the crash.
topic = lambda x: ('%08x' % abs(hash(str(x))))[:8]


print '1. Spawn %d SUB sockets' % n
subs = []
ports = []
for x in range(n):
    s = c.socket(zmq.SUB)
    s.set(zmq.SNDHWM, 10)  # Lower high water mark leads the crash faster.
    for x in range(m):
        s.set(zmq.SUBSCRIBE, topic(x))
    port = s.bind_to_random_port('tcp://127.0.0.1')
    ports.append(port)
    subs.append(s)


print '2. Connect to SUB sockets'
for port in ports:
    p.connect('tcp://127.0.0.1:%d' % port)


print '3. Subscribing/Unsubscribing...'
topics = defaultdict(set)
while True:
    for s in subs:
        if topics[s] and random.random() < 0.5:
            t = random.choice(list(topics[s]))
            s.set(zmq.UNSUBSCRIBE, t)
        else:
            t = topic(random.randrange(m))
            s.set(zmq.SUBSCRIBE, t)
            topics[s].add(t)
    time.sleep(0)  # Only 0 seconds lead the crash.
```

I tried with PyZMQ-16.0.2, ZeroMQ-4.2.0, gevent-1.1.2, and CPython-2.7.11.  Does anyone have an idea?

**Comment by sublee** [comment]
There was a mistake on my code to reproduce the crash.  I had to remove an unsubscribed topic `t` from `topics[s]` after `s.set(zmq.UNSUBSCRIBE, t)` but I didn't.  So the right code should be:

```python
topics = defaultdict(set)
while True:
    for s in subs:
        if topics[s] and random.random() < 0.5:
            t = random.choice(list(topics[s]))
            s.set(zmq.UNSUBSCRIBE, t)
            topics[s].remove(t)
        else:
            t = topic(random.randrange(m))
            s.set(zmq.SUBSCRIBE, t)
            topics[s].add(t)
    time.sleep(0)  # Only 0 seconds lead the crash.
```

When I fixed it, this code didn't crash anymore.  Now I have a new question:

When `SUB` socket sends asymmetric `SUBSCRIBE`/`UNSUBSCRIBE` messages over its high water mark, may `PUB` socket crash by intent? (`zmq_assert (erased == 1)`)

@bluca, do you have any idea?  Or do you know anyone who may know about it?

**Comment by bluca** [comment]
Don't know sorry. Again if you can reproduce this with just libzmq it would be very useful.

I'm on holiday right now so I wasn't able to check, I'll try to find time in the next week.

**Comment by sublee** [comment]
@bluca Sure.  I'll keep reproducing the crash by libzmq without any dependency.  Have a nice holiday. 😄

**Comment by bluca** [comment]
It shouldn't crash and it should simply drop subscriptions that exceed the HWM. Can you reproduce the crash? If so can you share how?

**Comment by bluca** [comment]
@sublee any updates on this?

**Comment by sublee** [comment]
@bluca No I didn't succeed to reproduce yet.  It looks like a bug in only PyZMQ.

**Comment by bluca** [comment]
Have you opened an issue on the pyzmq repo?

**Comment by sublee** [comment]
@bluca Yes, I did.  This issue is better to be closed for now.

**Comment by bluca** [comment]
Thanks!

**Comment by saifhhasan** [comment]
Hello, I am getting the same crash but I am not using pyzmq (just libzmq and lightweight C++ wrapper using zmqcpp). Crash happens in mtrie.cpp ... Couldn't see anything wrong with our code. 

Symptoms: We have 1000+ topics and 30+ subscribers. PUB binds and SUB connects. Crash happens on PUB side (single publisher) and not reproducible easily. I do think problem is somewhere in libzmq

```
    @ 0000000002de8e1d folly::symbolizer::(anonymous namespace)::signalHandler(int, siginfo_t*, void*)
                       ./folly/experimental/symbolizer/SignalHandler.cpp:414
    @ 00007f65e7b94acf (unknown)
    @ 00007f65e71967c8 gsignal
    @ 00007f65e7198590 abort
    @ 0000000002fc6838 zmq::zmq_abort(char const*)
                       /home/engshare/third-party2/zeromq/4.2.1/src/libzmq-4.2.1/src/err.cpp:87
    @ 0000000002ff223e zmq::mtrie_t::rm_helper(unsigned char*, unsigned long, zmq::pipe_t*)
                       /home/engshare/third-party2/zeromq/4.2.1/src/libzmq-4.2.1/src/mtrie.cpp:297
    @ 0000000002ff2053 zmq::mtrie_t::rm_helper(unsigned char*, unsigned long, zmq::pipe_t*)
                       /home/engshare/third-party2/zeromq/4.2.1/src/libzmq-4.2.1/src/mtrie.cpp:315
    @ 0000000002ff2053 zmq::mtrie_t::rm_helper(unsigned char*, unsigned long, zmq::pipe_t*)
                       /home/engshare/third-party2/zeromq/4.2.1/src/libzmq-4.2.1/src/mtrie.cpp:315
    @ 0000000002ff2053 zmq::mtrie_t::rm_helper(unsigned char*, unsigned long, zmq::pipe_t*)
                       /home/engshare/third-party2/zeromq/4.2.1/src/libzmq-4.2.1/src/mtrie.cpp:315
    @ 0000000002ff2053 zmq::mtrie_t::rm_helper(unsigned char*, unsigned long, zmq::pipe_t*)
                       /home/engshare/third-party2/zeromq/4.2.1/src/libzmq-4.2.1/src/mtrie.cpp:315
    @ 0000000002ff2053 zmq::mtrie_t::rm_helper(unsigned char*, unsigned long, zmq::pipe_t*)
                       /home/engshare/third-party2/zeromq/4.2.1/src/libzmq-4.2.1/src/mtrie.cpp:315
    @ 0000000002ff2053 zmq::mtrie_t::rm_helper(unsigned char*, unsigned long, zmq::pipe_t*)
                       /home/engshare/third-party2/zeromq/4.2.1/src/libzmq-4.2.1/src/mtrie.cpp:315
    @ 0000000002ff2053 zmq::mtrie_t::rm_helper(unsigned char*, unsigned long, zmq::pipe_t*)
                       /home/engshare/third-party2/zeromq/4.2.1/src/libzmq-4.2.1/src/mtrie.cpp:315
    @ 0000000002ff2053 zmq::mtrie_t::rm_helper(unsigned char*, unsigned long, zmq::pipe_t*)
                       /home/engshare/third-party2/zeromq/4.2.1/src/libzmq-4.2.1/src/mtrie.cpp:315
    @ 0000000002ff2053 zmq::mtrie_t::rm_helper(unsigned char*, unsigned long, zmq::pipe_t*)
                       /home/engshare/third-party2/zeromq/4.2.1/src/libzmq-4.2.1/src/mtrie.cpp:315
    @ 0000000002ff2053 zmq::mtrie_t::rm_helper(unsigned char*, unsigned long, zmq::pipe_t*)
                       /home/engshare/third-party2/zeromq/4.2.1/src/libzmq-4.2.1/src/mtrie.cpp:315
    @ 0000000002ff2053 zmq::mtrie_t::rm_helper(unsigned char*, unsigned long, zmq::pipe_t*)
                       /home/engshare/third-party2/zeromq/4.2.1/src/libzmq-4.2.1/src/mtrie.cpp:315
    @ 0000000002ff2053 zmq::mtrie_t::rm_helper(unsigned char*, unsigned long, zmq::pipe_t*)
                       /home/engshare/third-party2/zeromq/4.2.1/src/libzmq-4.2.1/src/mtrie.cpp:315
    @ 0000000002ff2e81 zmq::mtrie_t::rm(unsigned char*, unsigned long, zmq::pipe_t*)
                       /home/engshare/third-party2/zeromq/4.2.1/src/libzmq-4.2.1/src/mtrie.cpp:315
    @ 0000000002fe588a zmq::xpub_t::xread_activated(zmq::pipe_t*)
                       /home/engshare/third-party2/zeromq/4.2.1/src/libzmq-4.2.1/src/xpub.cpp:113
    @ 0000000002fe3e6d zmq::xpub_t::xattach_pipe(zmq::pipe_t*, bool)
                       /home/engshare/third-party2/zeromq/4.2.1/src/libzmq-4.2.1/src/xpub.cpp:81
    @ 0000000002fd8ea6 zmq::socket_base_t::process_bind(zmq::pipe_t*)
                       /home/engshare/third-party2/zeromq/4.2.1/src/libzmq-4.2.1/src/socket_base.cpp:326
    @ 0000000002fc9f38 zmq::object_t::process_command(zmq::command_t&)
                       /home/engshare/third-party2/zeromq/4.2.1/src/libzmq-4.2.1/src/object.cpp:105
    @ 0000000002fd30f4 zmq::socket_base_t::process_commands(int, bool) [clone .constprop.153]
                       /home/engshare/third-party2/zeromq/4.2.1/src/libzmq-4.2.1/src/socket_base.cpp:1360
    @ 0000000002fd52df zmq::socket_base_t::send(zmq::msg_t*, int)
                       /home/engshare/third-party2/zeromq/4.2.1/src/libzmq-4.2.1/src/socket_base.cpp:1104
    @ 0000000002fb4add zmq_msg_send
                       /home/engshare/third-party2/zeromq/4.2.1/src/libzmq-4.2.1/src/zmq.cpp:375
```

**Comment by saifhhasan** [comment]
I create socket in main thread and all writes to it (on PUB socket) are from a different thread which is started by main thread after creating sockets. Bind happens in main thread.

Does this impose any problems ?

**Comment by bluca** [comment]
Yes, sockets are not thread safe as the doc says, so try to use it and create it from the same thread

**Comment by mrseanmorris** [comment]
According to the api documentation, it is safe to create a socket in one thread and use it in another, with a few caveats.  Here's the relevant text from [http://api.zeromq.org/4-2:zmq](url)

**Thread safety**

A ØMQ context is thread safe and may be shared among as many application threads as necessary, without any additional locking required on the part of the caller.

Individual ØMQ sockets are not thread safe except in the case where full memory barriers are issued when migrating a socket from one thread to another. In practice this means applications can create a socket in one thread with zmq_socket() and then pass it to a newly created thread as part of thread initialisation, for example via a structure passed as an argument to pthread_create().

**Comment by saifhhasan** [comment]
@bluca I created the socket in same thread and the exact crash I mentioned above still exists. All I do is send multipart message on PUB socket (msg1=subscriptionToken, msg2=data) and subscribers subscribes to subscription tokens of their choice. There are 1000+ unique subscription tokens. Don't have consistent repro yet but I think it is something related to internal of libzmq.

**Comment by bluca** [comment]
Ok, then please try to reproduce without zmqpp

**Comment by bluca** [comment]
Also make sure the socket is not being closed from another thread - that looks like a pipe disappearing
