### ISSUE TITLE
Precompiled header doesn't work using CMake to generate MSVC project

### ISSUE THREAD

**Issue by XinyuHou** [zeromq/libzmq#2253]
```
cd /zmq/src/dir
mkdir build
cd build
cmake -G "Visual Studio 14 2015 Win64" .. 
```

I can compile the code in vs2015, but when I check the project, it doesn't use precompiled headers.

Using QtCreator with MSVC2015 kit, it tries to build the project with precompiled headers on, but failed to file the file.

> libzmq\src\address.cpp(30): fatal error C1083: Cannot open precompiled header file: 'precompiled.pch': No such file or directory

In the root CMake file at line 692, it supposes to enable the precompiled header option for precompiled.hpp file, if I understand it correctly.

Am I doing something wrong?

**Comment by bluca** [comment]
Sorry but I'm not very familiar with the Windows environment. There are a few Windows developers following the mailing list, I would suggest asking there.

**Comment by XinyuHou** [comment]
Could you let me know the mailing list address? Thanks.

**Comment by bluca** [comment]
http://zeromq.org/docs:mailing-lists

**Comment by XinyuHou** [comment]
Thanks @bluca

**Comment by JohanMabille** [comment]
@bluca @XinyuHou it seems setting the `/Yc` flag on the `precompiled.cpp` file doesn't make it to be the first file to compile.

Putting `precompiled.cpp` as the first file in `cxx-source` fixes the problem. There's still a problem with `nmake install` however.

I will submit a PR when everything is fixed.

**Comment by XinyuHou** [comment]
@JohanMabille 
I removed the precompiled header requirement in the cmake file for Windows

**Comment by themightyoarfish** [comment]
I'm getting a similar error 
```
Cannot open compiler intermediate file: 'c:\users\user\downloads\libzmq433\libzmq-4.3.3\out\build\x64-release\precompiled.pch': Permission denied
```
when compiling 4.3.3 with visual studio 16.8.4 on Windows 10. Is this related?
