### ISSUE TITLE
Interaction between non-blocking use of sockets and multi-part messages

### ISSUE THREAD

**Issue by rotty** [zeromq/libzmq#2269]
I'm working on high(er)-level [Rust bindings for libzmq](https://github.com/erickt/rust-zmq), and would like to provide a multipart API that works well with non-blocking mode. The resulting API would be simpler if I could be sure that when I was able to receive the first part of a multi-part message, receiving further parts could not encounter `EAGAIN`. Similarly for sending, it would be nice to know that being able to enqueue the first part, the subsequent parts will not cause `EAGAIN`.

The following statement can kinda-sorta be read between the lines in the documentation, if one applies some imagination, but I wonder if it really holds:

- When receiving a message from a socket, and `zmq_msg_more()` returns true on that message, can I assume all further message parts can be read without blocking (i.e. no `EAGAIN` errors with `ZMQ_DONTWAIT`)?

For sending, my imagination was not vivid enough to read an analogous statement into the existing documentation.

So, are there any such guarantees, or is this, on the contrary, an expectation that is not (or can/should not be) fulfilled by libzmq? Either way, it would be nice if the documentation would be more explicit on that point.

**Comment by bluca** [comment]
As far as I can see, it's possible that the decoder sets the MORE flag when receiving, but without having received yet the following messages.
For example, it could do a TCP read from the kernel buffer of 2 out of 3 messages, set the MORE flag in the first 2, and then the TCP connection blows up before enough data is read from the kernel for the whole final part.

Now my memory isn't entirely fresh so I'd have to go read the code again to remember what exactly happens in that case. I think the library will attempt to fix the connection, but in the meanwhile you'd get EAGAIN. But don't quote me on this.

**Comment by tailhook** [comment]
> As far as I can see, it's possible that the decoder sets the MORE flag when receiving, but without having received yet the following messages.

I haven't been following zmq development lately, but it wasn't the case in previous versions. And I'm pretty sure zeromq can't sanely work this way. Consider the following situation:

1. You can a zmq socket connected to peers A and B
2. Peer A sends first frame with MORE flag set
3. Then peer A start very expensive computation before being able to send more frames
4. Then peer B sends many smaller messages

@bluca if what you're saying is true then all messages from peer B would be blocked by waiting for peer A to send next frames (because socket is still in state where MORE flag is set so it can't be used to receive messages from other peers).

**Comment by bluca** [comment]
The MORE flag is per message though, not per socket. It just tells the user of the library that it can get more messages.

If you read v2decoder.cpp/hpp and decoder.hpp, MORE is read and set from each message's header upon decoding

**Comment by tailhook** [comment]
Yes. What I'm trying to say is: if peer A has a message "xyz" and peer B has message "pqr", then if you've received "x" from peer A, and that message has MORE flag, you can't receive any of "p", "q", "r" until you receive "y" and "z".

**Comment by tailhook** [comment]
Okay so here is the [relevant portion of code in fq.cpp](https://github.com/zeromq/libzmq/blob/master/src/fq.cpp#L94-L124). Fair queueing is an algorithm that is used to receive from req/rep and pull sockets.

Is it convincing enough to make documentation more clear?

**Comment by rotty** [comment]
Quoting from the code that @tailhook referenced:

>      //  Check the atomicity of the message.
>      //  If we've already received the first part of the message
>      //  we should get the remaining parts without blocking.

The comment above only applies to the receiving side, but I think I have found a corresponding comment there as well in [lp.cpp](https://github.com/zeromq/libzmq/blob/master/src/lb.cpp#L111-L120):

>        // If send fails for multi-part msg rollback other
>        // parts sent earlier and return EAGAIN.
>        // Application should handle this as suitable

So in summary, this would be the semantics I'd assume:

- Upon receive, all parts of a multi-part message can be received without blocking.

- Upon sending, encountering `EAGAIN` on a message part can happen, but it means the whole multipart message needs to be retried.

Is this a valid conclusion? If so, I'd try to prepare a documentation patch.

**Comment by tailhook** [comment]
> Upon sending, encountering EAGAIN on a message part can happen, but it means the whole multipart message needs to be retried.

This is strange because of:
```
bool zmq::lb_t::has_out ()
{

    //  If one part of the message was already written we can definitely
    //  write the rest of the message.
    if (more)
        return true;
```
Basically this snippet means you can't poll for write if `more` is set.

**Comment by tailhook** [comment]
Ah, okay, basically when EAGAIN returned this means the pipe (connection) you have been sending message to is terminating. So while I don't understand why it isn't just activate `dropping` mode, you're right, upon sending you need to handle EAGAIN.

Actually, another case where EAGAIN may appear as far as I can see is when, user lowers high water mark in the middle of the message, which is obscure, but may happen nevertheless :)

**Comment by bluca** [comment]
> Upon receive, all parts of a multi-part message can be received without blocking.

Yes, from the socket side of the pipe, I was referring to the other side in the I/O thread. I have to check again how messages are delivered in the internal pipe, it looks like they are delivered atomically but can't remember the exact mechanic.

In the decoder, given it's reading from the kernel buffer, there's no guarantee it will get everything in one go, and that's what I was referring to.

> Upon sending, encountering EAGAIN on a message part can happen, but it means the whole multipart message needs to be retried.

That's correct, and that's how CZMQ implements multi-part message support for example:

https://github.com/zeromq/czmq/blob/master/src/zmsg.c#L125

**Comment by bluca** [comment]
No further updates, assuming the information provided was enough, closing for housekeeping
