### ISSUE TITLE
zmq_msg_routing_id not linking using C api (4.2.0)

### ISSUE THREAD

**Issue by galileolajara** [zeromq/libzmq#2270]
using pure C (zmq.h) and -D ZMQ_BUILD_DRAFT_API, both gcc (6.2.1) and clang (3.8.1) complains about zmq_msg_routing_id as undefined reference while the rest of the functions are ok.

It works after I tried prepending: extern "C" in src/zmq_draft.h and src/zmq.cpp

thanks for all efforts in ZeroMQ!

**Comment by galileolajara** [comment]
also affects zmq_msg_set_routing_id

**Comment by bluca** [comment]
Are you rebuilding libzmq? If so are you configuring it with --enable-drafts?

**Comment by galileolajara** [comment]
didn't knew about that. tried --enable-drafts from a clean tarball. It works now! thanks!

**Comment by bluca** [comment]
No problem. It's mentioned in the NEWS for 4.2.0 which introduces these new APIs.
