### ISSUE TITLE
HTTPS://zeromq.org

### ISSUE THREAD

**Issue by petehayes102** [zeromq/libzmq#2279]
Apologies if this is poorly directed. I couldn't find a repo for the website to create an issue there.

As someone who links to zeromq.org from a 'secure' site, i.e. https://, it's frustrating that you don't support SSL yourselves, especially with free certificates floating around (https://letsencrypt.org).

Is it possible that someone can tweak the server(s) to support SSL?

**Comment by petehayes102** [comment]
Oh I forgot to mention - I'm aware that there's a redirect from https => http, though that involves going through a very angry browser warning about non-secure connections.

**Comment by petehayes102** [comment]
Also, somewhat ironically, curvezmq.org doesn't support SSL either. I'll add that to the wishlist. 😄

**Comment by keith-dev** [comment]
Maybe curvezmq isn't the best interface for this, as the name implies elliptic curve crypto.

I think a new sslzmq might be a better way to handle this requirement.

**Comment by petehayes102** [comment]
Hey Keith, apologies that last comment wasn't clear - I'm talking about the _website_, not CurveZMQ itself! I'd like to see https:// support for curvezmq.org.

**Comment by keith-dev** [comment]
Ok, got it.

**Comment by bluca** [comment]
The best place for this kind of queries is the mailing list:

https://lists.zeromq.org/pipermail/zeromq-dev/2016-December/031274.html

Hopefully the folks that manage the website can answer. Closing this in the meanwhile.

**Comment by petehayes102** [comment]
No worries. Thanks for the fwd mate!
