### ISSUE TITLE
CMAKE tests generation under windows leads to linking error

### ISSUE THREAD

**Issue by vtellier** [zeromq/libzmq#2286]
While trying to execute the tests I struggled a bit with their compilation.
The documentation [(tests/README.md)](https://github.com/zeromq/libzmq/blob/master/tests/README.md) says:

> # Building tests in Windows
> 
> Install CMAKE
> CMD> CMAKE libzmq/tests
> CMD> tests.sln
> CMD> # build all projects in the solution
> 

However I was faicing linking error on libzmq.lib.
After researches I found out these comments in [tests/CMakeLists.txt](https://github.com/zeromq/libzmq/blob/master/tests/CMakeLists.txt):

>     # This is the output for Debug dynamic builds on Visual Studio 6.0
>     # You should provide the correct directory, don't know how to do it automatically
>     find_path(LIBZMQ_PATH "libzmq.lib" PATHS "../bin/Win32/Debug/v120/dynamic")

I just changed _v120_ to _v140_ as I am under Visual studio 2015 and it worked.
The thing is that it was the first time I used CMAKE so I spent some time trying to spot it.

Would it be possible to add a line about that in  [tests/README.md](https://github.com/zeromq/libzmq/blob/master/tests/README.md), or to make this fully automatic?

**Comment by bluca** [comment]
Please do send a PR to update the README and I'll merge it.

I'm not a Windows expert so not sure if it can be automated, hopefully someone else can help here.

**Comment by vtellier** [comment]
For me the note in the README file is fair enough, would you like me to close the issue or should I keep it open until a Windows expert goes further?

**Comment by bluca** [comment]
Let's close it for now, if someone else on Windows wants to try and automate this they will
