### ISSUE TITLE
Error static linking with libzmq.a

### ISSUE THREAD

**Issue by xunzhang** [zeromq/libzmq#2300]
I am using static linking library libzmq.a but met following problem:

```
libzmq.a(src_libzmq_la-zmq.o): relocation R_X86_64_32 against _ZSt7nothrow can not be used when making a shared object; recompile with -fPIC
libzmq.a: error adding symbols: Bad value
```

Help!

**Comment by bluca** [comment]
As the compiler suggests you are probably building a program with -fPIE but you have not built the library with -fPIC. Is this the case?

**Comment by xunzhang** [comment]
So how can I modify the CMakelists.txt or configure to generate static libzmq.a?

**Comment by bluca** [comment]
It's always created by default

**Comment by xunzhang** [comment]
Oh, the default one returns the above error message, the latest version 4.2.1.

**Comment by bluca** [comment]
If you need to built with fPIC, then you need to pass the distribution and compiler specific flags to the configure options. For example on Ubuntu something like this should work:

./configure CPPFLAGS=-DPIC CFLAGS=-fPIC CXXFLAGS=-fPIC LDFLAGS=-fPIC

**Comment by xunzhang** [comment]
I will try now. Does libzmq support something like this `./configure --disable-shared --enable-static`

**Comment by bluca** [comment]
yes

**Comment by xunzhang** [comment]
It works after adding this flags, thanks a lot @bluca !

**Comment by bluca** [comment]
no problem
