### ISSUE TITLE
Crash on windows 2008 server

### ISSUE THREAD

**Issue by Attention** [zeromq/libzmq#2303]
When I used pyzmq16.0.2(libzmq 4.1.6) in multi-process ,I create about 12 processes, there is a crach:

Assertion failed: nbytes == sizeof (dummy) (bundled\zeromq\src\signaler.cpp:182)
Assertion failed: nbytes == sizeof (dummy) (bundled\zeromq\src\signaler.cpp:182)

I check code ,and make a patch , problem resolved, wish I can help it:

void zmq::signaler_t::send ()
{
.........
#elif defined ZMQ_HAVE_WINDOWS
unsigned char dummy = 0;
while(true){
int nbytes = ::send (w, (char*) &dummy, sizeof (dummy), 0);
wsa_assert (nbytes != SOCKET_ERROR);
if (nbytes == sizeof (dummy))
break;
}
//int nbytes = ::send (w, (char*) &dummy, sizeof (dummy), 0);
//wsa_assert (nbytes != SOCKET_ERROR);
//zmq_assert (nbytes == sizeof (dummy));
#else
..........
}

**Comment by bluca** [comment]
Can you reproduce the problem without pyzmq, only with a minimal C test case?

**Comment by bluca** [comment]
And with libzmq from the master branch

**Comment by bluca** [comment]
Fixed by https://github.com/zeromq/libzmq/pull/2360
