### ISSUE TITLE
Compiling for windows universal app failed: Error	C3861 'CoCreateInstanceFromApp': identifier not found

### ISSUE THREAD

**Issue by yuanhuihe** [zeromq/libzmq#2309]
I have compiled the newest zmq 4.2.1 with cmake:

> cmake -H. -Bbuild -G"Visual Studio 14 2015 Win64" -DCMAKE_SYSTEM_NAME=WindowsStore -DCMAKE_SYSTEM_VERSION=10.0

And then open the 'ZeroMQ.sln' in 'build' folder, build it with debug/x64/libzmq(Universal Windows), it complains:

`Severity	Code	Description	Project	File	Line	Suppression State
Error	C3861	'CoCreateInstanceFromApp': identifier not found	libzmq	C:\Program Files (x86)\Windows Kits\10\Include\10.0.14393.0\um\combaseapi.h	1189	
`

Anyone faced this issue?

**Comment by bbdb68** [comment]
FYI I just managed to build an UWP version of the dll a load it from a Unity/UWP project. 
It is far to be PR ready but I will try to improve my hack.

basically you need to disasble security featreus (curve, tweetnacl)
I also defined WIN32_LEAN_AND_MEAN to get rid of COM stull.

then there is only a few hotsptos to fix.

I'll try to clean this an propose a PR

**Comment by bluca** [comment]
Thanks, but why do the security need to be disabled? Look forward to see the PR

**Comment by bbdb68** [comment]
for now this is the only way I found to get libzmq compile, I am discovering UWP...

**Comment by bluca** [comment]
Ah I understand. Thanks for working on this!

**Comment by bbdb68** [comment]
@bluca , how could I add a #define such as ZMQ_HAVE_WINDOWS_UWP so that I can isolate my changes ?

**Comment by bluca** [comment]
Does the uwp stuff have its own build system? If so you can simply define it in there and nowhere else

**Comment by bbdb68** [comment]
ok I have a first (very crude) version running on uwp, I was even able to perform a rep req from an uwp unity client using the uwp zeromq dll as a plugin  to a regular server. (I did not check if the bind can work but winsock is said to be available...)

you can check the changes here
https://github.com/bbdb68/libzmq/tree/uwp
I had to disable curve for some link issues, and look for ZMQ_HAVE_WINDOWS_UWP for finding the changes I had to do. This is far from being PR ready, any advice / tip welcome to re-enable the features I had to disable.

**Comment by hyhrepo** [comment]
Great job @bbdb68 !
You are right, some API about security is limited on UWP. You can find the same limit on WinCE. So I added a micro '_WIN32_UNIVERSAL_APP' and used it in some src files with '_WIN32_WCE'. Like this:

`#   if !defined _WIN32_WCE && !defined _WIN32_UNIVERSAL_APP
    //  Windows CE does not manage security attributes
    SECURITY_DESCRIPTOR sd;
    SECURITY_ATTRIBUTES sa;
    memset (&sd, 0, sizeof sd);
    memset (&sa, 0, sizeof sa);

    InitializeSecurityDescriptor (&sd, SECURITY_DESCRIPTOR_REVISION);
    SetSecurityDescriptorDacl (&sd, TRUE, 0, FALSE);

    sa.nLength = sizeof (SECURITY_ATTRIBUTES);
    sa.lpSecurityDescriptor = &sd;
#   endif
`

For errors of COM component, the default value of  ‘_WIN32_WINNT’ is '0x0600', but for WindowsStore and Windows Sytem Version 10.0, it must be or great then 0x0A00. so you must add '-DWINAPI_FAMILY=WINAPI_FAMILY_APP' in CMakeLists.txt:

```
  # WindowsStore
  if (CMAKE_SYSTEM_NAME MATCHES "WindowsStore")
	add_definitions (-D_WINDLL)
	add_definitions (-D_WIN32_UNIVERSAL_APP)
	#add_definitions (-D_WIN32_WINNT=0x0A00)
	add_definitions (-DWINAPI_FAMILY=WINAPI_FAMILY_APP)
  endif ()
```

The other thing is about crypt API, You can add the following code in CMakeLists.txt:

```
  # WindowsStore
  if (CMAKE_SYSTEM_NAME MATCHES "WindowsStore")
    target_link_libraries (libzmq Advapi32.lib)
  endif ()
```

And then, change 'CryptAcquireContext' to 'CryptAcquireContextA' in tweetnacl.c.

**Comment by bbdb68** [comment]
@hyhrepo thanks for the feedback, I'll try the tip for Advapi32.lib. 
BTW, do you have any suggestion about the if_nametoindex function ?

**Comment by hyhrepo** [comment]
I have deal with it like this:
```
#if !defined ZMQ_HAVE_WINDOWS_TARGET_XP && !defined _WIN32_UNIVERSAL_APP
            zone_id = if_nametoindex(if_str.c_str());
#else
            // The function 'if_nametoindex' is not supported on Windows XP.
            // If we are targeting XP using a vxxx_xp toolset then fail.
            // This is brutal as this code could be run on later windows clients
            // meaning the IPv6 zone_id cannot have an interface name.
            // This could be fixed with a runtime check.
            zone_id = 0;
#endif

```

means XP and UWP app can not use this function.

**Comment by hyhrepo** [comment]
Further study, I found that the Crypt API can not be used on UWP. And in CMakeLists.txt, there is an option:
`option (ENABLE_CURVE "Enable CURVE security" ON)`
This option can enable or disable the encryption functions in tweetnacl file. So, add the follow code block to CMakeLists.txt of zmq is better way to enable or disable crypt api:

```
option (WITH_LIBSODIUM "Use libsodium instead of built-in tweetnacl" OFF)
option (ENABLE_CURVE "Enable CURVE security" ON)

**# For WindowsStore, the Crypt API is unusable
if (CMAKE_SYSTEM_NAME MATCHES "WindowsStore")
option (ENABLE_CURVE "Enable CURVE security" OFF)
endif ()**
```

**Comment by martin---** [comment]
Thanks for porting zmq to uwp!

Intra-app communication works well. But the following scenario fails: A in-app publisher socket sends data to a out-app subscriber socket - the publisher socket binds, the subscriber socket connects. The scenario works well if we connect in-app and bind out-app.

Any ideas?

**Comment by bbdb68** [comment]
try to run your processes on two separates boxes. I found that IP
communication on the same box is not possible with UWP (even a "regular"
win32 process cannot communicate with an UWP one)

Hope this helps

Bruno

**Comment by martin---** [comment]
I get a new error, when working with the libzmq master branch:
`missing type specifier` in `netioapi.h` line 168 and 169.
I am using Visual Studio 2017

Martin

**Comment by bluca** [comment]
ZMQ_HAVE_WINDOWS_UWP was added, so closing this issue

**Comment by AntonioGMuriana** [comment]
> 
> 
> I get a new error, when working with the libzmq master branch:
> `missing type specifier` in `netioapi.h` line 168 and 169.
> I am using Visual Studio 2017
> 
> EDIT: Note this error only occurs with 10.0.15036.0 not with 10.0.14393.0
> 
> Martin

Still giving error compiling with modern SDK. Having to downgrade to 10.0.14393.0... any ideas to use newest ones ?

**Comment by AntonioGMuriana** [comment]
PR #3081 has added anothe if_nametoindex breaking compilation for UWP

**Comment by AntonioGMuriana** [comment]
I've tried this solution based on the idea from https://github.com/zeromq/libzmq/issues/2309#issuecomment-278521981 here:
https://github.com/AntonioGMuriana/libzmq/commit/fae0c5033211e2b4c467d9551de4360cfc581166

But not sure about side effects, since I don't know why this code is used.

**Comment by bluca** [comment]
It's probably better to set it to 0 rather than -1, reading around. Let's start with that to fix the immediate build issue, and then eventually follow-up.
