### ISSUE TITLE
Static linking libzmq with free-pascal/lazarus

### ISSUE THREAD

**Issue by cpicanco** [zeromq/libzmq#2320]
Hi. Have anyone ever tried to static link `libzmq` using free-pascal/lazarus? I would really appreciate any recommendations/documentation on static linking libzmq (in general). 

Best,
Rafael

**Comment by bluca** [comment]
Not sure about Pascal but static linking works like with any other library on *nix. Could you try and report back your findings?

**Comment by cpicanco** [comment]
Some background:

- I am not trying to define my own headers. I am using delphizmq, that supports FPC and libzmq v3.2.5 (https://github.com/bvarga/delphizmq).

- In Linux, I am guessing that I must link to the `*.a` library. Tha libzmq.a compiled by me has the following content:

``` bash
$/usr/local/lib$ ar -t libzmq.a
libzmq_la-address.o
libzmq_la-clock.o
libzmq_la-ctx.o
libzmq_la-decoder.o
libzmq_la-devpoll.o
libzmq_la-dist.o
libzmq_la-encoder.o
libzmq_la-epoll.o
libzmq_la-err.o
libzmq_la-fq.o
libzmq_la-io_object.o
libzmq_la-io_thread.o
libzmq_la-ip.o
libzmq_la-ipc_address.o
libzmq_la-ipc_connecter.o
libzmq_la-ipc_listener.o
libzmq_la-kqueue.o
libzmq_la-lb.o
libzmq_la-mailbox.o
libzmq_la-msg.o
libzmq_la-mtrie.o
libzmq_la-object.o
libzmq_la-options.o
libzmq_la-own.o
libzmq_la-pair.o
libzmq_la-pgm_receiver.o
libzmq_la-pgm_sender.o
libzmq_la-pgm_socket.o
libzmq_la-pipe.o
libzmq_la-poll.o
libzmq_la-poller_base.o
libzmq_la-pull.o
libzmq_la-push.o
libzmq_la-proxy.o
libzmq_la-reaper.o
libzmq_la-pub.o
libzmq_la-random.o
libzmq_la-rep.o
libzmq_la-req.o
libzmq_la-select.o
libzmq_la-session_base.o
libzmq_la-signaler.o
libzmq_la-socket_base.o
libzmq_la-stream_engine.o
libzmq_la-sub.o
libzmq_la-tcp.o
libzmq_la-tcp_address.o
libzmq_la-tcp_connecter.o
libzmq_la-tcp_listener.o
libzmq_la-thread.o
libzmq_la-trie.o
libzmq_la-xpub.o
libzmq_la-router.o
libzmq_la-dealer.o
libzmq_la-v1_decoder.o
libzmq_la-v1_encoder.o
libzmq_la-xsub.o
libzmq_la-zmq.o
libzmq_la-zmq_utils.o
```
- Linking to the dynamic library (.so) works just fine.

```
    const
      libzmq = 'libzmq.so';
     
    procedure zmq_version( var major, minor, patch: Integer ); cdecl; external libzmq;
```

- Linking to the static library (.a) the following way does not work.

```
    const
      libzmq = 'libzmq.a';
     
    procedure zmq_version( var major, minor, patch: Integer ); cdecl; external libzmq;     
```

Other things I tried with no success, all applied to the `delphizmq/zmq.pas` unit:

1) Use the compiler directives `{$L libzmq.a}` (reserved for object files).

2) Use the compiler directives `{$LINKLIB libzmq.a}` (reserved for static or dynamic libraries).

3) Use the compiler directive for all object files `{$L libzmq_la-zmq.o}`,  `{$L libzmq_la-zmq_utils.o}`,  and so on.

4) Compiler directive `{$L /mypath/libzmq.a}`

5) Compiler command `-Lo/mypath/` (with lazarus) and compiler directive `{$L libzmq.a}`

There is also a discussion running here:
http://forum.lazarus.freepascal.org/index.php?topic=35543.msg235206#msg235206

Considering the previous discussion, I should be able to link the `libzmq.a` somehow. For sure I am missing something here. However, I am not sure if it is during compilation of the libzmq.a or a sintax, configuration issue in the lazarus/fpc scope.

**Comment by bluca** [comment]
What do you mean by "does not work"?

Also if you are using a very old 3.x please try with the latest master.

Finally, remember that when static linking you need to add more dependencies explicitly. This is made easier by using pkg-config with --static:

```
$ pkg-config --cflags --libs libzmq
-lzmq 
$ pkg-config --cflags --libs --static libzmq
-lzmq -lstdc++ -lsodium -lpgm -lpthread -lm
```

The exact flags will depend on the build (so it might not need lpgm and/or lsodium)

**Comment by cpicanco** [comment]
Thank you @bluca ! I will try again!

Unfortunately, I did tried with libzmq 4.0.5 and, despite compiling, it fails with delphizmq and my current code base.

**Comment by cpicanco** [comment]
I think that I made it!

**on delphizmq**

1 - rename all 'external libzmq' to 'external';
2 - remove the 'const' section;
3 - add the following compiler directives before the `interface` section at `zmq.pas`:
```
{$LINKLIB stdc++}
{$LINKLIB gcc_s}
{$LINK /usr/local/lib/libzmq.a}   
```
libzmq
1) compile libzmq project with --static configuration

NOTE: I test the executable after unninstalling libzmq and running ldconfig. I NEED TO TEST THE EXECUTABLE ON DIFFERENT MACHINES THOUGH.

**Comment by bluca** [comment]
Great, happy you were able to sort it out, thanks for reporting back

**Comment by cpicanco** [comment]
There is a pull request here:

https://github.com/bvarga/delphizmq/pull/23

**Comment by cpicanco** [comment]
Ok, need to update this:

For linking libzmq on linux against the current master the following should work:
```pascal
{$IFDEF LINUX}
  {$LINKLIB m}
  {$LINKLIB stdc++}
  {$LINKLIB gcc_s}
  {$LINKLIB zmq.a}
{$ENDIF}  
```
However, static linking on windows will not work with static builds (vs 2017) of libzmq:
```pascal
// directive for libraries
{$IFDEF WINDOWS}
  {$LINKLIB libzmq.lib}
{$ENDIF}
// Error: Invalid DLL <libzmq.lib path>, Dos Header invalid.

{or}

// directive for object files
{$IFDEF WINDOWS}
  {$LINK libzmq.lib}
{$ENDIF}
// Error: Illegal COFF Magic while reading <libzmq.lib path>, 
```
Maybe there is some sort of configuration I am not aware of while building those static libraries or linking them or worse, there is no free pascal support to static linking this kind of static library. I need more information...

**Comment by bluca** [comment]
For Linux, using pkg-config is really the best way - otherwise if one of the optional dependencies is used to build, that hard-coded list will not be enough and it will not work.

```
pkg-config --cflags --libs --static libzmq
-lzmq -lstdc++ -lsodium -lpgm -lpthread -lm
```

For Windows I'm sorry but I don't really know, maybe somebody else can chip in.

**Comment by cpicanco** [comment]
I guess I have found the information I needed:

> ludob : 
> There are different library formats but the fpc linker only accepts the gnu format. On windows this means that static libraries produced by MS tools can not be used. Mingw or cygwin ports of the gnu binutils need to be used.
> http://forum.lazarus.freepascal.org/index.php/topic,15712.0.html

**Comment by bluca** [comment]
Ok, great. Can we close again then?

**Comment by cpicanco** [comment]
Let me try to build the static windows dll first. Would you recommend Mingw or cygwin? Why?????

**Comment by bluca** [comment]
Sorry, I can't really say, I don't use either.

**Comment by cpicanco** [comment]
Gosh save the stackoverflow!

https://stackoverflow.com/a/792142/1880535
