### ISSUE TITLE
clock_t crash on iOS 9.3.2 and 9.3.5

### ISSUE THREAD

**Issue by azawawi** [zeromq/libzmq#2323]
I am trying to figure why this bug "[Crash when creating a .subscriber socket](https://github.com/azawawi/SwiftyZeroMQ/issues/13)" is happening after upgrading pre-built binaries to the 4.2.1 branch. After reviewing [clock.cpp](https://github.com/zeromq/libzmq/blob/v4.2.1/src/clock.cpp#L156) code, I am suspecting that this [performance enhancement](https://github.com/zeromq/libzmq/commit/c5b528fdcd95dbfb914dc0c05bf7546e1d5cdc34) commit may be the culprit. The [workaround](https://github.com/zeromq/libzmq/blob/v4.2.1/src/clock.cpp#L156) may need to be applied there as well. Please advise.

**Comment by bluca** [comment]
Makes sense. Could you please send a pr to fix it?

**Comment by azawawi** [comment]
@bluca sure I will do that once I verify that it solves the problem. Thanks for your time.

**Comment by azawawi** [comment]
@bluca done. Thanks 👍
