### ISSUE TITLE
zmq send hangs forever if ZAP fails for the connection

### ISSUE THREAD

**Issue by mrvn** [zeromq/libzmq#2329]
I have a DEALER/ROUTER setup using CURVE encryption. The DEALER connects to the ROUTER and sends a single message. The ROUTER receives the ZAP requests and replies with status_code="300" to signal a temporary failure. A bit later the DEALER calls zmq_send() again to send a heartbeat and hangs. I believe it blocks waiting for the send queue to send a message so it can add the next one. And the queue is waiting for the connection to be established. But the DEALER socket never ever tries to reconnect.

**Comment by Asmod4n** [comment]
Hm, the last time i checked this the client sockets keeps on connecting forever until it is accepted, got this changed?

**Comment by evoskuil** [comment]
The previous behavior was that errors were not handled, resulting in the appearance of a secure connection when there was not. See: https://github.com/zeromq/libzmq/issues/2483

**Comment by evoskuil** [comment]
@Asmod4n You seem to be referring to the connection as opposed to the authentication. The DEALER (client) will continue to attempt a connection  to the (non-ZAP) ROUTER (server), but the connection is not secured - the messages are. After the connection is established sequential ordering is enforced by sockets (as applicable to the socket type). So the 300 response from the ZAP handler will prevent zmq from sending a response via the ROUTER back to the DEALER, which will hang the socket.

**Comment by evoskuil** [comment]
I'm looking at this again, as I think I hosed up part of it.

**Comment by evoskuil** [comment]
Prior to the change a failure in `zap_connect()` resulted in a `send_ready` state (same as a 200 response), now it fails `process_initiate()` -  the same result as a failure in `send_zap_request()` or a hard failure in `receive_and_process_zap_reply()`. A 300 response should result in a `send_error` state, as before:

https://github.com/zeromq/libzmq/pull/2482/commits/a0ccdc866efbac5889d8872c7f27c53e9c0a7c5b#diff-3bca2b2a10c02cfb01c7dbd2367d3d4c
