### ISSUE TITLE
vs2010 x64 crash

### ISSUE THREAD

**Issue by tigerssj** [zeromq/libzmq#2336]
I opened the proejct of zmqlib with vs2010 to compile and run, if the config of solution was win32, everything is ok, but crashed if the config is x64....who can help me?

**Comment by bluca** [comment]
what do you mean by crash? some logs (on gist/pastebin please) would be a good starting point

**Comment by tigerssj** [comment]
here is the screenshot.

**Comment by tigerssj** [comment]
![Uploading 1.png…]()
![Uploading 2.png…]()
![Uploading 3.png…]()
![Uploading 4.png…]()

![Uploading 6.png…]()
![Uploading 1.png…]()
![Uploading 2.png…]()
![Uploading 3.png…]()
![Uploading 4.png…]()
![Uploading 5.png…]()
![Uploading 6.png…]()

**Comment by tigerssj** [comment]
there was no log, just crash in vs2010.... i can not send the screenshots to github...
