### ISSUE TITLE
Setting ZMQ_SNDBUF/ZMQ_RCVBUF reduces performance (in unexpected way)?

### ISSUE THREAD

**Issue by rbx** [zeromq/libzmq#2338]
Following the recent compatibility-breaking change of the default value of ZMQ_SNDBUF/ZMQ_RCVBUF (from 0 to -1) I began experimenting with both flags, trying to find a setting that corresponds to my system defaults.

The below numbers are on Ubuntu 16.10 (4.8.0-37 kernel). I also tried on MacOS with similar results.

As a reference (values of ZMQ_SNDBUF/ZMQ_RCVBUF unchanged) I ran throughput benchmark:
```
$ ./local_thr tcp://127.0.0.1:5555 1000000 100000
message size: 1000000 [B]
message count: 100000
mean throughput: 7876 [msg/s]
mean throughput: 63008.000 [Mb/s]
```

My system buffer settings are the following:
```
$ cat /proc/sys/net/ipv4/tcp_wmem 
4096	16384	4194304
$ cat /proc/sys/net/core/wmem_default
212992
```

While trying to get same performance numbers as above, I then modified the bundled perf utilities and tried various settings for the ZMQ_SNDBUF (remote_thr) and ZMQ_RCVBUF (local_thr) as follows:

```C++
int size = 212992;
zmq_setsockopt(s, ZMQ_SNDBUF, &size, sizeof(int));
```

But in each case it always resulted in lower throughput:

with size of 212992:
```
$ ./local_thr tcp://127.0.0.1:5555 1000000 100000
message size: 1000000 [B]
message count: 100000
mean throughput: 5707 [msg/s]
mean throughput: 45656.000 [Mb/s]
```

with size of 106496 (according to SO_SNDBUF docs setsockopt doubles the given value):
```
$ ./local_thr tcp://127.0.0.1:5555 1000000 100000
message size: 1000000 [B]
message count: 100000
mean throughput: 5121 [msg/s]
mean throughput: 40968.000 [Mb/s]
```

with size of 4194304 (if it actually modifies tcp_wmem):
```
$ ./local_thr tcp://127.0.0.1:5555 1000000 100000
message size: 1000000 [B]
message count: 100000
mean throughput: 5682 [msg/s]
mean throughput: 45456.000 [Mb/s]
```

Each time the throughput is nowhere near the default unchanged setting.

What am I missing here? What does ZMQ_SNDBUF/ZMQ_RCVBUF actually set?

Thanks!

**Comment by bluca** [comment]
https://github.com/zeromq/libzmq/blob/master/doc/zmq_setsockopt.txt#L740
https://github.com/zeromq/libzmq/blob/master/doc/zmq_setsockopt.txt#L551

```
The 'ZMQ_RCVBUF' option shall set the underlying kernel receive buffer size for
the 'socket' to the specified size in bytes.  A value of -1 means leave the
OS default unchanged. For details refer to your operating system documentation
for the 'SO_RCVBUF' socket option.
```

Fiddling with the kernel buffer sizes is not recommended apart from special cases and circumstances - what problem are you trying to solve?

**Comment by rbx** [comment]
For now, only trying to understand what the default value of the "underlying kernel receive buffer size" actually is on my system. Since the values I try do not match the "default" behavior. I guess it is more complex than a single number.

My application has its own default value for this parameter that it gives to zmq, until now it was "0". For the new version I would need "-1". Trying to avoid the version check I was looking at how it affects the performance and if some specific value would also work as a default (e.g. 128 kB).
But now I think I will solve this by updating the zmq value only if my default was overridden.

**Comment by bluca** [comment]
Why do you need to pass a value if you are just using the default?

There's plenty literature on the kernel TCP buffers, you can manage them manually from the terminal with sysctl

**Comment by bluca** [comment]
EG: https://russ.garrett.co.uk/2009/01/01/linux-kernel-tuning/

```
$ sudo sysctl net.ipv4.tcp_wmem
net.ipv4.tcp_wmem = 4096	16384	4194304
$ sudo sysctl net.ipv4.tcp_rmem
net.ipv4.tcp_rmem = 4096	87380	6291456
$ sudo sysctl net.core.rmem_max 
net.core.rmem_max = 212992
$ sudo sysctl net.core.wmem_max 
net.core.wmem_max = 212992
```

**Comment by rbx** [comment]
Thanks for the link!

And yes, no need to update the values if the defaults are used.
