### ISSUE TITLE
router to one dealer will appear mutil connect, how to close the old connect?

### ISSUE THREAD

**Issue by bill68551632** [zeromq/libzmq#2342]
server router poll debian8 pyzmq14.7.0
client delear connect win7 pyzmq14.7.0

tcp 0 0 172.16.21.56:6905 192.168.33.54:63805 ESTABLISHED -
tcp 0 0 172.16.21.56:6905 192.168.33.54:49176 ESTABLISHED -

router server 6905, client delear have only one connect

tcp 0 0 172.16.21.56:6905 192.168.33.54:49176 ESTABLISHED -

to the router, I set ZMQ_ROUTER_HANDOVER to 1，
the router can respond to the new connect,  but  the old connect always exist.

the doc tell me , set ZMQ_ROUTER_HANDOVER to 1, will close the exist connect, used the new connect

how can I do?

**Comment by bluca** [comment]
Sorry I'm not sure I follow - what is the exact problem?

**Comment by bill68551632** [comment]
for example:
tcp 0 0 172.16.21.56:6905 192.168.33.54:63805 ESTABLISHED -
tcp 0 0 172.16.21.56:6905 192.168.33.54:49176 ESTABLISHED -

the two connections always  exist on the router side,   only one connection on the delear side.
if  reconnect,  the router side will have three connections.
the three connections will always exist.  
why  can not close  the old connection on the router side?  
if reconnect again,  will have more connections exist. 
do you understand?

**Comment by bill68551632** [comment]
always exist!  always exist!

**Comment by bluca** [comment]
The zmq connection is closed - the tcp connection eventually will too. The point of libzmq is to ignore these kind of details and let the library handle them. What is the problem you are trying to solve?

**Comment by bill68551632** [comment]
when execute,
socket.close(linger=0)
context.term()
all the connections  are just closed, I can ignore these connections
used the command "netstat -anp | grep 6905"， will see all connections，
include valid and invalid connections，I want to see the valid connections only.

**Comment by bluca** [comment]
The connections are handled asynchronously, so just because the code opens or closes a socket it does not mean it will be done immediately. Also the OS might not release immediately the port, depending on the platform and the settings.

But again, all of this is really not important, the point of zeromq is to abstract away all these platform-dependent low level details, and free the developers from caring about them.

Please read the zguide:

http://zguide.zeromq.org/

**Comment by bill68551632** [comment]
Thank you for your help!!!
