### ISSUE TITLE
Assertion failed: pfd.revents & POLLIN (src/signaler.cpp:239)

### ISSUE THREAD

**Issue by jivk** [zeromq/libzmq#2343]
Does anybody know what causes this assertion failure?  Although I can read code, I'm not a C++ or C programmer and am not able to debug the code to understand why this occurs.  It is a sporadic problem, difficult to replicate reliably.

**Comment by bluca** [comment]
On what platform?
Can you attach a minimal test case that reproduces the problem?

**Comment by jivk** [comment]
Hi, thanks for the response.  I am unable to produce a minimal test case as it's not obvious which condition is triggering this failed assertion.
It is happening in my unit tests (although I believe that issue may have also occurred in non unit test scenarios too).
I am running on Centos 7.2 VM on Virtual Box.

The difference between unit test and non unit-test execution of these code paths is the protocol.  IPC for former, EPGM/TCP for latter.  In both scenarios there are also inproc sockets involved.

**Comment by bluca** [comment]
Can you upload this unit test on gist/pastebin?

**Comment by jivk** [comment]
Difficult to do that - it's not a trivial unit test.  One of them is triggering the assertion failure almost every time now.  I've narrowed it down to when the Context is being closed.  I'm pretty sure it's a timing issue but don't really understand what is different about this Unit Test compared to one that is not failing.  They are both doing similar things with Sockets.

If I put a sleep before closing the Context it changes the failure pattern but not so significantly that I can circumvent the issue.  The only way I can avoid this assertion failure is to not close the context at all.

**Comment by bluca** [comment]
do you close all sockets before the context? also setting linger to 0?

**Comment by jivk** [comment]
Yes, I am doing all that - if I didn't the context close would hang.  I'll give you some more background and what I've found so far.

1.  I am testing the components in my software that provide and interaction between a Server and a Client.
2.  Server uses 3 sockets; PUB for Discovery, PUB for Data and ROUTER for synchronization.  Also Monitor Sockets for each one too.
3.  Client uses 3 sockets; SUB for Discovery, SUB for Data and DEALER for synchronrization. Also Monitor Sockets for each one too.
4.  The Client and Server logic are wrapped/encapsulated inside Protocols.  These Client and Server Protocols know how to interact with each other to establish a meaningful data stream.
5.  I have a Unit Test(s) for the Server Protocol and a Unit Test(s) for the Client Protocol
6.  Both Unit Tests share the same infra-code for cleaning up ZMQ
7.  Clean shut down of ZMQ is required at the end of each test case as otherwise the next test case cannot run reliably and often fails.
8.  In Unit Test scenarios the Protocols use IPC addresses.
9.  The Unit Test for Client Protocol runs smoothly, doesn't fail.  Each test case tears down the Context after use.
10.  The Unit Test for the Server Protocol is failing with this assertion.  Most of the time the first test case fails but sometimes a few will pass and then the next one will fail
11.  Each test case changes the address values so I can circumvent this issue by removing the close context call but that is **_highly undesirable_**.

Obviously I always want to close the context but there is something about the patterns of Socket use in Server Protocol that is falling foul of the assertion.

**Comment by bjovke** [comment]
@jivk Can you please create a minimal test case which reproduces this issue? It is not easy, if not impossible, to investigate the issue based on descriptions you gave.
If you create a test that will for sure speed up resolution.
