### ISSUE TITLE
EHOSTDOWN from getsockopt must not cause assertion abort; causes SaltStack crashes

### ISSUE THREAD

**Issue by MarkMartinec** [zeromq/libzmq#2351]
As requested by _bluca_  at the zeromq/zeromq4-1 repository
https://github.com/zeromq/zeromq4-1/issues/164

> Could you please send a pr to the libzmq repository? And then we can backport

so here is a copy of the PR:

With zeromq-4.1.5 from FreeBSD ports, as used by SaltStack.

For some time I have been observing instability of a running salt_minion on several of our FreeBSD hosts: after a couple of days Salt master loses contact with most FreeBSD hosts, but Linux hosts remain connected. After such event one can find a coredump of a salt-minion process (written in python) on such systems, and manually restarting a salt_minion is needed.

After adding some debugging, and capturing stdout and stderr of a non-daemonized salt-minion process, the following is the last reported line:

   Host is down (src/tcp_connecter.cpp:359)

So it seems there was some minor network glitch or outage, and libzmq decided to abort the process with an assertion, which is supposed to exempt all usual network socket -related problems and catch only a potential application problem.

The problem is that the exemption list is missing the EHOSTDOWN error code, which should not be a cause of a process abort.

The essential code snippet is shown here:

 /usr/ports/net/libzmq4/work/zeromq-4.1.5/src/tcp_connecter.cpp :

```
 zmq::fd_t zmq::tcp_connecter_t::connect ()
 {
     //  Async connect has finished. Check whether an error occurred
     int err = 0;
     socklen_t len = sizeof err;

     const int rc = getsockopt (s, SOL_SOCKET, SO_ERROR, (char*) &err, &len);

     //  Assert if the error was caused by 0MQ bug.
     //  Networking problems are OK. No need to assert.
 [...]
     //  Following code should handle both Berkeley-derived socket
     //  implementations and Solaris.
     if (rc == -1)
         err = errno;
     if (err != 0) {
         errno = err;
         errno_assert (
             errno == ECONNREFUSED ||
             errno == ECONNRESET ||
             errno == ETIMEDOUT ||
             errno == EHOSTUNREACH ||
   +         errno == EHOSTDOWN ||
             errno == ENETUNREACH ||
             errno == ENETDOWN ||
             errno == EINVAL);
         return retired_fd;
     }
```

So, please add the missing "errno == EHOSTDOWN ||" exemption to the errno_assert list.

Here is the patch:

```
--- src/tcp_connecter.cpp~      2016-06-17 13:38:14.000000000 +0200
+++ src/tcp_connecter.cpp       2017-02-23 17:38:25.616705000 +0100
@@ -355,4 +355,5 @@
             errno == ETIMEDOUT ||
             errno == EHOSTUNREACH ||
+            errno == EHOSTDOWN ||
             errno == ENETUNREACH ||
             errno == ENETDOWN ||

```

I don't know about the equivalent code section a couple of lines higher, pertaining to Windows. If a Windows system has an errno code WSAEHOSTDOWN known, it should be added there too.

Btw, the equivalent sister patch for the FreeBSD port net/libzmq4 is here:
https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=217313

**Comment by bluca** [comment]
Thanks, but I meant a pull request :-) Could you please implement this change and send a pull request to this repo?

**Comment by bluca** [comment]
Closing as tcp_connecter has been refactored and this problem no longer applies to 4.2+
