### ISSUE TITLE
Message corruption in subscriber when using OpenPGM

### ISSUE THREAD

**Issue by jivk** [zeromq/libzmq#2363]
Hi, we are experiencing an issue of message corruption in our ZMQ application.  We have a distributed application with many components communication via the OpenPGM protocol.  Following are the relevant version numbers

Name        : zeromq
Arch        : x86_64
Version     : 4.1.4
Release     : 5.el7

Name        : openpgm
Arch        : x86_64
Version     : 5.2.122
Release     : 2.el7

We have two components (let's call them P1 and P2) that publish data on different topics (let's say T1 and T2) but the same multicast address/port.  Both these publishers are C++ although I don't believe this is relevant to the problem, it is mentioned for completeness.  There are several subscriber applications displaying the same behaviour - all happen to be Java.  We have not seen this issue in a C++ subscriber but then we don't have a C++ subsriber that is receiving data from both P1 and P2.  Therefore we cannot assume that the issue is related to Java only but this maybe a possibility.

P1 and P2 run on different hosts, as do the subscribers.

Before carrying on, I want to point out that this issue does not occur if we publish the data on different multicast address/port.

The data on topics T1 and T2 are being published at a rate of approximately 100 messages per second
Each message on these topics is multipart - both are 3 frames per message.
We see message corruption in the form of incorrect frame counts.  So for example the subcsribers would frequently receive 2, 4 or even 5 frames per message.  We developed some validation code that performs a Hex dump of the message frames to log file when this corruption occurs.  Below is an example where 5 frames were received.

`Frame 1 [44, 45, 56, 32, 45, 78, 65, 63, 75, 74, 69, 6f, 6e, 52, 65, 70, 6f, 72, 74, 53, 54, 52, 45, 41, 4d, 50, 72, 69, 6d, 61, 72, 79, 35, 32, 30, 31, 37, 36, 61, 33, 2d, 31, 32, 32, 35, 2d, 34, 30, 30, 35, 2d, 62, 37, 66, 39, 2d, 34, 66, 62, 65, 39, 33, 36, 36, 35, 65, 38, 35]`
`Frame 2 [8, 37, 10, b1, e1, d6, cd, 99, ca, d2, 2]`
`Frame 3 [44, 45, 56, 32, 4c, 32, 55, 70, 64, 61, 74, 65, 53, 54, 52, 45, 41, 4d, 50, 72, 69, 6d, 61, 72, 79, 66, 65, 38, 32, 62, 30, 36, 30, 2d, 64, 66, 37, 62, 2d, 34, 30, 32, 37, 2d, 38, 31, 31, 64, 2d, 35, 35, 66, 31, 35, 37, 34, 38, 30, 38, 30, 61]`
`Frame 4 [8, 1e, 10, 89, b9, e5, cd, 99, ca, d2, 2]`
`Frame 5 [12, 3b, 8, 1, 15, 18, 30, 1e, 0, 19, b1, ab, b5, 99, 51, 4a, 5, 0, 21, e4, 39, c, 99, 0, 0, 0, 0, 28, 2, 31, 40, 42, f, 0, 0, 0, 0, 0, 39, e4, da, 1, 0, 0, 0, 0, 18, 45, 20, 3, 0, 0, 49, 3c, 47, 3b, 99, 51, 4a, 5, 0]`

The interesting Frames are 1 and 3 - when we decoded them they turned out to be the Topics T1 and T2.  This implies that the ZMQ subscription receiving code is not corectly assembling message frames back together.  I always thought that ZMQ was actually concatenating the frames of a multipart message before sending a single sequence of bytes.  In which case it's difficult to see how this corruption could occur other than be due to a concurrency bug - which in itself is also difficult to justify as the subscribing components use a single ZMQ Context with an I/O threadcount of 1.

For completeness, here is the code that we use for reading from the ZMQ.SUB socket.

    protected void read(final ZMQ.Socket socket, final List<byte[]> frames) {
        byte[] bytes;
        do {
            bytes = socket.recv();
            if (bytes != null) {
                frames.add(bytes);
            }
        } while (socket.hasReceiveMore() && bytes != null);
    }

The list referenced by frames is empty on call to this method.  The subscribing applications are using two distinct ZMQ SUB sockets for each of the two data streams.

**Comment by bluca** [comment]
>We have not seen this issue in a C++ subscriber but then we don't have a C++ subsriber that is receiving data from both P1 and P2. Therefore we cannot assume that the issue is related to Java only but this maybe a possibility.

Any chance you could perform this test?
If it's not reproducible with libzmq then it means it's a problem in the Jave binding (which one and which version are you using, btw?)

**Comment by jivk** [comment]
Hi, thanks for the response.  I am unable to perform the C++ test in the short term but we will look into attempting a reproduction.  Do you already have a sample/example that does effectively the same thing?

The Java binding we are using is 3.1.1-SNAPSHOT `f8318463700f69c76e20b57a027acce08f673976`

Could you confirm that publishing ZeroMQ messages via N different sockets (either in the same process, across N processes on the same machine or on N different hosts) on the same multicast address/port should be received correctly by any process that is subscribing to all these messages.  Seems a basic use case and reason for using multicast.

**Comment by bluca** [comment]
Sorry don't think I have an example, but should be pretty simple to put together. Also I'm not quite familiar with PGM, just trying to do basic triage to point you in the right direction.

**Comment by jivk** [comment]
Hi Luca, what would you suggest if we 

1. Could not reproduce in C++
2. Could reproduce in C++

Either way I would still like confirmation that the use case is or is not supported.

**Comment by jivk** [comment]
Hi ZMQ Team, could you please advise.

Cheers
Jivraj

**Comment by bluca** [comment]
Hi, sorry again but I'm not that familiar with PGM, so without diving into the modules I'm not sure if the use case is supported.

That said, in case the problem is reproducible only with the Java binding/implementation, that would strongly suggest that it is supposed to work and there's a problem in that binding, and I could point you to the relevant repository to try and proceed to identify the issue.

If instead it can be reproduced with only libzmq, then either the use case is not supported or there's a bug in libzmq and we have to fix it. In this case I would recommend writing to the mailing list and mention PGM in the subject. Hopefully then someone more familiar with that protocol can help us.
