### ISSUE TITLE
Problem: format of ZMQ_STREAM message

### ISSUE THREAD

**Issue by itoolset** [zeromq/libzmq#2366]
I am working on a zmq client (ZMQ_STREAM socket type) with a non-zmq server.
I should parsing the message form the client by my self, so is there any documents about the format of ZMQ_STREAM message? and how about the message framing?

thx a lot.

**Comment by bluca** [comment]
Have you checked the manpage?

https://github.com/zeromq/libzmq/blob/master/doc/zmq_socket.txt#L385

**Comment by itoolset** [comment]
@bluca 
yes I have, but it without any help.

**Comment by bluca** [comment]
https://github.com/zeromq/libzmq/blob/master/tests/test_stream.cpp
http://grokbase.com/t/zeromq/zeromq-dev/136v5qh3d7/new-zmq-stream-socket-type
http://stackoverflow.com/questions/17176871/can-zeromq-be-used-to-accept-traditional-socket-requests

**Comment by bluca** [comment]
No reply so assuming those links had enough information available, closing
