### ISSUE TITLE
test_sodium fails: libsodium sets errno even if it doesn't fail

### ISSUE THREAD

**Issue by mrvn** [zeromq/libzmq#2370]
In test_sodium zmq_curve_keypair() is called and then zmq_errno() is checked. This works fine with the built-in tweetnacl but can fail with libsodium. What happens is this:

    ...
    access("/dev/arandom", R_OK)            = -1 ENOENT (No such file or directory)
    access("/dev/urandom", R_OK)            = 0
    open("/dev/urandom", O_RDONLY)          = 3
    ...
    test_sodium: tests/test_sodium.cpp:43: void test__zmq_curve_keypair__always__success(): Assertion `zmq_errno () == 0' failed.

libsodium does not reset the errno to 0 so it remains ENOENT even though everything works just fine.

What that means is that errno is meaningless unless the return code actually indicates an error and should not be checked in the testcase.

**Comment by bluca** [comment]
Perhaps then zmq_curve_keypair should return the return value of crypto_box_keypair and then the errno check can be removed. Could you please send a PR to fix it?

**Comment by mrvn** [comment]
It already checks the return value:

    assert (rc == 0);
    assert (zmq_errno () == 0);

It's just the second assert that fails.

**Comment by bluca** [comment]
I mean inside the zmq_curve_keypair function itself - if you check, it just always return 0, so assert (rc == 0) can never catch any error

**Comment by mrvn** [comment]
That makes more sense. let me try.

**Comment by bluca** [comment]
Thanks!

**Comment by bluca** [comment]
Fixed by https://github.com/zeromq/libzmq/pull/2372
