### ISSUE TITLE
Problem:  doesn't reconnect on windows with wsapoll

### ISSUE THREAD

**Issue by xkkd** [zeromq/libzmq#2443]
I must start local_thr.exe first ,then start remote_thr.exe

**Comment by evoskuil** [comment]
Hi @xkkd, This sounds like it may be related to an issue I'm having on Windows (though I'm not sure it's only Windows). Could you provide more detail and/or take a look at issue I linked above? Thanks!

**Comment by xkkd** [comment]
WSApoll will not capture events that fail to connect asynchronously, and will always block it, even with POLLIN | POLLOUT

**Comment by evoskuil** [comment]
My issue was unrelated, just improper configuration.
