### ISSUE TITLE
Problem: __STDC_LIMIT_MACROS define precedes PCH include.

### ISSUE THREAD

**Issue by evoskuil** [zeromq/libzmq#2452]
Visual Studio 2013 warning:
```
.\..\..\..\src\zmq_utils.cpp(30): warning C4603: '__STDC_LIMIT_MACROS' : macro is not defined or definition is different after precompiled header use
          Add macro to precompiled header instead of defining here
          ..\..\..\..\src\zmq_utils.cpp(32) : use of precompiled header
```

It's not clear to me whether this inclusion should be strictly limited to `zmq_utils.cpp` and as such I'm hesitant to move it to the precompiled header (PCH). But the PCH should be the first source in the file. Moving this define after the PCH may have unintended consequences as well, since it affects the behavior of includes of the PCH.

**Comment by bluca** [comment]
https://github.com/zeromq/libzmq/commit/c6c21cf1971ba6e0be2fba9ea7637b0b80403d70
> * Define __STDC_LIMIT_MACROS before including stdint.h

Given the commit message, and if I remember correctly, that fixed an issue with stdint.h, so it might be safe to move after the PCH. Want to give it a try?

**Comment by evoskuil** [comment]
The PCH includes `<stdint.h>`, as well as other STD C files, for Windows (I'd really like to remove the Windows condition in the PCH. So the Windows builds would be affected. But it compiles on VS2013 at least.

**Comment by bluca** [comment]
Fixed by https://github.com/zeromq/libzmq/pull/2454
