### ISSUE TITLE
Problem: VC++ warnings from <poll.h> includes prior to PCH.

### ISSUE THREAD

**Issue by evoskuil** [zeromq/libzmq#2453]
In `signaler.cpp` and `proxy.cpp` this conditional define occurs before the precompiled header (PCH) include:
```cpp
#if defined ZMQ_POLL_BASED_ON_POLL && defined ZMQ_HAVE_AIX
#include <poll.h>
#endif
```
The following warnings are emitted by Visual Studio 2013 in each case:
```
..\..\..\..\src\proxy.cpp(37): warning C4627: '#include <poll.h>': skipped when looking for precompiled header use
          Add directive to 'precompiled.hpp' or rebuild precompiled header
```
```
..\..\..\..\src\signaler.cpp(37): warning C4627: '#include <poll.h>': skipped when looking for precompiled header use
          Add directive to 'precompiled.hpp' or rebuild precompiled header
```
Given the comment:
```
//  On AIX platform, poll.h has to be included first to get consistent
//  definition of pollfd structure (AIX uses 'reqevents' and 'retnevents'
//  instead of 'events' and 'revents' and defines macros to map from POSIX-y
//  names to AIX-specific names).
//  zmq.h must be included *after* poll.h for AIX to build properly.
//  precompiled.hpp includes include/zmq.h
```
...it appears that the proper resolution would be to move the conditional includes into the PCH, along with this code from `signaler.cpp`:
```cpp
#if defined ZMQ_POLL_BASED_ON_POLL
#if !defined ZMQ_HAVE_WINDOWS && !defined ZMQ_HAVE_AIX
#include <poll.h>
#endif
#elif defined ZMQ_POLL_BASED_ON_SELECT
#if defined ZMQ_HAVE_WINDOWS
#elif defined ZMQ_HAVE_HPUX
#include <sys/param.h>
#include <sys/types.h>
#include <sys/time.h>
#elif defined ZMQ_HAVE_OPENVMS
#include <sys/types.h>
#include <sys/time.h>
#else
#include <sys/select.h>
#endif
#endif
```
but I'm not aware if there is an adverse impact to including these more broadly. I'm aware that the includes will have no affect on VC++ (assuming proper platform defines) but we should still clean up the warnings. And it would be a simplification to centralize these conditions.

**Comment by bluca** [comment]
This was causing build failures on AIX and was quite a pain to solve, I think we need someone with access to AIX that can confirm changes in this regards do not introduce regressions I'm afraid
