### ISSUE TITLE
Using ZMQ for bidirectional inter-thread communication

### ISSUE THREAD

**Issue by bakarydiarra** [zeromq/libzmq#2480]
Hi,

I am new to zeromq. I have spent the last couple of month reading the documentation and experimenting with the library. I am currently developing a multi-threaded c++ application and want to use ZMQ instead of mutexes to exchnage data between my main thread and one of its child.

The child thread is handling the communication with an external application. Therefore, I will need to queue/sockets between the main thread and its child. One for outgoing messages and one for incoming messages.

Which zmq socket should I use, in order to achieve this.

Thanks in advance

**Comment by bluca** [comment]
ZMQ_PAIR with inproc transport, check the zmq_socket doc page

**Comment by bakarydiarra** [comment]
@bluca thanks for your answer. After checking the documentation for the pair socket, I found the following:
**Summary of ZMQ_PAIR characteristics**
**Compatible peer sockets**	ZMQ_PAIR
**Direction**	Bidirectional
**Send/receive pattern**	Unrestricted

This is exactly what I was looking for. 

Thanks again

**Comment by bluca** [comment]
No problem. Closing since it's solved.

**Comment by ElectricRCAircraftGuy** [comment]
For anyone needing the documentation page, see `ZMQ_PAIR` on this page here: http://api.zeromq.org/2-1:zmq-socket
