### ISSUE TITLE
Problem: invalid security configuration in heartbeats test case.

### ISSUE THREAD

**Issue by evoskuil** [zeromq/libzmq#2483]
The heartbeats test includes an invalid security configuration that has only been succeeding because of the lack of error handling that is fixed in [this PR](https://github.com/zeromq/libzmq/pull/2482) (so it's now failing).

There is no [ZAP handler](https://github.com/zeromq/libzmq/blob/master/tests/test_security_curve.cpp#L91-L138) implemented in the heartbeats test, which is easily confirmed by searching for the `inproc://zeromq.zap.01` [binding](https://github.com/zeromq/libzmq/blob/master/tests/test_security_curve.cpp#L162). As such there is no way that authentication can succeed.

**Unfortunately anyone who has followed this test case as an example may have entirely unsecured connections that are believed to be secure.**

It's a great example of the argument for never suppressing an unhandled error result.

**Comment by evoskuil** [comment]
Resolved in https://github.com/zeromq/libzmq/pull/2482/commits/fbe3841b5f95195222951a6bb145ef0576fdfb8f by removing the curve configuration.

**Comment by bluca** [comment]
Thanks for catching this!
Fixed by #2482
