### ISSUE TITLE
cmake and windows

### ISSUE THREAD

**Issue by diorcety** [zeromq/libzmq#2505]
There is a bug with cmake and library on Windows if you do a OUTPUT_NAME with the same name that the target the output will have liblib. in this case liblibzmq.dll.a and liblibzmq.dll .
Changing the libzmq target by libzmq-shared (as libzmq-static) will solve the issue.
(tested on msys2)

**Comment by bluca** [comment]
could you please send a PR to fix it?

**Comment by bluca** [comment]
Fixed by https://github.com/zeromq/libzmq/pull/2527
