### ISSUE TITLE
Problem: setting ZMQ_RCVHWM after connect causes polling issues when queue is full

### ISSUE THREAD

**Issue by saifhhasan** [zeromq/libzmq#2509]
When I set ZMQ_RCVHWM after connect (which according to docs says should work) is causing trouble to polling.

In my setup, I am polling on SUB socket and reading one message out of it at a time. If I set ZMQ_RCVHWM after connect and I get sudden burst of updates which fills up the queue on client side (guessing HWM is not applied and defaults to 1000). After this I never receive `ZMQ_POLLIN` even on this sub socket anymore even though sender is pushing more data. `netstat -nat` shows that recv buffer on client and send buffer on server connection is full and `tcpdump` shows no packet activity between server and client. (this happens with ipc and inproc socket modes as well).

However surprisingly things workout well when I set HWM before connect which is weird. client loses some messages because it's recv queue is full (but POLLIN is working as per expectation)

**Comment by evoskuil** [comment]
Hi @saifhhasan, I think you are misinterpreting the documentation.:

> Caution: All options, with the exception of ZMQ_SUBSCRIBE, ZMQ_UNSUBSCRIBE and ZMQ_LINGER, only take effect for subsequent socket bind/connects.

http://api.zeromq.org/3-0:zmq-setsockopt

**Comment by saifhhasan** [comment]
Hello @evoskuil ... libzmq-4.2 has exceptions for more socket types
http://api.zeromq.org/4-2:zmq-setsockopt

Even though lets say setting hwm after connect is ineffective for currently connected socket, it shouldn't stop responding to `poll` even though there are events pending in the queue to be read.

**Comment by saifhhasan** [comment]
Following code consistently re-produce this issue. Moving setsockopt of ZMQ_RCVHWM before connect fixes it. I am using zmq-4.2.1 and according to docs it support setting ZMQ_RCVHWM after connect.

Also note that this happens for other transport types as well (tcp, ipc as well as inproc)

```
#include <chrono>
#include <thread>

#include <fbzmq/async/ZmqEventLoop.h>
#include <fbzmq/zmq/Zmq.h>
#include <folly/init/Init.h>


fbzmq::Context context;
const std::string url{"tcp://[::1]:60090"};
const int hwm = 500;
const int bufLen = 1024;

void runServer() noexcept {
  fbzmq::Socket<ZMQ_PUB, fbzmq::ZMQ_SERVER> server(context);
  server.setSockOpt(ZMQ_SNDHWM, &hwm, sizeof(int)).value();
  server.bind(fbzmq::SocketUrl{url}).value();

  int j = 0;
  while (j < 5) {
    ++j;
    for (int i = 0; i < 1e4; ++i) {
      server.sendOne(
          fbzmq::Message::from(std::string(bufLen, 'a')).value()).value();
    }
    LOG(INFO) << "Server: sent " << 1e4 << " messages.";
    std::this_thread::sleep_for(std::chrono::milliseconds(500));
  }
}

void runClient() noexcept {
  fbzmq::Socket<ZMQ_SUB, fbzmq::ZMQ_CLIENT> client(context);
  const int rcvHwm = 0;
  client.connect(fbzmq::SocketUrl{url}).value();
  client.setSockOpt(ZMQ_SUBSCRIBE, "", 0).value();
  client.setSockOpt(ZMQ_RCVHWM, &rcvHwm, sizeof(int)).value();

  int64_t rcvd = 0;
  fbzmq::ZmqEventLoop evl;
  evl.addSocket(fbzmq::RawZmqSocketPtr{*client}, ZMQ_POLLIN, [&](int) mutable {
    ++rcvd;
    auto maybeMsg = client.recvOne(std::chrono::milliseconds(1000));
    if (maybeMsg.hasError()) {
      LOG(ERROR) << "Failed to received message. " << maybeMsg.error();
    }
    CHECK_EQ(bufLen, maybeMsg.value().size());
    if (rcvd % hwm == 0) {
      LOG(INFO) << "Client: received " << hwm << " messages.";
      std::this_thread::sleep_for(std::chrono::milliseconds(200));
    }
  });

  evl.run();
}

int main(int argc, char** argv) {
  folly::init(&argc, &argv);

  std::thread serverThread([] {
    runServer();
  });

  std::thread clientThread([] {
    runClient();
  });

  serverThread.join();
  clientThread.join();

  return 0;
}
```

**Comment by bjovke** [comment]
@saifhhasan Can you please create example showing `ZMQ_RCVHWM `issue which does not require building `fbzmq` and it's dependencies. It should be possible to build it with `libzmq` only. In that way you will achieve two things:

- You will have more people willing to test the issue and work on it.
- It will eliminate any possibility that the issue is related to something other than `libzmq`.

Greetings.

**Comment by teterycz** [comment]
@saifhhasan were you able to determine the cause of the SUB socket not receiving a ZMQ_POLLIN? I'm on libzmq 4.2.3 and have experienced sporadic hangs where I don't get notified of data on SUB socket. Signaling the process seems to bring it back to life...until the next hang.
