### ISSUE TITLE
Using existing socket

### ISSUE THREAD

**Issue by maandree** [zeromq/libzmq#2530]
Hi!

I want to create a socket(7) manually, use let zmq_bind(3) use that socket instead of creating it's own socket, because I want to create the socket from another process, kind of like inetd(8). How do I do this?

Thank you!

**Comment by somdoron** [comment]
I think it is possible with ZMQ_USE_FD, check the followings:

https://github.com/zeromq/libzmq/blob/dce4d06b71ba77ebd4f0818412a1f5f868a059b3/doc/zmq_setsockopt.txt#L499

https://github.com/zeromq/libzmq/blob/3683a96fcbf25c4bc04ac4b002a1b1550db99767/tests/test_use_fd_tcp.cpp

https://github.com/zeromq/libzmq/blob/3683a96fcbf25c4bc04ac4b002a1b1550db99767/tests/test_use_fd_ipc.cpp

**Comment by bluca** [comment]
Yep that's the purpose of that option.

If you are trying to integrate with systemd's socket activation, then I suggest using CZMQ, where setting a environment variable (or a flag in the code) will make the library automatically fetch the file descriptor from systemd based on the endpoint:

https://github.com/zeromq/czmq/blob/master/include/zsys.h#L330

eg, if you bind to 192.168.0.1 and systemd has a file descriptor already for that address, it will automatically use it

Closing now given the answer is there, please reopen if you have any issues

**Comment by maandree** [comment]
@somdoron Thanks for your help!
