### ISSUE TITLE
CMake options to control build output (static vs. dynamic)

### ISSUE THREAD

**Issue by RPGillespie6** [zeromq/libzmq#2535]
We are building ZeroMQ in our process, but we really only need `libzmq.so` and not the static archive. Can we add an option to control the build output? For example, something like:

`-DBUILD_STATIC=OFF`

It just seems like a waste that we spend 10-15 seconds per build on something we are not going to use.

**Comment by bluca** [comment]
Feel free to send a PR to implement it

**Comment by bluca** [comment]
Fixed by https://github.com/zeromq/libzmq/pull/2536
