### ISSUE TITLE
ZMQ_HAVE_POLLER and ZMQ_BUILD_DRAFT_API

### ISSUE THREAD

**Issue by juan-filewave** [zeromq/libzmq#2540]
In zmq.h ZMQ_HAVE_POLLER is defined iff ZMQ_BUILD_DRAFT_API is defined. But in zmq_draft.h ZMQ_HAVE_POLLER is defined following the inverse logic, ie, iff ZMQ_BUILD_DRAFT_API is _not_ defined.
For my usage in Windows, I'm interested into not having ZMQ_HAVE_POLLER defined and use poll (WSAPoll in windows.hpp), but I can't unless I modify the code, and I'm not sure to understand if ZMQ_HAVE_POLLER should be defined iff ZMQ_BUILD_DRAFT_API is defined, of the other way around.

**Comment by bluca** [comment]
poll will be used, but through the new zmq_poller code

**Comment by bluca** [comment]
I have now realised what you mean, and it's absolutely true the new poller is used whether the users wants it or not - will send a PR to fix it shortly as it should be optional until it's finalised
