### ISSUE TITLE
GSSAPI only allows host-based principals to be explicitly selected

### ISSUE THREAD

**Issue by garlick** [zeromq/libzmq#2542]
Principals specified with ZMQ_GSSAPI_PRINCIPAL (client and server), as well as ZMQ_GSSAPI_SERVICE_PRINCIPAL (client) are looked up with the GSS_C_NT_HOSTBASED_SERVICE name type.

As described in  https://web.mit.edu/kerberos/krb5-1.13/doc/appdev/gssapi.html, this means principals must be specified as "service" or "service@host", and are internally canonicalized (at least in MIT krb5) to principals named "service/host" in the local realm, with host set to the local hostname if unspecified.

This means that a principal that is not tied to a host (for example an "application principal") cannot be used with zeromq, unless it is the default credential on the client side (used when the client does not set ZMQ_GSSAPI_PRINCIPAL).  Maybe there is a good reason not to allow that, and in fact @fichtner may be asserting this in
> commit 8c09ae6e49b29a731dc4f0b123101baecdace113
> Author: Franco Fichtner <franco@lastsummer.de>
> Date:   Mon May 5 21:59:11 2014 +0200
> 
>    gssapi: RFC 2744 mandates GSS_C_NT_HOSTBASED_SERVICE
>   
>   Tested on FreeBSD 10.

(I can't seem to find the passage he is referring to in [RFC 2744](https://tools.ietf.org/html/rfc2744))

It would seem like a useful thing to allow principals to be optionally looked up with the GSS_C_NT_USER_NAME name type.  I'm not sure of the right way to do this though.

Option 1:  add two new socket options (true by default for backwards compat), e.g. 
* ZMQ_GSSAPI_PRINCIPAL_NT_HOST_BASED
* ZMQ_GSSAPI_SERVICE_PRINCIPAL_NT_HOST_BASED

Option 2:  special prefix character for princpals, e.g. if `@` is the first character, strip it off and look up the name with GSS_C_NT_USER_NAME

**Comment by bluca** [comment]
New options are easier to document imho
