### ISSUE TITLE
ASCIIDOC_EXECUTABLE used even if not found

### ISSUE THREAD

**Issue by diorcety** [zeromq/libzmq#2552]
if not ASCIIDOC_FOUND then WITH_DOC is forced to false
but the command using ASCIIDOC_EXECUTABLE is still defined. 
it should be conditionnal to WITH_DOC

cf https://github.com/diorcety/libzmq/commit/fcf992a7e73850d9cc9aa4ca782385cb8cf7ef43

**Comment by bluca** [comment]
can you send a PR to fix it?
