### ISSUE TITLE
Rework CMake package and library generation 

### ISSUE THREAD

**Issue by herbrechtsmeier** [zeromq/libzmq#2556]
The current CMake package don't work with CMake version below 3.0 because the `export()` function isn't available. The CMake version should be increased or the package generation should be disable for CMake versions below 3.0.

Rename the exported targets to `zmq-shared` and `zmq-static`. Add an alias target `zmq` which depends on the value of the common `BUILD_SHARED_LIBS` variable. This allows other project to automatically select the correct library or manual select one of the two libraries. Additionally the project should only use the zmq alias.

Replace the `BUILD_SHARED` and `BUILD_STATIC` options by the common  `BUILD_SHARED_LIBS`  option and a private `BUILD_STATIC_LIBS` option. Thereby the shared library is build only if the `BUILD_SHARED_LIBS` option is on and the static library is build if the `BUILD_SHARED_LIBS` option is off or the `BUILD_STATIC_LIBS` is on. If possible the `BUILD_STATIC_LIBS` options should be off by default to allow the user to select the library type with a common variable.

Prepend all exported target by the namespace `ZeroMQ::`.

Rework the CMake tests project to a stand-alone project. This allows Travis to build the tests against the CMake ZeroMQ package.

**Comment by bluca** [comment]
Please do send PRs to fix those issues. But also please do not break backward compatibility for users since the last stable release.

**Comment by herbrechtsmeier** [comment]
I will send PRs but before we need to agree on the exported CMake targets because they need to be fixed. Is `ZeroMQ::zmq*` okay or should it be `ZeroMQ::ZeroMQ*` or ?`ZeroMQ::libzmq*`?

@bluca Does this means that the CMake package should support targets only if the CMake version is high enough and the project build both libraries by default?

**Comment by bluca** [comment]
I think that would be reasonable, yes.

**Comment by bluca** [comment]
@stefanherbrechtsmeier @JohanMabille @RPGillespie6 @diorcety @bbdb68  @SylvainCorlay @Kentzo @kurdybacha @hnwyllmm @Bitiquinho 
You all have sent CMake changes in the past few months, so hearing your opinion/preferences would be appreciated. Thanks!

**Comment by herbrechtsmeier** [comment]
I found a solution for the `export(export)` problem which allows the usage of targets with CMake Version 2.8.12. After we agree on the target names I will adapt the CMake code and send PRs.

**Comment by JohanMabille** [comment]
@herbrechtsmeier Thanks for tackling this!

>Rework the CMake tests project to a stand-alone project. This allows Travis to build the tests against the CMake ZeroMQ package.

I really like this idea, that's what Debian developpers (and I guess developpers of other distributions) do and it has proven to work great!

About the naming distrinction between static and shared libraries, do you plan to do it on all platforms ? Or only for Windows ? I think that is not required on Linux / OsX where shared and static libraries can be distinguished by their name extension, however that would be better to have the same naming convention everywhere.

About the name of the package, I think we should keep `libzmq`; that would avoid to break scripts that rely on that name and I think people are used to this name now.

I don't understand what you mean by "Prepend all exported target by the namespace ZeroMQ::". I guess you're talking about cmake namespace, but that's not something I'm familiar with. What are the benefits and what does it imply for projects depending on libzmq ?

**Comment by herbrechtsmeier** [comment]
> About the naming distrinction between static and shared libraries, do you plan to do it on all platforms ? Or only for Windows ? I think that is not required on Linux / OsX where shared and static libraries can be distinguished by their name extension, however that would be better to have the same naming convention everywhere.

I don’t speak about the libraries but about the CMake targets and they are always distinguishing.

> About the name of the package, I think we should keep libzmq; that would avoid to break scripts that rely on that name and I think people are used to this name now.

The CMake package is named ` ZeroMQ ` since the last release. Which scripts do you mean?

> I don't understand what you mean by "Prepend all exported target by the namespace ZeroMQ::". I guess you're talking about cmake namespace, but that's not something I'm familiar with. What are the benefits and what does it imply for projects depending on libzmq

I always speak about CMake. Namespaces allows a separation between real targets and alias or imported targets. Additionally they are commonly used in FindXXX files. The namespace means that other projects need to use the target `ZeroMQ::zmq` instead of `zmq`.

Since the last release libzmq supports `find_package(ZeroMQ)` with the three variables `ZeroMQ_INCLUDE_DIR`, `ZeroMQ_LIBRARY` and `ZeroMQ_STATIC_LIBRARY`. In the next release the package should offer a shared target (`zmq-shared`), a static target (`zmq-static`) and an alias target (`zmq`) for the shared and if not available static target. This allows user to simple add ZeroMQ by add the following lines:

```
find_package(ZeroMQ REQUIRED)

add_executable(a a.c)
target_link_libraries(a ZeroMQ::zmq)

```

The namespace should be match the package name. The target name must be defined before the next release.

**Comment by kurdybacha** [comment]
@herbrechtsmeier good stuff.

I believe @JohanMabille is talking about target outputs when referring to `libzmq`.

+1 for common options `BUILD_SHARED_LIBS` and `BUILD_STATIC_LIBS`

I am not that experience with namespaces but example looks nice.

I am using ZeroMQ as cmake ExternalProject currently so happy to test your changes on that setup.

**Comment by JohanMabille** [comment]
Indeed I was talking about the name of the output libraries, sorry for the mistake.
@herbrechtsmeier thanks for your explanations.
