### ISSUE TITLE
MinGW compiling error (4.2.1)

### ISSUE THREAD

**Issue by scifinder** [zeromq/libzmq#2563]
**Problem:** When compiling in MinGW, as written here: http://zeromq.org/build:mingw, an error occurs: 'SOCKADDR_INERT does not name a type' etc.
**Solution:** Add
#include <ws2tcpip.h>
#include <winsock2.h>
#include <winsock.h>
in windows.hpp (str num ~56)

**Comment by bluca** [comment]
ws2tcpip.h and winsock2.h are already there, only winsock.h is missing. Could you please send a PR to add it?

**Comment by bjovke** [comment]
Including winsock.h would be useless since winsock2.h prevents including winsock.h:

winsock2.h:
`#define _WINSOCKAPI_   /* Prevent inclusion of winsock.h in windows.h */`

winsock.h:
```
#ifndef _WINSOCKAPI_
#define _WINSOCKAPI_
...
#endif
```
I'm not sure what is symbol `SOCKADDR_INERT` , can you post all of the errors you get?

**Comment by bjovke** [comment]
Also, including winsock.h before winsock2.h is forbidden and it won't compile anyway.

**Comment by bluca** [comment]
We've got other PRs are reports that mingw is working fine, so closing
