### ISSUE TITLE
one crash in windows server 2008

### ISSUE THREAD

**Issue by gebogebo** [zeromq/libzmq#2569]
developing a 32-bit server plugin dll project which runs on windows server 2008 64bit
i tried zmq function with connect, send, close.  It causes the server down every time.
So, I focused on the code, if I ignore the line send_plug (object_) in own.cpp, it will not lead the sever down.
But I don't know if it works well if without this line.

is there probably a bug for socket thread management in zmq?  I also notice "LIBZMQ_UNUSED (priority_)"  in the code.  anyway, I want that helps fix.

**Comment by bluca** [comment]
what version? are you using the same socket from multiple threads? can you upload the code and the backtrace to gist/pastebin?

**Comment by gebogebo** [comment]
well, i don't have the server code. so i compile zmq with static lib in my dll project. the version is the latest. in my code with developing zmq, there are only sever lines, i only use connect function now.  
But with a new server version, it works well.   We still have to develop the plugin with the older server version. 

	ctx = zmq_init(1);
	if (!ctx) {
		return;
	}

	s = zmq_socket(ctx, ZMQ_PUB);
	if (!s) {
		return;
	}

	rc = zmq_connect(s, "tcp://127.0.0.1:8002");
	if (rc != 0) {
		return;
	}

**Comment by bluca** [comment]
have you increased the stack size as the documentation recommends? can you paste the backtrace?

**Comment by gebogebo** [comment]
code:
	ctx = zmq_init(1);
	if (!ctx) {
		return(TRUE);
	}
	LogsOut("ppppppp6");

	s = zmq_socket(ctx, ZMQ_PUB);
	if (!s) {
		LogsOut(string("error in zmq_socket:" + string(zmq_strerror(errno))).c_str());
		return(TRUE);
	}
	LogsOut("ppppppp7");

	rc = zmq_connect(s, "tcp://127.0.0.1:8002");
	if (rc != 0) {
		LogsOut(string("error in zmq_connect:" + string(zmq_strerror(errno))).c_str());
		return(TRUE);
	}
	LogsOut("ppppppp8");

log:
ppppppp6
ppppppp7
ppppppp8

after print ppppppp6 for several seconds, the server restart.
if I ignore the "send_plugin", the server will not restart.

it works well in newer server version, it is windows server 2012 64bit and server is also 64bit.
the problem happens under older server version, it is windows server 2008 64bit and server is 32bit.

**Comment by gebogebo** [comment]
well ,so sorry , i currently don't know where to increase the stack size and how to use backtrace? i am gonna try.

**Comment by bluca** [comment]
https://github.com/zeromq/libzmq/blob/master/INSTALL#L49

it's visual studio specific, so it will be somewhere in the visual studio documentation

**Comment by gebogebo** [comment]
do u mean the dummy_size? sorry, i really don't know where to change the config.

**Comment by bluca** [comment]
Sorry I'm not that familiar with visual studio, perhaps @bjovke can help with the right settings to set the stack size

**Comment by gebogebo** [comment]
can u help me forward the question? i set dummy_size, it doesn't work. so ,i guess i did a wrong config.

**Comment by bluca** [comment]
have you checked https://msdn.microsoft.com/en-us/library/tdkhxaks(v=vs.90).aspx ?

**Comment by gebogebo** [comment]
thanks, i just found and trying. if ok, i will let you know

**Comment by gebogebo** [comment]
well, sorry, it doesn't work, still crash :(

**Comment by bluca** [comment]
have you done that in both the library build and your project build? what did you set the size to?

**Comment by gebogebo** [comment]
i both tried, it's /F 2097152

**Comment by bluca** [comment]
Try 4 MB with /STACK as well

**Comment by gebogebo** [comment]
thanks anyway, i will try next day. do u mean "/STACK 4MB" or “/STACK 4194304”

**Comment by bluca** [comment]
From the doc it looks like it takes values in bytes

**Comment by bjovke** [comment]
If you're building from IDE then go to Project->Properties->Linker->System->Stack Reserve Size. The value is in bytes.
This is equivalent to setting linker option /STACK:<bytes>

**Comment by bjovke** [comment]
@gebogebo  _"so i compile zmq with static lib in my dll project."_
Please take extreme care not to mix modules using static runtime libraries with ones using dynamic runtime libraries. This always causes horrible crashes.
What is "send_plugin" you are mentioning?

**Comment by gebogebo** [comment]
well, thanks. my vs solution has two projects. one is the libzmq in release lib, the other is a dll project which is used for the server plugin. i ever tried several times for setting the stack size, but it will still cause the server program crash and restart. 
the "send_plugin" is the line in function "zmq::own_t::launch_child (own_t *object_)" in own.cpp.  if I comment out this line with "//", it will not cause the server down. But I guess it's not good.

**Comment by gebogebo** [comment]
I don't know how the server runs and I use the libzmq lib mode for trying to find out reason, I will try to use the dll mode, but i guess it still doesn't work.

**Comment by bjovke** [comment]
@gebogebo Which runtime libraries are set for libzmq and which for your dll project? These are /MT, /MTd, /MD, /MDd copmiler options.

**Comment by gebogebo** [comment]
I ever tried /MT, /MTD and /MD。  /MDd is not recognized for the server.

**Comment by bjovke** [comment]
Small letter "d" stands for "debug" version and capital "D" for "dynamic. libzmq AND your DLL project must have the same option set.

**Comment by gebogebo** [comment]
yes, if not, it will not link succeed.

**Comment by bjovke** [comment]
@gebogebo If you have a DLL project which uses libzmq, what is this DLL used for? Is it being used by another piece of software?

**Comment by gebogebo** [comment]
yes, exactly, it is the plugin of a server program, which is the another piece of software. and i don't have its code.   with a newer version, there is no problem with zmq.  with the older version, the same code and the simple connect function, it doesn't work well with zmq.

**Comment by gebogebo** [comment]
i use libzmq lib mode for trying to find out reason. i also tried dll mode for many times, using the same runtime libraray, but it doesn't work. if no better way, i will try more times, maybe i did something wrong while compling.

**Comment by bjovke** [comment]
@gebogebo That's exactly what I wanted to know. So your module and libzmq are packed into one DLL which is then used by another executable program, if I understood correctly?
That program which is using the DLL is compiled with static or dynamic runtime libraries. You have to match this in your DLL so it uses the same runtime library type as the server.
Also, you need to compile your DLL **with the same compiler** that compiled server program.

**Comment by gebogebo** [comment]
ok, i understand.  what i want to say again is that the server has two versions. the newer version is ok with my dll project when using zmq, the older one is not. I want to find a way to make the older one work also well.

**Comment by bjovke** [comment]
@gebogebo What is the error when server crashes? Did you notice some exception or notification in popup window? Is there any entry for this in Event log which has more information?

**Comment by bjovke** [comment]
@gebogebo You need to find first with which compiler older server version was compiled. Then you need to use **the same** compiler for your DLL. And you need to find if older server version uses static or dynamic runtime libraries and use the same ones in your DLL.

**Comment by gebogebo** [comment]
@bjovke  thanks. you explain very clearly and know what i am doing.  normally, my dll project runs under the server program, and my dll will use libzmq dll, put the libzmq dll under system32.   what i mentioned the lib mode before was the special way for me trying to find out what cause the server program crash. in this way, don't need the libzmq dll, because it is compiled and packed into my dll.

**Comment by gebogebo** [comment]
@bjovke thanks a lot again. i will try to figure out the compiler. maybe it is too new for the old server, while i am using vs2017.  no popup window, after doing the connect function for several seconds, the sever restarted automatically. and the server don't leave any message.

**Comment by bjovke** [comment]
@gebogebo As a starting point, you need to determine two things:

- Compiler used to build server program.
- Which runtime library server program is using (static/dynamic).

Let's start from there because there's no point in going any further if we don't know these settings.

**Comment by bjovke** [comment]
@gebogebo If you're using VS2017 and your server is old, there's a great chance that it was compiles with VS2015 or earlier one. If you have "Process explorer" and your server is using dynamic runtime libraries, find the server process and list it's loaded DLLs in the lower pane.
Try to find **MSVCPxxx.DLL**. If it is there then it's compiled with Microsoft compiler and "xxx" will tell you the compiler version. 140 is VS2015, 110 is VS2012, I'm not sure abut the others but it can be found easily. Then you need to use the appropriate Visual studio for your plugin.

**Comment by gebogebo** [comment]
@bjovke ok, i will try. thanks.

**Comment by bjovke** [comment]
@gebogebo _"it works well in newer server version, it is windows server 2012 64bit and server is also 64bit.
the problem happens under older server version, it is windows server 2008 64bit and server is 32bit."_

It might be that you only need to install [Microsoft Visual C++ Redistributable for Visual Studio 2017](https://go.microsoft.com/fwlink/?LinkId=746572) on Windows server 2008 because this maybe exists on Windows server 2012 but not in Windows server 2008.

**Comment by bjovke** [comment]
@gebogebo Actually I was wrong about redistributable package. Programs don't even start if required redistributable DLL is not available.

**Comment by gebogebo** [comment]
@bjovke yes, i ever installed redist 2017, it didn't work.  Just now, I tried the older version 2010 because i found v100.dll in system32 and all the other plugin were developed with 2010. But the bad thing is it still didn't work. it happened the same thing. :(

**Comment by gebogebo** [comment]
i found some longs on the server, it tells the crash caused by libzmq


      crash : #010 00000AB0 EIP: 5C8E9B99 ESP: 0219F814 
              5C8E9B99:000000 [5C8E9B99] unknown (libzmq.dll)
              5C8BC945:000000 [5C8BC945] unknown (libzmq.dll)
              5C8BBA7E:000000 [5C8BBA7E] unknown (libzmq.dll)
              5C8BEC60:01073E [5C8CF39E] zmq_has (libzmq.dll)
              5C8BEC60:02354D [5C8E21AD] zmq_has (libzmq.dll)
              5C7DF690:000104 [5C7DF794] _crt_at_quick_exit (ucrtbase.dll)
              758B3378:000012 [758B338A] AcquireSRWLockExclusive (kernel32.dll)
              77BF9F0F:000063 [77BF9F72] RtlInsertElementGenericTableAvl (ntdll.dll)
              77BF9F0F:000036 [77BF9F45] RtlInsertElementGenericTableAvl (ntdll.dll)

   crash -->  5C8E9B99 8500              test       [eax], eax
              5C8E9B9B EBE7              jmp        0x5c8e9b84

              5C8E9B9D CC                int3       
              5C8E9BA0 56                push       esi
              5C8E9BA1 8B442414          mov        eax, [esp+0x14]

**Comment by bjovke** [comment]
@gebogebo Sorry for the late reply, I have limited access to Internet these days.
I'm kind of confused now.
_"I tried the older version 2010 because i found v100.dll in system32 and all the other plugin were developed with 2010"_ 
So was the server compiled with VS 2010? Did you compile your project AND libzmq with VS 2010 then?
It's still not clear to me if server is using static or dynamic runtime?

**Comment by gebogebo** [comment]
@bjovke yes, i compile libzmq and my project with 2010, server is using dynamic runtime. everything is ok, except adding a function of libzmq. now, i write another dll project for using libzmq, and the dll project of the server plugin will call it, now there is no crash, but the server will leave the log of clean up my plugin and restart. So, problem still exist.  i just don't understand why there is no problem with the newer server.

**Comment by gebogebo** [comment]
The following the Requirements for Plugins,  will it helps? I think my project meets them.
When developing plugins, it is necessary to meet the following requirements:

•Since the plugin is running in the server address space, it:
•should be as efficient in memory usage as possible;
•should fragment memory as little as possible;
•should not cause memory leaks.
•A plugin is no case should generate unhandled exceptions.
•A plugin must quickly return control from event handlers and hooks.
It is recommended to develop plugins using Microsoft Visual C++. Disable the "Exception handling" option in the project settings (in the 'Project\Settings' menu the 'C/C++' tab, the 'C++ Language' category), because the server completely intercepts error handling and adds them to the crash log. It is also recommended to add version information as a resource.

It is also recommended to specify the _CRT_SECURO_NO_WARNINGS macro in the compiler directives (the Preprocessor section).

**Comment by bjovke** [comment]
@gebogebo Hm, it could be that stack is overflown. Can you find out the stack size for old and new server?

**Comment by gebogebo** [comment]
@bjovke thanks for your answer. I ever increased stack size of my dll project, libzmq.  sorry, i can't find out the stack size for server.

**Comment by gebogebo** [comment]
@bjovke I think the following may have some help.
my dll project import libzmq, and define context_t and socket_t. then i debug the dll with an exe project. there is an error for exitting the exe program with the following message:"WSASTARTUP not yet performed (..\..\..\..\src\signaler.cpp:191)"
That's exactly the same as i comment out "send_plugin". 
I guess I can do this so far, i may use the zmq as a second choice for the older sever plugin project.

**Comment by bjovke** [comment]
@gebogebo WSAStartup() should have been called during context creation (`zmq_ctx_new()`). It must have executed with error or not executed at all. Since there's this code:
```
    int rc = WSAStartup (version_requested, &wsa_data);
    zmq_assert (rc == 0);
```
It would have asserted on error in `WSAStartup()`, so it must have been that you never called `zmq_ctx_new()`.
Can you check that in your code?

**Comment by bjovke** [comment]
@gebogebo Any news about this issue?

**Comment by gebogebo** [comment]
thanks。 in the older server version, we change another way.

**Comment by bjovke** [comment]
@gebogebo So have you managed to make it work?

**Comment by gebogebo** [comment]
thanks. since it can work with the newer server version, different version, different windows editiion, even different platform target, so i don't want to continue fixing the problem. by the way, i use boost library in the newer server version, it work well with a timer definition and initilization in the constructor function. but it will hold on and block if i do so. so in the older server version, i only use boost timer in the function as a local variable , it works. i don't know why either.   since i don't have the code of server, maybe i can't give more information. just close it for some time.
