### ISSUE TITLE
Skip the receiving line of code instead of having to wait until a message is received

### ISSUE THREAD

**Issue by Davar1990** [zeromq/libzmq#2573]
Hi,

I have two publishers and two subscribers to establish two independent communication processes. My publishers keep broadcasting messages and both of my independent subscribers are running **ON THE SAME THREAD** in serial with different subscriptions and sockets. One of the publishers sends messages every 100 ms and the other sends messages every 10 ms. My problem is, since both of my subscribers are on the same thread, the subscriber which receives messages later, doesn't allow the faster subscriber to run independently because the program doesn't continue until the first subscriber has received its message. ( For your information, I don't want to run them on separate thread to avoid this issue, they should be on the same thread).

while(true) {

       s_recv(socket1);     
       s_recv(socket2);     

}

I don't want socket2 to wait for socket1 until it receives the message. I tried the following

while(true) {
    try{
         s_recv(socket1);     
    }
    catch(...){
         s_recv(socket2);     
    }
}

but since socket1 doesn't throw any errors I can't skip that line. I would very much appreciate it if you could help me with this problem.

Thanks,
Davar

**Comment by bluca** [comment]
Have you tried with polling? http://api.zeromq.org/4-2:zmq-poll

**Comment by Davar1990** [comment]
Thank you so much for the quick reply and your fantastic library. My problem got fixed.

**Comment by Davar1990** [comment]
In case someone else runs into a similar problem please refer to the following code;


#include <iostream>
#include <thread>
#include <zhelpers.hpp>

using std::endl;
using std::cout;

zmq::context_t context(1);

void get() {
	
	zmq::socket_t sub(context, ZMQ_SUB);
	sub.connect("tcp://localhost:6000");
	sub.setsockopt(ZMQ_SUBSCRIBE, "cam", 3);

	zmq::socket_t client(context, ZMQ_SUB);
	client.connect("tcp://localhost:8000");
	client.setsockopt(ZMQ_SUBSCRIBE, "mac", 3);

	zmq::pollitem_t items[] = {
		{ sub, 0, ZMQ_POLLIN, 0 },
		{ client, 0, ZMQ_POLLIN, 0 }
	};

	while (true) {

		//zmq::poll(&items[0], 2, -1);
		zmq::poll(items, 2, -1);

		if (items[0].revents & ZMQ_POLLIN) {
			s_recv(sub);
			cout << "sub  " << s_recv(sub) << endl;
		}

		if (items[1].revents & ZMQ_POLLIN) {
			s_recv(client);
			cout << "client " << s_recv(client) << endl;

		}
	}
}

void snd() {

	zmq::socket_t publ(context, ZMQ_PUB);
	publ.bind("tcp://*:8000");
	
	while (true) {
		s_sendmore(publ, "mac");
		s_send(publ, "yoursssssssssssssssssssssssssssssssssssssssssssss");
	}
}

int main()
{
	zmq::socket_t publisher(context, ZMQ_PUB);
	publisher.bind("tcp://*:6000");

	std::thread t2(snd);
	std::thread t1(get);

	while (true) {	
		Sleep(100);
		s_sendmore(publisher, "cam");
		s_send(publisher, "mine");
	}
}

**Comment by bluca** [comment]
Thanks for confirming, closing since it's solved
