### ISSUE TITLE
Brew installation instructions

### ISSUE THREAD

**Issue by atav32** [zeromq/libzmq#2576]
Could you guys update the website with the Brew installation instructions instead of the Makefile instructions? 

I think they're outdated anyways. I had a ton of trouble running `autogen.sh`. I followed the instructions to configure `pkg-config` to no avail. Eventually, it worked after I read the errors and Brew installed Automake. Still don't understand why though.

Then I saw this https://github.com/zeromq/libzmq/issues/1835#issuecomment-210423049 😭

**Comment by bluca** [comment]
Which webpage do you have in mind precisely? If you link it I'll update it

**Comment by atav32** [comment]
Awesome, thanks! http://zeromq.org/docs:source-git

**Comment by bluca** [comment]
That page refers to getting the git source repository, I've instead added it to the main download page: http://zeromq.org/intro:get-the-software

**Comment by atav32** [comment]
Sweet, thanks!
