### ISSUE TITLE
Compilation issue on Windows with ninja

### ISSUE THREAD

**Issue by diorcety** [zeromq/libzmq#2579]
On windows with ninja the precompiled.hpp can't be found. Put precompiled.cpp first doesn't solve the issue, a better dependency tree must be done.

Cf https://github.com/diorcety/libzmq/commit/66b94c78e8087538d5acbd3d62069d0b31a12bd4

**Comment by bluca** [comment]
I don't think we support ninja?

**Comment by bluca** [comment]
But it's windows stuff so I'm not really sure

**Comment by diorcety** [comment]
Ninja is not only for windows. But in this case, the issue appear because ninja doesn't process source in the given order. My fix force a dependency which force at the end the order

**Comment by bjovke** [comment]
@diorcety What is ninja?

**Comment by diorcety** [comment]
https://ninja-build.org/

**Comment by bluca** [comment]
As I mentioned there's no support for it and afaik you're the first to ask, so if you are interested please do send PRs to add support for it

**Comment by bjovke** [comment]
@diorcety Thanks. I don't think building with ninja is supported for libzmq.

**Comment by diorcety** [comment]
Okay this is the only fix to do for supporting ninja :)

**Comment by bluca** [comment]
Could you please send a PR for it?

**Comment by bluca** [comment]
Fixed by https://github.com/zeromq/libzmq/pull/2580
