### ISSUE TITLE
Java HelloWorld Client Server not working

### ISSUE THREAD

**Issue by R-Lath** [zeromq/libzmq#2589]
Hi,
I am new to ZeroMQ so thought to start with Hello World Client Server program.
Hello World Server program I used: http://zguide.zeromq.org/java:hwserver
Hello World Client program I used: http://zguide.zeromq.org/java:hwclient
I am running both client and server on same windows machine and not getting any compilation errors. At runtime my server program is crashing at code "byte[] request = responder.recv(0)". Error message is 
"Java(TM) Platform SE binary has stopped working"
![javaerror](https://cloud.githubusercontent.com/assets/29110879/26661568/df527c10-46c1-11e7-9ce5-06560abfa504.JPG)

Version of Java I am using is : jre1.8.0_131
OS: Windows7 64-bit
ZeroMQ : ZeroMQ 4.0.4

I tried Java weather update server-client program as well, but no luck.

Please help.

**Comment by bluca** [comment]
Hi, this repository is for the C/C++ library, please open an issue on https://github.com/zeromq/jzmq to ask for help from the Java experts
