### ISSUE TITLE
coredump with option immediate and linger setted

### ISSUE THREAD

**Issue by laplaceyang** [zeromq/libzmq#2590]
I set immediate = 1 and linger = 100, then my application always coredump in timer_event

![qq 20170601103417](https://cloud.githubusercontent.com/assets/7036040/26662376/0b957342-46b6-11e7-858e-6f2b54443cb3.png)

It seems the reconnect function of session_base implement incorrect.
![image](https://cloud.githubusercontent.com/assets/7036040/26662391/2715aa6a-46b6-11e7-9bfe-93db17031be4.png)
In first block of this function, we set pipe to NULL, but has not cancel_timer. Thus, if the linger timer tiggered , we will get coredump.

**Comment by bluca** [comment]
Could you please send a PR to fix it?

**Comment by laplaceyang** [comment]
@bluca 
done.   PR is here [https://github.com/zeromq/libzmq/pull/2591](https://github.com/zeromq/libzmq/pull/2591)

**Comment by bjovke** [comment]
Merged.

**Comment by bluca** [comment]
Thanks!
