### ISSUE TITLE
dish client does not resend subscriptions to radio server

### ISSUE THREAD

**Issue by ilovexyz** [zeromq/libzmq#2592]
Hi all
recently i am using zmq radio/dish pattern for distributing messages, and i found that, if the radio process restarts, the dish will not resend subscriptions to radio. And the result is that the dish will never receive any more messages. is this a bug?

PS: 
after debugging my code, i found that if  add a bit code to session_base.cpp, the problem disappears, please help confirm.

what i changes:
add `options.type == ZMQ_DISH` for hiccup situations

```
void zmq::session_base_t::reconnect ()
{
......
//  For subscriber sockets we hiccup the inbound pipe, which will cause
    //  the socket object to resend all the subscriptions.
    if (pipe && (options.type == ZMQ_SUB || options.type == ZMQ_XSUB  || options.type == ZMQ_DISH))
        pipe->hiccup ();
}
```

**Comment by bluca** [comment]
Seems reasonable. @somdoron what do you think?

**Comment by somdoron** [comment]
Seems good.

**Comment by bluca** [comment]
@ilovexyz could you send a pull request please?

**Comment by ilovexyz** [comment]
ok, i'll make a pull request

**Comment by bluca** [comment]
Thanks!

Fixed by https://github.com/zeromq/libzmq/pull/2593
