### ISSUE TITLE
Problem: CurveZMQ connection fails without ZAP

### ISSUE THREAD

**Issue by cxreg** [zeromq/libzmq#2594]
In commit a0ccdc866efbac5889d8872c7f27c53e9c0a7c5b from #2482 the logic of `curve_server.cpp` was changed so that `zmq::curve_server_t::process_initiate` returns -1 if `zap_connect` fails.  Previously, this was allowed and the ZAP logic was only processed if that returned 0.  Was this deliberate?  Is ZAP mandatory now?

**Comment by bluca** [comment]
I don't it could be securely used at all without ZAP, and it was just an oversight as mentioned in the PR.

@evoskuil @somdoron do you confirm?

**Comment by somdoron** [comment]
I actually not sure, nees to dig into that

**Comment by cxreg** [comment]
Well, it's definitely not documented as mandatory (in fact the CurveZMQ docs make no reference to ZAP at all), and it worked previously.  If this breaking change is deliberate it should be stated very explicitly.

Peoples networks  and requirements vary substantially and authentication is not required in every circumstance where encryption is warranted.  I would rather not have it mandated, but if that is to be the case please make sure it is done clearly and deliberately.

**Comment by bluca** [comment]
So after a quick look, I _think_ that @evoskuil change makes sense with the PLAIN mechanism, as without ZAP there's no check at all. Username and password are parsed and then thrown out.

But with CURVE some people might want just encryption, without any authentication. They might be interested in just avoiding eavesdropping, perfect forward secrecy etc, but don't care that any client can connect from anybody can connect.

I think this is your use case, @cxreg ? I believe this is a valid use case, right?

(No actual idea about GSSAPI btw)

**Comment by jemc** [comment]
@bluca Yes, I think there's definitely a use case for CURVE encryption without ZAP authentication.

Though I could see @evoskuil's point that if you were expecting ZAP, and it was failing to find ZAP silently, you'd never know it until you tried to connect from a bogus client and it worked.

Perhaps we need a socket option to declare whether you expect to use ZAP or not, then fail hard if you expect ZAP and it isn't found?

**Comment by cxreg** [comment]
That's correct @bluca, I have found it to be a valid use case.  Having a declared intent to use ZAP makes sense and would avoid the ambiguity around the error return.

To maintain legacy functionality maybe something like

```
     if (rc == 0) {
￼         rc = send_zap_request (client_key);
￼         if (rc != 0)
￼             return -1;
￼         rc = receive_and_process_zap_reply ();
￼         if (rc == 0)
￼             state = status_code == "200"
￼                 ? send_ready
￼                 : send_error;
￼         else
￼         if (errno == EAGAIN)
￼             state = expect_zap_reply;
￼         else
￼             return -1;
￼     }
     else if (zap_required) {
￼         return -1;
     }
￼
```

**Comment by bluca** [comment]
Perhaps the intention of using ZAP could be the fact that the socket exists? After all it's an inproc socket with a fixed endpoint, it's either there or not, I can hardly see scope for serious race conditions.

In that case only the search for the endpoint would return -1, and all other error could assert.
IE: if the socket is there it must be of the right type and it must be writable.

https://github.com/zeromq/libzmq/blob/master/src/session_base.cpp#L318

This way we avoid adding yet another socket option while maintaining backward compatibility.

**Comment by jemc** [comment]
Sounds fine to me if @evoskuil also feels that it still fulfills his original intent.

**Comment by evoskuil** [comment]
I'm on a safari at the moment, so not much ability to review details. But ZAP is not required for curve (privacy), ZAP is only used to authenticate. However if ZAP connect is attempted it imples that it is required and as such the failure must propagate. Presumably ZAP connect should not be called if authentication is not required.

The solution of requiring successful ZAP connect in the case where the ZAP endpoint is found and succeeding in the case where the endpoint is not found would resolve the curve issue without the need for additional config. However if one is running ZAP for non-curve auth purposes (e.g. plain) at the same time as non-auth curve (privacy), there may be complications (not sure).

**Comment by cxreg** [comment]
> The solution of requiring successful ZAP connect in the case where the ZAP endpoint is found and succeeding in the case where the endpoint is not found would resolve the curve issue without the need for additional config. However if one is running ZAP for non-curve auth purposes (e.g. plain) at the same time as non-auth curve (privacy), there may be complications (not sure).

In 4.2.2 this is already the case, as a succesful connect to the ZAP endpoint is processed as mandatory success, so at least that wouldn't be a regression

**Comment by jemc** [comment]
> However if one is running ZAP for non-curve auth purposes (e.g. plain) at the same time as non-auth curve (privacy), there may be complications (not sure).

If you had the need to do that, the recommendation would probably be to use two different *contexts*, since the `inproc` socket used by ZAP is local to a single context.

**Comment by bluca** [comment]
I'll prepare a PR in a little while

**Comment by evoskuil** [comment]
My understanding (from memory) is that the ZAP endpoint is global to a process, not a context.

**Comment by bluca** [comment]
It's an inproc socket, and those are local to a context:

https://github.com/zeromq/libzmq/blob/master/src/session_base.cpp#L322

**Comment by bluca** [comment]
@garlick GSSAPI question - should the fact that ZAP is not set up by the user be considered a hard failure?

https://github.com/zeromq/libzmq/blob/master/src/gssapi_server.cpp#L123

For context - in the CURVE case we might want encryption without authentication, but in the PLAIN case there's no point if the plaintext parameters are not checked, so it doesn't make sense to allow continuing without ZAP

**Comment by garlick** [comment]
As I recall, ZAP can be used to refuse clients, but to even get that far with GSSAPI, the two sides already have to mutually authenticate through the kerberos key exchange.  So ZAP is filling more of an authorization role here.  I guess no ZAP could mean "allow all" instead of "deny all" like it is now and that would be OK.

It does sound scary to do that - one would need to be sure that the "gate isn't left open" if ZAP is failing in some unexpected way, as opposed to not being set up on purpose.  (Sorry if that's already been covered)

**Comment by bluca** [comment]
Yes I'll push some very small changes to harden it a bit - but the idea is, if ZAP is enabled then it must work, but if it's not enabled for CURVE (and GSSAPI too now I guess) then proceed.
