### ISSUE TITLE
Is there any way to keep a pointer from being freed when closing a message?

### ISSUE THREAD

**Issue by preparedice** [zeromq/libzmq#2595]
For example:

```
void * data;
{
zmq::message_t msg;
socket->recv(&msg);
data = msg.data();
}
```

Is there any way to maintain access to ```void * data``` when ```msg``` falls out of scope?
When ```msg``` falls out of scope, ```free``` is automatically called on ```msg.data()```. Is there any way of closing the ```msg``` while preserving the data maintained at ```msg.data()```? Ideally, I'd like to be able to keep the data within the message without manually allocating space for a ```message_t``` or memcpy'ing ```msg.data()``` into my own buffer.

**Comment by bluca** [comment]
That's part of the cpp  bindings, not of libzmq. Libzmq exports a C API where you can keep a message around for as long as you like.

Please open an issue at https://github.com/zeromq/cppzmq

**Comment by bluca** [comment]
In general though, once the message is closed the memory is deallocated, that's how it works.
So if you can't use C API, you'll simply have to keep around a reference to the message. That's how it's generally done with the libzmq APIs.

**Comment by preparedice** [comment]
Ah, it was a limitation of the cppzmq binding. Thanks for your help!
