### ISSUE TITLE
Problem: cmake does not build and install manpages

### ISSUE THREAD

**Issue by Vaelatern** [zeromq/libzmq#2597]
On release tag 4.2.2, building on Linux, I can't complete a build in CMake due to a lack of `ZeroMQConfig.cmake.in`

Build log snippet follows:
```
-- Checking whether TIPC is supported
CMake Error: File /builddir/zeromq-4.2.2/ZeroMQConfig.cmake.in does not exist.
CMake Error at /usr/share/cmake-3.8/Modules/CMakePackageConfigHelpers.cmake:312 (configure_file):
  configure_file Problem configuring file
Call Stack (most recent call first):
  CMakeLists.txt:920 (configure_package_config_file)


-- Configuring incomplete, errors occurred!
See also "/builddir/zeromq-4.2.2/build/CMakeFiles/CMakeOutput.log".
See also "/builddir/zeromq-4.2.2/build/CMakeFiles/CMakeError.log".
```

**Comment by bluca** [comment]
There were files missing for the make dist tarball for CMake, that has been fixed since.

For 4.2.2 please either use the full repository tarball: https://github.com/zeromq/libzmq/archive/v4.2.2.tar.gz or git clone and checkout the tag.

Given you are on Linux, note we also build packages for most distros/architectures that are ready to use: https://build.opensuse.org/project/show/network:messaging:zeromq:release-stable

**Comment by Vaelatern** [comment]
This is not installed in a `./configure` `make` setup, but is installed in a `cmake` build.
Yet if I build via `cmake`, files such as the man pages don't get installed.

**Comment by bluca** [comment]
Docs are installed in PATH/doc/zmq, you need to make sure to have the build dependencies, like Python and asciidoc

**Comment by bluca** [comment]
Ah yes they are not manpages, it installs the HTML versions

Could you please send a PR to enable manpages generation and installation in CMake too?

**Comment by Vaelatern** [comment]
Also
Problem: `make install` doesn't install `cmake` build files.

**Comment by Vaelatern** [comment]
Sadly my cmake knowledge is very limited, but I can give it a shot.

**Comment by Vaelatern** [comment]
Wow I let this slide.
My cmake knowledge is still limited, but I'll try to at least install the cmake build files from the Makefile, if that's doable.
