### ISSUE TITLE
zmq ports are occupied, and socket leak?

### ISSUE THREAD

**Issue by caidongyun** [zeromq/libzmq#2598]
The ports are occupied, and then these connections are initiated by the 12580 which takes up some of the user's application ports. These are not probing connections and then are not closed

TCP    127.0.0.1:12567        127.0.0.1:5905         ESTABLISHED     16540
  TCP    127.0.0.1:12568        127.0.0.1:5905         ESTABLISHED     16540
  TCP    127.0.0.1:12569        127.0.0.1:5905         ESTABLISHED     16540
  TCP    127.0.0.1:12570        127.0.0.1:5905         ESTABLISHED     16540
  TCP    127.0.0.1:12574        127.0.0.1:5905         ESTABLISHED     16540
  TCP    127.0.0.1:12577        127.0.0.1:5905         ESTABLISHED     16540
  TCP    127.0.0.1:12578        127.0.0.1:5905         ESTABLISHED     16540
  TCP    127.0.0.1:12579        127.0.0.1:5905         ESTABLISHED     16540
  TCP    127.0.0.1:**12580**        127.0.0.1:5905         ESTABLISHED     16540
  TCP    127.0.0.1:12581        127.0.0.1:5905         ESTABLISHED     16540
  TCP    127.0.0.1:12582        127.0.0.1:5905         ESTABLISHED     16540
  TCP    127.0.0.1:12583        127.0.0.1:5905         ESTABLISHED     16540

TCP    127.0.0.1:5905         127.0.0.1:12570        ESTABLISHED     16540
  TCP    127.0.0.1:5905         127.0.0.1:12574        ESTABLISHED     16540
  TCP    127.0.0.1:5905         127.0.0.1:12577        ESTABLISHED     16540
  TCP    127.0.0.1:5905         127.0.0.1:12578        ESTABLISHED     16540
  TCP    127.0.0.1:5905         127.0.0.1:12579        ESTABLISHED     16540
  TCP    127.0.0.1:5905         127.0.0.1:**12580**        ESTABLISHED     16540

**Comment by caidongyun** [comment]
TCP 127.0.0.1:12567 127.0.0.1:5905


Why he built so much connection？？？？？？？？

**Comment by caidongyun** [comment]
unsigned char dummy = 0;
    while (true) {
        int nbytes = ::send (w, (char*) &dummy, sizeof (dummy), 0);
        wsa_assert (nbytes != SOCKET_ERROR);
        if (unlikely (nbytes == SOCKET_ERROR))
            continue;
        zmq_assert (nbytes == sizeof (dummy));
        break;
    }


 caused by this？

**Comment by bluca** [comment]
Which version? On which platform? Can you upload your code to pastebin or gist?

**Comment by caidongyun** [comment]
#define ZMQ_VERSION_MAJOR 4
#define ZMQ_VERSION_MINOR 1
#define ZMQ_VERSION_PATCH 2

windows

**Comment by caidongyun** [comment]
Who will create a connection 5905?
 I need the key code and then do a review. Thank you

**Comment by bluca** [comment]
Is your code creating one context per socket perhaps? That would explain it

**Comment by Crossverse** [comment]
I see the similar situation on windows.

zmq - MSYS2 4.2.2-1 build.

zmq_init creates two interconnected 127.0.0.1 sockets.
zmq_socket creates half-dozen interconnected 127.0.0.1 sockets.
That sockets exist forever.

**Comment by bluca** [comment]
On Windows the internal pipes are TCP, so it's normal that there are sockets. The initial transfer is to "tune" the pipes.

What is the exact problem?

**Comment by bluca** [comment]
No answer, closing
