### ISSUE TITLE
libzmq conan packages in bintray

### ISSUE THREAD

**Issue by memsharded** [zeromq/libzmq#2600]
Hi!

I am currently maintaining [conan](https://conan.io) packages for libzmq. You can check the repo I am using here: https://github.com/memsharded/conan-zmq/tree/release/4.1.5. As you can see, it is totally non-intrusive, and the package recipe (https://github.com/memsharded/conan-zmq/blob/release/4.1.5/conanfile.py) should be easy to understand.

4.1.5 is now the version I pretend to submit an inclusion-request to 
[conan-center](https://bintray.com/conan/conan-center), the new central repository in Bintray for C and C++ packages, now empty (launched 10 days ago), which is moderated and curated and will only accept quality packages, or package created by the original authors.

I am currently building, creating and testing packages for 124 different configurations, in Windows/Linux/OSX, for different compilers and versions, and with different architectures, build types and shared/static flavours. All of these binaries are created from sources with the above package recipe. The binaries are used by default, but building from sources is always possible (for those not trusting the binaries, or for platforms without pre-built binary packages)

This is the full matrix:

![nueva imagen](https://user-images.githubusercontent.com/15367152/27388468-d8929b64-569b-11e7-80fb-cea4d316e3e2.png)

Everything is fully automated in travis and appveyor, and automatically uploaded to my own personal repo in bintray:
- Travis: https://travis-ci.org/memsharded/conan-zmq
- Appveyor: https://ci.appveyor.com/project/memsharded/conan-zmq/build/1.0.56
- Bintray: https://bintray.com/memsharded/community/libzmq%3Amemsharded

From my personal repo in bintray I can already do the inclusion-request, but first I would like to ask to the zeromq community:

- Is there some interest in creating binaries for other configurations?
- Would the zeromq community be interested in having access to these repos? In that case, I could transfer my repo https://github.com/memsharded/conan-zmq to the zeromq github org, and I could create a zeromq organization in bintray, and give admin to you. I can keep working and maintaining this (next step I want to do is release/4.2), but you would have control over it too.

Looking forward to hearing your feedback. Thanks!

**Comment by bluca** [comment]
Hi,

First of all, thanks for your work!

Binary distribution is a very welcome contribution especially for Windows, we get requests and there has not been any since a few years back simply due to lack of manpower.

For Linux we have packages for most distros and architectures:

https://build.opensuse.org/project/show/network:messaging:zeromq:git-stable (latest Github HEAD)
https://build.opensuse.org/project/show/network:messaging:zeromq:release-stable (latest release)

For Linux IMHO the OBS approach is better because it guarantees no ABI problems, and also it has a built-in delivery system of updates (package repositories).
This is fully automated too on merge or on release.

For OSX I know someone contributed formulae to Brew. I am not an OSX user so I am not sure which one is more popular/useful, or if they serve different purposes.

Windows would be very very interesting. As you can see we have release automation to Github artefacts from Travis. How can we take this forward? Can that be integrated into the Travis release system? For example upload the source artefact to the Windows build system.

**Comment by memsharded** [comment]
Yes, totally agree the value is higher in Windows, because Linux system package managers have always been good. Even though, conan might have several advantages for developers, as it is a language package manager, not a system package manager, so for example:
- They do not require sudo/root permissions to install in any system.
- Multiple versions can coexist at the same time, without being overwritten, or having to change symlinks or anything
- Packages have user&channels, so they can be moved/promoted between different stages.
- "Forking" a package, and creating your customized/optimized binary and caching it in your local binary server is simple. Same for other platforms that might not have pre-compiled binaries, users can still create them and store them easily in their server, in a cross-platform way. Forked packages can easily coexist with the original packages in the same machine, even for the same version (using users&channels).

Also, it is very likely that conan users expect to be able to install libzmq from conan packages in all their platforms, this is basically one of the strengths of conan, so even if I know that much more people will install libzmq from the system package managers, I prefer to maintain the conan ones too. And once it is setup, it is totally effortless.

Regarding integration, I think it is still a bit premature, I would try first to start rolling it as a separate repo, learn, release, iterate. Also to know about your release cycle, if you want to create binary packages for the develop branch at every push? Might be too overkill. Even nightly. Maybe creating packages for the releases is what makes more sense. From the conan point of view the flow for a new release would be:

1. clone the package recipe repo: https://github.com/memsharded/conan-zmq
2. create new branch "release/version" for the new version
3. bump version in ``conanfile.py``. Check if the source origin has changed, update version if necessary accordingly. For example, in the current recipe, the source origin is now coded as:
  ```python
  def source(self):
        self.run("git clone https://github.com/zeromq/zeromq4-1.git")
        self.run("cd zeromq4-1 && git checkout v4.1.5")
  ```
  It should be updated

4. Create the package and test it locally with ``conan test_package``. If it fails, because something has changed, lets say, the final library name, fix it.
5. Update the travis & appveyor CI scripts for the new version.
6. git push

When library doesn't change much, this can be done in just a few minutes.


>For example upload the source artefact to the Windows build system.

Sorry I don't fully understand it, what do you mean with this?

Thanks very much for your quick response and interest!

**Comment by gasuketsu** [comment]
> * Multiple versions can coexist at the same time, without being overwritten, or having to change symlinks or anything
I think this is very important and helpful for developers who develop/maintain multiple applications that depends on zmq (e.g. one app requires zmq-3 for maintenance and other new app requires the latest stale zmq).

Also, as you can see http://conanio.readthedocs.io/en/latest/getting_started.html, consumer applications (applications who use zmq) just need to have simple recipe (conanfile.txt) and just run `conan install` to install all dependencies (not only direct dependencies but also indirect). This simplicity enables easy setup/adaptation to CI for the consumer applications too.

**Comment by marco-m** [comment]
Hello @bluca, any news? We are big conan users and producers at work and I can attest conan is a very good approach at managing C/C++ dependencies, both for Windows and for Linux, when the consumers are developers.

**Comment by bluca** [comment]
Hi, as I mentioned it looks like a great idea for Windows, but not sure what the steps are?
