### ISSUE TITLE
Heap corruption receiving multi-part messages (ZMQ 4.2.3, Windows 10, VS 2017) between v4 and v2

### ISSUE THREAD

**Issue by mpaffolter** [zeromq/libzmq#2604]
Hi,
When receiving multi-part messages (PUSH-PULL) in a minimal c++ program (B), I get a heap corruption error (detected by the page heap tool). When I receive the messages from the same PUSH client (A) in a python program (D) on the same machine, the heap corruption does not occur.

Version details:
- OS: Windows 10 x64 
- Program B: Built in C++ Visual Studio 2017, ZMQ v 4.2.3 (master) with cppzmq (master, commit fc990f1419adb10c8b064ee9557eea63e46f0f04)
- Program D: Python 3.5.2, pyzmq 16.0.2, ZMQ v 4.1.6 (pip-install)
- Program A: C++ built and run on Ubuntu 16.04.2

Please see the attached text-file with programs and detailed output. 
[ZMQ_crash_detailed_info.txt](https://github.com/zeromq/libzmq/files/1097456/ZMQ_crash_detailed_info.txt)

The crash occurs after a few seconds or minutes. What could be causing the crash? I'd be happy to provide more information if needed.

**Comment by bluca** [comment]
any chance you could reproduce without cppzmq?

**Comment by mpaffolter** [comment]
Ok, I've rewritten the minimal c++ programm (B) to use only the libzmq api. So far it did not crash after running for 1h and receiving 80k messages. Maybe I should post an issue at cppzmq then?

**Comment by bluca** [comment]
If it can't be reproduced with just libzmq then yes please, reopen over there

**Comment by bjovke** [comment]
@mpaffolter I've tested your program (file you attached) with Visual studio 2015 and it runs fine without crash. However, I could not find function `s_recv_strict()` anywhere in zguide library, where's this function defined? I've used `s_recv()`.

**Comment by bjovke** [comment]
@mpaffolter Your program crashed in `zmq::c_single_allocator` destructor on line `std::free (buf)`. Constructor allocates `buf ` but there's an assert in constructor: `alloc_assert (buf);`, so there's no way that `std::free()` was freeing `NULL` if `std::malloc()` failed.
So it must be that something has overwritten `buf` member of `zmq::c_single_allocator` or there's a mismatch between libzmq.dll and your program. By "mismatch" I mean that your program must have been compiled with the same compiler and have the same runtime linkage (static or dynamic) as libzmq.dll in order not to have mismatch.
Can you check how you compiled libzmq.dll and your program?

**Comment by mpaffolter** [comment]
@bjovke Thanks for testing. The function `s_recv_strict()` might have been added by us. I used both functions and the crash occurred also with `s_recv()`. Just to be complete, here's what it does:
```
//  Receive 0MQ string from socket and convert into string
static std::string
s_recv_strict(zmq::socket_t & socket) {

	zmq::message_t message;
	if (!socket.recv(&message))
		throw zmq::error_t();

	return std::string(static_cast<char*>(message.data()), message.size());
}
```
Both the test program and the libzmq.dll were built with VS2017 multithreaded debug, x64, 
![dependencies_libzmq](https://user-images.githubusercontent.com/16540939/27527808-bf40313e-5a4d-11e7-8da4-5737381b8a13.PNG)
so there should not be a mismatch. As stated above, the version using only the libzmq api did not crash, so I figure the issue might be related to cppzmq. I will open an issue there.

Test program using pure libzmq API:
```
#include "stdafx.h"
#include <assert.h>
#include <string>
#include <iostream>
#include <zmq/zmq.h>

int main(char** argv, int argc)
{
	unsigned long max_nof_messages = 1e6;
	std::string engine_uri = "tcp://*:5656";
	auto * context = zmq_ctx_new();
	auto * socket = zmq_socket(context, ZMQ_PULL);


	std::cout << "Binding to " << engine_uri << std::endl;
	zmq_bind(socket, engine_uri.c_str());

	std::cout << "Start receiving..." << std::endl;
	unsigned long nof_messages = 0;
	while (nof_messages < max_nof_messages) {
		zmq_msg_t msg_topic;
		int rc = zmq_msg_init(&msg_topic);
		assert(rc == 0);

		zmq_msg_t msg_content;
		rc = zmq_msg_init(&msg_content);
		assert(rc == 0);

		zmq_msg_recv(&msg_topic, socket, 0);
		zmq_msg_recv(&msg_content, socket, 0);
		auto topic_size = zmq_msg_size(&msg_topic);
		auto topic_data = zmq_msg_data(&msg_topic);
		auto content_size = zmq_msg_size(&msg_content);
		auto content_data = zmq_msg_data(&msg_content);

		std::string topic(static_cast<char*>(topic_data), topic_size);
		std::string content(static_cast<char*>(content_data), content_size);
		std::cout << topic << " (size: " << content.size() << ") [Nr." << nof_messages << "]" << std::endl;
		nof_messages++;
		zmq_msg_close(&msg_topic);
		zmq_msg_close(&msg_content);
	}
	return 0;
}
```

**Comment by bluca** [comment]
Is one of the sides a very old zmq v1 or v2? That's the only reason it would use the v1 decoder

**Comment by mpaffolter** [comment]
The version used by the ubuntu machine sending the messages is 2.2.0+dfsg-7 (ubuntu 16.04 lts).

I just did another test with the libzmq API only program and the crash occurred also, so it doesn't seem to be a cppzmq problem after all.

**Comment by bluca** [comment]
Did you build your own program there? Then install libzmq3-dev instead so you get a more recent version

**Comment by bjovke** [comment]
@mpaffolter _"The bufsize is seems a little high, since the sent content in this message is just "Replay""_ Well this adds to the theory that `buf` value given to `free()` is not the same one obtained by `malloc()` in `zmq::c_single_allocator` constructor/destructor.
If this is the case, we need to find a way to determine where in code did the `buf` change.
It would have been easy with memory breakpoint if crash can be caused on every run but it's harder this way.
It seems that your test app involves more of your code, `Analyzer `? Can you remove all of the other stuff in your test, Analyzer, VLOG(), message_queue, etc., that is, strip down the code as much as possible, and try again?

**Comment by bjovke** [comment]
@mpaffolter  Then again, sending code has a lot of stuff, not the receiving one which crashes, if I'm right?

**Comment by mpaffolter** [comment]
@bjovke Yes, the receiving side is the one that is crashing and it is already stripped down to the bare bones :). 
@bluca We updated the sending side to 4.1.4 and will now test again. Hopefully this will solve our crashing problem. I'll let you know.

**Comment by mpaffolter** [comment]
@bluca and @bjovke : The minimal example has been running for the last 4 1/2 h,  receiving 115k messages without any crash so far. So it seems the problem was related to the combination of different zmq versions (2.2 and 4.2.3). I consider the problem solved (i.e. do not use that combination). Thanks for your help!

**Comment by bluca** [comment]
Thanks for confirming. Interoperability should still work, so changed the titled.

**Comment by bjovke** [comment]
@mpaffolter Is there any chance that you make minimal example Wireshark traces for v2 sender and v4 sender?

**Comment by bluca** [comment]
I tried reproducing with a v2 client and a v4 server on Linux, but without any luck. The code is almost identical to the one you posted, with a couple small changes to make it compile:

https://gist.github.com/bluca/99dc37f83c3bcc65766307a1b638910d

Link the v2 against zeromq2-x and the v4 against libzmq master or zeromq4-1

**Comment by mpaffolter** [comment]
@bjovke I will try to find some time to setup and record the traffic with wireshark (was on vacation last week :) Will post the results here when finished.

@bluca Will run your code also, while I am at it. One difference I see is the constant size of the second message, in contrast to our variable size.

**Comment by bluca** [comment]
@mpaffolter did you manage to run that test?

**Comment by mpaffolter** [comment]
@bluca Sorry, no.

**Comment by bluca** [comment]
Ok, will consider it solved and close then. Reopen if you find issues again.
