### ISSUE TITLE
Enable building ZMQ with CMake and specify static lib name

### ISSUE THREAD

**Issue by Olipro** [zeromq/libzmq#2606]
Having libzmq build a static library with the same name as the shared one is awkward when building a cross-platform application as specifying `libzmq.a` is only going to work on platforms with that prefix.

It would be preferable if it either used the old `libzmq-static` or checked for a switch that would override the static lib's name.

**Comment by bluca** [comment]
Having the same name is the accepted common practice in all Linux distributions and allows the -lzmq flag to be passed to the linker and work in both cases.
The extension is there to disambiguate.

**Comment by bluca** [comment]
If you would like to add a cmake option to override the default that's fine though, so please send a PR and we'll merge it
