### ISSUE TITLE
Is it possible to async-poll on non-async ZMQ sockets?

### ISSUE THREAD

**Issue by azag0** [zeromq/libzmq#2607]
The async Poller seems to accept either async ZMQ sockets or raw sockets, but not non-async ZMQ sockets. I get a non-async ZMQ socket from within an upstream project, and would like to poll on it in my asyncio project. Right now, I run blocking upstream functions within the asyncio thread executor, but that's unnecessarily inefficient.

**Comment by bluca** [comment]
This sounds like Python stuff? If so the right place is https://github.com/zeromq/pyzmq

**Comment by azag0** [comment]
Ah, sorry about this.
