### ISSUE TITLE
Don't undef _WIN32_WINNT

### ISSUE THREAD

**Issue by diorcety** [zeromq/libzmq#2612]
If the user set an _WIN32_WINNT definition we should avoid to change it.
https://github.com/zeromq/libzmq/blob/master/src/windows.hpp#L54
https://github.com/zeromq/libzmq/blob/master/include/zmq.h#L71
An error message is maybe better.

**Comment by bjovke** [comment]
@diorcety I'm not sure that I can see the issue.
`_WIN32_WINNT` will be defined/redefined only if it's already not defined or if features require some minimum Windows version:

- `ZMQ_HAVE_WINDOWS_UWP` defined -> minimum Windows 10.
- `__MINGW32__` defined -> if `_WIN32_WINNT` is less than `0x0600` redefine it to `0x0600`.

This code maybe needs some rearrangement to be more readable but it's nothing critical.

```
//  Set target version to Windows Server 2008, Windows Vista or higher.
//  Windows XP (0x0501) is supported but without client & server socket types.
#if !defined _WIN32_WINNT && !defined ZMQ_HAVE_WINDOWS_UWP
#define _WIN32_WINNT 0x0600
#endif

#if defined ZMQ_HAVE_WINDOWS_UWP
#define _WIN32_WINNT _WIN32_WINNT_WIN10 
#endif

#ifdef __MINGW32__
//  Require Windows XP or higher with MinGW for getaddrinfo().
#if(_WIN32_WINNT >= 0x0600)
#else
#undef _WIN32_WINNT
#define _WIN32_WINNT 0x0600
#endif
#endif
```

**Comment by diorcety** [comment]
If the user define 0x0501 i don't see the the point to undef it. The issue behind is a preprocessor nightmare that I had. I have 0x0501 as value, I include one header which include windows.h, the vista functions are not defined. I include an another header which include libzmq, the value is changed to 0x0600. I include an other header which use _WIN32_WINNT do modify some code using vista functions, which trigger errors.

**Comment by bjovke** [comment]
@diorcety To be honest I'm not sure why for MinGW Vista is minimum Windows version (0x0600). Even the comment is confusing:
```
//  Require Windows XP or higher with MinGW for getaddrinfo().
#if(_WIN32_WINNT >= 0x0600)
```
This is related to #1381 and #1383 and it seems that this part with MinGW is skipped.
I will make a PR with some changes for this.

**Comment by bjovke** [comment]
@diorcety Tests won't compile with this change. There seems to be a requirement for overriding _WIN32_WINNT for tests. I have to inspect this a little bit more.

**Comment by bjovke** [comment]
@diorcety Unfortunately it seems that for MinGW `getaddrinfo()` is needed and minimum Windows version which supports `getaddrinfo()` is Windows Vista, hence the `#undef` and `#define` to` 0x0600`.
Actually tthis line is wrong:

`//  Require Windows XP or higher with MinGW for getaddrinfo().`

It should say instead:

`//  Require Windows Vista or higher with MinGW for getaddrinfo().`

Did you manage to build something on Windows XP and MinGW? If that's the case can you explain how you did it so we can make appropriate changes?
Letting `_WIN32_WINNT `to be lower than `0x0600` for MinGW build makes all of the tests non-compilable.

**Comment by diorcety** [comment]
@bjovke You can see my commit here: https://github.com/diorcety/libzmq/commit/ca8df3d224eb0fb5b34dee8644f5ff7b44819b3a
I'm currently using this branch for compiling on linux, windows MSVC and windows MSYS. Maybe there is an issue in mingw on the MSDN documentation, it's written:

> The getaddrinfo function was added to the Ws2_32.dll on Windows XP and later

**Comment by bjovke** [comment]
@diorcety  Yes, you're right. But the building of all tests fails. This might have something to do with AppVeyor build environment setup. Can you try running build and test for your commit on AppVeyor?

**Comment by bjovke** [comment]
@diorcety Here are the failed ones for me: [AppVeyor](https://ci.appveyor.com/project/zeromq/libzmq/build/build-1518) and [Libzmq](https://libzmq.cloudapp.net/job/libzmq/1707/) builds.

**Comment by bjovke** [comment]
@diorcety Also, for `getaddrinfo()` on XP it is recommended to additionally include `Wspiapi.h`, which is currently not included.
