### ISSUE TITLE
zmq_socket_monitor on ZMQ_PUB socket

### ISSUE THREAD

**Issue by eile** [zeromq/libzmq#2618]
Is it possible that pub sockets do not emit events on new subscriptions? If yes, is this considered a bug or is this by design? Is there another way to get notified of new subscribers without resorting to XPUB/SUB sockets and implementing my own topic filtering?

**Comment by bluca** [comment]
XPUB/XSUB is the way to go for that kind of notifications, that's the whole point of those socke types. There are no events. It would be redundant.

**Comment by eile** [comment]
Too bad. I understand it would be redundant, but not having it forces two different implementations to hide this asymmetry to get notifications for pub/sub and req/rep sockets.

**Comment by bluca** [comment]
If it would be useful for you and you would like to spend time to implement it, please feel free to do so and send a pull request, and we'll merge it.
