### ISSUE TITLE
How to use libzmq in android？

### ISSUE THREAD

**Issue by privatez** [zeromq/libzmq#2627]
when i flow [doc build for android](https://github.com/zeromq/libzmq/blob/master/builds/android/README.md) i will got 'libzmq.so' file.
How to use this file in android?

**Comment by djelenc** [comment]
Once you've compiled binaries, you have to upload them to your Android device (there's a dedicated folder inside your Android app where you have to put it) and the use a java ZMQ bindings: check out [jzmq](https://github.com/zeromq/jzmq) 

There is a pure-Java ZMTP implementation called [JeroMQ.](https://github.com/zeromq/jeromq) It recently got ZMTP/3.0 support, including security, so unless you require something that JeroMQ explicitly does not support--like ipc, pgm, or normprotocol, stick to JeroMQ -- it is the simplest solution.

Also, bare in mind that if using C++ ZMQ implementation, you'll have to make multiple binaries depending on what kind of CPU the Android device is using: while most use ARM, there are also those that use Atom, for instance.

**Comment by bluca** [comment]
http://zeromq.org/build:android

@djelenc if you see something missing/wrong/out of date on that page, could you please update it? Thanks!

**Comment by privatez** [comment]
@djelenc 
JeroMQ i just try it.But it can't connect my service.
I got a new ‘libjzmq.so’ file buy the [doc](https://github.com/zeromq/jzmq/blob/master/jzmq-jni/Dockerfile) on last night.But the  ‘libjzmq.so’ file is 64-bit.So how can i  build a 32-bit?

**Comment by privatez** [comment]
@bluca
First, thank for your job for zeromq.
But  I'm so sorry to say [http://zeromq.org/build:android](http://zeromq.org/build:android) is not a good doc.I will try to update it when i fish my job.

**Comment by bluca** [comment]
You'll need to cross compile or use a multiarch chroot - either way it's independent of libzmq, we use autotools so look for instructions for autotools cross compilation
Also for jzmq problems please use jzmq issue tracker

**Comment by bjovke** [comment]
@privatez It seems that there's no issue in libzmq itself, based on this discussion.
It also seems that there are no errors observed during build process, you just need guidance on how to set up everything on android if I'm correct?
Please use libzmq mailing lists if you need assistance, here we are discussing only issues in the libzmq native library itself.
