### ISSUE TITLE
IPV6_V6ONLY compatibility on OpenBSD

### ISSUE THREAD

**Issue by ecoughlan** [zeromq/libzmq#2630]
zmq::enable_ipv4_mapping in ip.cpp causes an assertion failure (EINVAL) on OpenBSD. The IPV6_V6ONLY socket option cannot be set.

> With OpenBSD IPv6 sockets are always IPv6-only, so the socket option is read-only (not modifiable).

See also https://man.openbsd.org/OpenBSD-current/ip6#IPV6_V6ONLY

I believe a simple addition to the ifdef to read like
`#if defined IPV6_V6ONLY && !defined ZMQ_HAVE_OPENBSD`
would be enough.

**Comment by bluca** [comment]
Is it always been read-only, or just in recent versions?
Could you please send a PR to fix it as you suggested?

**Comment by ecoughlan** [comment]
It's been many years at least. I've changed the link above. Also PR here:
https://github.com/zeromq/libzmq/pull/2631

**Comment by bluca** [comment]
Great, thanks.
