### ISSUE TITLE
File descriptor leak in context constructor

### ISSUE THREAD

**Issue by hoditohod** [zeromq/libzmq#2632]
Hi libzmq guys!

## Issue
I have a test that spawns a few threads, creates a zmq context in each of them, does some boring stuff, then destroys the context and joins the threads. The test application leaks a few fd's to /dev/urandom in each iteration.

## Env
Ubuntu 16.04 64bit
libzmq 4.2.2 + cppzmq

## Root cause
The libzmq build I use has the ZMQ_USE_TWEETNACL undefined, so `randombytes()` directly reads /dev/urandom storing the fd in global static variable [here](https://github.com/zeromq/libzmq/blob/master/src/tweetnacl.c#L908) without any protection against concurrent execution. When calling the context constructor concurrently from multiple threads, the scoped_lock_t [here](https://github.com/zeromq/libzmq/blob/master/src/ctx.cpp#L94) is useless because the corresponding mutex is a class member (each instance has one mutex), and it doesn't prevent multiple concurrent context instances calling `randombytes()`.

As a result multiple threads open the file but only one close is issued.

**Comment by bluca** [comment]
Thanks for the report, I can see the issue. We'll have to lock&refcount I guess.

In the meanwhile, you can use 4.2.2 built with libsodium with packages for 16.04 from OBS: http://download.opensuse.org/repositories/network:/messaging:/zeromq:/release-stable/xUbuntu_16.04/

**Comment by bluca** [comment]
@hoditohod please try again from latest master
