### ISSUE TITLE
Problem: no man page for zmq_msg[_set]_group APis

### ISSUE THREAD

**Issue by nayabbashasayed** [zeromq/libzmq#2634]
Hi,
Where can I find the man page for zmq_msg_set_group() function?

**Comment by bluca** [comment]
There is none yet, as it's still a DRAFT api

**Comment by nayabbashasayed** [comment]
Would you please post and explain prototype briefly here as I am experimenting with it?

**Comment by bluca** [comment]
Check the ZMQ_RADIO section in the zmq_socket manpage.
Every message belongs to a group, sort of like the pub-sub subscription topic. zmq_msg_set_group(msg, group) is used to set the group of a message being sent. The group is a 15 char (+1 terminator) char array.

**Comment by nayabbashasayed** [comment]
Thanks. :)

**Comment by bluca** [comment]
No problem. I'll reopen as the lack of documentation needs to be tracked and solved.
