### ISSUE TITLE
Disconnecting a connected inproc socket cause "No such file or directory"

### ISSUE THREAD

**Issue by andreibica** [zeromq/libzmq#2635]
This may seems like a synchronization issue.
I'm using ZeroMQ version 4.2.1 on a 64 bit Linux machine.
The issue is easier to be reproduce on a slower machine or a machine with high CPU load from other applications.

The problem was initially detected using pyzmq in a Python script but it is also reproducible using the C API.
The following test will reproduce the problem:

```
#include <string.h>
#include <zmq.h>


void main(){

  for(int i = 0; i < 1000000 ; i++){

    void* context = zmq_ctx_new();
    char* endpoint = "inproc://test";

    void* puller = zmq_socket(context, ZMQ_PULL);
    if (!puller){
        printf("Failed to create puller socker: %s", strerror(errno));
        return;
    }

    if (zmq_bind(puller, endpoint)){
        printf("Failed to bind: %s", strerror(errno));
        return;
    }

    void* pusher = zmq_socket(context, ZMQ_PUSH);
    if (!pusher){
        printf("Failed to create pusher socker: %s", strerror(errno));
        return;
    }

    if (zmq_connect(pusher, endpoint)){
        printf("Failed to connect: %s", strerror(errno));
        return;
    }

    if (zmq_unbind(puller, endpoint)){
        printf("Failed to unbind: %s", strerror(errno));
        return;
    }

    if (zmq_close(puller)){
        printf("Failed to close puller: %s", strerror(errno));
        return;
    }

    if (zmq_disconnect(pusher, endpoint)){
        printf("Failed to disconnect: %s", strerror(errno));
        return;
    }

    if (zmq_close(pusher)){
        printf("Failed to close pusher: %s", strerror(errno));
        return;
    }

    zmq_ctx_destroy(context);
  }
}

```

After some iterations the program will exit with "Failed to disconnect: No such file or directory" when trying to disconnect the pusher.
If I change the order, and disconnect and close the pusher before unbinding and closing the puller, the problem doesn't appear anymore.
Also, if I put a sleep between puller and pusher cleanup the problem doesn't appear anymore.

**Comment by andreibica** [comment]
The problem is reproducible with the master as well ( 2991e6f).

**Comment by sigiesec** [comment]
I added the test case in https://github.com/sigiesec/libzmq/tree/issue-2635

**Comment by sigiesec** [comment]
The described problem shows up with the valgrind build/run here: https://travis-ci.org/sigiesec/libzmq/jobs/266470701

**Comment by ovanes** [comment]
Just wanted to confirm same here on Mac OS X.

In my case I created `REQ/REP` `inproc` socket pair. `unbind` of the `REQ` socket always works, `REP` socket never.

**Comment by bluca** [comment]
note that you don't need to disconnect if you are closing the socket

**Comment by ovanes** [comment]
Well, not doing `unbind` brought `close` to crash with `SIGABRT` later on... I did lots of empirical testing and it seemed like `socket::unbind`, `socket::close`, `context::close` works best. I understand, that at this point an example is needed, but I can't provide it right now.
