### ISSUE TITLE
On zmq_recv timeout my thread received data ment for other thread.

### ISSUE THREAD

**Issue by pradsin** [zeromq/libzmq#2637]
I am using ZMQ in multi threaded environment, I observed that when there is load on system and recv times out then next recv receives packet ment for previous recv for which request timed out.

I have written sample to reproduce the issue, I have kept a low timeout value or 10ms to reproduce the issue sooner.

Client is using ZMQ_REQ sockets and sending a number and some other data to server. on server there are 8 worker threads to process sockets. I noticed that client is receiving data meant for other thread.

Source Files [msvc.zip](https://github.com/zeromq/libzmq/files/1182960/msvc.zip)

Visual Studio 2010 solution, you will need to place libzmq.lib in libs folder and also specify libzmq include path. [vs2010.zip](https://github.com/zeromq/libzmq/files/1182981/vs2010.zip)

**Comment by bluca** [comment]
You are sending from a dealer to multiple connected clients - as the documentation says, the dealer outgoing strategy is round-robin. If a send fails, the next client is sent the message.

Also given you are sending from dealer to rep you should add the empty frame as described in the zguide:
http://zguide.zeromq.org/page:all#toc60

**Comment by sigiesec** [comment]
@pradsin I assume your question is answered, and close the issue for now. If you still have issues, feel free to reopen it.
