### ISSUE TITLE
make_fdpair hangs trying to send large chunk of data

### ISSUE THREAD

**Issue by 0x0badc0de** [zeromq/libzmq#2638]
Faced this while using ZMQ under Wine on OS X. it just hangs on this line https://github.com/zeromq/libzmq/blob/1d58a00992fa3f2930bb8c6602db600e24a13756/src/signaler.cpp#L543 trying to send 1MB into a socket.
Quick workaround:
```
$ sudo sysctl -w net.inet.tcp.sendspace=1300000
net.inet.tcp.sendspace: 131072 -> 1300000
```
But probably it would be better to make ZMQ working regardless of system buffer size. Let me know if any further details/debugging are required.

**Comment by bluca** [comment]
That is necessary to work around a Windows problem. Perhaps worth documenting that running Windows binaries on *nix needs at least a MB of TCP buffers.
Could you please send a PR to update the INSTALL file?

**Comment by 0x0badc0de** [comment]
Sorry for delay, I see you've already done some changes, thanks for that!

**Comment by bluca** [comment]
No problem - thanks for finding the workaround
