### ISSUE TITLE
Assertion on latest stable version of pyzmq

### ISSUE THREAD

**Issue by janemba** [zeromq/libzmq#2641]
Hi,

I'm using the following versions :
 - zeromq-4.2.2
 - pyzmq-17.0.0.dev
 - cython-0.26

And it seems `python ZMQ` is not working fine. I'm using the following test script:

    #!/usr/bin/env python                                                                                                  
    # -*- coding: utf-8 -*-                                                                                                

    import zmq
    import multiprocessing

    class Worker(multiprocessing.Process):

        def __init__(self, name, context):

            super(Worker, self).__init__()

            self._name = name
            self._ctx  = context

            self._sock = self._ctx.socket(zmq.REP)

       def run(self):

            print "ok 1"
            self._sock.connect("ipc:///tmp/backend.ipc")
            print "ok 2"

            while True:

                print "I'm waiting %s" % self._name
                s = self._sock.recv()
                print "I received something %s" % self._name
                print self._name, s

    def main():

        context  = zmq.Context()
        frontend = context.socket(zmq.ROUTER)
        backend  = context.socket(zmq.DEALER)

        frontend.bind("tcp://*:5555")
        backend.bind("ipc:///tmp/backend.ipc")

        p = Worker('bar 1', context)
        p.daemon = True
        p.start()

        p = Worker('bar 2', context)
        p.daemon = True
        p.start()

        zmq.proxy(frontend, backend)

    if __name__ == '__main__':
        main()

And the output :

    $ python test.py    
    ok 1
    Assertion failed: ok (src/mailbox.cpp:99)
    ok 1
    ok 2
    I'm waiting bar 1
    [1]    3703 abort      python test.py
    ok 2                                                                                                                   
    I'm waiting bar 2

So...why that `assertion` ?

**Comment by bluca** [comment]
For pyzmq issues please use the pyzmq repository: https://github.com/zeromq/pyzmq/issues

**Comment by janemba** [comment]
ok thank you
