### ISSUE TITLE
ZeroMQ RADIO/DISH Requirement

### ISSUE THREAD

**Issue by deepthi16** [zeromq/libzmq#2642]
Is there a way of using RADIO/DISH (with UDP)  to send data to the first receiver and not broadcast to all the nodes but just to the first node which receives it. 

More like a PUSH/PULL pattern where only one of the receiver gets the message from the pipe and the same message is not repeated in other nodes.

The reason I am using RADIO/DISH is for UDP support but I need the functionality of push / pull which is not supported in UDP.

Any thoughts or work arounds?

**Comment by bluca** [comment]
Have a look at ZMQ_DGRAM

**Comment by somdoron** [comment]
You can also use unicast addresses with radio/dish.

**Comment by deepthi16** [comment]
Thank you will check it out.

**Comment by bluca** [comment]
Closing then - feel free to reopen if you find any issues

**Comment by deepthi16** [comment]
Is there a way where I can know the first node which receives the message using RADIO/DISH or have the message be transmitted to only one of the nodes listening to this socket.

I tried DGRAM socket but its like req-reply and does not solve my use case where the first receiver of the message processes it and other ignore it .

**Comment by bluca** [comment]
There is no way to know, as UDP is lossy. If you implement an ACK, you might not receive it, but the client might have sent it and might have been lost.

If you need reliable transport you need TCP.

**Comment by deepthi16** [comment]
Thanks.
