### ISSUE TITLE
Misleading error code in case ZAP handler sends an invalid status code

### ISSUE THREAD

**Issue by sigiesec** [zeromq/libzmq#2643]
According to the ZAP protocol specification, the allowed status codes are 200, 300, 400 and 500. If the ZAP handler sends something like "blah" instead, this is a violation of the ZAP protocol rather than a rejected authentication request.

The error code should therefore be EPROTO rather than EACCES.

**Comment by bluca** [comment]
Fixed by https://github.com/zeromq/libzmq/pull/2646
