### ISSUE TITLE
Help: Divided test_radio_dish.cpp into test_radio.cpp and test_dish.cpp won't work.

### ISSUE THREAD

**Issue by nayabbashasayed** [zeromq/libzmq#2657]
Hi,

I separated [Combined radio dish example](https://github.com/zeromq/libzmq/blob/master/tests/test_radio_dish.cpp) into [radio](https://github.com/nayabbashasayed/libzmq-examples/blob/master/test_radio.cpp) and [dish](https://github.com/nayabbashasayed/libzmq-examples/blob/master/test_dish.cpp) each.

I compiled those programs with -lzmq (into let's say `test_radio` and `test_dish`).
Then I started `./test_dish` in one terminal first. And then `./test_radio` in the second terminal.

`zmq_msg_recv` keeps on waiting (in blocking state) even though `test_radio` finished execution.

The combined example works fine. I've studied API man pages. Don't know what I am missing here.

**Comment by bluca** [comment]
radio, like pub, is lossy, and trying to carefully synchronise them manually is not a good idea. Either send in a loop or have an out-of-band synchronisation mechanism to signal start and stop, like a req-rep
