### ISSUE TITLE
getrandom() broken on Solarish platforms

### ISSUE THREAD

**Issue by jimklimov** [zeromq/libzmq#2658]
Probably related to recent/ongoing work with crypto etc., I got this in my build of current master on OpenIndiana:

````
../../../.srcclone/SunOS-i86pc-czmq_4/libzmq/src/tweetnacl.c: In function 'randombytes':
../../../.srcclone/SunOS-i86pc-czmq_4/libzmq/src/tweetnacl.c:936:13: error: too few arguments to function 'getrandom'
         i = getrandom (x, i);
             ^
In file included from ../../../.srcclone/SunOS-i86pc-czmq_4/libzmq/src/tweetnacl.c:912:0:
/usr/include/sys/random.h:76:12: note: declared here
 extern int getrandom(void *, size_t, int);
            ^
gmake[3]: *** [Makefile:3278: src/src_libzmq_la-tweetnacl.lo] Error 1
````

According to https://docs.oracle.com/cd/E86824_01/html/E54765/getrandom-2.html and https://blogs.oracle.com/darren/solaris-new-system-calls:-getentropy2-and-getrandom2 these were recently added (and ported to ecosystem) following Linux calls that apparently also have 3 args.

**Comment by bluca** [comment]
This is strange as there's an autoconf snippet to detect it:

https://github.com/zeromq/libzmq/blob/master/acinclude.m4#L859

Any idea why is that returning true?

**Comment by bluca** [comment]
oh hang on - lol, my mistake

**Comment by jimklimov** [comment]
Fixed for me too, on both Linux and Solarish systems.
