### ISSUE TITLE
Code coverage measurement is only partial

### ISSUE THREAD

**Issue by sigiesec** [zeromq/libzmq#2669]
We do not have coverage measurements for:
- [ ] Windows-specific code
- [ ] PGM
- [ ] NORM
- [ ] GSSAPI
- [ ] SOCKS

**Comment by bluca** [comment]
The issue with PGM/NORM/GSSAPI is coming up with a working test for the CI environment. They all need external configurations - working multicast or a working kerberos server. It would be quite complex to set that up for Travis, and I'm not sure the ROI justifies it.
Of course if anyone wants to give it a shot they are very welcome to do so.

For Windows, I'm sure it could be done but I have no idea how as I'm not really a Windows dev.

**Comment by sigiesec** [comment]
Hm, I can imagine that this is complex to set up. However, it should essentially be a one-time effort (of course it might break over time...), with permanent benefits :)

Unfortunately, I don't know a free Windows/Visual Studio code coverage tool. There is https://github.com/OpenCppCoverage/OpenCppCoverage but I have never used that, and I don't know whether it integrates with coveralls. I could have a look, however.

Just added SOCKS to the list above. I think that should be quite easy, e.g. using the "featureless" socksd https://github.com/floj/socksd
