### ISSUE TITLE
a bug occurs when using 2 zmq context_t concurrently and how to reproduce it

### ISSUE THREAD

**Issue by ykwd** [zeromq/libzmq#2670]
According to http://api.zeromq.org/2-1:zmq, multiple contexts may coexist within a single application. So I have two zmq context_t in the same process but different threads. And sometimes I need to delete an old context and create a new one. The problem is with time goes by, zmq will open /dev/urandom hundreds of times and finally, the process will crash due to running out of open file limit. Here is a simple program to reproduce it:

```
#include <stdio.h>
#include <zmq.hpp>
#include <thread>

void test_zmq()
{
    std::thread master_thread([&](){
        zmq::context_t* zmq_ctx = new zmq::context_t(2);
        zmq::socket_t* server = new zmq::socket_t(*zmq_ctx, ZMQ_REP);
        server->bind("tcp://127.0.0.1:12345");
        delete server;
        delete zmq_ctx;
    });
    std::thread worker_thread([&](){
        zmq::context_t* zmq_ctx = new zmq::context_t(2);
        delete zmq_ctx;
    });
    worker_thread.join();
    master_thread.join();
}

void my_test()
{
    for (int i = 0; 1 < 1000000; i++)
    {
        test_zmq();
    }
}

int main(int argc, char *argv[])
{
    int major, minor, patch;
    zmq_version (&major, &minor, &patch); printf ("Current ØMQ version is %d.%d.%d\n", major, minor, patch);
    my_test();
}
```
ps 1: my os is Ubuntu 14.04.5 LTS, my compiler is g++ 4.8.4, my zmq version is the latest 4.2.2. To compile the program, the compiler flag is -g -std=c++11 -lzmq
ps 2: Actually there is no need to wait the process to crash. After running it, type command "ls -l /proc/you_process_pid/fd | grep urandom | wc -l" and you can see how many times /dev/urandom has been opened but still not closed.

**Comment by bluca** [comment]
Hi, this is the same as: https://github.com/zeromq/libzmq/issues/2632 and was fixed by https://github.com/zeromq/libzmq/pull/2636

As a workaround, if you can't use the latest master (or the latest packages built on OBS http://download.opensuse.org/repositories/network:/messaging:/zeromq:/git-stable/xUbuntu_14.04/ ) you can rebuild using libsodium - install libsodium-dev and use ```./configure --with-libsodium=yes```

**Comment by ykwd** [comment]
thank you for your really quick response!
