### ISSUE TITLE
Value in ZMQ_EVENT_HANDSHAKE_FAILED_* monitor events 

### ISSUE THREAD

**Issue by sigiesec** [zeromq/libzmq#2682]
The value in the ZMQ_EVENT_HANDSHAKE_FAILED_* monitor events is currently an errno error code.
This does not allow to distinguish error situations in a fine grained way.

Another approach would be to define custom error codes for every situation where a handshake error is encountered, at least for all situations currently subsumed into EPROTO. This would allow for better tests, and for better diagnostics in production.

Currently, this is a DRAFT API, so it can still be changed without breaking a finalized API.

Any opinions on this?

**Comment by bluca** [comment]
Sounds like a good plan!
