### ISSUE TITLE
implement routing_id, group via message metadata

### ISSUE THREAD

**Issue by minrk** [zeromq/libzmq#2684]
`zmq_msg_get/set` added the ability to set metadata on messages (yay!). However, CLIENT-SERVER and RADIO-DISH sockets have added additional methods on frames in order to work. This is more work to support as a binding author than the existing option APIs, and why until now I haven't implemented support for these sockets in pyzmq.

If these message metadata fields were implemented via the existing message metadata functions rather than new, dedicated functions, they would be much more transparently exposed in bindings that already support those features, and significantly reduce the cost of supporting multiple libzmq versions. This would greatly facilitate users of bindings having access to draft features in the underlying library.

Same goes for join/leave, which would be nicer (for me as a binding maintainer) if implemented in setsockopt/getsockopt.

**Comment by bluca** [comment]
@somdoron what do you think? Were there particular reasons to add new functions for these properties?

**Comment by Asmod4n** [comment]
Would like to see that as well.

**Comment by somdoron** [comment]
we can add an alternative implementation through the old API semantic.
Regarding metadata, it is problematic to use, metadata is dynamically allocated. Right now it is allocated in the stream_engine and reused in all incoming messaging for that stream engine. So we cannot use that.

Anyway the idea behind this was to simplify the API, or make it more explicit. We had a discussion on this during one of the zeromq hackathons, to make zeromq API more like czmq and also to port stuff from czmq to zeromq. Like zmq_poller and timers.

I suggest not to drop the new methods (I actually prefer them that way, and most of the binding implement explicit API anyway) but to add an alternative implementation through set_sockopt

**Comment by minrk** [comment]
> I suggest not to drop the new methods (I actually prefer them that way, and most of the binding implement explicit API anyway) but to add an alternative implementation through set_sockopt

That sounds perfect to me. I do agree that the current C-API is nicer to use in C, and I wouldn't ask for it to be removed. It does make writing a high-level binding that supports libzmq back multiple major versions more complicated. If, for instance zmq_msg_gets('group') called `zmq_msg_group`, that would work quite well for me.  I've already implemented it this way at the pyzmq level because I think it's a better API in Python.

> to make zeromq API more like czmq and also to port stuff from czmq to zeromq. Like zmq_poller and timers.

I think that's a great goal for C users. And I would be super happy if I could treat the convenience methods such as `zmq_join` the same as I treat `zmq_poller`: that is, ignore them as high-level convenience methods of the C API that need not be exposed to Python.

**Comment by somdoron** [comment]
> I think that's a great goal for C users. And I would be super happy if I could treat the convenience methods such as zmq_join the same as I treat zmq_poller: that is, ignore them as high-level convenience methods of the C API that need not be exposed to Python.

Agreed. One comment though that zmq_poller yield better performance than zmq_poll, so you might want to consider to do the move at some point.

Bottom line, a PR that supporting set group through `zmq_msg_gets('group')` or join/leave through set_sockopt is very much welcomed.

**Comment by minrk** [comment]
Excellent. I'm a bit swamped right now, but I'll try to find a chance to do that if nobody gets to it first.
