### ISSUE TITLE
Assertion failed in test_sockopt_hwm on Windows

### ISSUE THREAD

**Issue by jimklimov** [zeromq/libzmq#2686]
https://ci.appveyor.com/project/zeromq/libzmq/build/build-1626/job/3y02wulys8m4f75f

Environment: platform=Win32, configuration=Release, WITH_LIBSODIUM=OFF, ENABLE_CURVE=OFF

````
Start 49: test_sockopt_hwm
[00:03:42] 
[00:03:42] 49: Test command: C:\projects\build_libzmq\bin\Release\test_sockopt_hwm.exe
[00:03:42] 49: Test timeout computed to be: 10
[00:03:42] 49: Assertion failed: send_count == 101, file C:\projects\libzmq\tests\test_sockopt_hwm.cpp, line 129
[00:03:45] 49/70 Test #49: test_sockopt_hwm .................***Exception: Other  3.67 sec
````

Other configurations in that run were OK

**Comment by sigiesec** [comment]
Unfortunately, we do not know the actual value of send_count here.

But I think the test makes wrong assumptions. The documentation of ZMQ_SNDHWM says:
> ØMQ does not guarantee that the socket will accept as many as ZMQ_SNDHWM messages, and the actual limit may be as much as 60-70% lower depending on the flow of messages on the socket.

But the test code actually tries to test that guarantee that is not given:
```
    val = 100;
    rc = zmq_setsockopt(bind_socket, ZMQ_SNDHWM, &val, sizeof(val));
    assert(rc == 0);

    // Fill up to hwm
    int send_count = 0;
    while (send_count < MAX_SENDS && zmq_send(bind_socket, &send_count, sizeof(send_count), ZMQ_DONTWAIT) == sizeof(send_count))
        ++send_count;
    assert(send_count == 101);
```

**Comment by bluca** [comment]
Sounds reasonable, perhaps ```send_count <= 101 && send_count > 50``` to have at least a lower bound?

**Comment by sigiesec** [comment]
Sounds good. I did this, and also changed the code below, but interestingly the minimum bound assumption does not hold there.
sndhwm is set to 70, but on my machine only 21 messages could be sent, which is only 30% rather than the 60-70% mentioned in the docs.

**Comment by sigiesec** [comment]
Also under Linux: 
https://travis-ci.org/sigiesec/libzmq/jobs/266016404#L1489

**Comment by sigiesec** [comment]
For the moment, yes. But this needs investigation. At least the doc would need to be updated. But IMO the effect of the hwm should be somewhat more predictable, at least as currently specified.

**Comment by bluca** [comment]
The problem is that it's quite tricky, especially with TCP. Lots and lots of variables at play.

**Comment by sigiesec** [comment]
Hm, ok... 
Then I will change the test to accept 10% of the HWM, and change the documentation accordingly.
