### ISSUE TITLE
Missed a heartbeat on MacOS

### ISSUE THREAD

**Issue by jimklimov** [zeromq/libzmq#2687]
https://travis-ci.org/zeromq/libzmq/jobs/265063746

````
FAIL: tests/test_heartbeats
===========================
Assertion failed: (rc == -1), function test_heartbeat_notimeout, file ../../tests/test_heartbeats.cpp, line 317.
FAIL tests/test_heartbeats (exit status: 134)
````

**Comment by bluca** [comment]
@sigiesec this is a test with curve (and DRAFT) enabled that seems to be receiving an unexpected extra event. It is monitoring ZMQ_EVENT_CONNECTED | ZMQ_EVENT_DISCONNECTED | ZMQ_EVENT_ACCEPTED - is it possible that it is related to recent changes?

**Comment by sigiesec** [comment]
@bluca Hm, I don't think any of the changes relate to that. The changes were only about ZMQ_EVENT_HANDSHAKE_* events.

**Comment by bluca** [comment]
Ok, thought so as well, was worth a check. Thanks!

**Comment by sigiesec** [comment]
This might have the same cause as #2707

**Comment by bluca** [comment]
Haven't seen this failure in a long time, so I'll close this for now
