### ISSUE TITLE
Can't build on Windows

### ISSUE THREAD

**Issue by Framnk** [zeromq/libzmq#2694]
I have several versions of Visual Studio installed but can't seem to get past the build stage.  Following the instructions on the wiki are tough because they mention running configure.bat which doesn't exist.  In any event, if I run build.bat it fails building with VS2013 with unresolved externals, same behavior if I open the solution file and attempt to build that way.  Here's one of the externals it's complaining about:

Error	LNK2019	unresolved external symbol "public: void __thiscall zmq::zap_client_t::send_zap_request(char const *,unsigned int,unsigned char const *,unsigned int)" (?send_zap_request@zap_client_t@zmq@@QAEXPBDIPBEI@Z) referenced in function "private: void __thiscall zmq::curve_server_t::send_zap_request(unsigned char const *)" (?send_zap_request@curve_server_t@zmq@@AAEXPBE@Z)	libzmq	C:\source\libzmq\builds\msvc\vs2013\libzmq\curve_server.obj	1

**Comment by bluca** [comment]
@sigiesec those look like the new source files that were added - they were not listed in the various files under builds/msvc, could you please have a look?

**Comment by sigiesec** [comment]
@bluca Are these builds still needed/supported? Aren't they redundant with the cmake builds?

**Comment by bluca** [comment]
Yes there are users that prefer to use native visual studio projects, so we have to keep them

**Comment by sigiesec** [comment]
I will try to fix that in my next PR. I cannot verify if they work. They are not in the CI.

Can't these builds be deprecated, and removed ? They are of limited use anyway since they don't include the tests.

On the other hand, they impose a significant maintenance burden.

**Comment by bluca** [comment]
I'm afraid not, sorry - as you can see, there's users relying on them. Think for example large projects developed in VS, including dependencies.

We don't add new source files that often, so it shouldn't be too bad.

**Comment by bluca** [comment]
For vs2008 it should be fixed by: https://github.com/zeromq/libzmq/pull/2697

**Comment by bluca** [comment]
@Framnk please pull from git and try again, should work now.
