### ISSUE TITLE
pgm build via cmake doesn't link libzmq with libpgm

### ISSUE THREAD

**Issue by xdmiodz** [zeromq/libzmq#2701]
steps to reproduce on linux

```
mkdir -p build && cd build && cmake -DWITH_OPENPGM=ON .. && make
sudo ldd lib/libzmq.so
```

The listing of linked libraries doesn't have the libpgm.

The build via `./autogen.sh && ./configure --with-pgm` works fine

**Comment by bluca** [comment]
Thanks for the report, fixed in https://github.com/zeromq/libzmq/pull/2700
