### ISSUE TITLE
zeromq.org website delivers invalid HTTPS certificate

### ISSUE THREAD

**Issue by fingolfin** [zeromq/libzmq#2717]
[ Sorry if this is the wrong place to report this, but I could not find any other ]

Trying to go to https://zeromq.org results in warning (resp. causes the browser to refuse a connection, depending on your browser) as the TLS certificate is invalid -- it is for `*.wikidot.com`, so the hostname does not match.

**Comment by bluca** [comment]
Hi,

The hosting is on wikidot so not sure we can do much about it.

Anyway the best place is the mailing list, I've already started a thread last year, so please have a look and reply there if needed:

https://lists.zeromq.org/pipermail/zeromq-dev/2016-December/031274.html

**Comment by KOLANICH** [comment]
zeromq websites, such as {zguide,api,wiki}.zeromq.org lack TLS, which is inacceptible in 2020 (since maliciouse entities called ISPs (see https://habr.com/ru/post/489528/) insert malware into unauthenticated traffic). If it is not possible to have TLS on WikiDot, how about moving them to GitHub?

**Comment by bluca** [comment]
Sure, feel free to send a PR to do so
