### ISSUE TITLE
zmq_socket will spend much time than my expected?

### ISSUE THREAD

**Issue by andwp** [zeromq/libzmq#2720]
# Issue description
zmq_socket(  ZMQ_SUB)  will spend time more than  1 seconds ?

# Environment

* libzmq 4.1.5 ( and apply pull #2362 patch): 
* OS: Win10 64
# Minimal test code / Steps to reproduce the issue
 1、  I wrote a program named MQDTest.exe
```
void  SubReset(char * pLinkInfo)
{
	void *pCtx = zmq_ctx_new();
	
	int nCreateCnt  = 0;
	while(true)
	{
		void *pWatch = zmq_stopwatch_start();
		void *pSck = zmq_socket(pCtx, ZMQ_SUB);
		
		unsigned long nTime = zmq_stopwatch_stop(pWatch);
		int nMillioinSec = nTime / 1e3;
		if(nMillioinSec >= 1000)
		{ 
			assert(nMillioinSec < 1000);
		}
		if(pSck!=nullptr)
		{ 
			int nCnt = zmq_connect(pSck, pLinkInfo);
			assert(nCnt == 0); 
			
			int nLinger = 0; 
			int nRecTimeOut = 10;
			zmq_setsockopt(pSck, ZMQ_RCVTIMEO,&nRecTimeOut, sizeof(int));
			zmq_setsockopt(pSck, ZMQ_LINGER, &nLinger, sizeof(int));
			zmq_msg_t msg;
			zmq_msg_init(&msg);  
			zmq_msg_close(&msg); 
			zmq_close(pSck); 
			pSck = nullptr;
		}else
		{
			nCreateCnt++;
			int nErr=zmq_errno();
			const char* tmp = zmq_strerror(nErr);
			printf("[Error:%d\t msg:%s]Create NULL [%d]times\n", nErr, tmp, nCreateCnt); 
			break;
		}

	}
	
}
```
2、 execute next command, it will run my program 11 instances(or more) in the same time.
```
@echo off
for /L %%i in (0,1,10) do start MQDTest.exe 
 ```

# What's the actual result? (include assertion message & call stack if applicable)
invoke zmq_socket maybe spend time more than 1 seconds(in win2008 maybe 5 seconds, but I have not environment to recurrent it ) 
assert(nMillioinSec < 1000);  will report crash..

# What's the expected result?
I expected that function used time less than 1 seconds.

**Comment by bluca** [comment]
The very first socket created in a context will setup the background threads, various data structures and so on. On Windows it also sets up the internal pipes which are TCP based.
So it's normal.

**Comment by jimklimov** [comment]
Just in case, also note that Windows 10 is reported to have a regression in process-killing time consumption : https://randomascii.wordpress.com/2017/07/09/24-core-cpu-and-i-cant-move-my-mouse/ (a fine read, got me re-thinking Amdahl's law -- how not just sequential parts define the performance baseline, but how having more parallelism ability can actually dig you a deeper hole to drop into, when you stumble on something sequential).
