### ISSUE TITLE
Documentation - zmq_send()

### ISSUE THREAD

**Issue by Tangerino** [zeromq/libzmq#2722]
*Please use this template for reporting suspected bugs or requests for help.*

# Issue description
The documentation states that 
The zmq_send() function shall return zero if successful. Otherwise it shall return -1 and set errno to one of the values defined below.

# Environment

* libzmq version (commit hash if unreleased): 
* OS: 

# Minimal test code / Steps to reproduce the issue

1.  The result code is the number of bytes sent

# What's the actual result? (include assertion message & call stack if applicable)

# What's the expected result?

**Comment by bluca** [comment]
You are probably looking at the 2.1 version API documentation. It's a common mistake as it's the first result in Google. You can see the version in the URL itself.

http://api.zeromq.org/4-0:zmq-send
http://api.zeromq.org/2-1:zmq-send

```
RETURN VALUE
       The zmq_send() function shall return number of bytes in the message if successful. Otherwise it
       shall return -1 and set errno to one of the values defined below.
```
