### ISSUE TITLE
ZMQ_RCVHWM documentation and TCP behaviour

### ISSUE THREAD

**Issue by sigiesec** [zeromq/libzmq#2724]
The effect of exceeding the ZMQ_RCVHWM is unclear for me. The documentation states:

> If this limit has been reached the socket shall enter an exceptional state and depending on the socket type, ØMQ shall take appropriate action such as blocking or dropping sent messages. Refer to the individual socket descriptions in zmq_socket(3) for details on the exact action taken for each socket type.

However, this appears to be simply copied from the documentation of ZMQ_SNDHWM. "blocking or dropping sent messages" is not applicable to receiving messages. This should be fixed.

Furthermore, the zmq_socket documentation does not explain this for each socket type. Here, the focus is on exceeding ZMQ_SNDHWM only. At least this is what I understand from "mute state" (which does not match the term "exceptional state" used on zmq_setsockopt). This should also be fixed.

I can prepare fixes for the inconsistencies mentioned above, however the actual behaviour should also be described, and I don't know what it is for each socket type. Does this also differ between socket types? 

In particular, I am currently interested in the behaviour of a ZMQ_DEALER when its ZMQ_RCVHWM is exceeded. Does it continue receiving messages and drops them?

**Comment by bluca** [comment]
Yes all those things should be fixed.
On receive there is nothing much to be done since it's asynchronous and the engine can't be stalled, so messages are always dropped if the RCVHWM is full IIRC. And I think it's the same for all socket types.
@somdoron did I get this right?

**Comment by bluca** [comment]
> the engine can't be stalled

Or maybe it does and I'm getting confused. Need to go and check again.

**Comment by sigiesec** [comment]
@bluca Oh. If that is true, that would be really bad. Until today, I thought libzmq simply stops reading from the underlying socket when the RCVHWM is reached.

**Comment by bluca** [comment]
Yes that could be the case, I think my memories of the engine code are not fresh enough, need to have another look

**Comment by sigiesec** [comment]
I made an initial fix in 9550ad4 that addresses part of the issues above.

**Comment by sigiesec** [comment]
I had a look at the code handling hwms and I found something weird. when one peers hwms are modified, they are sent to the peer. That's ok. but the peer then uses them in process_pipe_hwm, disregarding its own hwms. Can this be correct?

**Comment by sigiesec** [comment]
I am also somewhat confused by this comment:
https://github.com/zeromq/libzmq/blob/f1c72dc8e5a92c32013a07d8aee68deee70adf8a/src/pipe.cpp#L461
This is apparently not true for an individual instance of pipe_t. I added an assertion for this in https://github.com/sigiesec/libzmq/commit/0adfade8996b9e8d24a242efcee75875ab4c6e27 and it fails in tests where custom HWMs are set. However, I now think that the comment is misleading, as the HWM it refers to is the HWM of the peer's pipe. Is this correct?

**Comment by sigiesec** [comment]
I had a look at test_hwm.cpp:test_defaults. I think this shows the behaviour I expected (socket stops receiving after ZMQ_RCVHWM has been reached, and does not drop messages), but this uses ZMQ_PUSH/ZMQ_PULL sockets and inproc transport rather than ZMQ_ROUTER/ZMQ_DEALER and tcp transport.

**Comment by sigiesec** [comment]
I found at that it is an issue of the tcp transport, in works as expected with ZMQ_ROUTER/ZMQ_DEALER via inproc!

**Comment by sigiesec** [comment]
@bluca @ricnewton  I think the changes made by #1426 are not correct at least for non-inproc transports. The tests in test_setsockopt_hwm are performed using inproc only.

**Comment by bluca** [comment]
It was changed a bit later to make it thread safe here: https://github.com/zeromq/libzmq/pull/2302

**Comment by sigiesec** [comment]
I now think the description of compute_lwm is misleading since https://github.com/zeromq/libzmq/commit/acf0b0e515515e51ad32ba7a2d147ce703579478, where bidirectional pipes were introduced.

**Comment by bluca** [comment]
Sorry I won't have time to look in details in this until next week - but will try to

**Comment by sigiesec** [comment]
@bluca Ok, thanks :)

I am not talking about the thread-safety here, it is the whole calculation that is at least confusing, and requires more documentation. I can set both RCVHWM/SNDHWM on the two sides of a connection independently, right? When I query them again, they also have the values I set. But the pipe's internal values are inconsistent with what I query then. This is not visible via the API. Maybe I find a place to add an assertion that shows the inconsistency.

**Comment by somdoron** [comment]
Actually messages won't be dropped. So when the receive highwatermark is full the zeromq engine will stop picking up messages from the wire, then wire buffer will get full and eventually the sender will stop sending as all the buffers are full, after that the send highwatermark on the sender side will be reached and eventually sender will get blocked (or messages will be dropped). So the behavior of full receive highwater mark is just to stop picking messages from the wire (for tcp transport).

For inproc sockets the size of the underlying queue will be SEND_HIGHTWATERMARK+RECV_HIGHTWATERMARK. After sender will get blocked or drop messages.

**Comment by sigiesec** [comment]
@somdoron Thanks for making this clear :) That's what I originally thought. I will get back to my original test and have a look why it seemed to have  a different behaviour.
I will also try to incorporate this information in the docs.

**Comment by bluca** [comment]
Yeah that makes sense, I confused myself thinking about pubsub as I work mainly with those, sorry
