### ISSUE TITLE
Improve documentation on support level per platform/configuration

### ISSUE THREAD

**Issue by sigiesec** [zeromq/libzmq#2725]
It is somewhat unclear which platforms/configurations are supported to what level by libzmq.

Different levels of support I currently see are:
1. Built & tested on primary CI (i.e. Travis / Appveyor) pre-merge (e.g. Windows ??, VS ??, x64, DEBUG, with DRAFT, CURVE, POLL?? or SELECT??, using cmake)
2. Built & tested on secondary CI (OBS) post-merge only (e.g. Ubuntu trusty, x86-64, with DRAFT, CURVE, using cmake)
3. Built but not tested on either primary or secondary CI (e.g. Linux with GSSAPI)
4. Never built (e.g. Windows VS-native builds)
but known to have active users
5. Never built and unknown if anyone uses it
6. Known not to be supported

For 4 we don't know anything (does it build, does it run) unless someone in the wild does it herself.

**Comment by bluca** [comment]
Should probably go either on the wiki or in the readme (or both)

Travis tests with/without drafts, with/without libsodium, with/without PGM, with/without GSSAPI, with/without docs, with/without IPv6 with autotools and epoll on Linux 64bit (Ubuntu 14.04 currently). It also runs code coverage, valgrind, GCC's address sanitizer, cmake and an Android NDK build cross-compilation build.
Also Travis runs with/without drafts, with/without libsodium and cmake builds on OSX 64bit.

Appveyor does MSVC2015 Cmake builds on Windows 7 32/64 release/debug with/without drafts and with/without libsodium.

Post merge on OBS all builds are with libsodium, GSSAPI and PGM, with epoll and autotools. There are both with/without DRAFT, and are done on a matrix (not full) of the following architectures: i586, x86_64, ppc64el, armv7l, arm64, s390x, on the following distros: Debian, Ubuntu, SUSE, CentOS, RHEL, Fedora for all current supported releases.

We have users on AIX, zOS, Solaris/SunOS/Openindiana, HP-UX and Windows VS but no CI for them.

**Comment by sigiesec** [comment]
Can you say which is the oldest gcc version that needs to be supported?

**Comment by bluca** [comment]
We have users on Solaris 10, which means gcc 3.4. Might be older on some of the other Unices, but unfortunately I don't have access to them (I have a Solaris 10 x86 VM I occasionally compile things on).

Oh the list now can add with/without NORM as well :-) Both in Travis and in OBS.
I've packaged libnorm and I've uploaded it to Debian, it's pending review in the NEW queue: https://ftp-master.debian.org/new/norm_1.5r6%2Bdfsg1-1.html

**Comment by jimklimov** [comment]
Good question - we have a number of distributions with gcc-4.8 and 4.9 building and running just fine. Not sure there are many of practical interest whose tooling is older than 4.x - but it is possible.

**Comment by sigiesec** [comment]
I don't think there is any travis build using select. 
Appveyor, on the other hand, only builds using select, but not with poll.

**Comment by bluca** [comment]
Yes Travis uses only the default polling method. Maybe switching one of the builds around would be good.

**Comment by jimklimov** [comment]
Sounds reasonable to define travis sub-jobs with all explicit polling
methods (of those available on Linux) and same everything else.
