### ISSUE TITLE
tests/CMakeLists.txt uses target_sources but says it works with CMake 2.8.1

### ISSUE THREAD

**Issue by fove-robin** [zeromq/libzmq#2728]
*Please use this template for reporting suspected bugs or requests for help.*

# Issue description

`tests/CMakeLists.txt` uses CMake's `target_sources`, which was only added in CMake 3.1. 
`cmake_minimum_required` is set to 2.8.1 in that file, and 2.8.12 in the project root.

This is causing libzmq project's Jenkins to fail:
https://libzmq.cloudapp.net/job/libzmq/1820/console

Note Jenkins isn't reporting the problem, but it's not exactly working either...

# Environment

* libzmq version (commit hash if unreleased): d5e4319edcc984e4b03f16249378ae9eca67fc01
* OS: all
* CMake: before v3.1

# Minimal test code / Steps to reproduce the issue

1.  kick off CI on Jenkins

# What's the actual result? (include assertion message & call stack if applicable)

```
CMake Error at tests/CMakeLists.txt:184 (target_sources):
  Unknown CMake command "target_sources".
```

# What's the expected result?

Jenkins should build, not just flake out and say "SUCCESS!" (Fixing Jenkins itself is a separate issue I guess...?)

**Comment by bluca** [comment]
Not sure where the Jenkins script actually is unfortunately.

Any idea how to do the same CMake thing without target_sources?

**Comment by bluca** [comment]
Well it looks like those directives are not actually needed - testing without them right now

**Comment by bluca** [comment]
Sigh it looks like it's necessary on Windows, not on *nix

**Comment by bluca** [comment]
I have a different solution - a bit clunkier but it seems to work
