### ISSUE TITLE
push_back and others std:: may throw std::bad_alloc

### ISSUE THREAD

**Issue by msune** [zeromq/libzmq#2739]
# Issue description

(While inspecting the code for #2623 I've observed the following. Posting an issue to see if I've overlooked something first)

Most `std` containers (e.g. `vector`, `list`) may throw `std::bad_alloc` during operations that can potentially allocate memory (e.g. `[]` operators or `push_back()`), if out of memory. This is particularly relevant in high resiliency memory constrained environments.

Since the ZMQ API has C linkage, and there is no apparent protection against such exceptions (nor mechanisms to propagate to the user), user applications simply ABRT.

Some occurrences of `push_back()` as an example:

```
marc@Beluga:~/libzmq/src$ grep push_back * -R
array.hpp:        inline void push_back (T *item_)
array.hpp:            items.push_back (item_);
ctx.cpp:            io_threads.push_back (io_thread);
ctx.cpp:            empty_slots.push_back (i);
ctx.cpp:        empty_slots.push_back (slot);
ctx.cpp:    sockets.push_back (s);
ctx.cpp:    empty_slots.push_back (tid);
devpoll.cpp:    pending_list.push_back (fd_);
dist.cpp:        pipes.push_back (pipe_);
dist.cpp:        pipes.push_back (pipe_);
epoll.cpp:    retired.push_back (pe);
fq.cpp:    pipes.push_back (pipe_);
ipc_listener.cpp:                tmp_path.push_back('/');
kqueue.cpp:    retired.push_back (pe);
lb.cpp:    pipes.push_back (pipe_);
mailbox_safe.cpp:    signalers.push_back(signaler);
options.cpp:                    tcp_accept_filters.push_back (mask);
poll.cpp:    pollset.push_back (pfd);
pollset.cpp:    retired.push_back (pe);
radio.cpp:        udp_pipes.push_back (pipe_);
select.cpp:    family_entry.fd_entries.push_back (fd_entry);
select.cpp:    fd_entries.push_back (fd_entry);
socket_base.cpp:    pipes.push_back (pipe_);
socket_poller.cpp:    items.push_back (item);
socket_poller.cpp:    items.push_back (item);
xpub.cpp:                pending_pipes.push_back (pipe_);
xpub.cpp:                pending_data.push_back (blob_t (data, size));
xpub.cpp:                pending_metadata.push_back (metadata);
xpub.cpp:                pending_flags.push_back (0);
xpub.cpp:                    pending_data.push_back (blob_t(data, size));
xpub.cpp:                    pending_metadata.push_back (metadata);
xpub.cpp:                    pending_flags.push_back (0);
xpub.cpp:            pending_data.push_back (blob_t (data, size));
xpub.cpp:            pending_metadata.push_back (metadata);
xpub.cpp:            pending_flags.push_back (sub.flags ());
xpub.cpp:        self->pending_data.push_back (unsub);
xpub.cpp:        self->pending_metadata.push_back (NULL);
xpub.cpp:        self->pending_flags.push_back (0);
xpub.cpp:            self->pending_pipes.push_back (NULL);
```

Thoughts?

**Comment by bluca** [comment]
There are many operations that allocate memory, the first example being receiving messages. It's policy to assert on OOM in these cases as it's simply not possible to guarantee consitent and reliable network protocol functionality if random messages can go lost.

Simpler and non-fatal cases (eg: getting or setting a socket option) might be made more resilient for example, but I'm not sure how much different it would make.

**Comment by msune** [comment]
Well... the problem (one of) is that in OOM langue, like C++, there are ways to catch and react to that, even if it is just to cleanly bail out (because there is _really_ nothing else to do).

However, since the ZMQ has a C API (which certainly is the right way to go IMO), but the core is in C++ and no parachutes (`catch{}`) are in place, it is simply impossible for the application to do absolutely anything* (e.g. for cleaning up) .

Btw, I don't quite get why you say there is the need to allocate on a per-message on RX. Pools (pre-allocation) are a known strategy to avoid this, and are also in general more efficient. I would have to revise the RX path in depth to understand how is the implementation nowadays. But, at least from the external memory behaviour, I thought ZMQ does already some pooling (even if that's a side effect of using `std` containers)

*Technically _there might be_ ways to do it, handling signals and compilar destructors, I guess, but way too complicated for a general purpose library IMO.

**Comment by bluca** [comment]
Yes the engine uses a buffer (IIRC 8KB for payloads), but still - on high volume traffic, that doesn't last long. It's 240 messages of the minimum size (34 bytes). You can find the code in the stream_engine and v2_decoder.

Still, the point is, it's not an accident, it's a very precise design choice driven by experience. I think Pieter wrote a few blog posts about it. It might sound counter-intuitive, but it's better this way.

**Comment by msune** [comment]
I don't quite understand how to unilaterally terminating a program can be any better than returning an error and let the application react (I can tell you for sure we have use cases for that).

But, since you point out it is intentional - which, I doubt, specially since Martin has posts explaining the issues with exceptions in ZMQ -, feel free to close the issue :relaxed:

**Comment by sigiesec** [comment]
I have the impression that two things are mixed up in the thread here.

I think the statement "it's not an accident but a design choice" refers to the dynamic allocation, right, @bluca?

The problem with signalling memory allocation errors to the application is that some of them occur asynchronously in the I/O thread (right?). It is not possible to signal them using some return code. But maybe one could signal them using a monitoring event, maybe only when requested by the application.
