### ISSUE TITLE
error install

### ISSUE THREAD

**Issue by Rafoula** [zeromq/libzmq#2754]
hello,
I have Ubuntu 12.04 and I am trying to install ZeroMQ.
I follow theses commands:

>git clone https://github.com/zeromq/libzmq
>./autogen.sh && ./configure && make -j 4
>make check && make install && sudo ldconfig

But in the last command I have error like this:

>make[2]: *** [install-man3] Error 1
>make[2]: Leaving directory `/home/rafoula/libzmq/doc'
>make[1]: *** [install-am] Error 2
>make[1]: Leaving directory `/home/rafoula/libzmq/doc'
>make: *** [install-recursive] Error 1

**Comment by bluca** [comment]
You need sudo to make install in the default prefix.

Use the pre built packages instead so you don't have to worry about these things: https://software.opensuse.org/download.html?project=network%3Amessaging%3Azeromq%3Arelease-stable&package=libzmq3-dev

**Comment by Rafoula** [comment]
@bluca I follow these commands :+1: 
"
For xUbuntu 12.04 run the following:

sudo sh -c "echo 'deb https://download.opensuse.org/repositories/network:/messaging:/zeromq:/release-stable/xUbuntu_12.04/ /' > /etc/apt/sources.list.d/libzmq3-dev.list"
sudo apt-get update
sudo apt-get install libzmq3-dev

You can add the repository key to apt. Keep in mind that the owner of the key may distribute updates, packages and repositories that your system will trust (more information). To add the key, run:

wget -nv https://download.opensuse.org/repositories/network:messaging:zeromq:release-stable/xUbuntu_12.04/Release.key -O Release.key
sudo apt-key add - < Release.key
sudo apt-get update
"
But I have the same error

**Comment by bluca** [comment]
Once the packages are installed you are done, you don't need to build manually from git anymore

**Comment by Rafoula** [comment]
ok,thanks a lot!!

**Comment by bluca** [comment]
No problem
