### ISSUE TITLE
Unoptimal Copying of fd_set Structure in Windows

### ISSUE THREAD

**Issue by apirila** [zeromq/libzmq#2758]
# Issue description

If FD_SETSIZE is large (I have 16384) copying of fd_set is done in non-optimal fashion. In Windows fd_set if defined as follows:

```c
typedef struct fd_set {
        u_int fd_count;               /* how many are SET? */
        SOCKET  fd_array[FD_SETSIZE];   /* an array of SOCKETs */
} fd_set;
```
(from WinSock2.h)

If we want to copy the structure, we need only to copy used elements in the fd_array, not the whole structure. 

I've modified select.cpp to code like this:
```c
zmq::select_t::fds_set_t::fds_set_t (const fds_set_t& other_)
{
#if defined ZMQ_HAVE_WINDOWS
  memcpy (&read, &other_.read, sizeof other_.read.fd_count + sizeof SOCKET * other_.read.fd_count);
  memcpy (&write, &other_.write, sizeof other_.write.fd_count + sizeof SOCKET * other_.write.fd_count);
  memcpy (&error, &other_.error, sizeof other_.error.fd_count + sizeof SOCKET * other_.error.fd_count);
#else
  memcpy(&read, &other_.read, sizeof other_.read);
  memcpy(&write, &other_.write, sizeof other_.write);
  memcpy(&error, &other_.error, sizeof other_.error);
#endif
}
```

I was able to get considerable reduction of latency with local_lat and remote_lat programs. Latency dropped from ~200us to less than 100us.

This structure of fd_set in Windows is publicly documented: https://msdn.microsoft.com/en-us/library/windows/desktop/ms737873(v=vs.85).aspx

# Environment

* libzmq 4.2.2
* OS: Windows

**Comment by bbdb68** [comment]
nice catch ! I used your code  in a small zmq_poller_wait bench code I have, and I a good 30% perf increase!

:+1:

**Comment by bbdb68** [comment]
will you send a PR with the change ?

**Comment by apirila** [comment]
Hi, 
It seems that similar fix is already on the master.
https://github.com/zeromq/libzmq/blob/master/src/select.cpp#L422

**Comment by bbdb68** [comment]
fine !
