### ISSUE TITLE
libzmq >v4.1.x causes mongrel2 crashes

### ISSUE THREAD

**Issue by lacombar** [zeromq/libzmq#2760]
# Issue description
Sometimes during the development phase between v4.1.0 and v4.2.0 a bug was introduced which ultimately triggers a crash of `mongrel2`. The crash is identified by libc as a double free / corruption. Reverting to v4.1.6 fixes the issue. I bisected the problem between 
e50a987650b217ef6d808659beaa4cf9d68f6dc3 and 91e121c9d36e87811e1c03ac8eb4347b2ef0aace, however, due to instability of `libzmq` in that timeframe, I cannot provide an exact faulty commit.

# Environment
* libzmq version (commit hash if unreleased): > v4.1.x
* OS: ubuntu 12.04 to 16.06

# Minimal test code / Steps to reproduce the issue
1. build `mongrel2' with the latest zmq
2. run a trivial configuration
3. connect multiple client at the same time (eg. `telnet 127.0.0.1 8116 & telnet 127.0.0.1 8116 & telnet 127.0.0.1 8116 &`)
4. wait for `mongrel2` to kill the connection

# What's the actual result? (include assertion message & call stack if applicable)
`mongrel2` crash.

# What's the expected result?
`mongrel2` does not crash.

**Comment by bluca** [comment]
Can you provide a way to reproduce without a third party software?

**Comment by lacombar** [comment]
`mongrel2` is open-source, there shouldn't be any problem to reproduce.

**Comment by rodgert** [comment]
Not really a question of license, it's being able to reproduce the issue in
isolation without the 3rd party dependency. Greatly aids in debugging these
issues.

**Comment by lacombar** [comment]
I'm open to assist, but can't devote the time to provide a reduced test case.
