### ISSUE TITLE
Abort on TrueOS (FreeBSD 12) in stream_engine

### ISSUE THREAD

**Issue by hxw** [zeromq/libzmq#2761]
# Issue description

I am seeing an error on close: 
```
Connection reset by peer (src/stream_engine.cpp:157)
Abort trap
```

# Environment

* libzmq 4.2.2
* OS: TrueOS (FreeBSD 12)

# Problem code

Appears to be the use of a FreeBSD specific code to ignore that specific error that does not actually get included

## Locating the code
```
# grep -nHr __FreeBSD_kernel__ work/zeromq-4.2.2/src/
work/zeromq-4.2.2/src/stream_engine.cpp:156:#ifdef __FreeBSD_kernel__
work/zeromq-4.2.2/src/thread.cpp:149:#ifdef __FreeBSD_kernel__
```
The symbol: `__FreeBSD_kernel__` is only defined if sys/param.h is included.
Since sys/param.h is not generally included by other source files,
I suggest changing both occurences of `__FreeBSD_kernel__` to `__FreeBSD__`
would be the simplest option.

Here is a diff:  [zmq4.diff.txt](https://github.com/zeromq/libzmq/files/1343263/zmq4.diff.txt) to change the two files.

**Comment by bluca** [comment]
Hi,

```__FreeBSD_kernel__``` is the definition exported by Debian's kFreeBSD port, so it looks like the right solution is to check for either of them: ```#if defined(__FreeBSD_kernel__) || defined (__FreeBSD__)```

Could you please test if that works, and if so, send a pull request? Thanks!

**Comment by hxw** [comment]
I have made the change on my system, and will run for a couple of days; then make pull request.

**Comment by bluca** [comment]
Great, thanks

**Comment by hxw** [comment]
I have over 48hr of run time on my program with this patch, so I sent it as a pull request

**Comment by bluca** [comment]
Merged, thank you very much!
