### ISSUE TITLE
zmq subscriber stops receiving data at a interface event.

### ISSUE THREAD

**Issue by jonakarl** [zeromq/libzmq#2763]
# Issue description
We are experiencing a reoccurring (1-2 hours interval) "hang" of a
subscriber where it stops receiving data over the socket and thereby
"hang" on the recv() call.
The hangs are synchronized between all subscribers regardless when they
first subscribed to the socket.

When doing a tcpdump of the socket we can see that at there is a brief
interface (a bridge actually) problem (the subscriber ip do a arp
request for the publisher ip). After this the subscriber does not
receive any more data.

However if connecting a new subscriber to the same socket/ip after it
got stale, data is received on the socket for the new subscriber but not
for the old subscribers that are already stuck.
Neither the publisher or the subscriber throws any exceptions or show
any other signs of problems (memory leaks etc).

We verified this by using pollers that poll for data on the socket at
the subscriber side.
If we have not received any data for a timeperiod (default 60 seconds)
we recreate the zmq Context. This works every time but at the cost of
dataloss.
We have further reproduced the same error with a c++ subscriber to
eliminate the possibility of bug in the python zmq binding.

The cause of the interface problem is unknown (could be a docker bug) but the effects are not handled by zmq. We cannot manually reproduce the issue whether we drop interfaces, pull them down and up again, flush conntrack, arp tables, add firewall rules or the like. 

# Environment
* libzmq version : libzmq-4.2.1
* OS:  Debian stretch

We have timeframed the error to have started after a upgrade to Debian
stretch as the same code for both subscriber and publisher worked in
debian jessie. However, we are not sure if this is just a coincidence or
due to a change in the underlying libraries.

The subscriber runs in a docker container and the publisher runs in the
host but both run in the same network namespace.
We are using the packaged version of libzmq and pyzmq in Debian stretch:
libzmq-4.2.1
pyzmq-16.0.2
Python-2.7.13 (default, Jan 19 2017, 14:48:08)
[GCC 6.3.0 20170118]

Before the error we where using Debian Jessie with these (packaged)
library versions:
libzmq-4.0.5
pyzmq-14.4.0
Python-2.7.9 (default, Jun 29 2016, 13:08:31)
[GCC 4.9.2]

# Minimal test code / Steps to reproduce the issue
The subscriber code with the workaround can be found here:
https://github.com/MONROE-PROJECT/Experiments/blob/master/metadata-subscriber/files/metadata_subscriber.py

Old code that hangs forever on recv:
https://github.com/MONROE-PROJECT/Experiments/blob/4c2d97f1310c85b38f6c854c3cb9b198112d72c6/metadata-subscriber/files/metadata_subscriber.py
(This code is basically the python example code for a subscriber) 

Publisher:
https://github.com/MONROE-PROJECT/data-exporter/blob/master/metadata_writer_zeromq.c

# What's the actual result? (include assertion message & call stack if applicable)
The subscriber subscriber stops receiving data over the socket. However if connecting a new subscriber to the same socket/ip after it got stale, data is received on the socket for the new subscriber but not for the old subscribers that are already stuck. Neither the publisher or the subscriber throws any exceptions or show any other signs of problems (memory leaks etc).

# What's the expected result?
zmq recovers from the interface disruption and continue to deliver data to the subscriber.

**Comment by bluca** [comment]
> The cause of the interface problem is unknown (could be a docker bug) but the effects are not handled by zmq. We cannot manually reproduce the issue whether we drop interfaces, pull them down and up again, flush conntrack, arp tables, add firewall rules or the like.

This bit here is quite suspicious...

Have you tried running the application via strace and checking if there are reads/writes happening from the kernel, and if the epolls return something?

In the end it's TCP sockets - if data is not delivered, the only thing you can do is tweak the socket timeout so that the connections are tore down and recreated automatically

**Comment by jonakarl** [comment]
We do not have a ton of experience with zmq but we used strace on the subscriber and as far as we could tell it is just waiting for data on "a socket" (like normal) but noting arrived (ie epoll did not return anything).

I do not think it would help to change the socket timeout as the socket did not timeout in at least 6 hours , or at least the subscriber did not receive any data for 6 hours in a row (this is how we noticed the problem in the first place).

**Comment by bluca** [comment]
Yes, the default TCP timeout on Linux is very long, hours IIRC.

Maybe give a try to the ZMQ_HEARTBEAT* socket options - they can enable a protocol-level ping-pong, that can help detect dead connections.

More in general, if the socket is still there but it does not receive any data from the kernel, I'm not sure we can do anything - it sounds like a problem of the underlying system. The only thing, as I mentioned, is trying to detect it.

**Comment by bluca** [comment]
So on Debian 9 the default TCP keepalive is 2 hours:

```
# sysctl net.ipv4.tcp_keepalive_time 
net.ipv4.tcp_keepalive_time = 7200
```

So for 2 hours after the last data packet has been received, the socket will simply be idle. After that, the socket will be closed and so the library will notice it and restart it.

I do not know why the kernel is not simply re-establishing the TCP connection after the interface comes up again.

**Comment by bluca** [comment]
There are also socket options to override the defaults, check ZMQ_TCP_KEEPALIVE*

**Comment by jonakarl** [comment]
I am unsure about what is happening but it is connected to the bridge.

So the setup we have is that the publisher is running in host namespace and connected to one end of the bridge (docker0) and the subscriber is connected to "the other end" of the bridge in a seperate namespace.

When both the publisher and the  subscriber connects to docker0 (ie the same end of the bridge) it works and there is no issues. However on "the other end" of the bridge (ie on the other namespace) we at some times have a event on the bridge that triggers a new arp request for the docker0 ip.
During this arp request the zmq socket sends a RST and after that the subscriber does not recive anything more. As said before; reconnecting or starting a new subscriber after the arp request works and will receive data. A subscriber that is connected on the same side of the bridge as the publisher also recieves data (but on this end there has probably never been the arp and RST packets sent).

We replaced the bridge with a veth pair and now we do not experience the problems anymore, most likely as the veth pair do not trigger the arp and following RST of the tcp connection.
Of course in all situations this workaround is not applicable.

**Comment by asddsa1137** [comment]
Also experiencing this issue on libzmq 4.2.3 (using C++). 
Noticed that then this issue occurs we can see quite a lot of data in tcp socket queue (Recv-Q on SUB side and Send-Q on PUB side in ss output). TCP connections on both sides are in ESTABLISHED state.

**Comment by zwn** [comment]
> Maybe give a try to the ZMQ_HEARTBEAT* socket options - they can enable a protocol-level ping-pong, that can help detect dead connections.

We did try that and I am happy to report - for all the poor souls coming here as we were - it fixed the problem! We run two listener processes on the same machine - one with and one without ZMQ_HEARTBEAT_IVL set. The one with the hearbeat option set keeps running while the other one does not receive anything (it takes about a day for this issue to reproduce in our setup).

In our setup the publisher runs inside a podman container and the subscriber runs on a different linux machine but I not sure if that has any significance.
