### ISSUE TITLE
Issue with binding to same address after closing the TCP socket.

### ISSUE THREAD

**Issue by jay11ca39** [zeromq/libzmq#2772]
# Issue description
Unable to bind to the same TCP address even after closing the socket.

# Environment
* libzmq library: Debian 9.0
* OS: Linux [Ubuntu 14.04]
   
# test code to reproduce the issue
```
    zmq::socket_t *publisher = new zmq::socket_t(context, ZMQ_PUB);
    publisher->bind ("tcp://127.0.0.1:5555");  //can use any address to reproduce  
    publisher->close();  //bind to same address 
    publisher->bind ("tcp://127.0.0.1:5555"); //try to bind to same address 
    [It is failing here with error: 48 address already in use]
```

# What's the actual result?
Should be able to use the same TCP address as Socket Close API is being called.

# What's the expected result?
Getting exception: Address already in use.

Thanks in advance.

**Comment by bluca** [comment]
The close is asynchronous, so it might not have happened yet.

Use zmq_socket_monitor and wait for ZMQ_EVENT_CLOSED before re-binding if you need to do that often in rapid sequences.

**Comment by jay11ca39** [comment]
Hi @bluca ,
Thanks for your last reply.
Is it the same case with "Connect" API also. 
For example: If I created a subscriber Socket then connect it to particular ip port and then close it again try to connect it to same ip and port?

**Comment by bluca** [comment]
Yes, connect is asynchronous too

**Comment by bluca** [comment]
http://api.zeromq.org/4-2:zmq-connect

```
for most transports and socket types the connection is not performed immediately but as needed by ØMQ. 
```

**Comment by jay11ca39** [comment]
Hi bluca,
Thanks.
I have tried following:
1. Monitor the network socket.
2. Stop the socket and wait for EVENT_CLOSED from socket.
3. then call the start again.

Start is sync as per my understanding  i.e. bind and connect.. And for close we have to monitor socket event.

**Comment by bluca** [comment]
zmq_connect is asynchronous. zmq_bind is synchronous at the moment, but if you have hard requirements to double bind you should use the events API as well.

ZMQ_EVENT_LISTENING for bind and ZMQ_EVENT_CONNECTED for connect:

http://api.zeromq.org/4-2:zmq-socket-monitor

> I also have one more query regarding recv API .. It is blocking call. There is one flag: ZMQ_DONTWAIT for non blocking call but is it possible to set a timeout for that?

The blocking call can set a timeout, yes, see ZMQ_RCVTIMEO in http://api.zeromq.org/4-2:zmq-setsockopt

**Comment by jay11ca39** [comment]
@bluca ,
Thanks I got your points. I will close this issue.
