### ISSUE TITLE
Is polling possible on REQ REP sockets? if not what could be a solution?

### ISSUE THREAD

**Issue by Davar1990** [zeromq/libzmq#2774]
I have two parallel threads running. Thread 1 captures frames from camera and sends it to thread 2 for corner detection. I want thread 1 to display real time frames and once it receives a request from thread 2, sends the most recent frame to thread 2 for corner detection. I used REQ socket for thread 1 and REP socket for thread 2. So I send one frame to thread 2 and use polling on thread 1 to not wait for a reply and display the real time frames until the corner detection on thread 2 is done and a request for new frame is sent to thread 1. So the idea is keep displaying real time frames and once you receive a request from thread 2, send a new frame to it. I used the following code:

```
#include<iostream>
#include<zhelpers.hpp>
#include<thread>

zmq::context_t context(1);
zmq::socket_t master(context, ZMQ_REQ);          // for thread 1
zmq::socket_t slave(context, ZMQ_REP);              // for thread 2

void detectCorners(){
 
    slave.connect("inproc://frame");

    while(true){

        std::string frameString = s_recv(slave);

	... do corner detection
	
	s_send(slave, "ok");                          // request for new frame
     }

}

int main(){

std::thread t2(detectCorners);			// second thread for corner detection

master.bind("inproc://frame");

... get one frame, and make it ready for sending

zmq::pollitem_t items[] = { {master, 0, ZMQ_POLLIN, 0} };
int numOfPollingSockets = 1;

s_send(master, frameString);

    while(true){
    
         ... capture frame from camera, serialize and make it ready for sending
    
         zmq::poll( items, numOfPollingSockets, -1);        

         if ( items[0].revents & ZMQ_POLLIN ){
              s_recv(master);         // receive the request
              s_send(master, frameString);
         }

         cv::imshow("window", frame);
         cv::waitkey(1);

     }

return 0;
}
```

The problem is that polling seems not to be the solution in this scenario (maybe not on REQ sockets).  The code constantly falls into the polling " if " statement, hence it reaches the "s_recv()" line and waits a long time until it receives something from thread 2 to move on and display the frames. In fact the frames are displayed with long delay (as long as the corner detection time). Just for the record, I don't want use anymore than two threads to get around this problem. Thanks.

# Environment
* libzmq version 4.1.4
* OS: Ubuntu 16.04

**Comment by bluca** [comment]
Polling works fine on REQ and REP.

Are you creating and using sockets in different threads?

**Comment by Davar1990** [comment]
I e

**Comment by Davar1990** [comment]
Thanks for replying back. Yes, I use sockets in different threads. I just updated the code above so you can see everything.

**Comment by bluca** [comment]
A socket must be created, used and closed from a single thread. Otherwise all kind of race conditions might happen.

**Comment by Davar1990** [comment]
I actually didn't know that so I'll keep that in mind from now on. But the problem got fixed by the changing the fourth argument value of "zmq::poll( items, numOfPollingSockets, -1);" from -1 to 0 or any other number higher depending on the need for timeout. Thanks again for your fantastic library.

**Comment by Davar1990** [comment]
Just for the record, did you mean all sockets must be created from a single thread or each individual socket must be created separately in the thread associated with them?

**Comment by bluca** [comment]
Great, thanks for confirming, closing now then.

> Just for the record, did you mean all sockets must be created from a single thread or each individual socket must be created separately in the thread associated with them?

The second one - sockets are not thread safe
