### ISSUE TITLE
libzmq crashes in load test. 

### ISSUE THREAD

**Issue by kukuruzca** [zeromq/libzmq#2776]
# Issue description
libzmq.dll crashes in  load test. 

Server side, implements Router-Dealer template. In some load test, client sends many requests in many threads to server. Often server catch assert in libzmq.dll in msg.cpp in **size_t zmq::msg_t::size ()** ( zmq_assert (check ());)
The error is floating.

After debugging found that when it fails 
u.base.type: 0
u.base.routing_id: 0
u.base.flags: 0
u.base.group : 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0
u.base.unused : 0x50 0xC9 0xBA 0x32 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0

What could it be? How to find the error?

# Environment
* libzmq version : 4.2.2 Release. Compiled with MSVC 2015 with static runtime (/MT)
* OS: Windows Server 2008 R2 x64

**Comment by bluca** [comment]
Are you using a socket from multiple thread?
Are you using a message from multiple threads, or closing a message after a successful send, or deallocating it in any other way?

u.base.type = 0 means the message has been invalidated by your application somehow

**Comment by kukuruzca** [comment]
On server, every thread uses own independent REP socket,  that are connected to backend socket of Router-Dealer.  And all sockets, in threads, waiting for Receive Message, do some work , sends replay back(creates new message), and once again waits for receive new message.

**Comment by bluca** [comment]
What about the messages? Are they been closed correctly?

If you upload to Gist/Pastebin/etc your code or even better a minimal fully contained example that reproduces the problem someone can take a look.

**Comment by kukuruzca** [comment]
I use clrzmq4 4.1.0.21 wrapper for c#. 
And the replay method is

_protected ZError Reply(Reply reply, ZSocket socket)
        {
            ZError error;
            var sendError = reply.Error ?? "";
            using (ZMessage zMessage = new ZMessage())
            {
                zMessage.Add(new ZFrame(GetEncodedString(sendError))); // this means that there are no error and client can get return result
                if (string.IsNullOrWhiteSpace(sendError))
                {
                    ProcessReturnValue(reply.ReturnValue, zMessage);
                }
                zMessage.Add(new ZFrame("")); // send one last empty frame
                socket.SendMessage(zMessage, out error);
                if (error != null)
                {
                    return error;
                }
                ZmessageToLog(zMessage, ZActionType.Send);
                zMessage.Clear();
            }
            return ZError.None;
        }_

So after exit of using, automatic will call dispose, i think.

**Comment by bluca** [comment]
Sorry, I don't know much about clrzmq. Please re-open this issue on its repository:

https://github.com/zeromq/clrzmq4

**Comment by sigiesec** [comment]
As bluca said, please create a self-contained example, either using clrzmq4 (and then open that as an issue in the clrzmq4 repo) or using libzmq itself, and reopen here.
