### ISSUE TITLE
ZMQ_STREAM socket lose first byte on recv after connecting to remote non-zmq server.

### ISSUE THREAD

**Issue by chao83** [zeromq/libzmq#2777]
*Please use this template for reporting suspected bugs or requests for help.*

# Issue description
Hello, I'm writing a simple http proxy (handles CONNECT request only) for ftp servers.
It uses 2 STREAM sockets, one for clients, the other for servers.
In ftp passive mode, sometimes the file data is not complete, with the first byte missing.
for example: a.txt has 6 bytes, "123abc", sometimes I receive "23abc";
I have read API docs and checked zmq socket options and found nothing relative.
Is it a bug or am I missing something ?

# Environment

* libzmq version (commit hash if unreleased): 4.1.5, 4.2.2
* OS: rhel5.5, 32bit, in virtualbox.

# Minimal test code / Steps to reproduce the issue

1.  here is my code to recv from server:
```cpp
void HttpProxy::OnServer(zmq::socket_t &server, zmq::socket_t &clients)
{
	bool more = true;
	std::string addr(SRecv(server, more));
	std::string data(SRecv(server, more));

	auto pos = ser_rec_.find(addr);
	assert(pos != ser_rec_.end());

	auto &ssn = *pos->second;  // client-server tcp pair.
	if (!data.empty()) {
		LOG_DEBUG() << AddrName(ssn.client_) << kO << LogMsg(data);
		SSend(clients, ssn.client_, yes_more);
		SSend(clients, data, yes_more);
	} else {
		if (!ssn.has_server_) {
			ssn.has_server_ = true;
			SSend(clients, ssn.client_, yes_more);
			SSend(clients, "HTTP/1.0 200 Connection established\r\n\r\n", yes_more);
			LOG_DEBUG() << AddrName(ssn.client_) << " CONNECTED.";
		} else {
			LOG_DEBUG() << AddrName(ssn.client_) << " CLOSED by server.";
			SSend(clients, ssn.client_, yes_more);
			SSend(clients, data, yes_more);
			cli_rec_.erase(ssn.client_);
			ser_rec_.erase(pos);
		}
	}
}
```
# What's the actual result? (include assertion message & call stack if applicable)

sometimes, the first byte of file content is lost.

# What's the expected result?

complete file content.

**Comment by chao83** [comment]
* some log here: 


[2017-10-13 18:12:22.253045](1) 006B8B4567 ---> [8]TYPE A

[2017-10-13 18:12:22.254706](1) 006B8B4567 <--- [30]200 Switching to ASCII mode.

[2017-10-13 18:12:22.255734](1) 006B8B4567 ---> [6]PASV

[2017-10-13 18:12:22.257119](1) 006B8B4567 <--- [50]227 Entering Passive Mode (192,168,2,220,180,16)

[2017-10-13 18:12:22.258260](1) 006B8B4567 ---> [12]RETR a.txt

[2017-10-13 18:12:22.259594](1) 006B8B457D ---> [67]CONNECT 192.168.2.220:46096 HTTP/1.1
Host: 192.168.2.220:46096


[2017-10-13 18:12:22.261298](1) 006B8B457D CONNECTED.
[2017-10-13 18:12:22.263077](1) 006B8B457D <--- [6]123abc
[2017-10-13 18:12:22.263119](1) 006B8B457D CLOSED by server.
[2017-10-13 18:12:22.263927](1) 006B8B4567 <--- [86]150 Opening BINARY mode data connection for a.txt (6 bytes).
226 Transfer complete.

[2017-10-13 18:12:22.856155](1) 006B8B4567 ---> [8]TYPE A

[2017-10-13 18:12:22.857338](1) 006B8B4567 <--- [30]200 Switching to ASCII mode.

[2017-10-13 18:12:22.858033](1) 006B8B4567 ---> [6]PASV

[2017-10-13 18:12:22.859301](1) 006B8B4567 <--- [50]227 Entering Passive Mode (192,168,2,220,140,66)

[2017-10-13 18:12:22.860394](1) 006B8B4567 ---> [12]RETR a.txt

[2017-10-13 18:12:22.861769](1) 006B8B457E ---> [67]CONNECT 192.168.2.220:35906 HTTP/1.1
Host: 192.168.2.220:35906


[2017-10-13 18:12:22.865200](1) 006B8B4567 <--- [62]150 Opening BINARY mode data connection for a.txt (6 bytes).

[2017-10-13 18:12:22.865263](1) 006B8B457E CONNECTED.
[2017-10-13 18:12:22.865283](1) 006B8B457E <--- [5]23abc
[2017-10-13 18:12:22.865300](1) 006B8B457E CLOSED by server.
[2017-10-13 18:12:22.866983](1) 006B8B4567 <--- [24]226 Transfer complete.

**Comment by bluca** [comment]
Could you please upload a full, self-contained example that reproduces the problem?

**Comment by chao83** [comment]
Uploaded demo source code.
The code is modified to reduce extra dependencies, and
it only work with ip servers, like ftp://192.168.1.2/, domain name will not work.
[http_proxy_demo.tar.gz](https://github.com/zeromq/libzmq/files/1382567/http_proxy_demo.tar.gz)

**Comment by bluca** [comment]
Could you please explain exactly how to use that example?

**Comment by chao83** [comment]
To build the code on linux, you need cmake and modern C++ compiler, I'm using g++ 6.2.
The output file is named http_proxy. I could provide it but I'm not sure if it runs on your OS.
It will listen on port 3128 (same as squid, could be changed in main.cpp) by default,
then we can use it as an http proxy in ftp clients, I used WinSCP (v5.0.5) in my tests,
ftp server must be in ip form as described in my previous comment.
some log was written to stderr.
to stop http_proxy, just press Ctrl-C.

**Comment by bluca** [comment]
> then we can use it as an http proxy in ftp clients, I used WinSCP (v5.0.5) in my tests,
ftp server must be in ip form as described in my previous comment.

Sorry I should have been more precise - this part is what I was referring to, exactly what commands should be used on Linux to reproduce?

**Comment by chao83** [comment]
On linux, just start http_proxy is enough.
I run WinSCP on windows, and set proxy in ftp connection settings, use that linux host's ip and port as proxy.
![default](https://user-images.githubusercontent.com/4090147/32216001-ae5a0672-be5e-11e7-86fa-c2886c430ec2.png)

**Comment by chao83** [comment]
I've added hostname resolve support, but it depends on boost code.
If you need that, I can upload the new version, which do not require server in ip form.

**Comment by bluca** [comment]
I'm not familiar with ftp client or servers either, so that's why I'm asking which commands to use.

**Comment by chao83** [comment]
winscp is a windows program with GUI. 
If you do not have windows, I can try some linux ftp clients later.

**Comment by bluca** [comment]
Thanks, I do not have Windows.

**Comment by chao83** [comment]
I tried FileZilla client on Ubuntu (installed in virtualbox), and have the same issue, without the proxy.
Maybe it is not an zmq issue, but a bug in our ftp server, I'll do some more check.

**Comment by chao83** [comment]
The problem is gone when I run my program on a real linux PC, not in virtualbox.
So I think it was caused by virtualbox, but not a zmq issue, zmq is good.
