### ISSUE TITLE
-DZMQ_STATIC required externally when using a static libzmq in mingw, is not set in pkg-config

### ISSUE THREAD

**Issue by youRFate** [zeromq/libzmq#2788]
# Issue description
for using a static libzmq with mingw `-DZMQ_STATIC` is required by some defines in `zmq.h`, but it is not set by pkg-config. However, this can't be fixed right now, as there is no Cflags.private in pkg-config, see https://bugs.freedesktop.org/show_bug.cgi?id=47996

# Environment

* libzmq version (commit hash if unreleased): 4.2.2
* OS: linux/any

**Comment by bluca** [comment]
Thanks - given that ticket is 4 years old I doubt pkg-config will ever implement cflags.private, unfortunately, so given you have documented it in INSTALL I'll close this issue
