### ISSUE TITLE
zmq_atomic_counter_value doc/html

### ISSUE THREAD

**Issue by aeiouzy** [zeromq/libzmq#2789]
Name
zmq_atomic_counter_value - return value of atomic counter

Return value
The zmq_atomic_counter_value() function returns the new atomic counter if successful. Otherwise it returns NULL.       //here is different

**Comment by bluca** [comment]
Could you please clarify what you mean?

**Comment by aeiouzy** [comment]
This function is the return value, but the document is interpreted as the return object
