### ISSUE TITLE
msys2 and configure problems (windows)

### ISSUE THREAD

**Issue by lvecsey** [zeromq/libzmq#2802]
I am using msys2 and I noticed I had to adjust configure.ac before running ./autogen.sh to get a working configure script. Basically the AC_CONFIG_FILES statement currently spans multiple lines and there was some kind of whitespace character in there that was causing a problem.

I fixed it by adjusting AC_CONFIG_FILES to be all on one line. I will try to edit this post and put in the exact error that came out (when running ./autogen.sh) when I get a chance, on this platform.

I am using msys2 (msys2-i686-20161025.exe) on a Windows 10 machine, 32bit mode.

The commit hash is cb266ee073f681b718efe1e54cc18051c6310b0b

Finally, once I got a built configure script I had to manually edit it in a half dozen places because of a second issue. There were some "else" and "fi" statements with nothing inbetween, just a blank line or two. I was able to add statements within such as 'echo testing..', so at least some kind of command would run within the else block. Sorry I haven't been able to track this down further at the moment.

**Comment by bluca** [comment]
Could you please send a PR to fix it?
