### ISSUE TITLE
calling zmq_ctx_term returns EINTR  right after fork, what should be the expected result?

### ISSUE THREAD

**Issue by Frankief46** [zeromq/libzmq#2807]
*Please use this template for reporting suspected bugs or requests for help.*

# Issue description
Unclear what should be the expected result  of calling zmq_ctx_term right after a fork

# Environment

* libzmq version (commit hash if unreleased): 4.2.0
* OS: 16.04.1-Ubuntu

# Minimal test code / Steps to reproduce the issue

1.  
```
const char *address = "tcp://127.0.0.1:6571";

#define NUM_MESSAGES 5

int main (void)
{
#if !defined (ZMQ_HAVE_WINDOWS)
    setup_test_environment ();
    void *ctx = zmq_ctx_new ();
    assert (ctx);
    
    //  Create and bind pull socket to receive messages
    void *pull = zmq_socket (ctx, ZMQ_PULL);
    assert (pull);
    int rc = zmq_bind (pull, address);
    assert (rc == 0);

    int pid = fork ();
    if (pid == 0) {
        //  Child process
        //  Immediately close parent sockets and context
        zmq_close (pull);
        **auto rc = zmq_ctx_term (ctx);
        assert (rc == 0);**
```

# What's the actual result? (include assertion message & call stack if applicable)
I modified the test_fork.cpp to assert the zmq_ctx_term and I found it returns non zero (EINTR)

# What's the expected result?
What is the expected result  of calling zmq_ctx_term  right after a fork? Would it returns EINTR?

**Comment by bluca** [comment]
That can happen. As the manpage says:

```
EINTR
           Termination was interrupted by a signal. It can be restarted if needed.
```
