### ISSUE TITLE
Notification problem when using inproc router to dealer.

### ISSUE THREAD

**Issue by and-fs** [zeromq/libzmq#2810]
# Issue description

Hello, we're using ZMQ since 2 years for the IPC in our software and everything worked fine.
A few weeks ago we switched to the VS2015 compiler and toolset and also from ZMQ 4.1.6 to 4.2.2.
And now we have problems with the inproc-Communication.
Not: Using the 4.1.6 DLL's with the newly compiled application works - so it shouldn't be an application issue.

We're using the following pattern:

<pre>
ZAP (PAIR, InProc)
        |
[Server] Frontend (ROUTER, TCP) <--> Backend (ROUTER, InProc) <--> Connection (DEALER, InProc)
        |
Client (DEALER, TCP)
</pre>

The problem seems to be somewhere between the both inproc router and dealer sockets. I tried to reproduce it outside our application and it works, but not inside (as long as I'm not using the old libs).
This reproduction try is made using only the both inproc router and dealer, no polling, no zap, no frontend a.s.o.

# Here is what we're doing:

1. create a context, set zero io threads option (this context is for the inproc sockets only)
2. create a router socket in that context, set linger to 500 and router mandatory option
3. bind that router to an inproc address
4. Thread-Loop: poll on frontend and backend socket (forward messages from frontend to backend and vise versa)

If a new connection comes from the frontend, following is done:

5. create a dealer socket in the inproc context, set identity (e.g. "0001"), connect to the inproc router
6. send identity of the new dealer socket ("0001") followed by the delimiter and the messages from the frontend

All steps in the same thread so far.

In step 6 sometimes EHOSTUNREACH is returned, although the dealer has been connected immediately before. And here the magic thing:

If I put a **sleep** of at least **250ms** (less doesn't catch every case on my machine) **between** dealer **connect and send** to router **it works** everytime!

So I tried to work around it and in case of new connections I waited up to 2 seconds before putting the first message for the new dealer connection into the router - this leads to EHOSTUNREACH again (in the between time other operations like polling or forwarding known dealer messages to the router are done).

It seems as if it only works if in some cases I don't touch the router after connecting the dealer...

Unfortunately I cannot debug it, when using the debugger the code is slow enough not to run into the problem.
So I added debug logs at some points inside the zmq code and found a difference between the times it works and it doesn't:

<pre>
# [thisptr] threadid message (filtered for server thread)
[00000000053B77B0] <15940> connect 3 to 'inproc://server1' (peer.tid = 2)                      | [000000000556DF00] <15940> connect 7 to 'inproc://server1' (peer.tid = 2)
                                                                                               | 
[00000000053B77B0] <15940> Sending identity '0000000000000001' of myself 3 to peer 2           | [000000000556DF00] <15940> Sending identity '0000000000000005' of myself 7 to peer 2
[00000000053B77B0] <15940> Binding 3 to 2                                                      | Binding 7 to 2
                                                                                               |
[00000000053B77B0] <15940> send_bind (sender = 3, dest = 2)                                    | [000000000556DF00] <15940> send_bind (sender = 7, dest = 2)
[0000000002C85A10] <15940> mailbox_t::send(dest = 2, cmd = bind) -> ok = false                 | [0000000002C85A10] <15940> mailbox_t::send(dest = 2, cmd = bind) -> ok = false
                                                                                               | 
[00000000053B77B0] <15940> attach_pipe(in: 3 -> out: 3)                                        | [000000000556DF00] <15940> attach_pipe(in: 7 -> out: 7)
                                                                                               | 
                                                                                               | [0000000002CD8E70] <15940> mailbox_t::send(dest = 2, cmd = activate_write) -> ok = false
                                                                                               | [0000000002CD8E70] <15940> mailbox_t::send(dest = 2, cmd = activate_write) -> ok = true
                                                                                               | 
[0000000002C85A10] <15940> mailbox_t::recv(dest = 2, cmd = bind, signaled)                     | [0000000002C85A10] <15940> mailbox_t::recv(dest = 2, cmd = bind, signaled)
                                                                                               | 
[0000000002E38810] <15940> attach_pipe(in: 2 -> out: 2)                                        | [0000000002E38810] <15940> attach_pipe(in: 2 -> out: 2)
[0000000002C85BF0] <15940> mailbox_t::send(dest = 3, cmd = activate_write) -> ok = false       | [0000000002C860A0] <15940> mailbox_t::send(dest = 7, cmd = activate_write) -> ok = false
                                                                                               | 
[0000000002CD8E70] <15940> mailbox_t::send(dest = 2, cmd = activate_write) -> ok = false       | 
[0000000002CD8E70] <15940> mailbox_t::send(dest = 2, cmd = activate_write) -> ok = true        | 
                                                                                               | 
[0000000002C85A10] <15940> mailbox_t::recv(dest = 2, cmd = activate_write, signaled)           | 
[0000000002C85A10] <15940> mailbox_t::recv(dest = 2, cmd = activate_write, active)             | 
</pre>

On the left the log of the working example, at the right side of one which leads to EHOSTUNREACH.
The numbers for dest, in, out etc. are the tid attribute for the object.
2 is the router, 3 and 7 a dealer.

Here the code where I placed the debug logs:

<pre>
void zmq::mailbox_t::send (const command_t &cmd_)
{
    sync.lock ();
    cpipe.write (cmd_, false);
    const bool ok = cpipe.flush ();
    sync.unlock ();
    LIBZMQ_TRACE("mailbox_t::send(dest = %d, cmd = %s) -> ok = %s", cmd_.destination ? cmd_.destination->get_tid() : 0, zmq_cmd_info(cmd_), ok ? "true" : "false");
    if (!ok)
        signaler.send ();
}

int zmq::mailbox_t::recv (command_t *cmd_, int timeout_)
{
  //  Try to get the command straight away.
    if (active) {
        if (cpipe.read(cmd_))
        {
            LIBZMQ_TRACE("mailbox_t::recv(dest = %d, cmd = %s, active)", cmd_->destination ? cmd_->destination->get_tid() : 0, zmq_cmd_info(*cmd_));
    ...
    //  Get a command.
    const bool ok = cpipe.read (cmd_);
    zmq_assert (ok);
    LIBZMQ_TRACE("mailbox_t::recv(dest = %d, cmd = %s, signaled)", cmd_->destination ? cmd_->destination->get_tid() : 0, zmq_cmd_info(*cmd_));

void zmq::object_t::send_bind (own_t *destination_, pipe_t *pipe_,
    bool inc_seqnum_)
{
    LIBZMQ_TRACE("send_bind (sender = %d, dest = %d)", get_tid(), destination_->get_tid());

void zmq::socket_base_t::attach_pipe (pipe_t *pipe_, bool subscribe_to_all_)
{
    LIBZMQ_TRACE("attach_pipe(in: %d -> out: %d)", pipe_->get_tid(), get_tid());

int zmq::socket_base_t::bind (const char *addr_)
{
    ...
    if (protocol == "inproc") {
        LIBZMQ_TRACE("bind %d to '%s'", get_tid(), addr_);

int zmq::socket_base_t::connect (const char *addr_)
{
    ....
    if (protocol == "inproc") {
        endpoint_t peer = find_endpoint (addr_);
        LIBZMQ_TRACE("connect %d to '%s' (peer.tid = %d)", get_tid(), addr_, peer.socket ? peer.socket->get_tid() : 0);
    ....

int zmq::socket_base_t::connect (const char *addr_)
{
    ....
    if (protocol == "inproc") {
        ....
        if (!peer.socket) { ... }
        else {
            //  If required, send the identity of the local socket to the peer.
            if (peer.options.recv_identity) {
# ifdef _DEBUG
                char idstr[256];
                memcpy(idstr, options.identity, options.identity_size);
                idstr[options.identity_size] = 0;
                LIBZMQ_TRACE("Sending identity '%s' of myself %d to peer %d", idstr, get_tid(), peer.socket->get_tid());
# endif
</pre>

I lot of text, sorry, but I invested more then 60 hours in this problem and now I hope, someone sees what happens here (or what I'm doing wrong).

If you need more informations, logs or whatever, I'll provide it.

Thank you very much!

# Environment

* libzmq version 4.2.1 and 4.2.2 (maybe 4.2.0, too, couldn't test it)
* OS: Windows 7 Pro x64, Windows 10

**Comment by bluca** [comment]
Ok, thanks for checking
