### ISSUE TITLE
‘ZMQ_RADIO’ was not declared in libzmq 4.2.3

### ISSUE THREAD

**Issue by wchengad** [zeromq/libzmq#2811]
*Please use this template for reporting suspected bugs or requests for help.*

# Issue description
I want to use libzmq to transfer date using UDP, I cloned the recent 4.2.3 libzmq-master, and autogen, configure with default configuration and --enable-draft(=true), then make and make install. The problem is that it seems draft was not activated with 'ZMQ_RADIO' not declared error.

# Environment

* libzmq version (commit hash if unreleased):  4.2.3
* OS: Ubuntu 14.04

# Minimal test code / Steps to reproduce the issue

1.  void *radio = zmq_socket(context, ZMQ_RADIO);

# What's the actual result? (include assertion message & call stack if applicable)

error: ‘ZMQ_RADIO’ was not declared in this scope

# What's the expected result?

**Comment by bluca** [comment]
Are you using pkgconfig in your build to get libzmq flags? If not you will have to manually define ZMQ_BUILD_DRAFT_API before including zmq.h. it's recommended to just use pkgconfig as it's standard practice on Linux and Unix.

Also as the readme says, if you are not making changes consider using the prebuilt packages add it will make your life easier.

https://software.opensuse.org/download.html?project=network%3Amessaging%3Azeromq%3Agit-draft&package=libzmq3-dev

**Comment by wchengad** [comment]
Hi @bluca , thanks for your comment. I tried to use prebuilt package, but still with ZMQ_RADIO declaration error, should I manually define ZMQ_BUILD_DRAFT_API?

**Comment by bluca** [comment]
If you don't use pkg-config, then yes. pkg-config is recommended.

**Comment by wchengad** [comment]
Thanks @bluca , I am new to libzmq, I still have some questions on binding sockets on radio and dish. In official documentation the asserted rc after binding or connecting a port is always 0. But in test_udp.cpp 

`    //  Connecting dish should fail
    int rc = zmq_connect (dish, "udp://127.0.0.1:5556");
    assert (rc == -1);

    rc = zmq_bind (dish, "udp://*:5556");
    assert (rc == 0);

    //  Bind radio should fail
    rc = zmq_bind (radio, "udp://*:5556");
    assert (rc == -1);

    rc = zmq_connect (radio, "udp://127.0.0.1:5556");
    assert (rc == 0);

    msleep (SETTLE_TIME);

    rc = zmq_join (dish, "TV");
    assert (rc == 0);

    rc = msg_send (&msg, radio, "TV", "Friends");
    assert (rc != -1);

    rc = msg_recv_cmp (&msg, dish, "TV", "Friends");
    assert (rc != -1);

    rc = zmq_close (dish);
    assert (rc == 0);

    rc = zmq_close (radio);
    assert (rc == 0);

    rc = zmq_ctx_term (ctx);
    assert (rc == 0);`
some should fail. What's the difference, because in my case, the return values are -1.

Thank you very much if you can help me.

**Comment by bluca** [comment]
For UDP it's different - dish sockets are bound, and radio sockets connect to as many dish as needed. It's usually the other way around for other transports.
