### ISSUE TITLE
Ordering of events in publisher/subscriber

### ISSUE THREAD

**Issue by jay11ca39** [zeromq/libzmq#2812]
# Issue description
Hello @bluca ,
It is not a bug, but it is just to get some information about libzmq.
Is ordering of message is guaranteed in PUB/SUB socket. 
In other words, if I publish 1 million messages,  Will these message will be written on the wire in that same sequence and  subscriber will get in same sequence

# Environment

* libzmq: Debian 9 latest release
* OS: Linux

**Comment by bluca** [comment]
Yes, ordering is guaranteed.
