### ISSUE TITLE
ZMQ's asserts execute in release build

### ISSUE THREAD

**Issue by Fetterless** [zeromq/libzmq#2814]
# Issue description
Hello!

I use zmq in my project which crashes after a long period of time. After debugging it I saw, that the problem is in zmq: all the ZMQ's asserts (zmq_assert, wsa_assert etc) execute in release mode. If I skip them in Visual Studio, application continues run correctly, but without debugger attached it crashes due to reason above.

Also from **err.hpp:**
```
//  This macro works in exactly the same way as the normal assert. It is used
//  in its stead because standard assert on Win32 in broken - it prints nothing
//  when used within the scope of JNI library.
#define zmq_assert(x) \
    do {\
        if (unlikely (!(x))) {\
            fprintf (stderr, "Assertion failed: %s (%s:%d)\n", #x, \
                __FILE__, __LINE__);\
            fflush (stderr);\
            zmq::zmq_abort (#x);\
        }\
    } while (false)
```

>  This macro works in exactly the same way as the normal assert.

But the normal **assert** is replaced by `assert(_Expression)     ((void)0)` as opposed to zmq.

# Environment

* libzmq version (commit hash if unreleased): 4.1.6+
* OS: Windows

# Question
So, the question is: **"should ZMQ's asserts (zmq_assert, wsa_assert etc) execute in release mode"**?
And an extra question: is it safe to implement **normal assert** logic for zmq asserts in my "special zmq build"?

Thanks in advance

**Comment by bluca** [comment]
Yes, it is normal, there are no "release" or "debug" builds. If you are interested in more details, it's been asked before, you can find information in old issues and mails to the list and blog posts.

Paste a trace and minimal code to reproduce the issue and someone can help.

Most common issues:

1) Creating/using/closing a socket from multiple threads
2) Creating/using/deleting a message from multiple threads
3) Closing a message after a successful send
4) Memory corruption / OOM
