### ISSUE TITLE
ISO C++ forbids braced-groups within expressions

### ISSUE THREAD

**Issue by jdemeyer** [zeromq/libzmq#2817]
# Issue description

On my Gentoo Linux system, zeromq does not build due to
```
src/msg.cpp:400:5: error: ISO C++ forbids braced-groups within expressions [-Werror=pedantic]
     assert (metadata_ != NULL);
```
The reason is that glibc 2.25 uses GNU extensions to define `assert`. Since zeromq does not use `-std=c++XY` or `-ansi`, such GNU extensions should be allowed.

But the **real** reason for the broken build is `-Werror`, see #2818 for that.

# Environment

* libzmq version (commit hash if unreleased): 4.2.2
* OS: `Linux tamiyo 3.17.7-gentoo #2 SMP PREEMPT Fri Dec 23 18:13:49 CET 2016 x86_64 Intel(R) Core(TM) i7-2640M CPU @ 2.80GHz GenuineIntel GNU/Linux`
* Compiler: g++ (Gentoo 4.9.4 p1.0, pie-0.6.4) 4.9.4
* glibc: glibc-2.25 (+ Gentoo patches)

# Minimal test code / Steps to reproduce the issue

1.  Build zeromq

# What's the actual result? (include assertion message & call stack if applicable)

```
src/msg.cpp:400:5: error: ISO C++ forbids braced-groups within expressions [-Werror=pedantic]
     assert (metadata_ != NULL);
```

# What's the expected result?

A working build of zeromq

**Comment by bluca** [comment]
std=gnu11 is used by default, with fallback to gnu99, not sure why is it falling for that?

**Comment by jdemeyer** [comment]
> std=gnu11 is used by default, with fallback to gnu99, not sure why is it falling for that?

But zeromq is a C++ library, not C. So the C standard flag seems irrelevant.

**Comment by bluca** [comment]
The c++ equivalents, of course

**Comment by bluca** [comment]
@jdemeyer I cannot reproduce on Debian sid x86_64 with glibc 2.25 and gcc 7:

```
root@BRA-6G85P12:/zeromq3-4.2.2# ldd debian/tmp/usr/lib/x86_64-linux-gnu/libzmq.so.5.1.2 
	linux-vdso.so.1 (0x00007ffe37909000)
	libeatmydata.so => /usr/lib/x86_64-linux-gnu/libeatmydata.so (0x00007fbf3ada6000)
	/usr/lib/cowdancer/libcowdancer.so (0x00007fbf3aba0000)
	libsodium.so.18 => /usr/lib/x86_64-linux-gnu/libsodium.so.18 (0x00007fbf3a92f000)
	libpgm-5.2.so.0 => /usr/lib/x86_64-linux-gnu/libpgm-5.2.so.0 (0x00007fbf3a6e2000)
	librt.so.1 => /lib/x86_64-linux-gnu/librt.so.1 (0x00007fbf3a4da000)
	libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007fbf3a2bc000)
	libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007fbf3a0b8000)
	libstdc++.so.6 => /usr/lib/x86_64-linux-gnu/libstdc++.so.6 (0x00007fbf39d39000)
	libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007fbf39a26000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007fbf39683000)
	libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007fbf3946c000)
	libncurses.so.5 => /lib/x86_64-linux-gnu/libncurses.so.5 (0x00007fbf39248000)
	libtinfo.so.5 => /lib/x86_64-linux-gnu/libtinfo.so.5 (0x00007fbf3901e000)
	/lib64/ld-linux-x86-64.so.2 (0x00007fbf3b232000)
root@BRA-6G85P12:/zeromq3-4.2.2# dpkg -l | grep libc6
ii  libc6:amd64                      2.25-0experimental3        amd64        GNU C Library: Shared libraries
ii  libc6-dev:amd64                  2.25-0experimental3        amd64        GNU C Library: Development Libraries and Header Files
```

What's the ./configure string you used? Also the compiler you used is very old, are you sure it's compatible with the bleeding edge libc?

**Comment by bluca** [comment]
Also tried with gcc 5, works fine. There's no gcc-4 since Debian 8 so I cannot try it with glibc 2.25.

**Comment by bluca** [comment]
Build works on an even newer version of glibc in Fedora 27, so it all points at a problem with very old gcc plus very new glibc. Closing due to that and inactivity.
