### ISSUE TITLE
Stop using -Werror

### ISSUE THREAD

**Issue by jdemeyer** [zeromq/libzmq#2818]
# Issue description

zeromq is built with the `-Werror` compiler flag. This means that any kind of warning in the build toolchain (compiler, assembler, linker) breaks the build. The option `-Werror` may be great when you have complete control over the operating system and the toolchain (for example, on a CI system). But who knows on what kind of systems and with which compilers people will compile zeromq. The `-Werror` option is breaking zeromq on systems where it would otherwise build and work perfectly fine. The fact that zeromq already disables `-Werror` on some systems should also be a sign that the option is unreliable.

Concretely, my build is broken due to #2817. Regardless of whether/how you fix that issue, I'm sure that `-Werror` will cause other breakage for no good reason.

**Comment by bluca** [comment]
Feel free to send a PR to implement a configure flag to disable it, like we have in zproject/czmq/etc: https://github.com/zeromq/zproject/blob/master/configure.ac#L336
