### ISSUE TITLE
Running out of sockets while trying to connect an unreachable ip address

### ISSUE THREAD

**Issue by MVJMBoeren** [zeromq/libzmq#2819]
# Issue description
Running out of sockets while trying to connect an unreachable ip address.
After 1024 attempts the next attempt to create a zmq::socket_t triggers an exception.

# Environment
Windows

* libzmq version (commit hash if unreleased): 
Tested on 4.0.5 and 4.2.0
* OS: Windows 7

# Minimal test code / Steps to reproduce the issue
```
TEST_F(RpcConnectionTest, Findingout)
{
    zmq::context_t context(1);
    int i(0);
    while (true)
    {  
        i++;
        zmq::socket_t sock(context, ZMQ_REQ);
        sock.connect("tcp://192.168.10.234:5559"); //Unreachable ipAddress

        std::string request = "Hello!";
        sock.send(request.data(), request.size());

        zmq::pollitem_t pollItems[1] = { { sock, 0, ZMQ_POLLIN, 0 } };

        // wait for the response
        if (0 == zmq::poll(pollItems, 1, 50))
        {
            std::cout << "Timeout " << i << std::endl;
            continue;
        }
        else
        {
            zmq::message_t response;
            sock.recv(&response);
            std::cout << "We received something!!!" << std::endl;
            EXPECT_FALSE(true);
            break;
        }
    }
}
```
# What's the actual result? (include assertion message & call stack if applicable)
constructor of zmq::socket_t throws an exception.

# What's the expected result?
It should not throw an exception

**Comment by bluca** [comment]
Mmh this is quite strange, if the connection fails the socket is closed as expected. Maybe some Windows-specific quirkness? Any Windows expert that can help?

**Comment by bluca** [comment]
Hang on - that snippet is creating a new socket without closing the old one on each round around the loop. That is going to exhaust system resources at some point of course - if it's not file descriptors, it will be memory or TCP ports or whatnot.

Do not do that - the socket will automatically try to reconnect if the first attempt fails.

Also the poll is just waiting 50ms - the connects are asynchronous, so there's no guarantee it will be done even if the address is reachable by that time. If you want a deterministic way to know when a socket is connected (in 99.9% of the applications you don't - just queue messages), use zmq_socket_monitor and look for the CONNECTED event.

If for some reason you want to manually retry and don't want the background thread to do it, set the ZMQ_RECONNECT_IVL socket option to -1 before doing the connect. That will do only one attempt, and no more. If you don't close the socket with zmq_close though not all resources will be freed though.

**Comment by oponomarov** [comment]
@bluca:

Thank you for the explanation.  But this brings new questions then. ZMQ has except plain C interface also C++ wrappers to facilitate usage of this library in C++ code.  From C++ point of view when object goes out of scope it must be destroyed and all occupied resources must be released.  From that perspective the code snippet above is absolutely correct.  What is the purpose of asynchronous reconnection being performed for the socket if client already does not have ability to access this socket anymore?!  In my opinion it is nonsense and obvious bug in C++ wrapper for socket - zmq::socket_t. From client perspective it means that using zmq:socket_t wrapper - is dangerous and you still have to do some obscure tricks to actually release resources. 

Please comment. I think the new ticket should be created to fix incorrect beahvior of zmq::socket_t.

**Comment by MVJMBoeren** [comment]
@bluca, many thanks for the responses until now. We will definitely try to use the ZMQ_RECONNECT_IVL. Although I'm unsure if we can via the C++ wrapper interface.
We're indeed using the C++ wrapper interface and the zmq::socket_t object goes out of scope triggering the zmq::close.

We're using the [Shared-Queue-DEALER-and-ROUTER-sockets](http://zguide.zeromq.org/page:all#Shared-Queue-DEALER-and-ROUTER-sockets)
When we do use the dealer/router sockets and also initialize the zmq_proxy we experience slightly different behavior.
The first 1000 socket_t objects that go out of scope are destroyed as expected by the reaper thread. The socket queue is only filled with 3 sockets and the empty_slots queue is filled with 1021 items.
Beyond the usage of 1000 socket_t the reaper thread doesn't destroy the sockets anymore (Why is unclear for me). When debugging we see the socket queue grow and the empty_slots queue size reduce. When the empty_slots queue is empty, the zmq::error_t is thrown. 
To revive the behavior of zmq we need to restart the application completely which is of course unacceptable.

Please comment.

**Comment by bluca** [comment]
> Thank you for the explanation. But this brings new questions then. ZMQ has except plain C interface also C++ wrappers to facilitate usage of this library in C++ code. From C++ point of view when object goes out of scope it must be destroyed and all occupied resources must be released. From that perspective the code snippet above is absolutely correct. What is the purpose of asynchronous reconnection being performed for the socket if client already does not have ability to access this socket anymore?! In my opinion it is nonsense and obvious bug in C++ wrapper for socket - zmq::socket_t. From client perspective it means that using zmq:socket_t wrapper - is dangerous and you still have to do some obscure tricks to actually release resources.
>
> Please comment. I think the new ticket should be created to fix incorrect beahvior of zmq::socket_t.

Sorry, I don't know much about the C++ wrappers - I really don't use them. The right place for issues specific to those is either https://github.com/zeromq/zmqpp or https://github.com/zeromq/cppzmq depending on which one it's used.
What I mentioned refers to libzmq exclusively.

**Comment by bluca** [comment]
> @bluca, many thanks for the responses until now. We will definitely try to use the ZMQ_RECONNECT_IVL. Although I'm unsure if we can via the C++ wrapper interface.
We're indeed using the C++ wrapper interface and the zmq::socket_t object goes out of scope triggering the zmq::close.
>
> We're using the Shared-Queue-DEALER-and-ROUTER-sockets
When we do use the dealer/router sockets and also initialize the zmq_proxy we experience slightly different behavior.
The first 1000 socket_t objects that go out of scope are destroyed as expected by the reaper thread. The socket queue is only filled with 3 sockets and the empty_slots queue is filled with 1021 items.
Beyond the usage of 1000 socket_t the reaper thread doesn't destroy the sockets anymore (Why is unclear for me). When debugging we see the socket queue grow and the empty_slots queue size reduce. When the empty_slots queue is empty, the zmq::error_t is thrown.
To revive the behavior of zmq we need to restart the application completely which is of course unacceptable.
>
> Please comment.

Do you have a code snippet to reproduce that, without using any binding/wrapper?

Apart from that, why not letting the background reconnect happen instead of doing it manually? Wouldn't that be simpler? Is there any reason you are trying to re-implement that in the application layer?
