### ISSUE TITLE
Running out of sockets 

### ISSUE THREAD

**Issue by MVJMBoeren** [zeromq/libzmq#2822]
*Please use this template for reporting suspected bugs or requests for help.*

# Issue description
Running out of sockets while trying to connect an unreachable ip address.
After 1024 attempts the next attempt to create a zmq_socket returns nullptr.
(See also #2819, but now completely on the bare C-interface).

# Environment
Windows

* libzmq version (commit hash if unreleased): 
libzmq.lib 4.2.0
* OS: Windows 7

# Minimal test code / Steps to reproduce the issue
```
TEST_F(ZmqCTest, SendTest)
{
    auto context = zmq_ctx_new();
    std::string request = "Hello!";
    int i(0);

    while (true)
    {
        i++;
        std::cout << "Attempt " << i << std::endl;

        auto socket = zmq_socket(context, ZMQ_REQ);
        if (socket == nullptr)
        {
            throw std::runtime_error("Running out of sockets?");
        }

        zmq_connect(socket, "tcp://192.168.10.234:5559"); // Unreachable IP

        zmq_send(socket, request.data(), request.size(), 0);

        zmq_close(socket);
    }
    zmq_ctx_destroy(context);
}
```

# What's the actual result? (include assertion message & call stack if applicable)
We're not able to open new sockets.

# What's the expected result?
We should be able to open new sockets as long as we correctly closed the already used ones.

**Comment by sigiesec** [comment]
The problem might be here that the actual closing of the sockets happens asynchronously.
I assume this works indefinitely, if you slow the loop down sufficiently.
Would this be in line with your expectations?

**Comment by mrvn** [comment]
Also keep in mind that send messages on sockets linger. The socket won't be freed until the linger timeout has passed.

> The ZMQ_LINGER option shall set the linger period for the specified socket. The linger period determines how long pending messages which have yet to be sent to a peer shall linger in memory after a socket is disconnected with zmq_disconnect(3) or closed with zmq_close(3), and further affects the termination of the socket's context with zmq_ctx_term(3). The following outlines the different behaviours:

The default is 30s and your loop will clearly open more than 1000 sockets in 30s. So I would call this expected behaviour.

Things to test:
1) set LINGER timeout to 0
2) add a usleep() or yield() to give the IO processes time to clean up
3) when zmq_socket fails do sleep(1) and retry. Does it still fail then?

**Comment by sigiesec** [comment]
Closing this, assuming the issue has been resolved and the behaviour is correct.

@MVJMBoeren Please reopen with additional information if you still have issues.
