### ISSUE TITLE
Problem: creating monitor without connecting it hangs socket

### ISSUE THREAD

**Issue by hzdx2000** [zeromq/libzmq#2829]
*Please use this template for reporting suspected bugs or requests for help.*

# Issue description
I have a publisher written in python and send message every 1s.
Another subscriber written in C and receive messages.
TCP is the protocol for communication
After add monitor function in SUB sockect, sub receiving function cannot receive any messages.

# Environment
ubuntu for subscriber
centos for publisher

* libzmq version (commit hash if unreleased):  4.1.5 and 4.2.2
* OS:  linux

# Minimal test code / Steps to reproduce the issue

1.  Pub
```
import zmq
import random
import sys
import time

port = "5555"
if len(sys.argv) > 1:
    port =  sys.argv[1]
    int(port)

context = zmq.Context()
socket = context.socket(zmq.PUB)
#socket.socket_monitor("inproc://monitor.rep", ZMQ_EVENT_ALL)
socket.bind("tcp://172.17.42.1:%s" % port)
while True:
    topic = random.randrange(9999,10005)
    messagedata = random.randrange(1,215)
    print "%d %d" % (topic, messagedata)
    socket.send("%d %d" % (1001, messagedata))
    time.sleep(1)
```
2. Sub
```
        ctx = zmq_ctx_new ();
        sub_client = zmq_socket (ctx, ZMQ_SUB);
        zmq_socket_monitor (sub_client, "inproc://monitor-client", ZMQ_EVENT_ALL);
        zmq_connect(sub_client, "tcp://172.17.42.1:5555");

        zmq_setsockopt(sub_client, ZMQ_SUBSCRIBE, "", 0);

        while (running_) {
            zmq_msg_t msg;
            zmq_msg_init (&msg);
            if (zmq_msg_recv (&msg, sub_client, 0) == -1)
                return; // Interrupted, presumably
            xinfo() << "message has bee received: ";
        }
```

# What's the actual result? (include assertion message & call stack if applicable)
if zmq_socket_monitor (sub_client, "inproc://monitor-client", ZMQ_EVENT_ALL); is used,
then receive function won't work any more and hangs there.
After remove zmq_socket_monitor function, receiving function is ok.

# What's the expected result?
I hope to use the monitor functionality to monitor whether there is a connection/disconnection between sub and pub.
But now, monitor functionality will make receiving function in SUB side hang.
Would anyone know whether it is the wrong usage or a bug?
Thanks.

**Comment by bluca** [comment]
The client creates the monitor, but never connects a socket to it. Do it and it will work:

```
        ctx = zmq_ctx_new ();
        sub_client = zmq_socket (ctx, ZMQ_SUB);
        zmq_socket_monitor (sub_client, "inproc://monitor-client", ZMQ_EVENT_ALL);

        void *client_mon = zmq_socket (ctx, ZMQ_PAIR);

        zmq_connect(sub_client, "tcp://172.17.42.1:5555");

        zmq_setsockopt(sub_client, ZMQ_SUBSCRIBE, "", 0);

        while (running_) {
            zmq_msg_t msg;
            zmq_msg_init (&msg);
            if (zmq_msg_recv (&msg, sub_client, 0) == -1)
                return; // Interrupted, presumably
            xinfo() << "message has bee received: ";
        }
```

The problem is that once the socket connects, it tries to send an event but there's nothing to receive. Given it's inproc, there's no I/O thread managed pipe to buffer messages. It shouldn't hang like that though, but if it times out then the event monitoring becomes lossy as events get lost. I'll think about a solution.

**Comment by hzdx2000** [comment]
Hi bluca,

You are genius and really hep me by using 'connect'.

David.c.wang

**Comment by Lounarok** [comment]
Hi @bluca ,
Will this still happen today for libzmq 4.2.x if we're using `zmq_socket_monitor()`?
It allows only `ZMQ_PAIR` and its mute action of `ZMQ_PAIR` is block..
