### ISSUE TITLE
Cross compiling libzmq for ARM architecture.

### ISSUE THREAD

**Issue by jay11ca39** [zeromq/libzmq#2838]
Hi @bluca ,

It is just to get information. As it is urgent I raised this issue.

I want to build libzmq for arm architecure on my ubuntu-x86_64 machine.
I found the guide given at: 
[http://zeromq.org/build:arm](http://zeromq.org/build:arm)

I am currently using this guide for my ubuntu-x86_64 arch:

```
echo "deb http://download.opensuse.org/repositories/network:/messaging:/zeromq:/release-stable/Debian_9.0/ ./" >> /etc/apt/sources.list
wget https://download.opensuse.org/repositories/network:/messaging:/zeromq:/release-stable/Debian_9.0/Release.key -O- | sudo apt-key add
apt-get install libzmq3-dev
```

But I want to know is it possible to use the prebuilt binaries for cross compiling for arm arch like above.

**Comment by bluca** [comment]
Which distro are you targeting for the arm builds?
We already build arm binaries for a number of them:

https://build.opensuse.org/project/show/network:messaging:zeromq:release-stable

If your target is not there, then you can't use the pre-built binaries, as you'll need to build them locally.
Cross-compiling is supported with the standard autoconf tooling, there's nothing special, just pass the right flags to ./configure

**Comment by jay11ca39** [comment]
Hi @bluca 

I checked the above link but, I couldn't find arm library that I need.
I am following the steps to cross compile for arm on my ubuntu machine:

```
(1) git clone https://github.com/zeromq/libzmq.git

(2) ./autogen.sh

(3) ./configure --host=arm-none-linux-gnueabi

(4) make -j 4

(5) make check

(6) make install

(7) sudo ldconfig

```
Will It will install the library in /usr/local/lib folder?

Did i miss anything?

**Comment by bluca** [comment]
That should be all, yes it will be in /usr/local/lib, you can use the --prefix option with ./configure to change the path

**Comment by jay11ca39** [comment]
Hello @bluca 
I tried the above steps and build successfully libzmq for arm.
But when I am trying to build my project for arm, which internally uses libzmq . It is giving the following error:

```
/usr/local/lib/libzmq.so: file not recognized: File format not recognized
collect2: error: ld returned 1 exit status
```

**Comment by bluca** [comment]
Run ```file /usr/local/lib/libzmq.so.5.1.3```
If it says it's an ARM binary, then it's a problem with your project's build system.

**Comment by jay11ca39** [comment]
I checked this before as well:

This is my /usr/local/lib folder:

```
-rw-r--r--  1 root root   26147916  Nov 15 19:45    libzmq.a
-rwxr-xr-x  1 root root        954      Nov 15 19:45     libzmq.la
lrwxrwxrwx  1 root root         15     Nov 15 19:45     libzmq.so -> libzmq.so.5.1.3
lrwxrwxrwx  1 root root         15     Nov 15 19:45     libzmq.so.5 -> libzmq.so.5.1.3
-rwxr-xr-x  1 root root    8947583  Nov 15 19:45     libzmq.so.5.1.3
```

This is the output of file command:

`/usr/local/lib/libzmq.so.5.1.3: ELF 64-bit LSB  shared object, x86-64, version 1 (SYSV), dynamically linked, BuildID[sha1]=1faf36cd10a744c28e4ca2a96a045c3f7c7d80fa, not stripped`

**Comment by bluca** [comment]
Then the autoconf option was not correct or complete - I suggest to google for a general solution, again there's nothing special in this project, it's standard autoconf

**Comment by jay11ca39** [comment]
@bluca ,
I have tried with :

`./configure --host=arm-none-linux-gnueabi CC=arm-linux-gnueabi-gcc CXX=arm-linux-gnueabi-g++`

Then I ran the file command:

`libzmq.so.5.1.3: ELF 32-bit LSB  shared object, ARM, EABI5 version 1 (SYSV), dynamically linked, BuildID[sha1]=07c850504478cba3a5a5f90a001dac0a24b13087, not stripped`

It built for ARM arch.:)

**Comment by bluca** [comment]
Ok, great, I will update the wiki. Can we close this issue now then?

**Comment by jay11ca39** [comment]
Thanks @bluca  for quick responses....:)

**Comment by benjamg** [comment]
Based on https://www.gnu.org/savannah-checkouts/gnu/autoconf/manual/autoconf-2.69/html_node/Hosts-and-Cross_002dCompilation.html you probably just wanted to use `/configure --host=arm-none-linux-gnueabi --build=arm-none-linux-gnueabi`. I don't know if that would do other things than changing CC and CXX does.

**Comment by jay11ca39** [comment]
@benjamg ,
Firstly I tried with:
configure --host=arm-none-linux-gnueabi 
and then checked the arch of installed shard library.
but it was showing x86_64

Then i tried couple of options  and with the below one i got succes:
`./configure --host=arm-none-linux-gnueabi CC=arm-linux-gnueabi-gcc CXX=arm-linux-gnueabi-g++`

**Comment by benjamg** [comment]
Sorry, I wasn't clear. I did see you got it working but thought I'd mention the link as it implies, unlike older versions, with the current version of autoconf you need to do both host and build rather than just host. I'm assuming it worked your way because that is what the build option is changing anyway.

**Comment by jay11ca39** [comment]
@bluca ,
Do you have any info for cross compiling for arm64 what should be the host value in ./configure

Like for arm as per guide I have done:
./configure --host=arm-none-linux-gnueabi 

Similarly what should be the --host for arm64 ?

**Comment by bluca** [comment]
Google says aarch64-unknown-linux-gnu

**Comment by jay11ca39** [comment]
@bluca , 
It helped to build for ARM64....:) 
Thanks again,,,
