### ISSUE TITLE
Wrong ZMQ_LINGER default value

### ISSUE THREAD

**Issue by fnaime** [zeromq/libzmq#2845]
# Issue description
zmq_setsockopt(3) stated that ZMQ_LINGER default value is 30000 (thirty seconds), which is in fact -1 (infinite).

# Environment
* libzmq version 4.2.2
* OS: Linux

# Minimal test code / Steps to reproduce the issue

#include <stdlib.h>
#include <stdio.h>
#include <zmq.h>

int main(void)
{
    void *ctx = zmq_ctx_new();

    void *socket = zmq_socket(ctx, ZMQ_DEALER);

    int linger;
    size_t linger_size = sizeof(linger);
    int rc = zmq_getsockopt(socket, ZMQ_LINGER, &linger, &linger_size);
    if (rc != 0)
    {
        printf ("error in zmq_getsockopt: %s\n", zmq_strerror (errno));
        return -1;
    }

    printf("Default LINGER: %d\n", linger);

    return 0;
}

# What's the actual result? (include assertion message & call stack if applicable)
Default LINGER: -1

# What's the expected result?
Default LINGER: 30000

 I suggest changing documentation, since changing LINGER default value is not backward compatible.

**Comment by c-rack** [comment]
Could you please send a pull request with the proposed change?

**Comment by bluca** [comment]
Thanks. I was scared for a moment, but then noticed that we never actually released with a default different from -1, as it was just briefly changed to something else. As you noted it's just the documentation that was never fixed. Phew!
