### ISSUE TITLE
jzmq 3.1.0 crashes & our Java application crashes

### ISSUE THREAD

**Issue by b6arat6** [zeromq/libzmq#2855]
# Issue description
Our application uses Java binding for ZMQ, with Pub-Sub model. Sub crashes intermittently but frequently, with error traces (seen in the core dump generated during the crash) pointing to ZMQ crash.

The issue occurs in our Production, where the load is high.

# Environment
* Version: jzmq (3.1.0)
* OS: Linux

# Minimal test code / Steps to reproduce the issue

1. Use jzmq (3.1.0) with Pub-Sub model. Keep sending messages from Pub for some time.

# What's the actual result? (include assertion message & call stack if applicable)
ZMQ crashes with following messages.

Core dump traces:

Crash 1:
#0  0x00002b0169da7fc5 in raise () from /lib64/libc.so.6
#1  0x00002b0169da9a70 in abort () from /lib64/libc.so.6
#2  0x00002b0190f1dce9 in zmq::zmq_abort (errmsg_=0x4409 <Address 0x4409 out of bounds>) at err.cpp:76
#3  0x00002b0190f344c8 in zmq::stream_engine_t::write (this=<value optimized out>, data_=<value optimized out>, size_=<value optimized out>) at stream_engine.cpp:517
#4  0x00002b0190f34709 in zmq::stream_engine_t::out_event (this=0x1865cbf0) at stream_engine.cpp:275
#5  0x00002b0190f1d3ba in zmq::epoll_t::loop (this=0x2b017f34d490) at epoll.cpp:158
#6  0x00002b0190f3b28c in thread_routine (arg_=0x2b017f34d500) at thread.cpp:83
#7  0x00002b016974783d in start_thread () from /lib64/libpthread.so.0
#8  0x00002b0169e4d19d in clone () from /lib64/libc.so.6

Crash 2:
#0  0x00002b121f0444bb in memcpy () from /lib64/libc.so.6
#1  0x00002b12420f5a02 in zmq::encoder_base_t<zmq::v1_encoder_t>::get_data (this=0x1cdd1110, data_=0x1cafc958, size_=0x1cafc960, offset_=0x0) at encoder.hpp:117
#2  0x00002b12420e86f2 in zmq::stream_engine_t::out_event (this=0x1cafc910) at stream_engine.cpp:261
#3  0x00002b12420e1202 in zmq::session_base_t::read_activated (this=0x1cafcb50, pipe_=0x1be54720) at session_base.cpp:264
#4  0x00002b12420d27e9 in zmq::io_thread_t::in_event (this=<value optimized out>) at io_thread.cpp:75
#5  0x00002b12420d13da in zmq::epoll_t::loop (this=0x2b1234fea0b0) at epoll.cpp:162
#6  0x00002b12420ef28c in thread_routine (arg_=0x2b1234fea120) at thread.cpp:83
#7  0x00002b121e99883d in start_thread () from /lib64/libpthread.so.0
#8  0x00002b121f09e19d in clone () from /lib64/libc.so.6
(gdb) bt

Crash 3:
#0  0x00002b10f9bcdfc5 in raise () from /lib64/libc.so.6
#1  0x00002b10f9bcfa70 in abort () from /lib64/libc.so.6
#2  0x00002b1124d92ce9 in zmq::zmq_abort (errmsg_=0x3d41 <Address 0x3d41 out of bounds>) at err.cpp:76
#3  0x00002b1124da94c8 in zmq::stream_engine_t::write (this=<value optimized out>, data_=<value optimized out>, size_=<value optimized out>) at stream_engine.cpp:517
#4  0x00002b1124da9709 in zmq::stream_engine_t::out_event (this=0x8adb440) at stream_engine.cpp:275
#5  0x00002b1124d923ba in zmq::epoll_t::loop (this=0x2b111c2cf500) at epoll.cpp:158
#6  0x00002b1124db028c in thread_routine (arg_=0x2b111c2cf570) at thread.cpp:83
#7  0x00002b10f956d83d in start_thread () from /lib64/libpthread.so.0
#8  0x00002b10f9c7319d in clone () from /lib64/libc.so.6

# What's the expected result?
It should continue to run, without any crash.

Should we have to move to Jeromq (https://github.com/zeromq/jeromq), which is based on  libzmq 4.1.7 - Since latest releases would have fixed the issues?

Could you advise/help me to solve the issue?

**Comment by bluca** [comment]
The right repository for jzmq issues is: https://github.com/zeromq/jzmq/issues

**Comment by b6arat6** [comment]
Sorry. I will move it

**Comment by b6arat6** [comment]
Moved it to https://github.com/zeromq/jzmq/issues. Closing it
