### ISSUE TITLE
Visual Studio 2013 static library build as part of a bigger solution

### ISSUE THREAD

**Issue by glaure** [zeromq/libzmq#2858]
# Issue description
Trying to use libzmq as part of a bigger solution fails for static library builds.
Though ZMQ_STATIC is set for all projects, the linker complains with:
4>czmq-static.lib(zframe.obj) : error LNK2019: unresolved external symbol __imp_zmq_msg_init referenced in function zframe_new
4>czmq-static.lib(zsock.obj) : error LNK2001: unresolved external symbol __imp_zmq_msg_init
....

The problem seems to be the build optimization using a cmake "object" library.
The "object" library also has to have ZMQ_STATIC set so that zmq.h is correctly preprocessed.

# Environment
Visual Studio 2013
Cmake 3.9 

* libzmq version: 1dd42fe
* OS: Windows 10

# Minimal test code / Steps to reproduce the issue

1.  cmake  -DBUILD_SHARED=OFF -DBUILD_STATIC=ON

# What's the actual result? (include assertion message & call stack if applicable)
4>czmq-static.lib(zframe.obj) : error LNK2019: unresolved external symbol __imp_zmq_msg_init referenced in function zframe_new
4>czmq-static.lib(zsock.obj) : error LNK2001: unresolved external symbol __imp_zmq_msg_init

# What's the expected result?
No linker errors :)

We are currently trying to fix this, and will provide a patch if possible.

**Comment by bluca** [comment]
Makes sense. Could you please send a PR with the fix?

**Comment by bluca** [comment]
@glaure any update? I'd like to move toward release, but if there's a regression in the build system I can't

**Comment by glaure** [comment]
@bluca I hope this can wait until monday. I do not have access to a windows build environment on weekends...

**Comment by bluca** [comment]
Sure that's fine, thanks

**Comment by bluca** [comment]
I'll just revert the optimisation on Windows, there's no way to make it work on Windows given the different builds need different preprocessor flags.

**Comment by southie** [comment]
I second this solution. I am having issues with these optimizations with BUILD_STATIC and BUILD_SHARED both enabled, specifically on Visual Studio 15 2017, though I don't believe the issue is specific to this compiler.
I believe this issue will affect any functions decorated with ZMQ_EXPORT
For MSVC, the preprocessor affects 
 __declspec(dllimport) / __declspec(dllexport) 
It looks like it would also affect some other combinations:
```
#if defined _WIN32
#   if defined ZMQ_STATIC
#       define ZMQ_EXPORT
#   elif defined DLL_EXPORT
#       define ZMQ_EXPORT __declspec(dllexport)
#   else
#       define ZMQ_EXPORT __declspec(dllimport)
#   endif
#else
#   if defined __SUNPRO_C  || defined __SUNPRO_CC
#       define ZMQ_EXPORT __global
#   elif (defined __GNUC__ && __GNUC__ >= 4) || defined __INTEL_COMPILER
#       define ZMQ_EXPORT __attribute__ ((visibility("default")))
#   else
#       define ZMQ_EXPORT
#   endif
#endif
```
