### ISSUE TITLE
Configure errors without pkg-config installed

### ISSUE THREAD

**Issue by cloudOver** [zeromq/libzmq#2859]
# Issue description
./configure --with-libsodium=yes fails when pkg-config is not available. Instead information about missing package, configure script prints such error:

`...
checking for sodium... no
./configure: line 421: test: then: integer expression expected
configure: error: run
./configure: line 310: return: then: numeric argument required
./configure: line 320: exit: then: numeric argument required`

The output is exactly the same as here: https://github.com/zeromq/libzmq/issues/2202 but reason could be different.

# Environment
I'm using Docker container with manually installed gcc, g++, cmake and other dev tools. Unfortunately no pkg-config was installed inside and described error was appearing.

* libzmq 4.2.2
* OS: Debian and Ubuntu installed from Docker

# Minimal test code / Steps to reproduce the issue
Run configure with following options (or just --with-libsodium=yes)
`./configure PKG_CONFIG_PATH=$PKG_CONFIG_PATH:/tmp/libsodium/lib/pkgconfig/ CPPFLAGS=-DPIC CFLAGS=-fPIC CXXFLAGS=-fPIC LDFLAGS=-fPIC --with-libsodium=yes --prefix=/tmp/zeromq/`

# What's the actual result? (include assertion message & call stack if applicable)
Solution: apt-get install pkg-config

# What's the expected result?
It would be great to check first if pkg-config is available, before using it in configure. However this issue is not very important, but solution could save some time for developers using docker as build platform.

**Comment by bluca** [comment]
Could you please send a PR to fix it?

**Comment by jimklimov** [comment]
I had a dejavu effect seeing the title ;)

Addressed this problem for NUT, see analysis and proposed solution at https://github.com/networkupstools/nut/pull/491for inspiration.

I think zproject_autotools.gsl does support trying with pkg-config (though maybe too naively in face of the bugs above) and falls back to just trying to compile with a lib and header - not at a computer now so not certain. I'm not sure if libzmq has the same configure code, though.

**Comment by cloudOver** [comment]
Hi, I don't have any experience with autoconf. The only place where I found suitable to put such condition is autoconf file, but it used to generate configure script only, so it won't be executed during compilation on user's computer.

**Comment by Atrosha** [comment]
I have this issue with pkg-config already installed on Ubuntu 16.04.

I'd tried to add PKG_CONFIG_PATH dirs

Command **echo $(pkg-config --variable pc_path pkg-config)${PKG_CONFIG_PATH:+:}${PKG_CONFIG_PATH}** result
`/usr/local/lib/x86_64-linux-gnu/pkgconfig:/usr/local/lib/pkgconfig:/usr/local/share/pkgconfig:/usr/lib/x86_64-linux-gnu/pkgconfig:/usr/lib/pkgconfig:/usr/share/pkgconfig:/usr/local/lib/pkgconfig:/usr/lib/pkgconfig:/usr/bin/pkgconfig:/usr/bin/pkg-config:/usr/bin/`

Command **whereis pkgconfig** result
`pkgconfig: /usr/lib/pkgconfig /usr/local/lib/pkgconfig /usr/share/pkgconfig`
