### ISSUE TITLE
Next release ?

### ISSUE THREAD

**Issue by gouarin** [zeromq/libzmq#2863]
Hi, 

I would like to know if you plan a new release of libzmq soon.

I use libzmq and cppzmq for our C++ kernel for jupyter (https://github.com/QuantStack/xeus-cling)

We have some issues with conda packages for windows and we want to see if we have the same issues if we use 4.2.2 instead of 4.2.1. The problem is that the CMake files of libzmq are not compatible with the CMake files of cppzmq for the 4.2.2 versions.

**Comment by bluca** [comment]
I'm about to push 4.2.3 - what do you mean by "not compatible"?

**Comment by gouarin** [comment]
Great news !!

`cppzmq` uses the TARGET which is not present in the libzmq 4.2.2 release. But it is now in the `CMakeLists.txt` of `libzmq`.

**Comment by bluca** [comment]
All done and published.

**Comment by gouarin** [comment]
Thanks!

Le 13 déc. 2017 3:09 PM, "Luca Boccassi" <notifications@github.com> a
écrit :

**Comment by gouarin** [comment]
@bluca the file `ZeroMQConfig.cmake.in` is not included in the release. 

Could you add it because it very useful when you want to do

```
find_package(ZeroMQ)
```

Thanks.

**Comment by bluca** [comment]
I guess it needs to be listed in EXTRA_DIST in Makefile.am. Could you please send a PR?

**Comment by gouarin** [comment]
done https://github.com/zeromq/libzmq/pull/2867

**Comment by gouarin** [comment]
If it's ok, @bluca could you update the release ?

**Comment by bluca** [comment]
Sorry, but it's too late - will need to wait for the next one
As a workaround you can use the "Source Code" tarball/zip, it includes everything and for cmake it doesn't really make a difference - the distributable tarball is for the configure; make; make install workflow

**Comment by gouarin** [comment]
OK. Thanks.

Le 13 déc. 2017 8:50 PM, "Luca Boccassi" <notifications@github.com> a
écrit :
