### ISSUE TITLE
Publisher/Subscriber Sockets Not Honoring Send/Receive High Watermarks

### ISSUE THREAD

**Issue by 9ee1** [zeromq/libzmq#2871]
# Issue description
I am having some trouble understanding the behavior I am seeing for Publisher/Subscriber sockets in respect to the send/receive high watermarks.

My basic understanding from the documentation is that the Publisher socket maintains 1 outbound queue for each connected subscriber and it is only impacted by the rate that publisher is able to send messages to that subscriber on the wire, and **not** on how fast the subscriber is processing the messages.

The Subscriber socket maintains 1 incoming queue for each publisher is is connected to and messages are simply lost if the subscriber does not process messages faster than they are received and the watermark is reached.

For the subscriber socket in particular, I  am not seeing this behavior. It seems the watermark is completely ignored. Can someone review this example and help me understand what I am doing wrong, if anything? 

Thanks!

# Environment
* libzmq version (commit hash if unreleased): 4.2.2, compiled as X64
* OS: Windows 10 X64

# Minimal test code / Steps to reproduce the issue
```c
int main()
{
	void* ctx = zmq_ctx_new();
	void* publisherSocket = zmq_socket(ctx, ZMQ_PUB);
	int sendHigh = 0;
	zmq_setsockopt(publisherSocket, ZMQ_SNDHWM, &sendHigh, sizeof(sendHigh));
	
	void* subscriberSocket = zmq_socket(ctx, ZMQ_SUB);
	int receiveHigh = 10;
	zmq_setsockopt(subscriberSocket, ZMQ_RCVHWM, &receiveHigh, sizeof(receiveHigh));	
	
        zmq_bind(publisherSocket, "tcp://localhost:50902");
	zmq_connect(subscriberSocket, "tcp://localhost:50902");
	zmq_setsockopt(subscriberSocket, ZMQ_SUBSCRIBE, "AAAAAA", 6);
	Sleep(5000);
	
	for (int i = 0; i < 1000; i++)
	{
		/* Create a new message, allocating 6 bytes for message content */
		zmq_msg_t msg;
		int rc = zmq_msg_init_size(&msg, 6);
		
		/* Fill in message content with 'AAAAAA' */
		memcpy(zmq_msg_data(&msg), "AAAAAA", 6);
		
		/* Send the message to the socket */
		rc = zmq_msg_send(&msg, publisherSocket, 0);
		printf("Sending message %d\n", i);
		if (rc == -1) {
			printf("%d\n", errno);
			break;
		}
	}

	for (int i = 0; i < 1000; i++)
	{
		/* Create a new message, allocating 6 bytes for message content */
		zmq_msg_t msg;
		int rc = zmq_msg_init(&msg);
		
		/* Send the message to the socket */
               // I EXPECT NO MORE THAN 10 MESSAGES HERE. I GET ALL 1000!
		rc = zmq_msg_recv(&msg, subscriberSocket, 0);
		printf("RECV message %d\n", i);
		
		if (rc == -1) {
			printf("%d\n", errno);
			break;
		}
	}
}
```

# What's the actual result? (include assertion message & call stack if applicable)
I am able to receive all **1000** messages from the subscriber that are sent by the publisher.

# What's the expected result?
I should receive only **10** messages from the subscriber that are sent by the publisher. Everything else should be dropped.

**Comment by 9ee1** [comment]
I just tried his same example with DEALER and ROUTER sockets and got the same behavior. If I set ZMQ_RCVHWM to 10 on the ROUTER, bind the ROUTER, connect the DEALER, and send 1000 messages from the DEALER in an isolated loop, then read the messages in a second isolated loop from the ROUTER, I still get all 1000 messages. Shouldn't 990 them be dropped?

**Comment by 9ee1** [comment]
I found a comment on another ticket, [https://github.com/zeromq/libzmq/issues/2724#issuecomment-327075787](https://github.com/zeromq/libzmq/issues/2724#issuecomment-327075787), that explains that receive high watermarks, **ZMQ_RCVHWM**, are a logical extension to send high watermarks, **ZMQ_SNDHWM**. So a socket will buffer on the receiving end until it hits **ZMQ_RCVHWM**, at which point its peer will buffer on the sending end until it hits **ZMQ_SNDHWM**, at which point, depending on the socket's type and other configuration options, it will either block or drop messages. My unit tests seem to confirm this behavior.

One thing I still can't explain though is this. It seems that unless the **ZMQ_RCVHWM** or **ZMQ_SNDHWM** are a minimum value, they are rounded up somehow. So in my tests, for example, if I set **ZMQ_RCVHWM** and **ZMQ_SNDHWM** to **150** each, I still see a total of **375** messages buffered on both sides, when I should see **300**. But if I set them to any value above **200** each, I get the sum of that number buffered on both sides. So a value of **200** each, for example, will buffer **400** messages. A value of **500** each will buffer **1000** messages.

In general though, the behavior of **ZMQ_RCVHWM** and **ZMQ_SNDHWM** being logical extensions to each other is not very clear from the documentation. I've never contributed to ZeroMQ but if you guys can point me in the right direction, I am happy to contribute a documentation change to make this point more clear.

Thanks!

**Comment by bluca** [comment]
Other factors affect the queues, like the system TCP buffers, and that's why there might be some small deviation

**Comment by laplaceyang** [comment]
I test your code with the situation of 150 hwm in each side, and I just see 300 msgs buffered.

Then, as the first code of your issue, which set the sndhwm to 0, should recv all msg. Because the 0 of hwm means infinite. See [pipe.cpp#L524](https://github.com/zeromq/libzmq/blob/master/src/pipe.cpp#L524).

> I am able to receive all 1000 messages from the subscriber that are sent by the publisher.

Thus, it's the right behavior.

**Comment by bluca** [comment]
@9ee1 have you managed to clarify all doubts? Here's the docs for the HWM options:
https://github.com/zeromq/libzmq/blob/master/doc/zmq_getsockopt.txt#L540
https://github.com/zeromq/libzmq/blob/master/doc/zmq_setsockopt.txt#L624

**Comment by 9ee1** [comment]
@bluca Yes, my doubts have been clarified. Thanks to everyone that has provided feedback. I think though the docs can be updated to clarify the end-to-end behavior. Can I open a pull request to edit the docs at the links you provided?

**Comment by bluca** [comment]
sure

**Comment by 9ee1** [comment]
@bluca, I added a Pull Request with the proposed documentation additions. I will close this ticket and welcome any comments on the pull request itself. Thanks!
