### ISSUE TITLE
Multiple ZMQ_PUB on same port block

### ISSUE THREAD

**Issue by SimonEbner** [zeromq/libzmq#2874]
*Please use this template for reporting suspected bugs or requests for help.*

# Issue description
When I start two ZMQ_PUB sockets in isolated threads with separate contexts, the second call to bind will block. This behaviour is different from ZMQ_PUSH for example. I am aware that it is probably not a bug but is there any chance to get an exception or timeout in that case? 

# Environment

* libzmq version (commit hash if unreleased): v4.2.2
* OS: Ubuntu

# Minimal test code / Steps to reproduce the issue
```
#include <thread>
#include <chrono>
#include <future>
#include <zmq.hpp>

int main()
{
    std::atomic<bool> thread1_ready{false};
    std::atomic<bool> thread2_ready{false};
    
    // launch first publisher
    auto f1 = std::async(std::launch::async, [&] {
        zmq::context_t context(1);
        zmq::socket_t pub(context, ZMQ_PUB);
        std::cout << "Binding socket1" << std::endl;
        pub.bind("tcp://*:5563");
        std::cout << "Bound socket1" << std::endl;
        thread1_ready = true;

        // spin-lock, wait for thread2 to be ready
        while (!thread2_ready)
            std::this_thread::sleep_for(std::chrono::milliseconds(10));
    });

    // launch second publisher on same port
    auto f2 = std::async(std::launch::async, [&] {
        // spin-lock, wait for thread1 to be ready
        while (!thread1_ready)
            std::this_thread::sleep_for(std::chrono::milliseconds(10));

        zmq::context_t context(1);
        zmq::socket_t pub(context, ZMQ_PUB);
        std::cout << "Binding socket2" << std::endl;
        pub.bind("tcp://*:5563");
        std::cout << "Bound socket2" << std::endl;
        thread2_ready = true;
    });

    f1.get();
    f2.get();
    return 0;
}
```

# What's the actual result? (include assertion message & call stack if applicable)
Binding socket1
Bound socket1
Binding socket2

# What's the expected result?
Binding socket1
Bound socket1
Binding socket2
// Exception being thrown or timeout being triggered

**Comment by guidog** [comment]
Read about TCP/IP and how ports are used.
That has nothing to do w/ ZeroMQ.

**Comment by SimonEbner** [comment]
thanks for your reply. Sorry if it's too obvious of a question. Usually when I bind a server I get an exception trying to bind to the same port twice rather than having a blocking call. Is there any way to cause zmq to throw an exception too ?

**Comment by bluca** [comment]
libzmq's zmq_bind does return an error if the binds fail, it's a synchronous API.
You are however using cppzmq, where the behaviour might be different, so you need to reopen the issue here:
https://github.com/zeromq/cppzmq
