### ISSUE TITLE
building problems

### ISSUE THREAD

**Issue by RCYajad** [zeromq/libzmq#2880]
# Issue description
I've used zmq with python before and did not have any trouble with it. However, for my present project, I should use zmq with C++ but I don't know how to. I am using Microsoft Visual Studio 2017 but so far I don't know how to build the library and how to include it with my project to use it.

# Environment

* libzmq version (commit hash if unreleased): libzmq 4.2.3
* OS: Windows 10 x64

**Comment by bluca** [comment]
There's a solution in the builds/msvc/vs2017 subdirectory, you should be able to import it in your VS project

**Comment by RCYajad** [comment]
Thank you for the quick reply! I've already build the solution using visual studio 2017. Though, how do I build the solution with cppzmq? Since I read that I need to have cppzmq in order to use zmq with c++.

**Comment by evoskuil** [comment]
@RCYajad zeromq is c++, you don't need cppzmq or czmqpp :).

**Comment by RCYajad** [comment]
Ohhhhh. How do I configure my present project in visual studio to use with what I've built (I built the libzmq using visual studio)? I apologize for the question as I'm still not familiar with visual studio 2017 and with c++.

**Comment by evoskuil** [comment]
If you want easy and don’t have a lot of experience you might consider a NuGet packaged version.

**Comment by sigiesec** [comment]
libzmq is implemented in C++, but provides a C API, while cppzmq/czmqpp provide a C++ API

**Comment by evoskuil** [comment]
Sure, but the C api is perfectly usable in C++. I used to maintain czmqpp but it wasn’t worth the extra layer. I’m not sure about cppzmq.

**Comment by bluca** [comment]
Closing as it does not appear there are problems left
