### ISSUE TITLE
TCP keep alive don't work 

### ISSUE THREAD

**Issue by hzdx200** [zeromq/libzmq#2882]
*Please use this template for reporting suspected bugs or requests for help.*

# Issue description
TCP_KEEP_ALIVE cannot work in req/rep, sub/pub mode.

# Environment
Ubuntu 16.04.2 LTS
* libzmq version (commit hash if unreleased):  latest
* OS: Linux

# Minimal test code / Steps to reproduce the issue
1.   Client.py
# -*- coding:utf-8 -*-
```
import zmq
import time
context = zmq.Context()
#  Socket to talk to server
print "Connecting to hello world server..."
socket = context.socket(zmq.REQ)
socket.connect ("tcp://localhost:5555")
socket.setsockopt(zmq.TCP_KEEPALIVE,1)
socket.setsockopt(zmq.TCP_KEEPALIVE_CNT,10)
socket.setsockopt(zmq.TCP_KEEPALIVE_IDLE,1)
socket.setsockopt(zmq.TCP_KEEPALIVE_INTVL,1)
#  Do 10 requests, waiting each time for a response
for request in range (1,10):
#print "Sending request ", request,"..."
    socket.send ("Hello")
#  Get the reply.
    message = socket.recv()
    print "Received reply ", request, "[", message, "]"
```

2. Server.py
```
import zmq
import time
#from common import time_utils

context = zmq.Context()
socket = context.socket(zmq.REP)
socket.bind("tcp://*:5555")
socket.setsockopt(zmq.TCP_KEEPALIVE,1)
socket.setsockopt(zmq.TCP_KEEPALIVE_CNT,10)
socket.setsockopt(zmq.TCP_KEEPALIVE_IDLE,1)
socket.setsockopt(zmq.TCP_KEEPALIVE_INTVL,1)
count= 0
while True:
#  Wait for next request from client
    message = socket.recv()
    count+= 1
    print "Received request: ", message, count

#  Do some 'work'
    time.sleep (10)        #   Do some 'work'

    #  Send reply back to client
    socket.send( "123456"+" World")
```

# What's the actual result? (include assertion message & call stack if applicable)
1. I use :tcpdump -i eth0 -w keepalive.cap
2. there is no keep alive in wireshark.

# What's the expected result?
I hope keep alive information can be found in keepalive.cap

**Comment by hzdx200** [comment]
What i understand: if client or server found that there is no data in 1s, keep alive information will be sent every 1s. So, there would be seen in wireshark.

**Comment by bluca** [comment]
From the manpage of zmq_setsockopt:

```
Caution: All options, with the exception of ZMQ_SUBSCRIBE, ZMQ_UNSUBSCRIBE, ZMQ_LINGER, ZMQ_ROUTER_HANDOVER, ZMQ_ROUTER_MANDATORY, ZMQ_PROBE_ROUTER, ZMQ_XPUB_VERBOSE, ZMQ_XPUB_VERBOSER, ZMQ_REQ_CORRELATE, ZMQ_REQ_RELAXED, ZMQ_SNDHWM and ZMQ_RCVHWM, only take effect for subsequent socket bind/connects.
```

http://api.zeromq.org/4-2:zmq-setsockopt

Set the options before binding/connecting.

**Comment by hzdx200** [comment]
Hi, 

Thanks a lot @bluca for your detail instructions, I change the code as instruction and it works very well now :).

David.c.wang

**Comment by bluca** [comment]
No problem, closing now
