### ISSUE TITLE
Cannot link with dynamic library on windows

### ISSUE THREAD

**Issue by JohanMabille** [zeromq/libzmq#2883]
# Issue description

On windows I cannot link with the shared dll. After further investigations, it appears that the `ZeroMQ_LIBRARY` variable is set to `libzmq-NOTFOUND` instead of pointing to the right file.

# Environment

* libzmq version (commit hash if unreleased): 4.2.3
* OS: Windows 10

# Minimal test code / Steps to reproduce the issue
```cmake
cmake_minimum_required(VERSION 3.1)
project(test)

find_package(ZeroMQ REQUIRED)
MESSAGE(STATUS "ZeroMQ_FOUND ${ZeroMQ_FOUND}")
MESSAGE(STATUS "ZeroMQ_LIBRARY ${ZeroMQ_LIBRARY}")
MESSAGE(STATUS "ZeroMQ_STATIC_LIBRARY ${ZeroMQ_STATIC_LIBRARY}")
MESSAGE(STATUS "ZeroMQ_INCLUDE_DIR ${ZeroMQ_INCLUDE_DIR}")
```

# Actual result

```bash
-- ZeroMQ_FOUND 1
-- ZeroMQ_LIBRARY libzmq-NOTFOUND
-- ZeroMQ_STATIC_LIBRARY C:/Users/jmabille/Miniconda3_test/Library/lib/libzmq-mt-s-4_2_3.lib
-- ZeroMQ_INCLUDE_DIR C:/Users/jmabille/Miniconda3_test/Library/include
```
# Expected result

```bash
-- ZeroMQ_FOUND 1
-- ZeroMQ_LIBRARY  C:/Users/jmabille/Miniconda3_test/Library/lib/libzmq-mt-4_2_3.lib
-- ZeroMQ_STATIC_LIBRARY C:/Users/jmabille/Miniconda3_test/Library/lib/libzmq-mt-s-4_2_3.lib
-- ZeroMQ_INCLUDE_DIR C:/Users/jmabille/Miniconda3_test/Library/include
```

# Additional investigations

If I understand correctly, the variable `ZeroMQ_LIBRARY` is set at the end of the file `ZeroMQConfig.cmake`:

```cmake
if(NOT TARGET libzmq AND NOT TARGET libzmq-static)
  include("${CMAKE_CURRENT_LIST_DIR}/ZeroMQTargets.cmake")

  get_target_property(ZeroMQ_INCLUDE_DIR libzmq INTERFACE_INCLUDE_DIRECTORIES)
  get_target_property(ZeroMQ_LIBRARY libzmq LOCATION)
  get_target_property(ZeroMQ_STATIC_LIBRARY libzmq-static LOCATION)
endif()
```

and the different properties of the targets libzmq are set in the `ZeroMQTargets.cmake` and `ZeroMQTargets-release.cmake` files.

In this latter file, if I replace
```cmake
# Import target "libzmq" for configuration "Release"
set_property(TARGET libzmq APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(libzmq PROPERTIES
  IMPORTED_IMPLIB_RELEASE "${_IMPORT_PREFIX}/lib/libzmq-mt-4_2_3.lib"
  )
```
with
```cmake
# Import target "libzmq" for configuration "Release"
set_property(TARGET libzmq APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(libzmq PROPERTIES
  IMPORTED_IMPLIB_RELEASE "${_IMPORT_PREFIX}/lib/libzmq-mt-4_2_3.lib"
  IMPORTED_LOCATION_RELEASE "${_IMPORT_PREFIX}/lib/libzmq-mt-4_2_3.lib"
  )
```
it fixes the problem, however this is a generated file and I don't know (yet) how to tell cmake to generate the `IMPORTED_LOCATION_RELEASE` for shared libraries. I'll have more time to investigate this afternoon, however if someones knows how to fix that, or can give some pointers that help, that will speed up the fix of this issue.

cc @gouarin @SylvainCorlay

**Comment by JohanMabille** [comment]
Ok actually the solution is to use `libzmq` target in the `target_link_library` instead of `ZeroMQ_LIBRARY` variable.

**Comment by SalvoVirga** [comment]
Is this issues closed cause solved or is it planned to be fixed?
Using `libzmq` is a good solution, but I would then expect the varbiable `ZeroMQ_LIBRARY` to not exist at all (or get fixed) - having it but broken only adds confusion.

**Comment by JohanMabille** [comment]
It is solved, the good practice now is to link with the target instead of the library, that is `libzmq`instead of `${ZEROMQ_LIBRARY}`. Now I agree that `ZeroMQ_LIBRARY` should not be defined anymore.
