### ISSUE TITLE
Problem: router handover is sensitive to router-side events

### ISSUE THREAD

**Issue by minrk** [zeromq/libzmq#2892]
# Issue description

ROUTER identity takeover is sensitive to what's happening on the ROUTER socket when the new socket connects, even if there is a very long time separating close of the first socket and connect of the second. General sequence of events:

1. router binds
2. dealer 1 connects with IDENTITY
3. dealer 1 sends message
4. router echoes message
5. dealer 1 receives reply
6. dealer 1 closes
7. router and dealer threads both sleep a significant amount of time
8. dealer 2 connects with same IDENTITY
9. router begins receiving again
10. dealer 2 sends message
11. router never receives dealer 2's message

If steps 8 and 9 are reversed, i.e. if the router is waiting for a message when dealer 2 connects, then no messages are lost and dealer 2 properly takes over the identity. If, instead, the router thread is 'working' (sleep in this case) when dealer 2's connect event occurs, then dealer 2's connection will apparently be rejected.

# Environment

* libzmq version (commit hash if unreleased): 4.2.4 4518e0cc35ffae84b077044c071b3c78e5d4237c (also 4.2.1)
* OS: macOS

# Minimal test code / Steps to reproduce the issue

```python
import sys
from threading import Thread
import time

import zmq

ctx = zmq.Context()
url = 'tcp://127.0.0.1:5555'

print('libzmq-' + zmq.zmq_version())

ROUTER_SLEEP = 0.5
DEALER_SLEEP = 0.4
# if DEALER_SLEEP is less than ROUTER_SLEEP (takeover occurs during ROUTER sleep),
# identity takeover will fail.
# if DEALER_SLEEP is greater than ROUTER_SLEEP (takeover occurs during ROUTER recv),
# identity takeover will succeed.

def router():
    """Background thread echoing ROUTER messages"""
    r = ctx.socket(zmq.ROUTER)
    # setting router_handover will also fix the issue
    r.bind(url)
    while True:
        try:
            print('sleeping')
            time.sleep(ROUTER_SLEEP)
            print('recving')
            msg = r.recv_multipart()
            r.send_multipart(msg)
            print('recvd', msg)
        except KeyboardInterrupt:
            return
    r.close()

def dealer(msg):
    """Connect DEALER and send message, waiting for reply"""
    d = ctx.socket(zmq.DEALER)
    d.rcvtimeo = 3000
    identity = b'identity'
    d.identity = identity
    print('connecting')
    d.connect(url)
    print('sending %s' % msg)
    d.send(msg)
    try:
        assert d.recv() == msg
    except zmq.Again:
        sys.exit("Never received %s!" % msg)
    else:
        print('ok')
    d.close()

t = Thread(target=router, daemon=True)
t.start()

dealer(b'1')
time.sleep(DEALER_SLEEP)
dealer(b'2')

ctx.destroy()
```

# What's the actual result? (include assertion message & call stack if applicable)

If second dealer connects while the router thread is 'working', the second socket connection never completes. If, instead, the second dealer connects while the router thread is blocking in a zmq operation, second dealer takes over from the first.

# What's the expected result?

Handling of lost and resumed connections should not be sensitive to whether zmq API calls are being made at the time. If a long time separates the first socket's close and the second socket's connection (i.e. the close has completed and the router has handled the disconnect), then the second connect should take over the connection.

**Comment by bluca** [comment]
Without looking at anything, this smells like another one of the IO thread vs application state machine thread races.
I hope there will be enough folks at the meeting in Brussels next week to try and sketch a solution for these, as they are the biggest cause of hard-to-fix bug we have.

**Comment by mrvn** [comment]
From the code it looks like ROUTER_HANDOVER should fix the problem. Otherwise it assumes the background threads have finished their housekeeping and evicted the old connection before the DEALER reconnects. And that's just a race condition waiting to trigger.

I think when a connection comes in with an identity that is already in use then that should "flush" all the housekeeping work to see if the old connection isn't already closed.
