### ISSUE TITLE
Pin libzmq core repository to GitHub organization

### ISSUE THREAD

**Issue by jmlemetayer** [zeromq/libzmq#2893]
Not really an issue, but is it possible [to pin](https://github.com/blog/2191-pin-repositories-to-your-github-profile) [this repository](https://github.com/zeromq/libzmq) on top of the [zeromq GitHub organization](https://github.com/zeromq) ?

This way it will be always on top of the organization page.

**Comment by bluca** [comment]
Well if you ask the developers of each implementation, they'll tell you that theirs is the core one :-) So let's keep it "equal"
