### ISSUE TITLE
Problem: Android build scripts not compatible with newer NDK versions

### ISSUE THREAD

**Issue by deonblaauw** [zeromq/libzmq#2894]
When running ./build.sh in the /builds/android directory, I get the following message:

> Android build failed for the following reasons:
  The ANDROID_BUILD_SYSROOT directory does not exist
    /home/deon/android-ndk-r16b-linux-x86_64/android-ndk-r16b//platforms/android-9/arch-arm

I don't have android-9 in my platforms directory, I do however have android-14 all the way to android-27. I then tried changing android_build_helper.sh to use android-27 (line 119):

`ANDROID_BUILD_SYSROOT="${ANDROID_NDK_ROOT}/platforms/android-27/arch-${TOOLCHAIN_ARCH}"`

Running ./build.sh again, I get the following:

> make: *** No rule to make target 'clean'.  Stop.
autoreconf: Entering directory `.'
autoreconf: configure.ac: not using Gettext
autoreconf: running: aclocal -I config --force -I config
autoreconf: configure.ac: tracing
autoreconf: running: libtoolize --copy --force
libtoolize: putting auxiliary files in AC_CONFIG_AUX_DIR, 'config'.
libtoolize: copying file 'config/ltmain.sh'
libtoolize: putting macros in AC_CONFIG_MACRO_DIRS, 'config'.
libtoolize: copying file 'config/libtool.m4'
libtoolize: copying file 'config/ltoptions.m4'
libtoolize: copying file 'config/ltsugar.m4'
libtoolize: copying file 'config/ltversion.m4'
libtoolize: copying file 'config/lt~obsolete.m4'
autoreconf: running: /usr/bin/autoconf --include=config --force
autoreconf: running: /usr/bin/autoheader --include=config --force
autoreconf: running: automake --add-missing --copy --force-missing
configure.ac:56: installing 'config/compile'
configure.ac:14: installing 'config/missing'
Makefile.am: installing 'config/depcomp'
autoreconf: Leaving directory `.'
configure: WARNING: using cross tools not prefixed with host triplet
configure: error: in `/tmp/android_build/arm-linux-androideabi-4.9/libzmq':
configure: error: C preprocessor "/home/deon/android-ndk-r16b-linux-x86_64/android-ndk-r16b/toolchains/arm-linux-androideabi-4.9/prebuilt/linux-x86_64/bin//arm-linux-androideabi-cpp" fails sanity check
See `config.log' for more details

Any ideas?

I'm using Ubuntu 17.10, android NDK r16b.

Thanks!
[config.log](https://github.com/zeromq/libzmq/files/1659842/config.log)

**Comment by faisal00813** [comment]
For any trying to replicate the issue mentioned above do the below changes in android-build-helper.sh in builds directory

These changes have been done for arm64

`ANDROID_BUILD_SYSROOT="${ANDROID_NDK_ROOT}/platforms/android-21/arch-${TOOLCHAIN_ARCH}"`

`function _android_build_opts_process_cxx_stl {
    case "${ANDROID_BUILD_CXXSTL}" in
    stlport_static)
        LIBS+=" -lstlport_static"
        CPPFLAGS+=" -I${ANDROID_NDK_ROOT}/sources/cxx-stl/stlport/stlport"
        case "${TOOLCHAIN_ARCH}" in
        arm64)
            LDFLAGS+=" -L${ANDROID_NDK_ROOT}/sources/cxx-stl/stlport/libs/arm64-v8a"
        ;;
        arm)
            LDFLAGS+=" -L${ANDROID_NDK_ROOT}/sources/cxx-stl/stlport/libs/armeabi"
        ;;
        x86)
            LDFLAGS+=" -L${ANDROID_NDK_ROOT}/sources/cxx-stl/stlport/libs/x86"
        ;;
        mips)
            LDFLAGS+=" -L${ANDROID_NDK_ROOT}/sources/cxx-stl/stlport/libs/mips"
        ;;
        *)
            ANDROID_BUILD_FAIL+=("Unknown combination for ANDROID_BUILD_CXXSTL and TOOLCHAIN_ARCH")
            ANDROID_BUILD_FAIL+=("  ${ANDROID_BUILD_CXXSTL}")
            ANDROID_BUILD_FAIL+=("  ${TOOLCHAIN_ARCH}")
        ;;
        esac
    ;;
    gnustl_shared_49)
        LIBS+=" -lgnustl_shared"
        CPPFLAGS+=" -I${ANDROID_NDK_ROOT}/sources/cxx-stl/gnu-libstdc++/4.9/include"
        case "${TOOLCHAIN_ARCH}" in
        arm)
            LDFLAGS+=" -L${ANDROID_NDK_ROOT}/sources/cxx-stl/gnu-libstdc++/4.9/libs/armeabi"
            CPPFLAGS+=" -I${ANDROID_NDK_ROOT}/sources/cxx-stl/gnu-libstdc++/4.9/libs/armeabi/include"
        ;;
        arm64)
            LDFLAGS+=" -L${ANDROID_NDK_ROOT}/sources/cxx-stl/gnu-libstdc++/4.9/libs/arm64-v8a"
            CPPFLAGS+=" -I${ANDROID_NDK_ROOT}/sources/cxx-stl/gnu-libstdc++/4.9/libs/arm64-v8a/include"
        ;;
        x86)
            LDFLAGS+=" -L${ANDROID_NDK_ROOT}/sources/cxx-stl/gnu-libstdc++/4.9/libs/x86"
            CPPFLAGS+=" -I${ANDROID_NDK_ROOT}/sources/cxx-stl/gnu-libstdc++/4.9/libs/x86/include"
        ;;
        mips)
            LDFLAGS+=" -L${ANDROID_NDK_ROOT}/sources/cxx-stl/gnu-libstdc++/4.9/libs/mips"
            CPPFLAGS+=" -I${ANDROID_NDK_ROOT}/sources/cxx-stl/gnu-libstdc++/4.9/libs/mips/include"
        ;;
        *)
            ANDROID_BUILD_FAIL+=("Unknown combination for ANDROID_BUILD_CXXSTL and TOOLCHAIN_ARCH")
            ANDROID_BUILD_FAIL+=("  ${ANDROID_BUILD_CXXSTL}")
            ANDROID_BUILD_FAIL+=("  ${TOOLCHAIN_ARCH}")
        ;;
        esac
    ;;
    '');;
    *)
        ANDROID_BUILD_FAIL+=("Unknown value for ANDROID_BUILD_CXXSTL")
        ANDROID_BUILD_FAIL+=("  ${ANDROID_BUILD_CXXSTL}")
    ;;
    esac
}`

I wrote this shell script to set env variables
_libzmq_android_build.sh_
`export ANDROID_NDK_ROOT=<path to sdk>/android_sdk/android-ndk-r16b
export TOOLCHAIN_NAME=aarch64-linux-android-4.9
export TOOLCHAIN_HOST=aarch64-linux-android
export TOOLCHAIN_PATH=${ANDROID_NDK_ROOT}/toolchains/${TOOLCHAIN_NAME}/prebuilt/linux-x86_64/bin
export TOOLCHAIN_ARCH=arm64
./build.sh 
`
To trigger build call `sh libzmq_android_build.sh`

I also came across the same error of `sanity check failed`

A workaround for armv7 is on this ticket https://github.com/zeromq/libzmq/issues/1063

Any help for arm64 will be appreciated.
Thanks.

**Comment by bluca** [comment]
As you can see in the CI scripts:

https://github.com/zeromq/libzmq/blob/master/builds/android/ci_build.sh

Our toolchain only supports NDK r11 and ABi 4.9. I think in newer versions google moved from GCC to clang, and thus the scripts in builds/android would need to be updated.

Feel free to do so and send a PR with the fixes - but I'm afraid personally I'm not very familiar with Android development.

**Comment by faisal00813** [comment]
Yes, Clang is prefered now.

Unfortunately, I am also new to android builds and native binary builds.

Any help from experts will be deeply appreciated.
TIA.
