### ISSUE TITLE
SIGSEGV in libzmq zmq::trie_t::check

### ISSUE THREAD

**Issue by Wojtek42** [zeromq/libzmq#2898]
*Please use this template for reporting suspected bugs or requests for help.*

# Issue description
I hit a SIGSEGV using the libzmq library wrapped in jzmq

# Environment
Java(TM) SE Runtime Environment (7.0_79-b15) (build 1.7.0_79-b15)

* libzmq version (commit hash if unreleased): 
4.1.2
jzmq-3.1.0.jar

* OS: 
Linux 2.6.32-642.11.1.el6.x86_64

# Minimal test code / Steps to reproduce the issue

1.  Not able to reproduce.  Occurred once.

# What's the actual result? (include assertion message & call stack if applicable)
Stack: [0x00007f04e2cb8000,0x00007f04e2db9000],  sp=0x00007f04e2db7568,  free space=1021k
Native frames: (J=compiled Java code, j=interpreted, Vv=VM code, C=native code)
C  [libzmq.so.5+0x40cd2]  zmq::trie_t::check(unsigned char*, unsigned long)+0x72

Java frames: (J=compiled Java code, j=interpreted, Vv=VM code)
J 1097  org.zeromq.ZMQ$Socket.recv(I)[B (0 bytes) @ 0x00007f0521230498 [0x00007f0521230460+0x38]

# What's the expected result?
No SIGSEGV

**Comment by bluca** [comment]
Unless you are able to reproduce it with only libzmq, please report that on jzmq issue tracker

**Comment by Wojtek42** [comment]
Thanks.  I've opened https://github.com/zeromq/jzmq/issues/464
