### ISSUE TITLE
call zmq_poll Invalid argument (..\..\..\src\zmq.cpp:918)

### ISSUE THREAD

**Issue by muyanbing** [zeromq/libzmq#2905]
*Please use this template for reporting suspected bugs or requests for help.*

# Issue description
when call zmq_poll using 64-bit application, but 32-bit work.
return 
Assertion failed: Invalid argument (..\..\..\src\zmq.cpp:918)

# Environment

* libzmq version (commit hash if unreleased):  4.0.4
* OS: windows Server 2008R2

# Minimal test code / Steps to reproduce the issue
delphi 
```
    Context := TZMQContext.create;
    Socket := Context.Socket(TZMQSocketType.stRep);
    Poller := TZMQPoller.Create(True, Context);
    Socket.bind('tcp://*:7801');
    Poller.Register(Socket, [pePollIn]);
    while not Context.Terminated do
    begin
      Poller.poll(1000); //Invalid argument (..\..\..\src\zmq.cpp:918)
    ...
```
# What's the actual result? (include assertion message & call stack if applicable)

# What's the expected result?

**Comment by sigiesec** [comment]
The source line of the assertion is this:
https://github.com/zeromq/zeromq4-x/blob/1ac53ed1f75202bbe36dd0b409736f90984638e5/src/zmq.cpp#L918

**Comment by sigiesec** [comment]
Have you tried using the most recent version of libzmq (4.0.8 or 4.2.3)? The code around the line of the assertion has definitely changed since 4.0.4, and maybe the problem is already resolved.

**Comment by muyanbing** [comment]
I tried using 4.0.8 and 4.2.3. 
```
    Context := TZMQContext.create;
    Socket := Context.Socket(TZMQSocketType.stRep);
    Poller := TZMQPoller.Create(True, Context);
    Socket.bind('tcp://*:7801');
    Poller.Register(Socket, [pePollIn]);
    while not Context.Terminated do
    begin
      Poller.poll(1000);
      if pePollIn in Poller.PollItem[0].revents then //always return false
      begin
        
```
