### ISSUE TITLE
use of old poll w/draft APIs?

### ISSUE THREAD

**Issue by WallStProg** [zeromq/libzmq#2906]
# Is it possible to use "old" poll with draft APIs?

We are running into a nasty Heisenbug w/zmq_poll (see below), and would like to be able to narrow it down a bit so we can try to repro the problem.

One thought is that the issue may be related to the "new" poller implementation, which is apparently activated when building with draft APIs enabled.  However, we are also using CLIENT/SERVER sockets for IPC, and would prefer to leave that code alone, at least until we've figured out what the problem is with zmq_poll.

Is there any way to use the draft API for C/S while reverting to the old poller implementation?  

# Environment

* libzmq version (commit hash if unreleased): d17581929cceceda02b4eb8abb054f996865c7a6
* OS: RH/CentOS 5, 6

Note also that we are building libzmq using cmake:

```
cmake -DCMAKE_INSTALL_PREFIX=${INSTALL_PREFIX} -DCMAKE_BUILD_TYPE=${CMAKE_BUILD_TYPE} \
   -DBUILD_STATIC=Off \
   -DWITH_OPENPGM=Off \
   ..
```

# Minimal test code / Steps to reproduce the issue

I wish ...

Unfortunately we only see this during a full-scale stress test at high message rates in our integration test environment.  We have not been able to repro this in a development environment, much less with "pure" ZeroMQ code.

# What's the actual result? (include assertion message & call stack if applicable)

We are seeing frequent but intermittent hangs in zmq_poll(...,-1) when it appears that data is in fact available (this on a SUB socket using TCP).

FWIW, doing a pstack/gstack on the process when it becomes "stuck" immediately un-freezes it, and queued messages are returned to the application as fast as it can process them.  

The process will subsequently hang again after some period of time, and addl pstack/gstack's will unfreeze it.

# What's the expected result?

zmq_poll would return when data is available.

**Comment by bluca** [comment]
There is no facility right now to switch, but it would be easy to add a context option for it in src/zmq.cpp. If you send a PR we'll merge it - incidentally I do think that it would be better to keep the implementations separate, but that's just my opinion. An option for it would be a good idea that makes everyone happy.

**Comment by WallStProg** [comment]
I was thinking more along the lines of simply building with the old poller, rather than being able to select it at run-time, while preserving the ability to use C/S.  

Is that even possible?  Or do the thread-safe socket types require the new poller implementation?

Thanks.

**Comment by bluca** [comment]
IIRC new sockets should work fine with zmq_poll

Feel free to send a PR with a build-time switch if you want, but something like that I think it's well placed for a context option

**Comment by WallStProg** [comment]
I'd be happy to send a PR except I have no idea how to build with the old poller implementation -- hence the question.

The naive option (commenting out the `#define ZMQ_HAVE_POLLER` in zmq.h)  builds but immediately crashes when run.

Any guidance on how to force use of the old poller would be appreciated!

**Comment by WallStProg** [comment]
So, I think I understand it now:

- `zmq_poll` *is* the old poller
- `zmq_poller_poll` is the *new* poller

So any call to `zmq_poll` is by definition using the old implementation.  

To use the new implementation, one must call `zmq_poller_poll` instead:  
> Obviously, `zmq_poller_poll` must have been built, and that is specified by defining `ZMQ_BUILD_DRAFT_API`, which in cmake build at least is triggered by the presence of a `.git` directory in the root of the source tree.

Is this correct?  Thanks again ...

**Comment by WallStProg** [comment]
Never mind -- that's wrong.

Looks like if `ZMQ_BUILD_DRAFT_API` is defined, that causes `ZMQ_HAVE_POLLER` to be defined, and in that case you get the new poller, and there is no way to get the old one:

```
int zmq_poll (zmq_pollitem_t *items_, int nitems_, long timeout_)
{
    //  TODO: the function implementation can just call zmq_pollfd_poll with
    //  pollfd as NULL, however pollfd is not yet stable.
#if defined ZMQ_HAVE_POLLER
    // if poller is present, use that.
    return zmq_poller_poll(items_, nitems_, timeout_);
#else
...
```

I'll see if I can come up with something reasonable for a PR once I've sorted things out on this end.

Thanks again!

**Comment by bluca** [comment]
Yes that's the bit I meant - feel free to send a PR that adds an option for that piece of code

**Comment by WallStProg** [comment]
DId some more digging and it appears that the old zmq_poll implementation does not support the draft socket types (following from socket_base.cpp):

```
 370 int zmq::socket_base_t::getsockopt (int option_, void *optval_,
 371     size_t *optvallen_)
 372 {
 ...
 397         if (thread_safe) {
 398             // thread safe socket doesn't provide file descriptor
 399             errno = EINVAL;
 400             return -1;
 401         }
```

Given that, there is little reason to make the old `zmq_poll` implementation available if `ZMQ_BUILD_DRAFT_API` is defined.

**Comment by bluca** [comment]
agh sorry, I forgot that, my bad

**Comment by WallStProg** [comment]
No worries ...

**Comment by WallStProg** [comment]
Sorry!  Should have updated this issue with the resolution of the root problem.  

This was occurring on RH5.4 (yes I know ...) -- the spurious hang was resolved by upgrading to RH5.11, so presumably a problem in OS implementation.
