### ISSUE TITLE
zsock_resolve may be wrong on lots of socket

### ISSUE THREAD

**Issue by zhuizhuhaomeng** [zeromq/libzmq#2933]
# Issue description

#define ZSOCK_TAG           0x0004cafe
#define ZACTOR_TAG         0x0005cafe

when there are more than 0x0005cafe sockets, zsock_resolve will be wrong for FD.
eg:  fd =  0x0005cafe;
zsock_resolve ((void *) &fd) will be libzmq sokect, which is wrong.

just set  ZSOCK_TAG and  ZACTOR_TAG   to be a bigger number will OK.

# Environment

* libzmq version (commit hash if unreleased): 
* OS: 

# Minimal test code / Steps to reproduce the issue

1.  

# What's the actual result? (include assertion message & call stack if applicable)

# What's the expected result?

**Comment by bluca** [comment]
That is a CZMQ API, so this is the right repository: https://github.com/zeromq/czmq so closing it here.

Also 0x4cafe is 314110 sockets, on what kind of system can you get that many sockets at the same time?

**Comment by zhuizhuhaomeng** [comment]
under pub sub model, maybe on million sockets

**Comment by zhuizhuhaomeng** [comment]
@bluca under pub sub model, maybe on million sockets
