### ISSUE TITLE
Infinite socket SYN after .disconnect() and .close()

### ISSUE THREAD

**Issue by CyrusTheVirusG** [zeromq/libzmq#2948]
*Please use this template for reporting suspected bugs or requests for help.*

# Issue description

Sockets keep attempting to reconnect after being closed.

# Environment
* libzmq version (commit hash if unreleased): 
commit 4c7c9b87bf18b2561e65305dabe5a9bc97624ae1
4.1.6 & 4.2.4
* OS:
 
OSX, latest

# Minimal test code / Steps to reproduce the issue

    import zmq.green as zmq
    import socket
    import time
    import gevent
    
    hostname = socket.gethostname()
    local_ip = socket.gethostbyaddr(hostname)[2][0]
    
    context = zmq.Context.instance()
    server = context.socket(zmq.ROUTER)
    client = context.socket(zmq.DEALER)
    server_port = server.bind_to_random_port('tcp://*')
    client.connect('tcp://{local_ip}:{port}'.format(local_ip=local_ip, port=server_port))
    poller = zmq.Poller()
    poller.register(client, zmq.POLLIN)
    poller.register(server, zmq.POLLIN)
    disconnect_at = time.time() + 5
    client_close_at = time.time() + 10
    close_client = False
    while True:
        events = poller.poll(timeout=1000)
        for event in events:
            socket, something = event
            print(event)
            print(socket.recv())
        tick = time.time()
        if disconnect_at < tick:
            if server:
                if not server.closed:
                    server.close()
                    poller.unregister(server)
                    server = None
        if client_close_at < tick:
            close_client = True
        if close_client:
            if client:
                if not client.closed:
                    client.disconnect('tcp://{local_ip}:{port}'.format(local_ip=local_ip, port=server_port))
                    client.close()
                    poller.unregister(client)
                    client = None
            print("Shouldn't be reconnecting.")
        gevent.sleep(1)
        if client:
            if not client.closed:
                client.send(b"Stuff.")

# What's the actual result? (include assertion message & call stack if applicable)

Sockets send FIN-ACK, but then SYN infinitely. No errors are logged, have to use wireshark or similar to see result.

# What's the expected result?

Sockets that use .connect() should end operation completely upon .close() or .disconnect()

**Comment by CyrusTheVirusG** [comment]
I suppose this could also be a memory leak whereas the socket is not being cleaned up properly.

**Comment by bluca** [comment]
Set linger to 0 if you want a socket to discard queued messages and close immediately

**Comment by CyrusTheVirusG** [comment]
It still makes absolutely no sense. It might make sense on a disconnect if you intend on reconnecting at some point in the future but closing the socket and destroying it should terminate this behavior.

Anyhow setting any linger seems to correct, so thanks.

**Comment by CyrusTheVirusG** [comment]
Additionally, the documentation says the default value should be 30 seconds. Not infinity.

http://api.zeromq.org/4-2:zmq-setsockopt#toc37

**Comment by bluca** [comment]
> It still makes absolutely no sense. It might make sense on a disconnect if you intend on reconnecting at some point in the future but closing the socket and destroying it should terminate this behavior.

I would recommend reading the zguide as it explains many of the default behaviours and their reasons - http://zguide.zeromq.org/

> Anyhow setting any linger seems to correct, so thanks.

Great, closing then.

> Additionally, the documentation says the default value should be 30 seconds. Not infinity.

Sorry about that, it was a mistake in the documentation that went unnoticed. It was fixed last year in https://github.com/zeromq/libzmq/issues/2845
