### ISSUE TITLE
Unit tests not recognized by code coverage measurement

### ISSUE THREAD

**Issue by sigiesec** [zeromq/libzmq#2949]
The unit tests are not recognized by the code coverage measurement. If I read Makefile.am correctly, only the shared library is instrumented for coverage measurement, but the unit tests are run against the static library. 

I am not that familiar with either Makefile.am nor gcov. Is it sufficient/adequate to just apply the same flags ($(CODE_COVERAGE_*FLAGS)) to the the build of libzmq.a as well?

**Comment by bluca** [comment]
If I remember correctly how it works, adding that flags to the unit tests flags should do the trick - have you tried that?

**Comment by sigiesec** [comment]
Not yet, but I will try :)

**Comment by sigiesec** [comment]
Looks good now, thanks for the hint :)
