### ISSUE TITLE
Problem: Missing support for TIPC Port Identities

### ISSUE THREAD

**Issue by eponsko** [zeromq/libzmq#2952]
TIPC supports addressing with location independent addresses (**Port Names**) using a distributed lookup table (`{type,instance}`), and location dependent addresses (**Port Identities**) using randomly assigned port numbers (`<NodeId:Ref>`). The NodeId corresponds to the node address and the reference number is automatically assigned when the socket is created, similar to binding a TCP/UDP port to a random port number.  ZeroMQ only supports Port Names, forcing the user to distribute the port in the lookup table which comes with a small cost. 

As the reference number is randomly assigned by the kernel one cannot bind to a particular reference number, but one can connect to a particular Port Identity if it is known. This means that the address has to be treated differently when binding a socket vs. connecting to a socket. 

Support for using Port Identities is provided in PR #2951. 

- To bind a socket using port identities:   `zmq_bind(s, "tipc://<*>");`
- To connected using port identities: `zmq_connect(s, "tipc://<1.2.3:123456>");`

**Comment by bluca** [comment]
Fixed by https://github.com/zeromq/libzmq/pull/2951

Tests for this would be much welcome
