### ISSUE TITLE
Crash in select_t on windows

### ISSUE THREAD

**Issue by K0n63n** [zeromq/libzmq#2954]
# Issue description

Getting a crash in libzmq at select_t::is_retired_fd()

![callcrash](https://user-images.githubusercontent.com/16082841/36413414-344782d2-1616-11e8-9d70-25d9382fe262.png)

# Environment

* libzmq version: 4.2.3, usepoll = false, compiled with msvc: v140, dynamic, release
* OS: Windows 10

# Minimal test code / Steps to reproduce the issue

1.  Polling a router socket, exact same code works fine on version 4.1.6

# What's the actual result? (include assertion message & call stack if applicable)

![callstack](https://user-images.githubusercontent.com/16082841/36413383-0ba855ea-1616-11e8-9e40-79dc6ce32eb4.png)

**Comment by sigiesec** [comment]
Can you try again with the current master? There have been several fixes in select.cpp since 4.2.3.

If it still happens, can you please post self-contained code that reproduces the issue?

**Comment by K0n63n** [comment]
Ok, just tested with the current master and it looks fine now

**Comment by sigiesec** [comment]
Great :) Probably this was fixed by #2943
