### ISSUE TITLE
unit_test compile error when used for my own project's dependent library

### ISSUE THREAD

**Issue by maony** [zeromq/libzmq#2957]
*Please use this template for reporting suspected bugs or requests for help.*

# Issue description

in my own project, libzmq was used as one of the depentent library.

that is, there exist one top cmake file in my project.

then, when compile unit_test file, unittest_pooller.cpp unittest_ypipe.cpp, there will be compile error，

/unittests/unittest_poller.cpp:22:22: fatal error: poller.hpp: No such file or directory
/unittests/unittest_ypipe.cpp:22:21: fatal error: ypipe.hpp: No such file or directory

maybe the 'CMakeLists.txt' file:

include_directories("${CMAKE_SOURCE_DIR}/include" "${CMAKE_SOURCE_DIR}/src" "${CMAKE_BINARY_DIR}")

should change to

include_directories("${PROJECT_SOURCE_DIR}/include" "${PROJECT_SOURCE_DIR}/src" "${CMAKE_BINARY_DIR}")

# Environment

* libzmq version (commit hash if unreleased):  the newest
* OS: ubuntu

# Minimal test code / Steps to reproduce the issue

1.  

# What's the actual result? (include assertion message & call stack if applicable)

# What's the expected result?

**Comment by bluca** [comment]
@sigiesec could you please have a look when you have a moment?

**Comment by bluca** [comment]
@maony sounds like you are embedding the code directly in your repository - consider using the Ubuntu packages and pkgconfig instead, it will make your life so much easier

**Comment by maony** [comment]
sorry to have not decribed problem clearly.
my project have many dependentions on other libraries, so we have constructed one auto-build tool to pull all of the git projects to keep up with the newest version.

**Comment by maony** [comment]
besides, project should support x86/gpu/arm linux platform meantime.

**Comment by bluca** [comment]
Ubuntu does have arm builds - you should use what the distribution provides if it's there, so you avoid these kind of issues

**Comment by maony** [comment]
sorry for missing some info.
host os: ubuntu
target os: arm-linux
we use cross-compile tool-chains. thanks for your advice, we have changed to the latest release version.

**Comment by sigiesec** [comment]
I don't know if including our CMakeLists.txt is a supported use case? I have never done something like that before for an external library. I am no cmake expert :(

**Comment by bluca** [comment]
Yeah I don't think that's supported or recommended in any way - the existing findpackage stuff should be used instead

**Comment by bluca** [comment]
@maony have you tried with the findpackage functionality instead?

**Comment by sigiesec** [comment]
Can you send a PR to fix that?

**Comment by bluca** [comment]
@maony any update?

**Comment by bluca** [comment]
No updates, closing. Reopen if the issue persists.
