### ISSUE TITLE
Which tool/app does it use to draw diagram in The Guide of ZeroMQ

### ISSUE THREAD

**Issue by 61t** [zeromq/libzmq#2958]
*Please use this template for reporting suspected bugs or requests for help.*

# Issue description

Which tool/app does it use to draw diagram in The Guide of ZeroMQ

# Environment

* libzmq version (commit hash if unreleased): n/a
* OS: n/a

# Minimal test code / Steps to reproduce the issue

n/a

# What's the actual result? (include assertion message & call stack if applicable)

n/a

# What's the expected result?

Draw diagram the same as in The Guide of ZeroMQ

**Comment by 61t** [comment]
As I prefer to do prototyping the same as in The Guide, that is brilliant.

**Comment by bluca** [comment]
This is something you'll want to ask on the zguide repository, which you can find here: https://github.com/booksbyus/zguide

**Comment by 61t** [comment]
Thanks @bluca
