### ISSUE TITLE
Possibly unexpected side effect of setting a socket option

### ISSUE THREAD

**Issue by Vaelatern** [zeromq/libzmq#2959]
# Issue description

When a person calls, from czmq in my case, `zsock_set_curve_server(self, 0)`, or `int myint = 0; zmq_setsockopt(self, ZMQ_CURVE_SERVER, &myint, sizeof(int))`, there is a side effect, from the perspective of the user, that instead of using CURVE encryption the socket is switched to NULL encryption.

https://github.com/zeromq/libzmq/blob/master/src/options.cpp#L451

To compare: `ZMQ_GSSAPI_SERVER`: https://github.com/zeromq/libzmq/blob/master/src/options.cpp#L486

`ZMQ_PLAIN_SERVER`: https://github.com/zeromq/libzmq/blob/master/src/options.cpp#L404

but then a variety of other functions in the same set of options returns the mechanism to `ZMQ_CURVE`.

# Environment

* libzmq version (commit hash if unreleased): 4.2.3
* OS: Void Linux

# Minimal test code / Steps to reproduce the issue

1.  Pick an otherwise working example of CURVE encryption
1. Set the socket option `ZMQ_CURVE_SERVER` to 0 on the client as the last step of setting CURVE encryption.

# What's the actual result? (include assertion message & call stack if applicable)

The client decides to use NULL encryption.

# What's the expected result?

The client is extra certain it's the client (whithout reading the source it is unclear `ZMQ_CURVE_SERVERKEY` also does this (https://github.com/zeromq/libzmq/blob/master/src/options.cpp#L468))

**Comment by bluca** [comment]
0 means disable, 1 means enable - this documented: https://github.com/zeromq/libzmq/blob/master/doc/zmq_setsockopt.txt#L198

**Comment by Vaelatern** [comment]
Then consistency with the `ZMQ_GSSAPI_SERVER` option might be desired?

**Comment by bluca** [comment]
These are stable APIs, so the behaviour is no longer allowed to change
