### ISSUE TITLE
test_pair_tcp.cpp test hangs inside the bounce() function call

### ISSUE THREAD

**Issue by mesegura** [zeromq/libzmq#2962]
*Please use this template for reporting suspected bugs or requests for help.*

# Issue description
The test_pair_tcp.cpp test hangs inside the bounce() function call, specifically the first zmq_recv() call. I've traced this to zmq_recv() => s_recvmsg() => s_->recv() => process_commands() => mailbox->recv() => signaler.wait() => select(). It seems xrecv() fails and it goes into a blocking wait.

# Environment

* libzmq version (commit hash if unreleased): 4.2.3
* OS: VxWorks 6.8

# Minimal test code / Steps to reproduce the issue

1.  Run test_pair_tcp.cpp program as a RTP in VxWorks 6.8

# What's the actual result? (include assertion message & call stack if applicable)
Call Stack:
semBTake() - 0x10148445	
semTake() - 0x10149c49	
select() - 0x100aff63	
selectSc() - 0x100b3201	
syscallDispatch() - 0x100cbdab	
syscallTrapHandle() - 0x1011e9e6	
select() - 0x13264a24	
signaler_t::wait() - signaler.cpp:280	
mailbox_t::recv() - mailbox.cpp:81	
socket_base_t::process_commands() - socket_base.cpp:1346	
socket_base_t::recv() - socket_base.cpp:1251	
s_recvmsg() - zmq.cpp:476	
zmq_recv() - zmq.cpp:501	
bounce() - testutil.hpp:107	
main() - test_pair_tcp.cpp:52	

# What's the expected result?
zmq_recv() call in the bounce() function call should not hang.

**Comment by bluca** [comment]
From my reply to the ML:

``` Do other tests fail? Or only that one?

You can try and add socket monitors to check that the handshake
succeeds:

https://github.com/zeromq/libzmq/blob/master/doc/zmq_socket_monitor.txt

Alternatively, given it's a tcp test, you can use wireshark/tshark with
the zmtp dissector to snoop on the wire:

https://github.com/whitequark/zmtp-wireshark
```

**Comment by mesegura** [comment]
I tried to add socket monitors to check the handshake, but it hangs when trying to read in an event from the monitor socket in the first call to `get_monitor_event()`. It appears to be the same problem with receiving when I called `bounce()` from testutils.hpp.
```
static int get_monitor_event (void *monitor, int *value, char **address) 
{ 
	//  First frame in message contains event number and value 
	zmq_msg_t msg; 
	zmq_msg_init (&msg); 
	if (zmq_msg_recv (&msg, monitor, 0) == -1) 
		return -1;              //  Interrupted, presumably 
	assert (zmq_msg_more (&msg));  

	uint8_t *data = (uint8_t *) zmq_msg_data (&msg); 
	uint16_t event = *(uint16_t *) (data); 
	if (value) 
		*value = *(uint32_t *) (data + 2); 


	//  Second frame in message contains event address 
	zmq_msg_init (&msg); 
	if (zmq_msg_recv (&msg, monitor, 0) == -1) 
		return -1;              //  Interrupted, presumably 
	assert (!zmq_msg_more (&msg)); 


	if (address) { 
		uint8_t *data = (uint8_t *) zmq_msg_data (&msg); 
		size_t size = zmq_msg_size (&msg); 
		*address = (char *) malloc (size + 1); 
		memcpy (*address, data, size); 
		(*address)[size] = 0; 
	} 
	return event; 
} 


int main (void)
{
    setup_test_environment();
    size_t len = MAX_SOCKET_STRING;
    char my_endpoint[MAX_SOCKET_STRING];
    void *ctx = zmq_ctx_new ();
    assert (ctx);

    //  We'll monitor these two sockets
    void *sb = zmq_socket (ctx, ZMQ_DEALER);
    assert (sb);
    void *sc = zmq_socket (ctx, ZMQ_DEALER);
    assert (sc);
    
    //  Monitor all events on client and server sockets
    int rc = zmq_socket_monitor (sc, "inproc://monitor-client", ZMQ_EVENT_ALL); 
    assert (rc == 0); 
    rc = zmq_socket_monitor (sb, "inproc://monitor-server", ZMQ_EVENT_ALL); 
    assert (rc == 0); 

    //  Create two sockets for collecting monitor events 
    void *client_mon = zmq_socket (ctx, ZMQ_PAIR); 
    assert (client_mon); 
    void *server_mon = zmq_socket (ctx, ZMQ_PAIR); 
    assert (server_mon); 

    //  Connect these to the inproc endpoints so they'll get events 
    rc = zmq_connect (client_mon, "inproc://monitor-client"); 
    assert (rc == 0); 
    rc = zmq_connect (server_mon, "inproc://monitor-server"); 
    assert (rc == 0); 

    
    rc = zmq_bind (sb, "tcp://127.0.0.1:*");
    assert (rc == 0);
    rc = zmq_getsockopt (sb, ZMQ_LAST_ENDPOINT, my_endpoint, &len);
    assert (rc == 0);
    rc = zmq_connect (sc, my_endpoint);
    assert (rc == 0);
    
    //bounce (sb, sc);
    
    //Client events
    int event = get_monitor_event (client_mon, NULL, NULL); 
    if (event == ZMQ_EVENT_CONNECT_DELAYED) 
    	event = get_monitor_event (client_mon, NULL, NULL); 
    assert (event == ZMQ_EVENT_CONNECTED); 
    event = get_monitor_event (client_mon, NULL, NULL); 

    //Server events
    event = get_monitor_event (server_mon, NULL, NULL); 
    assert (event == ZMQ_EVENT_LISTENING); 
    event = get_monitor_event (server_mon, NULL, NULL); 
    assert (event == ZMQ_EVENT_ACCEPTED); 
    event = get_monitor_event (server_mon, NULL, NULL); 


    rc = zmq_close (sc);
    assert (rc == 0);

    rc = zmq_close (sb);
    assert (rc == 0);

    rc = zmq_ctx_term (ctx);
    assert (rc == 0);

    return 0 ;
}
```

**Comment by bluca** [comment]
It's a new platform right? My best guess is that polling is not working - in the unittest directory there's a poller test, try that one

**Comment by mesegura** [comment]
Yes, its a new platform that maybe should be added to the repo once I get it working. I'll try the poller test next and let you know how it goes. Thank you.

**Comment by mesegura** [comment]
I've resolved it! It's working on Vxworks 6.8!

**Comment by bluca** [comment]
Great, feel free to send a PR if you have any code changes. I'm not familiar with vxworks, che IPC code relies on Unix file based sockets, it might not be supported on that system, check it out.

**Comment by mesegura** [comment]
VxWorks does have IPC (AF_UNIX) through the Connection-Oriented Message Passing protocol (COMP) component of the Kernel, but the socket name format is different, e.g. "ipc:///comp/socket/0x345". Abstract IPC sockets resolve to "ipc:///comp/socket/0xN" where N is some hex number. Also, there is no SOCK_STREAM socket type for AF_UNIX, only SOCK_SEQPACKET.

When I try the socket monitor code with IPC sockets, I get an assertion fail on the `assert (event == ZMQ_EVENT_CONNECTED)` line.
```
    //Client events
    int event = get_monitor_event (client_mon, NULL, NULL); 
    if (event == ZMQ_EVENT_CONNECT_DELAYED) 
    	event = get_monitor_event (client_mon, NULL, NULL); 
    assert (event == ZMQ_EVENT_CONNECTED); 
```

**Comment by bluca** [comment]
Check what the event is - probably an error.

ipc:// uses SOCK_STREAM, if VxWorks doesn't support it you'll have to provide a different implementation.

I'm not sure how the VxWorks kernel works, but at least in Linux nowadays a TCP loopback (127.0.0.1) connection is not too different from AF_UNIX connection, so you might get away with skipping it entirely and just use TCP.

**Comment by mesegura** [comment]
I think I'll use your TCP workaround if I need inter process communications. I think I'll be using inproc:// and TCP mostly.

I'll send a PR once I've cleaned up my code changes a bit.

**Comment by bluca** [comment]
If IPC does not work, remember to add the ifdefs to disable it via ifdefs like on windows, for example: https://github.com/zeromq/libzmq/blob/master/src/ipc_connecter.cpp#L33

**Comment by mesegura** [comment]
I shifted and added a few things in my main() of my test routine, and I noticed that the server socket events don't have a ZMQ_EVENT_CLOSED, but instead a ZMQ_EVENT_DISCONNECTED in its place. 
```
    bounce (sb, sc);

    rc = zmq_close (sc);
    assert (rc == 0);

    rc = zmq_close (sb);
    assert (rc == 0);

    //Client events
    int event = get_monitor_event (client_mon, NULL, NULL); 
    if (event == ZMQ_EVENT_CONNECT_DELAYED) 
    	event = get_monitor_event (client_mon, NULL, NULL); 
    assert (event == ZMQ_EVENT_CONNECTED); 
    event = get_monitor_event (client_mon, NULL, NULL); 
    assert (event == ZMQ_EVENT_MONITOR_STOPPED); 

    //Server events
    event = get_monitor_event (server_mon, NULL, NULL); 
    assert (event == ZMQ_EVENT_LISTENING); 
    event = get_monitor_event (server_mon, NULL, NULL); 
    assert (event == ZMQ_EVENT_ACCEPTED);
    event = get_monitor_event (server_mon, NULL, NULL); 
    assert (event == ZMQ_EVENT_CLOSED); 
    event = get_monitor_event (server_mon, NULL, NULL); 
    assert (event == ZMQ_EVENT_MONITOR_STOPPED); 

    rc = zmq_ctx_term (ctx);
    assert (rc == 0);
```
Also, even though the TCP/IP socket transfers in `bounce()` pass, the `zmq_ctx_term()` call hangs if I comment out the following:

```
    assert (event == ZMQ_EVENT_CLOSED); 
    event = get_monitor_event (server_mon, NULL, NULL); 
    assert (event == ZMQ_EVENT_MONITOR_STOPPED); 
```

**Comment by bluca** [comment]
The events can depend on which order things happen in the background, so that's ok. Set linger to 0 just after you create the sockets to avoid the context waiting for all messages to be delivered (other events I imagine)

**Comment by mesegura** [comment]
That makes sense. The original test_pair_tcp.cpp passes/doesn't hang.
