### ISSUE TITLE
zmq_socket assert failed on signaler.cpp:589 with errno set to ENOTSOCK

### ISSUE THREAD

**Issue by cuteshell** [zeromq/libzmq#2968]
# Issue description
when I create a ZMQ_PAIR socket using zmq_socket in multithread program, restart the program all the time, then the error occurs sometimes. 

# Environment
OS is windows 10
IDE is visual studio 2013

* libzmq version (commit hash if unreleased): 
zmq version is 4.2.3 released

* OS: 
windows 10
# Minimal test code / Steps to reproduce the issue

create the socket in a thread using these code, the `gContext` is a global context have inited.
`void *dataSocket = zmq_socket(gContext, ZMQ_PAIR)`

# What's the actual result? (include assertion message & call stack if applicable)

assert message is: Assertion failed: Socket operation on non-socket(..\..\..\src\signaler.cpp:589)

![notsock](https://user-images.githubusercontent.com/16982751/36956259-5973bb5a-2068-11e8-8e43-4e7a49787a89.png)

# What's the expected result?
expect zmq_socket always success

**Comment by sigiesec** [comment]
This sounds like some race/memory corruption in your program, though it is hard to tell without having the program. Can you reduce your program to a minimal test case that reproduces the problem?

**Comment by cuteshell** [comment]
Thanks, I cann't reproduces the problem now .no memory overflow or double free have been found yet.  I encounter zmq_socket return succcess and zmq_msg_send return nonsock sometimes.  May be it caused by a virus? I will continue to check my own code and the running environment.

**Comment by bluca** [comment]
@cuteshell any update?

**Comment by bluca** [comment]
No updates, closing. Reopen if the issue returns.

**Comment by cuteshell** [comment]
This problem has been solved. I use a log library written by my colleague, In the library, he create and close a udp socket using windows raw api, such as `socket` and `closesocket`, but store this socket in a global variable. We use this log library in multi-thread. when change this global variable to local variable. the non-socket issue disapper.

Hope these can help others.
