### ISSUE TITLE
Are there some zmq logs to say "ZMQ_PUSH socket enters the mute state" 

### ISSUE THREAD

**Issue by hzdx200** [zeromq/libzmq#2975]
*Please use this template for reporting suspected bugs or requests for help.*

# Issue description
Version used is 4.0-x
I used ZMQ push-pull peers to communicate; push peer is used in windows, pull peer is used in linux;
peer works ok for 4 hours more or less, suddenly push peer block here: 'zmq_send' message fucntion, (I don't know why and when, it's wired to me now) and also the app cannot be terminated with command < ctr+c >
I have to close the app with 'close' button in 'CMD' window.
After restart APP(I didn't restart pull peer at all), the communication works well.

I saw there are discriptions about push peer in zeromq offical API manual page.
<<When a ZMQ_PUSH socket enters the mute state due to having reached the high water mark for all downstream nodes, or if there are no downstream nodes at all,>>
I supposed whether the high water mark is beyond in all downstream nodes firstly.
But, not big data is sent actually at that time.
I supposed there is disconnection between push-pull peers.
But I don't know how could I find some logs about the disconnection.
Well, sorry to say so much...
it meant that how could I find logs to help me to located about this :"ZMQ_PUSH socket enters the mute state"

Also, if ZMQ_PUSH socket enters the mute state, "then any zmq_send(3) operations on the socket shall block". Does it mean that send function will hang there and <ctr+c> cannot terminate it?

# Environment
push peer in windows, pull peer in linux
* libzmq version (commit hash if unreleased): 
* OS: 

# Minimal test code / Steps to reproduce the issue

1.  

# What's the actual result? (include assertion message & call stack if applicable)

# What's the expected result?

**Comment by hzdx200** [comment]
I forgot to say: thanks in advance...

**Comment by sigiesec** [comment]
It's hard to say why you cannot terminate your application. This is nothing that libzmq directly controls. 

But yes, without setting a send timeout, zmq_send might block forever. Since the problem resolves when you restart the PUSH side only, it could be a bug on that side.

Can you try with a more recent libzmq version (4.2.3 or master) at least on the PUSH side?

**Comment by bluca** [comment]
Ctrl c depends entirely on your application, there is no signal handling in libzmq.

To avoid blocking when sending, use the ZMQ_DONTWAIT flag in zmq_msg_send and it will return -1 with errno EAGAIN if it would have blocked. See the zmq_msg_send manage.

**Comment by hzdx200** [comment]
Thanks a  lot for your comments. @sigiesec and @bluca.
I will try to add timeout or ZMQ_DONTWAIT flag firstly, if this still happen, I will try to upgrade the libzmq version.
This issue can be closed and new findings can be shared later in new issue ticket.

**Comment by ns-lwu** [comment]
@hzdx200  did you still have this issue after upgrading the libzmq version?
