### ISSUE TITLE
CMake import targets do not have the target-property IMPORTED_LOCATION_<CONFIG> set

### ISSUE THREAD

**Issue by wittmeie** [zeromq/libzmq#2985]
*Please use this template for reporting suspected bugs or requests for help.*

# Issue description
The CMake import-targets, generated by the Windows install rules, do not have the `IMPORTED_LOCATION_<CONFIG>` property set. Hence, it is not possible for a consumer project to install the ZeroMQ DLL as part of their packaging (e.g. via `install(FILES $<TARGET_FILE:${IMPORT_TARGET}> INSTALL_PATH)`)

# Environment

* libzmq version (commit hash if unreleased): 9c748f1bf1c039dd1f13927f5df3c8c16e3617dc
* OS: Windows

# Minimal test code / Steps to reproduce the issue

1.  Compile libzmq under Windows

# What's the actual result? (include assertion message & call stack if applicable)
The generated `ZeroMQTargets-<CONFIG>.cmake` file sets the following target properties:
`set_property(TARGET libzmq APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(libzmq PROPERTIES
  IMPORTED_IMPLIB_RELEASE "${_IMPORT_PREFIX}/lib/libzmq-v141-mt-4_2_4.lib"
)`

# What's the expected result?
The import target should also have the `IMPORTED_LOCATION_<CONFIG>` property set:
`set_property(TARGET libzmq APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(libzmq PROPERTIES
  IMPORTED_IMPLIB_RELEASE "${_IMPORT_PREFIX}/lib/libzmq-v141-mt-4_2_4.lib"
  IMPORTED_LOCATION_RELEASE "${_IMPORT_PREFIX}/bin/libzmq-v141-mt-4_2_4.dll"
  )`

**Comment by sigiesec** [comment]
Do you know how to achieve that? It would be great if you sent a PR :)

**Comment by bluca** [comment]
Fixed by https://github.com/zeromq/libzmq/pull/2986
