### ISSUE TITLE
fd leak use zmq api

### ISSUE THREAD

**Issue by jinhz** [zeromq/libzmq#2993]
*Please use this template for reporting suspected bugs or requests for help.*

# Issue description
fd not released call zmq_close( ) with pattern ZMQ_REQ  and ZMQ_DEALER

# Environment

* libzmq version (commit hash if unreleased): ØMQ/4.2.3 and 4.1.6
* OS: Linux 66e6a3224aea 4.4.0-116-generic #140~14.04.1-Ubuntu SMP Fri Feb 16 09:25:20 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

# Minimal test code / Steps to reproduce the issue

1.  
#include <stdio.h>
#include <stdlib.h>
#include "zmq.h"

int main( int argc, char *argv[] )
{
     uint32_t linger_time = 0;
     void *context    = NULL;
     void *socket = NULL;
 
     printf("----init\n");
     system("ls -l /proc/$(pidof main)/fdinfo | wc -l");
     context = zmq_ctx_new();
     if(NULL == context)
        return -1;

     printf("----create context\n");
     system("ls -l /proc/$(pidof main)/fdinfo | wc -l");
     socket = zmq_socket(context, ZMQ_REQ);
     if(NULL ==socket)
         return -1;

     zmq_setsockopt(socket, ZMQ_LINGER, &linger_time, sizeof(linger_time));
     printf("----open socket\n");
     system("ls -l /proc/$(pidof main)/fdinfo | wc -l");
    
     zmq_close(socket);
     printf("----close socket fd\n");
     system("ls -l /proc/$(pidof main)/fdinfo | wc -l");

     zmq_ctx_destroy(context);
     printf("----destroy context fd\n");
     system("ls -l /proc/$(pidof main)/fdinfo | wc -l");
     
     return 0;
}

2.gcc main.c -o main -lzmq
# What's the actual result? (include assertion message & call stack if applicable)
----init
4
----create context
6
----open socket
11
----close socket fd
10
----destroy context fd
4

# What's the expected result?
 after call zmq_close( ), the FD is back to normal

**Comment by sigiesec** [comment]
One thing to note here is that zmq_close works asynchronously, so the socket is unlikely to be actually closed on return of zmq_close. ZeroMQ uses various fds internally, depending on the polling mechanism configured at build time. Actually, since you did not connect or bind your socket, none of the fds will be a socket used for external communication.

**Comment by bluca** [comment]
As Simon said the close is asynchronous - your own test shows that after destroying the context, which is synchronous, everything is fine, so I'll mark this as solved.
