### ISSUE TITLE
Extensive redundancies in Makefile.am

### ISSUE THREAD

**Issue by sigiesec** [zeromq/libzmq#2996]
Makefile.am contains extensive redundancies, which makes them hard to read and maintain. I am not at all familiar with autotools, but I cannot imagine that this is necessary.

One example is the specification of flags and link libraries for the test programs, for example:
```
tests_test_connect_resolve_LDADD = src/libzmq.la ${UNITY_LIBS}
tests_test_connect_resolve_CPPFLAGS = ${UNITY_CPPFLAGS}
```

Since these apply to many test programs (in the end, to all test programs), it would be desirable to only specify these at one point.

Maybe this can be achieved by creating sub-Makefiles, which have their own global settings? I also read somewhere than autogen can be used to address such redundancies.

**Comment by bluca** [comment]
Recursive automake is a pain in the back, full of bugs, race conditions and various issues, so it's really not something we should do

**Comment by bluca** [comment]
There are global flags but those affect everything (AM_CPPFLAGS etc), not sure if there are test-specific ones - automake is very verbose and very obnoxious, unfortunately
