### ISSUE TITLE
XPUB subscription messages are lost when IPv6 is enabled

### ISSUE THREAD

**Issue by lytboris** [zeromq/libzmq#3000]
# Issue description
When IPv6 is enabled on XPUB socket, no subscription events (regardless of ZMQ_XPUB_VERBOSE and/or ZMQ_XPUB_VERBOSER being set) can be read from socket. zmq_recv will block forever.

# Environment

* libzmq version (commit hash if unreleased): 4.2.2 and 4.2.3 
* OS: FreeBSD

# Minimal test code / Steps to reproduce the issue
https://github.com/lytboris/libzmq/commit/ea2db8961d4ab667eb8c34b5d09b2209dc1e9feb
I compiled this test without unity using
`clang++ -lpthread t.cpp ../src/.libs/libzmq.a`
(Yes, I use static linking)

# What's the actual result? (include assertion message & call stack if applicable)
>blocking read on pub bound to tcp://127.0.0.1:7777 ...DONE
blocking read on pub bound to tcp://[::1]:7777 ...DONE

# What's the expected result?
>blocking read on pub bound to tcp://127.0.0.1:7777 ...DONE
blocking read on pub bound to tcp://[::1]:7777 ...[1]    87897 alarm      ./a.out

**Comment by bluca** [comment]
That test enables IPv6 only on the PUB socket, not on the SUB. If you do that on the SUB it will then work.
There's a zmq_ctx_set option if you want to enable IPv6 globally.

**Comment by lytboris** [comment]
Indeed, thanks.
