### ISSUE TITLE
s_recv in zhelpers.h is incompatible with auto-assigned DEALER identities in v3.0 and later 

### ISSUE THREAD

**Issue by prutschman** [zeromq/libzmq#3010]
The C examples in the guide make frequent use of the helper function s_recv (in zhelpers.h) to receive frames. It maps received frames to C strings, and as a result, is incompatible with embedded null characters.

The examples in the guide for router sockets use s_recv to get the dealer identity. These examples also have the dealers explicitly set C-string compatible identities. As a result, the example works as written.

Prior to v3.0, dealers which didn't request an identity got a C-string compatible UUID. in v3.0 and later, they get a 5-byte sequence beginning with a null byte.

The example code is unaffected by this change, but if used as the basis for an application, the resulting router will be unable to communicate with dealers that don't set an explicit identity; s_recv will return an empty C string.

This can't be fixed without either changing the s_recv API, or changing the example not to use it. It would be prudent, however, to expressly call this limitation out in the example code.

**Comment by prutschman** [comment]
To the documentation's credit, this is called out in the section "A Minor Note on Strings." It would be worth including the caveat that the library itself will generate identities inconsistent with the assumption stated there.

**Comment by bluca** [comment]
The guide's repository is not here, it's at this link: https://github.com/booksbyus/zguide
Please open an issue, or even better a PR with a fix, on that repository

**Comment by prutschman** [comment]
Sorry about that. Re-filed at https://github.com/booksbyus/zguide/issues/733
