### ISSUE TITLE
Source install does not pass any tests

### ISSUE THREAD

**Issue by aytekinar** [zeromq/libzmq#3012]
### Environment

I am using Arch Linux with the following:

```
~> uname -a
Linux KTH-5435 4.15.8-1-ARCH #1 SMP PREEMPT Sat Mar 10 00:00:33 UTC 2018 x86_64 GNU/Linux
```

### Steps to reproduce

I run the following set of commands on my `fish` shell to install `v4.2.3` from source:

```fish
~> git clone https://github.com/zeromq/libzmq
~> cd libzmq/
~> git checkout -b install v4.2.3 
~/libzmq> mkdir build install
~/libzmq> cd build
~/l/build> cmake -D CMAKE_INSTALL_PREFIX=../install -D WITH_DOC=0 -D WITH_LIBSODIUM=1 -D WITH_OPENPGM=1 -D LIBZMQ_WERROR=1 -G Ninja ../ > cmake.log ; and cmake --build . > build.log ; and cmake --build . --target test > test.log
```

The last command returns with error. I have attached the corresponding [cmake.log](https://github.com/zeromq/libzmq/files/1834084/cmake.log), [build.log](https://github.com/zeromq/libzmq/files/1834083/build.log) and [test.log](https://github.com/zeromq/libzmq/files/1834085/test.log) files.

I would appreciate if you helped me resolve the

```
/usr/bin/ld: warning: cannot find entry symbol rrwarn=%all; defaulting to 0000000000002090
```

type of warnings. I guess this is the problem that results in segfaults in the test phase.

**Comment by bluca** [comment]
Don't use ninja - nobody supports it. Just use make.

**Comment by aytekinar** [comment]
FYI, dropping the `-G Ninja` results in the same. I think the problem is on the line below:

https://github.com/zeromq/libzmq/blob/7fb3bdd59a506d3c6dc8de45aeb64dc37b8c9b95/CMakeLists.txt#L301

When I change my compiler with `env CC=/usr/bin/clang CXX=/usr/bin/clang++ cmake ...` and compile with LLVM, that switch is ignored by LLVM and everything proceeds as normal. Then, when I disable `LIBZMQ_WERROR` by setting it to `0`, it builds and passes the tests, again.

**Comment by sigiesec** [comment]
I think -errwarn is an option of the Sun compiler, probably this check is supposed to fail with gcc.
But apparently it doesn't with your gcc version (7.3.0), which is very recent, and probably not widely used yet.

**Comment by aytekinar** [comment]
I see. I think it passes this option directly to `ld`, which creates other problems, I assume, by checking the build log. For now, I will disable WERROR, then?

**Comment by sigiesec** [comment]
Can you try to change this to
```
if (NOT "${CMAKE_CXX_COMPILER_ID}" STREQUAL "GNU")
    zmq_check_cxx_flag_prepend ("-errwarn=%all") 
endif()
```

If it works, please send a PR with the change :)
