### ISSUE TITLE
zmq_poller_wait_all corner case

### ISSUE THREAD

**Issue by sigiesec** [zeromq/libzmq#3022]
# Issue description

Inconsistent handling of zmq_poller_wait_all corner case. With n_events == 0, it should be allowed to pass NULL as events, since events may not be dereferenced anyway.

# Environment

* libzmq version (commit hash if unreleased):  #4.2.3
* OS: any

# Minimal test code / Steps to reproduce the issue

```
void *poller = zmq_poller_new();
long timeout_ms = 50; // any value except -1
TEST_ASSERT_FAILURE_ERRNO(EAGAIN, zmq_poller_wait_all (poller, NULL, 0, timeout_ms))
```

# What's the actual result? (include assertion message & call stack if applicable)

Test case fails, actual errno = EFAULT.

# What's the expected result?

EAGAIN is returned after sleeping for timeout_ms.

**Comment by bluca** [comment]
Not sure, sorry, haven't really used this API yet - @somdoron what do you think?
