### ISSUE TITLE
Build.bat script incorrect for Visual Studio 2017 Enterprise

### ISSUE THREAD

**Issue by dirkdokter** [zeromq/libzmq#3026]
# Issue description
When building using build.bat in the VS2017 Enterprise Dev Command Prompt, the build script fails, due to an incorrectly determined value of VSVER.

C:\ROOT_PATH\libzmq\builds\msvc\build>build.bat
*** ERROR, build tools not found: Microsoft Visual Studio **ri.0**\VC\vcvarsall.bat`

Variables in build.bat script:
`%VSINSTALLDIR%  = C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\`

In build.bat, `VSVER `is set to `%VSINSTALLDIR:~-5,2%`, which is obviously incorrect for this path.

# Environment
* libzmq version (commit hash if unreleased):  4.2.5
* OS: Windows 7, Visual Studio 2017 Enterprise

**Comment by bluca** [comment]
Could you send a or to fix it?

**Comment by dirkdokter** [comment]
Sure! Will be next week though.

**Comment by bluca** [comment]
The solutions are getting deprecated, the supported way is to use CMake to generate them nowadays, so closing.
