### ISSUE TITLE
Add cygwin CI jobs on Appveyor

### ISSUE THREAD

**Issue by sigiesec** [zeromq/libzmq#3030]
Currently, there are no cygwin CI jobs on Appveyor, but it should be supported. To ensure that support does not break unnoticed, CI jobs should be added.

**Comment by bluca** [comment]
Would be nice indeed, is it possible at all on Appveyor to use different toolchains than visual studio?

**Comment by sigiesec** [comment]
Yes, they have both cygwin and mingw installed by default.

**Comment by bluca** [comment]
Ah great, I had no idea

**Comment by sigiesec** [comment]
Here is example where builds are run using cygwin and mingw:
https://github.com/libyal/libbde/blob/master/appveyor.yml

**Comment by sigiesec** [comment]
In the best case, it suffices to start the ci_build.sh used on travis in a cygwin/mingw bash. But probably there are some caveats ;)
