### ISSUE TITLE
App crashed with abort signal

### ISSUE THREAD

**Issue by nayabbashasayed** [zeromq/libzmq#3043]
Hi again,

I am using radio / dish communication between multiple devices. I see that app is crashing at least once in a few hours with the abort signal from ZeroMQ library. I couldn't find the exact reason for that crash though I have the following debug information regarding this.
>(gdb) bt
#0  0xb6bb4424 in __GI_raise (sig=sig@entry=6) at libpthread/nptl/sysdeps/unix/sysv/linux/raise.c:67
#1  0xb6bae7f0 in __GI_abort () at libc/stdlib/abort.c:89
#2  0xb6e8ced0 in zmq::fq_t::~fq_t (this=0x0, __in_chrg=<optimized out>) at src/fq.cpp:44
#3  0xb6e8ced0 in zmq::fq_t::~fq_t (this=0x0, __in_chrg=<optimized out>) at src/fq.cpp:44
Backtrace stopped: previous frame identical to this frame (corrupt stack?)

# Environment

* libzmq version (commit hash if unreleased): 4.2.3
* OS: Linux with kernel version 3.14

Since I am not much into CPP code, I am not able to figure it out how to avoid this crash and reason behind the crash.

**Comment by bluca** [comment]
> Backtrace stopped: previous frame identical to this frame (corrupt stack?)

This suggests that the application is corrupting the stack, try running it in valgrind, it should spot these problems

Without at least a full decoded backtrace it's impossible to see what's happening
