### ISSUE TITLE
Aborts when iOS abuses EBADF to report a socket has been reclaimed

### ISSUE THREAD

**Issue by acsearle** [zeromq/libzmq#3046]
# Issue description

ZeroMQ intermittently calls abort() on iOS.

iOS abuses EBADF to report that a socket can no longer be used because its resources have been reclaimed while the app was in the background.  Apple documents this behaviour here:

https://developer.apple.com/library/content/technotes/tn2277/_index.html#//apple_ref/doc/uid/DTS40010841-CH1-SUBSECTION3

ZeroMQ asserts on the errno value EBADF in multiple locations, interpreting it as an impossible value indicating an internal error, so iOS apps with open sockets will intermittently crash after waking from background.

# Environment

* libzmq version (commit hash if unreleased): 4.2.3
* OS: iOS 11.2.6

# Minimal test code / Steps to reproduce the issue

Repeatedly sleep and wake an iOS device while running an app with an open ZeroMQ socket.

# What's the actual result? (include assertion message & call stack if applicable)

"Bad file descriptor (src/tcp_connecter.cpp:403)"
(aborts)

# What's the expected result?

On iOS only, treat EBADF like any other "networking problem", and recover by closing and attempting to reconnect.

**Comment by sigiesec** [comment]
There is no libzmq version 4.3.2, you probably meant 4.2.3?

**Comment by acsearle** [comment]
Sorry, corrected.

**Comment by bluca** [comment]
Fixed by https://github.com/zeromq/libzmq/pull/3047
