### ISSUE TITLE
ZMQ_SERVER and ZMQ_CLIENT and draft situation

### ISSUE THREAD

**Issue by korbes** [zeromq/libzmq#3050]
# Issue description

I'm trying to use ZMQ_SERVER/ZMQ_CLIENT sockets, but they are only available if libzmq is compiled with draft API. However, they are not documented as draft API (like the RADIO/DISH are in http://api.zeromq.org/4-2:zmq-socket) and neither are the routing_id functions (http://api.zeromq.org/4-2:zmq-msg-set-routing-id and http://api.zeromq.org/4-2:zmq-msg-routing-id)

# What's the expected result?

Either have the documentation stating client/server is in draft, or have them enabled without the draft flag.

Thanks for the awesome library!

**Comment by bluca** [comment]
Yes they are draft - I'll fix the doc
