### ISSUE TITLE
Occasional exceptions to closing the program

### ISSUE THREAD

**Issue by JehuShaw** [zeromq/libzmq#3051]
*Please use this template for reporting suspected bugs or requests for help.*

# Issue description
Occasional exceptions to closing the program.

Exception Time: 24:23:56 (2018-4-20)
Error code: 0
mem:85096 vmem:36660 read:8799 write:89038 cpu:1
Process ID=9512, Thread ID=8276
Exception code: 40000015 {致命的应用程序退出}
%hs
Fault address:  75A3C54F 01:0000B54F
File: C:\Windows\syswow64\KERNELBASE.dll
EAX:076DF5BC	EBX:00BB5230
ECX:00000001	EDX:00000000
ESI:076DF624	EDI:076DF630
CS:EIP:0023:75A3C54F
SS:ESP:002B:076DF5BC  EBP:076DF60C
DS:002B  ES:002B  FS:0053  GS:002B
Flags:00000202
BeginFile:,BeginLine:0 
EndFile:,EndLine:0 
Line:0 
Call stack:
Address   Frame     Function
75A3C54F  076DF60C  
0F435CB7  076DF634    e:\rpcz_new\rpcz\dependence\zeromq-4.1.5\src\err.cpp line 80
0F4754B8  076DF660    e:\rpcz_new\rpcz\dependence\zeromq-4.1.5\src\signaler.cpp line 298
0F43ACFD  076DF680    e:\rpcz_new\rpcz\dependence\zeromq-4.1.5\src\mailbox.cpp line 90
0F464259  076DF6BC    e:\rpcz_new\rpcz\dependence\zeromq-4.1.5\src\reaper.cpp line 84
0F46EC59  076DF76C    e:\rpcz_new\rpcz\dependence\zeromq-4.1.5\src\select.cpp line 212
0F46EF8B  076DF774    e:\rpcz_new\rpcz\dependence\zeromq-4.1.5\src\select.cpp line 227
0F49D092  076DF788    e:\rpcz_new\rpcz\dependence\zeromq-4.1.5\src\thread.cpp line 45
506AA273  076DF7C4  
506AA204  076DF7D0  
75A9343D  076DF7DC  
775B9832  076DF81C  
775B9805  076DF834  

# Environment
windows 7 64-bit

* libzmq version (commit hash if unreleased): 
zeromq-4.1.5

* OS: 
windows 7 64-bit

# Minimal test code / Steps to reproduce the issue

1.  
Occasional exceptions to closing the program.

# What's the actual result? (include assertion message & call stack if applicable)
 "Connection reset by peer" :

# What's the expected result?

  (no_ == WSAECONNRESET) ?
            "Connection reset by peer" :

**Comment by sigiesec** [comment]
Please include at least the exact assertion message, including the libzmq source file name and line number.

Can you also try the latest libzmq version 4.2.5 and see if the problem persists? There have been several fixes to the Windows specific code since 4.1.5
