### ISSUE TITLE
What is the official way to build zeromq on Windows?

### ISSUE THREAD

**Issue by kybu** [zeromq/libzmq#3052]
*Please use this template for reporting suspected bugs or requests for help.*

# Issue description

I am trying to compile 4.2.5 on Windows 10. I already tried VS2017 and VS2010 using solution files in
the `build/` directory. I also tried VS2010 using cmake. I can get the zeromq dll compiled in the release mode, but it crashes either during tests run by ctest or when using in my project.

Is there an official way how to compile libzmq on Windows?

# Environment

* libzmq version (commit hash if unreleased): 4.2.5
* OS: Windows 10
* Toolchain: VS2017, VS2010, cmake VS2010

# What's the actual result? (include assertion message & call stack if applicable)

ctest tests crash.

# What's the expected result?

ctest tests pass.

**Comment by kybu** [comment]
It seems like this is an issue of the FD_SETSIZE value being quite big and the stack size limit on Windows. I think that the cmake build needs to be modified to set the stack size for test binaries in order for them to pass. That also suggests, that tests are not being run on Windows when doing a zeromq release.

**Comment by bluca** [comment]
https://github.com/zeromq/libzmq/blob/master/INSTALL#L49

**Comment by kybu** [comment]
Thanks. However, that does not change the fact, that ctest fails to run tests. That has to be taken care of in cmake scripts.

**Comment by bluca** [comment]
I'm not familiar with the Windows build, can you send a PR to fix it?

**Comment by kybu** [comment]
Sure, I can.

Do you know, whether there is any CI process before making an oficial zeromq release? Is there any Windows build being tested?

**Comment by bluca** [comment]
we have appveyor builds:

https://ci.appveyor.com/project/zeromq/libzmq
https://github.com/zeromq/libzmq/blob/master/appveyor.yml
