### ISSUE TITLE
CMake build broken from dist tarball

### ISSUE THREAD

**Issue by dennisklein** [zeromq/libzmq#3056]
# Issue description

When invoking the cmake build from the dist tarballs attached to each release, it will abort, because files are missing in the dist tarball, but are present in the git repo.

# Environment

* libzmq version (commit hash if unreleased): 4.2.5
* OS: MacOS and Linux

# Minimal test code / Steps to reproduce the issue

```
wget https://github.com/zeromq/libzmq/releases/download/v4.2.5/zeromq-4.2.5.zip
tar -xvzf zeromq-4.2.5.tar.gz
cd zeromq-4.2.5
mkdir build
cd build
cmake ..
```

# What's the actual result? (include assertion message & call stack if applicable)

```
(...)
CMake Error: File /home/dklein/tmp/zeromq-4.2.5/builds/cmake/clang-format-check.sh.in does not exist.
CMake Error at builds/cmake/Modules/ClangFormat.cmake:27 (configure_file):
  configure_file Problem configuring file
Call Stack (most recent call first):
  CMakeLists.txt:1295 (include)


-- Configuring incomplete, errors occurred!
```

# What's the expected result?

It is expected, that the dist tarball contains all files that are tracked in git.

If one uses the source tarball generated by github, the problem does not occur:

```
wget https://github.com/zeromq/libzmq/archive/v4.2.5.tar.gz
tar -xvzf v4.2.5.tar.gz
cd zeromq-4.2.5
mkdir build
cd build
cmake ..
```

Why the confusion with additional dist tarballs that are not reflecting the real source tree?

**Comment by bluca** [comment]
This has been already fixed in master

**Comment by tomlankhorst** [comment]
As a quick fix, I downloaded [clang-format-check.sh.in](https://github.com/zeromq/libzmq/raw/v4.2.5/builds/cmake/clang-format-check.sh.in
) to `builds/cmake`
