### ISSUE TITLE
Loose validation in address parsing code

### ISSUE THREAD

**Issue by simias** [zeromq/libzmq#3069]
# Issue description

The current TCP address parsing code (as currently implemented in `tcp_address.cpp`) is not very strict and will silently accept bogus address formats, sometimes with weird results that might be tricky to debug. In particular it allows ambiguous `IPv6:port` specifications and it does not validate that the port is actually valid.

# Environment

* libzmq version (commit hash if unreleased): v4.2.5
* OS: any

# Minimal test code / Steps to reproduce the issue

Consider this pyzmq code:

```python
import zmq

context = zmq.Context()

socket = context.socket(zmq.REQ)
socket.setsockopt(zmq.IPV6, 1)
socket.connect("tcp://[fd95:74a4:b46c:1000::1:100b]:5555")
```

This code works fine, the brackets are used to disambiguate between the IPv6 and the port specifier. However while ZMQ allows the brackets it merely ignores them and you can remove them without changing the meaning at all:

```python
socket.connect("tcp://fd95:74a4:b46c:1000::1:100b:5555")
```

It makes it pretty difficult to figure out what's going on for IPv6 address:port specifier, and it also means that if the user forgets to specify the port ZMQ will just assume that the final component of the IPv6 is actually the port specifier:

```python
socket.connect("tcp://fd95:74a4:b46c:1000::1:100b")
```

Here ZMQ will assume that `100b` is the port number, which you might argue is invalid but since the parser uses a simple `atoi` without further validation it'll actually attempt to connect to address `fd95:74a4:b46c:1000::1` on port `100` which doesn't exactly conform to the "principle of least astonishment".

# What's the expected result?

I think ZMQ should:

* Enforce that brackets be present around the hostname when a port specifier is expected *if* the hostname contains the ':' character

* Reject port numbers that contain trailing garbage

It's a very straightforward modification but it might cause regressions for people who rely on the current behavior to parse "weird" URLs.

**Comment by bluca** [comment]
> It's a very straightforward modification but it might cause regressions for people who rely on the current behavior to parse "weird" URLs.

You figured out the problem yourself - so the first change you propose cannot be done, as avoiding regressions in existing, working applications is more important than guarding against silly mistakes.

Feel free to send a PR to fix the second one.
