### ISSUE TITLE
Assertion failed: false (../zeromq-4.2.3/src/pipe.cpp:431)

### ISSUE THREAD

**Issue by talkhasib** [zeromq/libzmq#3072]
I connected a DEALER socket of a client to a PUB port on the server by mistake.
When I tried to terminate the connection, The process crashed

Assertion failed: false (../zeromq-4.2.3/src/pipe.cpp:431)
#0  0xb59ff610 in /usr/lib/libzmq.so.5 (?+0x0)
#1  0xb5a0f4b4 in /usr/lib/libzmq.so.5 (?+0x0)
#2  0xb5a20410 in /usr/lib/libzmq.so.5 (?+0x0)

How would you handle such a situation without causing your process to crash. Assuming you dont know about the socket type on the other end.

**Comment by bluca** [comment]
You don't - it's a programming error

**Comment by talkhasib** [comment]
In my case, the URL of the server is passed to the process on a different socket.
So, its more of a config error than a programming error.

How would you gracefully exit such a state or not enter it in the first place?

**Comment by bluca** [comment]
Again, you don't - fix the config and the logic handling it so that wrong data is not used

**Comment by sigiesec** [comment]
Hm, that doesn't sound to be a viable solution to me, since the cause is not constrained to the local process. 

Instead of a misconfiguration, imagine a peer that does not implement the ZMTP protocol correctly. This shouldn't crash the other peer in any case.
