### ISSUE TITLE
Problem: Why call msg->init() after msg->close()

### ISSUE THREAD

**Issue by laplaceyang** [zeromq/libzmq#3073]
*Please use this template for reporting suspected bugs or requests for help.*

# Issue description

In [xsub.cpp#117](https://github.com/zeromq/libzmq/blob/master/src/xsub.cpp#L117), after send msg to endpoint of pub. Why should we call msg->init() after msg->close() called at line 115
```
    int rc = msg_->close ();
    errno_assert (rc == 0);
    rc = msg_->init ();
    errno_assert (rc == 0);
```

In the same file of [xsub.cpp#247](https://github.com/zeromq/libzmq/blob/master/src/xsub.cpp#L247), we just call msg->close() and end the function. No msg->init() called there

Can anyone explain it?

**Comment by bluca** [comment]
init() will reset the data structures - in the first case, the message is owned by the application, so in principle they could access it - in the second one by the library so there's no need to do that as it will go out of scope
