### ISSUE TITLE
Problem: zmq_poll returns EBADFD with NULL FDs/ZMQ sockets (zmq_poller backend)

### ISSUE THREAD

**Issue by msune** [zeromq/libzmq#3076]
# Issue description

In previous releases `zmq_poll` was ignoring `zmq_pollitem_t` entries  `fd == -1` and `sock== NULL`. This was consistent with the `poll`/`epoll` behaviour:

```
       If this (fd)
       field is negative, then the corresponding events field is ignored and
       the revents field returns zero.  (This provides an easy way of ignor‐
       ing a file descriptor for a single poll() call: simply negate the fd
       field.  Note, however, that this technique can't be used to ignore
       file descriptor 0.)
```

and is something desirable for `zmq_poller` (and `zmq_poller`) IMHO.

With the introduction of `zmq_poller()` as the default backend implementation of `zmq_poll() (`HAVE_ZMQ_POLLER` not configurable(?))`, this is broken, and `zmq_poll()` returns `EBADFD`.

# Environment

* libzmq version (commit hash if unreleased): v4.2.5
* OS: Debian

# Minimal test code / Steps to reproduce the issue

Pass a single `zmq_pollitem_t` with `fd == -1`, `socket == NULL`

# What's the actual result? (include assertion message & call stack if applicable)

Difference in behaviour between previous releases, and `EBADFD`

# What's the expected result?

Ignore these `zmq_pollitem_t` entries

**Comment by bluca** [comment]
IMHO zmq_poll's implementation should stay separate from zpoller. There are also performance concerns I think.

**Comment by msune** [comment]
I am almost sure it wasn't, but let me compile a fresh copy from master HEAD

**Comment by msune** [comment]
Humm... I am confused.

A simple `./configure` seems to enable drafts by default (?), although there is no `--disable-drafts` rather only `--enable-drafts`:

```
configure: Building stable and legacy API + draft API
```

Anyhow, with this configure, the default backend is `zmq_poller()`:

```
diff --git a/src/zmq.cpp b/src/zmq.cpp
index 832eb77..0db143b 100644
--- a/src/zmq.cpp
+++ b/src/zmq.cpp
@@ -792,6 +792,7 @@ int zmq_poll (zmq_pollitem_t *items_, int nitems_, long timeout_)
 //  TODO: the function implementation can just call zmq_pollfd_poll with
 //  pollfd as NULL, however pollfd is not yet stable.
 #if defined ZMQ_HAVE_POLLER
+    #error Using zmq_poller by default
     // if poller is present, use that.
     return zmq_poller_poll (items_, nitems_, timeout_);
 #else
```

```
  CXX      src/src_libzmq_la-zmq_utils.lo
../src/zmq.cpp:795:6: error: #error Using zmq_poller by default
     #error Using zmq_poller by default
      ^

``

**Comment by msune** [comment]
Using `--disable-drafts` works (as expected) and doesn't use `zmq_poller()`. So:

1. `zmq_poller()` behaves differently than `zmq_poll()` for NULL/-1 items
1. Cosmetics in `configure.ac` help string 

I am not sure it's a good idea to have drafts enabled by default in `configure`.

**Comment by bluca** [comment]
It's only enabled by default in git repositories - the request to change it that way came from developers, you can find it in the old PRs/issues.
It's not enabled by default with release tarballs.

**Comment by msune** [comment]
@bluca understood. Renamed issue to better reflect the problem.

**Comment by bluca** [comment]
@somdoron I would like to move back zmq_poll to use its own implementation - I am of course happy to maintain it.
Besides this issue, which might be solvable in other ways, and other potential behaviour changes, I have concerns w.r.t. performances, given the zmq_poller_poll implementation always mallocs once per call, while zmq_poll doesn't (unless it polls on more than 16 sockets - quite uncommon).
What do  you think?

**Comment by sigiesec** [comment]
@bluca Do you also intend to undeprecate zmq_poll? I thought it is intended to be superseded by zmq_poller_*

**Comment by bluca** [comment]
Not necessarily - but until it's there, I think it should have its own implementation

**Comment by sigiesec** [comment]
Ok, this actually simplifies things, since currently there are implementations of zmq_poll with and without zqm_poller, so there is no additional maintenance effort at all

**Comment by somdoron** [comment]
I have no problem with going back with zmq_poll. I think it was like this originally.
