### ISSUE TITLE
Build output is hardly readable when doing a parallel make

### ISSUE THREAD

**Issue by sigiesec** [zeromq/libzmq#3098]
This should be solvable using --output-sync when I understand https://www.gnu.org/software/make/manual/html_node/Parallel-Output.html correctly.

**Comment by sigiesec** [comment]
This requires GNU make >= 4, but Ubuntu 14.04 still has the ancient make 3.81. Ubuntu 16.04 will have make 4.1, however. Yay.

**Comment by bluca** [comment]
should be easy to check the version and conditionally use the option in the travis script, if you want to give it a try

**Comment by sigiesec** [comment]
Yes that should be easy, but there seem to be no packages for make 4.1 for Ubuntu 14.04, so it would need to be built from scratch.

**Comment by sigiesec** [comment]
Hope that travis-ci/travis-ci#5821 will be resolved soon...
