### ISSUE TITLE
Coveralls no longer reporting coverage in PRs

### ISSUE THREAD

**Issue by sigiesec** [zeromq/libzmq#3099]
Some administrator should check if these settings are up-to-date: http://docs.coveralls.io/coveralls-notifications

**Comment by bluca** [comment]
the notifications were disabled - I've turned them back on, let's see

**Comment by sigiesec** [comment]
Thanks :)

**Comment by sigiesec** [comment]
Appears to work :) https://github.com/zeromq/libzmq/pull/3096 just got a comment and status check :)

**Comment by bluca** [comment]
Great! Do we want both status and comments?
The comments are quite spammy so IMHO we could do just with status

**Comment by sigiesec** [comment]
I don't have a strong opinion on that. I think you disabled comments in the meantime, right? Fine with me :)

**Comment by bluca** [comment]
Yeah, if someone asks for it we can enable it later, in the meanwhile we can keep the notifications level down
