### ISSUE TITLE
zmq.hpp - message_t::equal method

### ISSUE THREAD

**Issue by kreuzerkrieg** [zeromq/libzmq#3113]
The `equal` method looks like this
```
inline bool equal(const message_t* other) const ZMQ_NOTHROW
        {
            if (size() != other->size())
                return false;
            std::string a(data<char>(), size());
            std::string b(other->data<char>(), other->size());
            return a == b;
        }
```
is it really necessary to create strings (which implies copying the buffer) to compare two pieces of memory?

**Comment by kreuzerkrieg** [comment]
Right... My bad. Could admin move messages between repos?

**Comment by sigiesec** [comment]
I don't think moving issues is possible on GitHub. Please reopen in the cppzmq repository

**Comment by kreuzerkrieg** [comment]
Done
