### ISSUE TITLE
Send Msgpack message using zmq

### ISSUE THREAD

**Issue by SysOverdrive** [zeromq/libzmq#3118]
# Issue description

I can not figure how to send a notification message encoded in msgpack with libzmq in C.

I am basically trying to make this functionality that exists in Python in C, namely

```
def send_recv_notification(n):
    # REQ REP requirese lock step communication with multipart msg (topic,msgpack_encoded dict)
    req.send_multipart(('notify.%s'%n['subject'], msgpack.dumps(n)))
    return req.recv()

#set start eye windows
n = {'subject':'eye_process.should_start.0','eye_id':0, 'args':{}}

```
# Environment
Windows. Unreal Engine with c++
* OS: 
Windows 10 

# Steps to reproduce the issue

1.  I have basically created a struct and then packed it.

EyeStruct EyeStruct = { "notify.eye_process.should_start.0",1 };
msgpack::pack(EyeStruct);

How can I now get it into a zmq:message_t such that I can send it further with a ZMQ_PUB socket ?

**Comment by bluca** [comment]
For cppzmq issues use its repository: https://github.com/zeromq/cppzmq

**Comment by SysOverdrive** [comment]
I want to implement this in C. Even if the Unreal Engine platform uses c++. Since I have found it hard to integrate the c++ wrappers over that.

How my current code works (just sending a string) https://github.com/SysOverdrive/UPupilLabsVR/blob/master/Source/UPupilLabsVR/Private/FPupilLabsUtils.cpp#L43
