### ISSUE TITLE
[libzmq 4.2.5] Android ndk17 arm64-v8a compile error v1_decoder.cpp:113:28

### ISSUE THREAD

**Issue by kasru** [zeromq/libzmq#3131]
libzmq 4.2.5
Android
ndk17
arm64-v8a

compile error:
  CXX      src/src_libzmq_la-v2_encoder.lo
../src/v1_decoder.cpp:113:28: error: comparison 'unsigned long' > 18446744073709551615 is always false [-Werror,-Wtautological-constant-compare]
    if (payload_length - 1 > std::numeric_limits<size_t>::max ()) {
        ~~~~~~~~~~~~~~~~~~ ^ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
1 error generated.

**Comment by bluca** [comment]
That's a very annoying warning that clang enables by default... it might be tautological on 64 bit architectures, but it certainly isn't in 32 bit x86, were size_t is 4 bytes.

**Comment by sigiesec** [comment]
This could be guarded by some preprocessor clause, but I think it would make more sense to disable the warning in our build files. At least in this and comparable cases it doesn't make much sense in cross platform code.

**Comment by bluca** [comment]
Yeah that makes sense, I've added a check in cmake/autoconf

**Comment by bluca** [comment]
@kasru please try again from the latest master

**Comment by kasru** [comment]
@bluca Please attach patch file for libzmq 4.2.5 with fix this issue.

**Comment by bluca** [comment]
https://github.com/zeromq/libzmq/commit/58d13395ece1fa0dd9b0583d736af4ac342c1267
