### ISSUE TITLE
Define policy on using strcpy/strcat

### ISSUE THREAD

**Issue by sigiesec** [zeromq/libzmq#3147]
[CWE-119](https://cwe.mitre.org/data/definitions/119.html) warns against the use of functions that handle strings without specifying maximum lengths explicitly such as strcpy or strcat. clang-tidy currently finds 13 or so of such uses with its clang-analyzer-security.insecureAPI.strcpy diagnostic. See e.g. https://travis-ci.org/sigiesec/libzmq/jobs/385901602#L1338

I did not analyze all such uses but I at least some check the length of the strings before calling strcpy/strcat in a custom way. 

How should we handle this?
1. Disable the diagnostic completely. (I don't think this is a good idea. Even if the code is correct at the moment, this might easily break when the code is modified.)
2. Leave the diagnostic enabled, and do not care about it. (This is even worse than the first option, as it may detract from other warnings)
3. Leave the diagnostic enabled in general, and disable specific instances of the warning after checking them thoroughly. (However, this will leave it disabled even if the code is modified)
4. Provide and use functions that encapsulate this check, maybe reusing existing library functions where available. (I would prefer this option.)

**Comment by bluca** [comment]
strcpy/cat are just fine in some cases (eg: just allocated a buffer and copying a literal), in other cases some projects are starting to use strlcpy, but that adds a dependency on libbsd on Linux

**Comment by sigiesec** [comment]
I think that there is no common substitute that is available on all platforms. MSVC doesn't have strlcpy, but strncpy_s
