### ISSUE TITLE
crash in send_command following zmq_disconnect 

### ISSUE THREAD

**Issue by WallStProg** [zeromq/libzmq#3152]
I'm seeing a (very) intermittent crash in ZeroMQ that I can't otherwise explain, and am wondering if it's a bug.

The root cause of the crash is that `send_command` calls `get_tid` with a NULL pointer (Screenshot-1.png).

At the time of the crash, the application is shutting down and closing the inproc control socket it uses to break out of a `zmq_poll` call that is retrieving events from `zmq_socket_monitor` on a dedicated thread (Screenshot-2.png).  (Note: the control socket is simply added to the list of sockets for `zmq_poll`, to force zmq_poll to return when it's time to shut down the monitor thread).

The only other thread doing anything at the time is, I think, the "reaper" thread, which is shown in (Screenshot-3.png).

(I've also attached a "thread apply bt full" stack trace with all the above in text form).

- The control socket is a ZMQ_SERVER and the socket used to send it the "shutdown" command is a ZMQ_CLIENT, so I don't think there should be any obvious issues related to threading that would cause the crash.

The `zmqBridgeMamaTransportImpl_disconnectSocket` that is being called looks more or less like this:

```
   int rc = zmq_disconnect(socket->mSocket, uri);
   if (0 != rc) {
      ...
   else {
      status = zmqBridgeMamaTransportImpl_kickSocket(socket->mSocket);
   }
```

The `zmqBridgeMamaTransportImpl_kickSocket` is simply this: 

```
   zmq_pollitem_t pollitems [] = { { socket, 0, ZMQ_POLLIN, 0 } };
   CALL_ZMQ_FUNC(zmq_poll(pollitems, 1, 1));
```

Now, you may ask yourself: "Why is he calling `zmq_poll` after `zmq_disconnect`?", and frankly I don't have a good answer (although I would love to have one).

There have been several email threads and GitHub issues which suggest that calling `zmq_poll` afer certain socket operations is a good idea, including this one: <https://github.com/zeromq/libzmq/issues/2267>.  

I've adopted the convention of giving a socket a "kick" (hence the name) after calling connect, bind, etc.  Up till now that has at least appeared to cause no harm, and in fact it may have nothing to do with the crash.  Then again, it might...

So, my questions:

- Is this crash a bug, or have I stumbled (once again) into behavior that is not OK?
- Is there an "official" recommendation of when to call `zmq_poll` as above?  Are there specific scenarios where it is **NOT** OK to call `zmq_poll`? (Other than the obvious -- e.g., after closing the socket).
- Is there a better way to shut down the control socket?  Perhaps just calling `zmq_close` ?  

FWIW, the sequence I'm using to shutdown the control publisher looks like this:

```
zmq_disconnect(pubSocket, ...
zmq_poll(pubSocket, ...
zmq_setsockopt(pubSocket, ZMQ_LINGER, 0, ...
zmq_socket_monitor(pubSocket, NULL, ZMQ_EVENT_ALL)
zmq_close(pubSocket, ...
```

For the sub socket it's similar:

```
zmq_unbind(subSocket, ...
zmq_poll(subSocket, ...
zmq_setsockopt(subSocket, ZMQ_LINGER, 0, ...
zmq_socket_monitor(subSocket, NULL, ZMQ_EVENT_ALL)
zmq_close(subSocket, ...
```

For context, the crash occurred in a "stress test" that does the following:
- start a publisher process that publishes a message on a well-known topic once per milli;
- start several listener processes that subscribe to that topic
- start another listener process that subscribes to the topic, receives ten messages, then quits.  This process is run "forever" in a loop until it returns a non-zero return code.

As can be seen from the tillcore.txt file, the crash occurred on iteration 4116 of the test.  Test system is CentOS 6 w/16GB running on 4xi5-2400.  Software built in "debug" mode w/gcc 4.8.2.  Version of libzmq is essentially d17581929cceceda02b4eb8abb054f996865c7a6.

Any suggestions would be much appreciated -- thanks in advance!

**Comment by WallStProg** [comment]
Attached files:
[gdb.txt](https://github.com/zeromq/libzmq/files/2065100/gdb.txt)
![screenshot-3](https://user-images.githubusercontent.com/6627231/40877941-0d2274f0-6657-11e8-8698-001a3d4c5f08.png)
![screenshot-2](https://user-images.githubusercontent.com/6627231/40877942-0d2ef090-6657-11e8-8cc2-7be8edd5f7cb.png)
![screenshot-1](https://user-images.githubusercontent.com/6627231/40877943-0d3a927e-6657-11e8-9bf2-3b36f0a0f17d.png)
[tillcore.txt](https://github.com/zeromq/libzmq/files/2065102/tillcore.txt)

**Comment by sigiesec** [comment]
Could you provide an executable minimal example that reproduces the problem?

**Comment by WallStProg** [comment]
Not at this point.  I'm still trying to narrow down the conditions that trigger the crash -- as mentioned it is very intermittent.

And of course libzmq is at the bottom of a pile of libraries, any of which could be the culprit.  Which makes a repro even more difficult.

Having said that, it has happened at least twice, and in both cases get_tid was called with a NULL this pointer from send_command:

```
void zmq::object_t::send_command (command_t &cmd_)
{
    ctx->send_command (cmd_.destination->get_tid (), cmd_);
}
```

In both cases, `cmd_.destination` is NULL.

FWIW, I've since removed the calls to disconnect/unbind mentioned above, and have not seen the crash since then.  Of course, that may just mean that the crash has gone from very intermittent to almost never.  It's the almost part that worries me ...

**Comment by bill-torpey-ullink** [comment]
Note that the problem occurs only on tcp sockets -- it does not occur with inproc sockets.  Presumably this is because disconnect is synchronous w/inproc (although @sigiesec says no: https://github.com/zeromq/libzmq/issues/2759#issuecomment-389185969).

If inproc is not in fact synchronous then presumably this is still a latent bug w/inproc, but happens very infrequently because disconnect is faster (i.e., we get "lucky" ;-)
