### ISSUE TITLE
Assertion failed: nbytes == 0 (src/pgm_sender.cpp:220)

### ISSUE THREAD

**Issue by ZeleniJure** [zeromq/libzmq#3154]
# Issue description
Using 2 context threads and epgm pub-sub sockets, code terminates with "Assertion failed". I have only seen it happen on start-up, when the system is under more load.
Problem is in a race condition:
Function out_event is called several times from different io threads, using common write_size variable.

```
1st thread                                  2nd thread

write_size = 507
nbytes = pgm_write(write_size) == 507
                                             nbytes = pgm_write(write_size) == 507
if (write_size == nbytes) {
   write_size = 0
}
                                             if (write_size == nbytes)
                                             else
                                             {
                                               assert(nbytes == 0)
                                             }
```

                                            
Calls to out_event are coming from two different locations:
1. /usr/src/debug/zeromq-4.1.4/src/epoll.cpp:173
2. /usr/src/debug/zeromq-4.1.4/src/session_base.cpp:267

# Environment

* libzmq version:  4.1.4 distributed with CentOS up to  4.2.5
* OS: linux

# Minimal test code / Steps to reproduce the issue

Tried writing smallest example, but it seems hard to reproduce. io_treads seem to get assigned
based on number of pollers. The bug occurs in a large application, that creates cca. 20 pub-subs,
with multiple pollers on each.

Workaround:
- only 1 IO thread (e.g. new Context(1))
- setting affinity does not help

**Comment by bluca** [comment]
I'm not quite sure how a socket can end up being used from different I/O threads - can you post the full decoded backtraces?
