### ISSUE TITLE
signaler.send aborts intermittently

### ISSUE THREAD

**Issue by neel-parikh** [zeromq/libzmq#3169]
# Issue description
We are seeing intermittently process crashing with EBADF error code on signaler.send() call. The core file backtrace shows that the value of file descriptor "w" is -1 which means it's already closed and the thread is trying to write on the already closed FD.

There is no context sharing between the threads, everything happens in the same thread.
Only thing I observed is reaper thread is aborted due to invalid "w" value as the io thread closed the file descriptor.

# Environment
Using libzmq v4.2.0
Linux OS

# Minimal test code / Steps to reproduce the issue
This issue is intermittent and hard to reproduce all the time.

# What's the actual result? (include assertion message & call stack if applicable)
Below is the stack trace:

```
Thread 2: IO Thread
(gdb) t 2
[Switching to thread 2 (LWP 29017)]
#0  0x43a11598 in write () from ./105197/1418/lib/libpthread.so.0
(gdb) bt
Python Exception <type 'exceptions.ImportError'> No module named gdb.frames: 
#0  0x43a11598 in write () from ./105197/1418/lib/libpthread.so.0
#1  0x43eb7094 in zmq::signaler_t::send (this=this@entry=0x2cfbc) at /usr/src/debug/libzmq/4.2.0-r0.0/git/src/signaler.cpp:180
#2  0x43e9e808 in zmq::mailbox_t::send (this=0x2cf88, cmd_=...) at /usr/src/debug/libzmq/4.2.0-r0.0/git/src/mailbox.cpp:66
#3  0x43ea6854 in send_command (cmd_=..., this=<optimized out>) at /usr/src/debug/libzmq/4.2.0-r0.0/git/src/object.cpp:436
#4  zmq::object_t::send_term_ack (this=this@entry=0x33910, destination_=<optimized out>) at /usr/src/debug/libzmq/4.2.0-r0.0/git/src/object.cpp:318
#5  0x43ea8be4 in zmq::own_t::check_term_acks (this=0x33910) at /usr/src/debug/libzmq/4.2.0-r0.0/git/src/own.cpp:205
#6  0x43eb6cd8 in zmq::session_base_t::pipe_terminated (this=0x33910, pipe_=<optimized out>) at /usr/src/debug/libzmq/4.2.0-r0.0/git/src/session_base.cpp:268
#7  0x43eaa280 in zmq::pipe_t::process_pipe_term_ack (this=0x33da8) at /usr/src/debug/libzmq/4.2.0-r0.0/git/src/pipe.cpp:347
#8  0x43e9b494 in zmq::io_thread_t::in_event (this=0x2c938) at /usr/src/debug/libzmq/4.2.0-r0.0/git/src/io_thread.cpp:85
#9  0x43e99f68 in zmq::epoll_t::loop (this=0x2ce58) at /usr/src/debug/libzmq/4.2.0-r0.0/git/src/epoll.cpp:179
#10 0x43ecaedc in thread_routine (arg_=0x2cea4) at /usr/src/debug/libzmq/4.2.0-r0.0/git/src/thread.cpp:100
#11 0x43a06068 in ?? () from ./105197/1418/lib/libpthread.so.0
Backtrace stopped: previous frame identical to this frame (corrupt stack?)
(gdb) frame 1
#1  0x43eb7094 in zmq::signaler_t::send (this=this@entry=0x2cfbc) at /usr/src/debug/libzmq/4.2.0-r0.0/git/src/signaler.cpp:180
180	in /usr/src/debug/libzmq/4.2.0-r0.0/git/src/signaler.cpp
_(gdb) p w
$5 = 21_
(gdb) 

Thread 1: Reaper Thread
(gdb) t 1
[Switching to thread 1 (LWP 29016)]
#0  0x438bc6d4 in raise () from ./105197/1418/lib/libc.so.6
(gdb) bt
Python Exception <type 'exceptions.ImportError'> No module named gdb.frames: 
#0  0x438bc6d4 in raise () from ./105197/1418/lib/libc.so.6
#1  0x438bda30 in abort () from ./105197/1418/lib/libc.so.6
#2  0x43e9a2ac in zmq::zmq_abort (errmsg_=errmsg_@entry=0x439aeeb8 "Bad file descriptor") at /usr/src/debug/libzmq/4.2.0-r0.0/git/src/err.cpp:91
#3  0x43eb70f0 in zmq::signaler_t::send (this=this@entry=0x2bdc0) at /usr/src/debug/libzmq/4.2.0-r0.0/git/src/signaler.cpp:181
#4  0x43e9e808 in zmq::mailbox_t::send (this=0x2bd8c, cmd_=...) at /usr/src/debug/libzmq/4.2.0-r0.0/git/src/mailbox.cpp:66
#5  0x43ea6958 in zmq::object_t::send_done (this=this@entry=0x2c308) at /usr/src/debug/libzmq/4.2.0-r0.0/git/src/object.cpp:351
#6  0x43eb1100 in zmq::reaper_t::process_reaped (this=0x2c308) at /usr/src/debug/libzmq/4.2.0-r0.0/git/src/reaper.cpp:138
#7  0x43eb1400 in zmq::reaper_t::in_event (this=0x2c308) at /usr/src/debug/libzmq/4.2.0-r0.0/git/src/reaper.cpp:97
#8  0x43e99f68 in zmq::epoll_t::loop (this=0x2c830) at /usr/src/debug/libzmq/4.2.0-r0.0/git/src/epoll.cpp:179
#9  0x43ecaedc in thread_routine (arg_=0x2c87c) at /usr/src/debug/libzmq/4.2.0-r0.0/git/src/thread.cpp:100
#10 0x43a06068 in ?? () from ./105197/1418/lib/libpthread.so.0
Backtrace stopped: previous frame identical to this frame (corrupt stack?)
(gdb) frame 3
#3  0x43eb70f0 in zmq::signaler_t::send (this=this@entry=0x2bdc0) at /usr/src/debug/libzmq/4.2.0-r0.0/git/src/signaler.cpp:181
181	in /usr/src/debug/libzmq/4.2.0-r0.0/git/src/signaler.cpp
_(gdb) p w
$7 = -1_
(gdb) 
```

Can you please take a look and provide any suggestion on how to avoid this scenario?
I'm thinking if we could add some error check instead of aborting?

Appreciate your help.

Thanks.

**Comment by sigiesec** [comment]
Could you update to libzmq 4.2.5? I think there is reason to believe this has already been fixed.

**Comment by neel-parikh** [comment]
@sigiesec Thank you for your response.
Yes, we are in line to update the libzmq version, however we would be doing in next few months. Is there a patch I can apply to fix in v4.2.0 ?

**Comment by sigiesec** [comment]
4.2.5 is a bugfix release for 4.2.x, so the patch is the diff between 4.2.5 and 4.2.0 ;) I don't know which changes are exactly related to this issue.

But if you could apply a patch and build a new libzmq, why can't you simply build 4.2.5?

**Comment by bluca** [comment]
4.2.0 and the latest release are binary compatible, so you should be able to seamlessly upgrade and test it.

If you use packages, you can grab the latest release for your version of Ubuntu from:

https://software.opensuse.org/download.html?project=network%3Amessaging%3Azeromq%3Arelease-stable&package=libzmq5

**Comment by neel-parikh** [comment]
Ok thanks for your suggestions @sigiesec  and @bluca 
I'll try to test with the new libzmq version and see if this issue is fixed.

**Comment by neel-parikh** [comment]
@bluca  @sigiesec 
One clarification.
What do you recommend for czmq version if I upgrade ZMQ to v4.2.5?
Currently, we are using below:

ZMQ: v4.2.0
CZMQ: v3.0.2

**Comment by bluca** [comment]
As the version bump suggests, later versions of czmq are NOT binary compatible, as many deprecated classes have been removed in 4.x, so you'd not only need to rebuild your program but also to ensure that you have migrated away from retired apis

**Comment by neel-parikh** [comment]
Ok thank you @bluca 
If there is no version dependency for CZMQ with ZMQ v4.2.5 I would then stick with the current czmq version 3.0.2 as I would need binary compatibility

**Comment by bluca** [comment]
There is no dependency (but you need to move from 3.x at some point, it's not maintained anymore)

**Comment by neel-parikh** [comment]
Got you, yes we will eventually move to 4.x but may be after a while as it would need a lot of code changes in due to all the deprecated APIs.
Thanks a lot.

**Comment by DeLucaDan** [comment]
I looked through the change log and I did not see the fix.
