### ISSUE TITLE
ZMQ_REQ——ZMQ_REP order

### ISSUE THREAD

**Issue by ZhangPengchao** [zeromq/libzmq#3172]
*Please use this template for reporting suspected bugs or requests for help.*

# Issue description
server code:
int main () {
    zmq::context_t context (1);
    zmq::socket_t socket (context, ZMQ_REP);
    socket.bind ("tcp://*:5555");

    while (true) {
        zmq::message_t request;

        string str = s_recv(socket);
        std::cout << "Received:" << str << std::endl;

        usleep(10000*1000);

        zmq::message_t reply (5);
        memcpy (reply.data (), "World", 5);
        socket.send (reply);
    }
    return 0;
}
client code:
int main ()
{
    zmq::context_t context (1);

    for (int request_nbr = 0; request_nbr != 5; request_nbr++) {
        zmq::socket_t socket (context, ZMQ_REQ);
        std::cout << "Connecting to hello world server…" << std::endl;
        socket.connect ("tcp://localhost:5555");

        zmq::message_t request (5);
        memcpy (request.data (), "Hello", 5);
        std::cout << "Sending Hello " << request_nbr << "…" << std::endl;
        char send_str[10] = {0};
        sprintf(send_str, "%d", request_nbr);
        s_send(socket, send_str);
        // I have a mind to not recv
        usleep(1000*1000);
    }
    return 0;
}

result:
./server 
Received:0
Received:4
Received:1
Received:2
Received:3

./client 
Connecting to hello world server…
Sending Hello 0…
Connecting to hello world server…
Sending Hello 1…
Connecting to hello world server…
Sending Hello 2…
Connecting to hello world server…
Sending Hello 3…
Connecting to hello world server…
Sending Hello 4…

why server recv order not match client send order?

# Environment

* libzmq version (commit hash if unreleased): apt-get install libzmq3-dev
* OS: TX2 ubuntu16

# Minimal test code / Steps to reproduce the issue

1.  start server
2.  start client

# What's the actual result? (include assertion message & call stack if applicable)
./server 
Received:0
Received:4
Received:1
Received:2
Received:3

# What's the expected result?
./server 
Received:0
Received:1
Received:2
Received:3
Received:4

**Comment by bluca** [comment]
There is no guarantee of ordering among different sockets. If you want guaranteed ordering, use the same socket, or add unique monotonic sequence numbers to your messages and do the reorder yourself in your application.

**Comment by ZhangPengchao** [comment]
Thank you, I just don't know if this phenomenon is correct and I don't know how to confirm this problem, because the phenomenon seen through packet capture is sent out in order. I understand now, thank you.
