### ISSUE TITLE
Is there any good idea to control memory if we do not recv msg in inbound side

### ISSUE THREAD

**Issue by laplaceyang** [zeromq/libzmq#3176]
# Issue description
If recv is not called on the inbound socket, the queue and memory will grow with each message received. 
We should call getsockopt(ZMQ_EVENTS) in my app for control memory.
But it's a bad trick to do so, I just want to release memory used instead of getting some socket option
It's there any good idea for dealing with this scenario.

See [issues@3171](https://github.com/zeromq/libzmq/issues/3171) and also [issues@2474](https://github.com/zeromq/libzmq/issues/2474)
# Environment

* libzmq version (commit hash if unreleased): master
* OS: linux

# Minimal test code / Steps to reproduce the issue

See [issues@3171](https://github.com/zeromq/libzmq/issues/3171) and also [issues@2474](https://github.com/zeromq/libzmq/issues/2474)

# What's the actual result? (include assertion message & call stack if applicable)
memory use always increase and finally killed by os due to oom

# What's the expected result?

memory use is stable

**Comment by laplaceyang** [comment]
@sigiesec It's a more general issue.  It's not related to ZMQ_CONFLATE option. All kinds of recv side (double way socket) have the problem of memory growing if we don't call recv.  

---
See https://github.com/zeromq/libzmq/issues/2474 .
In this situation, I use router but never recv, will also lead to the problem.
Because I use ip as identity to specify the sub endpoint for sending msg, so I never recv msg in server.

So.. All kinds of recv side (double way socket) have the problem of memory growing if we don't call recv.

**Comment by jamesdillonharvey** [comment]
So the HWM has no effect if you don't call `zmq_recv` on other (non conflate) socket types?  I assumed it was only related to `ZMQ_CONFLATE` as this option bypasses HWM's

**Comment by laplaceyang** [comment]
@jamesdillonharvey I think it's because pipe will only destroyed after process_command call that lead memory increase(msg is attached with pipe)... And process_command will only called inner recv call, or getsockopt(ZMQ_EVENTS)

zmq_conflate option change pipe struct to pipe_conflate. And pipe_conflate hold just two storge (use dbuffer). So i don't think the option will change memory using.

Never called recv is the only reason  memory always increasing.

**Comment by jamesdillonharvey** [comment]
Have you tested with sockets that don't have conflate set?

**Comment by laplaceyang** [comment]
I'm sorry for conclusion before. Memory can not controled only set conflate = 1, where use sub socket. 
But in another situation, router and dealer, it's the reason of pipe not destoryed.

Test code:
pub-sub:

pub side:
```
#include "zmq.h"
#include <stdio.h>
#include <unistd.h>
#include <malloc.h>

int main(int argc, char* argv[])
{
  const char* endpoint = "tcp://127.0.0.1:49152";
  void *ctx = zmq_ctx_new ();
  //  Create a subscriber
    void *pub = zmq_socket (ctx, ZMQ_PUB);

    zmq_bind (pub, endpoint);

    const char msg[10000] = {0};

    int count = 0;
    while(1){
        usleep(1000);
        if(++count % 100 == 0) {
            printf("send msg count %d\n", count);
        }
      zmq_send(pub, NULL, 0, ZMQ_SNDMORE);
      zmq_send(pub, msg, sizeof(msg), 0);
    }

  return 0;
}
```

sub side:
```
#include "zmq.h"
#include <stdio.h>
#include <unistd.h>
#include <malloc.h>

int main(int argc, char* argv[])
{
    const char* endpoint = "tcp://127.0.0.1:49152";
    void *ctx = zmq_ctx_new ();
  //  Create a subscriber
    void *sub = zmq_socket (ctx, ZMQ_SUB);
     zmq_setsockopt (sub, ZMQ_SUBSCRIBE, "", 0);
     int conflate = 1;
     zmq_setsockopt (sub, ZMQ_CONFLATE, &conflate, sizeof(conflate));
    //int hwm = 10;
    //zmq_setsockopt (sub, ZMQ_RCVHWM, &hwm, sizeof(hwm));
    //zmq_setsockopt (sub, ZMQ_SNDHWM, &hwm, sizeof(hwm));

    zmq_connect (sub, endpoint);

    uint64_t count =0;

    while(1){
        usleep(1000000);
        //int event;
        //size_t event_size = sizeof(event);

        //zmq_getsockopt (sub, ZMQ_EVENTS, &event, &event_size);

        if(count%10 == 0)
        {
          printf("\n\ncount: %u\n", count);
          malloc_trim(0);
          malloc_stats();
        }
        ++count;
    }

  return 0;
}
```

set hwm make sense, but conflate not

---

Second Scenario

Router Dealer:

Router side:
```
#include "zmq.h"
#include <stdio.h>
#include <unistd.h>
#include <malloc.h>

int main(int argc, char* argv[])
{
  const char* endpoint = "tcp://127.0.0.1:49152";
  void *ctx = zmq_ctx_new ();
  //  Create a subscriber
    void *router = zmq_socket (ctx, ZMQ_ROUTER);

    int hwm = 1;
    zmq_setsockopt(router, ZMQ_SNDHWM, &hwm, sizeof(hwm));
    zmq_setsockopt(router, ZMQ_RCVHWM, &hwm, sizeof(hwm));

    zmq_bind (router, endpoint);

    const char identity[] = "myidentity";
    const char msg[10000] = {0};

    int count = 0;
    while(1){
        usleep(1000);
        //int event;
        //size_t event_size = sizeof(event);

        //zmq_getsockopt (sub, ZMQ_EVENTS, &event, &event_size);

        if(count%10000 == 0)
        {
          printf("\n\ncount: %u\n", count);
          malloc_trim(0);
          malloc_stats();
        }
        ++count;

      zmq_send(router, identity, sizeof(identity), ZMQ_SNDMORE);
      zmq_send(router, "", 0, ZMQ_SNDMORE);
      zmq_send(router, msg, sizeof(msg), 0);
    }

  return 0;
}
```

dealer side:

```
#include "zmq.h"
#include <stdio.h>
#include <unistd.h>
#include <malloc.h>

int main(int argc, char* argv[])
{
    const char* endpoint = "tcp://127.0.0.1:49152";
    void *ctx = zmq_ctx_new ();
  //  Create a subscriber
    void *dealer = zmq_socket (ctx, ZMQ_DEALER);
    const char identity[] = "myidentity";
    zmq_setsockopt (dealer, ZMQ_IDENTITY, identity, sizeof(identity));

    zmq_connect (dealer, endpoint);

    int count = 0;
    while(1){
        usleep(100000);
        zmq_disconnect(dealer, endpoint);
        usleep(100000);
        zmq_connect(dealer, endpoint);
        printf("reconnect %d\n", ++count);
    }

  return 0;
}
```

dealer reconnect after a specify time interval, and router never call recv

memory use:
```
count: 0
Arena 0:
system bytes     =      24576
in use bytes     =      22384
Arena 1:
system bytes     =     135168
in use bytes     =       2256
Total (incl. mmap):
system bytes     =     159744
in use bytes     =      24640
max mmap regions =          0
max mmap bytes   =          0


count: 10000
Arena 0:
system bytes     =      49152
in use bytes     =      46608
Arena 1:
system bytes     =    1916928
in use bytes     =    1904528
Total (incl. mmap):
system bytes     =    1966080
in use bytes     =    1951136
max mmap regions =          0
max mmap bytes   =          0


count: 20000
Arena 0:
system bytes     =      61440
in use bytes     =      59584
Arena 1:
system bytes     =    3796992
in use bytes     =    3775952
Total (incl. mmap):
system bytes     =    3858432
in use bytes     =    3835536
max mmap regions =          0
max mmap bytes   =          0


count: 30000
Arena 0:
system bytes     =      73728
in use bytes     =      72192
Arena 1:
system bytes     =    4595712
in use bytes     =    4543056
Total (incl. mmap):
system bytes     =    4669440
in use bytes     =    4615248
max mmap regions =          0
max mmap bytes   =          0

--- here we stop dealer

count: 40000
Arena 0:
system bytes     =      73728
in use bytes     =      72192
Arena 1:
system bytes     =    4595712
in use bytes     =    4543056
Total (incl. mmap):
system bytes     =    4669440
in use bytes     =    4615248
max mmap regions =          0
max mmap bytes   =          0


count: 50000
Arena 0:
system bytes     =      73728
in use bytes     =      72192
Arena 1:
system bytes     =    4595712
in use bytes     =    4543056
Total (incl. mmap):
system bytes     =    4669440
in use bytes     =    4615248
max mmap regions =          0
max mmap bytes   =          0
```

In count between 0 - 30000, memory always incr, even if I control the memory use.
I stop dealer in count between 30000 - 40000, and the memory use not incr, but also not freed.

**Comment by laplaceyang** [comment]
However, this two kind memory problem can be soluted by call getsockopt(ZMQ_EVENTS), so should we just add a timer to call process_command in zmq lib? To solve the memory problem both in pub-sub with conflate, and router-dealer with router not recv.

**Comment by jamesdillonharvey** [comment]
OK so there are two cases where the memory bloats if **recv is not called**

 - SUB with ZMQ_CONFLATE
 - ROUTER

There is a timer event in socket_base, you could possibly call process_command from there. Looks like you have to add the timer to the poller
https://github.com/zeromq/libzmq/blob/6bfa91f13f73b67be47ded18986b76d154d5923b/src/socket_base.cpp#L1508

**The question is:**
Is it worth adding extra complexity to the system for these two very unique cases? Documentation (like I added for conflate) is the other option.

**Comment by laplaceyang** [comment]
@jamesdillonharvey After busy work for an afternoon on it, and confirm there is no bug in the lib, I think this is not really worth to add timer for these two very unique cases.

Call the getsockopt may be a better solution.

Closed.
