### ISSUE TITLE
Cross network 0mq subscriptions not working correctly

### ISSUE THREAD

**Issue by kveroneau** [zeromq/libzmq#3180]
*Please use this template for reporting suspected bugs or requests for help.*

# Issue description

I am running into an odd issue with a custom 0mq application which uses SUB/PUB model.  I have a 0mq publisher server running on IP 192.168.1.1 on my home network.  I have many 0mq subscribers on other devices running in 192.168.1.x, these subscribers are working with no issues.

Recently due to home WiFi issues, I have placed one of the 0mq subscribers behind another router.  The router itself has an IP of 192.168.1.253, and the 0mq subscriber on this other network has an IP of 192.168.2.5.  Running `netstat -nt` on the 0mq subscriber on 192.168.2.5, it shows it is connected to 192.168.1.1:9898, however when sending out messages which this device subscribes to does not reach the device for some reason.  When this same 0mq subscriber was running on 192.168.1.2, messages were send with no issues.  The issue with no messages reaching this client started when it was placed onto a new subnet behind a router.

I plan on performing additional troubleshooting to determine what could be causing this, however I have decided to open an issue here in the meantime in case there is a known issue with cross network PUB/SUB.  Both 0mq Publisher and Subscribers use the Python zmq library.

# Environment

* libzmq version (commit hash if unreleased): 4.0.5armhf
* OS: Raspbian Jessie
* python-zmq version: 14.4.0-1armhf

# Minimal test code / Steps to reproduce the issue

1.  Create a 0mq publisher on IP 192.168.1.1 port 9898
2.  Add a router on IP 192.168.1.253 using subnet 192.168.2.0/24
3.  Create a 0mq subscriber on IP 192.168.2.5
4.  Publish a message which the subscriber should receive.
5.  Note that message is not received on subscriber.

I will create some example code for testing this evening at home after work using these exact steps and report back in a comment what happens.

# What's the actual result? (include assertion message & call stack if applicable)

Subscriber never receives the message sent from the publisher.

# What's the expected result?

Subscriber receives message and acts upon it.

**Comment by bluca** [comment]
There is no issue with "cross network" connections, it's just TCP. You need to check your routing table/masquerading/etc

**Comment by kveroneau** [comment]
Good point, I will check that.  It seems that 192.168.2.5 can establish a connection to 192.168.1.1, but when 192.168.1.1 tries to send a packet off to 192.168.2.5, I figure the packet is lost somewhere, so the subscriber never gets the data.  I will test with netcat first and try sending packets back and forth to confirm this.  Thank you for the suggestion/idea on what the cause might be.  I will close this issue.
