### ISSUE TITLE
zmq_ctx_new() hangs on syscall getrandom() for several minutes after reboot

### ISSUE THREAD

**Issue by Chickenmarkus** [zeromq/libzmq#3183]
# Issue description
The method call `zmq_ctx_new()` hangs at the system call `getrandom()` for several minutes after a reboot.

Is it using `/dev/random` instead of `/dev/urandom`? `cat` on the first one blocks after a few bytes or even immediately while the latter one works like a charm. Probably `/dev/random` has not obtained sufficient entropy since the startup.

(My initial question on StackExchange: https://stackoverflow.com/questions/51302854/)

# Environment

* libzmq version (commit hash if unreleased): 4.2.5
* OS: Debian Testing (Buster)

# Minimal test code / Steps to reproduce the issue

1.  void *context = zmq_ctx_new (); (e. g. within the [C example](http://zguide.zeromq.org/c:hwclient))
2. Reboot the machine.
3. Run the client trying to open a new context.

# What's the actual result? (include assertion message & call stack if applicable)
It hangs at the initialization of the context. Inspected via `strace`, it hangs at the syscall `getrandom()`.

# What's the expected result?
Just getting a random number and continuing.

**Comment by bluca** [comment]
getrandom() is a system call, so you'll have to take that up to the kernel maintainers.

You should be using libsodium anyway, which will avoid tweetnacl and the need for getrandom(). Use the library from Debian rather than your own.

**Comment by Chickenmarkus** [comment]
I don't use neither `libsodium` nor `tweetnacl` nor something own. As I wrote, I just use the linked C example. `zmq_ctx_new()` involves `getrandom()` itself.

However, in the meanwhile I found libzmq sets  the flags of `getrandom()` explicitly to 0. Thus, it usually should only blocking till `/dev/urandom` is initialized.

**Comment by bluca** [comment]
getrandom is _only_ used directly when built with tweetnacl. So if you use the packaged library from Debian, it will not be used, as it's built with libsodium.

**Comment by bluca** [comment]
Again, that's just a system call being made - nothing we can do about it. It needs to be done in blocking mode as the random bytes _must_ be available at that point.
If your system doesn't have the required entropy to make it return, then your system has a problem (likely) or there is an issue in glibc/kernel (very unlikely).

And again, in production tweetnacl should not be used, only libsodium, so there will be no getrandom calls at all.

**Comment by Chickenmarkus** [comment]
Sorry for asking about probably nothing but now I want to try to understand.
Okay, I use `libzmq5` packaged from Debian. Thus, it's built with `libsodium`. Hence, there should be no getrandom calls at all, right?
Nevertheless, `getrandom()` is called and hangs as `strace` says?!?

However, I fixed it for my case:
```
$ uname -a
Linux zazu 4.16.0-2-amd64 #1 SMP Debian 4.16.16-2 (2018-06-22) x86_64 GNU/Linux
```
was NOT working. In contrast,
```
$ uname -a
Linux zazu 4.16.0-1-amd64 #1 SMP Debian 4.16.5-1 (2018-04-29) x86_64 GNU/Linux
```
IS working. Thus, it is not an issue with zmq but the syscall handled by the kernel.

**Comment by bluca** [comment]
It is of course possible that libsodium itself is using getrandom. It's a much, much better api than manually reading from /dev after all.

It is possible that there's something quite not working with the system. It's Debian testing after all.
