### ISSUE TITLE
Getting error java.lang.UnsatisfiedLinkError: no jzmq in java.library.path in IntelliJ ide with windows 10

### ISSUE THREAD

**Issue by KamranShahid** [zeromq/libzmq#3184]
I have a java project which have zeromq implementation. i have installed zeromq windows version in my windows 10 OS. When running the application i am getting above error. I have downloaded zeromq (windows) installer from http://zeromq.org/area:download and installed it in C:\ZeroMQ4.0.4 folder. Any idea what further action i have to take?

**Comment by bluca** [comment]
The correct repository for JZMQ is: https://github.com/zeromq/jzmq
