### ISSUE TITLE
Several checks fail under 64-bit MinGW on Windows when running make check

### ISSUE THREAD

**Issue by chymanfx** [zeromq/libzmq#3185]
# Issue description

I have successfully compiled libzmq via configure and 64-bit MinGW on Windows, but several checks fail.
I have tried different versions by now: 4.0.8, 4.1.6, 4.2.3 and master, all of them compile well, no warnings, no issues, but all of them get the same dozened failed tests.
Going back to version 3.2.5, the supplied tests all work fine.
I have also tried different mingw64 versions, the behavior is same.

One reason for failed tests: for example, test_reqrep_inproc.exe asserts in file   src/signaler.cpp, line
`182:    zmq_assert (nbytes == sizeof (dummy));`

This is the backtrace:

```
Starting program: test_reqrep_inproc.exe
[New Thread 3240.0x10c4]
gdb: unknown target exception 0x40000015 at 0x7fefd3ea06d

Program received signal ?, Unknown signal.
0x000007fefd3ea06d in RaiseException ()
   from C:\Windows\system32\KernelBase.dll
(gdb) bt
#0  0x000007fefd3ea06d in RaiseException ()
   from C:\Windows\system32\KernelBase.dll
#1  0x00000000697893ae in zmq::zmq_abort (
    errmsg_=0x697e29cf "nbytes == sizeof (dummy)") at src/err.cpp:80
#2  0x00000000697a1bd1 in zmq::signaler_t::send (this=0x8a8bc8)
    at src/signaler.cpp:182
#3  0x000000006978bff0 in zmq::mailbox_t::send (this=0x8a8b68, cmd_=...)
    at src/mailbox.cpp:65
#4  0x0000000069782c51 in zmq::ctx_t::send_command (this=0x8a4a10, tid_=4,
    command_=...) at src/ctx.cpp:371
#5  0x00000000697919cf in zmq::object_t::send_stop (this=0x8a8840)
    at src/object.cpp:200
#6  0x00000000697a3796 in zmq::socket_base_t::stop (this=0x8a8840)
    at src/socket_base.cpp:182
#7  0x0000000069782106 in zmq::ctx_t::terminate (this=0x8a4a10)
    at src/ctx.cpp:157
#8  0x00000000697b84e4 in zmq_ctx_term (ctx_=0x8a4a10) at src/zmq.cpp:167
#9  0x0000000000402424 in main () at test_reqrep_inproc.cpp:56
```
When I comment line 182 out, it never terminates the ctx and the test anymore, I guess it keeps signaling "stop" infinitely.
When I insert 100ms sleep commands in some of the test programs, right before "zmq_ctx_term", that seams to relieve the problem, but is not reliable for all tests.

Since it worked with version 3.2.5 and stopped working with 4.0.x, I guess it must be something deeper. Did anyone get the tests working with mingw64 or other compilers on the Windows platform successfully? Many thanks for looking into this!

# Environment

* libzmq version: 4.1.6, but also shows with 4.0.8, 4.2.3 and master (3.2.5 works fine)
* OS: Windows 7 Pro SP1
* Toolchain: msys-rev13 + x86_64-4.8.2-release-posix-seh-rt_v3-rev4 (also tried x86_64-4.9.2)

Please see complete log with zmq 4.1.6 as example for details: 
[zmq.log](https://github.com/zeromq/libzmq/files/2201289/zmq.log)

**Comment by chymanfx** [comment]
Here is a little update / summary of which tests fail for what reason:

```
test_reqrep_inproc.exe    :
    fixed by commits bcf7577 and 9624f9a     --> now PASS
test_hwm.exe		  :
    fixed by commits bcf7577 and 9624f9a     --> now PASS
test_hwm_pubsub.exe	  :
    asserts with recv_count == send_count
test_srcfd.exe  	  :
    asserts with errno == EBADF
test_unbind_wildcard.exe  :
    just fails, reason unknown ???
test_ctx_options.exe	  :
    asserts with zmq_ctx_get (ctx, ZMQ_MAX_SOCKETS) == ZMQ_MAX_SOCKETS_DFLT  --> 63 vs 1023
test_spec_req.exe	  :
    fixed by commits bcf7577 and 9624f9a     --> now PASS
test_req_relaxed.exe	  :
    just fails, reason unknown ???
test_inproc_connect.exe   :
    works when number of simultanious connects is reduce from 50 to 30, todo with ZMQ_MAX_SOCKETS=63 ???
test_proxy.exe  	  :
    hangs forever in zmq_ctx_term
test_ipc_wildcard.exe	  :
   is this test meant to be for windows ??? (other ipc tests are not included for windows)

```

**Comment by sigiesec** [comment]
Unfortunately, there are no MinGW ci job at the moment, so these problems have not been noticed. There has been a Cygwin CI job for some time, but there are also tests failing. If you could add CI for MinGW and fix these issues, it would be great.

For adding CI, look at all references to cygwin in https://github.com/zeromq/libzmq/blob/master/appveyor.yml. MinGW can probably be handled in a very similar way. To my knowledge, it is already preinstalled on the Appveyor machines.

**Comment by chymanfx** [comment]
Thank you for your comment and direction. I have to admit that I am a bit of a newbie on ci and c++, but I will try to look into Appveyor and add MinGW ci job to the appveyor.yml to help automating the MinGW testing.

**Comment by chymanfx** [comment]
I had a look at the Appveyor file and found that it is mostly build around cmake. In order not to completely rewrite the appveyor.yml to handle "configure", I tried to adapt my build procedure accordingly. The following commands worked for me by hand from cmd.exe:

For configure:
```
set PATH=C:\mingw64\bin;C:\msys\bin;%PATH%
tar xvzf zeromq-4.1.6.tar.gz
cd zeromq-4.1.6
bash configure --build=x86_64-w64-mingw32
make check
```

For cmake:
```
set PATH=C:\mingw64\bin;C:\msys\bin;%PATH%
tar xvzf zeromq-4.1.6.tar.gz
md build
cd build
cmake -D CMAKE_INCLUDE_PATH="" -D CMAKE_LIBRARY_PATH="" -D WITH_LIBSODIUM="OFF" -D ENABLE_DRAFTS="ON" -D ENABLE_ANALYSIS="" -D ENABLE_CURVE="ON" -D API_POLLER="" -D POLLER="" -D WITH_LIBSODIUM="OFF" -D LIBZMQ_WERROR="ON" -G "Unix Makefiles" "z:\zeromq-4.1.6"
cmake --build .
ctest -C "Release" -V
```
With cmake there are some warnings, but also compiles successfully, yet the results don't run for me.

I have adapted the appveyor.yml to include mingw64 as new platform, see attached file (ext. changed to txt): [appveyor.txt](https://github.com/zeromq/libzmq/files/2223564/appveyor.txt)

For readability and maintainability I have changed some "if" statements and indentation, I hope you like it. I hope you can have a look at it and replace the current one with it if fine.

**Comment by chymanfx** [comment]
I resolved the cmake warnings by removing the  -D LIBZMQ_WERROR="ON"  flag. My local mingw64 version is a little old and seems to have a problem with it.

Now the results run fine for me and I get the same test results from cmake:
```
80% tests passed, 9 tests failed out of 45

Total Test time (real) =  37.73 sec

The following tests FAILED:
          4 - test_reqrep_inproc (Failed)
          6 - test_hwm (Failed)
          7 - test_hwm_pubsub (Failed)
         10 - test_invalid_rep (Failed)
         23 - test_unbind_wildcard (Failed)
         24 - test_ctx_options (Failed)
         30 - test_spec_req (Failed)
         38 - test_inproc_connect (Failed)
         40 - test_shutdown_stress (Failed)
Errors while running CTest
```

The appveyor mingw64 version is much newer and may not have this issue with -errwarn=%all.

As a side note: Instead of  -G "Unix Makefiles"  we can switch to  -G "MSYS Makefiles"  for mingw64 platform as the PATH variable includes MSYS as well.
