### ISSUE TITLE
Is this possible?

### ISSUE THREAD

**Issue by textbrowser** [zeromq/libzmq#3192]
*Please use this template for reporting suspected bugs or requests for help.*

# Issue description

This is not a problem report!

I would like to know if the following is possible with zeromq. Please assume that the referenced processes reside on one machine.

There are a bunch of processes each having a single TCP socket connection. As data is received through some socket, I'd like to place the data in some specific bin using zeromq. Some other process will be notified of the new data. Items in bins should self-expire after some time. The bins are not owned by any single process in the socket group. A bin should be magically created if it does not exist, that is, subscriptions are dynamic. Also necessary is a mechanism for retrieving the list of bin identities.

[Bin A] [Bin B] ... [Generic Bin] <- One or more processes will read and write items from and to one or more bins. A guardian process will remove expired items if zeromq does not provide such a feature. The guardian process will also own the set of bins.

I'm searching for a solution (zeromq?) that does not require me to manage databases, queues, bins, local sockets, memory, notifications and have it (zeromq?) do everything, mostly.

Thank you for any guidance!

# Environment

* libzmq version (commit hash if unreleased): 
* OS: 

# Minimal test code / Steps to reproduce the issue

1.  

# What's the actual result? (include assertion message & call stack if applicable)

# What's the expected result?

**Comment by bluca** [comment]
Have a look at the zguide, you should be able to find a pattern that suits your use case: http://zguide.zeromq.org
