### ISSUE TITLE
Problem: libzmq can not be used as an cmake object library

### ISSUE THREAD

**Issue by justusranvier** [zeromq/libzmq#3196]
It's not possible to use libzmq as a subproject in another cmake project for use as an object library.

If both BUILD_STATIC and BUILD_SHARED are turned off by the parent project cmake will still still try to install targets that do not exist.

Solution: modify CMakeLists.txt to avoid exporting targets and installing files if neither BUILD_SHARED nor BUILD_STATIC is set

**Comment by bluca** [comment]
https://github.com/zeromq/libzmq/pull/3197
