### ISSUE TITLE
Using zmq_send under windows sometimes causes assertion failure

### ISSUE THREAD

**Issue by lsmengineer** [zeromq/libzmq#3200]
*Please use this template for reporting suspected bugs or requests for help.*

# Issue description
The two functions zmq_recv and zmq_send run in two thread. The two threads use a mutex. The software sometimes reports Assertion failed: false (..\..\..\..\src\object.cpp : 155) Error, which causes the software to flash back. Viewing through the zmq source is caused by the undefined cmd.type in the process_command function. Unable to debug the error message because the software throws an abnormal time.

Compile the zmq environment to vs2015(x86)
Use zmq environment for QT5.9.0 compilation environment msvc-2015 (32bit)

# Environment

* libzmq version (commit hash if unreleased): 4.2.3
* OS: win64

# Minimal test code / Steps to reproduce the issue

```
void zmqGUI::sendData(QByteArray *data)
{
	run_lock.lock();
	int zmqStatus = zmq_send(z_socket, data->data(), data->length(), 0);
	if (zmqStatus < 0)
	{
		qDebug() << "send zmq data fail:" << zmqStatus;
	}
	run_lock.unlock();
}
```

# What's the actual result? (include assertion message & call stack if applicable)

Assertion failed: false (..\..\..\..\src\object.cpp:155)

# What's the expected result?
Cause of assertion failure？

**Comment by bluca** [comment]
> The two functions zmq_recv and zmq_send run in two thread.

The documentation is quite clear - this is not supported. Sockets are not thread safe. You _must_ create, use and destroy a socket from the same thread.
