### ISSUE TITLE
Question about IPC file unlinking on context termination

### ISSUE THREAD

**Issue by Peque** [zeromq/libzmq#3204]
It seems https://github.com/zeromq/libzmq/issues/2764 was fixed by https://github.com/zeromq/libzmq/pull/2765.

I have a project ([osBrain](https://github.com/opensistemas-hub/osbrain)) that uses PyZMQ. The recent PyZMQ 17 version bundles libzmq 4.2, which includes that fix.

osBrain is a multi-agent system that creates IPC connections with random addresses between agents. The problem is that now our test suite [fails](https://travis-ci.org/opensistemas-hub/osbrain/builds/405590284) when checking that no IPC files are left in the file system after finishing osBrain code execution. Actually, the test suite leaves hundreds of those files in the file system. This issue ultimately leads to an operating system error due to an excessive number of files.

I wonder, is that really the expected behavior? As I do not have direct control over the creation of that file, why should I take care of its unlinking? In example: if I had to `open()` the IPC file manually before binding, I would understand I had to unlink it afterwards. But when binding, the IPC file creation is "transparent".

I find that change so disruptive that I think I may be missing something and maybe there is a way to make libzmq/PyZMQ unlink all those files on context termination?

Am I doing something wrong or should I really be unlinking all those files manually on termination? If I run a program on my system that opens some IPC files, I would always expect that program to remove them after execution and do not pollute my file system if it is not running. Should not that be the default behavior in libzmq?

**Comment by bluca** [comment]
Well the issue is that either #2764 or this can be fixed, not both. So take your pick...
In your case, you can create the files in the /run ephemeral filesystem and that should take care of the problem

**Comment by Peque** [comment]
@bluca Okay, just wanted to make sure I was not missing something. I still find this default behavior unfriendly, but it seems nobody else has complained, so it must be only me. :stuck_out_tongue_winking_eye: 

Maybe you could leave this open anyway, for future users to :+1: if they find that default behavior unfriendly?

Yeah in GNU/Linux systems we store those files by default under `$XDG_RUNTIME_DIR` (`/run/user/<ID>`). But that does not solve the problem, as automatic cleaning of those files [is not guaranteed in time](https://standards.freedesktop.org/basedir-spec/basedir-spec-latest.html) (for our use case we can be continuously creating new connections and destroying old ones).

> [...] Files in this directory MAY be subjected to periodic clean-up. To ensure that your files are not removed, they should have their access time timestamp modified at least once every 6 hours of monotonic time or the 'sticky' bit should be set on the file.

Anyway we already [have a fix](https://github.com/opensistemas-hub/osbrain/pull/307), so we can definitely fix that on our side.

**Comment by bluca** [comment]
@Peque I realise the behaviour is unfriendly, but the race condition is real, and extremely difficult to fix (filename might be shared not only across different sockets but different contexts).

Feel free to send a PR to add a socket option to optionally unlink the files on close.
