### ISSUE TITLE
[Query] Regarding zcert_t [czmq] equivalent in libzmq 

### ISSUE THREAD

**Issue by jay11ca39** [zeromq/libzmq#3207]
Hi @bluca ,

**This is not an issue it is query.** 

I am working on some project in which i want to enable zmq curve security [libzmq].  I checked the samples and test cases in which by setting the socket options we can set the public and secret key for client and server : https://github.com/zeromq/libzmq/blob/master/tests/test_security_curve.cpp

I checked the examples of czmq: 
https://github.com/zeromq/czmq/blob/master/examples/security/

There they are using the file path of certificate which contains the public and private pair.. and many other abstracted APIs are given.

Is such kind of APIs, in which we can pass the certificate path to libzmq and internally it will set all the keys.. Is it there or any alternative way to set certificate to libzmq?

**Comment by bluca** [comment]
CZMQ is a high level abstraction above libzmq. That's by design. So if you want that kind of commodity you need to use CZMQ, or implement it yourself in your application. libzmq only takes buffers with keys.

**Comment by jay11ca39** [comment]
@bluca ,
Thanks for quick response.
 I am using libzmq in my project. I will see to implement some of the abstracted API for certificates in my sdk. Thanks..:)
