### ISSUE TITLE
Visual Studio 2013 Debug builds with libsodium are failing test_security_curve

### ISSUE THREAD

**Issue by sigiesec** [zeromq/libzmq#3210]
# Issue description

The test case test_security_curve fails due to a heap corruption.

# Environment

* libzmq version (commit hash if unreleased): Apparently all since 7e6792ca74b40de1a081479ba73154ece0a81100
* OS: Windows

# Minimal test code / Steps to reproduce the issue

1.  Build with Visual Studio 2013 and libsodium
2.  Run test_security_curve

# What's the actual result? (include assertion message & call stack if applicable)

```
68: Test command: C:\projects\build_libzmq\bin\Debug\test_security_curve.exe
68: Test timeout computed to be: 60
68: f:\dd\vctools\crt\crtw32\misc\dbgheap.c(1328) : Assertion failed: _BLOCK_TYPE_IS_VALID(pHead->nBlockUse)
64/81 Test #68: test_security_curve ..............***Exception: SegFault  0.03 sec
```

cf. https://ci.appveyor.com/project/zeromq/libzmq/build/build-2491/job/ynbe789n221wgooi#L1325

# What's the expected result?

No failure.

**Comment by bluca** [comment]
How did that commit affect the libsodium run?

**Comment by sigiesec** [comment]
Maybe it was failing already before, but the previous build was fine. Maybe just a coincidence.

The commit did not change any relevant code at all, and libsodium did not change either at that time.

**Comment by sigiesec** [comment]
I cannot reproduce it with VS2017 locally :(

**Comment by bluca** [comment]
@sigiesec any chance you've got time to look at this? Given the TIPC one is fixed now, I think this is the only blocker for a new release

**Comment by sigiesec** [comment]
I will try to look at it in the next days, but I cannot promise, sorry!

**Comment by sigiesec** [comment]
Finally I made some progress, I installed VS2013. Will give the failing test a look tomorrow.

**Comment by sigiesec** [comment]
Unfortunately, I cannot reproduce the problems with VS2013 on my machine either :(
