### ISSUE TITLE
Issue for setting socket option [ZMQ_CURVE_SERVERKEY] for multiple publishers

### ISSUE THREAD

**Issue by jay11ca39** [zeromq/libzmq#3216]
# Issue description
I have built libzmq for secured mode [with libsodium]. I have tested single publisher and single subscriber sample applications. Samples are working fine.

I want to test when there are 2 or more publishers and one subscriber want to receive data from all the publishers in **Secured mode**. This is normal behavior and I have tested the same in **Unsecured node**. In unsecured mode is **working fine**. But in secured mode it is getting the data from the last publisher whose key we have set at last in subscriber.

# Environment Linux 

* libzmq version : v4.2.2
* OS:  Ubuntu 16.04

# Minimal test code / Steps to reproduce the issue
**Sample Publisher1:**
```
rc = zmq_setsockopt (pubSocket1, ZMQ_CURVE_SERVER, &as_server, sizeof (int));
rc = zmq_setsockopt (pubSocket1, ZMQ_CURVE_SECRETKEY, server_secret1, 41);
```

**Sample Publisher2:**
```
rc = zmq_setsockopt (pubSocket2, ZMQ_CURVE_SERVER, &as_server, sizeof (int));
rc = zmq_setsockopt (pubSocket2, ZMQ_CURVE_SECRETKEY, server_secret2, 41);
```

**Sample Subscriber:**
```
rc = zmq_setsockopt (subSocket, ZMQ_CURVE_SERVERKEY, server_public1, 41);
rc = zmq_setsockopt (subSocket, ZMQ_CURVE_SERVERKEY, server_public2, 41);  --> here it is overwriting the old option ZMQ_CURVE_SERVERKEY with new key
rc = zmq_setsockopt (subSocket, ZMQ_CURVE_PUBLICKEY, client_public, 41);
rc = zmq_setsockopt (subSocket, ZMQ_CURVE_SECRETKEY, client_secret, 41);
```

	
# What's the actual result?
It is receiving data from last publisher, whose public key we have set on subscriber at last. It means it is over-writing the socket option. [ZMQ_CURVE_SERVERKEY]. In above sample, it is receiving the data from Publisher2 and for  Publisher1 it is showing the error :
`CURVE I: cannot open client HELLO -- wrong server key?`

# What's the expected result?
It should receive data from all the publishers whose keys we have set on subscriber side.

**Comment by bluca** [comment]
This cannot work - either use 2 sub sockets, or use the same key on the publishers

**Comment by sigiesec** [comment]
I think to achieve what you want, you need to revert the server and client roles:

Sample Publisher1:
```
int as_server = 0;
rc = zmq_setsockopt (pubSocket1, ZMQ_CURVE_SERVER, &as_server, sizeof (int));
rc = zmq_setsockopt (subSocket, ZMQ_CURVE_SERVERKEY, server_public, 41);
rc = zmq_setsockopt (subSocket, ZMQ_CURVE_PUBLICKEY, client1_public, 41);
rc = zmq_setsockopt (subSocket, ZMQ_CURVE_SECRETKEY, client1_secret, 41);
```

Sample Publisher2:
```
int as_server = 0;
rc = zmq_setsockopt (pubSocket2, ZMQ_CURVE_SERVER, &as_server, sizeof (int));
rc = zmq_setsockopt (subSocket, ZMQ_CURVE_SERVERKEY, server_public, 41);
rc = zmq_setsockopt (subSocket, ZMQ_CURVE_PUBLICKEY, client2_public, 41);
rc = zmq_setsockopt (subSocket, ZMQ_CURVE_SECRETKEY, client2_secret, 41);
```

Sample Subscriber:
```
int as_server = 1;
rc = zmq_setsockopt (pubSocket2, ZMQ_CURVE_SERVER, &as_server, sizeof (int));
rc = zmq_setsockopt (subSocket, ZMQ_CURVE_PUBLICKEY, server_public, 41);
rc = zmq_setsockopt (subSocket, ZMQ_CURVE_SECRETKEY, server_secret, 41);
```

**Comment by bluca** [comment]
CURVE only works with a 1:N pattern - one "server-ish" and N clients. You can invert the roles as Simon suggested, or have multiple sockets.

**Comment by jay11ca39** [comment]
Hi @bluca ,
Changing the roles may be one option.

But, I have tested with the approach that I explained.
It is working fine. My subscriber is able to receive data from both the publishers. 

I do not know the internal of ZMQ security, but the approach is working fine. 
Can you please let me know, will it create any problem?

**Comment by jay11ca39** [comment]
Hi @bluca ,
I have tested that scenario as well... 
Subscriber was running and I terminated the first publisher ..then again started the publisher and even after that subscriber was able to receive the data .

**Comment by bluca** [comment]
If that works for you then there's nothing to do here, closing
