### ISSUE TITLE
php-ext unexpected behaviour of ZMQ_LINGER=0

### ISSUE THREAD

**Issue by proArtex** [zeromq/libzmq#3234]
# Issue description
Could you please verify that php-ext behaviour is incorrect according to this [issue](https://github.com/mkoppanen/php-zmq/issues/191)

# Environment

* libzmq version 4.2.5
* ext-zmq version 1.1.3
* Mac OS Sierra 10.12.6

# Minimal test code / Steps to reproduce the issue

1. create persistent context
2. create socket (PULL)
3. bind to tcp://127.0.0.1:5555
4. recv in cycle

5. create another persistent context
6. create another socket (PUSH)
7. set socket opt ZMQ_LINGER = 0
8. connect to tcp://127.0.0.1:5555
9. send message

# What's the actual result? (include assertion message & call stack if applicable)

There is like 1 of 5 sent messages (step 5-9) received.

# What's the expected result?

5 messages received.

**Comment by bluca** [comment]
I'm not sure I follow - what exactly is the issue? If you close a program with linger 0 then messages may be dropped

**Comment by proArtex** [comment]
PUSH socket with linger 0 stop to send messages to alive PULL one, it may send like 1 of 5 tries. PUSH socket has short fpm-script life, when PULL socket is still alive as cli.

**Comment by bluca** [comment]
I still don't follow. You've set linger 0, and then the script exits after sending. Is that right?

**Comment by proArtex** [comment]
That's right. You can see php example [here](https://github.com/mkoppanen/php-zmq/issues/191)

**Comment by bluca** [comment]
That's working as intended. If you don't want messages to be lost, set linger to infinite.

**Comment by proArtex** [comment]
You didn't catch the point. I want them to be lost. But if I set linger 0 there no delivered messages at all.

**Comment by bluca** [comment]
Yes. That's because the script exits and the sockets are killed before the messages are delivered. That's what linger is for.

**Comment by proArtex** [comment]
Got it. Thanks!
