### ISSUE TITLE
Issues building libzmq with visual studio 2015 - error LNK1181: cannot open input file 'libzmq.lib'

### ISSUE THREAD

**Issue by Vizhen123** [zeromq/libzmq#3235]
Hi all, 

I've been having problems building libzmq 4.2.5 with visual studio 2015. I've tried using the vs command prompt and running build.bat but it fails. I've also tried building from the libzmq.sln in the vs2015 directory but that doesn't work for me either. I get the error: _LINK : fatal error LNK1181: cannot open input file 'libzmq.lib'_ and _fatal error C1189: #error:  None of the ZMQ_IOTHREAD_POLLER_USE_* macros defined (compiling source file ..\..\..\..\src\kqueue.cpp)._ 

Am I missing some steps in the building process? The INSTALL file and other zeromq resources don't really provide any more instructions beyond this and I don't have much experience in this so I'm hoping someone will be able to help me thank you.  

p.s. I had downloaded libzmq 4.2.3 earlier and had similar problems also so I tried my luck with this version. I changed the additional library directories in libzmq 4.2.3 but that didn't seem to make a difference. 

Also, I'd just like to mention that my main goal is to get this working with pyzmq so if anyone can suggest an easier way of doing this, i would really appreciate it! Thanks! 

# Environment
* libzmq version (commit hash if unreleased): 4.2.5
* OS: Windows 10 home
* Visual Studio 2015

# Minimal test code / Steps to reproduce the issue

1.  Ran build.bat from VS command prompt 
 and 
1. Build libzmq.sln 

# What's the actual result? (include assertion message & call stack if applicable)

One of the recurring errors that show up when using build.bat is: 
`    2>c:\users\vivia\documents\libzmq\src\poller.hpp(59): fatal error C1189: #error:  None of the ZMQ_IOTHREAD_POLLER_USE_* macros defined (compiling source file ..\..\..\..\src\xsub.cpp) [c:\Users\vivia\Documents\libzmq\builds\deprecated-msvc\vs2015\libzmq\libzmq.vcxproj]
         zmq_utils.cpp
     2>c:\users\vivia\documents\libzmq\src\poller.hpp(59): fatal error C1189: #error:  None of the ZMQ_IOTHREAD_POLLER_USE_* macros defined (compiling source file ..\..\..\..\src\xpub.cpp) [c:\Users\vivia\Documents\libzmq\builds\deprecated-msvc\vs2015\libzmq\libzmq.vcxproj]
     2>c:\users\vivia\documents\libzmq\src\poller.hpp(59): fatal error C1189: #error:  None of the ZMQ_IOTHREAD_POLLER_USE_* macros defined (compiling source file ..\..\..\..\src\zmq.cpp) [c:\Users\vivia\Documents\libzmq\builds\deprecated-msvc\vs2015\libzmq\libzmq.vcxproj]
     2>c:\users\vivia\documents\libzmq\src\poller.hpp(59): fatal error C1189: #error:  None of the ZMQ_IOTHREAD_POLLER_USE_* macros defined (compiling source file ..\..\..\..\src\zap_client.cpp) [c:\Users\vivia\Documents\libzmq\builds\deprecated-msvc\vs2015\libzmq\libzmq.vcxproj]
     2>Done Building Project "c:\Users\vivia\Documents\libzmq\builds\deprecated-msvc\vs2015\libzmq\libzmq.vcxproj" (default targets) -- FAILED.
     1>Done Building Project "c:\Users\vivia\Documents\libzmq\builds\deprecated-msvc\vs2015\libzmq.sln" (default targets) -- FAILED.`

When I use visual studio I get the same thing:

`1>------ Build started: Project: libzmq, Configuration: ReleaseDLL x64 ------
1>  ConfigurationType : DynamicLibrary
1>  Configuration     : ReleaseDLL
1>  PlatformToolset   : v140
1>  TargetPath        : C:\Users\vivia\Documents\libzmq\builds\deprecated-msvc\vs2015\libzmq\..\..\..\..\bin\x64\Release\v140\dynamic\libzmq.dll
1>  Option-tweet      : true
1>  Option-sodium     :
1>  Option-openpgm    :
1>  Option-gssapi     :
1>  Option-draftapi   :
1>  Option-usepoll    :
1>  client.cpp
1>  ctx.cpp
1>  curve_client.cpp
1>  curve_mechanism_base.cpp
1>  curve_server.cpp
1>  dealer.cpp
1>  devpoll.cpp
1>  dgram.cpp
1>c:\users\vivia\documents\libzmq\src\poller.hpp(59): fatal error C1189: #error:  None of the ZMQ_IOTHREAD_POLLER_USE_* macros defined (compiling source file ..\..\..\..\src\devpoll.cpp)
_...............(more of the same thing)_....................
1>c:\users\vivia\documents\libzmq\src\poller.hpp(59): fatal error C1189: #error:  None of the ZMQ_IOTHREAD_POLLER_USE_* macros defined (compiling source file ..\..\..\..\src\xpub.cpp)
1>c:\users\vivia\documents\libzmq\src\poller.hpp(59): fatal error C1189: #error:  None of the ZMQ_IOTHREAD_POLLER_USE_* macros defined (compiling source file ..\..\..\..\src\zap_client.cpp)
2>------ Build started: Project: inproc_thr, Configuration: ReleaseDEXE x64 ------
3>------ Build started: Project: inproc_lat, Configuration: ReleaseDEXE x64 ------
4>------ Build started: Project: remote_thr, Configuration: ReleaseDEXE x64 ------
5>------ Build started: Project: remote_lat, Configuration: ReleaseDEXE x64 ------
6>------ Build started: Project: local_thr, Configuration: ReleaseDEXE x64 ------
7>------ Build started: Project: local_lat, Configuration: ReleaseDEXE x64 ------
2>  ConfigurationType : Application
2>  Configuration     : ReleaseDEXE
2>  PlatformToolset   : v140
2>  TargetPath        : C:\Users\vivia\Documents\libzmq\builds\deprecated-msvc\vs2015\inproc_thr\..\..\..\..\bin\x64\Release\v140\dynamic\inproc_thr.exe
2>  Linkage-libzmq    : dynamic
2>LINK : fatal error LNK1181: cannot open input file 'libzmq.lib'
4>  ConfigurationType : Application
4>  Configuration     : ReleaseDEXE
4>  PlatformToolset   : v140
4>  TargetPath        : C:\Users\vivia\Documents\libzmq\builds\deprecated-msvc\vs2015\remote_thr\..\..\..\..\bin\x64\Release\v140\dynamic\remote_thr.exe
4>  Linkage-libzmq    : dynamic
3>  ConfigurationType : Application
3>  Configuration     : ReleaseDEXE
3>  PlatformToolset   : v140
3>  TargetPath        : C:\Users\vivia\Documents\libzmq\builds\deprecated-msvc\vs2015\inproc_lat\..\..\..\..\bin\x64\Release\v140\dynamic\inproc_lat.exe
3>  Linkage-libzmq    : dynamic
5>  ConfigurationType : Application
5>  Configuration     : ReleaseDEXE
5>  PlatformToolset   : v140
5>  TargetPath        : C:\Users\vivia\Documents\libzmq\builds\deprecated-msvc\vs2015\remote_lat\..\..\..\..\bin\x64\Release\v140\dynamic\remote_lat.exe
5>  Linkage-libzmq    : dynamic
4>LINK : fatal error LNK1181: cannot open input file 'libzmq.lib'
3>LINK : fatal error LNK1181: cannot open input file 'libzmq.lib'
5>LINK : fatal error LNK1181: cannot open input file 'libzmq.lib'
7>  ConfigurationType : Application
7>  Configuration     : ReleaseDEXE
7>  PlatformToolset   : v140
7>  TargetPath        : C:\Users\vivia\Documents\libzmq\builds\deprecated-msvc\vs2015\local_lat\..\..\..\..\bin\x64\Release\v140\dynamic\local_lat.exe
7>  Linkage-libzmq    : dynamic
6>  ConfigurationType : Application
6>  Configuration     : ReleaseDEXE
6>  PlatformToolset   : v140
6>  TargetPath        : C:\Users\vivia\Documents\libzmq\builds\deprecated-msvc\vs2015\local_thr\..\..\..\..\bin\x64\Release\v140\dynamic\local_thr.exe
6>  Linkage-libzmq    : dynamic
7>LINK : fatal error LNK1181: cannot open input file 'libzmq.lib'
6>LINK : fatal error LNK1181: cannot open input file 'libzmq.lib'
========== Build: 0 succeeded, 7 failed, 0 up-to-date, 0 skipped ==========`

**Comment by bluca** [comment]
Use cmake

**Comment by evoskuil** [comment]
How should these macros be defined for the VS builds?

**Comment by bluca** [comment]
Using cmake it will be done automatically I think - @sigiesec ?

**Comment by sigiesec** [comment]
Yes, they will be defined by cmake. There is a default, which you could override by setting the POLLER cmake definition (valid values for Windows are select or epoll).

**Comment by evoskuil** [comment]
I got that part :).

**Comment by evoskuil** [comment]
I assume this a new configuration option that should be added to the IDE configuration properties.

**Comment by bluca** [comment]
@Vizhen123 have you managed to succeed using cmake from visual studio?
