### ISSUE TITLE
Does the zmq have a transport message between two processes by shared memory?

### ISSUE THREAD

**Issue by westeast** [zeromq/libzmq#3241]
*Please use this template for reporting suspected bugs or requests for help.*

# Issue description
I want to transport message by shared-memory

# What's the expected result?
I want to transport message by shared-memory

**Comment by bluca** [comment]
http://api.zeromq.org/master:zmq-inproc

**Comment by jimklimov** [comment]
I am not sure 'inproc' is a full answer to the original question, as it is
a transport between threads of same process and I think the OP implied a
sort of SHM between different processes to, I guess, minimise the latency
and processing overhead of syscalls and perhaps even structured message
en/de-coding.

**Comment by bluca** [comment]
http://api.zeromq.org/master:zmq-ipc then is the closest

**Comment by westeast** [comment]
@bluca Thanks so much

**Comment by KOLANICH** [comment]
So, can inproc be used for different processes sharing a memory mapping?

**Comment by taylorjdawson** [comment]
@bluca when you indicated that `zmq_ipc` is the closest, are you implicitly stating that as of right now ØMQ does not support POSIX shared-memory IPC?

**Comment by bluca** [comment]
> @bluca when you indicated that `zmq_ipc` is the closest, are you implicitly stating that as of right now ØMQ does not support POSIX shared-memory IPC?

Yes

**Comment by KOLANICH** [comment]
So why is it closed then?

**Comment by fatfatson** [comment]
+1

**Comment by poly2it** [comment]
Odd that this is still closed, it'd be great if there was a statement on whether this will be considered. I'm interested in shared memory as an IPC backend for overhead reduction. ZMQ has the benefits of exposing a standardised structured and rich API.
