### ISSUE TITLE
SIGABRT on assert if example code is nested on my project

### ISSUE THREAD

**Issue by fabioz23** [zeromq/libzmq#3249]
*Please use this template for reporting suspected bugs or requests for help.*

# Issue description
SIGABRT on assert if example code is nested on my project

I'm trying to add zmq functionalities on my project.
Testing alone this example is OK, it works: http://zguide.zeromq.org/c:psenvpub
But if i copy this code on my project when i call the func that launch this code i obtain
```
Assertion failed: rc == 1 (../zeromq-4.2.5/src/signaler.cpp:275)
Aborted
```
# Environment
my C project without external dependencies. Is a program that read/write from sockets and serial port.

* libzmq version (commit hash if unreleased): 4.2.5
* OS: Linux Yocto 2.1.2 Kernel 4.1.36+g2a95ccc armv7l

# Minimal test code / Steps to reproduce the issue

1.  

# What's the actual result? (include assertion message & call stack if applicable)

# What's the expected result?

**Comment by bluca** [comment]
> But if i copy this code on my project when i call the func that launch this code i obtain

Can you provide a minimal test program that reproduces this?

**Comment by fabioz23** [comment]
[CMakeLists-OK.txt](https://github.com/zeromq/libzmq/files/2371149/CMakeLists-OK.txt)
[CMakeLists-ERR.txt](https://github.com/zeromq/libzmq/files/2371150/CMakeLists-ERR.txt)
[main.c.txt](https://github.com/zeromq/libzmq/files/2371152/main.c.txt)

Unfortunately no. I can only attach the main.c with some code parts removed.

In attachment 2 CMakeLists.txt, if I compile only the main the demo PUB code works.
If I compile with the remaining project files it gives me this error:
```
Welcome
Invalid argument (../zeromq-4.2.5/src/signaler.cpp:260)
Aborted
```
With this informations it seems that something (var, define, func) shared between zmq and my project is rewritten and then causes error on zmq. But my project works with sockets, files and serial port. There isn't assert redefine, etc.

**Comment by bluca** [comment]
If you can't provide a way to reproduce it, it will be next to impossible to figure out what the problem is.

Make sure you are not using sockets from multiple threads, for starters.

**Comment by fabioz23** [comment]
i don't use pthread.
I'm checking but at the moment i don't see any problem....

**Comment by fabioz23** [comment]
because my project is relatively big but with a medium complexity **the only reason why zmq goes in abort state is related to other sockets opened by the main program.**

trying with nanomsg the problem does not occur and then i proceed with nanomsg.

**Comment by bluca** [comment]
Ok, I'll close then
