### ISSUE TITLE
INSTALL documentation regarding windows builds is out of date.

### ISSUE THREAD

**Issue by marvingreenberg** [zeromq/libzmq#3258]
*Please use this template for reporting suspected bugs or requests for help.*

# Issue description

The documentation in INSTALL regarding windows builds is outdated.

    For Windows building, see the libzmq\builds\msvc\readme.txt file.  

This directory has been renamed to deprecated-msvc.  Commit comments suggest CMake is now preferred, but it unclear if CMake can be used for older platform builds, or if the deprecated project files should be used, for, e.g. Window7 VS2017. 

# Environment

* libzmq version (commit hash if unreleased): 17df28d
* OS: Documentation

**Comment by bluca** [comment]
@sigiesec could you please have a look when you have a sec, thanks

**Comment by bluca** [comment]
@marvingreenberg the CI uses cmake with various old VS versions so it should be all right

**Comment by sigiesec** [comment]
I removed the reference to the deprecated files. I noticed that the INSTALL file is somewhat confusing in general (I must admit I have never looked into it before). It refers to CMake at some places, and to the autotools at other places, without making the options clear. It should be rewritten IMO.

**Comment by bluca** [comment]
great, thanks
