### ISSUE TITLE
Boost.ASIO integration stopped working with master

### ISSUE THREAD

**Issue by hoditohod** [zeromq/libzmq#3269]
# Issue description
Hi,
I'm using ZeroMQ and Boost.ASIO together in a Windows application. The zmq's internal signalig socket is retrieved with ZMQ_FD socket option, and passed to ASIO wrapped in a asio::ip::tcp::socket for completion handler notification. The logic is identical to the one in [AZMQ](https://github.com/zeromq/azmq/blob/master/azmq/detail/socket_ops.hpp#L106): a duplicate handle is passed, no read/write performed on the ZMQ_FD socket itself. Asio is using IOCP.

This mechanism was working fine with libzmq 4.2.5 but fails master from mid august. I get an exception in the tcp::socket constructor: 'assign: The parameter is incorrect'. If I disable the IOCP backend in ASIO it starts working again. I found something similar on [StackOverflow](https://stackoverflow.com/a/5329413/2233603) stating that the operation fails in CreateIoCompletionPort because the socket is already associated to an IOCP. 

I suspect the most recent zmq poller code uses IOCP on windows and that causes the hickup with boost.  I'm not familiar with IOCP's at all. Do you think this is the case? Do I have other options than disabling IOCP in either boost or libzmq? 

@rodgert Did you experience this with AZMQ?

# Environment
Win7 and Win10
Boost 1.62 
VS2017
libzmq version (commit hash if unreleased):  libzmq master aug. 15 (2cdad3d0ced9f4ef4d9647cfd60cd697a04ca41a)

**Comment by bluca** [comment]
There's no usage of IOCP here, so it must be something else. Probably the switch to epoll by default? Have you tried forcing back to select?
@sigiesec any idea?

**Comment by hoditohod** [comment]
I'm using CMake and VS2017 for the build, I don't pass any flags to CMake apart from the BUILD_TYPE=RelWithDebInfo. 

The output is: 
-- Using polling method in I/O threads: select
-- Using polling method in zmq_poll(er)_* API: select

So it's probably not wepoll... I'll try to track down the commit, and double check on my side.

**Comment by bluca** [comment]
yeah try to bisect and see what comes up

**Comment by sigiesec** [comment]
Could you provide some example code using Boost.Asio and libzmq that reproduces this? Then I can give it a look.

**Comment by enricodetoma** [comment]
Example that reproduces the behavior.
Windows 10 - Visual C++ 2017 - Boost 1.68 - AZMQ

	#define _WIN32_WINNT 0x0A00
	#include <iostream>
	#include <boost/asio.hpp>
	#include <azmq/socket.hpp>

	using namespace boost::asio;

	void main ()
	{
		io_service service;
		io_service::work work (service);

		try {
			azmq::rep_socket socket (service);
		}
		catch (std::exception &e) {
			std::cout << e.what ();
		}
	}

Output:

	assign: Parametro non corretto

**Comment by sigiesec** [comment]
With some existing builds I found that 2aa54d662048f420ac0dbd5d9b46559963a675f2 was still fine, while d7e51cdfed4159b8 was not. I will try to extract a libzmq test case from what boost::asio/azmq do, and the bisect.

**Comment by sigiesec** [comment]
Bisecting showed that 2d9a8955f54f1b21032f27fc0b9cf771772b0bba is the first bad commit

**Comment by sigiesec** [comment]
I found a simple solution. In the call to WSASocket, WSA_FLAG_OVERLAPPED must also be specified.
