### ISSUE TITLE
After unsubscribe XSUB socket receives messages sent before the unsubscribe event

### ISSUE THREAD

**Issue by kikosha** [zeromq/libzmq#3274]
**Issue description:**
Messages that are sent by a PUB socket to an XSUB socket before XSUB sent an unsubscribe message are still received by the XSUB socket after the unsubscribe. Minimal code example below illustrates what I mean.

**Environment:**
Ubuntu 18.04.01

**libzmq version:**
I'm using zmq through its C++ binding:
libzmq5:amd64                   4.2.5-1
libzmqpp4:amd64                 4.1.2-0ubuntu2

I'm opening an issue on zmq and not on zmqpp as after looking through the zmqpp binding implementation I saw that it just forwards the calls to the C implementation.

**A minimal code to reproduce the issue:**
```
void xsubSocketTest()
  {
    std::cout << "XSUB socket test" << std::endl;

    zmqpp::context_t context;

    zmqpp::socket_t pub(context, zmqpp::socket_type::pub);
    zmqpp::socket_t xsub(context, zmqpp::socket_type::xsub);

    pub.bind("inproc://xpub");
    xsub.connect("inproc://xpub");

    {
      char subs[] = {1, '1'};
      zmqpp::message_t subsMsg;
      subsMsg.add_raw(subs, 2);
      xsub.send(subsMsg);
    }

    pub.send("1");
    pub.send("12");
    pub.send("13");
    std::string rcv;
    xsub.receive(rcv);
    std::cout << "XSUB Received first: " << rcv << std::endl;
    sleep(1);
    {
        char unsubs[] = {0, '1'};
        zmqpp::message_t unsubsMsg;
        unsubsMsg.add_raw(unsubs, 2);
        xsub.send(unsubsMsg);
        std::cout << "XSUB Unsubscribed" << std::endl;
    }
    sleep(1);

    xsub.receive(rcv);
    std::cout << "XSUB Received second: " << rcv << std::endl;

    xsub.receive(rcv);
    std::cout << "XSUB Received third: " << rcv << std::endl;

    pub.send("14");
    xsub.receive(rcv);
    std::cout << "XSUB Received fourth: " << rcv << std::endl;
  }

```

The actual output is:

> XSUB socket test
> XSUB Received first: 1
> XSUB Unsubscribed
> XSUB Received second: 12
> XSUB Received third: 13
> 

"XSUB Received fourth: 14" is never printed as the code waits forever on the last receive.
I'd expect that the second and the third message would not be received as well.

Interestingly enough, this works well if a SUB socket is used instead of XSUB:

```
void subSocketTest()
  {
    std::cout << "SUB socket test" << std::endl;

    zmqpp::context_t context;

    zmqpp::socket_t pub(context, zmqpp::socket_type::pub);
    zmqpp::socket_t sub(context, zmqpp::socket_type::sub);

    pub.bind("inproc://pub");
    sub.connect("inproc://pub");

    {
      sub.subscribe("1");
    }

    pub.send("1");
    pub.send("12");
    pub.send("13");
    std::string rcv;
    sub.receive(rcv);
    std::cout << "SUB Received first: " << rcv << std::endl;
    sleep(1);
    {
        sub.unsubscribe("1");
        std::cout << "SUB Unsubscribed" << std::endl;
    }
    sleep(1);

    sub.receive(rcv);
    std::cout << "SUB Received second: " << rcv << std::endl;

    sub.receive(rcv);
    std::cout << "SUB Received third: " << rcv << std::endl;

    pub.send("13");
    sub.receive(rcv);
    std::cout << "SUB Received fourth: " << rcv << std::endl;
  }

```

This produces the following output:

> SUB socket test
> SUB Received first: 1
> SUB Unsubscribed
> 

No messages are received after the unsubscribe. 

I suspect that there is some subtle difference between calling the unsubscribe method of SUB socket (zmq_setsockopt unsubscribe) and sending an unsubscribe message through the XSUB.

**Comment by bluca** [comment]
XSUB sockets do not do any automated filtering, it's left to the user application. Use SUB if you want automated filtering.

**Comment by kikosha** [comment]
Well, then the documentation must updated accordingly, because in all places where XSUB is mentioned it states that XSUB is exactly as SUB except that it allows sending arbitrary messages to the PUB, example: 
http://zguide.zeromq.org/page:all#The-Dynamic-Discovery-Problem

> We need XPUB and XSUB sockets because ZeroMQ does subscription forwarding from subscribers to publishers. XSUB and XPUB are exactly like SUB and PUB except they expose subscriptions as special messages. The proxy has to forward these subscription messages from subscriber side to publisher side, by reading them from the XPUB socket and writing them to the XSUB socket. This is the main use case for XSUB and XPUB.

Also, in API section:
http://api.zeromq.org/4-2:zmq-socket#toc13

> ZMQ_XSUB
> 
> Same as ZMQ_SUB except that you subscribe by sending subscription messages to the socket. Subscription message is a byte 1 (for subscriptions) or byte 0 (for unsubscriptions) followed by the subscription body. Messages without a sub/unsub prefix may also be sent, but have no effect on subscription status.

My reason for chosing XSUB over SUB was that I needed the functionality of sending arbitrary messages to the publisher. Making me thing, can we have a flag that allows us to enjoy both features? Automated filtering AND sending the arbitrary messages?

**Comment by bluca** [comment]
The flag was there but removed intentionally. Feel free to send a pr to update the docs.

**Comment by kikosha** [comment]
Here:
http://zguide.zeromq.org/page:all#The-Dynamic-Discovery-Problem
XSUB and XPUB are _similar_ to SUB and PUB except they expose subscriptions as special messages _and the XSUB socket does not perform subscription-based message filtering. The latter can create race condition between un-subscription and incoming data, this edge case has to be handled by application logic._

In API section:
http://api.zeromq.org/4-2:zmq-socket#toc13
ZMQ_XSUB
Same as ZMQ_SUB except that you subscribe by sending subscription messages to the socket _and have to perform subscription-based filtering on application level._
