### ISSUE TITLE
terminating with uncaught exception of type zmq::error_t: Operation cannot be accomplished in current state

### ISSUE THREAD

**Issue by MyraBaba** [zeromq/libzmq#3282]
I have this error in Qt 👍 
terminating with uncaught exception of type zmq::error_t: Operation cannot be accomplished in current state

same code working on the Clion cmake:
zocket.send(request) line producing this error.

`zmq::context_t context (1);
    zmq::socket_t zocket (context, ZMQ_REP);
    zocket.connect ("tcp://localhost:5559");

    zmq::message_t request (5);
    memcpy (request.data (), "Hello", 5);

    std::cout << "Sending image ..." << std::endl;
    zocket.send(request);

    //  Get the reply.
    zmq::message_t reply;
    zocket.recv(&reply);
    std::cout << "Received World " <<std::endl;
`

**Comment by bluca** [comment]
The reply socket, as the name suggests, can only reply, not initiate. I suggest to read the guide: http://zguide.zeromq.org/page:all
