### ISSUE TITLE
Subscribe to the same topic multiple times, send a subscription message to the publisher, and when I unsubscribe the topic one by one, only send the last unsubscribe message?

### ISSUE THREAD

**Issue by ForrestSu** [zeromq/libzmq#3300]
*Please use this template for reporting suspected bugs or requests for help.*

# Issue description
I used an XPUB socket to get the subscription notification, set **ZMQ_XPUB_VERBOSER** = 1, use the same socket to subscribe to the topic "**test**" multiple times, and I can receive the subscription notification. According to the ZMQ documentation [ZMQ_UNSUBSCRIBE](http://api.zeromq.org/4-2:zmq-setsockopt#toc57) 

> If the socket has several instances of the same filter attached the ZMQ_UNSUBSCRIBE option shall remove only one instance.

  So I call **setsockopt(socket, ZMQ_UNSUBSCRIBE, topic, topic_len)** multiple times, but the XPUB socket only received the last unsubscribe notify!!

# Environment
* libzmq version v4.2.5: 
* OS:  CentOS Linux release 7.5

# Minimal test code / Steps to reproduce the issue

# What's the actual result? (include assertion message & call stack if applicable)

# What's the expected result?
  Each time a subscription is made, a subscription message is sent to the publisher. Unsubscribe from the same topic, sent every time? (regardless whether the reference count for this topic is 0)

**Comment by bluca** [comment]
The _VERBOSER option allows to pass duplicated subscriptions from _different_ sub sockets, as the default behaviour is to only pass unique subscriptions across _all_ clients. The filtering is done from the client side, as it's a huge resource saver.

Yes, the documentation could be a bit clearer about that.

Why do you need to receive duplicated unsubs from the same client? What's the use case?

**Comment by ForrestSu** [comment]
Thank you. I maybe no need receive duplicated unsubs from the same client, I just used **_VERBOSER** option in the project, and wanted to verify the feature of _VERBOSER.  
[ZMQ_XPUB_VERBOSER](http://api.zeromq.org/4-2:zmq-setsockopt#toc59) it said:

>  If enabled, the socket passes all subscribe and unsubscribe messages to the caller.

I gree with you, the documentation need a bit clearer about _VERBOSER_.

### Here is my understanding, is this correct?
I found the _VERBOSER option allows to pass duplicated subscriptions from _different_ sub sockets (**or the same sub sockets**） ,   allows to pass duplicated _**un**subscriptions_ from _different_ sub sockets (**the same sub sockets just pass unique unsubscriptions**).  

### last i want to know
  why we need pass the same topic from the the _same_ sub client, based on what use cases, is there more relevant information?

Thank you very much. @bluca

**Comment by bluca** [comment]
> I found the _VERBOSER option allows to pass duplicated subscriptions from different sub sockets (or the same sub sockets) , also allows to pass duplicated unsubscriptions from different sub sockets (the same sub sockets only pass unique unsubscriptions).
This behavior is asymmetrical, which may be a bit confusing.

Yes that is correct, and it's due to historical reasons in the implementation which we cannot change anymore without breaking backward compatibility. Feel free to send a PR to amend the documentation.

> why we need pass the same topic from the the same sub client, based on what use cases, is there more relevant information?

I do not know why it was added, I suppose someone wanted to do manual refcounting in their application.

**Comment by ForrestSu** [comment]
I reviewed the history issue #448 about _VERBOSE, via git blame.
>Do not filter out duplicate subscriptions on the XSUB side of
XSUB/XPUB, so that ZMQ_XPUB_VERBOSE doesn't get blocked by forwarding
devices (as long as the devices all use ZMQ_XPUB_VERBOSE)

Consider for forwarding devices (eg: sockets proxy). 

the author `John Muehlhausen` only modified the subscription. 
_So, maybe unsubscription has the same problem?_

**Comment by bluca** [comment]
> So, maybe unsubscription has the same problem?

Perhaps, but nobody complained in 6 years about that. If you need such a change, it will need to be a new option as we cannot break backward compatibility. Feel free to send a PR to implement it.
