### ISSUE TITLE
libzmq project doesn't have reference to C4.1

### ISSUE THREAD

**Issue by crocket** [zeromq/libzmq#3302]
# Issue description

It is one of the core projects of zeromq. Yet, I do not see reference to C4.1 in this project.

Did developers decide to not observe or stick to C4.1?

C4.1 is the best contribution policy that I have ever seen so far. If there is a better alternative, let me know.

**Comment by bluca** [comment]
It's linked in the pr template, feel free to send a pr to mention it elsewhere too https://github.com/zeromq/libzmq/blob/master/.github/PULL_REQUEST_TEMPLATE.md
