### ISSUE TITLE
DealerSocket stacks on recv on DealerRouter disconnection

### ISSUE THREAD

**Issue by christose** [zeromq/libzmq#3305]
*Please use this template for reporting suspected bugs or requests for help.*

# Issue description
I have a DealerSocket in C++ (client) and a RouterSocket in C# (server).  On clients connection to the server, server sends messages periodically. When I stop RouterSocket then client hangs inside the 
DealerSocket.recv(&reply);
I also monitor client events so on ZMQ_EVENT_DISCONNECTED is where I am trying to force some how the client to reconnect/try but with no luck, application terminates with exceptions from libzmq.
Here's what I am trying:
I tried using a different thread and sending an exit signal but thread never exits for some reason.
I tried also:
DealerSocket.disconnect(...);
DealerSocket.close();
and call my function who handles in a while(keep_playing) the client but I get an exception from zmq.hpp
at int nbytes = zmq_msg_recv(&(msg_->msg), ptr, flags_);

# Environment

* libzmq version (commit hash if unreleased): latest from GitHub, compiled successfully with VS2017
* OS: Windows 10

# Minimal test code / Steps to reproduce the issue
`
zmq::context_t context(1);
zmq::socket_t DealerSocket(context, ZMQ_DEALER);

int main{
    Init:{
         InitializeZeroMQ();
    }

    goto Init;
}

void InitializeZeroMQ()
{
	mtx.lock();
	std::cout << "ZMQ_DEALER Started..." << std::endl;
	const char* connectionString = "tcp://127.0.0.1:xxxx";
	DealerSocket.connect(connectionString);

	if (DealerSocket.connected())
		DealerSocket.send(request); // Send Subscription Message

	mtx.unlock();
	while (keep_playing) // I was using DealerSocket.connected() but wasn't working on disconnection because again code hangs in multipart method inside DealerSocket.recv(&reply);
	{
		multy_part();
		counter++;
	}
}

void multy_part()
{
	try
	{
		mtx.lock();
		zmq::message_t reply;
		vector<string> replies;
		DealerSocket.recv(&reply);
		replies.push_back(get_zmq_str(reply));
		mtx.unlock();

		int64_t more;
		size_t more_size = sizeof(more);
		zmq_getsockopt(DealerSocket, ZMQ_RCVMORE, &more, &more_size);
		while (more)
		{
			DealerSocket.recv(&reply);
			replies.push_back(get_zmq_str(reply));
			zmq_getsockopt(DealerSocket, ZMQ_RCVMORE, &more, &more_size);
		}
		
		task_run(replies); // pass replies for processing to a Concurrency::task<void>
	}
	catch (exception ex)
	{
		mtx.unlock();
		....
	}
}

//This method runs async
void zeromq_monitoring_events()
{
	try
	{
		zmq_socket_monitor(DealerSocket, "inproc://monitor-client", ZMQ_EVENT_ALL);
		zmq::socket_t monitor_socket(context, ZMQ_PAIR);
		monitor_socket.connect("inproc://monitor-client");

		while (true)
		{
			string event = get_monitor_event(monitor_socket, NULL, NULL);
			std::cout << "EVENT => " << event << std::endl;
			if (event == "ZMQ_EVENT_DISCONNECTED")
			{
                                //mtx.lock();  // IF I usre lock here it hangs because is already locked in multipart method and there the code hangs inside DealerSocket.recv(&reply);

				exit_signal.set_value();
				std::cout << "Asking Thread to Stop" << std::endl;
				t.join();
				//DealerSocket.disconnect("tcp://127.0.0.1:xxxx");
				pause_thread(1000);
				keep_playing = false; // this suppose to stop the while loop but again main thread hangs in DealerSocket.recv(&reply);
				//DealerSocket.close();

				break;
			}
		}
	}
	catch (exception ex)
	{
		....
	}
}

`
Steps
1. 
You need a RouterSocket to send continuous messages to the client and then try terminate the RouterSocket and see how Dealer reacts...

# What's the expected result?
The expected result is the Dealer to try and reconnect to the RouterSocket on any disconnection and drop any pending messages from previous session.

**Comment by bluca** [comment]
> The expected result is the Dealer to try and reconnect to the RouterSocket on any disconnection and drop any pending messages from previous session.

Please read the zguide http://zguide.zeromq.org/ - you can either use timeouts or polling.

**Comment by christose** [comment]
I already did :), but perhaps I didn't understand well how poller works in c++, in c# is something I already use.

Here's what I came up with back then when I was trying with poller:
`       zmq::pollitem_t poller [1];

	//void *poller = zmq_poller_new();
	poller[0].socket = socket;
	poller[0].events = ZMQ_POLLIN;

	//zmq::active_poller_t active_poller;
	//zmq_poller_add(poller, socket, ZMQ_POLLIN, NULL);

	zmq_poll(poller, 1, -1);
	while (poller[0].revents & ZMQ_POLLIN)
	{
		zmq::message_t reply;
		DealerSocket.recv(&reply);
		std::string rpl = std::string(static_cast<char*>(reply.data()), reply.size());

		std::cout << rpl << std::endl;
	}`

Can you please tell why this is not working..
Also can you explain the difference of the commented out quote, I found them from various examples
