### ISSUE TITLE
69 out of 104 unit tests fail under Clang thread sanitizer

### ISSUE THREAD

**Issue by malikkirchner** [zeromq/libzmq#3309]
# Issue description

Using the Clang thread sanitizer most of the unit tests fail due to race conditions. They all pass (except 9 skipped) without sanitizer.

# Environment

* libzmq version (commit hash if unreleased): v4.2.5 (d062edd8c142384792955796329baf1e5a3377cd)
* OS: Arch Linux, x86_64 (kernel 4.19.2)

# Minimal test code / Steps to reproduce the issue

Compile and test with:
CFLAGS= -march=x86-64 -Wall -Wextra -pedantic -fpic -fpie -fstack-protector   -O0 -g3 -ggdb -fno-omit-frame-pointer -fno-optimize-sibling-calls -fPIC -fsanitize=thread -fno-sanitize-recover=null -fsanitize-trap=alignment -Wno-error
CC=/usr/bin/clang 

```
clang version 7.0.0 (tags/RELEASE_700/final)
Target: x86_64-pc-linux-gnu
Thread model: posix
InstalledDir: /usr/bin
Found candidate GCC installation: /usr/bin/../lib/gcc/x86_64-pc-linux-gnu/8.2.1
Found candidate GCC installation: /usr/bin/../lib64/gcc/x86_64-pc-linux-gnu/8.2.1
Found candidate GCC installation: /usr/lib/gcc/x86_64-pc-linux-gnu/8.2.1
Found candidate GCC installation: /usr/lib64/gcc/x86_64-pc-linux-gnu/8.2.1
Selected GCC installation: /usr/bin/../lib64/gcc/x86_64-pc-linux-gnu/8.2.1
Candidate multilib: .;@m64
Candidate multilib: 32;@m32
Selected multilib: .;@m64
```
[config.log](https://github.com/zeromq/libzmq/files/2593142/config.log)

# What's the actual result? (include assertion message & call stack if applicable)

Please check attached test log
[test-suite.zip](https://github.com/zeromq/libzmq/files/2593148/test-suite.zip)

# What's the expected result?

All unit tests pass with thread sanitizer enabled.

**Comment by malikkirchner** [comment]
Hi bluca, 

it is a tool, that discovers data races using compiler instrumentation and a support library, please find details at https://clang.llvm.org/docs/ThreadSanitizer.html. I use it in my CI to make "sure" my code is sane. There might be rare false positives and it cannot guarantee to discover all data races.

I took a quick look to the stack traces in the test-suite.log. The good news is, that most (maybe all) issues have their origin in only a few places: ypipe.hpp:165, ypipe.hpp:120, ypipe.hpp:81, ypipe.hpp:97, ypipe.hpp:86, socket_base.cpp:1388, socket_base.cpp:343, pipe.cpp:413, pipe.cpp:217, ...

From a first look to the code I cannot tell much more about the problem. From my experience I can tell that those data races most probably are real bugs. How can I help to fix them?

**Comment by bluca** [comment]
These are false positives. That's because that tool doesn't know (and it shouldn't of course) about the ad-hoc lock-free queue implementation. So you can just ignore them.

**Comment by malikkirchner** [comment]
Ok, I cannot really assess that at the moment.

**Comment by simonvpe** [comment]
> These are false positives. That's because that tool doesn't know (and it shouldn't of course) about the ad-hoc lock-free queue implementation. So you can just ignore them.

I can verify, libzmq needs to be built with thread sanitizer or you'll get false positives.
