### ISSUE TITLE
Custom memory alignment for message data

### ISSUE THREAD

**Issue by aaronovz1** [zeromq/libzmq#3316]
We have a memory alignment requirement for our image processing algorithms and need to send image data, that when received, is aligned to 32 byte address boundary. I don't currently see a way in ZMQ to define a custom alignment value.

Is there any fundamental reason why custom memory alignment and/or allocators couldn't be added to ZMQ?
It would be ideal to be able to define it for select sockets/transports as we wouldn't want every instance to have the same alignment. Perhaps it could be set through a socket option like `ZMQ_MSG_MEM_ALIGNMENT`.

I see in `zmq::msg_t::init_size` it just uses `malloc` but we could use something like `_aligned_malloc / aligned_malloc` with an extra alignment value being passed in.

**Comment by bluca** [comment]
Data is received in batched, reused buffers to implement zero copy, so that's not possible. There's an option to disable zero copy receives that you can set and that will give you word aligned buffers, at the price of halving performances or worse in most use cases.
