### ISSUE TITLE
zmq_unbind with ZMQ_SERVER is disconnection clients.

### ISSUE THREAD

**Issue by lp35** [zeromq/libzmq#3317]
# Issue description

zmq_unbind on a ZMQ_SERVER socket is closing the connection with already connected clients.

We should be able to unbind from an endpoint, and rebind to another endpoint withotu disconnecting already connect clients.

# Environment

* libzmq version 4.2.5: 
* OS: Windows 7

# Minimal test code / Steps to reproduce the issue

1. Create a couple of ZMQ_CLIENT/ZMQ_SERVER sockets.
2. zmq_bind the ZMQ_SERVER socket.
3. zmq_connect the ZMQ_CLIENT.
4. Send few messages from ZMQ_CLIENT to ZMQ_SERVER.
5. do zmq_unbind on ZMQ_SERVER.

```
#include "stdafx.h"


#include <string>
#include <unordered_set>
#include <chrono>
#include <thread>
#include <cstring>
#include <cstdio>
#define ZMQ_BUILD_DRAFT_API
#define ZMQ_STATIC

#include <zmq.h>

static void *ctx;
//static const char *endpoint = "inproc://tmp";
static const char *endpoint = "tcp://127.0.0.1:8899";

void client(std::string str) {
    auto socket = zmq_socket(ctx, ZMQ_CLIENT);
    zmq_connect(socket, endpoint);

    for (;;) {
        zmq_msg_t msg;
        zmq_msg_init_size(&msg, str.size() + 1);
        memcpy(zmq_msg_data(&msg), str.c_str(), str.size() + 1);
        zmq_msg_send(&msg, socket, 0);

        std::this_thread::sleep_for(std::chrono::milliseconds(1000));
    }
}

void server() {
    using namespace std::chrono;

    std::unordered_set<uint32_t> routings;
    auto heartbeat_timestamp = steady_clock::now();
    char heartbeat_str[] = "heartbeat from server";
    auto socket = zmq_socket(ctx, ZMQ_SERVER);
    zmq_bind(socket, endpoint);

    int k = 0;
    for (;;) {
        // recv msgs
        {
            zmq_msg_t msg;
            zmq_msg_init(&msg);
            zmq_msg_recv(&msg, socket, 0);
            routings.insert(zmq_msg_routing_id(&msg));
            printf("server recv msg: %s\n", (char*)zmq_msg_data(&msg));
            zmq_msg_close(&msg);
        }

        // refresh heartbeats

        if (k++ == 4)
        {
            char lastEndPoint[100];
            size_t length = sizeof(lastEndPoint);
            zmq_getsockopt(socket, ZMQ_LAST_ENDPOINT, lastEndPoint, &length);

            printf("Closing endpoint: %s\n", (char*)lastEndPoint);
            int res = zmq_unbind(socket, lastEndPoint);
            if (res != 0)
            {
                printf("Error %s\n", (char*)lastEndPoint);
            }
        }
    }
}

int main() {
    ctx = zmq_ctx_new();
    zmq_ctx_set(ctx, ZMQ_IO_THREADS, 4);
    std::thread t1(client, "hello from thread 1");
    std::thread t3(server);
    while (1) {
        using namespace std::chrono_literals;
        std::this_thread::sleep_for(1s);
    }
    return 0;
}


```

# What's the actual result? (include assertion message & call stack if applicable)

Server thread cannot receive messages anymore from the client.

# What's the expected result?

Server should be still able to receive packets from the client.

**Comment by bluca** [comment]
> We should be able to unbind from an endpoint, and rebind to another endpoint withotu disconnecting already connect clients.

The point of unbinding is to stop pipes connected to that endpoint.

**Comment by lp35** [comment]
What is the difference with zmq_close then?

**Comment by bluca** [comment]
that one can bind to multiple endpoints, and unbind only one

**Comment by lp35** [comment]
Ok, so how I can know which "pipes" are connected to a specific endpoint? The remote endpoint does not seems to be closed gracefully, and I would like to send a last packet before closing the ep.

**Comment by bluca** [comment]
That is implemented by the application. You can use router/dealer with the id to identify sockets.
