### ISSUE TITLE
Using zmq_msg_data/zmq_msg_size after zmq_msg_close results in SIGABRT

### ISSUE THREAD

**Issue by joelfrederico** [zeromq/libzmq#3329]
# Issue description

Calling zmq_msg_size/zmq_msg_data on a closed zmq_msg_t results in a ZMQ crash. It seems to me that we could remove the crash without changing the API. Both crashes are triggered off of a zmq_assert.

https://github.com/zeromq/libzmq/blob/b70d31c432f1dced4e65a83959787e7f4a3ba0d7/src/msg.cpp#L327 and https://github.com/zeromq/libzmq/blob/b70d31c432f1dced4e65a83959787e7f4a3ba0d7/src/msg.cpp#L347.)

Both of these are triggered off of a check() call. If we are going to check(), why not prevent the crash?

- [zmq_msg_size](http://api.zeromq.org/master:zmq-msg-size) says nothing about a closed message. We could return 0 and still be within the documented behavior (although this isn't quite ideal).
- [zmq_msg_data](http://api.zeromq.org/master:zmq-msg-data) says nothing about a closed message either. We could return NULL and still be within the documented behavior. We could also set errno to EFAULT, a la http://api.zeromq.org/4-2:zmq-msg-close.

We could also update the documentation with whatever behavior we decide to use. We could also deprecate zmq_msg_size and release a new zmq_msg_size:

```
int zmq_msg_size(zmq_msg_t *msg, size_t *size);
```

This version would return 0 on success and -1 on error, and set errno to EFAULT, a la http://api.zeromq.org/4-2:zmq-msg-close.

# Environment

* libzmq version (commit hash if unreleased): 4.3.0
* OS: macOS Sierra

# Minimal test code / Steps to reproduce the issue

```
extern "C" {
#include <zmq.h>
}

#include <iostream>

void print_error(int line) {
  std::cout << "Error (line " << line << "): " << zmq_strerror(zmq_errno()) << std::endl;
}

void check_error(bool condition, int line) {
  if (!condition) {
    print_error(line);
  }
}

int main() {
  // Create context
  void* ctx = zmq_ctx_new();
  check_error(ctx != NULL, __LINE__);

  // Init and close a message
  zmq_msg_t msg;
  int status = zmq_msg_init(&msg);
  check_error(status == 0, __LINE__);
  status = zmq_msg_close(&msg);
  check_error(status == 0, __LINE__);

  // A repeated message is idempotent with an error. This makes sense!
  status = zmq_msg_close(&msg);
  check_error(status == 0, __LINE__);  // Prints "Error (line 31): Bad address"

  /* ================================================== */
  /* Either line will trigger SIGABRT from a zmq_assert */
  /* ================================================== */
  zmq_msg_size(&msg);  // Why not return 0 or use error code model?
  zmq_msg_data(&msg);  // Why not return NULL?

  status = zmq_ctx_term(ctx);
  check_error(status == 0, __LINE__);
}

```

# What's the actual result? (include assertion message & call stack if applicable)

This produces the output:

```
Error (line 31): Bad address
Assertion failed: check () (_deps/libzmq-src/src/msg.cpp:347)
Abort trap: 6
```

# What's the expected result?

The behavior is undocumented, so there is no expected result. I propose we pick a sensible method for doing things and document it.

**Comment by joelfrederico** [comment]
Isn't it true that the uninitialized message could randomly have the check pass yet still be bad? Unlikely perhaps... 7 valid types out of 256 possibilities = 2.7% chance of passing while still being an invalid message. That seems high!

But yes, somebody somewhere needs to own messages, so it either would have to be libzmq or the user. And I think the user owns messages, because small messages can be allocated on the stack that way, yes? That's faster and avoids an allocation on the heap. Which makes small messages faster, unless you for some reason want to transfer ownership to libzmq, like if you're leaving the scope connected to that bit of stack. Then the memory has to be copied out of the stack if libzmq isn't finished with it.

So okay, I think this is actually impossible to fix.

If we detect that the message is invalid, do we really need to SIGABRT? If the check passes (2.7% of the time) we're in trouble no matter what, there will be undefined behavior. But if the check fails, we can signal to our users. The bad thing, I think, is that users won't understand that this is a probabilistic failure mode. So yes, it's better to bring things to a crashing halt than to probabilistically check. It puts the onus on the user to manage lifetimes, which they ought to be doing anyways. As best we can anyways- 2.7% of the time we won't catch the error and there's nothing that can help that AFAICT.

Does that sound right? Feel free to close.

**Comment by bluca** [comment]
@joelfrederico that all sounds reasonable. Would you like to update your PR to clarify that those functions can only be used on valid messages and will assert otherwise? So that there is no more ambiguity

**Comment by joelfrederico** [comment]
Oh, sure, I may do that later. I think it would be more accurate to say that those functions can only be used on valid messages and will exhibit undefined behavior otherwise? I don't want to promise an assert when one may not happen.
