### ISSUE TITLE
receive message reduce to 0 when using openpgm and pub/sub pattern in windows

### ISSUE THREAD

**Issue by lqxandxl** [zeromq/libzmq#3340]
*Please use this template for reporting suspected bugs or requests for help.*

# Issue description
when I use zeromq pub/sub pattern, send 100000 messages per second and each msg length 200 ,
sub receive message , and it stayed normal for a few minutes or for 1-3 hours, And then all of a sudden it goes down to zero, and sub can't get any more messages.

When I go down to 20,000 message per second ,  it's normal.

And the other weird thing is, on a good computer(ThinkStation P700), 100,000 messages per second works and not go down to 0.

another thing is ，  three subscribers in three computer  receive nothing nearly close  at the same time .  Is this a coincidence? 

pub and sub memory did not increase,I don't know what's going on,did I do something wrong?

# Environment

* libzmq version (commit hash if unreleased):  4.2.5 4.3.0
* Windows: 
openpgm 5.2.121
vs2010
https://miru.hk/openpgm/
OpenPGM-5.2.121~miru1.5-x86.exe

# Minimal test code / Steps to reproduce the issue

pub 

```
context = zmq_ctx_new();
publisher  = zmq_socket(context,ZMQ_PUB);

const int rate = 200000;
int rc = zmq_setsockopt(publisher,ZMQ_RATE,&rate,sizeof(rate));

const int hwm = 600000;
rc = zmq_setsockopt(publisher,ZMQ_SNDHWM,&hwm,sizeof(hwm));

const int sndbuf = 5000;
rc = zmq_setsockopt(publisher,ZMQ_SNDBUF,&sndbuf,sizeof(sndbuf));

const int one = 1;
rc = zmq_setsockopt(publisher,ZMQ_XPUB_NODROP,&one,sizeof(one));
rc = zmq_setsockopt(publisher,ZMQ_LINGER,&one,sizeof(one));

rc = zmq_bind(publisher,"epgm://70.3.1.14;239.0.0.13:5566");
Sleep(1000);

string tmp = "10001 12340123456789"
tmp = tmp+tmp+tmp+tmp+tmp;
tmp = tmp + tmp;

long long x = 999999990;
char update[500];
for(long long i=0;i<x;++i){
  sprintf(update,"%s",(char *) tmp.c_str());
  update[tmp.size()] = '\0';  
  int msg_size = s_send(publisher,update);
  send_count++;
  if(send_count%100 == 0)
     Sleep(1);
}

zmq_close(publisher);
zmq_ctx_destroy(context);

```

sub
```

void * context = zmq_ctx_new();
zmq_ctx_set(context,ZMQ_IO_THREADS,60);

void * subscriber = zmq_socket(context,ZMQ_SUB);

const int hwm = 10000000;
int rc = zmq_setsockopt(subscriber,ZMQ_RCVHWM,&hwm,sizeof(hwm));

const int rcvbuf = 2000000000;
rc = zmq_setsockopt(subscriber,ZMQ_RCVBUF,&rcvbuf,sizeof(rcvbuf));

rc = zmq_connect(subscriber,"epgm://70.3.1.25;239.0.0.13:5566");

char * filter = "10001 ";
rc = zmq_setsockopt(subscriber,ZMQ_SUBSCRIBE,filter,strlen(filter));

while(1){
       char * s1 = s_recv(subscriber);
       string res(s1);
       free(s1);
}

zmq_close(subscriber);
zmq_ctx_destroy(context);
```

# What's the actual result? (include assertion message & call stack if applicable)

recv msg 0 per second

# What's the expected result?

recv msg 100000 per second

**Comment by lqxandxl** [comment]
seem like the pipe is not active, when i use s_recv.

just like :  

https://github.com/zeromq/libzmq/pull/1649

or 

https://github.com/zeromq/libzmq/issues/2228

Is it because I use openpgm?

**Comment by bluca** [comment]
Have you profiled your application?

**Comment by lqxandxl** [comment]
@bluca how to profile？ I just write a test case to test the multicast performance using zmq.

**Comment by jamesdillonharvey** [comment]
Also try using just one context thread (I see you have 60). I use openpgm
for zeromq extensively (on linux admittedly ) but see issues with anything
more than one context thread.

Issues I have seen are:
1. Data flow stopping when application overloaded but then not recovering
2. Random crashes during reconnect events often weeks after the application
is started.

Both have proved impossible (for me at least) to reproduce in a debug
environment. By accident I found that they dissapear when there is only one
context thread.

**Comment by bluca** [comment]
> @bluca how to profile？ I just write a test case to test the multicast performance using zmq.

With perf or similar. Also why are there _60_ I/O threads? The application will pre-empt and context switch itself to death

**Comment by lqxandxl** [comment]
@bluca  @jamesdillonharvey  
I have change the thread num to 1, but still have problem.
I debug in zeromq`s src code, and I found

in function
```
int zmq::xsub_t::xrecv (msg_t *msg_)
```
when sub recv msgs, after a few minutes or a few hour ,
it will exec code
```
        //  Message doesn't match. Pop any remaining parts of the message
        //  from the pipe.
        while (msg_->flags () & msg_t::more) {
            rc = fq.recv (msg_);
            errno_assert (rc == 0);
        }
```
sub can`t deal with any message .
then , the session still push msg into pipe to socket base, but after a while openpgm stop to push msg to session.
so sub will never receive message again.
what should i do? to prevent this happen?

**Comment by bluca** [comment]
There are some apparently arbitrary values set as the buffer sizes / HWM options, have you tried without those?

**Comment by lqxandxl** [comment]
when i use zmq_setsockopt(subscriber,ZMQ_SUBSCRIBE,””,0)

After some time later,it always receive a lot of wrong msg,150000msgs/s,then receive nothing
