### ISSUE TITLE
Anaconda is install on windows-10 64 bit ,but after sucessfull installation also the Anaconda is not showing in start menu.But it is install in user/username/Anaconda3 . But nothing is showing in start menu.

### ISSUE THREAD

**Issue by AshitoshDesai** [zeromq/libzmq#3348]
*Please use this template for reporting suspected bugs or requests for help.*

# Issue description

# Environment

* libzmq version (commit hash if unreleased): 
* OS: 

# Minimal test code / Steps to reproduce the issue

1.  

# What's the actual result? (include assertion message & call stack if applicable)

# What's the expected result?

**Comment by bluca** [comment]
Anaconda's repositories are here: https://github.com/Anaconda-Platform
