### ISSUE TITLE
медленный я очень 

### ISSUE THREAD

**Issue by ARMINI** [zeromq/libzmq#3352]
*Please use this
 template for reporting suspected bugs or requests for help.*
# Issue description

# Environment

* libzmq version (commit hash if unreleased): 
* OS: 

# Minimal test code / Steps to reproduce the issue

1.  

# What's the actual result? (include assertion message & call stack if applicable)

# What's the expected result?

**Comment by c-rack** [comment]
Feel free to re-open with a valid problem description.
