### ISSUE TITLE
102 of 108 tests fail during build of zeromq-4.3.1

### ISSUE THREAD

**Issue by barjac** [zeromq/libzmq#3365]
I am trying to update our package and am hitting massive test failures. In the past a local build with tests would pass, and then fail on the official Mageia build servers, so we ignored and disabled the tests for the official build. With this version the tests fail locally also so something is obviously wrong.
Any help would be appreciated.

# Issue description
102 ctests fail

# Environment
Mageia Linux (Cauldron x86_64) building in chroot basesystem + deps

* libzmq version (commit hash if unreleased): 4.3.1

* OS: Mageia Cauldron

# Minimal test code / Steps to reproduce the issue
N/A

# What's the actual result? (include assertion message & call stack if applicable)
N/A

# What's the expected result?
All tests pass

Build log attached
[build.0.20190115215650.log](https://github.com/zeromq/libzmq/files/2761682/build.0.20190115215650.log)

List of installed packages in the chroot:
[rpm_qa.0.20190115215650.log](https://github.com/zeromq/libzmq/files/2761685/rpm_qa.0.20190115215650.log)

**Comment by bluca** [comment]
That doesn't say much, log in and run a test manually. I suspect it's something like there's no networking available - you a loopback interface at the very least to run the TCP tests.
Also you really should be using autotools rather than cmake...

**Comment by barjac** [comment]
Thanks - it's behaving much better after switching to autotools. 9 tests are skipped and the rest pass OK on my local system with internet connection. Our official BS specifically does not have network connection, which explains the fails there.

**Comment by barjac** [comment]
Now I have another problem. How do we build cppzmq package which requires cmake files from the zeromq build? I suspect this is why we switched to cmake in the first place.

**Comment by bluca** [comment]
It's just a header, you don't need to do any build. Copy it where you need it.
