### ISSUE TITLE
Make queue length and HWM state observable

### ISSUE THREAD

**Issue by sigiesec** [zeromq/libzmq#3370]
For a zmq_socket, the current queue length and HWM state should be observable by the application, such that this information can be integrated into application monitoring data. This might be implemented in either a push or pull way. A push way might extend the current socket monitor facility, a pull way might add new socket options that can be queried via zmq_getsockopt.

**Comment by bluca** [comment]
This was implemented by https://github.com/zeromq/libzmq/pull/3383
