### ISSUE TITLE
 zmq not sending on same binded port, when change-in uplink interface

### ISSUE THREAD

**Issue by acsdkquery** [zeromq/libzmq#3380]
1.I have the uplink over ethernet connection.
2.client is enalbed with moniter events(connected/disconnected)
3.client is receiving the connected monitor event and can able to send the data, server is receiving it 
4 I disconnected eth uplink and connected back after sometime , Server is  receiving any all pending data(all fine till here)
5. Now I disconnected eth uplink and connected over wifi, here server is Not received any data after that,

**Comment by sigiesec** [comment]
Thanks for bringing this up. Please use the issue template for the report. In particular, please add the following information:
* operating system & version
* libzmq version
* ideally, working code to reproduce this, but if this not feasible, at least the following information:
   * transport used (tcp?)
   * which side is disconnected from eth and connected via wifi, is this the client? does the client use zmq_connect?
* are wifi and eth on the same local network? does the peer maintain its IP address?
* which behaviour are you expecting? in particular, do you expect the data transfer to proceed immediately after establishing the wifi connection, or would you expect this only happens after some possibly long-running timeouts expired?

**Comment by acsdkquery** [comment]
Thanks for your support sigiesec!  
Please find the requested information 

OS ubuntu - 18.04
libzmq - 4.2.5
 
transport - tcp (dealer-client and router-server)
Client heartbeat is disabled, reconnect is defaulted. 
router handover is disabled. 

Yes, disconnected from eth and connected via wifi at client side. 

Yes, client uses zmq_connect 

Yes, wifi and eth on the same local network  and peer maintains with IP address

Expected: the data transfer to proceed immediately after establishing the wifi connection

Note:
If the intial connection is established using wifi, and if we disconnect wifi and connect back, the data transfer is working fine. The same is applicable for eth uplink. However if we switch the two different uplink it's not working.

**Comment by acsdkquery** [comment]
Hi @sigiesec, any further updates on this issue?

**Comment by sigiesec** [comment]
Sorry, unfortunately not. At first I thought it might be some obvious reason why it cannot work. But in principle, it sounds as if it might work. However, I don't know enough about the details of the Linux networking stack. Did you make this work with a raw TCP connection?

**Comment by sigiesec** [comment]
Sorry, unfortunately not. At first I thought it might be some obvious reason why it cannot work. But in principle, it sounds as if it might work. However, I don't know enough about the details of the Linux networking stack. Did you make this work with a raw TCP connection?

**Comment by bluca** [comment]
I don't think the kernel will switch over established TCP connections to other interfaces. The connection needs to be closed first - try using heartbeats

**Comment by jamesdillonharvey** [comment]
In the case where the same interface is bounced the TCP connection is
probably not timing out. So both ends are just waiting and retrying (as TCP
is reliable)

In the case of the interface changing we need a TCP timeout to force a
reconnect. If not how will the new network route be established.

Try setting very aggressive ZMQ_TCP_* settings to force the timeout sooner.

Also use a non blocking send (if possible in your model) to see if the send
is blocking or failing.

**Comment by bluca** [comment]
@acsdkquery have you managed to try with heartbeats?
