### ISSUE TITLE
IPC listener fails to clean up temporary socket files/directories

### ISSUE THREAD

**Issue by jvanstraten** [zeromq/libzmq#3387]
# Issue description

ZeroMQ's IPC protocol fails to clean up its own temporary files in at least the following circumstances:

 - A socket is bound with URI `ipc://*`.
 - `$TMP`/`$TMPDIR`/`$TEMPDIR` environment vars are not defined, so the directory/socket file is created in the current working directory.
 - `HAVE_MKDTEMP` is defined.

That makes [this](https://github.com/zeromq/libzmq/blob/14da2ab629f897779299e0dd04f52d3107b3ac9f/src/ipc_listener.cpp#L255) call to `rmdir()` fail with errno `ENOTEMPTY`. I think `libzmq` is at least passing this failure on to the user, but `cppzmq` ignores it as it is part of a `nothrow` function/destructor.

I have *not* checked if it also fails if the temp directory environment variables are defined, or `HAVE_MKDTEMP` is not defined. I have also not checked without using `cppzmq` to handle closing the socket and context, but I *have* checked that those functions are appropriately called by adding print statements to `zmq.hpp`.

I've only just started *using* ZeroMQ yesterday, so I don't yet feel comfortable making a PR to fix this myself in all circumstances, but for this particular case it seems to be as simple as adding an `unlink()` call with the appropriate path before the `rmdir()`.

# Environment

* `libzmq` 14da2ab6 (latest at time of writing, line number refers to this commit)
* `cppzmq` `bfdc7885` (latest at time of writing)
* OS: OpenSUSE Leap 15.0
* uname -a: `Linux tud278100 4.12.14-lp150.12.45-default #1 SMP Mon Jan 14 20:29:59 UTC 2019 (7a62739) x86_64 x86_64 x86_64 GNU/Linux`

and also on:

* `libzmq` 19b64709
* `cppzmq` `66394418`
* OS: OpenSUSE Leap 15.0
* uname -a: `Linux tud278100 4.12.14-lp150.12.45-default #1 SMP Mon Jan 14 20:29:59 UTC 2019 (7a62739) x86_64 x86_64 x86_64 GNU/Linux`

and also on:

* `libzmq` 19b64709
* `cppzmq` `66394418`
* OS: Ubuntu 18.10 (cosmic)
* uname -a: `Linux 4.18.0-13-generic #14-Ubuntu SMP Wed Dec 5 09:04:24 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux`

Aside from a custom prefix passed to CMake, I'm building the libraries without special arguments.

# Minimal test code (with cppzmq)

Judging by the library source code I'm expecting any ZeroMQ program using the IPC protocol to fail cleanup. This is enough:

```c++
#include <zmq.hpp>

int main() {
    zmq::context_t context;
    zmq::socket_t req(context, zmq::socket_type::req);
    req.bind("ipc://*");
}
```

# Actual result

A directory named (for example) `tmpDz09JF` with a single file named `socket` is created and survives graceful process termination.

# Expected result

The directory and socket file are cleaned up when the process terminates gracefully, through an implicit call to `zmq_close()` by `cppzmq` when `req` goes out of scope.

**Comment by bluca** [comment]
We can't delete the files as the close is asynchronous, so other sockets might be reusing the same directory https://github.com/zeromq/libzmq/issues/2764

**Comment by sigiesec** [comment]
I stumbled about the same issue as well when adding monitoring tests for ipc. I think #2764 is not exactly the same, as it is not about an ipc wildcard bind, which is the case here. In the current master, this leads to a ZMQ_EVENT_CLOSE_FAILED monitoring when closing a socket with an ipc wildcard bind. I fixed this in f177f2dfe961646512f2d7dab81637bd7614d925

**Comment by bluca** [comment]
ok, that makes sense

**Comment by jvanstraten** [comment]
I can confirm that @sigiesec's PR fixes the issue in my use case/environment. Awesome response time!
