### ISSUE TITLE
make install error on Debian

### ISSUE THREAD

**Issue by ccding** [zeromq/libzmq#3390]
*Please use this template for reporting suspected bugs or requests for help.*

# Issue description

make install error

# Environment

* libzmq version (commit hash if unreleased): 4.3.1
* OS: Linux 4.9.0-3-amd64 #1 SMP Debian 4.9.30-2+deb9u5 (2017-09-19) x86_64 GNU/Linux

# Minimal test code / Steps to reproduce the issue

1.  ./autogen && ./configure --prefix=$PWD && make -j && make install

# What's the actual result? (include assertion message & call stack if applicable)

```
 /bin/mkdir -p '/home/cong/calvin/ext/zeromq/bin'
  /bin/bash ./libtool   --mode=install /usr/bin/install -c tools/curve_keygen '/home/cong/calvin/ext/zeromq/bin'
libtool: install: /usr/bin/install -c tools/.libs/curve_keygen /home/cong/calvin/ext/zeromq/bin/curve_keygen
 /bin/mkdir -p '/home/cong/calvin/ext/zeromq/include'
 /usr/bin/install -c -m 644 include/zmq.h include/zmq_utils.h '/home/cong/calvin/ext/zeromq/include'
/usr/bin/install: 'include/zmq.h' and '/home/cong/calvin/ext/zeromq/include/zmq.h' are the same file
/usr/bin/install: 'include/zmq_utils.h' and '/home/cong/calvin/ext/zeromq/include/zmq_utils.h' are the same file
Makefile:6086: recipe for target 'install-includeHEADERS' failed
make[2]: *** [install-includeHEADERS] Error 1
make[2]: Leaving directory '/home/cong/calvin/ext/zeromq'
Makefile:7355: recipe for target 'install-am' failed
make[1]: *** [install-am] Error 2
make[1]: Leaving directory '/home/cong/calvin/ext/zeromq'
Makefile:6114: recipe for target 'install-recursive' failed
make: *** [install-recursive] Error 1
```

# What's the expected result?

**Comment by sigiesec** [comment]
You cannot use the source directory as the install prefix. Just specify a different directory, e.g. one parallel to the source directory or one within the source directory.

**Comment by ccding** [comment]
Problem solved. Thanks.
