### ISSUE TITLE
TCP reset causing dropped messages with PUSH/PULL

### ISSUE THREAD

**Issue by d4l3k** [zeromq/libzmq#3392]
# Issue description

The docs say that the TCP transport is reliable, however, I'm seeing dropped messages when using iptables to forcibly reset the TCP connection. Just dropping the packets works as expected not when the connection fully drops. http://api.zeromq.org/4-2:zmq-tcp

We found this issue in a production environment when a bad kernel configuration started sending TCP reset packets.

Is this expected behavior and is there anyway to make the message sending completely reliable?

# Environment

* libzmq version (commit hash if unreleased): zeromq 4.3.1
* OS: Linux

# Minimal test code / Steps to reproduce the issue

Create a PUSH/PULL pair with one thread sending messages and one receiving them and then forcibly interrupt the connection with tcp resets.

Run:
```
iptables -I OUTPUT -p TCP --dport 5333 -j REJECT --reject-with tcp-reset 

... wait a second

iptables -F
iptables -X
```

Code and example output:

https://gist.github.com/d4l3k/d3e6d40495ff8bcc6e58515892816352

(while this code is in Go, the original discovery code was in C++)

# What's the actual result? (include assertion message & call stack if applicable)

Messages are dropped after connection comes back.

# What's the expected result?

No messages are dropped.

**Comment by bluca** [comment]
Reliability depends on TCP working. Artificially breaking TCP will break it in some cases.

**Comment by d4l3k** [comment]
@bluca Can you confirm that if a connection gets a TCP reset ZMQ is no longer reliable? 

We encountered this in a production system without any artificial breakage. This is just the best attempt to make a simple reproduction.

**Comment by bluca** [comment]
@d4l3k I was a bit in a hurry earlier - to be more specific: if the TCP connection dies for any reason _after_ a message was sent by the application thread _and_ it was processed by the I/O thread _and_ given to the kernel, _and_ the kernel cannot recover the connection and the buffer, then that message will be lost. There are no "overlay" ACK/NACK/sequence numbers in libzmq on top of TCP - it's beyond its scope, and a bit redundant.

A protocol written using libzmq can employ seq numbers. This is typically done for PUB/SUB, which is not reliable by default. One could adapt the same monotonic seq number + asynchronous back channel for replays for other patterns, if TCP really starts breaking all the time.
In general it should be the job of firewalls to avoid hostile RSTs being spammed to unsuspecting applications.

**Comment by d4l3k** [comment]
@bluca Is there a way to make a PUSH/PULL socket not clear it's queue on TCP connection drop?

Using wireshark, I'm seeing message 1375057 go through, and then the TCP connection gets reset, and then when the connection comes back it starts up with message 1687000. All those queued messages aren't ever being sent by ZMQ and just dropped.

I guess that's expected with the RFC saying "SHALL create this queue when a peer connects to it. If this peer disconnects, the PULL socket SHALL destroy its queue and SHALL discard any messages it contains."

Is there a way around that, or a better way to be using ZMQ to never lose any messages even on disconnect/reconnect?

**Comment by d4l3k** [comment]
@bluca I really appreciate the help. 

We're just trying to be resilient to failures as possible. We're in a private DC without a direct connection to the internet and still experienced RST packets from the network.

Is there a way to tell if it's the kernel's queue or ZMQ's queue that's getting flushed? Does ZMQ's internal queue block until the message is sent on the wire by the kernel?

**Comment by bluca** [comment]
> Is there a way to tell if it's the kernel's queue or ZMQ's queue that's getting flushed? Does ZMQ's internal queue block until the message is sent on the wire by the kernel?

There's no observability of queues at the moment but funnily enough it's something I'm working on right now - there's a WIP PR open. With that one will be able to probe the status of the queues of a socket.

The backpressure comes from the TCP buffer. Roughly speaking, when the TCP socket write blocks, then the ZMQ internal queue will start filling up. There's no actual visibility of what the kernel does once a write on the file descriptor of the socket has succeeded - it's entirely up to the kernel, and we can't do much after that point.

As mentioned before, if you want extra reliability, it's up to the application protocol - monotonic seq num + async reply channel is the most common pattern, used normally with PUB/SUB.

**Comment by bluca** [comment]
Sure (and that happens already), but I meant to stop it _before_ the connection it's killed

**Comment by d4l3k** [comment]
@bluca Ah yeah, you're right, can't prevent that. It would be nice if ZMQ could handle connection failures across multiple connections though.

**Comment by somdoron** [comment]
@d4l3k use dafka!

http://github.com/zeromq/dafka

It is reliable... and almost ready for production use

**Comment by zuzy** [comment]
Same issue. 
I tried `close & rebind` and `unbind & rebind` but all got failure.
And I set HWM as 1, the queue pusher works well.
