### ISSUE TITLE
PUB-SUB can't recieve anything

### ISSUE THREAD

**Issue by ADDubovik** [zeromq/libzmq#3394]
*Please use this template for reporting suspected bugs or requests for help.*

# Issue description
Subscriber in PUB-SUB pattern can't get any data over TCP transport.
This problem was added in fresh commits somewhere - between 14da2ab629f897779299e0dd04f52d3107b3ac9f and b8b1b8def349f448f0861c6deeecae914213914c.
Others patterns are not tested.

# Environment

* libzmq version (commit hash if unreleased): 
* OS: 
Windows 7 64-bit
# Minimal test code / Steps to reproduce the issue

```
#include "zmq.hpp"

int main()
{
	zmq::context_t context;
	zmq::socket_t pub(context, ZMQ_PUB);
	zmq::socket_t sub(context, ZMQ_SUB);
	pub.bind("tcp://*:24089");
	sub.connect("tcp://localhost:24089");
	sub.setsockopt(ZMQ_SUBSCRIBE, "", 0);

	std::set<std::string> results;
	for ( int i = 0; i < 200; ++i )
	{
		std::ostringstream buf;
		buf << "Some text " << i;
		pub.send(buf.str().c_str(), buf.str().length() + 1);
		std::this_thread::sleep_for(std::chrono::milliseconds(1));
	}

	zmq::message_t msg;
	while ( sub.recv(&msg, ZMQ_DONTWAIT) )
	{
		std::string str(static_cast<const char*>(msg.data()), static_cast<const char*>(msg.data()) + msg.size());
		results.emplace(str);
		std::cout << str << "\n";
		std::this_thread::sleep_for(std::chrono::milliseconds(1));
	}
 } 
```

# What's the actual result? (include assertion message & call stack if applicable)

```
error: Value of: results.empty()
  Actual: true
Expected: false

error: Expected: (results.size()) > (static_cast<size_t>(190)), actual: 0 vs 190
```
... and nothing in console.

# What's the expected result?

```
	EXPECT_FALSE(results.empty());
	EXPECT_GT(results.size(), static_cast<size_t>(190));
```
... and a lot of lines in console (about 198 pcs).

**Comment by somdoron** [comment]
try to call setsockopt before connect.
Also after both, make a small sleep, something like 100ms.
The problem is that 200 messages is very fast, the connection and subscription will arrive to the publisher in that time, so you must give the subscriber some time to connect to the publisher and sent the subscription.

**Comment by bluca** [comment]
Another solution, which is more reliable, is to use ZMQ_XPUB instead of ZMQ_PUB, and to wait on the subscription message before starting to send.

**Comment by ADDubovik** [comment]
I use setsockopt.
200 ms is not very fast. 2 ms is enough to reconnect, I know. I am not a newbie with ZMQ. Usually there's 198 messages out of 200 in the code example.

This is newly-added bug. Everything was fine until commit b8b1b8def349f448f0861c6deeecae914213914c.

**Comment by sigiesec** [comment]
@ADDubovik Thanks for reporting this. I can reproduce this on my machine. 

Using git bisect, I tracked it down to:
```
68d520ef682a2f7335c9d5e5ea1f235eed928b1b is the first bad commit
commit 68d520ef682a2f7335c9d5e5ea1f235eed928b1b
Author: Simon Giesecke <simon.giesecke@btc-ag.com>
Date:   Mon Feb 4 07:31:08 2019 -0500

    Problem: tcp_connecter_t and tcp_listener_t duplicate code around opening and configuring a TCP socket

    Solution: extract common parts into tcp_open_socket function

:040000 040000 a71b76a01c3885572a7ea70e07ed3bbb00f0e983 75bda9a75fefb8818c3babc1776227318d373381 M      src
```
Will give 68d520ef682a2f7335c9d5e5ea1f235eed928b1b a closer look.

**Comment by sigiesec** [comment]
Actually, this is not related to any performance changes, but, as the issue title correctly states, no connection is made at all. Apparently, there were no test cases for TCP name resolution at all. I now added a test case for that, so this won't break without notice again in the future.

**Comment by ADDubovik** [comment]
> no connection is made at all

Yes, really.

**Comment by bluca** [comment]
Great, thanks for the report and the fixes
