### ISSUE TITLE
No test case for ZMQ_BINDTODEVICE

### ISSUE THREAD

**Issue by sigiesec** [zeromq/libzmq#3397]
There is no test case setting the ZMQ_BINDTODEVICE socket option.

**Comment by bluca** [comment]
This is going to be tricky, as it requires root or CAP_NET_ADMIN, so it will most likely run nowhere

**Comment by sigiesec** [comment]
The travis nodes are sudo-enabled, isn't that sufficient?

**Comment by bluca** [comment]
yes, but it will need script changing to run the test as root
