### ISSUE TITLE
zmq_proxy cause 100% cpu usage

### ISSUE THREAD

**Issue by jiephe** [zeromq/libzmq#3407]
*Please use this template for reporting suspected bugs or requests for help.*

# Issue description

code is：
```
	void CProxy::Run()
	{
		void *context = zmq_ctx_new();

		auto router = fmt::format("tcp://*:{}", routerPort_);
		auto dealer = fmt::format("tcp://*:{}", dealerPort_);

		frontend_ = zmq_socket(context, ZMQ_ROUTER);
		zmq_bind(frontend_, router.c_str());

		backend_ = zmq_socket(context, ZMQ_DEALER);
		zmq_bind(backend_, dealer.c_str());

		zmq_proxy(frontend_, backend_, nullptr);
		zmq_ctx_destroy(context);	
	}
```

when run， sometimes cpu is 100% usage and never come down

# Environment

* libzmq version (commit hash if unreleased): 4.2.3
* OS: centos 7

# Minimal test code / Steps to reproduce the issue

1.  

# What's the actual result? (include assertion message & call stack if applicable)

high cpu usage

# What's the expected result?
normal cpu usage

**Comment by bluca** [comment]
Can you provide code to fully reproduce the problem?

**Comment by jiephe** [comment]
oh, sorry,  it's my fault. my structure is A Server --> proxy server <---B server,  and A server send msg to proxy server, proxy server send msg to B server. and the reason cpu 100% usage is B server do not connect proxy server, so the msg receive proxy server, but can not reach B server.
