### ISSUE TITLE
Program NAME is changed by ctx code

### ISSUE THREAD

**Issue by bys** [zeromq/libzmq#3424]
*Please use this template for reporting suspected bugs or requests for help.*

# Issue description
Program NAME is changed by ctx code

ctx.cpp :433

#ifndef ZMQ_HAVE_ANDROID
    std::ostringstream s;
    if (!_thread_name_prefix.empty ())
        s << _thread_name_prefix << "/";
    s << "ZMQbg/" << nthreads_started;
    thread_.setThreadName (s.str ().c_str ());
#endif
    nthreads_started++;

is that all right?
may be configure file misstake?
# Environment

* libzmq version (commit hash if unreleased):release 4-3-1 
* OS: linux ubuntu 1804 server

# Minimal test code / Steps to reproduce the issue

# What's the actual result? (include assertion message & call stack if applicable)

# What's the expected result?

**Comment by bluca** [comment]
That's the name of the posix threads created by the library, not of the program - what is the actual issue?

**Comment by bys** [comment]
i mean ：
if i use linux and write program use libzmq
my program name was changed by that code.

of course use 'ps aux' may be can not find this error (it show command line)
but use top and no 'c' option, you will find program name was changed

AND

you can open /proc/xxxxx file and see Name(changed)

so how can i control the program use bash-shell ? 
if so , i can only use process id  actually right?

On the other hand
if i use libzmq write a lot of programs 
all process called : ZMQbg?

**Comment by bys** [comment]
> That's the name of the posix threads created by the library, not of the program - what is the actual issue?

i mean ：
if i use linux and write program use libzmq
my program name was changed by that code.

of course use 'ps aux' may be can not find this error (it show command line)
but use top and no 'c' option, you will find program name was changed

AND

you can open /proc/xxxxx file and see Name(changed)

so how can i control the program use bash-shell ?
if so , i can only use process id actually right?

On the other hand
if i use libzmq write a lot of programs
all process called : ZMQbg?

**Comment by UUSim** [comment]
It seems to me that ZMQ only changes (or actually sets) the name of its own threads. The name of the main thread, i.e. your program, remains untouched.

Perhaps you can list all threads associated with the PID of your process?

**Comment by dufferzafar** [comment]
Oh, there's already an option called `ZMQ_THREAD_NAME_PREFIX`, just need to figure out how to set / use it now.

**Comment by UUSim** [comment]
I think you can call:
```cpp
zmq_ctx_set(ctx, ZMQ_THREAD_NAME_PREFIX, 1234);
```

As is performed here: https://github.com/zeromq/libzmq/blob/master/tests/test_ctx_options.cpp#L144
(Also see: http://api.zeromq.org/master:zmq-ctx-set#toc9)

However, you can only set an integer value as a prefix, so I would suggest using the PID of your main application.

There is also the [`zmq_ctx_set_ext`](https://github.com/zeromq/libzmq/blob/master/tests/test_ctx_options.cpp#L155) function which accepts a string value as prefix, however this is only part of the DRAFT API.

**Comment by dufferzafar** [comment]
Ah, I didn't realise you can only set an integer. That won't be of much use, since the PID is already visible when listing via `ss -ntlp`.
