### ISSUE TITLE
Confusing zmq_poller_new error behavior description

### ISSUE THREAD

**Issue by Eelis** [zeromq/libzmq#3425]
The documentation for `zmq_poller_new` states: https://github.com/zeromq/libzmq/blob/cdc4b8c6c6e6925a95a1bfcb0e9ea38d41182927/doc/zmq_poller.txt#L175

But in the same file, under "ERRORS" we find:

>    On `zmq_poller_new`:
>    `*ENOMEM*`::
>    A new poller could not be allocated successfully.

"always returns a valid pointer to a poller" makes it sound like ENOMEM can't happen. :)

**Comment by bluca** [comment]
The first bit looks wrong - the poller object is allocated with "new" so it could fail with enomem. Could you please send a PR to fix it?

**Comment by Eelis** [comment]
Will do
