### ISSUE TITLE
Segfault in process_command with zmq_socket_monitor_pipes_stats

### ISSUE THREAD

**Issue by sigiesec** [zeromq/libzmq#3446]
# Issue description

I get a segfault at https://github.com/zeromq/libzmq/blob/bd6fa4bbb3ec775d6ff9df0e1bb3174254daffa4/src/object.cpp#L111 because the object has already been destroyed.

# Environment

* libzmq version (commit hash if unreleased): 6937447832a786c89f1d3af6be072be5519b3459
* OS: Linux

# Minimal test code / Steps to reproduce the issue

Call zmq_socket_monitor_pipes_stats near a socket that is being disconnected.

Unfortunately, I was not yet able to reproduce this in a small test case.

I have the impression that it is possible that a destroy command is processed by a pipe before a pipe_peer_stats command that is still in the queue.

# What's the actual result? (include assertion message & call stack if applicable)

Segfault

# What's the expected result?

No segfault

**Comment by sigiesec** [comment]
@bluca Do you think this could be a race within libzmq?

**Comment by bluca** [comment]
It's entirely possible - no idea how though. What's the full decoded trace?

**Comment by sigiesec** [comment]
I am not sure if this is very helpful:
```
1 zmq::object_t::process_command            object.cpp       111 0x7ffff31a2f38 
2 zmq::io_thread_t::in_event                io_thread.cpp    88  0x7ffff318a349 
3 zmq::select_t::trigger_events             select.cpp       134 0x7ffff31c390b 
4 zmq::select_t::select_family_entry        select.cpp       449 0x7ffff31c4747 
5 zmq::select_t::loop                       select.cpp       421 0x7ffff31c4549 
6 zmq::worker_poller_base_t::worker_routine poller_base.cpp  139 0x7ffff31b6dc4 
7 thread_routine                            thread.cpp       182 0x7ffff320c669 
8 start_thread                              pthread_create.c 463 0x7ffff4c20594 
9 clone                                     clone.S          95  0x7ffff4953e6f 
```

**Comment by bluca** [comment]
Yeah not very - any luck with reproducing?

**Comment by sigiesec** [comment]
I didn't have luck with reproducing it with a minimal example. The last occurrences of this all had to do with a test involving a mechanism mismatch (e.g. PLAIN client against a CURVE server), which won't communicate successfully, of course, but still should not cause a crash.
