### ISSUE TITLE
Recv data memory alignment

### ISSUE THREAD

**Issue by TweakySolution** [zeromq/libzmq#3448]
I have the need to directly spool receiving data from zeromq to disk. My desire is to avoid a memory copy and use direct I/O for the disks, which requires page aligned memory. The sender delivers a header and then the disk data. The sender is guaranteed to deliver at least a disk block size of data so underflow is not an issue and no VSM is expected.

Is it possible to align all LSMG data to a memory page?

* libzmq version: 4.1.4
* OS: CentOS 7

**Comment by bluca** [comment]
It is not - you can disable zero copy and get individually malloced buffers, which are aligned since that's what malloc does, but then you get the extra malloc and copy from the socket buffer which defeats the purpose

**Comment by bluca** [comment]
This can't actually be done - a user can choose zero copy receive or aligned receive buffers, but not both at the same time, so closing the issue
