### ISSUE TITLE
PUB lost tcp connection to sub.

### ISSUE THREAD

**Issue by qianyi3210** [zeromq/libzmq#3455]
*Please use this template for reporting suspected bugs or requests for help.*

# Issue description
I have a PUB and many SUB workers.
some SUB workers have a slow receive issue because of high CPU work after receiving pub messages.
After running for several days, tcp connections lost from PUB side  to above SUB clients last night

# Environment
* libzmq version (commit hash if unreleased):  4.1.6
* OS: centos7
* pyzmq:17.0.0

# Minimal test code / Steps to reproduce the issue
connections check
```
 [root@localhost apolo]#  netstat -an|grep "127.0.0.1:5000         ESTABLISHED"|wc -l
230
[root@localhost apolo]#  netstat -an|grep "0 127.0.0.1:5000"|wc -l
141
```
PUB code
```
zmq_publish = context.socket(zmq.PUB)
zmq_publish.bind("tcp://127.0.0.1:5000")
```
SUB code
```
zmq_subscripe = context.socket(zmq.SUB)
zmq_subscripe.connect("tcp://127.0.0.1:5000")
```
COPY normal tcp status after restart program
```
tcp   1552932      0 127.0.0.1:37698         127.0.0.1:5000          ESTABLISHED
tcp        0      0 127.0.0.1:5000          127.0.0.1:37062         ESTABLISHED
tcp        0      0 127.0.0.1:5000          127.0.0.1:36876         ESTABLISHED
tcp        0      0 127.0.0.1:5000          127.0.0.1:36792         ESTABLISHED
tcp        0      0 127.0.0.1:5000          127.0.0.1:37582         ESTABLISHED
tcp        0      0 127.0.0.1:5000          127.0.0.1:37556         ESTABLISHED
tcp   1530280      0 127.0.0.1:37992         127.0.0.1:5000          ESTABLISHED
tcp        0      0 127.0.0.1:5000          127.0.0.1:37830         ESTABLISHED
tcp        0      0 127.0.0.1:5000          127.0.0.1:37422         ESTABLISHED
tcp   1553312      0 127.0.0.1:38016         127.0.0.1:5000          ESTABLISHED
tcp        0      0 127.0.0.1:36948         127.0.0.1:5000          ESTABLISHED
tcp   1553612      0 127.0.0.1:37770         127.0.0.1:5000          ESTABLISHED
```

# What's the actual result? (include assertion message & call stack if applicable)

# What's the expected result?

**Comment by bluca** [comment]
The kernel will kill an idle connection after some hours (depending on the platform), enable zmq_heartbeats to keep them alive

**Comment by qianyi3210** [comment]
thanks, do you know how to check log whether connections killed by kernel? or how to reproduce this issue again？

**Comment by bluca** [comment]
There's a sysctl flag to change it, I can't remember the details, should be easy to search for it

**Comment by qianyi3210** [comment]
[root@localhost ~]#  netstat -npo|grep 37878
tcp   1935960      0 127.0.0.1:37878         127.0.0.1:5000          ESTABLISHED 27514/python         off (0.00/0/0)
tcp        0 2034464 127.0.0.1:5000          127.0.0.1:37878         ESTABLISHED 26690/python         probe (86.51/0/0)

you can find that pub side always in "probe" status due to tcp buffer full, and after research, it called TCP ZERO WINDOW, it seems different from keep_alive param,  i need to reproduce this issue.

**Comment by bluca** [comment]
There are socket options for TCP keepalive too, use those
