### ISSUE TITLE
Can't install from centos 7 repository

### ISSUE THREAD

**Issue by pedropilla** [zeromq/libzmq#3469]
Following the lines to install from repository ends in error:

> [root@localhost ~]# rpm -q centos-release
> centos-release-7-6.1810.2.el7.centos.x86_64
> [root@localhost ~]# uname -a
> Linux localhost.localdomain 3.10.0-327.el7.x86_64 #1 SMP Thu Nov 19 22:10:57 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux
> 
> 
> [root@localhost yum.repos.d]# yum install zeromq-devel
> Loaded plugins: fastestmirror
> Loading mirror speeds from cached hostfile
>  * base: linorg.usp.br
>  * epel: espejito.fder.edu.uy
>  * extras: linorg.usp.br
>  * updates: linorg.usp.br
> Resolving Dependencies
> --> Running transaction check
> ---> Package zeromq-devel.x86_64 0:4.3.1-23.5 will be installed
> --> Processing Dependency: libzmq5 = 4.3.1-23.5 for package: zeromq-devel-4.3.1-23.5.x86_64
> --> Processing Dependency: pkgconfig(openpgm-5.2) >= 5.2 for package: zeromq-devel-4.3.1-23.5.x86_64
> --> Processing Dependency: pkgconfig(libsodium) for package: zeromq-devel-4.3.1-23.5.x86_64
> --> Processing Dependency: openpgm-devel for package: zeromq-devel-4.3.1-23.5.x86_64
> --> Processing Dependency: libsodium-devel for package: zeromq-devel-4.3.1-23.5.x86_64
> --> Processing Dependency: libzmq.so.5()(64bit) for package: zeromq-devel-4.3.1-23.5.x86_64
> --> Running transaction check
> ---> Package libsodium-devel.x86_64 0:1.0.17-1.el7 will be installed
> ---> Package libzmq5.x86_64 0:4.3.1-23.5 will be installed
> --> Processing Dependency: libsodium.so.18()(64bit) for package: libzmq5-4.3.1-23.5.x86_64
> ---> Package openpgm-devel.x86_64 0:5.2.122-32.2 will be installed
> --> Processing Dependency: libpgm-5_2-0 = 5.2.122 for package: openpgm-devel-5.2.122-32.2.x86_64
> --> Running transaction check
> ---> Package libpgm-5_2-0.x86_64 0:5.2.122-32.2 will be installed
> ---> Package libsodium18.x86_64 0:1.0.11-1.6 will be installed
> --> Finished Dependency Resolution
> 
> Dependencies Resolved
> 
> 
> Installing:
>  zeromq-devel                                    x86_64                                 4.3.1-23.5                                   network_messaging_zeromq_release-stable                                 436 k
> Installing for dependencies:
>  libpgm-5_2-0                                    x86_64                                 5.2.122-32.2                                 network_messaging_zeromq_release-stable                                 173 k
>  libsodium-devel                                 x86_64                                 1.0.17-1.el7                                 epel                                                                    1.1 M
>  libsodium18                                     x86_64                                 1.0.11-1.6                                   network_messaging_zeromq_release-stable                                 171 k
>  libzmq5                                         x86_64                                 4.3.1-23.5                                   network_messaging_zeromq_release-stable                                 275 k
>  openpgm-devel                                   x86_64                                 5.2.122-32.2                                 network_messaging_zeromq_release-stable                                  39 k
> 
> Transaction Summary
> 
> Install  1 Package (+5 Dependent packages)
> 
> Total size: 2.2 M
> Installed size: 7.4 M
> Is this ok [y/d/N]: y
> Downloading packages:
> Running transaction check
> Running transaction test
> 
> 
> Transaction check error:
>   file /usr/lib64/libpgm-5.2.so.0.0.122 from install of libpgm-5_2-0-5.2.122-32.2.x86_64 conflicts with file from package openpgm-5.2.122-2.el7.x86_64

**Comment by bluca** [comment]
openpgm didn't use to be available on centos 7 - I have disabled the build and purged it, try to refresh the repository and try again, it will now remove the local version and install the distro one.

**Comment by bluca** [comment]
@pedropilla did you have a chance to try again?

**Comment by pedropilla** [comment]
Yes, installed without any problem, thank you!

**Comment by bluca** [comment]
great, thanks for reporting

**Comment by pedropilla** [comment]
Solved, thanks!
