### ISSUE TITLE
Memory leak/memory usage problem in trivial PUB/SUB use case

### ISSUE THREAD

**Issue by UUSim** [zeromq/libzmq#3470]
# Issue description
Trivial PUB/SUB use case results in memory not being released.

Use case is as follows:
1. Initialize `PUB` and `SUB` sockets.
2. Publish `N` messages
3. Receive `N` messages, and delete them
4. RAM is not released

# Environment

* libzmq version (commit hash if unreleased): 4.3.2 (commit:6c613902)
* OS: Linux-4.9.0-8-amd64-x86_64-with-debian-9.8

# Minimal test code / Steps to reproduce the issue
```
#include <assert.h>
#include <iostream>
#include <vector>
#include <thread>
#include <chrono>
#include <zmq.h>

#define kNumTestMessages (1000)
#define kPubMessageSize (5 * 1024 * 1024)
#define kHighWaterMark (10000)

void sleep(int seconds) {
    std::this_thread::sleep_for (std::chrono::seconds(seconds));
}

using namespace std;
int main(int argc, char *argv[])
{
    cout << "------------ System info ------------" << endl;
    int major, minor, patch;
    zmq_version (&major, &minor, &patch);
    printf ("Current ØMQ version is %d.%d.%d\n", major, minor, patch);
    cout << "-------------------------------------\n" << endl;

    // Initialize sockets
    void* context = zmq_ctx_new();

    void* pubSocket = zmq_socket(context, ZMQ_PUB);
    void* subSocket = zmq_socket(context, ZMQ_SUB);
    int hwm = kHighWaterMark;
    assert(zmq_setsockopt(pubSocket, ZMQ_SNDHWM, &hwm, sizeof(hwm))==0);
    assert(zmq_setsockopt(subSocket, ZMQ_RCVHWM, &hwm, sizeof(hwm))==0);

    string subscribe_topic = "";
    assert(zmq_setsockopt(subSocket, ZMQ_SUBSCRIBE, subscribe_topic.data(), subscribe_topic.size())==0);

    char strBind[]      = "tcp://127.0.0.1:5555";
    char strConnect[]   = "tcp://localhost:5555";

    assert(zmq_bind(pubSocket, strBind)==0);
    cout << "Started PUB socket" << endl;
    sleep(1);
    assert(zmq_connect(subSocket, strConnect)==0);
    cout << "Started SUB socket" << endl;
    sleep(1);

    auto p_msg = new vector<char>;
    p_msg->resize(kPubMessageSize);
    sleep(1);
    cout << "Sending " << kNumTestMessages << " messages START" << endl;

    int numSend = 0;
    for (int i=0; i< kNumTestMessages; ++i) {
        if (zmq_send(pubSocket, p_msg->data(), p_msg->size(), 0) <= 0) {
            printf("Can not send message msg %d (%s)\n", i,
                   zmq_strerror(zmq_errno()));
        }
        ++numSend;
    }

    // clean up variable with dummy data
    delete p_msg;

    // Wait before receiving in SUB socket
    cout << "Sending " << numSend << " messages DONE, memory should be high\n" << endl;
    cout << "The program is now sleeping" << endl << endl;
    sleep(5);
    cout << "Receiving messages START" << endl;

    int numReceived = 0;

    // Create buffer for receiving data
    vector<char>* s_msg = new vector<char>();
    s_msg->resize(kPubMessageSize + 100);

    for (int i=0; i<kNumTestMessages; ++i) {
        int rc_msg = zmq_recv(subSocket, s_msg->data(), s_msg->size(), 0);
        if (rc_msg <= 0) {
            cout << "Can not receive msg " << i << " (" << zmq_strerror(zmq_errno()) << ")" << endl;
            return 1;
        }
        cout << "Recv: (rc_msg: " << rc_msg << ") " << numReceived << endl;
        ++numReceived;
    }

    // Release receive buffer
    s_msg->clear();
    delete s_msg;

    // At this point, all the messages are processed, but there is still some 5GB in use
    cout << "Received " << numReceived << " messages, memory should be low again, but is not" << endl;
    cout << "Sleeping program..." << endl;
    sleep(5);

    cout << "Cleaning up sockets and context ..." << endl;

    // Cleanup
    zmq_close(subSocket);
    zmq_close(pubSocket);
    zmq_ctx_destroy(context);
    zmq_ctx_term(context);

    cout << "Sockets cleaned u, now the memory is low again" << endl;
    // Wait before quitting, so you can still see the RAM decrease
    cout << "Stopping program..." << endl;
    sleep(5);

    return 0;
}
```

# What's the actual result? (include assertion message & call stack if applicable)
Several gigabytes of RAM are not released.

# What's the expected result?
RAM must be released once all messages have been received.

What you think of this issue? I am very interested to find out if there is a real issue here, or whether I'm, somehow, using the library incorrectly.

**Comment by UUSim** [comment]
Is there anyone wo can please try the code for reproducing this?

**Comment by ssbl** [comment]
Hey @UUSim, I ran your program with valgrind and didn't see any leaks. I think the allocator doesn't let go of the memory till the program exits to reduce fragmentation.

**Comment by bluca** [comment]
> Several gigabytes of RAM are not released.

Please define "released"

**Comment by UUSim** [comment]
Not released, as in: when I monitor the process (using htop), the memory usage does not decrease.
The process keeps using ~60% of RAM (`5GB` out of `8GB` total), until the sockets are destroyed.

**Comment by bluca** [comment]
That's not a memory leak, it's just how memory management works in Linux, and it has nothing to do specifically with libzmq, so I'll close this. You can find plenty of resources that talk about it online.

**Comment by UUSim** [comment]
How exactly are you concluding from the above that this is standard Linux MMU behavior?

Not to offend or anything, but that seems a bit rash to me. The above program demonstrates how the memory is only freed after the context is closed, even though the messages were already processed. To me this seems like there is something going wrong.

**Comment by bluca** [comment]
Because that's how glibc works. You can build your own library with unoptimised malloc/free and inject it with LD_PRELOAD and you'll see that there's no leak and everything is accounted for - that's what valgrind does

**Comment by UUSim** [comment]
Thank you for the quick response. I've updated the issue title to reflect the situation more clearly.
I've spend the better part of today to investigate my situation more, and I'm not sure this is a non-issue.

After the demonstration program has processed all messages using `zmq_recv`, the memory usage looks as follows:
![Screenshot_2019-04-11_15-39-51](https://user-images.githubusercontent.com/9439166/55962116-9953a880-5c70-11e9-8c7d-17f195570cc2.png)

The `RES` column still shows a large number.

If I now start  another copy of the program, which also tries to use a lot of RAM, the pc starts swapping heavily, and eventually the program is killed. <sub>Note that I modified the program to bind to a port specified on the command line, to support running multiple instances.</sub>

This gives me the idea that ZMQ did not release the memory. I know that ZMQ has its own allocator, which allocates blocks as needed, and reuses them when possible.

Am I correct to understand that these blocks, once allocated, are always kept for later use? In that case it seems that I should work around this by limiting the maximum number of messages (using `HWMs` etc).

<sub>Side note: Our program, which is a sort of PUB-SUB data processor, typically has a very long uptime (several weeks), so it cannot claim large amounts of memory forever.</sub>

**Comment by bluca** [comment]
> This gives me the idea that ZMQ did not release the memory.

Yes, it did. Again, if you want a different behaviour from glibc, you'll have to provide your own malloc implementation via LD_PRELOAD. There's nothing we can do about that.

**Comment by bluca** [comment]
@UUSim if you are memory-constrained and performance penalty is acceptable, you can set the ZMQ_ZERO_COPY_RCV context option which has lower memory utilization

**Comment by UUSim** [comment]
Many thanks for your explanation. I now see that you are right. So we will look into writing our own (de)allocator for use with the `LD_PRELOAD` trick.

Also, the `ZMQ_ZERO_COPY_RCV` looks rather interesting, but it seems like it is not yet implemented. I cannot find any reference to it in the repository, other than in the documentation. This is likely because it is in draft, but I cannot find how to actually test it.

**Comment by bluca** [comment]
There's a typo in some of the docs, the actual name is ZMQ_ZERO_COPY_RECV (with an E) - you can either install the prebuilt packages by following the instructions at https://software.opensuse.org/download.html?project=network%3Amessaging%3Azeromq%3Arelease-draft&package=libzmq3-dev or you can build it yourself with the draft option enabled
