### ISSUE TITLE
Detect group join on ZMQ_RADIO

### ISSUE THREAD

**Issue by jean-airoldie** [zeromq/libzmq#3474]
I would like to implement a last-value-cache for the radio-dish pattern. To do so, I would most likely need to be able to detect a dish joining a group of a given radio socket. As this pattern is not well documented since it is still in draft, I would like to know if this is currently supported.

As an aside, is this github repository the right place to ask API related questions?

**Comment by bluca** [comment]
That feature is not supported, feel free to send a PR or to use XPUB which provides it.

**Comment by jean-airoldie** [comment]
If I were to write a PR, I would probably add a flag that makes RADIO behave similarly to XPUB. It would append group join / leave messages to a `pending` deque that can be received by the user via `recv`.

Do you see any immediate red flags with such design?

**Comment by bluca** [comment]
@somdoron is the most qualified to comment on that I think

**Comment by somdoron** [comment]
Sounds good to me.
We have special flag on the msg_t structure for join/leave and for the group. So you can utilize that and avoid the prefix byte.

**Comment by jean-airoldie** [comment]
Perfect I was wondering about that.

**Comment by jean-airoldie** [comment]
After some more thoughts, I do not actually need this feature. You may close this if you want.

**Comment by jean-airoldie** [comment]
The RADIO socket is meant as a one way transport since it can use PGM. I think that if you need communication in both direction you better use a SERVER socket anyway. You could write application code on top of it to provide the same features. I think its an anti-pattern so I'm closing.
