### ISSUE TITLE
ZeroMQ does not build for QNX 6.6 with CMake

### ISSUE THREAD

**Issue by ipa** [zeromq/libzmq#3479]
# Issue description

I'm evaluating ZeroMQ for a QNX 6.6 application and therefore tried to compile it using CMake, make and qcc. 

This issue is related to  #3371 but the solution is probably slightly different due to the newer QNX version.

# Environment

* libzmq version 4.3.1: 
* OS: Windows 10 x64
* QNX Momentics IDE 6.6.0
* CMake 3.14.0

# Minimal test code / Steps to reproduce the issue

1.  cmake -G "Eclipse CDT4 - Unix Makefiles" -DCMAKE_BUILD_TYPE=debug,release -DBUILD_SHARED=OFF 
2. cmake --build .

# What's the actual result? (include assertion message & call stack if applicable)

CMake generation fails

> cmake: could not autodetect polling method

# What's the expected result?

Code compiles without error for QNX 6.6

**Comment by ipa** [comment]
after adding `-DPOLLER=poll` to CMake, the static library compiles

for the tests we also needed to add libm and libsocket to the link_libraries

```
if(CMAKE_SYSTEM_NAME MATCHES "QNX")
    target_link_libraries(${test} socket)
    target_link_libraries(${test} m)
  endif()
```

**Comment by bluca** [comment]
Can you use autotools rather than cmake?

**Comment by sigiesec** [comment]
Great if you made it work :) Can you send a PR with your changes?

Iwan Paolucci <notifications@github.com> schrieb am Mi., 17. Apr. 2019,
22:44:

**Comment by ipa** [comment]
Yes, I'm preparing the pull request.

> 
> Great if you made it work :) Can you send a PR with your changes? Iwan Paolucci <notifications@github.com> schrieb am Mi., 17. Apr. 2019, 22:44:
