### ISSUE TITLE
Problem: zmq_poller does not fail with ETERM when context shutdown

### ISSUE THREAD

**Issue by jean-airoldie** [zeromq/libzmq#3492]
# Issue description
`zmq_poller` does not return `ETERM` when a registed socket's context is shutdown if no flags is specified. Note that this is only an issue when no flag is specified.

# Environment

* libzmq: 501f9d8da4b2201a6603c8cd8a0ff7525ee76fc6
* OS: fedora 29

# Minimal test code / Steps to reproduce the issue

1. Create a `zmq_poller`.
2. Create and register a socket in the poller with no flags specified (0).
3. Call `zmq_ctx_shutdown` on the context of the registered socket.
4. Call `zmq_poller_wait` with no timeout (-1) on the poller.

# What's the actual result? (include assertion message & call stack if applicable)
The call to `zmq_poller_wait` blocks forever.

# What's the expected result?
Since the context of one of the registered socket was terminated, the call to `zmq_poller_wait` should fail with `ETERM`, as specified in the [docs](http://api.zeromq.org/master:zmq-poller#toc6).

**Comment by sigiesec** [comment]
If you have a poller that only has one or more sockets without any flags registered, it can never return succesfully. Calling zmq_poller_wait with an infinite timeout in this case should probably fail with EINVAL immediately, independently from the shutdown of the context.
