### ISSUE TITLE
ZeroMQConfig.cmake fails if shared libraries are not built

### ISSUE THREAD

**Issue by RochaStratovan** [zeromq/libzmq#3494]
# Issue description

I found that the ZeroMQConfig.cmake file will not work if the shared libraries are not created. It will fail with the message

```
CMake Error at c:/3rdParty/libzmq/INSTALL/CLEAN/CMake/ZeroMQConfig.cmake:46 (get_target_property):
  get_target_property() called with non-existent target "libzmq".
Call Stack (most recent call first):
  CMakeLists.txt:9 (find_package)


CMake Error at C:/3rdParty/libzmq/INSTALL/CLEAN/CMake/ZeroMQConfig.cmake:47 (get_target_property):
  get_target_property() called with non-existent target "libzmq".
Call Stack (most recent call first):
  CMakeLists.txt:9 (find_package)

```

This configuration was done using the following cmake command line:

`cmake -D WITH_PERF_TOOL=OFF -D ZMQ_BUILD_TESTS=OFF -D CMAKE_INSTALL_PREFIX=..\..\INSTALL\CLEAN  -D ENABLE_CPACK=OFF -D BUILD_SHARED=OFF ..\..\libzmq-4.3.1
`

And then attempting to compile CPPZMQ 4.3.0 using the command line:

`cmake -D ZeroMQ_DIR=C:/3rdParty/libzmq/INSTALL/CLEAN/CMake ..\cppzmq-4.3.0`

I confirmed that if I removed `-D BUILD_SHARED=OFF` from the ZMQ compile/install then the previous mentioned error would not occur.

# Environment

* libzmq version (commit hash if unreleased): 4.3.1
* OS: Windows 10

# Minimal test code / Steps to reproduce the issue

1.  See description

# What's the actual result? (include assertion message & call stack if applicable)

See description.

# What's the expected result?

Expected result is that the cmake completes without any error when using find_package() for ZeroMQ.

**Comment by sigiesec** [comment]
Thanks for pointing this out. I have opened #3497 to solve this, but I didn't test it. Could you check if the patch solves your issue?

**Comment by RochaStratovan** [comment]
Thank you Simon. I can confirm that problem no longer happens.

Now CPPZMQ fails further on because it appears to need both static and shared libraries.

Long story short. The fix works!

John Rocha
Software Engineer
Stratovan Corporation

T: 530.746.7970
rocha@stratovan.com<mailto:rocha@stratovan.com> | www.stratovan.com<http://www.stratovan.com>

This message and/or attachments may include information which is intended to be accessed only by authorized recipients.  Use, storage and transmission are governed by Stratovan Corporation. Unauthorized review, use, disclosure or distribution is prohibited.  If you are not an intended recipient, please contact the sender and destroy all copies of the original message.

**Comment by sigiesec** [comment]
Since cppzmq is a header-only library, there is no need to build it. The build files are only needed for the tests.
