### ISSUE TITLE
NORM can only send up to a 2038 byte message

### ISSUE THREAD

**Issue by jackpimbert** [zeromq/libzmq#3501]
# Issue description
I am attempting to use NORM via ZeroMQ (python bindings) to multicast large messages of up to several MB. However, I have been unable to send any messages that are over 2038 bytes. I will attach simple publisher and subscriber example scripts that can hopefully be used to reproduce the issue.

I have also tried to recompile the libzmq `norm_engine.cpp` in order to see the debug log, and have attached a log of successful receiving (messages of 2038 bytes) and unsuccessful receiving (2039 bytes).

It's possible I'm overlooking something very simple, so any help is much appreciated.

# Environment

* libzmq version (commit hash if unreleased): 548f31d4b452eb9bb69b65a8836deee5bef4cc8f
* norm version: 1.5.8 (nightly)
* OS: Ubuntu 16.04 (4.15.0-47-generic)

# Minimal test code / Steps to reproduce the issue

```python
# Publisher
import os
import time
import zmq

context = zmq.Context()
socket = context.socket(zmq.PUB)

# Set the max datarate to 1Gbps
socket.setsockopt(zmq.RATE, 1000000)
ret = socket.getsockopt(zmq.RATE)
print("Data rate set: {} mb".format(ret/1000))

socket.connect("norm://127.0.0.1;224.1.2.3:5556")
i = 1
while True:
    topic = b""
    random_data = os.urandom(int(2038))
    print("sending %s: %s" % (i, len(topic) + len(random_data)))
    socket.send_multipart([topic, random_data])
    i += 1
    time.sleep(1)
```

```python
# Subscriber
import zmq

context = zmq.Context()
socket = context.socket(zmq.SUB)
socket.setsockopt(zmq.SUBSCRIBE, b"")

# Set the max datarate to 1Gbps
socket.setsockopt(zmq.RATE, 1000000)
ret = socket.getsockopt(zmq.RATE)
print("Data rate set: {} mb".format(ret/1000))

socket.bind("norm://127.0.0.1;224.1.2.3:5556")
while True:
    topic, data = socket.recv_multipart()
    print("received ", len(data))
```

# What's the actual result? (include assertion message & call stack if applicable)

Cannot receive messages with a payload of more than 2038 bytes.

Log for 2038 bytes:
[norm2038.txt](https://github.com/zeromq/libzmq/files/3165168/norm2038.txt)

Log for 2039 bytes:
[norm2039.txt](https://github.com/zeromq/libzmq/files/3165169/norm2039.txt)

# What's the expected result?

Receive messages with a payload up significantly more than 2038 bytes.

**Comment by bluca** [comment]
I don't really know anything about norm, but the buffer size is set to 2048 and it seems too close to be a coincidence: https://github.com/zeromq/libzmq/blob/master/src/norm_engine.hpp#L65

**Comment by jackpimbert** [comment]
@bluca Ah... many thanks, that seems to have fixed the issue. I was looking everywhere but the header.

It would still be great to hear if this is the "right" way, or if anyone has any input on sending larger files efficiently with NORM. Otherwise we can close this issue?

**Comment by bluca** [comment]
I don't know much about norm, but that limit feels wrong, feel free to send a PR to fix it

**Comment by jackpimbert** [comment]
Ok, thanks. I'll close this issue and look into the buffer size setting some more. If I find a reasonable solution I'll create a PR.

Thanks again!
