### ISSUE TITLE
Problem: Missing doc on `GATHER` and `SCATHER`

### ISSUE THREAD

**Issue by jean-airoldie** [zeromq/libzmq#3503]
Where can I find information on `DISH`, `RADIO`, `GATHER` and `SCATHER` draft socket types?

From my understanding the `RADIO-DISH` pattern is like the `PUB-SUB` with thread-safety, better performance and without `SNDMORE`. My guess would be that `GATHER-SCATHER` acts like `XPUB-XSUB` with the same tradeoffs?

**Comment by bluca** [comment]
The zmq_socket manpage

**Comment by jean-airoldie** [comment]
I could not find anything related to the `GATHER` and `SCATHER` other than the fact that they were thread-safe in the master manpage. Unless [this isn't the manpage](https://github.com/zeromq/libzmq/blob/master/doc/zmq_socket.txt).

**Comment by bluca** [comment]
Yes, information is missing about those types from the docs

**Comment by jean-airoldie** [comment]
From what I understand of the [unit test](https://github.com/zeromq/libzmq/blob/master/tests/test_scatter_gather.cpp#L54) `SCATTER-GATHER` seem to be more of a thread safe `PUSH-PULL` pattern.

**Comment by bluca** [comment]
@somdoron do you know if scatter-gather is documented somewhere? Thanks!

**Comment by somdoron** [comment]
It seems they are not documented yet :( 

scatter/gather are like the push/pull.
There is no xpub/xsub for dish/radio yet.

**Comment by leohard12** [comment]
2 millionaire 2 crypt for portfolio 10 millionaires me necessary financing soon crisis creation криптовалюты, she free of charge from confiscation women in индонезии forbidden opened account now all credits such situation on us, but if would was currency which all had access and can call her his currency not knowledge border and freedom from confiscation half population country but this 3 billion man does not have access to bank account and on appearance from perhaps will more, but 2023 on their all will new phone with application hard coin or another can create portfolio криптовалют procedure not complex hard coin or another currency they taking all titles to be called already hard my crypt will predict events on external market and адоптироваться in world policy they say what money spoil people but not pay attention as people spoil money hard coin place this end on this big stability than any from digital currencies this in beta version but this works initial capital 100000 $ on creation portfolio 1000000 $ this will allow create me prototype later need 12 million on one crypt this we together find major investors traditional banks and bank services stay in situ and not develop digital currency this train leaves you запрыгиваете in this or остаётесь on station i i will find another investors corporation opening interested soon bankruptcy end can invest

**Comment by bluca** [comment]
They are documented now: https://github.com/zeromq/libzmq/blob/fb9fb00eda5ade0725d8fd558dd861db800f1b5c/doc/zmq_socket.txt#L353
