### ISSUE TITLE
Problem zmq-socket-monitor-versioned missing from online API docs

### ISSUE THREAD

**Issue by jean-airoldie** [zeromq/libzmq#3504]
[This doc](https://github.com/zeromq/libzmq/blob/master/doc/zmq_socket_monitor_versioned.txt) is missing from the [API online docs](http://api.zeromq.org/master:zmq-socket-monitor-versioned).

**Comment by bluca** [comment]
Yes unfortunately these docs are generated manually, help is welcome to automate it via travis
