### ISSUE TITLE
Problem: outgoing messages are still queued when auth fails

### ISSUE THREAD

**Issue by jean-airoldie** [zeromq/libzmq#3505]
This is related to #882 but specifically for thread-safe socket types.

# Issue description
When `ZAP` is enabled and the connection succeeds but the authentication fails, the socket will still queue outgoing messages. This means that the application code will never be able to tell that the authentication failed via the `send` call (until the hwm is reached). This is a huge footgun in my opinion.

Currently this issue can be mitigated by making `connect` calls blocking by creating a `PAIR` socket that would wait for a  handshake event (success or failure) via `zmq_socket_monitor`. However this adds overhead to every `connect` call.

But this mitigation cannot work on thread safe types since multiple thread since making multiple concurrent connect calls would not guarantee that their `PAIR` socket would receive the appropriate event for their endpoint (e.g. first connect call receives the event for the endpoint of the second call and vice versa).

# Mitigation Ideas
* ~~Make the an API similar to `zmq_socket_monitor` but with a `PUB` socket instead of a `PAIR`. The message sent would the same as the first frame of the current API `zmq_socket_monitor` but the message topic would be the endpoint string. This way multiple concurrent connect calls would be guaranteed to received the events associated with their endpoint. Note that this cannot work with a `RADIO` socket since the maximum group length is of 15 chars. This works but its not ideal.~~
* Add a socket option / API flag so that the socket stays in mute state until a `ZMQ_EVENT_HANDSHAKE_SUCCEEDED` event. This would cause the `send` call to fail with `EAGAIN` if the autentication failed (similar to if the connection failed). Probably too hard to implement.
* ~~Add a zmq function call that blocks and returns only when the authentication succeeded or failed. Maybe a methods that calls connect underneat then wait until the event if received. This seems pretty ideal.~~

Edit1: Mitigation ideas that cannot work were crossed-out.

**Comment by jean-airoldie** [comment]
I guess it would be possible implement the first idea purely in userland by proxying the events from the `PAIR` socket to a `RADIO` socket using the same structure that I described. But thats not very ideal.

**Comment by jean-airoldie** [comment]
Damn just realized that the `RADIO` group max length is 15 characters, which is 1 byte short of the 16 bytes need to represent an ipv6 address. That first solution can't work then.

**Comment by jean-airoldie** [comment]
I think the best approach is to create a blocking connect function call that creates a monitor socket via `zmq-socket-monitor` with the event of interest, calls `connect`, then blocks on the monitor socket `recv` call.

**Comment by jean-airoldie** [comment]
I think making the event monitor socket a `PUB` socket is the simplest solution.

**Comment by swilwerth** [comment]
Can you detect the socket "failed connection/auth fail" from client when the server reply timed out?
If you can, the queue can be cleared and the error raised in the client application before any further send.
I don't think that queuing the outgoing messages on a failed connection is a bad idea.
The transport doesn't know if the fail is permanent or a temporary glitch.

**Comment by jean-airoldie** [comment]
Its not a failed connection but a failed authentication. From my understanding once an `ZAP` authentication attempt fails it is not retried. Moreover is you are not using a request reply pattern, you would not be able to detect the authentication failure. Its not the end of the world but its a significant footgun imo.

**Comment by swilwerth** [comment]
There should be a method to check the authentication status, I have no previous experience with ZMQ encryption, but is a common problem of the encrypted transports. It connects successfully and fail to send due authentication errors.
Connect is done at sockets level, in plain wire, authentication is over this.
Maybe something that can be retrieved using getsockopt, or setted through setsockopt, maybe ZMQ_IMMEDIATE?
I'm guessing.

**Comment by jean-airoldie** [comment]
The problem with having this as a sockopt is that, since authentication is on a per connection basis, the last state of each connection would have to be stored in the socket. This means that some kind of mutex hashmap would need to be use since it must work on thread-safe socket. Moreover, if you have to wait for authentication to succeed before proceeding, you would have to call getsockopt in a loop.

The solution that I'm working on right now is to make connect and bind calls blocking by waiting until the authentication fails, succeeds or timeouts using DRAFT socket event monitoring methods.

In case I am not clear, I am not trying to modify the behaviour of socket connect calls, I just want to make it possible for libs on top of `libzmq` to circumvent this problem.

**Comment by swilwerth** [comment]
I think I'm understanding your design. 
Do you have only one instance of zmq that handles all traffic from threads to one server or many servers? If that's right are the sockets shared between threads?
The ZMQ API says there is no thread safety on sockets, but nothing prevent you to instantiate new contexts for every thread and its respective sockets.

**Comment by jean-airoldie** [comment]
I'll try ZMQ_IMMEDIATE just in case it applies to ZAP authentication as well.

No there are thread-safe socket types (Client, Server, Radio, Dish, Gather, Scatter, Dgram) but they are pretty new and most of them still in DRAFT API.

As for the context, it is pretty exotic to require more than one at a time (unless you want to isolate your inproc transport or something). So I have a global atomic ref counted context singleton that is used as a default constructor.

**Comment by jean-airoldie** [comment]
Unfortunately `ZMQ_IMMEDIATE` only wait until a connection is completed, so this leads to the same problem. However I'll take a look at how this option works underneat. Maybe, like you said, a similar socket option could be added for authenticated connections.

**Comment by swilwerth** [comment]
This reply is only speculation.
Maybe the sockets are thread safe in that use cases, but not when used with encrypted transports.
Encrypted transports need handshakes, these handshakes are done after the connection is established, if the handshake fails, and another thread just overwrites this failure placing a new send.
That socket might reset to the "in handshake" status making impossible to subsequent threads to know if the previous handshake failed, and when failed.
So creating a socket per thread even if is for the same server is not exotic, in this way you will be sure that the internal socket status is consistent with the thread and also, if you are not doing a lot of connect and close (that is not a good thing to do,  by the way) it will not cause traffic overhead at all.

**Comment by jean-airoldie** [comment]
You are right. Even if I make connect calls blocking until the authentication succeeds, there are no guarantees that another thread won't be writing to it in the meantime, so it doesn't solve my issue in the first place.

The only way this could work is that outgoing pipe for a given endpoint stays blocked until authentication succeeds.

Seems like a hard problem.

**Comment by jean-airoldie** [comment]
I think the general ideal would be to associate an atomic bool which each outgoing pipe. When [event_handshake_succeeded](https://github.com/zeromq/libzmq/blob/de4d69f59788fed86bcb0f610723c5acd486a7da/src/socket_base.cpp#L1789) is called it would flip that bool to true which would unlock the pipe. However like you said, this wouldn't work if two thread are trying to connect to the same endpoint at the same time because a failure could overwrite a success and vice versa.

**Comment by swilwerth** [comment]
The problem here with added encryption is that adds new states. 
There are not "connected, or disconnected", there also connect but not authenticated state.
How this state would be treated? Like a disconnected one?
I think it a clever solution might block at thread level, not at pipe level.
A thread can have its own queue also to communicate with the pipe thread, it can be a REQ/REP with status report at the reply, but I know, It adds more complexity to the design.
Reliability has its tradeoffs.

**Comment by jean-airoldie** [comment]
I don't see why you would want to queue messages to an connected but unauthenticated endpoint.

For instance, in my library I enable ZAP on every socket so that even if the NULL mechanism is used (default mechanism), there is an handshake. I also have a ZAP handler that is started in the background with each context that would do the authentication. In that case, the only states that would matter to me would be `Pending`, `Failed` and `Succeeded`, which could fit in an atomic byte for instance.

By the way, why would you want to use `REQ/REP` over `DEALER/DEALER`?

**Comment by swilwerth** [comment]
Forget that, REQ/REP thing.
Think about the scenario when a failed authentication happens only sometimes, as when happens with connection also. It's not a problem of latency, is about losing messages when network misbehaves.
The messages should be queued, because network is not a fully reliable transport, so when it comes online again, there is no message loss.
If you have full control of your network, there is no problem, just restart the servers and configure them with proper certificates, but this is a specific case.
Messages are queued also on disconnected plain transports, as when using REQ/REP in RRR pattern  with timeout, it will queue until the server accepts them.
Is up to you what will be done with these messages, it should be discarded because they are very old? Or them should be kept because contains important information? There is no one solution to fit all.
Keep them all is the default case, if you don't want this, simply flush the queue.

**Comment by jean-airoldie** [comment]
The specific issue I want to solve is more about detecting invalid authentication credentials than having a fully reliable transport. I understand that the network will spuriously fail sometimes but it would be interesting to have a general idea of what caused the failure. Currently when a authentication via ZAP fails it is not retried, as opposed to spurious disconnections that are automatically reconnected if possible. This means that if someone misconfigure its credentials, and is not using a request-reply pattern in which the `recv` call would reply, he is screwed.

**Comment by jean-airoldie** [comment]
This basically a duplicate of #2653 now that I think about it.

**Comment by somdoron** [comment]
Are you using multiple connects or only one?
I'm thinking of a few solutions:
- Using something like WELCOME_MSG (from XPUB), so the SERVER will automatically send a message to every new client, on the client side you can wait to the WELCOME MSG before enqueueing messages.
- Create an option like ZMQ_IMMEDIATE which only make the pipe available after the handshake succeeds, this can go hand in hand with.
- You can layer another inproc socket on top of the authenticated socket, and only connect them and proxy when the authentication succeeds, any call to send will fail until you do that.

**Comment by jean-airoldie** [comment]
Now that I think about it, every authentication call has to go through a ZAP handler (since I enable ZAP on all my sockets), which means i can intercept them. I could use a RADIO socket directly in the ZAP handler and generate my own events. Then I could block waiting for the appropriate handshake event to be received etc.

Thanks for the response, your inprox socket proxying gave me this idea.

**Comment by jean-airoldie** [comment]
@somdoron By the way, do you know if concurrent connect call on a thread-safe socket safe? What if 2 threads try to connect to the same endpoint from the same ZMQ_DISH socket?

**Comment by somdoron** [comment]
yes, it is safe. The same behavior with any multiple connects, which is socket dependent.

https://github.com/zeromq/libzmq/blob/master/src/socket_base.cpp#L806

So it might be ignored or connect multiple times to the same address.

**Comment by jean-airoldie** [comment]
Here is my detailled solution in case anyone needs it.

Make the connect / bind call retrieve the handshake result, as opposed to the send call. This would mean that it is possible to queue messages to a not yet authenticated connection, but that's kinda similar to queueing messages to a not yet connected connection. This means that connect and bind calls would become blocking. We would do this by generating events based on the ZAP requests sent to the `ZapHandler`.

Lets define some roles. The subject socket is the socket looking to connect or bind. The connection socket is a one time use `Client` socket used to retrieve the handshake result from the server. The connection socket must be in the same thread than the subject socket. The server a `Server` socket in the `ZapHandler` thgat is used to notify clients of handshake events.

Now the actual procedure:
* The high level connect or bind call is made on the subject socket.
* We create a `Client` socket to act as our connection socket and we connect it to the server.
* The connection socket generates a unique `ZMQ_IDENTITY`.
* The connection socket sends this identity to the server.
* The `AuthHandler` receives the identity and associates it with the routing_id of the connection.
* Now we actually call `zmq_connect` or `zmq_bind` on the subject socket.
* The connection socket blocks waiting for a response from the server.
* The `AuthHandler` intercepts the `ZapRequest`, check if the identity frame is associated with a routing_id and if so sends the result of the handshake to the client.
* The connection socket receives the reply and returns whether the handshake was successful or not to the function caller.

**Comment by jean-airoldie** [comment]
Nevermind my solution can't work because not every call goes through a ZAP handler that I control, i.e. when I'm connecting to a 3rd party socket.

**Comment by jean-airoldie** [comment]
I guess the only sane way for users to retrieve handshake failure information be have a monitor thread per socket that logs authentication errors.

**Comment by swilwerth** [comment]
Now, I'm understand why you don't want to keep the messages, as you said. 

> When a authentication via ZAP fails it is not retried, as opposed to spurious disconnections that are automatically reconnected if possible.

But I think that behaviour is not robust as it might be.
The authentication must be retried as the same thing of a spurious network error connect failure.
Think about the guys at the datacenter messing up the certificates on the server, and then they rollbacking the changes because of being advised of the problem.
All clients, must be restarted, since they will not retry the authentication at all and they are in a deadlock forever.

**Comment by jean-airoldie** [comment]
After digging a bit, I think I might be wrong #990. I'll test it just to be sure.

**Comment by jean-airoldie** [comment]
Nevermind, it tested it and if the authentication failed because of invalid credentials, it is not retried.

**Comment by jean-airoldie** [comment]
However if the authentication server has misconfigured certs it will surely be restarted eventually. I wonder if the reconnection after the server restarted would trigger another authentication attempt. I'll test it once again.

**Comment by jean-airoldie** [comment]
Nope it is not triggerred again.

**Comment by swilwerth** [comment]
Mmm, that's not sound good.
I imagine me trying to explain that behaviour to a company directory that had loss thousands of dollars because guys just messed up the certs and lost billing messages from the clients during a massive ticket sales, and don't like that idea. No, Sir.

**Comment by jean-airoldie** [comment]
I think this would be worth a separate issue. A reconnection event should probably trigger another authentication attempt.

**Comment by swilwerth** [comment]
Yes, and also, it might trigger a reauth event when the ciphered transport fails, as when the case of "hot swapping certs" without restarting the server instances, if that makes sense.

**Comment by jean-airoldie** [comment]
Yes, I can easily imagine an auth server that swaps cerds dynamically after a certain time. It also possible that the same server uses a dynamic whitelist client public key white list which could change over time. Or maybe a time-based ip blacklist akin to a firewall. In these cases, authentication retries seem like a must.

I read more issues on the matter and there is a lot of conflicting information. For instance #883 seems to contradict my results. I'll dig some more.

**Comment by somdoron** [comment]
@jean-airoldie what about implementing ZMQ_IMMEDIATE for the scenario, will that solve the case?

**Comment by jean-airoldie** [comment]
I think my original issue is resolved by #3508. In my case I only wanted to be able to detect authentication failures to notify users of potential credentials misconfiguration.

The issue that @swilwerth addressed is separate in my opinion. Its more related to the discrepancy between connection retries and authentication retries. I'm not entirely sure but it seems that after a client is notified of authentication failure he doesn't retry to authenticate. In situations where the state of the authentication server changes over time, this would be a problem. Perhaps I should open a different issue.

**Comment by somdoron** [comment]
Cool, I think a different issue is probably the correct way.

**Comment by somdoron** [comment]
@jean-airoldie I would like to chat with you regarding your zeromq usage, can you drop me an email at somdoron@gmail.com

**Comment by jean-airoldie** [comment]
@somdoron Alright.
