### ISSUE TITLE
Crash caused by wrong wsa_assert() on Windows

### ISSUE THREAD

**Issue by Tulon** [zeromq/libzmq#3507]
*Please use this template for reporting suspected bugs or requests for help.*

# Issue description
Today ZMQ crashed on me, by failing a wsa_assert() check.
The code in question is [here](https://github.com/zeromq/libzmq/blob/e285fe6ea71523654b52efddacb4b8118195cf67/src/signaler.cpp#L368).
ZMQ asserts that the error from calling `recv()` from that particular place may only be `WSAEWOULDBLOCK`. In my case it was `WSAECONNRESET`. Indeed, Microsoft's [documentation](https://docs.microsoft.com/en-us/windows/desktop/api/winsock/nf-winsock-recv) lists `WSAECONNRESET` as a valid error for `recv()`, unlike in Unix based systems, where `ECONNRESET` may be produced by `send()` but not `recv()`.

In general, I believe calling `abort()` as a result of receiving an unexpected error from `recv()` is a really bad idea. After all, new versions of your operating system may introduce new error conditions that may occur for reasons outside of your control.

# Environment

* libzmq version (commit hash if unreleased): 6a5051fac3bb09db7e7772dcbdd591ee7ded1400
* OS: Windows 8.1

# Minimal test code / Steps to reproduce the issue

1.  

# What's the actual result? (include assertion message & call stack if applicable)

    KernelBase.dll!00007fff99eb8e6c()	Unknown
    railroad_control.exe!zmq::zmq_abort(const char * errmsg_) Line 89	C++
    railroad_control.exe!zmq::signaler_t::recv_failable() Line 369	C++
    railroad_control.exe!zmq::mailbox_t::recv(zmq::command_t * cmd_, int timeout_) Line 88	C++
    railroad_control.exe!zmq::io_thread_t::in_event() Line 84	C++
    railroad_control.exe!zmq::select_t::trigger_events(const std::vector<zmq::select_t::fd_entry_t,std::allocator<zmq::select_t::fd_entry_t> > & fd_entries_, const zmq::select_t::fds_set_t & local_fds_set_, int event_count_) Line 133	C++
    railroad_control.exe!zmq::select_t::select_family_entry(zmq::select_t::family_entry_t & family_entry_, int max_fd_, bool use_timeout_, timeval & tv_) Line 441	C++
    railroad_control.exe!zmq::select_t::loop() Line 409	C++
    railroad_control.exe!zmq::worker_poller_base_t::worker_routine(void * arg_) Line 136	C++
    railroad_control.exe!thread_routine(void * arg_) Line 51	C++
    [External Code]	

# What's the expected result?

No crash.

**Comment by sigiesec** [comment]
If I am not mistaken, this is not a data socket, but the internal libzmq loopback socket.

Under Unix, socketpair is used to create a pair of AF_UNIX sockets. Unfortunately, this is not supported under Windows until recent builds of Windows 10. Therefore, as a substitute, a pair of TCP sockets via the loopback device is used on Windows.

Under normal circumstances, these connections cannot file, but it has been reported several times that on some Windows installations, something seems to occasionally kill these connections. 

Unfortunately, there is no easy way out of this situation. The connection cannot be re-established (at least not without significant changes to the libzmq internal architecture), and without it a clean shutdown of the context is impossible, so the only resolution is to abort.

**Comment by Tulon** [comment]
I see. In my case, the crash happened when my laptop was waking up from a sleep (or perhaps when it was in the process of suspending). It's worth noting that I've got Wireshark installed, which only recently got the ability to capture loopback traffic on Windows. Even though Wireshark wasn't running, perhaps its loopback filtering component was somehow responsible for those two local sockets being disconnected. Just a guess.

**Comment by sigiesec** [comment]
The wireshark driver might be related to that. Unfortunately, no one has ever been able to clearly identify the cause of this behaviour. On many Windows machines it seems to never happen.

Another solution might be to extend wepoll to support an eventfd like mechanism (piscisaureus/wepoll#8).

**Comment by hoditohod** [comment]
Hi, 
We're also seeing some instabilities in our zmq based applications on windows when wireshark is running. 

Is there a known incompatibility between wireshark and libzmq?

**Comment by bluca** [comment]
Not specifically - but as Simon said anything on the system that could interrupt and kill the internal loopback TCP connection will cause instability. There's unfortunately nothing we can do about that.

**Comment by yikenan** [comment]
Installing a new version of WinSDK can solve this problem.

My environment: win10 1903
Install WinSDK 20348.1.210507 and the problem disappears.

However, the problem of installing this SDK on win10 1709 still exists.
