### ISSUE TITLE
Problem about Last Value Caching in XPub

### ISSUE THREAD

**Issue by imkcy9** [zeromq/libzmq#3510]
# Issue description
As the test code below, I think this last value cache should be sent to the last pipe which subscribe message, but the Xpub send the cache message to all pipes so the other pipe will recv a duplicated publish message. Is it possible to change the behavior on Xpub ZMQ_XPUB_MANUAL to send message to just one pipe when a last pipe just subscribe message to XPub socket?

# Environment

* libzmq version :  4.1.X
* OS: Linux

# Minimal test code
 //  When we get a new subscription, we pull data from the cache:
        if (items [1].revents & ZMQ_POLLIN) {
            zmq::message_t msg;
            backend.recv(&msg);
            if (msg.size() == 0)
                break;
            //  Event is one byte 0=unsub or 1=sub, followed by topic
            uint8_t *event = (uint8_t *)msg.data();
            if (event[0] == 1) {
                std::string topic((char *)(event+1), msg.size()-1);
                auto i = cache_map.find(topic);
                if (i != cache_map.end())
                {
                    s_sendmore(backend, topic);
                    s_send(backend, i->second);
                }
            }
        }

**Comment by mbodmer** [comment]
I am also interested in a solution to this. Did you find a possibility?
