### ISSUE TITLE
configure errors because of syntax errors in the use of `test` shell command

### ISSUE THREAD

**Issue by ackalker** [zeromq/libzmq#3517]
*Please use this template for reporting suspected bugs or requests for help.*

# Issue description

On my system, where `/bin/sh -> /bin/dash`, runnung `./configure` produces errors which I tracked down to `configure.ac` and `acinclude.m4` using the `test` shell command with a `==` operator, syntax which is not valid in a POSIX-like shell like `dash`. See [`man 1p test`](https://www.unix.com/man-page/posix/1P/TEST/) for details.

# Environment

* libzmq version (commit hash if unreleased): cef80655
* OS: Void Linux x86_64

# Minimal test code / Steps to reproduce the issue

1.  Run `./autogen.sh`
2.  Run `./configure`

# What's the actual result? (include assertion message & call stack if applicable)

```sh
[...output from step 2...]
./configure: 21529: test: x: unexpected operator
./configure: 21534: test: unexpected operator
```
Full output of running the repro steps on my system:
step 1: [output](https://gist.github.com/f7762a406c62228a0012c55d49c6f754)
step 2: [output](https://gist.github.com/65dea53e4a9a48c1131af6d0de7b2069).

# What's the expected result?

Running `configure` should produce no such errors.

**Comment by bluca** [comment]
Could you please send a PR to fix it?

**Comment by ackalker** [comment]
Will do, I'm already on it.
