### ISSUE TITLE
Problem: ZAP auth sometimes not retried using TCP

### ISSUE THREAD

**Issue by jean-airoldie** [zeromq/libzmq#3519]
# Issue description
Authentication attempts are sometimes (~50%) not retried when using TCP with NULL mechanism,

# Environment
* libzmq version : 046ccfc4
* OS: fedora 29

# Reproduction Steps
1. Create a ZAP handler and configure it to refuse all local sockets (e.g. blacklist the loopback addr).
2. Create a `CLIENT` and `SERVER`, set a ZAP domain and connect them to each others via TCP.
3. Send a message from the `CLIENT` socket to the `SERVER`.
4. Wait for 1 second.
5. Now update the state of the ZAP handler to allow all local sockets (e.g. remove the loopback addr from the blacklist).
6. Receive the message from the `SERVER`.

# What's the actual result?
About 50% of the time the message is received and 50% it blocks forever (I explain why later).

# What's the expected result?
 The `SERVER` receive call should never block forever.

# Socket Events
I did some digging using the socket monitor API. Turns out that the socket events are different in the two scenarios.

### Socket Events for the `SERVER`
```
Accepted
HandshakeFailedAuth(Denied)
HandshakeFailedAuth(Denied)
Disconnected
Accepted
HandshakeFailedAuth(Denied)
HandshakeFailedAuth(Denied)
Disconnected
# Pattern repeats many times until finally...
Accepted
HandshakeSucceeded
```
### Socket Events for the `CLIENT`
```
ConnectDelayed
Connected
HandshakeFailedAuth(Denied)
HandshakeFailedAuth(Denied)
Disconnected
ConnectRetried(163ms)
ConnectDelayed
Connected
HandshakeFailedAuth(Denied)
HandshakeFailedAuth(Denied)
Disconnected
ConnectRetried(117ms)
# Pattern repeats many times until finally...
ConnectDelayed
Connected
HandshakeSucceeded
```
In this case the connection is retried by the `CLIENT` socket until authentication succeeds. Thus the message can be sent from the `CLIENT` to  the `SERVER`.

### Socket Events for the `SERVER`
```
Accepted
HandshakeFailedAuth(Denied)
HandshakeFailedAuth(Denied)
Disconnected
```
### Socket Events for the `CLIENT`
```
ConnectDelayed
Connected
HandshakeFailedAuth(Denied)
HandshakeFailedAuth(Denied)
Disconnected
```
In this case the connection is not retried by the `CLIENT` socket after the first authentication attempt fails. Thus the message is never sent to the `SERVER`.

**Comment by jean-airoldie** [comment]
This is related to the issue @swilwerth mentionned in #3505.

**Comment by bluca** [comment]
The reconnection logic is in https://github.com/zeromq/libzmq/blob/master/src/session_base.cpp

**Comment by jean-airoldie** [comment]
Cool I'll check it out.

**Comment by swilwerth** [comment]
I'm reading that code, but is new to me, I need more research to understand the sequence of function calls when in zap, and what happens in the connecter thread after its launch.

I found two details not very clear for me:
In:
```c++
void zmq::session_base_t::reconnect ()
```
There is a call to a function reset() which has no body.
If options.reconnect_ivl  == -1
There is a new std::string memory allocation for the address, but I haven't found where is it deallocation.

**Comment by bluca** [comment]
https://github.com/zeromq/libzmq/commit/7942db7606c76f71b77863f8f883047ec69ffc5f
https://github.com/zeromq/libzmq/blob/master/src/socket_base.cpp#L1422

**Comment by swilwerth** [comment]
Got it! Thanks

**Comment by sigiesec** [comment]
I think this might also be the cause of the zap/security test failures that happen sometimes on the CI jobs.

**Comment by jean-airoldie** [comment]
I could write a minimal reproducible test case if that could help. The problem is that debugging is pretty hard since the error is happening in a background thread.

**Comment by jean-airoldie** [comment]
Moreover it seems like there are simply no authentication retries when using CURVE.

**Comment by jean-airoldie** [comment]
I found some weird behaviour using the NULL mechanism.

If I assign a ZAP domain to both the client and the server then the ZAP handshake is only retried twice. However if I only assign a ZAP domain to the client and not the server, then the handshake is retried until it succeeds.

**Comment by swilwerth** [comment]
I think the answer may be related of which role (server, client) binds and what one connects. 
According to the 0mq [SPEC 23](https://rfc.zeromq.org/spec:23/ZMTP/), in the topology part, mentions that the client/server role could be inverted at TCP role level.
Traditionally in TCP the server binds, and the client connect, this might not be the case.

According to the [ZAP specs](https://rfc.zeromq.org/spec:27/ZAP/)

> ZAP is a Remote Procedure Call
> 
> ZAP uses the ZeroMQ request-reply pattern. Specifically, the handler binds a REP socket, and the server connects a REQ socket. In practice the servers may use DEALER sockets in order to send multiple requests at once, and handlers may use ROUTER sockets for the same reason. Furthermore, ZAP messages contain the request-reply address envelope so that requests can be sent along multiple intermediaries, and replies will return to the right server.
> 

The "Some Things to Consider" part of this:
http://www.evilpaul.org/wp/2017/05/02/authentication-encryption-zeromq/

I don't really know how ZMQ manages to reverse the server/client roles over TCP.

**Comment by jean-airoldie** [comment]
Interesting.

As for the mentioned race condition in the "Some Things to Consider", I use `ZMQ_ZAP_ENFORCE_DOMAIN` to force the `ZAP` handler to be used by connecting sockets. So theoretically, I should not be having this problem. I'll make sure it is the case though.
