### ISSUE TITLE
zmq_msg_recv() has poor scalability (in terms of Gbps throughput) on a given socket

### ISSUE THREAD

**Issue by bobzhuyb** [zeromq/libzmq#3525]
*Please use this template for reporting suspected bugs or requests for help.*

# Issue description

Background: We are developing a network bandwidth-hungry application using zmq. Our environment has 100Gbps Ethernet connection per server. In iperf tests between two servers, a single TCP connection can run up to 15Gbps, and many parallel TCP connections can get aggregated 80+Gbps.

Problem: We find that when we use only one zmq socket (e.g., ROUTER or PULL) for receiving, the receving throughput is capped to roughly the same as a single kernel TCP connection (i.e., ~15Gbps), no matter how many senders are there. Increasing ZMQ_IO_THREADS, ZMQ_RCVBUF and ZMQ_SNDBUF does not help. We can't find a way to get higher throughput than that with just one receiving zmq socket.

# Environment

* libzmq version (commit hash if unreleased): 4.1.4, or master branch 96b9eece158311095cb0e3db9e6d655773385b57

* OS: Debian 8.11 (Linux kernel 4.9)

* Hardware: as described above, a few servers connected via 100Gbps NICs, cables and a switch. CPU and memory are far more than enough to drive 80Gbps+ TCP throughput.

# Minimal test code / Steps to reproduce the issue

1. Find two servers with Ethernet connection that is faster than a single TCP flow can saturate.

2. Use perf/local_thr and perf/remote_thr in libzmq repo

3. (Problematic scenario) on one server, run `perf/local_thr tcp://xxxx:5050 4096000 4000`. On the other server, run two instances of `perf/remote_thr tcp://xxxx:5050 4096000 2000` at the same time. Observe the total throughput.

4. (For comparison) On one server, run twice `perf/local_thr tcp://xxxx:yyyy 4096000 2000`, with different TCP ports. On the other server, run two instances of `perf/remote_thr tcp://xxxx:yyyy 4096000 2000` connecting to the two local_thr respectively. 

# What's the actual result? (include assertion message & call stack if applicable)

The total throughput of  Step 4 is much higher than Step 3. 

In our environment, Step 3 always gets ~15Gbps throughput, even with 4 or more concurrent senders. The throughput in Step 4 scales almost linearly with the number of processes (and thus the receiving sockets.)

# What's the expected result?

However, following zmq's programming model, we would expect that using a single receiving socket (in Step 3) can give us as good throughput as Step 4.

I thought that zmq internal threads would receive as many messages as defined by ZMQ_RCVHWM in a best-effort manner, and zmq_msg_recv() is just a zero-copy function that gets us the pointer to the received data in the form of messages (once there are any). If that's the case, zmq_msg_recv() should have scaled well with multiple senders. Unfortunately, it does not seem to be that way.

Did I miss anything? How may we get around this? 

With kernel socket, I would use accept() on the server to get an individual socket for each client, and recv() from them using multi-threading. However, it's not as straightforward (to me) to create multiple server socket in zmq, since it does not have accept()..

**Comment by somdoron** [comment]
Did you try to create multiple listeners (zeromq bind socket) on the server side and use a different thread for each? on the client side, you can connect to both sockets (using dealer or push) and the socket will load balance between the two (or more).

**Comment by bobzhuyb** [comment]
When using multiple zmq sockets for receiving, the total throughput would scale just fine. However, we would like to use only one TCP port on the server.. Is it possible to bind multiple zmq sockets to the same TCP port? 

I only know that kernel sockets are relatively easy for this, either by bind-once-then-accept() or using SO_REUSEADDR option.

**Comment by somdoron** [comment]
I'm not sure you can bind multiple sockets to the same TCP port.

You can try and build a proxy that split the traffic over inproc to multiple threads, but I'm not sure that will increase the throughput.

You might be limited by the application thread handling the messages.

So create multiple handlers (pull) and a broker (push-pull), broker bind the TCP port and bind over INPROC.

**Comment by bobzhuyb** [comment]
Thanks for the suggestion, though I highly doubt that the bottleneck is the app thread. The benchmark code (https://github.com/zeromq/libzmq/blob/master/perf/local_thr.cpp#L119) essentially does nothing except for zmq_recvmsg(). Since zmq_recvmsg is zero-copy, it should be really lightweight.

In the reproduce example above, I used 4MB message size, so the msg/second rate is just a few hundreds for 15Gbps throughput. I don't see how application thread can be a bottleneck for this.

**Comment by bluca** [comment]
Why is the TCP port a problem? You are using the same socket to receive, so it doesn't change anything from the application point of view. That's the right way to scale with push/pull.

Remember to set HWM to infinite, otherwise the sockets are going to block/drop at some point. Of course you need to ensure there is enough memory on the system to handle it, and that your receiver is at least as fast as the producer to handle the messages.

At that level, you are also probably being hit by the limit set by the inbound buffer size, which is 8KB - that is a value that works well in most occasions, but for a syntetic benchmark when you know more data is going to be available, you can try to tweak it and set it to your message size to avoid the extra wasted malloc: https://github.com/zeromq/libzmq/blob/master/src/config.hpp#L59

Also, for raw throughtput you'll always have better results with pub/sub

**Comment by bobzhuyb** [comment]
Regarding the TCP port, the real environment is a bit complicated. The app worker (or slave) is running in a shared cluster and has its own implementation to acquire a dynamic port and report the port to master. Master identifies each slave by unique "ip:port" tuples, and tells other slaves. I am not saying it's impossible to extend all this to support multi-TCP-port. It's just quite a bit of work, and seems to be patching something in a wrong place -- it's merely a local throughput problem, why should we fix it at the cluster scheduling level?

I don't think HWM is ever hit, because there is.no message drop in the test. 

We will try tuning the inbound buffer size. Thanks for the link!

**Comment by bluca** [comment]
push doesn't drop when HWM is reached, it blocks which will look as a slowdown, that's why I mentioned it

**Comment by bobzhuyb** [comment]
Okay, we will make sure HWM is very large, though the sender (push) side does not seem like a bottleneck. 

Does the zmq receiver (pull or router) have any additional flow control mechanism to slowdown senders except for TCP's flow control?

**Comment by bluca** [comment]
HWM applies to both sides, receiver has one too

**Comment by bobzhuyb** [comment]
I understand that receiver will drop messages if HWM is hit, and I don't see the receiver dropping any in the test.

**Comment by bobzhuyb** [comment]
Closing this issue since we decide to implement a workaround -- let servers connect to multiple clients, and use those sockets to receive data. Previously, it was the server being connected from clients, so server has only one (router) socket for receiving and thus we faced the scalability problem.

This is not a real fix to the zmq problem, but we can live with it now.
