### ISSUE TITLE
Is libzmq safe with posix_spawn?

### ISSUE THREAD

**Issue by skicc** [zeromq/libzmq#3531]
# Issue description
Sorry but this issue is a bit broad and seems even not a issue...

I know zmq may have some issues with fork() and using zmq in both parent and child process. I wonder whether it is safe to use posix_spawn() with zmq? Or, if I call exec right after fork/vfork, will zmq have any chances to be somewhat corrupted?

I did some naive tests and it seems to work.

Thanks!

# Environment

* libzmq version (commit hash if unreleased): 4.3.1
* OS: Windows, Linux

**Comment by bluca** [comment]
Same as with fork, just terminate the context in the child immediately after fork and before exec* and it will work
