### ISSUE TITLE
Connection through SOCKS5 proxy does not work

### ISSUE THREAD

**Issue by guillon** [zeromq/libzmq#3533]
# Issue description

Connection through SOCKS5 proxy does not work since commit 12c4b55a

# Environment

* libzmq version (commit hash if unreleased): commit 12c4b55a (version > 4.3.1)
* OS: all OSes

# Minimal test code / Steps to reproduce the issue

Initiate a connection through a SOCKS5 proxy with:
#include <zmq.hpp>
int main(int argc, char *argv[])
{
  const std::string socks_server("localhost:1080");
  const std::string server("localhost:5556");
  zmq::context_t context(1);
  zmq::socket_t sock(context, ZMQ_SUB);
  sock.setsockopt(ZMQ_SOCKS_PROXY, socks_server.c_str(), socks_server.length());
  sock.connect(std::string("tcp://") + server);
  sock.setsockopt(ZMQ_SUBSCRIBE, "", 0filter.c_str(), filter.length());

  zmq::message_t message; 
  sock.recv(&message);   

# What's the actual result? (include assertion message & call stack if applicable)
Actually, zmq connects directly to the target host (localhost:5556), ignoring the proxy server configuration (localhost:1080).
From the proxy server side logs (localhost:1080), not any connection attempt is visible.

# What's the expected result?
Connection through the proxy first, and let the proxy relay the connection to the target address.
This is the behavior of the last published release (4.3.1) which does not have this issue.

Actually the issue was introduced with commit  12c4b55a.

**Comment by guillon** [comment]
Here is a pull request which solves the issues: pr #3532

**Comment by bluca** [comment]
Fixed by https://github.com/zeromq/libzmq/pull/3532
