### ISSUE TITLE
Unable to use Streamer with inproc

### ISSUE THREAD

**Issue by jayrbolton** [zeromq/libzmq#3549]
# Issue description

I haven't been able to successfully use the `inproc` protocol in combination with a Streamer device. Apologies if I'm using zmq incorrectly, but I can't find documentation about this anywhere.

See my code example here:
https://github.com/jayrbolton/zmq_stream_inproc/blob/master/main.py

I start two "pusher" workers and two "puller" workers with a streamer device in between. Runs in py3

# Environment

* libzmq version (commit hash if unreleased): 4.3.1 
* OS: Debian

# Minimal test code / Steps to reproduce the issue

1. Clone the above repo
2. Using python 3: `python -m venv env`
3. `source env/bin/activate`
4. `pip install -r requirements.txt`
5. `python main.py`

# What's the actual result? (include assertion message & call stack if applicable)

Messages are pushed to the streamer's frontend socket, but never pulled by the backend.
If you switch from `inproc` to the `ipc` protocol, then it works as expected.

# What's the expected result?

Messages should flow from the `pusher` workers to the `puller` workers across the Streamer and be shown in stdout.

**Comment by bluca** [comment]
Not sure how the context works in python with threads, it needs to be the same shared among all of the threads, otherwise inproc doesn't work.

**Comment by jayrbolton** [comment]
My understanding is that `Context.instance()` shares the context across threads. Here's the output where i print the object ids in every thread:

```
context in parent <zmq.sugar.context.Context object at 0x7f0e409fc7b8>
context in pusher 0 <zmq.sugar.context.Context object at 0x7f0e409fc7b8>
context in pusher 1 <zmq.sugar.context.Context object at 0x7f0e409fc7b8>
context in puller 2 <zmq.sugar.context.Context object at 0x7f0e409fc7b8>
context in puller 3 <zmq.sugar.context.Context object at 0x7f0e409fc7b8>
```
Looks like they are the same object

**Comment by bluca** [comment]
This is all specific to pyzmq rather than libzmq - however, you are using a ProcessDevice which, as the name suggests, uses processes for multitasking. As the name suggests, inproc only works in the same process - it's just an in-memory queue. If you change from ProcessDevice to ThreadDevice it will then work.

**Comment by jayrbolton** [comment]
Thanks very much your help. That seems to have solved it. Apologies for this being pyzmq specific.. I posted this question in pyzmq and hadn't received any replies. I will relay this answer over there.
