### ISSUE TITLE
Problem: DISH can receive duplicate messages

### ISSUE THREAD

**Issue by jean-airoldie** [zeromq/libzmq#3552]
# Issue description
A DISH socket can connect multiple times to the same RADIO socket which duplicates the traffic. Not sure if this is intended.

# Environment
* libzmq version (commit hash if unreleased):  fcf828d
* OS: fedora 29

# Minimal test code / Steps to reproduce the issue
* Create and bind a RADIO socket.
* Create a DISH socket. Connect it twice to RADIO.
* Wait a bit for the connection to be established. 
* Send a message from the RADIO socket.
* Attempt to receive two messages from the DISH socket.

# What's the actual result? (include assertion message & call stack if applicable)
The DISH socket receives the same message twice.

# What's the expected result?
The DISH socket should probably only receive the message once.

**Comment by mrvn** [comment]
Why would you connect twice? Unless you connect different sockets this seems like you did something wrong.

As expected result I would rather see: Second connect fails with: already connected.

**Comment by jean-airoldie** [comment]
If you are connected on a DNS for instance, connecting multiple times to the same endpoint will cycle through the load balancer (see #2297).

As for the expected result I think silently ignoring the connect call if it resolves to a already connected endpoint would make more sense.

**Comment by tyler274** [comment]
still relevant.
