### ISSUE TITLE
zmq4.3.1 error on armv7l 

### ISSUE THREAD

**Issue by jaein-ETRI** [zeromq/libzmq#3553]
*Please use this template for reporting suspected bugs or requests for help.*

# Issue description
When I run the go lang application with pebbe/zmq library on the armv7l (32bit) and zmq4.3.1, 
error codes are coming. 

zmq 4.3.1 version is not working on armv7l(32bit) yet??
It was working well on the zmq 4.2.5 version. 

error codes:

panic: runtime error: invalid memory address or nil pointer dereference
        panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x2210e4]

goroutine 1 [running]:
github.com/pebbe/zmq4.(*Socket).Close(0x0, 0x866688, 0x1)
        /root/go/src/github.com/pebbe/zmq4/zmq4.go:852 +0x14
panic(0x28b208, 0x4b2708)
        /usr/local/go/src/runtime/panic.go:513 +0x194
github.com/pebbe/zmq4.(*Socket).Connect(0x0, 0x8844c0, 0x1a, 0x0, 0x0)
        /root/go/src/github.com/pebbe/zmq4/zmq4.go:911 +0x24

# Environment

* libzmq version (commit hash if unreleased): 4.3.1
* OS: linux

# Minimal test code / Steps to reproduce the issue

1.  

ss, _ := zmq4.NewSocket(zmq4.SUB)
ss.Connect("tcp://localhost:5555")              <-- error point 

# What's the actual result? (include assertion message & call stack if applicable)

# What's the expected result?

**Comment by bluca** [comment]
Can you reproduce without go, using just libzmq?

**Comment by jaein-ETRI** [comment]
Thanks bluca, I'm trying to other way.
