### ISSUE TITLE
Very high latency in dealer-router

### ISSUE THREAD

**Issue by nagarajsherigar** [zeromq/libzmq#3560]
Using libzmq 4 2.5 on centos 7. Getting very high latency when messages are sent from dealer to router and even from router to dealer. So i wrote simple client-server program using tcp and sent messages between them just for comparison. Tcp appears to be fast.

Sending single byte from dealer to router, zmq takes 900 microseconds.

Sending single byte from client to server, tcp takes 150 microseconds.

What am I doing wrong. I thought zmq will be atleast as fast as tcp. Is there any tuning I can do to make zmq faster?

**Comment by bluca** [comment]
On a single byte a naked tcp connection is obviously faster, as zmq adds an additional protocol with a connection handshake, asynchronous delivery and messages, all on top of tcp, so by definition it's impossible to have lower latency. The point is that it scales, and with techniques like zero copy and batching, with large quantities of messages this overhead is absorbed.

**Comment by nagarajsherigar** [comment]
OK. I repeated the test and sent payload of 512 bytes and in loop of 10000.most of the messages are around 300-400 microseconds and few are in range 50-60 microseconds. The lower latency are only in small groups. Is this normal?

**Comment by bluca** [comment]
I'm not sure what that means. There are performance test programs in this repository, they are built by default, use them if you want to get an idea: https://github.com/zeromq/libzmq/tree/master/perf

**Comment by nagarajsherigar** [comment]
I will explain how i recorded my cases. Dealer send a message of 512(including the timestamp) bytes for every 500 microsecond in a loop. At the router end when I receive a message,i again take the time stamp. Later once all the messages are recieved, I take the time difference. So for every message I have a sent time and recieved time. Using this i am checking the latency

**Comment by nagarajsherigar** [comment]
Regarding performance test cases. In remote_thr when is set send and recieve high marks to infinity there is a drop in throughput. Is setting high marks to infinity affects performance?

**Comment by nagarajsherigar** [comment]
@bluca can you give me some pointer on how to make the performance better

**Comment by bluca** [comment]
The thing is, this is a framework, not an end-product - it is not very useful to try and over-optimise arbtitrary test applications. What you should do instead, is to build a prototype for the actual application and protocol, and iterate on that. Read the zguide as the first step: http://zguide.zeromq.org/page:all

**Comment by nagarajsherigar** [comment]
@bluca I already have a working broker built using libzmq. During our load testing we facing the latency. So i wrote a 2 simple sample applications to test. Even there i am facing the issue. Dealer sends a message for every 500 microseconds, individual messages takes around 300-400 microseconds to reach router. Simple application is based on local_thr and remote_thr, modified for dealer - router with sleep in for loop. 300-400 is still a huge number for me. My applications is for high frequency financial domain.

**Comment by bluca** [comment]
Use pub-sub rather than dealer-router, and batch messages on poll - when poll returns, read as many messages as possible until there are no more and then go back into polling. Use zero copy API. These are things you can do. If you need more than that and nanoseconds matter, then nothing using the kernel networking stack will do - you'll have to build you own raw ethernet frame userspace application using DPDK or similar.

**Comment by nagarajsherigar** [comment]
@bluca these are my sample codes

**router.cpp**
    

```
#include <zmq.hpp>
    struct data
     {
     char one[21];
     unsigned long two;
    };
data * pdata;
std::size_t counter=0;

int main()
{
  zmq::context_t context(1);
  zmq::socket_t Device(context,ZMQ_ROUTER);
  
  int iHighWaterMark=0;
  
  Device.setsockopt(ZMQ_SNDHWM,&iHighWaterMark,sizeof(int));
  Device.setsockopt(ZMQ_RCVHWM,&iHighWaterMark,sizeof(int));
  
  Device.bind("tcp://0.0.0.0:5555");

  pdata=new data[10000];
  
struct timespec ts_dtime;
  unsigned long sec;
  
  zmq::message_t message;
  
  zmq::pollitem_t arrPollItems[]={{Device, 0, ZMQ_POLLIN, 0},{NULL, 0, ZMQ_POLLIN, 0}};
  
  while(counter < 10000)
    {
      try
	{
	  int iAssert = zmq::poll(arrPollItems, 1, -1);
	  if (iAssert <= 0)
	    {
	      if (-1 == iAssert)
		{
		  printf("zmq_poll failed errno: %d error:%s", errno, zmq_strerror(errno));
		 }
	       continue;
	     }
	   
	  if (arrPollItems[0].revents == ZMQ_POLLIN)
	    {
	      while(true)
		{
		  if(! Device.recv(&message,ZMQ_DONTWAIT))
		    break;

		  Device.recv(&message);

		  strncpy(pdata[counter].one,(char *)message.data(),message.size());
		  clock_gettime(CLOCK_REALTIME, &ts_dtime);
		  pdata[counter].two = (ts_dtime.tv_sec*1e9)+ ts_dtime.tv_nsec;
		  ++counter;
		}
	       
	     }
	 }
       catch(...)
	 {
	  
	 }
       
     }

      for(int i=0;i<counter;++i)
       printf("%d %s %lu\n",i+1,pdata[i].one,pdata[i].two);
   
      return 0;
      }
```
dealer.cpp

```
#include <zmq.hpp>
#include<unistd.h>

int main()
{
  zmq::context_t context(1);
  zmq::socket_t Device(context,ZMQ_DEALER);
  
  int iHighWaterMark=0;
  
  Device.setsockopt(ZMQ_SNDHWM,&iHighWaterMark,sizeof(int));
  Device.setsockopt(ZMQ_RCVHWM,&iHighWaterMark,sizeof(int));
  Device.setsockopt(ZMQ_IDENTITY,"TEST",4);
  
  Device.connect("tcp://0.0.0.0:5555");
  
  usleep(100000);

  struct timespec ts_dtime;
  unsigned long sec;
  
  for(std::size_t i=0;i<10000;++i)
    {
      clock_gettime(CLOCK_REALTIME, &ts_dtime);
      sec=(ts_dtime.tv_sec*1e9)+ ts_dtime.tv_nsec;
      zmq::message_t message(21);
      sprintf((char *)message.data(),"%lu",sec);
      Device.send(message);
      usleep(500);
    }

  return 0;
}
```

**Comment by nagarajsherigar** [comment]
@bluca Am i correct to assume sending a single message whatever the payload size maybe,i will always get a high latency figures?

**Comment by bluca** [comment]
"high" or "low" are relative terms and depend on the context. Run the programs in this directory to see what the library can do and decide for yourself: https://github.com/zeromq/libzmq/tree/master/perf

**Comment by nagarajsherigar** [comment]
> "high" or "low" are relative terms and depend on the context. Run the programs in this directory to see what the library can do and decide for yourself: https://github.com/zeromq/libzmq/tree/master/perf

i ran the tests,when i send 1 message i am getting a high latency,same is not seen when 1000 messages are sent.Every time i can't be sure i will get messages in bulk.most of the time application recieves single message

**Comment by bluca** [comment]
That's simply because the first message will be blocked until the TCP connection completes, since zmq_connect is asynchronous, and whent here's only one message the whole time is "counted" against that single message. When a 1000 are sent, the initial handshake is amortized against 1000 messages.

**Comment by nagarajsherigar** [comment]
> That's simply because the first message will be blocked until the TCP connection completes, since zmq_connect is asynchronous, and whent here's only one message the whole time is "counted" against that single message. When a 1000 are sent, the initial handshake is amortized against 1000 messages.

will i get same high latency if single messages are sent at regular frequencies?

**Comment by bluca** [comment]
no, if the same connection is reused

**Comment by nagarajsherigar** [comment]
> no, if the same connection is reused

that was my thinking also.but for consecutive single messages i am getting high latency

**Comment by nagarajsherigar** [comment]
@bluca are my test cases wrong?

**Comment by nagarajsherigar** [comment]
@bluca 
 This is what i am trying to tell.Check the below code

router.cpp

```
#include <zmq.hpp>
#include <stdio.h>
#include <stdlib.h>

int main (int argc, char *argv[])
{
    const char *bind_to;
    int roundtrip_count;
    size_t message_size;

    int rc;
    int i;


    if (argc != 4) {
        printf ("usage: local_lat <bind-to> <message-size> "
                "<roundtrip-count>\n");
        return 1;
    }
    bind_to = argv[1];
    message_size = atoi (argv[2]);
    roundtrip_count = atoi (argv[3]);

    zmq::context_t ctx(1);
  zmq::socket_t s(ctx,ZMQ_ROUTER);

  zmq::message_t msg,id;

    int iHighWaterMark=0;
    s.setsockopt(ZMQ_SNDHWM , &iHighWaterMark,
                         sizeof (int));
    s.setsockopt(ZMQ_RCVHWM , &iHighWaterMark,
                                              sizeof (int));
    s.bind( bind_to);
    struct timespec ts_dtime;
    unsigned long sec;
for (i = 0; i != roundtrip_count; i++) {
      rc =s.recv(&id);
        if (rc < 0) {
            printf ("error in zmq_recvmsg: %s\n", zmq_strerror (errno));
            return -1;
        }

        rc = s.recv(&msg, 0);
        if (rc < 0) {
            printf ("error in zmq_recvmsg: %s\n", zmq_strerror (errno));
            return -1;
        }

        clock_gettime(CLOCK_REALTIME, &ts_dtime);
        sec=((ts_dtime.tv_sec*1e9)+ ts_dtime.tv_nsec);
        printf("%.*s %lu\n",20,(char *)msg.data(),sec);
}




    s.close();



    return 0;
}
```


dealer.cpp

```
#include <zmq.hpp>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <unistd.h>
int main (int argc, char *argv[])
{
    const char *connect_to;
    int roundtrip_count;
    size_t message_size;

    int rc;
    int i;

    void *watch;
    unsigned long elapsed;
    double latency;

    if (argc != 4) {
        printf ("usage: remote_lat <connect-to> <message-size> "
                "<roundtrip-count>\n");
        return 1;
    }
    connect_to = argv[1];
    message_size = atoi (argv[2]);
    roundtrip_count = atoi (argv[3]);

    zmq::context_t ctx(1);
  zmq::socket_t s(ctx,ZMQ_DEALER);
                                                                                                                                       
  struct timespec ts_dtime;
  unsigned long sec;
int iHighWaterMark=0;
    s.setsockopt(ZMQ_SNDHWM , &iHighWaterMark,
                         sizeof (int));
    s.setsockopt(ZMQ_RCVHWM , &iHighWaterMark,
                                              sizeof (int));

    s.connect(connect_to);


    for (i = 0; i != roundtrip_count; i++) {
      zmq::message_t msg(message_size+20);
      clock_gettime(CLOCK_REALTIME, &ts_dtime);
      sec=(ts_dtime.tv_sec*1e9)+ ts_dtime.tv_nsec;
      sprintf((char *)msg.data(),"%lu",sec);
      rc = s.send(msg);
        if (rc < 0) {
            printf ("error in zmq_sendmsg: %s\n", zmq_strerror (errno));
            return -1;
        }

        sleep(1);
}
s.close();


    return 0;
}
```

output :
1562125527489432576 1562125527489773568
1562125528489582848 1562125528489961472
1562125529489740032 1562125529490124032
1562125530489944832 1562125530490288896
1562125531490101760 1562125531490439424
1562125532490261248 1562125532490631680
1562125533490422272 1562125533490798080
1562125534490555648 1562125534490980096
1562125535490745856 1562125535491161856
1562125536490894848 1562125536491245824
1562125537491039232 1562125537491416320
1562125538491229184 1562125538491601152
1562125539491375872 1562125539491764736
1562125540491517184 1562125540491908352
1562125541491657984 1562125541492027392
1562125542491816704 1562125542492193536
1562125543491963136 1562125543492338944
1562125544492103680 1562125544492564992
1562125545492248832 1562125545492675328
1562125546492397312 1562125546492783616
1562125547492543744 1562125547492926720
1562125564495211008 1562125564495629824
1562125565495372032 1562125565495783168
1562125566495515904 1562125566495924224
1562125567495660800 1562125567496006144
1562125568495806464 1562125568496160000
1562125569495896064 1562125569496235520
1562125570496080128 1562125570496547584
1562125571496235008 1562125571496666624
1562125572496391424 1562125572496803584
1562125573496532224 1562125573496935680
1562125574496652800 1562125574497053952
1562125575496843776 1562125575497277184
1562125576496997120 1562125576497417216
1562125577497182208 1562125577497726976
1562125578497336832 1562125578497726464
1562125579497549312 1562125579497928704
1562125580497696512 1562125580498115328
1562125581497847808 1562125581498198528
1562125582497998336 1562125582498340096
1562125583498140160 1562125583498622464
1562125584498295296 1562125584498680832
1562125585498445312 1562125585498842624
1562125586498627328 1562125586499025920


All are in the range for 350-450us

**Comment by brettviren** [comment]
The guide provides a suggestion to use asynchronous client

http://zguide.zeromq.org/page:all#Asynchronous-Majordomo-Pattern

I'm doing my own latency checking and was curious so I made my own (synchronous) test using CZMQ.  

I check round trip and get similar results.  Here's the dealer/client output

```
I: 19-07-03 09:26:37 [20] there: 348 us, back: 332 us, total: 680 us
I: 19-07-03 09:26:38 [19] there: 279 us, back: 221 us, total: 500 us
I: 19-07-03 09:26:39 [18] there: 280 us, back: 203 us, total: 483 us
I: 19-07-03 09:26:40 [17] there: 272 us, back: 201 us, total: 473 us
I: 19-07-03 09:26:41 [16] there: 277 us, back: 201 us, total: 478 us
I: 19-07-03 09:26:42 [15] there: 279 us, back: 207 us, total: 486 us
I: 19-07-03 09:26:43 [14] there: 241 us, back: 201 us, total: 442 us
I: 19-07-03 09:26:44 [13] there: 245 us, back: 205 us, total: 450 us
I: 19-07-03 09:26:45 [12] there: 274 us, back: 205 us, total: 479 us
I: 19-07-03 09:26:46 [11] there: 286 us, back: 210 us, total: 496 us
I: 19-07-03 09:26:47 [10] there: 279 us, back: 204 us, total: 483 us
I: 19-07-03 09:26:48 [9] there: 278 us, back: 205 us, total: 483 us
I: 19-07-03 09:26:49 [8] there: 267 us, back: 211 us, total: 478 us
I: 19-07-03 09:26:50 [7] there: 277 us, back: 206 us, total: 483 us
I: 19-07-03 09:26:51 [6] there: 284 us, back: 205 us, total: 489 us
I: 19-07-03 09:26:52 [5] there: 285 us, back: 204 us, total: 489 us
I: 19-07-03 09:26:53 [4] there: 273 us, back: 206 us, total: 479 us
I: 19-07-03 09:26:54 [3] there: 278 us, back: 216 us, total: 494 us
I: 19-07-03 09:26:55 [2] there: 276 us, back: 207 us, total: 483 us
I: 19-07-03 09:26:56 [1] there: 240 us, back: 207 us, total: 447 us
```

below is the code, run like
```
./check-latency s:tcp://127.0.0.1:5678 c:tcp://127.0.0.1:5678
```
or on separate hosts
```
./check-latency s:tcp://127.0.0.1:5678
./check-latency c:tcp://127.0.0.1:5678
```

code 

```c++ 
#include <czmq.h>
#include <chrono>
#include <vector>

const int hwm = 1000;

static
uint64_t now_us() {
    return std::chrono::duration_cast<std::chrono::microseconds>(
        std::chrono::system_clock::now().time_since_epoch()).count();
}

struct args_t {
    const char* addr;
    int count, id;
};

void server (zsock_t* pipe, void* vargs)
{
    const args_t& args = *(const args_t*)vargs;

    zsock_t* sock = zsock_new_router(args.addr);
    if (!sock) {
        zsys_error("failed to make router to \"%s\"", args.addr);
        return;
    }

    int count = args.count;
    zsock_set_sndhwm(sock, hwm);
    zsock_set_rcvhwm(sock, hwm);

    zpoller_t* poller = zpoller_new(sock, NULL);

    zsock_signal(pipe, 0);      // ready

    while (!zsys_interrupted) {

        void* which = zpoller_wait(poller, -1);
        if (!which) {
            zsys_info("interrupted");
            break;
        }
        

        //zframe_t* routing = zframe_recv(sock);
        zframe_t* routing = NULL;
        int seq=0;
        uint64_t then=0;
        int rc = zsock_recv(sock, "fi8", &routing, &seq, &then);
        if (rc != 0) {
            zsys_error("recv failed at %d", count);
            continue;
        }
        
        uint64_t now = now_us();
        zsys_info("%lu - %lu = %lu us", now, then, now-then);

        //zframe_send(routing, sock, ZFRAME_MORE);
        rc = zsock_send(sock, "fi88", routing, seq, then, now);
        if (rc != 0) {
            zsys_error("send failed at %d", count);
            continue;
        }

        --count;
        if (0 == count or 0 == seq) {
            break;
        }
    }
    zpoller_destroy(&poller);
    zsock_destroy(&sock);
    zsock_signal(pipe, args.id);      // done
}



void client(zsock_t* pipe, void* vargs)
{
    const args_t& args = *(const args_t*)vargs;

    zsock_t* sock = zsock_new_dealer(args.addr);
    int count = args.count;
    zsock_set_sndhwm(sock, hwm);
    zsock_set_rcvhwm(sock, hwm);

    const int snooze = 1000;

    zsock_signal(pipe, 0);      // ready

    while (!zsys_interrupted) {

        zclock_sleep(snooze);

        uint64_t t1 = now_us(), t1copy=0, st=0;
        int rc = zsock_send(sock, "i8", count, t1);
        if (rc != 0) {
            zsys_error("client: send failed at %d", count);
            continue;
        }
        
        int newcount = 0;
        rc = zsock_recv(sock, "i88", &newcount, &t1copy, &st);
        if (count != newcount) {
            zsys_error("count mismatch %d != %d", count, newcount);
        }
        if (t1 != t1copy) {    
            zsys_error("time mismatch %ld != %ld", t1, t1copy);
        }

        uint64_t t2 = now_us();

        zsys_info("[%d] there: %ld us, back: %ld us, total: %ld us",
                  count, st-t1, t2-st, t2-t1);

        --count;
        if (count == 0) {
            break;
        }
    }

    zsock_destroy(&sock);
    zsock_signal(pipe, args.id);      // done
}

int main(int argc, char* argv[])
{
    // check-latency c:<client-address>|s:<server-address> [c:...|s:...] ...

    zsys_init();
    const int nsend = 20;
    std::vector<zactor_t*> actors;

    zpoller_t* poller = zpoller_new(NULL);

    for (int ind=1; ind < argc; ++ind) {
        zactor_t* actor=NULL;
        int id = actors.size();
        if (argv[ind][0] == 's') {
            args_t* leak = new args_t{argv[ind]+2, nsend, id};
            actor = zactor_new(server, (void*)leak);
        }
        else if (argv[ind][0] == 'c') {
            args_t* leak = new args_t{argv[ind]+2, nsend, id};
            actor = zactor_new(client, (void*)leak);
        }
        else {
            zsys_error("unknown component description: %d: \"%s\"", ind, argv[ind]);
            return -1;
        }
        zpoller_add(poller, zactor_sock(actor));
        actors.push_back(actor);
    }

    int ndead = 0;
    while (!zsys_interrupted) {

        void* which = zpoller_wait(poller, -1);
        if (!which) {
            zsys_info("interrupted");
            break;
        }
        
        int ind = zsock_wait(which);
        if (ind < 0) {
            zsys_error("unexpected signal");
            continue;
        }

        if (actors[ind]) {
            zactor_destroy(&actors[ind]);
            ++ndead;
        }
        else {
            zsys_warning("component %d already destroyed", ind);
            continue;
        }
        if (ndead == actors.size()) {
            break;
        }
    }
    zpoller_destroy(&poller);
    return 0;
}
```

**Comment by nagarajsherigar** [comment]
Ya man this is creating me a huge bottleneck. Any solutions? Not finding any on internet

**Comment by bluca** [comment]
I already explained how to measure latency: use perf/remote_lat and perf/local_lat.
The "tests" you came up with add a load of processing between messages that inflate the latency - allocating memory, copying buffers, measuring time, formatting strings, printing to console. That's why the performance test doesn't do any of that - because the tests get artificially skewed. When nanoseconds are being counted, all of this matter. That's where the "bottleneck" is coming from.

The point is to measure the raw latency of the library, without any application-side complication.

**Comment by brettviren** [comment]
FWIW, the `*_lat` tests give similar latency as `ping` for me.  Indeed, even as minimal as my test is, it's the app code that is taking up all the time here, not zmq.  An eye opener!

**Comment by bluca** [comment]
czmq, while being a boon for simplicity and usability, adds really a lot of overhead. Just look at the implementation of zsock_send and zsock_recv: https://github.com/zeromq/czmq/blob/master/src/zsock.c#L835
there are multiple memory allocations, string formattings and copying per each message. Those functions are intended to be used to quickly setup a protocol for control, and definitely not to be used when performance is critical.

That's why czmq's socket setup API can be mixed with libzmq's low level message APIs - so that you can take advantage of the simplicity and usability, but also access the lower overhead functions when necessary.

**Comment by nagarajsherigar** [comment]
@bluca there is a 1 sec delay from sender to dealer. Whatever processing is there it should be done by then. My point is  single message ls a taking high latwncy

**Comment by bluca** [comment]
It's the application that adds it. Use perf/*_lat and you'll see.

**Comment by nagarajsherigar** [comment]
@bluca I tried. I commented also saying I put a sleep in between single msg takes time

**Comment by bluca** [comment]
If you add a sleep, the test is slower, that's kinda obvious isn't it?

**Comment by nagarajsherigar** [comment]
I added a sleep to get a picture how long a single message takes to reach other end. See simple there a sender who captures the current time, sends a message goes to sleep for 1 sec wakes up and does the same thing again. At the reciever end when the message is recieved current time is captured. So taking the difference between recieved time and current time I will get the picture how long it took for single message to reach destination

**Comment by bluca** [comment]
No, that's not how performance tests work. Again, doing that skews performance and adds artificial delays, and when nanoseconds are being counted, it makes a difference. That's why performance tests do a single measurement and do a statistical evaluation, which also serves the purpose of smoothing out jitter that happens due to cpu stalls, network issues, etc etc

**Comment by brettviren** [comment]
@nagarajsherigar your test measures one-way latency between app codes + any difference in clocks between the hosts of the two endpoints.  Are you running both the router and the dealer app on the same host?

The numbers you quoted are consisted with mine, few hundred microsec and not ~1 s so you must be doing something different than your quoted code.

**Comment by nagarajsherigar** [comment]
@brettviren am running both on same host. This is the exact code i am using to measure. You can see the output also.

What are the figures you are getting? I ran this in 16 core cpu today morning

**Comment by nagarajsherigar** [comment]
@bluca for me single message latency matters the most

My setup is

Sender--->Broker--->Reciever

I always recieve single message at a time at irregular periods. But once the sender send it should reach reciever as early as possible

**Comment by bluca** [comment]
Yes, and that's what perf/*_lat measures

**Comment by nagarajsherigar** [comment]
@bluca in that it doest give me figures for single message. It gives for a batch. But in my prod I won't get messages in batch. That is why I wrote a sample code to measure one way latency

**Comment by bluca** [comment]
No, it does not give the latency of a batch. It gives the latency of a single message trip, with a clean implementation and statistically significant and relevant measurement.

The test you are proposing on the other hand is not valid, as it does a single measurement, which already is not statistically relevant, and on top of that skewers the result with application-side computations.

**Comment by nagarajsherigar** [comment]
@bluca OK. As i remember i was getting high figures for round trip 2(since you told for 1 it will be high because of initial tcp handshake) that is why I wrote a sample code. I will once again run with round-trip 2 and paste the figures

**Comment by bluca** [comment]
That was a simple observation on the fact that it's a connection-oriented protocol, and therefore it has a handshake to perform on top of TCP's own handshake, and that takes time.

**Comment by nagarajsherigar** [comment]
@bluca you have any observed latency figures?

**Comment by bluca** [comment]
on my laptop:

```
message size: 30 [B]
roundtrip count: 1000
average latency: 26.489 [us]
```

**Comment by nagarajsherigar** [comment]
@bluca can you check for 2?

**Comment by bluca** [comment]
no, because it's statistically meaningless as already explained

**Comment by nagarajsherigar** [comment]
@bluca 2 is not statistically meaningless it is very much a valid one

**Comment by bluca** [comment]
A sample of 2 is not statistically meaningful for any sense of the term. You are confusing sample size with the result - the result I posted _is_ of a single round trip, which is what you are after. If you want to know what's the average latency of 2 round trips, it's 26.489 * 2.

**Comment by nagarajsherigar** [comment]
@bluca but that is no where near the figure i was getting. Mine is always 350+

**Comment by bluca** [comment]
run with size 30 and sample 1000 and see

**Comment by nagarajsherigar** [comment]
@bluca then even for a existing connection,  sending a single message i should get around <30 rt

**Comment by nagarajsherigar** [comment]
@bluca running _lat with larger roundtrips always gives the best latency. But my application never gets continuous messages. Only 1 at a time. Even in lat test for lower message counts latency is worst. That is what am concerned

**Comment by bluca** [comment]
Again, a single sample measurement is a meaningless statistical measurement. The perf application using a decent sample shows what the average is. That's what's important.

**Comment by nagarajsherigar** [comment]
@bluca what is your machine configuration?

**Comment by nagarajsherigar** [comment]
message size: 30 [B]
roundtrip count: 1000
average latency: 25.869 [us]

**Comment by bluca** [comment]
it's a laptop with an i7-8650U cpu

**Comment by nagarajsherigar** [comment]
even in my machine i will get around 26.but the same am not getting when my application sends.sender sendst the message to broker,broker send the message to reciever.At reciever end the latency is 600us

**Comment by bluca** [comment]
and that means the application, with its design using a broken, is adding ~570us - assuming the measurement is done correctly with a big enough sample to average out jitter and so on

**Comment by nagarajsherigar** [comment]
@bluca if there is a broker in between i need to divide by 4 to get the latency?
this scenario
sender ==>broker
broker==>reciever
reciever==>broker(ACK)
broker==>sender

**Comment by bluca** [comment]
Hard to say, it depends on what the individual applications are doing. You can use standard profiling tools to find out what the bottlenecks are and what to focus on.

**Comment by nagarajsherigar** [comment]
@bluca what are those tools?

**Comment by nagarajsherigar** [comment]
@bluca weird observation running perf/*_lat on multi core machine latencies are worst

Below are the figures

16 cpu machine
./remote_lat tcp://127.0.0.1:5555 30 1000
```
message size: 30 [B]
roundtrip count: 1000
average latency: 97.219 [us]
```
single cpu machine
/remote_lat tcp://127.0.0.1:5555 30 1000
```
message size: 30 [B]
roundtrip count: 1000
average latency: 27.195 [us]
```

how is number of cpu making difference here?

**Comment by bluca** [comment]
The number of CPUs doesn't matter beyond 2, unless multiple IO threads are used, which is not necessary with a single socket - what's likely happening is that the single cpu is faster than an individual core of the 16 cpus machine, or memory bandwidth is faster, or a combination of this and many more factors

**Comment by nagarajsherigar** [comment]
> The number of CPUs doesn't matter beyond 2, unless multiple IO threads are used, which is not necessary with a single socket - what's likely happening is that the single cpu is faster than an individual core of the 16 cpus machine, or memory bandwidth is faster, or a combination of this and many more factors

i tried with various cpu count 2,4,16,32.same pattern

**Comment by bluca** [comment]
> what's likely happening is that the single cpu is faster than an individual core of the 16 cpus machine, or memory bandwidth is faster, or a combination of this and many more factors

**Comment by nagarajsherigar** [comment]
> > what's likely happening is that the single cpu is faster than an individual core of the 16 cpus machine, or memory bandwidth is faster, or a combination of this and many more factors

but in all the machines it will happen? weird

**Comment by nagarajsherigar** [comment]
> > what's likely happening is that the single cpu is faster than an individual core of the 16 cpus machine, or memory bandwidth is faster, or a combination of this and many more factors

how do i actually confirm this is what is happening?
in production it is a 32 cpu machine.non zmq process are running fast,only zmq is is showing higher latencies

**Comment by nagarajsherigar** [comment]
@bluca Am i only one who is facing latency issues here?

**Comment by nagarajsherigar** [comment]
@bluca am using tcp protocol for the applications in the same box. Does it have any impact on latency?

**Comment by nagarajsherigar** [comment]
@bluca in very high end servers also am seeing the issue. It seems doesn't matter whether it is high end or low end. When there it is a muti processor system, the latencies are quite high almost 3x

**Comment by brettviren** [comment]
I try `local_lat` and `remote_lat` (using your example of 30 Bytes and 1000 round trips) on a 2nd gen i5 2.5 GHz, 4th gen i7 3.5 GHz and dual Xeon E5-2630 v4 2.2 GHz and see 30us, 17us and 49us, respectively using their loop-back interfaces.  So, multi CPU and multi core don't seem to matter.  Over 1 Gbps network between two i7 machines I get 75-90us.

Do be sure that you start `local_lat` before `remote_lat`.  Reverse their order mostly measures human response time.

**Comment by nagarajsherigar** [comment]
> I try `local_lat` and `remote_lat` (using your example of 30 Bytes and 1000 round trips) on a 2nd gen i5 2.5 GHz, 4th gen i7 3.5 GHz and dual Xeon E5-2630 v4 2.2 GHz and see 30us, 17us and 49us, respectively using their loop-back interfaces. So, multi CPU and multi core don't seem to matter. Over 1 Gbps network between two i7 machines I get 75-90us.
> 
> Do be sure that you start `local_lat` before `remote_lat`. Reverse their order mostly measures human response time.

I started local before remote only. Running both in same machine. First i checked in my laptop which is single processor i was getting around 39.then i copied the binaries to server which is 16 cpu xeon in that I get 90

**Comment by nagarajsherigar** [comment]
Am just copying the binary to the server and testing there. Dint do any code changes

**Comment by nagarajsherigar** [comment]
@bluca am trying to link zmq statically,but am getting these error

```
libzmq.a(src_libzmq_la-err.o): In function `zmq::print_backtrace()':
libzmq/src/err.cpp:423: undefined reference to `_Ux86_64_getcontext'
libzmq/src/err.cpp:424: undefined reference to `_ULx86_64_init_local'
libzmq/src/err.cpp:444: undefined reference to `dladdr'
libzmq/src/err.cpp:426: undefined reference to `_ULx86_64_step'
libzmq/src/err.cpp:435: undefined reference to `_ULx86_64_get_proc_info'
libzmq/src/err.cpp:438: undefined reference to `_ULx86_64_get_proc_name'
```

**Comment by bluca** [comment]
use pkg-config with the --static parameter, you are missing a lof of the dependencies

**Comment by nagarajsherigar** [comment]
@bluca can you give me the full command?

**Comment by nagarajsherigar** [comment]
> use pkg-config with the --static parameter, you are missing a lof of the dependencies

 can you give me the full command?
If lot of dependencies are missing how so file is working fine?

**Comment by bluca** [comment]
This is just a standard unix tool, nothing specific to libzmq. You can find plenty of information on how to compile linux applications searching online.

**Comment by nagarajsherigar** [comment]
> This is just a standard unix tool, nothing specific to libzmq. You can find plenty of information on how to compile linux applications searching online.

should i give pkg-config  while building libzmq or my application?

**Comment by nagarajsherigar** [comment]
@bluca i gave this pkg-config --static --libs libzmq

but still the same errors

**Comment by nagarajsherigar** [comment]
@bluca any suggestions?

**Comment by nagarajsherigar** [comment]
@bluca same errors

**Comment by nagarajsherigar** [comment]
@bluca figured it out.Thanks anyways

**Comment by nagarajsherigar** [comment]
@bluca when trying to compile with vmci this error is thrown

./configure --prefix=/home/mware_dev/gcc/gcc-9.1.0/ --with-vmci --with-libsodium

Making all in doc
make[1]: Entering directory `/home/mware_dev/libzmq/doc'
make[1]: Nothing to be done for `all'.
make[1]: Leaving directory `/home/mware_dev/libzmq/doc'
make[1]: Entering directory `/home/mware_dev/libzmq'
  CC       external/unity/unity.o
  CXX      tools/curve_keygen.o
  CXX      perf/local_lat.o
  CXX      perf/remote_lat.o
  CXX      perf/local_thr.o
  CXX      perf/remote_thr.o
  CXX      perf/inproc_lat.o
  CXX      perf/inproc_thr.o
  AR       external/unity/libunity.a
  CXX      src/src_libzmq_la-address.lo
  CXX      src/src_libzmq_la-client.lo
In file included from src/address.cpp:41:
src/vmci_address.hpp:39:10: fatal error: vmci_sockets.h: No such file or directory
   39 | #include <vmci_sockets.h>
      |          ^~~~~~~~~~~~~~~~
compilation terminated.
make[1]: *** [src/src_libzmq_la-address.lo] Error 1
make[1]: *** Waiting for unfinished jobs....

what is the solution for this?

using v4.2.5 tag

**Comment by bluca** [comment]
--with-vmci /path/to/directory/with/header

**Comment by nagarajsherigar** [comment]
> --with-vmci /path/to/directory/with/header

ok thanks

**Comment by nagarajsherigar** [comment]
@bluca am trying to bind the socket to 2 different endpoint.IPC and TCP
i get `Invalid argument` exception

sample code
Device->bind(IPCpoint);
Device->bind(TCPpoint);

IPCPoint="ipc:///tmp/0"
TCPPoint="tcp://192.168.1.210:*"

what might be the issue?

**Comment by nagarajsherigar** [comment]
@bluca One more observation

i started 2 applications in the same machine,established connection once using tcp and once more using ipc.I can see the latency between 2 protocol is almost same.Isnt it ipc should be fater than tcp?

**Comment by nagarajsherigar** [comment]
@bluca any suggestions?
