### ISSUE TITLE
Zmq Questions about Block Rollback

### ISSUE THREAD

**Issue by Rui2guo** [zeromq/libzmq#3574]
*Please use this template for reporting suspected bugs or requests for help.*

# Issue description

hello,
I'd like to ask ZMQ whether block monitoring for bitcoin will process rollback blocks into queues
In Jul-10-2019 11:24:15 Block rollback occurred in BSV network

But I found that ZMQ hashblock listener did not listen for the correct hash of the rollback block.
Original Chain： 590482 -->590483 --->590484
 
Normal occurrence block rollback chain:590482 -->590483(r) --->590484(r)-->590485--->(......)
ZMQ is not acquired the 590483(r) 590484(r) blockhash ,but the blockhash of 590485 is acquired. the old 590483 590484 is acquired

**Comment by sigiesec** [comment]
I don't think this is a question for libzmq. If it is, we would need more information on the usage of libzmq here.

**Comment by bluca** [comment]
Yes this is definitely the wrong repository, you need to find the application that's using the library. Closing.
