### ISSUE TITLE
zmq_socket_monitor documentation is incomplete for shutdown of monitor mode

### ISSUE THREAD

**Issue by f18m** [zeromq/libzmq#3575]
# Issue description
I found a very weird bug in my code that took me ages to debug. 
Here is what I was doing:
 1) create a ZMQ_STREAM
 2) put that STREAM socket in monitor mode (and open the ZMQ_PAIR socket associated)
 3) connect the STREAM socket to a TCP server
 4) close the ZMQ_PAIR socket of the monitor mode <-- this is where I was doing wrong - I thought this was enough to stop monitor mode
 5) shutdown the TCP server

PROBLEM: ZMQ background thread will hang forever trying to send a "ZMQ_EVENT_DISCONNECTED" event on the ZMQ_PAIR socket it contains.... nobody will ever dequeue that and the thread gets blocked forever inside zmq::socket_base_t::monitor_event().

SOLUTION: before step 4), just call zmq_socket_monitor(my STREAM socket, NULL, 0) to stop the monitor mode.

The fact that zmq_socket_monitor() accepts a NULL argument as endpoint to stop monitoring mode is however UNDOCUMENTED.

# Environment

* libzmq version (commit hash if unreleased): 4.3.1
* OS: Linux

# Minimal test code / Steps to reproduce the issue

See issue description.

**Comment by mrvn** [comment]
Could this be a race condition? Because I too have problems with closing monitor sockets.

In cases of errors or key changes I close both monitor and monitored sockets and then open them again. Sometimes it works, sometimes it works after a few seconds/retries and sometimes it keeps failing with:

    self._monitor = self._socket.get_monitor_socket()
  File "/usr/lib/python3/dist-packages/zmq/sugar/socket.py", line 735, in get_monitor_socket
    self.monitor(addr, events)
  File "zmq/backend/cython/socket.pyx", line 682, in zmq.backend.cython.socket.Socket.monitor
  File "zmq/backend/cython/checkrc.pxd", line 25, in zmq.backend.cython.checkrc._check_rc
zmq.error.ZMQError: Address already in use

I will try the python equivalent to your work around but I think this might be the same problem.

**Comment by sigiesec** [comment]
I think we hit this problem occasionally when running test_monitor (and maybe also test_security_zap). I have been able to capture an rr trace that exhibits the problem.

**Comment by SimonWoolf** [comment]
I think this is a race condition, and this issue should be reopened. I've also recently experienced this in production. Closing a monitor socket and then the main socket, without first unmonitoring the main socket, seems to have a small chance of leading to one of the iothreads becoming permanently blocked with the following stack:
```
Thread 23 (Thread 0x7f4c2bfff640 (LWP 3493589) "ZMQbg/IO/0"):
#0  0x00007f4cca918bcf in __GI___poll (fds=0x7f4c2bffdc40, nfds=1, timeout=-1) at ../sysdeps/unix/sysv/linux/poll.c:29
#1  0x0000000000d389b0 in zmq::signaler_t::wait (this=0x7f4c44003288, timeout_=-1) at /home/simon/dev/vendor/libzmq/src/signaler.cpp:219
#2  0x0000000000d21a7f in zmq::mailbox_t::recv (this=0x7f4c44003220, cmd_=0x7f4c2bffdd00, timeout_=-1) at /home/simon/dev/vendor/libzmq/src/mailbox.cpp:54
#3  0x0000000000d3eb9f in zmq::socket_base_t::process_commands (this=0x7f4c44002ae0, timeout_=-1, throttle_=false) at /home/simon/dev/vendor/libzmq/src/socket_base.cpp:1478
#4  0x0000000000d3e25a in zmq::socket_base_t::send (this=0x7f4c44002ae0, msg_=0x7f4c2bffdef0, flags_=2) at /home/simon/dev/vendor/libzmq/src/socket_base.cpp:1271
#5  0x0000000000d00e25 in s_sendmsg (s_=0x7f4c44002ae0, msg_=0x7f4c2bffdef0, flags_=2) at /home/simon/dev/vendor/libzmq/src/zmq.cpp:359
#6  0x0000000000d01cb8 in zmq_msg_send (msg_=0x7f4c2bffdef0, s_=0x7f4c44002ae0, flags_=2) at /home/simon/dev/vendor/libzmq/src/zmq.cpp:614
#7  0x0000000000d40544 in zmq::socket_base_t::monitor_event (this=0x7f4c44001ce0, event_=512, values_=0x7f4c2bffdfe0, values_count_=1, endpoint_uri_pair_=...) at /home/simon/dev/vendor/libzmq/src/socket_base.cpp:1979
#8  0x0000000000d402b1 in zmq::socket_base_t::event (this=0x7f4c44001ce0, endpoint_uri_pair_=..., values_=0x7f4c2bffdfe0, values_count_=1, type_=512) at /home/simon/dev/vendor/libzmq/src/socket_base.cpp:1945
#9  0x0000000000d40084 in zmq::socket_base_t::event_disconnected (this=0x7f4c44001ce0, endpoint_uri_pair_=..., fd_=26) at /home/simon/dev/vendor/libzmq/src/socket_base.cpp:1907
#10 0x0000000000d789b3 in zmq::stream_engine_base_t::error (this=0x7f4c200044d0, reason_=zmq::i_engine::timeout_error) at /home/simon/dev/vendor/libzmq/src/stream_engine_base.cpp:692
#11 0x0000000000d78ea1 in zmq::stream_engine_base_t::timer_event (this=0x7f4c200044d0, id_=129) at /home/simon/dev/vendor/libzmq/src/stream_engine_base.cpp:744
#12 0x0000000000d322d9 in zmq::poller_base_t::execute_timers (this=0x7f4c44001a70) at /home/simon/dev/vendor/libzmq/src/poller_base.cpp:85
#13 0x0000000000d1e3ce in zmq::epoll_t::loop (this=0x7f4c44001a70) at /home/simon/dev/vendor/libzmq/src/epoll.cpp:146
#14 0x0000000000d32519 in zmq::worker_poller_base_t::worker_routine (arg_=0x7f4c44001a70) at /home/simon/dev/vendor/libzmq/src/poller_base.cpp:119
#15 0x0000000000d4b0a3 in thread_routine (arg_=0x7f4c44001ac8) at /home/simon/dev/vendor/libzmq/src/thread.cpp:229
#16 0x00007f4cca894ac3 in start_thread (arg=<optimised out>) at ./nptl/pthread_create.c:442
#17 0x00007f4cca926850 in clone3 () at ../sysdeps/unix/sysv/linux/x86_64/clone3.S:81
```
