### ISSUE TITLE
worst latency for single message

### ISSUE THREAD

**Issue by nagarajsherigar** [zeromq/libzmq#3577]
i have a requirement to build real-time-low-latency messaging system.I read up zeromq guide ,for my requirement ROUTER-DEALER pattern matches perfectly.I built the system around it and it is working fine.But when i am doing performance testing i found zeromq latency is staggeringly high.
So i tested with latency tests provided in libzmq perf/ folders

./local_lat tcp://127.0.0.1:5555 1 1000
./remote_lat tcp://127.0.0.1:5555 1 1000
```
message size: 1 [B]
roundtrip count: 1000
average latency: 26.123 [us]
```
When the message count is high zeromq performance is awesome,but when the same message count is 1 the latency is quite high.

./local_lat tcp://127.0.0.1:5555 1 1
./remote_lat tcp://127.0.0.1:5555 1 1
```
message size: 1 [B]
roundtrip count: 1
average latency: 506.500 [us]

```
Still not convienced i took the publisher-subscriber example from zeromq guide modified to ROUTER-DEALER and added timestamp and tested again.There also it is really very high.This makes zeromq unusable .I agree when the message volumes are high there is nothing which will beat zeromq,but for the systems where the latency is critical even for single message zeromq fails.

Note : I ran the publisher-subscribe example also,it is showing me same latency figures

* libzmq version : 4.2.5
* OS: LINUX/UNIX

# Minimal test code / Steps to reproduce the issue

sender.cpp

```
 #include <zmq.hpp>
#include <stdlib.h>
#include <unistd.h>
#include <iostream>
#include <sys/time.h>

int main () {

    //  Prepare our context and publisher
    zmq::context_t context (1);
    zmq::socket_t publisher (context, ZMQ_ROUTER);
    publisher.bind("tcp://*:5556");

    //wait for peer to connect
    //once connected store the identity to send message later
    zmq::message_t identity,m;
    publisher.recv(&identity);//identity
    publisher.recv(&m);//message
    sleep(1);//sleep to set up connections
    struct timeval timeofday;
    int i=1;//no of messages to send
    while (i) {
      zmq::message_t id,message("10101",5);
      id.copy(&identity);
        gettimeofday(&timeofday,NULL);
	publisher.send(id,ZMQ_SNDMORE);
        publisher.send(message);

	std::cout << timeofday.tv_sec << ", " << timeofday.tv_usec << std::endl;
        usleep(1);
	--i;
    }
    return 0;
}
```

reciever.cpp

```
#include <zmq.hpp>
#include <iostream>
#include <sys/time.h>

int main (int argc, char *argv[])
{
    zmq::context_t context (1);

      zmq::socket_t subscriber (context, ZMQ_DEALER);
       subscriber.setsockopt(ZMQ_IDENTITY,"1",1);
       subscriber.connect("tcp://localhost:5556");

    struct timeval timeofday;
    subscriber.send(" ",1);
    int update_nbr;
    int i=1;
    for (update_nbr = 0; update_nbr < i; update_nbr++) {

        zmq::message_t update;
 
        subscriber.recv(&update);

	gettimeofday(&timeofday,NULL);
        std::cout << timeofday.tv_sec << ", " << timeofday.tv_usec << std::endl;
    }
    return 0;
}
```

# What's the actual result? (include assertion message & call stack if applicable)

sender output
`1562908600, 842072`

reciever output
1562908600, `842533`

As you can see it takes about 400 us.

# What's the expected result?

definitely not what the numbers i am seeing now.should be way less

**Comment by nagarajsherigar** [comment]
Any solutions?

**Comment by somdoron** [comment]
Zeromq is not very fast in sending one message, zeromq excel at sending and receiving at scale.
Sending one message is usually not a real-world scenario. Even if you have a client that is sending one message you still have a server that probably needs to accept messages from multiple clients.

Anyway, you can also try and enable the zero-copy option, which will improve performance for the scenario of one message.

**Comment by nagarajsherigar** [comment]
> Zeromq is not very fast in sending one message, zeromq excel at sending and receiving at scale.
> Sending one message is usually not a real-world scenario. Even if you have a client that is sending one message you still have a server that probably needs to accept messages from multiple clients.
> 
> Anyway, you can also try and enable the zero-copy option, which will improve performance for the scenario of one message.

Sending a single message is a real world scenario.  How do i use zero-copy option?

**Comment by somdoron** [comment]
https://github.com/zeromq/libzmq/blob/25bb43c33ad158a337ed349073f0a5deb74152c1/tests/test_ctx_options.cpp#L154

**Comment by nagarajsherigar** [comment]
> https://github.com/zeromq/libzmq/blob/25bb43c33ad158a337ed349073f0a5deb74152c1/tests/test_ctx_options.cpp#L154

Default value is 1.so that means zero copy is enabled right

**Comment by somdoron** [comment]
I agree with you that 400 ms sounds like way too much...

**Comment by nagarajsherigar** [comment]
> I agree with you that 400 ms sounds like way too much...

Is there any tunings I can do? This scenario is very critical for me

**Comment by somdoron** [comment]
Can you try a full round-robin before measuring performance?
Also, does the second message get a better performance?
It should definitely be under a millisecond.

**Comment by somdoron** [comment]
wait, it is 400us not ms, right?

**Comment by nagarajsherigar** [comment]
> Can you try a full round-robin before measuring performance?
> Also, does the second message get a better performance?
> It should definitely be under a millisecond.

When there is high volume of messages the performance is very good. It fails only when a single message is sent

**Comment by nagarajsherigar** [comment]
> wait, it is 400us not ms, right?

Yes measurements are in micro not milli

**Comment by somdoron** [comment]
> As you can see it takes about 400 ms.
You might want to change it to us.

Ok, the zeromq performance test actually tests a full round-robin. So the measurement between few to a lot should not be very different. However, the test also measures the first round-robin and only then calculate the average. I suggest making a full round before starting the measure.

**Comment by nagarajsherigar** [comment]
>  I suggest making a full round before starting the measure.
 Sorry i dint understand this part.. Can you help me with this

**Comment by somdoron** [comment]
https://gist.github.com/somdoron/df8daeec02cb435887103c9e469186c8

**Comment by nagarajsherigar** [comment]
> https://gist.github.com/somdoron/df8daeec02cb435887103c9e469186c8

I will test and see. Thank you

**Comment by nagarajsherigar** [comment]
Hi can anybody help me here?

**Comment by somdoron** [comment]
Can you try with client/server socket types? The latency is lower with those

**Comment by nagarajsherigar** [comment]
But that doesn't support multi part messages right

**Comment by somdoron** [comment]
Yes, you are right.
But they are using mutex for signaling instead of file descriptor. It can help to understand the issue you have.

By the way, what is your performance requirement?
What latency you would like too see for once in a while request?

**Comment by nagarajsherigar** [comment]
<150us
