### ISSUE TITLE
Assertion failed: false (src/object.cpp:166)

### ISSUE THREAD

**Issue by lukaszsamson** [zeromq/libzmq#3582]
# Issue description

Assertion failed: false (src/object.cpp:166)

# Environment

* libzmq version (commit hash if unreleased): 4.3.2
* OS: macOS 10.14.5

# Minimal test code / Steps to reproduce the issue

The bug is nondeterministic. My app is using erlang wrapper on libzmq but the stack trace does not tell where it fails. The app sends and receives messages over dealer socket and receives messages from sub socket.

# What's the actual result? (include assertion message & call stack if applicable)

```
Assertion failed: false (src/object.cpp:166)
Abort trap: 6
```

**Comment by sigiesec** [comment]
Are you sure you are using each socket only from a single thread?

**Comment by lukaszsamson** [comment]
@sigiesec It's an erlang app so there are Beam scheduler threads and I don't have control over which one of them is interacting with libzmq. However I looked into the wrapper code https://github.com/esl/erlzmq and it seems all of the socket usages are protected by a mutex.

**Comment by bluca** [comment]
mutex on the application side are not enough, as the I/O thread doesn't use them. Have a look at chumak, which is a native implementation: https://github.com/zeromq/chumak

**Comment by lukaszsamson** [comment]
@bluca chumak is not acceptable for my needs, see https://github.com/zeromq/chumak/blob/master/src/chumak_dealer.erl#L55

**Comment by lukaszsamson** [comment]
@bluca 
> mutex on the application side are not enough, as the I/O thread doesn't use them

does it mean that https://github.com/zeromq/erlzmq2 erlang binding is broken by design if it uses mutexes?

**Comment by sigiesec** [comment]
Migrating sockets between threads might work, but this is not a libzmq supported use case since there are too many pitfalls.

So based on that the design of erlzmq2 might be fundamentally flawed. However, I don't know enough about Erlang's execution model to judge that substantially.

**Comment by bluca** [comment]
Closing, as it's a problem in one of the bindings, not in this project
