### ISSUE TITLE
No simple way (aka no ZAP) to check client public key for authn

### ISSUE THREAD

**Issue by rixed** [zeromq/libzmq#3589]
*Please use this template for reporting suspected bugs or requests for help.*

# Issue description
My server knows of all client public keys and I'd like to use this client registry to authenticate the clients. I initially though that calling getPublicKey on the server would return the client public key, but apparently, that's just usable from the client to retrieve the key that's just been set.
Wouldn't that be more useful if getsockopt would return the client public key seen on that socket after the INITIATE?
Implementation seems trivial: after the INITIATE, once the client key is extracted from the box, save it in the socket (like, for instance, last_endpoints are saved), for a later getsockopt to retrieve it?
Would such a patch be welcomed or is this design flawed?

See also the exact same question on stack-overflow:
https://stackoverflow.com/questions/53839829/zeromq-how-to-get-the-public-key-of-a-client-when-using-a-router-socket-with-zm#

# Environment

* libzmq version (commit hash if unreleased): 4.3.2
* OS: Linux and MacOK

# Minimal test code / Steps to reproduce the issue

1.  call getsockopt on ZMQ_CURVE_PUBLICKEY from a curve server after a client has been authenticated by the curve server

# What's the actual result? (include assertion message & call stack if applicable)

Receive a zeroed buffer

# What's the expected result?

Receive the actual public key set by the client

**Comment by rixed** [comment]
Just wanted to add a few notes as to why one would want to do authn like this instead of using ZAP:

First, it's simpler, not requiring a dedicated thread for ZAP.
Then, it does not force the user to do authn right at the socket establishment. In my app for instance I'd like to allow unauthenticated communications until the client decide to upgrade its socket into a more secure mode where it is authenticated. This is when I'd like to check the supplied new identity with the public key.
Finally, ZAP authn service API is basic and inflexible: it takes the public key and must return the user identity, and that's it. As far as I can see there is no way to provide the authentication handler any more data, and for the authentication handler to return anything more than the userid. Furthermore, it seems from a rapid glance at the code that the userid is then attached to the message, not the socket. So that user program must read it from the first message of a new connection and then store it somewhere?

**Comment by bluca** [comment]
Zap is the way to do that. Look at the zauth implementation in czmq for a working example. Socket options cannot work.

**Comment by rixed** [comment]
I'm currently using ZAP as a complex work around to merely attach the public key to the socket, so I can do authn in my application (for the reasons explained above).

So I'd really like to know why socket options cannot work?

**Comment by bluca** [comment]
Among other reasons because the io thread connection management is asynchronous by design with the api thread and sockets are 1:N. Zap is the API to handle security, using it is the right thing. Look at zauth implementation in czmq if you need a working example with key whitelisting and so on.

**Comment by rixed** [comment]
Yes indeed you are right that setsockopt would not do it.
A more proper object to attach that information seems to be the message itself (as is done with the User-id that's returned from the ZAP handler). With the same annoying consequence that, if my understanding is correct, it would also be only set in the very first message.

(note: I've looked at several exemples of authn already; I'm not after a working exemple but after a way to implement my API with zmq. (remember the "tools not policy" idea: I have the policy, I'm now looking for the tools :))).
