### ISSUE TITLE
Problem: zmq_poller_wait doesn't error when polling a closed socket

### ISSUE THREAD

**Issue by jean-airoldie** [zeromq/libzmq#3592]
* libzmq version: 4.3.2
* OS: fedora 29

# Minimal test code / Steps to reproduce the issue
*  Create a poller.
* Create a socket.
* Add the socket to the poller.
* Close the socket.
* Call zmq_poller_wait on the poller with infinite timeout

# What's the actual result? (include assertion message & call stack if applicable)
The poller blocks forever.

# What's the expected result?
The poller errors out with `ENOTSOCK`.

**Comment by sigiesec** [comment]
This is as specified. Using a socket after zmq_close causes undefined behaviour. Maybe this should be clarified in the the documentation of zmq_close and/or zmq_poller.

**Comment by jean-airoldie** [comment]
Gotcha, I'll update the doc. Kinda tricky to enforce in this case however.
