### ISSUE TITLE
Missing .lib files in Windows .Zip downloads

### ISSUE THREAD

**Issue by DhavalNiphade** [zeromq/libzmq#3635]
*Please use this template for reporting suspected bugs or requests for help.*

# Issue description
It appears that no .lib files have been provided as part of the downloadable (.zip) binaries for Windows. This precludes users from statically linking the provided .dlls in their projects. The only work around I've found is to use LoadLibrary() or build the library from scratch. Perhaps more seasoned C++ developers could offer better advice.
Historically, .lib files were provided and made for easier integration.

# Environment
Visual Studio 14 (2015) x64
Visual Studio 15 (2017) x64

* libzmq version (commit hash if unreleased): 
* OS: Windows 10 Enterprise (17134.950)

# Minimal test code / Steps to reproduce the issue

1.  None. Could not find .lib to pass to the linker

# What's the actual result? (include assertion message & call stack if applicable)
NULL result. No .lib

# What's the expected result?
---

**Comment by somdoron** [comment]
I think adding *.lib to following line might solve it:
https://github.com/zeromq/libzmq/blob/master/appveyor.yml#L222

I cannot test it this week, you can make a PR, run app veyor on your own repository and download the artifact.

**Comment by sigiesec** [comment]
Thanks for opening the issue!

@bluca How are the archives published created? Are they from the appveyor builds? Then I can give that a look to fix this.

Indeed, an import library can be somehow created from the DLL, but this would only be an immediate workaround. The import library from the build process should be published along.

**Comment by somdoron** [comment]
@sigisec https://github.com/zeromq/libzmq/pull/3544

**Comment by somdoron** [comment]
@sigiesec https://github.com/zeromq/libzmq/pull/3540

**Comment by somdoron** [comment]
@sigiesec @DhavalNiphade I republished the v4.3.2 artifacts which include the lib files
