### ISSUE TITLE
Semantics of ZeroMQ sockets when used with epoll

### ISSUE THREAD

**Issue by Kobzol** [zeromq/libzmq#3641]
# Issue description
Hi! I would like to ask for a clarification of the semantics of using (the old, non thread-safe) ZMQ sockets with `ZMQ_FD` and `epoll`. When I use `epoll` in edge triggered mode with a `PUSH` socket and I hit the high watermark, the socket blocks (as it should). However, the problem is that once some other socket starts reading the messages, the `PUSH` socket will never unblock, i.e. there will be no more events coming from `epoll`. But if I read `ZMQ_EVENTS` after polling the socket, it will actually start to work, which is very unobvious, since this should be a simple "getter".

`ZMQ_EVENTS` is queried by the `zmq_poll` function and when you query the events, it will actually have a side effect and process some mailbox events on the sockets, which I suppose is what solves the issue with epoll. I didn't find any mention of this anywhere though, so I would like to ask for a clarification. How should `ZMQ_EVENTS` usage be combined with `epoll`? Is querying it after an `epoll` enough? What's the situation in terms of receiving messages? There it seems to work even without `ZMQ_EVENTS`, even if I hit the high watermark. 

I have attached a small (omits error checking, I don't check for epoll flags, since I only expect `EPOLLOUT`, it doesn't change anything anyway) code sample that reproduces this situation. The PUSH socket tries to send as much messages as it could, in a nonblocking way, using `epoll` to wait for the socket to become writable. After hitting the HWM (I set it to 1 to trigger the situation sooner, but it does the same thing even with the default 1000), the socket blocks. It should unblock after a PULL socket starts receiving on the given TCP address, but it doesn't. Actually even if a PULL socket was receiving before I start this program, the PUSH socket will still block and `epoll` will hang indefinitely (if the PULL socket is not fast enough and PUSH still hits its HWM).

The code will only work correctly if `EPOLLIN` is specified in the epoll event descriptor and if I call `getsockopts(ZMQ_EVENTS)` after polling. If I made any error in ZMQ/epoll usage, please let me know.

# Environment
* libzmq version: 4.2.5
* OS: Linux Mint 19.2, kernel 4.15.0-58

# Minimal test code
```cpp
#include <zmq.hpp>
#include <sys/epoll.h>
#include <iostream>

int main()
{
    void* ctx = zmq_ctx_new();
    void* socket = zmq_socket(ctx, ZMQ_PUSH);
    zmq_connect(socket, "tcp://127.0.0.1:5555");

    // set HWM to one to hit the error sooner
    uint32_t hwm = 1;
    zmq_setsockopt(socket, ZMQ_SNDHWM, &hwm, sizeof(hwm));

    int fd;
    size_t size = sizeof(fd);
    zmq_getsockopt(socket, ZMQ_FD, &fd, &size);

    struct epoll_event event;
    event.events = EPOLLIN | EPOLLOUT | EPOLLET | EPOLLHUP;
    event.data.fd = fd;

    int epoll = epoll_create(1);
    epoll_ctl(epoll, EPOLL_CTL_ADD, fd, &event);

    struct epoll_event events[10];
    while (true)
    {
        int event_count = epoll_wait(epoll, events, 10, -1);

        // if you uncomment the zmq_getsockopt call, it will work
        /*int zmq_events;
        zmq_getsockopt(socket, ZMQ_EVENTS, &zmq_events, &size);*/

        auto send = 1;
        while (send > 0)
        {
            zmq_msg_t msg;
            zmq_msg_init_size(&msg, 5);
            std::memcpy(zmq_msg_data(&msg), "Hello", 5);
            send = zmq_msg_send(&msg, socket, ZMQ_DONTWAIT);
            std::cerr << "Sending: " << send << std::endl;
        }
    }
    return 0;
}
```

# What's the actual result? (include assertion message & call stack if applicable)
The PUSH socket blocks indefinitely, no new epoll events are received if `ZMQ_EVENTS` are not queried.

# What's the expected result?
The PUSH socket should unblock after some other socket starts reading the messages.

**Comment by somdoron** [comment]
It is a bit tricky, after every pass the first timeout have to be zero (or skipping the epoll call). If no events is back you can continue with polling.

In your case, before every call to wait I would check the events (both in and out), if none, call wait. If in or out continue processing

**Comment by Kobzol** [comment]
My point is that in the example I have posted here, it works simply by querying `ZMQ_EVENTS`, I didn't even check if they contain the `ZMQ_POLLOUT` flag.

So that works "by accident"? The proper usage should be like this, otherwise it may block indefinitely?
```cpp
events = ZMQ_EVENTS;
if (!(events & POLLOUT)) epoll(...);
while (send() != EAGAIN);
```

If so, this is a bit unfortunate for my usecase, as I'm trying to use ZMQ sockets on top of an existing event loop (using `mio/Tokio` in Rust). Let's say that there is an existing `epoll` event loop and you cannot modify it, you only get a callback after an event is returned from `epoll`. Is it enough to query `ZMQ_EVENTS` after each such callback to ensure no lost events? Or is it just a coincidence that this makes my example work?

Also, do I have to use `EPOLLIN` for the ZMQ fd to get all the poll events even if I only send?

**Comment by somdoron** [comment]
In that case, when you are handling the socket after the epoll, do it in a loop, where you exit the loop after the events are none.

**Comment by Kobzol** [comment]
Yes, I process the messages in a loop until I get EAGAIN/EWOULDBLOCK back. So I use something like this:
```cpp
write_ready_callback(socket) {
     // socket.get_events() 
     while (socket.send(...) != EAGAIN);
     // socket.get_events() 
}
```
To avoid the indefinite block of the socket, I have to query `ZMQ_EVENTS` somewhere in this callback. It works if I query them before sending all the messages, it also works if I query them once I get `EAGAIN` (so after the while loop).

That's why I wanted to ask for the specific semantics, when (and where in the callback function) do I have to query `ZMQ_EVENTS` to make sure that the behaviour is correct. The same applies for receiving messages.

**Comment by somdoron** [comment]
@minrk if I remember correctly you have some experience with external eventloop and zeromq. Can you suggest the correct usage ?

**Comment by bluca** [comment]
This is a good writeup that is still valid: https://funcptr.net/2012/09/10/zeromq---edge-triggered-notification/

**Comment by Kobzol** [comment]
Thank you, that was a nice explanation.

So to summarize (for future readers):
1) `ZMQ_FD` should be obtained from a ZMQ socket
2) This fd should be polled for READ readiness (doesn't matter if you want to read or write to the actual ZMQ socket) using edge-triggered mode (so with `EPOLLET` for `epoll).
3) After the fd becomes ready to read, `ZMQ_EVENTS` have to be queried from the ZMQ socket.
- If `ZMQ_POLLIN` is active, as many messages as possible should be read from the socket (using `ZMQ_DONTWAIT`), until `EAGAIN` is returned
- If `ZMQ_POLLOUT` is active, as many messages as possible should be sent to the socket (using `ZMQ_DONTWAIT`), until `EAGAIN` is returned or you run out of messages to send
4) GOTO 2)

Even though it's still a bit of a hard fit for integration with my specific event loop, I'm now at least more certain about how to work with `ZMQ_FD` and `ZMQ_EVENTS`, thank you. If you didn't spot an error or something missing in my summarization, feel free to close this issue.
