### ISSUE TITLE
Socket Design for Asynchronous Callback Theading Model

### ISSUE THREAD

**Issue by smalls12** [zeromq/libzmq#3655]
Hello,
I'm looking for some guidance on how to incorporate zeromq into a system that utilizes an asynchronous callback threading model.

# Issue description
The underlying system provides a callback in a new thread; said thread than must communicate to another part of the system that has been bound and listening on a zeromq TCP socket.

It is well documented that zeromq sockets are not thread safe.

`
Don't share ZeroMQ sockets between threads. ZeroMQ sockets are not threadsafe. Technically it's possible to migrate a socket from one thread to another but it demands skill. The only place where it's remotely sane to share sockets between threads are in language bindings that need to do magic like garbage collection on sockets.
`

Is this still correct with the introduction of Client/Server sockets?

This type of question has been asked before:
https://stackoverflow.com/questions/41941702/one-zeromq-socket-per-thread-or-per-call
https://stackoverflow.com/questions/18139918/using-zmq-socket-in-a-callback-function

I was hoping that some clarification could be provided on the answers to these questions and using `thread_local`.

Also reading from the provided documentation http://api.zeromq.org/4-1:zmq (might not be the latest)

`
Individual ØMQ sockets are not thread safe except in the case where full memory barriers are issued when migrating a socket from one thread to another. In practice this means applications can create a socket in one thread with zmq_socket() and then pass it to a newly created thread as part of thread initialization, for example via a structure passed as an argument to pthread_create().
`

Can this be expanded upon in regards to `memory barrier`.

I appreciate any clarification that can be provided.

Note: I have been playing around with multiple different solutions including open/closing sockets repeatedly as well as opening a socket on one thread for use by other threads that is protected by a mutex.

My concern is that any success I might be seeing won't work at scale

**Comment by jean-airoldie** [comment]
From the master docs http://api.zeromq.org/master:zmq-socket:

> Following are the thread safe sockets: * ZMQ_CLIENT * ZMQ_SERVER * ZMQ_DISH * ZMQ_RADIO * ZMQ_SCATTER * ZMQ_GATHER

Note that these sockets are all part of the DRAFT API.

**Comment by bluca** [comment]
Mutex will not work as they are used on one side only, and memory barriers are not a full protection especially on architectures without cache coherency. As mentioned in the previous comment, there are specific thread-safe sockets - others are just not.

**Comment by smalls12** [comment]
Should this be updated in the master docs?

> ØMQ has both thread safe socket type and not thread safe socket types. Applications MUST NOT use a not thread safe socket from multiple threads except after migrating a socket from one thread to another with a "full fence" memory barrier.

The thread safe sockets are definitely a solution for this design pattern.
My concern however is that they are in draft mode still.

The opening/closing of sockets repeatedly within these callbacks is a sufficient design however, just wondering if there was an alternative as there is a certain amount of overhead in doing that.
