### ISSUE TITLE
4.3.x : segfault on sending data from XSUB to XPUB

### ISSUE THREAD

**Issue by freemanix** [zeromq/libzmq#3656]
Starting with libzmq 4.3.0, this code crashes:

```
int main()
{
    zmq::context_t ctx;

    zmq::socket_t publisher(ctx, ZMQ_XPUB);
    publisher.bind("inproc://test");

    zmq::socket_t receiver(ctx, ZMQ_XSUB);
    receiver.connect("inproc://test");

    zmq::message_t subscribe(1);
    *static_cast<unsigned char *>(subscribe.data()) = 2;
    receiver.send(subscribe);

    zmq::message_t receive;
    publisher.recv(&receive);

    return 0;
}
```
Note that instead of activating subscription (1) or cancelling it (0), I simply send user data (2). The problem is that this code for handling user messages comming upstream ***never*** executes:

https://github.com/zeromq/libzmq/blob/c737e5720fc50c206c588c9766377ed975d266fe/src/xpub.cpp#L114-L123

Instead, the above `else` is activated, but it just skip the data processing if first byte is not 0 or 1. Also, this `else` kind of duplicates above `if`. 

As a result, my code which needs to send upstream data from XSUB to XPUB does not work with libzmq 4.3.0 or higher. Any way how to resolve this?

**Comment by bluca** [comment]
Thanks for the report, regression introduced by https://github.com/zeromq/libzmq/pull/3168 PR pending
