### ISSUE TITLE
Idea: Configurable event forwarding through zmq_msg

### ISSUE THREAD

**Issue by jean-airoldie** [zeromq/libzmq#3658]
Any opposition to adding ZMQ_EVENT_SUBSCRIBED & ZMQ_EVENT_UNSUBSCRIBED to the `zmq_socket_monitor_versioned` 2? These events would provide the specific topic of that was subscribed / unsubscribed to. This events would be generated by `PUB/SUB` and `RADIO/DISH` sockets.

As a side effect, this would effectively remove for the need for a `XRADIO/XDISH` pattern.

**Comment by sigiesec** [comment]
I am not sure. 

This is an alternative design providing the same functionality as an XPUB socket (and a new XRADIO socket), which provides the events via the socket. It does not, however replace the XSUB (and a new XDISH socket), as these process subscription messages sent via the socket, which is somewhat symmetrical to the XPUB socket behaviour. But maybe there are different use cases for which monitoring events are more appropriate (e.g. when the only action done is to forward the events to an overall application logging or monitoring service). Is this what you have in mind?

**Comment by jean-airoldie** [comment]
I had two things in mind:
* Triggering an application level function when a new subscription is received (like a welcome message but better)
* Proxying a subscription at the application level with RADIO/DISH. e.g. Radio receives a subscription, proxies the subscription to another Dish socket, etc.

More generally, I am finding the stateless nature of zmq sockets to be problematic. I want to allow sockets send/recv operations to be interrupted by events chosen by the user. Essentially, every socket would be paired with a monitor socket so that, for instance a `send` event can be interrupted by a disconnection event for instance. This is really usefull when you need application level code that is linked to socket state (even thought zmq wants to hide its internal state).

**Comment by jean-airoldie** [comment]
Conceptually, all the problems I have with zmq currently can be solved by exposing so state via the `zmq_socket_monitor` API. However I understand that this is opposite to the original ideology of the lib.

**Comment by somdoron** [comment]
I would recommend taking a look at the malamute project source code, the
state issue is solved nicely without any monitoring.

**Comment by jean-airoldie** [comment]
@somdoron Could you implement a application session linked to the lifetime of a connection using malamute? For instance I need a deadman switch that triggers a soon as a client socket disconnect (even if it later reconnects). How can this be achieved without monitoring?

**Comment by somdoron** [comment]
Applicative ping-pong, this is what malamute is doing. Also if I remember correctly, router has a notification through msg.

We can do the same for SERVER and maybe even for RADIO/DISH.

Also with pub/sub you can utilize the XPUB_MANUAL to do this, with this you can subscribe to a token, the XPUB decode the unique token the do the subscription for the client. When you get unsubscribe for the token, you know the connection is dead.

**Comment by jean-airoldie** [comment]
Sure this works, but how is it better than via monitoring? With monitoring, you have a better latency and you don't need to schedule an second event loop on top of libzmq just to do the ping-pong. It make the client code simpler if the ping-pong is only done as the libzmq level.

libzmq already detects the disconnection, but does not inform the user, just for the sake of being stateless. I don't understand why transmitting this information to the user is necessarily bad.

**Comment by somdoron** [comment]
I myself not a big fan of the monitoring and it is working.
I prefer notification through the zmq_msg class.
However, the current way it is working is a bit hacky.

For SERVER socket we can use a special type for the zmq_msg, like zmq_msg_connect/zmq_msg_disconnect. The actual data can be empty as we already have the routing id.

**Comment by jean-airoldie** [comment]
Interesting, thats the general idea I'm looking for.

Do you think it would make sense for the newer socket types to more generally receive events using the zmq_msg? I'm thinking of a configurable behavior similar to zmq_socket_monitor, where the user would create the socket and would configure what events he wants to receive using a mask in a setsockopt option. This way, the user could decide whether the socket should be stateless, or whether he wants to be notified of specific events.

This would allow the user to achieve complex behavior linked to updates in the state of the socket. For instance, this would allow the user to:
* Detect when the connection was established, as opposed to the current behaviour waiting a random amount of time (in undirectional communication).
* Detect misconfigured ZAP credentials.
* Link application logic to the lifetime of a session with a client socket.
* Detect new clients.
* Etc.

**Comment by somdoron** [comment]
I would really like that, however, I would limit the events to accepted, connected and disconnected.

For the case of connected, it would only be relevant when immediate option is set.

I would also add a zmq_connect_peer that would return the routing id of the peer, that way you will be able to correlate the events to the peer.

**Comment by jean-airoldie** [comment]
> I would limit the events to accepted, connected and disconnected.

What would be the reasoning behind not allowing events such as sub & unsub or handshake errors?

I guess you would add metadata field on the message which indicates whether it is an event message, and what variant it is. Then depending on the variant, the content of the message might contain additional metadata.

**Comment by somdoron** [comment]
> What would be the reasoning behind not allowing events such as sub & unsub or handshake errors?

Those fine as well, I was thinking on the SERVER socket to start with. For sub/unsub we can utilize the `leave` and `join` already existed msg types, which will allow to forward them directly to an XDISH.

https://github.com/zeromq/libzmq/blob/master/src/msg.hpp#L200

Regarding the msg, no need for metadata, we would need a new msg_type for events:
https://github.com/zeromq/libzmq/blob/master/src/msg.hpp#L203

And a new struct in the msg union:
https://github.com/zeromq/libzmq/blob/master/src/msg.hpp#L212

And of course new constants on the zmq.hpp for the different events.

As for functions, I would add:
`zmq_msg_event` to get the event, this should be smart, in the can of JOIN and LEAVE msg types, we can return -1 for a none event.

`zmq_connect_peer` which return the peer routing_id instead of result. We can also use the existing zmq_connect with a new socket option, to return a routing id instead of result.

Currently on the SERVER socket is managing a unique id for each peer.
If we want to have a routing id on each event we would need to assign a routing id to new peers on all new socket type, which I like.

We might want to limit the routing ids to positive-none-zero only, right now negative is allowed, I think.

**Comment by jean-airoldie** [comment]
> zmq_msg_event to get the event, this should be smart, in the can of JOIN and LEAVE msg types, we can return -1 for a none event.

Agreed.

> Regarding the msg, no need for metadata, we would need a new msg_type for events:

A was thinking about, for instance, including the group joined as the message content for a join / leave event on a RADIO socket. This might be the current behavior of join / leave messages, I dont' remember.

> zmq_connect_peer which return the peer routing_id instead of result. We can also use the existing zmq_connect with a new socket option, to return a routing id instead of result.

Right so CLIENT sockets would use this function to connect to a server SOCKET so that they can retrieve the routing_id they were assigned. And using this routing_id they could correlate events with the corresponding SERVER they are connected to. Would collision be possible in this case? Say a client socket is connected to 2 SERVERs and by misfortune, they both assign the same routing_id? Maybe the remote SERVER IP could be provided as well to prevent that?

**Comment by somdoron** [comment]
We don't really forward the routing id from the SERVER. The client would generate its own routing ids.
It is not possible and doesn't really make sense to forward the routing ids from the server.

We only need it to correlate the events.

**Comment by somdoron** [comment]
So connecting to two different SERVER would generate two unique routing ids, without any relation to the SERVER assigned routing ids. routing ids are always local.

**Comment by jean-airoldie** [comment]
We could call those notifications instead of events to prevent conflicting with the ZMQ_EVENT_* namespace used by the socket_monitor API.

**Comment by somdoron** [comment]
Agreed

**Comment by jean-airoldie** [comment]
How would notification messages behave in regards highwater marks? I guess the simplest way would be to drop messages if the hwm is reached, but that might not be ideal.

**Comment by somdoron** [comment]
They are bypassing high watermark.
Because they are generated at the user thread.

So we need a queue of notification in each socket type, notification are
inserted into that queue. When user call recv we first check if a
notification is pending on the notification queue and dequeue if pending.
Otherwise regular socket type logic.

All notifications can be generated at the user thread by the socket type
classes, by enqueing notification on xattachedpipe and pipeterminated (we
call the notification the same, attached and terminated).

**Comment by jean-airoldie** [comment]
> For the case of connected, it would only be relevant when immediate option is set.

The immediate option would not really be required anymore, not that I think about it. All you would need to do is subscribe to notifications for connection events, connect to a remote socket then call `recv` blocking. You are guaranteed that the first message you will receive will be a connection notification. Then you can proceed as normal.

**Comment by somdoron** [comment]
For this to work immediate must be set to true, otherwise the xattachedpipe will be called on connect, before transport is actually connected.

**Comment by jean-airoldie** [comment]
I think I'll try my hand at a PR, but I'll need some mentoring. I'll write a pseudo-rfc in the PR so that I can understand exactly what needs to be done.
