### ISSUE TITLE
Can't build libzmq with libsodium

### ISSUE THREAD

**Issue by raphaelcfernandes** [zeromq/libzmq#3667]
*Please use this template for reporting suspected bugs or requests for help.*

# Issue description

I'm trying to add libcurve to my Zyre project and I read that I need libsodium as a dependency. However when I try to add libsodium to libzmq it gives me the error (actual result section). Libsodium is already installed following the instructions here (https://libsodium.gitbook.io/doc/installation). Am I missing something?

# Environment 

* libzmq version (commit hash if unreleased): 
* OS: Linux

# Minimal test code / Steps to reproduce the issue

1.  ./configure --with-libsodium

# What's the actual result? (include assertion message & call stack if applicable)

checking for sodium... no
./configure: line 417: test: then: integer expression expected
configure: error: run
./configure: line 306: return: then: numeric argument required
./configure: line 316: exit: then: numeric argument required

# What's the expected result?

Success build with libsodium

**Comment by sigiesec** [comment]
Which shell is your /bin/sh?

**Comment by raphaelcfernandes** [comment]
If I understood the question, my /bin/sh is a symbolic link to /bin/bash

**Comment by bluca** [comment]
platform?

**Comment by raphaelcfernandes** [comment]
Fedora 30 x86_64

**Comment by bluca** [comment]
No need to rebuild anything manually, we provide RPM repositories for fedora 30:

https://software.opensuse.org/download.html?project=network%3Amessaging%3Azeromq%3Agit-draft&package=zyre-devel
