### ISSUE TITLE
 future plan for zmq_proxy_steerable method

### ISSUE THREAD

**Issue by mortezaipo** [zeromq/libzmq#3675]
*Please use this template for reporting suspected bugs or requests for help.*

# Issue description
Is there any plan exists for the future of `zmq_proxy_steerable` method? Because want I've understood, we can have the `zmq_proxy` method with 4 arguments instead of calling `zmq_proxy_steerable`.

# Environment
Any

* libzmq version (commit hash if unreleased): e756743a12468fabe0141f979aa2da407c1e69ad
* OS: GNU/Linux

# Minimal test code / Steps to reproduce the issue

1.  

# What's the actual result? (include assertion message & call stack if applicable)

# What's the expected result?

**Comment by bluca** [comment]
zmq_proxy's signature cannot be changed as it would be a stable API breakage, so zmq_proxy_steerable is here to stay. It is also a stable API.
