### ISSUE TITLE
zmq cannot work on windows xp (if_indextoname IPHILPAPI.DLL)

### ISSUE THREAD

**Issue by myhevenisqing** [zeromq/libzmq#3693]
*Please use this template for reporting suspected bugs or requests for help.*

# Issue description

# Environment

* libzmq version (commit hash if unreleased): 
* OS: 

# Minimal test code / Steps to reproduce the issue

1.  

# What's the actual result? (include assertion message & call stack if applicable)

# What's the expected result?

**Comment by bluca** [comment]
It was already fixed a while ago:

https://github.com/zeromq/libzmq/blob/master/src/ip_resolver.cpp#L584

**Comment by myhevenisqing** [comment]
thanks a lot

**Comment by myhevenisqing** [comment]
i have try the newest code, still cannot run in windows xp.
