### ISSUE TITLE
zmq cannot work on windows xp

### ISSUE THREAD

**Issue by myhevenisqing** [zeromq/libzmq#3694]
It was already fixed a while ago:

https://github.com/zeromq/libzmq/blob/master/src/ip_resolver.cpp#L584

_Originally posted by @bluca in https://github.com/zeromq/libzmq/issues/3693#issuecomment-536190131_

sorry,i tryed the newest code, is still not fix zmq work on window xp. due to windows xp is not support the if_indextoname.

**Comment by sigiesec** [comment]
Can you provide more details on this? What are you doing? Are you experiencing problems building on Windows XP, or are you using a DLL built on a newer Windows version on Windows XP?

**Comment by myhevenisqing** [comment]
i use zeromq dll on work on windows xp sp3,but crash about: if_indextoname unable to locate program input point in IPHLPAPI.DLL

**Comment by myhevenisqing** [comment]
i bulid dll on window 10, but need work on window xp.

**Comment by bluca** [comment]
You need to build it on windows xp if you want to use it on windows xp

**Comment by sigiesec** [comment]
@bluca That shouldn't be necessary. The target SDK version can already be specified by setting the CMake variable ZMQ_WIN32_WINNT, but this particular guard uses a custom define ZMQ_HAVE_WINDOWS_TARGET_XP which was set only from the deprecated https://github.com/zeromq/libzmq/blob/92e3226869258e52b00727ac1d8bed82e357faa9/builds/deprecated-msvc/vs2015_xp/platform.hpp#L5, but is never set via CMake. This must be fixed.

@myhevenisqing For the moment, can you please try to edit the CMakeLists.txt file locally and add `add_definitions(-DZMQ_HAVE_WINDOWS_TARGET_XP)` there? Then you should be able to build on Windows 10 and run on Windows XP.

**Comment by myhevenisqing** [comment]
@sigiesec  in my job,i build zeromq dll in vs2010. so,I'm afraid that won't work .

**Comment by sigiesec** [comment]
@myhevenisqing You use CMake to generate a VS solution, don't you?

**Comment by sigiesec** [comment]
@myhevenisqing It turned out there were a few more incompatibilities with Win XP. With the changes in #3716, these will be fixed. You can then generate a VS solution that target Win XP by running `cmake -DZMQ_WIN32_WINNT=0x501 <libzmq source folder>`.
