### ISSUE TITLE
_retired vector in epoll.cpp is not thread-safe

### ISSUE THREAD

**Issue by louishust** [zeromq/libzmq#3712]
*Please use this template for reporting suspected bugs or requests for help.*

# Issue description

`_retired` variable in `src/epoll.cpp` is removed in `loop`, and user thread can call `rm_fd` to modify the `_retired` vector, so the `_retired` vector is not thread-safe.

# Environment

* libzmq version (commit hash if unreleased): 
* OS: 

# Minimal test code / Steps to reproduce the issue

1.  

# What's the actual result? (include assertion message & call stack if applicable)

# What's the expected result?

**Comment by bluca** [comment]
Hi, do you have an example where rm_fd is called from something other than the I/O thread?

**Comment by sigiesec** [comment]
It is actually checked via https://github.com/zeromq/libzmq/blob/master/src/epoll.cpp#L110 that rm_fd is only called from the I/O thread.

**Comment by louishust** [comment]
yes, you are right, I will close this issue.
