### ISSUE TITLE
Deb package for Ubuntu 19.10 doesn't exist in the repository.

### ISSUE THREAD

**Issue by mortezaipo** [zeromq/libzmq#3718]
*Please use this template for reporting suspected bugs or requests for help.*

# Issue description
Deb package for Ubuntu 19.10 doesn't exist in the repository:
http://download.opensuse.org/repositories/network:/messaging:/zeromq:/release-stable/xUbuntu_19.10/

Also the key: https://download.opensuse.org/repositories/network:messaging:zeromq:release-stable/xUbuntu_19.10/Release.key

# Environment

* libzmq version (commit hash if unreleased): 
* OS: Linux/Ubuntu

# Minimal test code / Steps to reproduce the issue

1.  

# What's the actual result? (include assertion message & call stack if applicable)
Resource is no longer available!

# What's the expected result?

**Comment by bluca** [comment]
Added
