### ISSUE TITLE
running test_pair_tcp_cap_net_admin without sudo access breaks terminal session

### ISSUE THREAD

**Issue by bill-torpey-ullink** [zeromq/libzmq#3725]
# Issue description

running test_pair_tcp_cap_net_admin without sudo access breaks terminal session

# Environment

* libzmq version (commit hash if unreleased): e5a7f2eb568b5655699a16ae9867fe656b42b533
* OS: CentOS 7

# Minimal test code / Steps to reproduce the issue

1.  run "make test" from a user w/o sudo access

# What's the actual result? (include assertion message & call stack if applicable)
test_pair_tcp_cap_net_admin times out, and terminal session is unusable

# What's the expected result?
Don't run test if user doesn't have sudo

**Comment by bluca** [comment]
@sigiesec we should probably add an option for this in cmake
