### ISSUE TITLE
router-dealer，server No message received,

### ISSUE THREAD

**Issue by chengqian1521** [zeromq/libzmq#3730]
*Please use this template for reporting suspected bugs or requests for help.*

# Issue description
In router-dealer pattern,client is dealer, server is router.
client send tick message to server.At first it was normal
An hour later server no message received.
Restarting the client has no effect.
But I changed client router_id,server can recv message.
use old router id.  server no message  received.
Eventually, the server restarted and returned to normal
what's the reason.
The problem recurred only once,Never to be seen again after restart sever

# Environment
server: centos7.6/go
client: windows server 2016/c++

* libzmq version (commit hash if unreleased): 4.3.2
* OS: 

# Minimal test code / Steps to reproduce the issue

1.  

# What's the actual result? (include assertion message & call stack if applicable)

# What's the expected result?

**Comment by sigiesec** [comment]
Unfortunately, the problem report does not contain sufficient information to reproduce the issue and is therefore not actionable. Feel free to reopen the issue with more information, ideally a minimal test case that reproduces the issue. Thanks for your understanding!
