### ISSUE TITLE
How to build with DRAFT API with Homebrew on macOS?

### ISSUE THREAD

**Issue by kakyoism** [zeromq/libzmq#3732]
With community help, I now can enable DRAFT API cppzmq/libzmq with vcpkg on Windows. But how do we enable this on macOS with Homebrew? Do we have special build switches like 

```
--with-draft-api
```

or something like that?

**Comment by bluca** [comment]
This is the formula and where it's maintained: https://github.com/Homebrew/homebrew-core/blob/master/Formula/zeromq.rb

It doesn't look like there's an option, you'll need to ask the developers/maintainers for it or provide a PR.
