### ISSUE TITLE
Sending multipart messages from XSUB to XPUB

### ISSUE THREAD

**Issue by drolevar** [zeromq/libzmq#3733]
# Issue description
Consider the following scenario: XSUB socket sends a multipart message to the XPUB socket.
What should be the correct behavior:
1. Any of the parts can be considered as a subscribe message (current behavior).
2. No parts should be considered as a subscribe message.
3. First part should be considered as a subscribe message.

Current implementation is considering the first byte of each part as a potential subscribe/unsubscribe, which IMO makes use of multipart messages very cumbersome in this scenario.

# Environment

* libzmq version (commit hash if unreleased): af86d93d5f9634c5f28664c667510b044f2a149c
* OS: Ubuntu 19.10

**Comment by somdoron** [comment]
we could support that, in case the first part is not a subscription or unsubscription all following parts will be ignored and just forwarded to the user.

**Comment by drolevar** [comment]
@somdoron What should be the behavior if the first part **is** a subscription/unsubscription and there are more parts?

**Comment by bluca** [comment]
Fixed by https://github.com/zeromq/libzmq/pull/3741

**Comment by bluca** [comment]
@somdoron is this covered by the ZMTP RFC?

**Comment by somdoron** [comment]
I wouldn't change the behavior for frames that follow subscribe/unsubscribe as it might break existing systems that want to chain subscriptions (for some reason).

**Comment by bluca** [comment]
Yeah, that makes sense

**Comment by drolevar** [comment]
@somdoron I can implement it in a way that if the first frame is **NOT** a subscription/unsubscription, then all the rest are also treated in the same way. However, the logic will be slightly more complicated.

**Comment by drolevar** [comment]
@somdoron @bluca @mrseanmorris So how should I proceed?

**Comment by somdoron** [comment]
make a pr that only frames that follow none sub/unsub are forwarded.
