### ISSUE TITLE
Memory problems

### ISSUE THREAD

**Issue by knightswim** [zeromq/libzmq#3737]
*Please use this template for reporting suspected bugs or requests for help.*

# Issue description
Using route for asynchronous transmission will consume a lot of memory in the high-traffic scenario. When the traffic is slow, the memory will be released very slowly, so that other applications of the system cannot apply for memory.

# Environment
ubuntu1604

* libzmq version (commit hash if unreleased): 4.1.7
* OS: 

# Minimal test code / Steps to reproduce the issue

1.  

# What's the actual result? (include assertion message & call stack if applicable)
 the memory will be released very slowly

# What's the expected result?
Memory fast recovery

**Comment by DoriHp** [comment]
@knightswim Did you resolve this problem? I faced with the same once
