### ISSUE TITLE
after zmq_send fail，and then disconnect and connect recover

### ISSUE THREAD

**Issue by xiaoyingSha** [zeromq/libzmq#3739]
*Please use this template for reporting suspected bugs or requests for help.*
   
# Issue description
hi，i have c code ,sever and client run in different board, we use secureCRT to test; when sever exit because of some reason ,client send some message to sever always,about 3 times 10 second;
After we recover server,sever recv any  msg;And then ,we check client sending failure always；
After Gdb set some flag，we made client disconneted ，and then connect ，sever can recv msg；

# Environment

* libzmq version (commit hash if unreleased): 4.2.1
* OS: centos6.5

# Minimal test code / Steps to reproduce the issue

1.  client：  
void *Zmq_ClientInit(UINT32 clientid)  
{   
    void *context = NULL;	
    void *requester = NULL;
    char connectadd[30] = {0}, add[24] = {0};
    tClient_zmq_context_info *p = NULL;
	UINT32 timeout = ZMQ_TIMEOUT;
	INT32 immediate = 1;
	INT32 relexted = 1;

	int re = 0;

    p = &(gClientZmqInfo18000[clientid]);	

    if(p->zmq_context || p->zmq_socket)
    {
        return NULL;
    }
	
    context = zmq_ctx_new();

    if(!context)
    {
        return NULL;
    }
    requester = zmq_socket (context, ZMQ_REQ);
    
    if(!requester)
    {
        zmq_term (context);
        return NULL;
    }
	zmq_setsockopt(requester,ZMQ_SNDTIMEO,&timeout,sizeof(timeout));
	zmq_setsockopt(requester,ZMQ_RCVTIMEO,&timeout,sizeof(timeout));
	zmq_setsockopt(requester,ZMQ_IMMEDIATE,&immediate,sizeof(immediate));
	zmq_setsockopt(requester,ZMQ_REQ_RELAXED,&relexted,sizeof(relexted));
	
       if(gpAddrSeg->mgmtMasterCollectorAddr !=0)
       {     	
	   ultoIpStr2( gpAddrSeg->mgmtMasterCollectorAddr, (char *)&add );
	
           sprintf(connectadd, "tcp://%s:18000",(char *)&add);	
   	}
        else
        {
           sprintf(connectadd, "tcp://192.168.0.49:18000");
        }

        re = zmq_connect (requester, connectadd);   
        p->zmq_context = context;
        p->zmq_socket = requester;
        p->ipaddress = gpAddrSeg->mgmtMasterCollectorAddr;

        return requester;
}

INT32 Zmq_ClientSend(UINT32 clientid,char *msg,UINT32 len,UINT32 flag)  
{
      INT32 ret = 0;
      char connectadd[30] = {0}, add[24] = {0};
      tClient_zmq_context_info *p = NULL; 
      p = &(gClientZmqInfo18000[clientid]);	
      if(!(p->zmq_socket))
      {
          p->send_fail++;
          return ERROR;
      }
      /*通过shell会修改server的ip地址。发送报文之前需要判断server的ip地址是否与创建的socket ip地址相同*/
      if(gClientZmqInfo18000[clientid].ipaddress != gpAddrSeg->mgmtMasterCollectorAddr)
      {
        TME_TRCMSG(1,"zmq client send ip change : clientid %d, old ip %x newip %x ",
        clientid,gClientZmqInfo18000[clientid].ipaddress,gpAddrSeg->mgmtMasterCollectorAddr );
        ultoIpStr2( gClientZmqInfo18000[clientid].ipaddress, (char *)&add );	
        sprintf(connectadd, "tcp://%s:18000",(char *)&add); 
        zmq_disconnect (gClientZmqInfo18000[clientid].zmq_socket, connectadd);	

        ultoIpStr2( gpAddrSeg->mgmtMasterCollectorAddr, (char *)&add ); 
        sprintf(connectadd, "tcp://%s:18000",(char *)&add); 
        zmq_connect (gClientZmqInfo18000[clientid].zmq_socket, connectadd);  
        p->ipaddress = gpAddrSeg->mgmtMasterCollectorAddr;		
      }
      ret = zmq_send(p->zmq_socket,msg,len,flag);
      if(ret == ERROR)
      {
          p->send_fail++;    // counter increase
      }
      else
      {
          p->send_msg++;
      }
      return ret;
}
2.sever：  
ps：mode =1，other arg don,t care
void *Zmq_ServerInit(void *serverInfo,UINT32 mode,UINT32 slotid,UINT32 port,UINT32 workerNum,char *workername)
{	 
		void *context = NULL;
		void *server = NULL;
		char addr[50] = {0};		
		tServer_zmq_context_info* p = NULL; 
		UINT32 timeout = ZMQ_TIMEOUT;
		UCHAR *pIp = NULL;
		int ret = 0;
		INT32 relexted = 1;
		
		p = (tServer_zmq_context_info *) serverInfo;

	        context = zmq_ctx_new ();
		if(!context)
		{
			return NULL;
		}
	
		if(ZMQ_SERVER_WORKER == mode)
		{
			server = zmq_socket (context, ZMQ_ROUTER);
		}
		else
		{
			server = zmq_socket (context, ZMQ_REP);
		}
	
		if(server == NULL)
		{
			zmq_term (context);
			return NULL;
		}

	         zmq_setsockopt(server,ZMQ_SNDTIMEO,&timeout,sizeof(timeout));  
	        zmq_setsockopt(server,ZMQ_RCVTIMEO,&timeout,sizeof(timeout));  
		zmq_setsockopt(server,ZMQ_REQ_RELAXED,&relexted,sizeof(relexted));  

		pIp = (UCHAR *)&gCtrlEth3IpAdd;

		sprintf(addr, "tcp://%u.%u.%u.%u:%d", *(pIp+3),*(pIp+2),*(pIp+1),*pIp,port);
		
		ret = zmq_bind(server, addr);

		if(ret == -1)
		{
		    TME_TRCMSG(1,"zmq server bind %s failed. errno %d ",addr,errno);
		}
		else
		{
		    TME_TRCMSG(1,"zmq server bind %s OK ",addr,addr);
		}
	
		if(ZMQ_SERVER_WORKER==mode)
		{
			void *workers = zmq_socket(context,ZMQ_DEALER);
			
			if(workers == NULL)
			{
				zmq_close(server);
				zmq_term (context);
				return NULL;
			}
	
			zmq_bind(workers,workername);	
			p->mode = ZMQ_SERVER_WORKER;
			p->workernum = workerNum;
			p->worker_socket = workers;
		}
		else
		{
		    /*非worker方式，信息存在第一个worker中*/
			p->worker_info[0].zmq_socket = server;
			p->mode = ZMQ_SERVER_NORMAL;
		}
		
		p->context = context;
		p->zmq_socket = server;
		
		return server;
}

# What's the actual result? (include assertion message & call stack if applicable)
client dont have any connection,"netstat -an|grep 18000",there is no  "ESTABLISHED" connection;
zmq_send return -1,errno 11

# What's the expected result?
before send，how can i got the connect info? success or failure；
is there something wrong in my code？
the problem is zmq_send msg too much in fifo？

**Comment by mrvn** [comment]
Please indent the code parts consitently so they show up as single code blocks (those blocks with darker background).
