### ISSUE TITLE
Monitor socket seems to prevent auto reconnection

### ISSUE THREAD

**Issue by donqui** [zeromq/libzmq#3745]
Hi,

# Issue description
I'm having issues caused by the monitor socket, not sure if this is a libzmq or pyzmq issue.

This is my scenario:

- server starts listening on a ROUTER socket
- client starts and connects to the server via DEALER socket that has a monitor socket created
- messages are exchanged successfully
- server crashes and is off-line for a couple of minutes
- client is still sending messages like the socket is open
- server comes up and the client is not able to reach it, i.e. the reconnection never happens

What I've noticed is that if I do not open the monitor socket on the client side, reconnection happens, but if the monitor socket is opened it never does and it becomes unresponsive in a way. One more thing I noticed is that the reconnection happens if the server comes back online fast, some measurements showed that if the server is down less than ~90seconds, there is no issue.

Have you maybe seen this behaviour, is this a bug or am I doing something wrong?

# Environment
OS: Ubuntu 16.04
Python version: 3.5
libzmq version: 4.3.2.
pyzmq version: 18.1.0.

# Minimal test code / Steps to reproduce the issue
Here is a test script I used to reproduce this:
https://github.com/donqui/zmq-sandbox/blob/master/client_server.py. 

- I ran one instance on one machine, and another on a different machine
- They start sending data to one another
- I stop one of the scripts while the other continues to send messages
- When monitor socket opened and both sides are disconnected for ~90s libzmq is unable to reconnect. If there is no monitor everything works fine

# What's the actual result? (include assertion message & call stack if applicable)
- Sockets are not reconnected when the peer comes online.

# What's the expected result?
- Reconnection should happen automatically.

**Comment by mrvn** [comment]
I don't see any code that reads from the monitor socket. Could it simply be that after 90s the send/recv queue of the monitor socket is full and blocks the notification of a reconnect attempt?

**Comment by donqui** [comment]
There is no code reading from the monitor socket. The sole existence of the monitor socket seems to cause the issue.

> Could it simply be that after 90s the send/recv queue of the monitor socket is full and blocks the notification of a reconnect attempt?
I honestly do not know, I am by no means an expert on this topic. Is it going to be filled up in the case of a disconnected socket on he other end?
