### ISSUE TITLE
Router not receiving message from Dealer

### ISSUE THREAD

**Issue by Cjen1** [zeromq/libzmq#3750]
*Please use this template for reporting suspected bugs or requests for help.*

# Issue description
This is specifically in the implementation of `ocaml-zmq` that I've found this.

I have a router bound to a port on loopback, and a dealer which connects to it.

The dealer sends the packet (I have a tcpdump which appears to show it correctly being sent), however the router never receives it.

The library uses the events library and when something should have arrived, `socket.getsocketopt(socket, ZMQ_EVENTS, &event, &event_size)` returns just ZMQ_POLLOUT.

```
 CAMLprim value caml_zmq_get_events(value socket) {
      CAMLparam1 (socket);
      uint32_t event = 0;
      size_t event_size = sizeof (event);
      int result = zmq_getsockopt (CAML_ZMQ_Socket_val(socket),
                                   ZMQ_EVENTS,
                                   &event,
                                   &event_size);
      caml_zmq_raise_if(result == -1, "zmq_getsockopt");
      printf("C: %x", event);
      int event_type = 0; /* No_event */
      if (event & ZMQ_POLLIN) {
          event_type = 1; /* Poll_in */
          if (event & ZMQ_POLLOUT) {
              event_type = 3; /* Poll_in_out */
          }
      } else if (event & ZMQ_POLLOUT) {
          event_type = 2; /* Poll_out */
      } else if (event & ZMQ_POLLERR) {
          event_type = 4; /* Poll_error */
      }
      CAMLreturn (Val_int(event_type));
  }
```

In the above code, the function only has `event_type = 2`.

An additional point is that the fd for the router does not become readable during this, I understand that the fd should be edge detected, i.e. on becoming readable or becoming unreadable.

If a tcpdump of the communication would be beneficial let me know, mainly I'm looking for how to debug this.

# Environment

* libzmq version (commit hash if unreleased): 4.3.2
* OS: Ubuntu

# Minimal test code / Steps to reproduce the issue

1.  Have a router socket established for a while ~10s.
2. Connect to it via a dealer socket and send a message.

# What's the actual result? (include assertion message & call stack if applicable)
Socket event doesn't update, and fd doesn't become readable.

# What's the expected result?
Socket event updates, and fd becomes readable.

**Comment by Cjen1** [comment]
Turns out that if multiple socket identities collide and are both connecting to the router, it will not update the `fd` or set `POLL_IN`.

**Comment by caicaiking** [comment]
how can solve this issue? set any option on the router socket?
