### ISSUE TITLE
Cannot link msvc libzmq to g++ xeno project inside Eclipse

### ISSUE THREAD

**Issue by flok** [zeromq/libzmq#3762]
*Please use this template for reporting suspected bugs or requests for help.*

# Issue description
Cannot link the msvc library to the g++ xenomai project

# Environment

* libzmq version (commit hash if unreleased): 3e7995f7f73fed6bb1ed6ecfd3a440d5772e5457
* OS: Windows 10 x64

# Minimal test code / Steps to reproduce the issue

1.  create libzmq VS 2019 Solution with "cmake .." inside build folder
2. compile libzmq with VS 2019 
3. include header inside Eclipse and add the libzmq.lib directory
4. compiling xenomai gcc project fails with "undefined reference to .." on all functions of libzmq

# What's the expected result?
linking the library dynamically or static inside Eclipse 

I'm a beginner with this stuff, if other things are needed i will provide them as needed

**Comment by sigiesec** [comment]
Are you building/using a shared or static libzmq? If you use a static libzmq library, you need to define ZMQ_STATIC when including `zmq.h`

I am not sure as well what you mean by "add the libzmq.lib directory". To link against a library, it is not sufficient to specify the directory of the library, but you also need to specify the name of the library in the link dependencies. I am not familiar with Eclipse, so I cannot give more specific advice on how to configure that.

If this doesn't help, please include more specific information on the steps to reproduce, and include the exact linker error messages, and preferably the linker command line.

**Comment by flok** [comment]
Thanks for the reply @sigiesec , since my question i got fairly good progress. 

The xenomai project inside Eclipse depends on gcc/g++. I finally got it to compile with zmq by using a static library (.a) from a linux 14.04 'apt-get install libzmq3-dev' installation (14.04 is necessary cause the system depends on this old binutils version(2.24) and upgrading it is not possible). 
The only question that i now have is how can i validate that the libzmq, libsodium, libpgm .a files are linked statically and not dynamically? I couldn't really find any infos or cmd tools online that gives me this info.
Also if i define ZMQ_STATIC into my Eclipse Project g++ preprocessor, the size of the generated file does not change to before without the define.

**Comment by sigiesec** [comment]
I somehow haven't read your original question properly, but I am now somewhat more confused: In your original question, you wrote you are on Windows, now you write you are on Linux? I don't know what xenomai is. On Linux, a `.a` file is always a static library, however, on Linux, you also don't need to define `ZMQ_STATIC`, it doesn't make any difference there. On Windows, a `.lib` file can be either a static library, or an import library for a DLL/shared library.

**Comment by flok** [comment]
The environment where i try to use libzmq in an application is a msys 2017 variante. sadly there is no way for me to adjust / update it as that would break the application that using the compiled code which has zmq.
xenomai is framework for real-time applications.

so i use the ubuntu 14.04 .a library file of zmq inside that environment. then it should link as static by default since its using g++? that is exactly what i need. Thanks for the informations and help!
