### ISSUE TITLE
Replace uses of strtok by strtok_r

### ISSUE THREAD

**Issue by sigiesec** [zeromq/libzmq#3766]
`strtok` is not thread-safe. The uses of `strtok` in `src/ws_engine.cpp` must be replaced by `strtok_r`.

**Comment by bluca** [comment]
manpage says strtok_r is POSIX.1-2001, will it be available on all platforms?

**Comment by colletted** [comment]
> manpage says strtok_r is POSIX.1-2001, will it be available on all platforms?

I think everywhere except windows. I found this StackOverflow issue on the subject.

[https://stackoverflow.com/questions/9021502/whats-the-difference-between-strtok-r-and-strtok-s-in-c](url)

**Comment by bluca** [comment]
ok, thanks for the PR
