### ISSUE TITLE
How to build for Windows with vs2019?

### ISSUE THREAD

**Issue by sun0929** [zeromq/libzmq#3776]
# I used "open in Visual Studio"  to clone the code to local, but I can't build the project.
# Environment
* libzmq version 4.3.2: 
* OS: win 10

**Comment by sigiesec** [comment]
I am not sure if this is the same what you are doing, but for me, using "File/Open/CMake...", selecting the to top-level CMakeLists.txt file and then running Build All also doesn't work. I get the error:
```C:\src\libzmq-test\src\precompiled.cpp : fatal error C1083: Cannot open compiler intermediate file: 'c:\src\libzmq-test\out\build\x64-debug\precompiled.pch': Permission denied
```

Not sure what is causing this. For now, please run cmake from the command line as described in the INSTALL file, to generate a Visual Studio solution file.

**Comment by sigiesec** [comment]
@sun0929 Can you check if it works with the current master?
