### ISSUE TITLE
Why can't router recv messages from itself ?

### ISSUE THREAD

**Issue by xu-jialei** [zeromq/libzmq#3777]
*Please use this template for reporting suspected bugs or requests for help.*

# Issue description
The router socket cannot receive messages from itself

# Environment

* libzmq version (commit hash if unreleased): 4.3.1
* OS: linux
gcc 4.8.5

# Minimal test code / Steps to reproduce the issue
[router_self.cpp](https://github.com/zeromq/libzmq/files/4053638/router_self.txt)
[router_self2.cpp](https://github.com/zeromq/libzmq/files/4053639/router_self2.txt)
[zhelpers.h](https://github.com/booksbyus/zguide/blob/master/examples/C/zhelpers.h)

# What's the actual result? (include assertion message & call stack if applicable)
Compile and run router_self.cpp will get the result below, no message is received.
In router_self.cpp, only one socket is used.
![image](https://user-images.githubusercontent.com/15306919/72258439-102b3100-3649-11ea-95d8-48e1dc23b8b5.png)

# What's the expected result?
If use two router socket like router_self2.cpp, will get the expected result
![image](https://user-images.githubusercontent.com/15306919/72258494-30f38680-3649-11ea-9b32-fa6923b81b55.png)

**Comment by somdoron** [comment]
Because you set the identity, you want two pipes, however, the two sides have the same identity, they will conflict with each other. The solution is not to use ZMQ_IDENTITY and to enable ZMQ_PROBE or ZMQ_ROUTER_NOTIFY

**Comment by e1ntr** [comment]
Thanks, @somdoron , I'll try it later.
