### ISSUE TITLE
[doc][clarification] Single socket used in multiple poller instances

### ISSUE THREAD

**Issue by std-any-emplace** [zeromq/libzmq#3778]
The documentation states:

> "... zmq_poller_add may not be called multiple times for the same socket (unless zmq_poller_remove has been called for that socket). ..."

Does this statement still hold, when two or more poller instances are created with _zmq_poller_new_ and a single socket is added with _zmq_poller_add_ to each of the poller instances once?
Or rephrased: Can a socket safely be associated with multiple poller instances?

**Comment by somdoron** [comment]
Yes, but only if it thread safe sockets

**Comment by somdoron** [comment]
I think the docs meant don't call add multiple times on same poller. Anyway, thread safe sockets can be associated with multiple pollers

**Comment by std-any-emplace** [comment]
So it works only with sockets of type ZMQ_CLIENT and ZMQ_SERVER?

**Comment by somdoron** [comment]
and radio, dish, scatter and gather

**Comment by std-any-emplace** [comment]
Perhaps add this to the documentation:

"zmq_poller_add registers a new socket with a given poller. _A socket may be added to multiple poller instances as long the socket is thread-safe (Client, Server, Radio, Dish, ...). If it is not, you must make sure to only add it to a single instance and only once._ ..."

As a sidenote: Before you answered my last question, I tried to add a REQ/REP socket-pair to multiple poller instances and it just seemed to work fine for hours without any hint of a problem. Can you elaborate as to why this is not guaranteed to work? Is it platform-dependent?

**Comment by somdoron** [comment]
You are welcome to make the pull request.

Yes, I can explain.

As part of poller work, it is accessing the socket data structures by querying the socket events with zmq_getsockopt with ZMQ_EVENTS, ZMQ_EVENTS is not a read-only operation, it is also causing the socket to process commands. When there are no commands you would see no problem, however, multiple threads trying to handle commands will eventually make the library assert.

**Comment by std-any-emplace** [comment]
Ok, thank you for the information.

Just a last question to be sure: zmq_poll is not subject to the aforementioned effects?

**Comment by somdoron** [comment]
It does. zmq_poll is also calling the ZMQ_EVENTS, you cannot use a none thread safe socket in multiple simultaneous zmq_poll
