### ISSUE TITLE
Static linking exception clarification

### ISSUE THREAD

**Issue by nightlark** [zeromq/libzmq#3787]
## Context
We've been building release binaries for BSD-3 licensed libraries+applications and bundling a copy of the ZeroMQ shared library. On some systems like Windows where there are no rpaths and it's not typical to have ZeroMQ somewhere on the PATH, this is inconvenient, particularly when it comes to packaging for things like pip where in theory bundled shared libraries should be given unique names to avoid conflicts if another module that uses a different version of the ZeroMQ shared library get used together (mainly a problem on Windows).

## The question
Our binary (and source tar) releases don't make any changes to ZeroMQ itself, just use it as a library. Does the static linking exception mean that we are 100% okay to static link ZeroMQ (unmodified) into our own shared libraries and applications so that we can have a standalone binary/library that doesn't require copying a separate ZeroMQ library along with it?

From the [FAQ](http://wiki.zeromq.org/area:faq) it seems like the answer is yes, but we want to be completely sure before making a change to static linking in our release builds.

(#2376 would be ideal, but it seems like that could become an indefinite wait for responses.)

**Comment by bluca** [comment]
> Does the static linking exception mean that we are 100% okay to static link ZeroMQ (unmodified) into our own shared libraries and applications so that we can have a standalone binary/library that doesn't require copying a separate ZeroMQ library along with it?

Yes

**Comment by nightlark** [comment]
Thanks!
