### ISSUE TITLE
autogen.sh fails: could not find autoreconf

### ISSUE THREAD

**Issue by JiaRu2016** [zeromq/libzmq#3800]
# Issue description

when I git clone the repo and run `autogen.sh`, it raises error:
```
$ git clone https://github.com/zeromq/libzmq.git
$ cd libzmq
$ ./autogen.sh
autogen.sh: error: could not find autoreconf.  autoconf and automake are required to run autogen.sh.
```

# Environment

* libzmq version (commit hash if unreleased):  75dfbae0d1dc65312d2aaad6902911a3214f4819
* OS: centos-release-7-7.1908.0.el7.centos.x86_64

**Comment by bluca** [comment]
2 options:

1) Use the pre-built Centos7 packages available at https://software.opensuse.org/download.html?project=network%3Amessaging%3Azeromq%3Arelease-stable&package=zeromq-devel
2) Install autoconf and automake, you need to check with your distribution on how to do this
