### ISSUE TITLE
Fallback to localhost in ws_address has no effect

### ISSUE THREAD

**Issue by sigiesec** [zeromq/libzmq#3809]
The fallback in case of an error of `getnameinfo` in https://github.com/zeromq/libzmq/blob/1b8a35248071e5fbccc9650c34d22933a56c505e/src/ws_address.cpp#L76 has no effect, since `_host` is always reassigned afterwards. I am not sure what the intended behaviour should be. Return from the `if` block?

**Comment by somdoron** [comment]
Yes, I think it should return
