### ISSUE TITLE
problem of scalability of zmq when sending message In parallel

### ISSUE THREAD

**Issue by sherlockkenan** [zeromq/libzmq#3830]
# Issue description

hi, everyone,
we are using zmq in our project. In our application,  it looks like a pub/sub mode. it haves one server and multiple clients, and the server want to send the message to all clients simultaneously.  After the client receive the message, it will send back an ack to server. However, in our evaluation, we find the latency of sending message increases as we increase the number of clients  and the size of message does not change.  For example the latency of 3 clients is 18ms, and the latency of 7 clients is 32 ms.

we implement this application using  both PUB-SUB model and  PUSH-PULL mode. both of them have the same performance problem. we also try to modify the ZMQ_IO_THREADS,  but it does not work.

# Environment

* libzmq version (commit hash if unreleased): 4.3.2
* OS: ubuntu 16.04

# Minimal test code / Steps to reproduce the issue

we  record the time that server starts sending message and the time that servers have received  all acks from all clients to calculate the latency.

 in the PUSH-PULL mode, the  pseudo-code like this 
server.cpp
```
 zmq:context_t context (16);
 zmq::socket_t * server_receiver= new zmq::socket_t(context, ZMQ_PULL);
 server_receiver->bind("tcp://*:1236");

 timer_t begin = get_timer();

 for(int i=0; i < client_size(); i++){
       zmq::socket_t * server_sender= new zmq::socket_t(context, ZMQ_PUSH);
       server_sender->bind(client_address[i]);
        /// no block,  return quickly
       server_sender->send(message);
 }
 timer_t  finish_sending = get_timer();

for(int i=0; i<client_size();i++) {
       string ack = server_receiver->recv();
}
timer_t end = get_timer();

timer_t  all_time = end - begin;
```
  
client.cpp
```
zmq:context_t context (16);
 zmq::socket_t * client_receiver= new zmq::socket_t(context, ZMQ_PULL);
client_receiver->bind("tcp://*:1236");

string message = client_receiver->recv();
// print message

zmq::socket_t * cient_sender= new zmq::socket_t(context, ZMQ_PUSH);
cient_sender->connect(server_address);
cient_sender->send(ack);

```
we record the variable (all_time) in the server.cpp as  the  latency

# What's the actual result? (include assertion message & call stack if applicable)
in our evaluation, we set the size of message as 1M. and we setup the server and clients in different node;

if the size of client  is 1,  the latency (all_time) is  9061 us
if the size of client  is 3,  the latency (all_time) is 18329 us
if the size of client  is 6,  the latency (all_time) is  32010us

when break down the all time.  the time  between finishing_sending and end takes most.. 

# What's the expected result?

we expect that latency  of client-6 is  almost the same as client-1. Because it is far  far from the bottleneck of network. we want  more resource of computer( like using multiple threads)  to do this work. We also set the ZMQ_IO_THREADS as 16, but it does work.

we also implement  this application using PUB -SUB mode , but it get the same result as above.
Is there any things we ignore? 
we hope you can us some suggestions。
thanks

-

**Comment by bluca** [comment]
Creating and binding sockets is configuration, and it's slow. Create the sockets first, and then reuse them instead.

**Comment by sherlockkenan** [comment]
I change this, but this problem  still exist. Because in the all_time(32ms): finish_sending - begin  (3ms),
end - finish_sending(29ms).   after creating ,binding sockets and  calling sending,  it takes 29ms to  send msg and  wait for ack;

**Comment by bluca** [comment]
There's likely some issue in your application, don't build your own measurement tool, use the provided ones: https://github.com/zeromq/libzmq/tree/master/perf - that will show you the ceiling of what's possible given hardware/environment
