### ISSUE TITLE
not providing "Findlibzmq.cmake" by cmake install

### ISSUE THREAD

**Issue by DinoStray** [zeromq/libzmq#3839]
If I use
```
find_package(libzmq REQUIRED)
```
then report error:
```
CMake Error at CMakeLists.txt:32 (find_package):
  By not providing "Findlibzmq.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "libzmq", but
  CMake did not find one.

  Could not find a package configuration file provided by "libzmq" with any
  of the following names:

    libzmqConfig.cmake
    libzmq-config.cmake

  Add the installation prefix of "libzmq" to CMAKE_PREFIX_PATH or set
  "libzmq_DIR" to a directory containing one of the above files.  If "libzmq"
  provides a separate development package or SDK, be sure it has been
  installed.
```

**Comment by bluca** [comment]
use pkg-config

**Comment by mjvk** [comment]
You can also use conan, it will generate it for you.

**Comment by ferdnyc** [comment]
You shouldn't be using `find_package(libzmq REQUIRED)`.

If you built and installed libzmq using `cmake`, the CMake config is installed as `ZeroMQConfig.cmake`.

Use the following, to incorporate it into another CMake project:
```cmake
find_package(ZeroMQ REQUIRED)

# Shared library
add_library(target SHARED target.c)
target_link_libraries(target PUBLIC ZeroMQ::libzmq)

# Static library
add_library(target STATIC target.c)
target_link_libraries(target PRIVATE ZeroMQ::libzmq-static)
```

**Comment by DinoStray** [comment]
# build and install libzmq
cmake -DCMAKE_BUILD_TYPE=RelWithDebInfo .. 
make -j 4 install 

# CMakeLists.txt
add_library(target STATIC target.c)
target_link_libraries(target PRIVATE ZeroMQ::libzmq-static)

# cmake error
Target "sharelogger" links to target "ZeroMQ::libzmq-static" but the target
  was not found.  Perhaps a find_package() call is missing for an IMPORTED
  target, or an ALIAS target is missing?

@ferdnyc

**Comment by ferdnyc** [comment]
@DinoStray Sorry, I made a mistake. Depending where your ZeroMQ targets are coming from, they probably don't use a namespace. The _target_ name is just `libzmq` or `libzmq-static`.

```cmake
# So it'd be
find_package(ZeroMQ)
# But then
target_link_libraries(something PUBLIC libzmq)
target_link_libraries(something PRIVATE libzmq-static)
```

**Comment by ferdnyc** [comment]
(If you want to check and make sure, you can do something like...)
```cmake
if(TARGET libzmq-static)
  target_link_libraries(...)
else()
  message(ERROR "Can't find ZeroMQ library target!")
endif()
```

**Comment by DinoStray** [comment]
> (If you want to check and make sure, you can do something like...)
> 
> ```cmake
> if(TARGET libzmq-static)
>   target_link_libraries(...)
> else()
>   message(ERROR "Can't find ZeroMQ library target!")
> endif()
> ```

OK, it works, thank you
