### ISSUE TITLE
Build latest_release branch on FreeBSD fails at linkage

### ISSUE THREAD

**Issue by MikHulk** [zeromq/libzmq#3842]
*Please use this template for reporting suspected bugs or requests for help.*

# Issue description

I am trying to build libzmq from source on the latest_release branch.

I am using autotools binutils and gmake. all of these are present in `/usr/local/bin`. 
So that the construction process uses the right version of ld I declare the path in the environment variables during the auto-configuration:
```
% env LD=/usr/local/bin/ld NM=/usr/local/bin/nm AS=/usr/local/bin/as ./autogen.sh
```
and later:
```
% env LD=/usr/local/bin/ld NM=/usr/local/bin/nm AS=/usr/local/bin/as ./configure --disable-dependency-tracking
```

Despite this (I tried the "normal" way to build before with the same result), I get this error during the build process:

```
% env LD=/usr/local/bin/ld NM=/usr/local/bin/nm AS=/usr/local/bin/as LANG=C gmake
Making all in doc
gmake[1]: Entering directory '/usr/home/user/libzmq/doc'
gmake[1]: Nothing to be done for 'all'.
gmake[1]: Leaving directory '/usr/home/user/libzmq/doc'
gmake[1]: Entering directory '/usr/home/user/libzmq'
  CXXLD    perf/benchmark_radix_tree
/usr/bin/ld: error: cannot preempt symbol: _ULx86_64_init_local
>>> defined in /usr/local/lib/libunwind.so
>>> referenced by err.cpp:409 (src/err.cpp:409)
>>>               libzmq_la-err.o:(zmq::print_backtrace()) in archive ./src/.libs/libzmq.a

/usr/bin/ld: error: cannot preempt symbol: _ULx86_64_step
>>> defined in /usr/local/lib/libunwind.so
>>> referenced by err.cpp:411 (src/err.cpp:411)
>>>               libzmq_la-err.o:(zmq::print_backtrace()) in archive ./src/.libs/libzmq.a

/usr/bin/ld: error: cannot preempt symbol: _ULx86_64_get_proc_info
>>> defined in /usr/local/lib/libunwind.so
>>> referenced by err.cpp:420 (src/err.cpp:420)
>>>               libzmq_la-err.o:(zmq::print_backtrace()) in archive ./src/.libs/libzmq.a

/usr/bin/ld: error: cannot preempt symbol: _ULx86_64_get_proc_name
>>> defined in /usr/local/lib/libunwind.so
>>> referenced by err.cpp:423 (src/err.cpp:423)
>>>               libzmq_la-err.o:(zmq::print_backtrace()) in archive ./src/.libs/libzmq.a

/usr/bin/ld: error: cannot preempt symbol: _ULx86_64_step
>>> defined in /usr/local/lib/libunwind.so
>>> referenced by err.cpp:411 (src/err.cpp:411)
>>>               libzmq_la-err.o:(zmq::print_backtrace()) in archive ./src/.libs/libzmq.a
c++: error: linker command failed with exit code 1 (use -v to see invocation)
gmake[1]: *** [Makefile:3319: perf/benchmark_radix_tree] Error 1
gmake[1]: Leaving directory '/usr/home/user/libzmq'
gmake: *** [Makefile:6925: all-recursive] Error 1
```

# Environment

* libzmq latest_release branch
* OS: Free BSD 12.0-RELEASE-p12

**Comment by MikHulk** [comment]
in the Makefile. The LD Variable is set with the proper path, but the Makefile seems to use CXXLD instead. I am not sure, could you confirm that ?

**Comment by bluca** [comment]
it's set to whatever autotools set it - there's no project-specific setting for the linker

**Comment by MikHulk** [comment]
So why I get an error with the wrong location ?

**Comment by bluca** [comment]
Sorry, I have no idea. You'll have to check the autotools documentation and/or ask some autotools maintainer.

**Comment by MikHulk** [comment]
Are your sure it comes from autotools ?

**Comment by bluca** [comment]
yes

**Comment by MikHulk** [comment]
ok...

So it comes from a bad usage so I must read the documentation or problem with the autotools  in this case I should see with maintainer.

I don't know autotools I just need a local build of libzmq to get pyzmq for a project.  So if you could give me some indication it would be great. 

I follow indication from the wiki page of the project, and get this error. zmq support  freebsd. So I don't understand from where the error comes from. Probably from me but I need a little help here.

**Comment by bluca** [comment]
IIRC freebsd ports include libzmq, so you don't need to build it at all

**Comment by MikHulk** [comment]
I don't want to have a system wide install. port management in freebsd is sensible so I try to keep a short list of software installed. I have another solution to build it from port in a jail / or in a VM I will do that if I don't understand where the problem comes from. I am looking autotools right now. thx

**Comment by bluca** [comment]
Even if you don't want to use ports, you can have a look at how they build it, and do the same. If it works there, it should work for you too.

**Comment by MikHulk** [comment]
yes I was looking in. the problem went from latest_release uses a higher version of libunwind which is not provided by port system. buid is successfull with 4.2.5 version of zmq. 

This don't explain why the error message mentions /usr/bin/ld however. But it seems to work now

**Comment by MikHulk** [comment]
make check fails with the same error. but some tests compile. Is there a mean to skip some tests perhaps ?

**Comment by MikHulk** [comment]
thx anyway. It works now
