### ISSUE TITLE
why zmq compile failed on macosx ？

### ISSUE THREAD

**Issue by linuxsky** [zeromq/libzmq#3845]
⇒  g++ -v
Configured with: --prefix=/Library/Developer/CommandLineTools/usr --with-gxx-include-dir=/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/c++/4.2.1
Apple clang version 11.0.0 (clang-1100.0.33.17)
Target: x86_64-apple-darwin19.3.0
Thread model: posix
InstalledDir: /Library/Developer/CommandLineTools/usr/bin

Configured with: --prefix=/Library/Developer/CommandLineTools/usr --with-gxx-include-dir=/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/c++/4.2.1
Apple clang version 11.0.0 (clang-1100.0.33.17)
Target: x86_64-apple-darwin19.3.0
Thread model: posix
InstalledDir: /Library/Developer/CommandLineTools/usr/bin

info：
  CXX      src/libzmq_la-ws_decoder.lo
  CXX      src/libzmq_la-ws_encoder.lo
  CXX      src/libzmq_la-ws_engine.lo
  CXX      src/libzmq_la-ws_listener.lo
  AR       external/unity/libunity.a
ar: `u' modifier ignored since `D' is the default (see `U')
  AR       tests/libtestutil.a
ar: `u' modifier ignored since `D' is the default (see `U')
  CXXLD    src/libzmq.la
ar: `u' modifier ignored since `D' is the default (see `U')
  CXXLD    tools/curve_keygen
  CXXLD    perf/remote_lat
  CXXLD    perf/local_lat
  CXXLD    perf/local_thr
ld: warning: ignoring file src/.libs/libzmq.a, building for macOS-x86_64 but attempting to link with file built for unknown-unsupported file format ( 0x21 0x3C 0x61 0x72 0x63 0x68 0x3E 0x0A 0x2F 0x20 0x20 0x20 0x20 0x20 0x20 0x20 )
ld: warning: ignoring file src/.libs/libzmq.a, building for macOS-x86_64 but attempting to link with file built for unknown-unsupported file format ( 0x21 0x3C 0x61 0x72 0x63 0x68 0x3E 0x0A 0x2F 0x20 0x20 0x20 0x20 0x20 0x20 0x20 )
ld: warning: ld: warning: ignoring file src/.libs/libzmq.a, building for macOS-x86_64 but attempting to link with file built for unknown-unsupported file format ( 0x21 0x3C 0x61 0x72 0x63 0x68 0x3E 0x0A 0x2F 0x20 0x20 0x20 0x20 0x20 0x20 0x20 )ignoring file src/.libs/libzmq.a, building for macOS-x86_64 but attempting to link with file built for unknown-unsupported file format ( 0x21 0x3C 0x61 0x72 0x63 0x68 0x3E 0x0A 0x2F 0x20 0x20 0x20 0x20 0x20 0x20 0x20 )

Undefined symbols for architecture x86_64:
  "_zmq_curve_keypair", referenced from:
      _main in curve_keygen.o
  "_zmq_errno", referenced from:
      _main in curve_keygen.o
ld: symbol(s) not found for architecture x86_64
Undefined symbols for architecture x86_64:
  "_zmq_close", referenced from:
      _main in remote_lat.o
  "_zmq_connect", referenced from:
      _main in remote_lat.o
  "_zmq_ctx_term", referenced from:
      _main in remote_lat.o
  "_zmq_init", referenced from:
      _main in remote_lat.o
  "_zmq_msg_close", referenced from:
      _main in remote_lat.o
  "_zmq_msg_data", referenced from:
      _main in remote_lat.o
  "_zmq_msg_init_size", referenced from:
      _main in remote_lat.o
  "_zmq_msg_size", referenced from:
      _main in remote_lat.o
  "_zmq_recvmsg", referenced from:
      _main in remote_lat.o
  "_zmq_sendmsg", referenced from:
      _main in remote_lat.o
  "_zmq_socket", referenced from:
      _main in remote_lat.o
  "_zmq_stopwatch_start", referenced from:
      _main in remote_lat.o
  "_zmq_stopwatch_stop", referenced from:
      _main in remote_lat.o
  "_zmq_strerror", referenced from:
      _main in remote_lat.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
clang: error: linker command failed with exit code 1 (use -v to see invocation)
Undefined symbols for architecture x86_64:
  "_zmq_bind", referenced from:
      _main in local_thr.o
  "_zmq_close", referenced from:
      _main in local_thr.o
  "_zmq_ctx_term", referenced from:
      _main in local_thr.o
  "_zmq_init", referenced from:
      _main in local_thr.o
  "_zmq_msg_close", referenced from:
      _main in local_thr.o
  "_zmq_msg_init", referenced from:
      _main in local_thr.o
  "_zmq_msg_size", referenced from:
      _main in local_thr.o
  "_zmq_recvmsg", referenced from:
      _main in local_thr.o
  "_zmq_setsockopt", referenced from:
      _main in local_thr.o
  "_zmq_socket", referenced from:
      _main in local_thr.o
  "_zmq_stopwatch_start", referenced from:
      _main in local_thr.o
  "_zmq_stopwatch_stop", referenced from:
      _main in local_thr.o
  "_zmq_strerror", referenced from:
      _main in local_thr.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[1]: *** [Makefile:4263: tools/curve_keygen] Error 1
make[1]: *** Waiting for unfinished jobs....
Undefined symbols for architecture x86_64:
  "_zmq_bind", referenced from:
      _main in local_lat.o
  "_zmq_close", referenced from:
      _main in local_lat.o
  "_zmq_ctx_term", referenced from:
      _main in local_lat.o
  "_zmq_init", referenced from:
      _main in local_lat.o
  "_zmq_msg_close", referenced from:
      _main in local_lat.o
  "_zmq_msg_init", referenced from:
      _main in local_lat.o
  "_zmq_msg_size", referenced from:
      _main in local_lat.o
  "_zmq_recvmsg", referenced from:
      _main in local_lat.o
  "_zmq_sendmsg", referenced from:
      _main in local_lat.o
  "_zmq_sleep", referenced from:
      _main in local_lat.o
  "_zmq_socket", referenced from:
      _main in local_lat.o
  "_zmq_strerror", referenced from:
      _main in local_lat.o
ld: symbol(s) not found for architecture x86_64
make[1]: *** [Makefile:3565: perf/remote_lat] Error 1
make[1]: *** [Makefile:3553: perf/local_thr] Error 1
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[1]: *** [Makefile:3547: perf/local_lat] Error 1
make[1]: Leaving directory '/Users/shiyang/.xmake/cache/packages/2003/z/zmq/master/source/zmq'
make: *** [Makefile:7347: all-recursive] Error 1

**Comment by bluca** [comment]
Your build environment is not set up correctly. Use macports or Homebrew instead.
