### ISSUE TITLE
Shared memory map transport

### ISSUE THREAD

**Issue by KOLANICH** [zeromq/libzmq#3853]
Does it make sense to have a memory map + ring buffer transport?

**Comment by bluca** [comment]
there's already inproc + user-supplied buffers

**Comment by KOLANICH** [comment]
Close this one in favour of #3241.

**Comment by aagor** [comment]
@bluca Can you give more details on user-supplied buffers? I couldn't find documentation or other information about that feature.

**Comment by bluca** [comment]
there isn't any, it's an implementation detail

**Comment by bluca** [comment]
See links in https://github.com/zeromq/libzmq/issues/3241

**Comment by aagor** [comment]
There are no links in the other issue, other then to the `inproc` API documentation. But there it isn't mentioned at all.
Even if it's an implementation detail, there must be some related issues/PRs/commits?

**Comment by bluca** [comment]
Just search the documentation, it's quite straightforward, messages can be initialized from user-owned data buffers
