### ISSUE TITLE
Support zmq_msg_init_copy for convenience

### ISSUE THREAD

**Issue by gummif** [zeromq/libzmq#3858]
There are 3 ways to initialize `zmq_msg_t`:
1. Empty message
2. With initial size of uninitialized memory
3. Taking ownership/pointer to existing memory

One of the most common things done with ZeroMQ is constructing messages. A very common operation (textbook [example](https://www.oreilly.com/library/view/zeromq/9781449334437/ch01s04.html)) is to construct a message by copying data (especially for other language bindings). Without error checks it looks like so:
```c
zmq_msg_t m;
zmq_msg_init_size(&m, size);
memcpy(zmq_msg_data(&m), data, size);
```
if data can be null, then it becomes
```c
zmq_msg_t m;
zmq_msg_init_size(&m, size);
if (size)
    memcpy(zmq_msg_data(&m), data, size);
```
which are 3 function calls and 1 branch, excluding checks for errors.

May I suggest a 4th option to copy existing data `int zmq_msg_init_copy(zmq_msg_t *msg, const void *data, size_t size);`, used like so
```c
zmq_msg_t m;
zmq_msg_init_copy(&m, data, size);
```

If this is is well received I am willing to see how far I can go implementing it.

**Comment by bluca** [comment]
That would be easily confused with zmq_msg_copy

**Comment by gummif** [comment]
How about `zmq_msg_init_buffer`?

**Comment by bluca** [comment]
sure that's fine, feel free to send a PR
