### ISSUE TITLE
libzmq's use of the as-server field of ZMTP 3 is non-conforming

### ISSUE THREAD

**Issue by cite-reader** [zeromq/libzmq#3863]
[ZMQ RFC 23](https://rfc.zeromq.org/spec/23/) and [37](https://rfc.zeromq.org/spec/37/) (ZMTP 3.0 and 3.1 respectively) define the 33rd byte of the greeting as the `as-server` field, intended to be used by security mechanisms to indicate whether they are acting in the server or client role. The NULL mechanism defined in those same documents explicitly sets this field to zero, but [PLAIN (RFC 24)](https://rfc.zeromq.org/spec/24/) "uses the greeting as-server field to identify which peer is 'client' and which peer is 'server'." The [CURVE (RFC 25)](https://rfc.zeromq.org/spec/25/) and [GSSAPI (RFC 38)](https://rfc.zeromq.org/spec/38/) mechanisms have identical language.

In practice libzmq [unconditionally sets `as-server` to zero](https://github.com/zeromq/libzmq/blob/a84ffa12b2eb3569ced199660bac5ad128bff1f0/src/stream_engine.cpp#L633) as though it were an extension of the 31-byte trailing filler. This is non-conforming, and a potential interoperability hazard if a client using an independent implementation of ZMTP attempts to validate it is speaking to a server before starting the security mechanism's handshake.

**Comment by bluca** [comment]
https://github.com/zeromq/libzmq/issues/2821
