### ISSUE TITLE
Wait until the message been transmitted to the network

### ISSUE THREAD

**Issue by yejw5** [zeromq/libzmq#3864]
As the [zmq_send docs](http://api.zeromq.org/2-1:zmq-send) says:

`A successful invocation of zmq_send() does not indicate that the message has been transmitted to the network, only that it has been queued on the socket and ØMQ has assumed responsibility for the message.`

Is there any way that we can wait until the message been transmitted to the network?

**Comment by bluca** [comment]
No, the behaviour is intentionally asynchronous

**Comment by yejw5** [comment]
Got it. Thanks!
