### ISSUE TITLE
Is ZeroMQ a Good Choice/Safe to Use in a DLL that Will Be Dynamically Loaded By Another Process?

### ISSUE THREAD

**Issue by 9ee1** [zeromq/libzmq#3869]
# Issue description

Hello - The use case I have is relatively straight forward. I am developing a plugin for Windows Active Directory that links to ZeroMQ. The plugin is compiled as a Windows DLL.

I am not very familiar with Active Directory internals but I can surmise that it uses a combination of the Win32 APIs _LoadLibrary_ and _GetProcAddress_ to dynamically load my Windows DLL and invokes a set of expected exported functions. Here is my question/concern.

Exploring the ZeroMQ code, I can see that when/if an exceptional error occurs, through the use of _zmq_assert_, it will call _zmq_abort_ which on Windows will raise a structured exception that will eventually terminate the AD Domain Controller process itself (since it is the one where my DLL is loaded).

For obvious reasons, this is unacceptable behavior in a plugin like mine. Is there anyway to prevent this happening at run-time or some kind of compile time option that changes this behavior? I am looking into _SetUnhandledExceptionFilter_ (https://docs.microsoft.com/en-us/windows/win32/api/errhandlingapi/nf-errhandlingapi-setunhandledexceptionfilter).

I understand handling this behavior, if there is a way, can lead to other unexpected issues but I can deal with those in another way, albeit probably an ugly way, that would be more acceptable then crashing an entire AD Domain Controller.

Thanks in advance.

# Environment

* libzmq version (commit hash if unreleased): **4.3.2**
* OS: **Windows**

# Minimal test code / Steps to reproduce the issue

**N/A**

# What's the actual result? (include assertion message & call stack if applicable)

**N/A**

# What's the expected result?

**N/A**

**Comment by jakecobb** [comment]
This doesn't directly answer your question, but in my experience asserts do not trigger under "normal exceptional" circumstances, but instead typically indicate a bug in ZeroMQ.

You may find #3786 relevant.  I showed the problem there in a thread, but it is equally problematic in `DllMain` for the `DLL_PROCESS_ATTACH` and `DLL_PROCESS_DETACH` events, which hold internal Windows locks and tend to deadlock on cross-thread interactions.  Cleanly creating and destroying a ZeroMQ context for use when your code lives in a DLL loaded by another process you don't control is not something I've been able to solve on Windows so far.

**Comment by 9ee1** [comment]
Thanks for your response. My experience with ZeroMQ assertions is the same as you but bringing down the entire process if a bug does occur is problematic for my specific use case.

I am going to go ahead and close the ticket since its been several months and I don't think anyone else is going to chime in.
