### ISSUE TITLE
What to do if your logic needs the connecting client's IP address?

### ISSUE THREAD

**Issue by jerkstorecaller** [zeromq/libzmq#3883]
I'm considering ZMQ to replace raw TCP sockets. From what I could read, ZMQ hides client address information from you.

Can you then please explain how ZeroMQ would work for servers where the client IP is used in logic?

Examples:

a) I want to allow special privileges to clients connecting from a specific IP, part of a configured whitelist on the server. For example, client attempts a REQ/REP command, the server must check client IP against the whitelist before executing. 
b) I want to restrict number of connected clients per IP to 2. If this is the 3rd active connection from that IP, my login function must reject them.
c) I want to track failed login attempts by IP, so I can block misbehaving hosts

I get that ZMQ doesn't just support TCP, but 99% of apps installed on your computer right now are designed to use TCP. It would be weird if ZMQ is letting a lowest common denominator transport drive the API decisions of the 99%.

**Comment by bluca** [comment]
ip addresses can be trivially spoofed, so if it is a security requirement, they are not adequate anyway. If it's not a security requirement, then can be reworked to avoid using them and instead use identifiers - the router/dealer pattern provides identity frames, for example.

I would recommend reading:
http://zguide.zeromq.org/page:all
you will find why that information is not, and will not, be made available

**Comment by jerkstorecaller** [comment]
IP-based Access Control Lists are a standard security requirement on non-cloud servers. I'm sure you have one on your wifi router.

If they can be spoofed, then that would be due to a flaw in the network infrastructure. That's way below the application layer, so it has nothing to do with software development. 

I looked through that book and don't see how you'd implement ACL, or blocking misbehaving IPs.

**Comment by bluca** [comment]
> IP-based Access Control Lists are a standard security requirement on non-cloud servers. I'm sure you have one on your wifi router.
> 
> If they can be spoofed, then that would be due to a flaw in the network infrastructure. That's way below the application layer, so it has nothing to do with software development.

Well, no, that's just how ip works. That's why we have authentication and authorization layers.

> I looked through that book and don't see how you'd implement ACL, or blocking misbehaving IPs.

With CURVE you can set up your own policy in software to allow/deny via ZAP.
