### ISSUE TITLE
What does Static Link Exception really mean?

### ISSUE THREAD

**Issue by guanbs** [zeromq/libzmq#3884]
Hi, 
I would like to know what does Static Link Exception (SLE) really mean in the license. 

1. Can I static link libzmq into my application/library if it is used for commercial purpose?
2. For commercial application/library, if static link is performed, should I open my application/library source code, provided that the code of libzmq is not modified.
3. If static link is performed, can I license for my application/library under other licenses?

[#3787](https://github.com/zeromq/libzmq/issues/3787) is a similar question but it is not for commercial purpose.
[#2376](https://github.com/zeromq/libzmq/issues/2376) is great but it may last for a while.

I am not doing static link right now and I do prefer dynamic link. The reason I ask this question is to clearify the static link concern I may face in future. It is not for finding some way to hide libzmq's work behind my software, but as mentioned in #3787, static link is sometimes more suitable that dynamic link.

Thanks,
Boshen

**Comment by bluca** [comment]
> Hi,
> I would like to know what does Static Link Exception (SLE) really mean in the license.
> 
> 1. Can I static link libzmq into my application/library if it is used for commercial purpose?

Yes

> 2. For commercial application/library, if static link is performed, should I open my application/library source code, provided that the code of libzmq is not modified.

No

> 3. If static link is performed, can I license for my application/library under other licenses?

Yes
