### ISSUE TITLE
zmq aborts in a network with glitch

### ISSUE THREAD

**Issue by mk4-github** [zeromq/libzmq#3891]
*Please use this template for reporting suspected bugs or requests for help.*

# Issue description
This application heavily uses ZMQs and has generated a core-dump on production. From a few occurrences, we could see, anytime there is instability of network (detected from other monitoring nodes) this abort happens.

# Environment

* libzmq version (commit hash if unreleased): 
zeromq3-3.2.5-1.el7.x86_64
zeromq-4.1.4-5.el7.x86_64
czmq-3.0.2-3.el7.x86_64
* OS: 

# Minimal test code / Steps to reproduce the issue
CentOS Linux release 7.4.1708 (Core)

# What's the actual result? (include assertion message & call stack if applicable)

#0 0x00007f44a00801f7 in raise () from /lib64/libc.so.6
#1 0x00007f44a00818e8 in abort () from /lib64/libc.so.6
#2 0x00007f44a1f74759 in zmq::zmq_abort(char const*) () from /lib64/libzmq.so.5
#3 0x00007f44a1fa410d in zmq::tcp_write(int, void const*, unsigned long) () from /lib64/libzmq.so.5
#4 0x00007f44a1f9f417 in zmq::stream_engine_t::out_event() () from /lib64/libzmq.so.5
#5 0x00007f44a1f7437a in zmq::epoll_t::loop() () from /lib64/libzmq.so.5
#6 0x00007f44a1fa83a6 in thread_routine () from /lib64/libzmq.so.5
#7 0x00007f44a1b2ce25 in start_thread () from /lib64/libpthread.so.0
#8 0x00007f44a014334d in clone () from /lib64/libc.so.6

Another time:
#0  0x00007fd632c1a1f7 in raise () from /lib64/libc.so.6
#1  0x00007fd632c1b8e8 in abort () from /lib64/libc.so.6
#2  0x00007fd632c59f47 in __libc_message () from /lib64/libc.so.6
#3  0x00007fd632c61619 in _int_free () from /lib64/libc.so.6
#4  0x00007fd634b179f5 in zmq::msg_t::close() () from /lib64/libzmq.so.5
#5  0x00007fd634b3b494 in zmq::stream_engine_t::~stream_engine_t() () from /lib64/libzmq.so.5
#6  0x00007fd634b3b9b9 in zmq::stream_engine_t::~stream_engine_t() () from /lib64/libzmq.so.5
#7  0x00007fd634b39ed5 in zmq::stream_engine_t::error(zmq::stream_engine_t::error_reason_t) () from /lib64/libzmq.so.5
#8  0x00007fd634b3b171 in zmq::stream_engine_t::in_event() () from /lib64/libzmq.so.5
#9  0x00007fd634b0e35e in zmq::epoll_t::loop() () from /lib64/libzmq.so.5
#10 0x00007fd634b423a6 in thread_routine () from /lib64/libzmq.so.5
#11 0x00007fd6346c6e25 in start_thread () from /lib64/libpthread.so.0
#12 0x00007fd632cdd34d in clone () from /lib64/libc.so.6

# What's the expected result?

**Comment by yinhuan99** [comment]
I have the same problem.
4.2.2 crash in zmq::msg_t::close() #2617  ，this is the same issue.

**Comment by yinhuan99** [comment]
The issue needs to be reopened.

**Comment by eclazi** [comment]
I believe we have seen this bug also
