### ISSUE TITLE
gssapi support with zmq/czmq on linux fails with KG_CCACHE_NOMATCH

### ISSUE THREAD

**Issue by muralinagaraj** [zeromq/libzmq#3906]
*Please use this template for reporting suspected bugs or requests for help.*

# Issue description

service_name = client3@localhost oid type = (null)
[21485] 1589112133.773384: Retrieving client3/localhost@PXP from FILE:/etc/krb5.keytab (vno 0, enctype 0) with result: 0/Success
[21485] 1589112133.773388: Retrieving client3/localhost@PXP from FILE:/etc/krb5.keytab (vno 0, enctype 0) with result: 0/Success
acquire_credentials:402 851968 39756032
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
my printf ... minor code 39756032 is CCACHE_NOMATCH

status = Unspecified GSS failure.  Minor code may provide more information
gssapi_server_t:68

[root@localhost auth]# klist 
Ticket cache: FILE:/tmp/tgt
Default principal: client3/localhost@PXP

Valid starting       Expires              Service principal
05/10/2020 11:58:25  05/11/2020 11:58:25  krbtgt/PXP@PXP
05/10/2020 12:02:01  05/11/2020 11:58:25  client3/localhost@
05/10/2020 12:02:01  05/11/2020 11:58:25  client3/localhost@PXP

# Environment

* libzmq version (commit hash if unreleased): 
libzmq-4.3.2
* OS: 
centos 8

# Minimal test code / Steps to reproduce the issue

1. trying this with czmq/zquth GSSAPI, simple test involving a server and client programs sending hello message over a REQ/REQ connection.

# What's the actual result? (include assertion message & call stack if applicable)

both end points hang in zmsg_recv (client does a send first)

# What's the expected result?

**Comment by muralinagaraj** [comment]
from ftp://ftp.isi.edu/in-notes/rfc2744.txt, gss_acquire_cred section,

<snip>
This routine is expected to be used primarily by context acceptors,
   since implementations are likely to provide mechanism-specific ways
   of obtaining GSS-API initiator credentials from the system login
   process.  Some implementations may therefore not support the
   acquisition of GSS_C_INITIATE or GSS_C_BOTH credentials via
   GSS_Acquire_cred() for any name other than GSS_C_NO_NAME, or a name
   resulting from applying GSS_Inquire_context() to an active context,
   or a name resulting from applying GSS_Inquire_cred() against a
   credential handle corresponding to default behavior. It is important
   to recognize that the explicit name which is yielded by resolving a
   default reference may change over time, e.g., as a result of local
   credential element management operations outside GSS-API; once
   resolved, however, the value of such an explicit name will remain
   constant.

</snip>

Changing  acquire_credentials to specify GSS_C_NO_NAME worked ... was able to get the following programs to work as expected. ie. with a valid keytab entry for client4@localhost, the programs are able to authenticate with one another and exchange messages. without the keytab entry, both hang (in zmsg_recv) as they cannot establish the security context because no creds for the principal.

`
#include <gssapi/gssapi.h>

using namespace std;

int
main(int argc, char **argv)
{
    zactor_t *auth = zactor_new (zauth, NULL);
    zstr_send (auth, "VERBOSE");
    zsock_wait (auth);
    zstr_sendx (auth, "GSSAPI", NULL);
    zsock_wait (auth);

    zsock_t *sock = zsock_new(ZMQ_REQ);
    zsock_set_gssapi_service_principal(sock, "client4@localhost");
    zsock_set_gssapi_principal(sock, "client4@localhost");

    zsock_connect(sock, "tcp://127.0.0.1:75000");
    zstr_send(sock, "hello from client\n");

    zmsg_t *zr = zmsg_recv(sock);
    zmsg_print(zr);
    zmsg_destroy(&zr);
    zsock_destroy(&sock);
    zactor_destroy(&auth);

    return 0;
}
`
`int
main(int argc, char **argv)
{
    zactor_t *auth = zactor_new (zauth, NULL);
    zstr_send (auth, "VERBOSE");
    zsock_wait (auth);
    zstr_sendx (auth, "GSSAPI", NULL);
    zsock_wait (auth);

    zsock_t *sock = zsock_new(ZMQ_REP);
    int s = 1;

    zsock_set_gssapi_server(sock, s);
    zsock_set_gssapi_principal(sock, "client4@localhost");

    zsock_bind(sock, "tcp://127.0.0.1:75000");

    zmsg_t *zm = zmsg_recv(sock);
    zmsg_print(zm);
    zmsg_destroy(&zm);
    zstr_send(sock, "hello from server");
    zsock_destroy(&sock);

    zactor_destroy (&auth);
    return 0;
}
`

`Failure case messages on server side
[root@localhost auth]# LD_LIBRARY_PATH=/home/vagrant/czmq-4.2.0/src/.libs/:/home/vagrant/libzmq-4.3.2/src/.libs/ ./server-gssapi
I: 20-05-11 06:50:09 zauth: API command=GSSAPI
[26772] 1589179809.637246: Failed to decrypt AP-REQ ticket: -1765328349/Request ticket server client4/localhost@PXP not found in keytab (ticket kvno 2)

`

`Success case messages on the server side
[root@localhost auth]# LD_LIBRARY_PATH=/home/vagrant/czmq-4.2.0/src/.libs/:/home/vagrant/libzmq-4.3.2/src/.libs/ ./server-gssapi
I: 20-05-11 07:02:36 zauth: API command=GSSAPI
[26884] 1589180560.16200: Decrypted AP-REQ with server principal client4/localhost@ABC: aes256-cts/B127
[26884] 1589180560.16201: AP-REQ ticket: localhost/host@ABC -> client4/localhost@ABC, session key aes256-cts/B3A3
[26884] 1589180560.16202: Negotiated enctype based on authenticator: aes256-cts
[26884] 1589180560.16203: Authenticator contains subkey: aes256-cts/DFF2
[26884] 1589180560.16205: Creating AP-REP, time 1589180560.25985, subkey aes256-cts/7000, seqnum 236723577
I: 20-05-11 07:02:40 zauth: ZAP request mechanism=GSSAPI ipaddress=127.0.0.1
I: 20-05-11 07:02:40 zauth: - allowed (GSSAPI) principal=localhost/host@ABC identity=
I: 20-05-11 07:02:40 zauth: - ZAP reply status_code=200 status_text=OK
D: 20-05-11 07:02:40 [018] hello from client

I: 20-05-11 07:02:40 zauth: API command=$TERM
[root@localhost auth]# 

`

**Comment by muralinagaraj** [comment]
Undoing the change which was done a few years ago to specify GSS_C_ACCEPT to gss_acquire_cred fixes this problem ...

**Comment by bluca** [comment]
You mean this change https://github.com/zeromq/libzmq/commit/f2b579ce027f4 ?
Paging @garlick for opinions on GSSAPI settings

**Comment by garlick** [comment]
I'm paying attention - waiting to see whether @muralinagaraj's response to your question.

(Disclaimer: I'm not an expert, and we're not using GSSAPI with libzmq at the moment, so I would need to spend time setting up a testbed to check out any proposed changes)

**Comment by muralinagaraj** [comment]
@bluca @garlick, Yes. That is the change.

**Comment by garlick** [comment]
The problem I was having prior to my change was that authentication was succeeding no matter what I set the client principal to.  The `gss_acquire_cred()` call would fall back to the default principal if called on the initiator (client) with GSS_AC_ACCEPT.

My change could well be wrong, though it was experimentally verified at the time.  The thing to "prove" is that after reverting it, the principal set on client is the one authenticated by the server.  Setting it on the client seemed to have no effect before.

I'll schedule some time to take a deeper dive next week if needed (Apologies: I am behind on a deadline this week and so my time is limited at the moment).

Minor note: you shouldn't need to start zauth on the client end.  Also (I'm sure you've noticed), zauth does not have any capability to limit which GSSAPI principals can connect.  It needs some work in that area.

We should have a look at libzmq's unit test too - make sure it works before and after any changes, and covers the specific issues we are hitting if possible.

**Comment by muralinagaraj** [comment]
Fair enough on the test/verification part --  let me know if you need any help there. I am kicking the tyres on zauth+gssapi so the code is not prime yet. My real use case is to get it to work with Active Directory as the KDC, but that is a bit farther down the line.

**Comment by garlick** [comment]
Any help would understanding this and/or with tests would be very much appreciated.  I'm not the maintainer of this code, so much as the person who touched it last :-)  I just want it to work properly because my project likely will need it soon.

**Comment by muralinagaraj** [comment]
Ok, I will post some supporting evidence based on tests that indeed the designated principal identities are being used to authenticate. I haven't run any ZMQ tests ever ... will try to spare some cycles to ramp up on that. 

Also, I noticed that we can improve troubleshooting simply by displaying a user friendly error, so some improvements are possible to the base ZMQ gssapi code. Will keep this space updated every few days.
