### ISSUE TITLE
More characters received than send in pub-sub pattern

### ISSUE THREAD

**Issue by yuzifu** [zeromq/libzmq#3912]
# Issue description
More characters received than send in pub-sub pattern

# Environment

* libzmq version (commit hash if unreleased): 4.3.2
* OS: win 10 1909 64bit

# Minimal test code / Steps to reproduce the issue

1.  
subscriber
```
int main(int argc, char* argv[])
{
    int64_t max_msg_size = 5 * 1024 * 1024;
    zmq::context_t context(1);

    zmq::socket_t subscriber(context, ZMQ_SUB);
    
    subscriber.connect("tcp://127.0.0.1:5661");
    subscriber.setsockopt(ZMQ_SUBSCRIBE, "", 0);
    subscriber.setsockopt(ZMQ_MAXMSGSIZE, &max_msg_size, sizeof(int64_t));

    zmq::message_t update(max_msg_size);
    size_t len;
    while (true) 
    {
        subscriber.recv(update, zmq::recv_flags::dontwait);

        if (!update.empty())
        {
            len = update.size();
            std::istringstream iss(static_cast<char*>(update.data()));
            std::string msg = iss.str();
            std::cout << "recv " << msg.length() << " bytes" << std::endl;

            std::cout << msg << std::endl;
        }
    }

    return 0;
}
```
2.
publisher
```
int main(int argc, const char* argv[])
{
    time_t _start, _end;
    double cost = 0;
    int64_t max_msg_size = 5 * 1024 * 1024;
    char* buf = nullptr;

    zmq::context_t o_zmq_context_ = zmq::context_t(1);
    zmq::socket_t o_push_socket_ = zmq::socket_t(o_zmq_context_, ZMQ_PUB);

    o_push_socket_.bind("tcp://*:5661");
    o_push_socket_.setsockopt(ZMQ_MAXMSGSIZE, &max_msg_size, sizeof(int64_t));

    time(&_start);

    while (true)
    {
        time(&_end);
        cost = difftime(_end, _start);
        if (cost >= 30)
        {
            _start = _end;
            buf = generate_msg_();

            size_t len = strlen(buf );
            zmq::message_t msg{ buf , len };
            zmq::send_result_t rtn = o_push_socket_.send(msg, zmq::send_flags::none);
            cout << "send bytes(" << len << ":" << rtn.value() << ")" << endl;
        }
    }

    return 0;
}
```

# What's the actual result? (include assertion message & call stack if applicable)
//send bytes(15552:15552)
//send bytes(16023:16023)
//send bytes(15949:15949)
//send bytes(15997:15997)

//recv 15552 bytes
//recv 16023 bytes
//recv 15963 bytes
//recv 16011 bytes

# What's the expected result?
The received size is the same as the send size

**Comment by bluca** [comment]
http://api.zeromq.org/master:zmq-setsockopt

> Caution: All options, with the exception of ZMQ_SUBSCRIBE, ZMQ_UNSUBSCRIBE, ZMQ_LINGER, ZMQ_ROUTER_HANDOVER, ZMQ_ROUTER_MANDATORY, ZMQ_PROBE_ROUTER, ZMQ_XPUB_VERBOSE, ZMQ_XPUB_VERBOSER, ZMQ_REQ_CORRELATE, ZMQ_REQ_RELAXED, ZMQ_SNDHWM and ZMQ_RCVHWM, only take effect for subsequent socket bind/connects.

**Comment by yuzifu** [comment]
> http://api.zeromq.org/master:zmq-setsockopt
> 
> > Caution: All options, with the exception of ZMQ_SUBSCRIBE, ZMQ_UNSUBSCRIBE, ZMQ_LINGER, ZMQ_ROUTER_HANDOVER, ZMQ_ROUTER_MANDATORY, ZMQ_PROBE_ROUTER, ZMQ_XPUB_VERBOSE, ZMQ_XPUB_VERBOSER, ZMQ_REQ_CORRELATE, ZMQ_REQ_RELAXED, ZMQ_SNDHWM and ZMQ_RCVHWM, only take effect for subsequent socket bind/connects.

I tried to comment the setsockopt statement and move setsockopt ahead of connect / bind, but the problem still existed

**Comment by bluca** [comment]
for C++ bindings the right repository is https://github.com/zeromq/cppzmq

**Comment by yuzifu** [comment]
The return value of the func recv() should be checked to determine the receive length.

like this:
```
recv_result_t = subscriber.recv(update, zmq::recv_flags::dontwait);
int recv_len = recv_result_t.value();
.
.
.
```
