### ISSUE TITLE
Thread Sanitizer support?

### ISSUE THREAD

**Issue by bill-torpey** [zeromq/libzmq#3919]
We've been using clang's "Thread Sanitizer" for a while now, and while it's not perfect, it has surfaced some potential problems that we are glad to have solved.  

ZeroMQ presents particular challenges w/TSAN, mostly because ZeroMQ uses non-standard synchronization techniques, which cause TSAN to report *lots of* false positives.

Some of those false positives can be eliminated by building ZeroMQ to use compiler intrinsics for atomic operations (`-DZMQ_HAVE_ATOMIC_INTRINSICS=1`), which [TSAN understands](https://github.com/google/sanitizers/wiki/ThreadSanitizerAtomicOperations).

Unfortunately, that isn't enough to reduce the numer of false positives to a  manageable level. The approach to eliminating false positives with other sanitizers (e.g., ASAN) has been to simply not instrument the problematic code.  However, that approach doesn't work w/TSAN -- it breaks TSAN's stack-unwinding code, so stack traces are incorrect.  (See <https://github.com/google/sanitizers/issues/941> for more information).

The best compromise appears to be to disable all TSAN instrumentation when building ZeroMQ *except* for function entry/exit code -- this preserves proper stack frames.  Then, at runtime a `called_from_lib:libzmq.so` is also required to prevent errors being reported from TSAN's interceptors (for functions like `memcmp`).

The relevant (undocumented) compile options are:

- `-mllvm -tsan-instrument-memory-accesses=0`
- `-mllvm -tsan-instrument-atomics=0`
- `-mllvm -tsan-instrument-func-entry-exit=1`

I've got a PR [ready to go](https://github.com/zeromq/libzmq/compare/master...nyfix:tsan-opts) to update the TSAN settings, but before I submit it I wanted to ask a couple of questions:

- Does the approach above (providing minimal TSAN support for libzmq) make sense?  
- Is there any interest in using TSAN to analyze libzmq itself?
  - I suspect not, but wanted to ask.  A better alternative to TSAN might be [Thread Safety Analysis](https://clang.llvm.org/docs/ThreadSafetyAnalysis.html), but that would be a fair amount of work to annotate the libzmq code.

Thanks.

P.S.  In [TSAN's documentation](https://github.com/google/sanitizers/wiki/ThreadSanitizerSuppressions), a suppression for `libzmq.so` is used as an example -- does anyone know how/why that got there?

**Comment by bluca** [comment]
That makes sense - if you can do the same for autoconf that would be great

**Comment by bill-torpey** [comment]
Updated the PR for autoconf, but that's strictly "monkey-see, monkey-do" -- should work, but no promises.

**Comment by bill-torpey** [comment]
I've taken the autoconf stuff as far as I can -- the correct compile options appear to be generated, but the build errors out with:

```
  CXXLD    src/libzmq.la
clang++: warning: argument unused during compilation: '-mllvm -mllvm' [-Wunused-command-line-argument]
clang++: warning: argument unused during compilation: '-mllvm -Wl,--version-script' [-Wunused-command-line-argument]
/usr/bin/ld:../src/libzmq.vers: file format not recognized; treating as linker script
/usr/bin/ld:../src/libzmq.vers:1: syntax error
clang++: error: linker command failed with exit code 1 (use -v to see invocation)
make[1]: *** [src/libzmq.la] Error 1
make[1]: Leaving directory `/home/btorpey/work/libzmq/master/src/test'
make: *** [all-recursive] Error 1
[btorpey@bt-brix test]$
```
This is beyond my ability to troubleshoot -- if someone else wants to pick up the autoconf bits please feel free to.

P.S.  I also had to manually hack the compiler options with `-Wno-unused-const-variable` to avoid this:

```
  CXX      src/src_libzmq_la-clock.lo
../src/clock.cpp:127:16: error: unused variable 'nsecs_per_usec' [-Werror,-Wunused-const-variable]
const uint64_t nsecs_per_usec = 1000;
               ^
1 error generated.
make[1]: *** [src/src_libzmq_la-clock.lo] Error 1
make[1]: Leaving directory `/home/btorpey/work/libzmq/master/src/test'
make: *** [all-recursive] Error 1
```

Note that this is with clang 10.x (https://github.com/llvm/llvm-project/tree/release/10.x) on CentOS 7.

**Comment by bluca** [comment]
the change looks fine, no idea what clang is complaining about there

**Comment by bill-torpey** [comment]
OK -- created PR.  Thanks.
