### ISSUE TITLE
This line doesn't seem correct

### ISSUE THREAD

**Issue by Jasper-Bekkers** [zeromq/libzmq#3923]
I'm pretty sure this should be `|` instead of `||`, though I have no idea what the implications would be. I'm guessing this mostly works by accident because WSA_FLAG_OVERLAPPED is 0x1 but it means WSA_FLAG_NO_HANDLE_INHERIT never gets set.

https://github.com/zeromq/libzmq/blob/e7f802d1ac7d61c89912ab261a19967b7d65b411/src/ip.cpp#L107

**Comment by bjovke** [comment]
Thanks @Jasper-Bekkers , I'll make a pull request.

**Comment by bjovke** [comment]
Resolved by #3943
