### ISSUE TITLE
ZeroMQ Zerocopy Speed Drop When using shared memory in MPSoc

### ISSUE THREAD

**Issue by baozinihao321** [zeromq/libzmq#3934]
*Please use this template for reporting suspected bugs or requests for help.*

# Issue description
Hi, I tried to deploy ZeroMQ in an Xilinx MPSoc Board. It's great to use zerocopy (init_data function) on a malloc buffer. However, the tcp transfer speed became very slow when I used an uncached memory area (shared memory) to send data. Is there any method to use MSG_ZEROCOPY flag (after linux kernel 4.14) in ZeroMQ to accelerate this situation ? Also the zerocopy tech in ZeroMQ seems to not the real "zerocopy", which is not identical to the MSG_ZEROCOPY. Does anyone have some ideas about these ? Thanks a lot.

# Environment

* libzmq version (commit hash if unreleased): 4.3.2
* OS: Linux 4.14

# Minimal test code / Steps to reproduce the issue

1.  Null

# What's the actual result? (include assertion message & call stack if applicable)

Null

# What's the expected result?
Null

**Comment by bluca** [comment]
> Is there any method to use MSG_ZEROCOPY flag (after linux kernel 4.14) in ZeroMQ to accelerate this situation ?

No, this is not implemented.
