### ISSUE TITLE
ZeroMQ binaries for windows with PGM

### ISSUE THREAD

**Issue by davidgyates** [zeromq/libzmq#3942]
# Issue description
Windows binaries don't have PGM support - just responds with EPROTONOSUPPORT

# Environment
Windows (Visual Studio 12 2013)

libzmq Release 4.3.2
from https://zeromq.org/download/

Building with OpenPGM is tortuous and so far I have not been successful (chase one build error away, to get another and another and another...).

At the very least, the docs should note that PGM is not included with this binary, and/or on the API page that the feature needs explicitly enabling/building or is simply not available on Windows.

**Comment by somdoron** [comment]
Maybe we can add zeromq to the new winget?

**Comment by davidgyates** [comment]
I did persist trying to build myself - just ended up with a build error that I can't get past.

So what should have been half an hour knocking up a simple test and evaluating has been a whole day lost trying to build it.

Is PGM actively supported with 0mq - I note that OpenPGM itself is looking a bit unloved in an archived project....

**Comment by davidgyates** [comment]
{Maybe we can add zeromq to the new winget?}
@somdoron just add to the _existing_ binary build!

Any other distribution mechanism is a bonus.
