### ISSUE TITLE
Invalid argument (../libzmq/src/condition_variable.hpp:308)

### ISSUE THREAD

**Issue by wzli** [zeromq/libzmq#3970]
# Issue description
Rare and sporadic crashing with
Invalid argument (../libzmq/src/condition_variable.hpp:308)

I've encountered this problem twice, once on d0d23446f5797364c885c7fdc982e5a1efe616fa, and once on v4.3.2 (hoping it would be more stable).

# Environment
Ubuntu 18.04 docker container

* libzmq version: 
d0d23446f5797364c885c7fdc982e5a1efe616fa
and v4.3.2

# Minimal test code / Steps to reproduce the issue
It happens rarely, haven't found out how to reliably reproduce. Maybe correlated high processing load, but here's my setup.
A P2P mesh with 32 nodes running inside different docker containers on the same host, talking over the virtual bridge network. Each node binds a dish socket and transmits over radio socket using UDP. On average each node transmits ~8kB messages to 4-6 neighbors at around 30Hz. I encountered the problem on some node after letting the system run for a while.

# What's the actual result? (include assertion message & call stack if applicable)

Invalid argument (../libzmq/src/condition_variable.hpp:308)
Aborted (core dumped)
exited with code 134

Unfortunately, I couldn't retrieve core dump since the docker container shutdown right after the crash. Will will keep the container running next time if I catch it again.

# What's the expected result?
No crash and continued operation.

**Comment by wzli** [comment]
Unexpected return value from a wait condition. Might be some sort of system out of resource error. But still, I wouldn't want the application to crash in deployment. Is it safe to compile without asserts?

**Comment by bluca** [comment]
> Is it safe to compile without asserts?

No, it is not.

The assert message shows your build is using the pthread implementation, might be worth rebuilding with a c++11 compiler so that the STL implementation is used? You can also force it with ```--with-cv-impl=stl11```

@somdoron this comes from the mailbox_safe:

https://github.com/zeromq/libzmq/blob/master/src/mailbox_safe.cpp#L109

> EINVAL
> Different mutexes were supplied for concurrent pthread_cond_timedwait() or pthread_cond_wait() operations on the same condition variable.

https://linux.die.net/man/3/pthread_cond_wait

As far as I can see, there's only one mutex (from the socket_base) being used with a safe mailbox. Any idea?

**Comment by somdoron** [comment]
Only thing that comes to mind is trying closing thread safe socket while another thread tries to send or receive. Which is not supported.

**Comment by wzli** [comment]
> Only thing that comes to mind is trying closing thread safe socket while another thread tries to send or receive. Which is not supported.

You mean calling somewhere calling zmq_close? I don't think that's happening. I'm using cppzmq ATM which triggers close in the socket_t destructor, but the socket is kept in scope for the duration of the program.

**Comment by somdoron** [comment]
Are you using the socket from multiple threads?

**Comment by somdoron** [comment]
@bluca I actually suspect the timeout parameter, which can also cause EINVL

**Comment by somdoron** [comment]
> EINVAL
> The value specified by cond, mutex, or abstime is invalid.

**Comment by somdoron** [comment]
@wzli I think the following commit might solve the issue:

https://github.com/zeromq/libzmq/commit/462dd36d0ee7d75f50529739e8c69f644c68e852#diff-35db4a1c7f2728c0828222b44157bc88

I suspect that for zero timeout, the condition variable for time to time can return with EINVL if the timeout end-up being in the past.

**Comment by somdoron** [comment]
> The pthread_cond_timedwait() function shall be equivalent to pthread_cond_wait(), except that an error is returned if the absolute time specified by abstime passes (that is, system time equals or exceeds abstime) before the condition cond is signaled or broadcasted, or if the absolute time specified by abstime has already been passed at the time of the call.

The docs doesn't specify which error, anyway, we might want to treat EINVAL as a valid return code.

**Comment by bluca** [comment]
> @wzli I think the following commit might solve the issue:
> 
> [462dd36#diff-35db4a1c7f2728c0828222b44157bc88](https://github.com/zeromq/libzmq/commit/462dd36d0ee7d75f50529739e8c69f644c68e852#diff-35db4a1c7f2728c0828222b44157bc88)
> 
> I suspect that for zero timeout, the condition variable for time to time can return with EINVL if the timeout end-up being in the past.

The tested versions as reported both contain that commit though

**Comment by bluca** [comment]
> > The pthread_cond_timedwait() function shall be equivalent to pthread_cond_wait(), except that an error is returned if the absolute time specified by abstime passes (that is, system time equals or exceeds abstime) before the condition cond is signaled or broadcasted, or if the absolute time specified by abstime has already been passed at the time of the call.
> 
> The docs doesn't specify which error, anyway, we might want to treat EINVAL as a valid return code.

It should be ETIMEDOUT, no?

**Comment by somdoron** [comment]
I'm not sure... Trying to check the source code now...

**Comment by bluca** [comment]
> I'm not sure... Trying to check the source code now...

Documentation says so:

> ETIMEDOUT
> The time specified by abstime to pthread_cond_timedwait() has passed.

**Comment by somdoron** [comment]
But not when entering the function...

Anyway, compare the following:

https://github.com/zeromq/libzmq/blob/v4.3.2/src/condition_variable.hpp#L283

https://code.woboq.org/userspace/glibc/nptl/pthread_cond_wait.c.html#665

So when in every 1000000000 this can fail... I don't think this is the issue.

**Comment by bluca** [comment]
> But not when entering the function...
> 
> Anyway, compare the following:
> 
> https://github.com/zeromq/libzmq/blob/v4.3.2/src/condition_variable.hpp#L283
> 
> https://code.woboq.org/userspace/glibc/nptl/pthread_cond_wait.c.html#665
> 
> So when in every 1000000000 this can fail... I don't think this is the issue.

Er, clock_gettime can return an error, but we ignore it... manpage says it's mostly setup errors, but still, might want to change that - if it doesn't touch the timespec on failure, its content will be initialized and then we add to it, so the time could be completely bogus. A bit of a long shot perhaps, but you never know...

**Comment by somdoron** [comment]
Or maybe it is?

**Comment by somdoron** [comment]
@wzli can you check with following commit:

https://github.com/zeromq/libzmq/commit/fb852fd3e712ef26cf67a5b4ee4e85b7eb4affba

**Comment by bluca** [comment]
> @wzli can you check with following commit:
> 
> [fb852fd](https://github.com/zeromq/libzmq/commit/fb852fd3e712ef26cf67a5b4ee4e85b7eb4affba)

Given it was reported to be a rare occurrence, there are good chances you are on the right path. Both changes seem the right thing to do regardless of this specific instance, so could you send a PR anyway?

**Comment by somdoron** [comment]
done

**Comment by wzli** [comment]
> Are you using the socket from multiple threads?

Yes, well it was mentioned that radio dish was supposedly threadsafe? Either way, there’s two threads that are calling connect, disconnect, and send on the radio socket. To be safe I additionally added a mutex to protected it the access.

**Comment by wzli** [comment]
I kept the system running overnight with the same setup on v4.3.2 in hopes of catching it again, and this try to log the error code and grab the core dump etc. Unfortunately haven’t encountered it again. Think I'll try some more before testing out the fix. Thanks guys.

**Comment by somdoron** [comment]
Yes, they are thread safe. No need for a mutex.

**Comment by somdoron** [comment]
@wzli If my assumption is correct, it happens once in a billion times...

**Comment by wzli** [comment]
I've been trying to reproduce this on v4.3.2 to get a concise coredump. Caught it again after leaving the system running for a couple of days. Unfortunately, the timeout variable in zmq::condition_variable_t::wait was optimized out, so can't directly confirm the theory. (I also tried debug builds for libzmq but that kept segfaulting is that expected?). The timeout variable in zmq::socket_base_t::recv is 2, though, wondering if that's related.

In anycase, I'll try the fix moving forwards, if the problem doesn't occur after a weekish of operation then it's probably safe.

```
(gdb) bt full
#0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:51
        set = {__val = {0, 0, 0, 0, 0, 0, 140545983408624, 3078627174789693184, 4134925906226985011, 0, 140545983409024, 140545983408688, 140546025278740, 0, 140545983409024, 140546023700062}}
        pid = <optimized out>
        tid = <optimized out>
        ret = <optimized out>
#1  0x00007fd36bd21801 in __GI_abort () at abort.c:79
        save_stage = 1
        act = {__sigaction_handler = {sa_handler = 0x7fd3696a6b90, sa_sigaction = 0x7fd3696a6b90}, sa_mask = {__val = {140546025280104, 140546040383784, 308, 93827078881936, 93827078882376, 0, 140546024139560, 140545983409184,
              5292960908, 93827069629408, 3078627174789693184, 140545983409136, 22, 140545983409280, 140545983411808, 22}}, sa_flags = 1812780672, sa_restorer = 0x7fd36c0cd840 <stderr>}
        sigs = {__val = {32, 0 <repeats 15 times>}}
        __cnt = <optimized out>
        __set = <optimized out>
        __cnt = <optimized out>
        __set = <optimized out>
#2  0x00007fd36cca075e in zmq::zmq_abort (errmsg_=errmsg_@entry=0x7fd36be95268 "Invalid argument") at /opt/primordial_particles/VirtualSpaceMeshnet/submodules/libzmq/src/err.cpp:88
No locals.
#3  0x00007fd36cca54ee in zmq::condition_variable_t::wait (timeout_=<optimized out>, mutex_=<optimized out>, this=0x5555d1b50448) at /opt/primordial_particles/VirtualSpaceMeshnet/submodules/libzmq/src/condition_variable.hpp:308
        errstr = 0x7fd36be95268 "Invalid argument"
        rc = 22
        rc = <optimized out>
        timeout = <optimized out>
        errstr = <optimized out>
#4  zmq::mailbox_safe_t::recv (this=0x5555d1b503e0, cmd_=<optimized out>, timeout_=<optimized out>) at /opt/primordial_particles/VirtualSpaceMeshnet/submodules/libzmq/src/mailbox_safe.cpp:109
        rc = <optimized out>
        ok = <optimized out>
        rc = <optimized out>
        errstr = <optimized out>
#5  0x00007fd36ccc40f7 in zmq::socket_base_t::process_commands (this=this@entry=0x5555d1b4fce0, timeout_=2, throttle_=throttle_@entry=false) at /opt/primordial_particles/VirtualSpaceMeshnet/submodules/libzmq/src/socket_base.cpp:1365
        cmd = {destination = 0x5555d1b49b30, type = 3518300912, args = {stop = {<No data fields>}, plug = {<No data fields>}, own = {object = 0x5555d1b49b30}, attach = {engine = 0x5555d1b49b30}, bind = {pipe = 0x5555d1b49b30},
            activate_read = {<No data fields>}, activate_write = {msgs_read = 93827078855472}, hiccup = {pipe = 0x5555d1b49b30}, pipe_term = {<No data fields>}, pipe_term_ack = {<No data fields>}, pipe_hwm = {inhwm = -776692944,
              outhwm = 21845}, term_req = {object = 0x5555d1b49b30}, term = {linger = -776692944}, term_ack = {<No data fields>}, term_endpoint = {endpoint = 0x5555d1b49b30}, reap = {socket = 0x5555d1b49b30},
            reaped = {<No data fields>}, pipe_peer_stats = {queue_count = 93827078855472, socket_base = 0x7fd36cca0a0f <zmq::fq_t::recvpipe(zmq::msg_t*, zmq::pipe_t**)+191>, endpoint_pair = 0x5555d1b4fce0}, pipe_stats_publish = {
              outbound_queue_count = 93827078855472, inbound_queue_count = 140546040007183, endpoint_pair = 0x5555d1b4fce0}, done = {<No data fields>}}}
        rc = <optimized out>
#6  0x00007fd36ccc5526 in zmq::socket_base_t::recv (this=this@entry=0x5555d1b4fce0, msg_=msg_@entry=0x5555d1b49b30, flags_=flags_@entry=0) at /opt/primordial_particles/VirtualSpaceMeshnet/submodules/libzmq/src/socket_base.cpp:1250
        sync_lock = {_mutex = 0x5555d1b50290}
        rc = <optimized out>
        timeout = 2
        end = <optimized out>
        block = <optimized out>
#7  0x00007fd36ccea3bc in s_recvmsg (flags_=0, msg_=0x5555d1b49b30, s_=0x5555d1b4fce0) at /opt/primordial_particles/VirtualSpaceMeshnet/submodules/libzmq/src/zmq.cpp:454
        rc = <optimized out>
        sz = <optimized out>
        rc = <optimized out>
        sz = <optimized out>
#8  zmq_msg_recv (msg_=0x5555d1b49b30, s_=0x5555d1b4fce0, flags_=0) at /opt/primordial_particles/VirtualSpaceMeshnet/submodules/libzmq/src/zmq.cpp:600
        s = <optimized out>
#9  0x00005555d10662fc in vsm::ZmqTransport::poll(std::chrono::duration<long, std::ratio<1l, 1000l> >) ()
No symbol table info available.
#10 0x00005555d102d7d4 in std::thread::_State_impl<std::thread::_Invoker<std::tuple<main::{lambda()#10}> > >::_M_run() ()
No symbol table info available.
#11 0x00007fd36c7456df in ?? () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
No symbol table info available.
#12 0x0000000000000000 in ?? ()
No symbol table info available.
```

**Comment by wzli** [comment]
Tried the fix, left the system running for almost a week, haven't ran into the issue. Tentatively considered fixed.
