### ISSUE TITLE
zeromq-4.2.2: first message not published

### ISSUE THREAD

**Issue by robmool** [zeromq/libzmq#3978]
# Issue description
In several projects we're using ZMQ (zeromq-4.2.2) to send/receive messages over the Internet using the following scheme:

A ZMQ proxy setup with the zmq_proxy() function which is always running under normal circumstances.

All the clients (ZMQ_PUB and ZMQ_SUB) connect to the ZMQ proxy using the following setup:
zmq_ctx_new()
zmq_socket()
zmq_setsockopt()
zmq_connect()

The problem is that the proxy doesn't receive the first message when publishing right after the zmq_connect() call which makes perfectly sense since the TCP socket is still in progress. For the time being I've put a sleep of several milliseconds after the zmq_connect() but this is not the right solution.

I've also tried to use the ZMQ_CONNECT_TIMEOUT option but doesn't seem to have any affect.
Is there a way to check the socket status ("in progress", "connected", "timeout", "closed", etc.)?

# Environment
* libzmq version (commit hash if unreleased): 4.2.2
* OS: Linux

**Comment by bluca** [comment]
PUB is lossy by definition. Please read the zguide: http://zguide.zeromq.org/page:all

**Comment by robmool** [comment]
Is there a way to check the socket status ("in progress", "connected", "timeout", "closed", etc.)?

**Comment by bluca** [comment]
No - please read the zguide
