### ISSUE TITLE
libzmq websocket transport usage problem in "zmq_bind".

### ISSUE THREAD

**Issue by HEIDIES** [zeromq/libzmq#3995]
*Please use this template for reporting suspected bugs or requests for help.*

# Issue description

I have compiled libzmq from source with  "ENABLE_DRAFTS". Everything went on okay until failed on binding a Websocket port

# Environment

* libzmq version (commit hash if unreleased): v4.3.2
* OS: ubuntu 18.04 LTS

# Minimal test code / Steps to reproduce the issue

1.  `void *context = zmq_ctx_new ();
    void *pub = zmq_socket (context, ZMQ_PUB);
    int rc = zmq_bind(pub, "ws://127.0.0.1:5001/zeromq");
    assert (rc == 0);`

# What's the actual result? (include assertion message & call stack if applicable)

assert failed.

# What's the expected result?

assert succeed.

**Comment by bluca** [comment]
Did ./configure confirm that WS was enabled?

**Comment by HEIDIES** [comment]
It reminds me that I should set --enable-drafts flag while ./configure.
