### ISSUE TITLE
configure: error: None of 'kqueue epoll devpoll pollset poll select' are valid pollers on this platform

### ISSUE THREAD

**Issue by zouaixu** [zeromq/libzmq#3999]
*Please use this template for reporting suspected bugs or requests for help.*

# Issue description
when I use zeromq 4.2.5 edtion do configure, on AIX  use cmd  ./configure CC=xlc CXX=xlC

the last error fllowing:

checking whether we are using Sun Studio C++ compiler... no
checking whether we are using clang C++ compiler... no
checking whether we are using gcc >= 4 C++ compiler... no
checking whether to enable debugging information... no
checking whether to enable code coverage... no
checking if TIPC is available and supports nonblocking connect... no
checking whether to enable ASan... no
checking for pthread_create in -lpthread... no
checking for clock_gettime in -lrt... no
checking whether C++ compiler supports dso visibility... no
checking for asciidoc... no
checking for xmlto... no
checking whether to build documentation... no
checking whether to install manpages... yes
configure: Choosing polling system from 'kqueue epoll devpoll pollset poll select'...
configure: error: None of 'kqueue epoll devpoll pollset poll select' are valid pollers on this platform

# Environment

* libzmq version    zeromq 4.2.5
* OS: AIX 7.1

how to solve this ?

**Comment by bluca** [comment]
Looks like a problem with that proprietary compiler - the build test to see which poll syscall is available fails. You should check the config.log and ask for support from the compiler vendor
