### ISSUE TITLE
use zeromq-4.3.2 on AIX and xlc compile failed.

### ISSUE THREAD

**Issue by zouaixu** [zeromq/libzmq#4000]
*Please use this template for reporting suspected bugs or requests for help.*

# Issue description
when I  use  zeromq-4.3.2 on AIX 7.1.0,    
./configure CC=xlc CXX=xlC
gmake

the result is:

# gmake
Making all in doc
gmake[1]: Entering directory '/opt/dev/lib/zeromq-4.3.2/doc'
gmake[1]: Nothing to be done for 'all'.
gmake[1]: Leaving directory '/opt/dev/lib/zeromq-4.3.2/doc'
gmake[1]: Entering directory '/opt/dev/lib/zeromq-4.3.2'
  CXX      tests/tests_libtestutil_a-testutil.o
/opt/IBM/xlC/16.1.0/bin/.orig/xlC: 1501-210 (S) command option Wno-long-long contains an incorrect subargument
Makefile:4169: recipe for target 'tests/tests_libtestutil_a-testutil.o' failed
gmake[1]: *** [tests/tests_libtestutil_a-testutil.o] Error 40
gmake[1]: Leaving directory '/opt/dev/lib/zeromq-4.3.2'
Makefile:6680: recipe for target 'all-recursive' failed
gmake: *** [all-recursive] Error 1

when use make :

# make
"Makefile", line 7968: make: 1254-055 Dependency line needs colon or double colon operator.
"Makefile", line 7969: make: 1254-055 Dependency line needs colon or double colon operator.
"Makefile", line 7970: make: 1254-055 Dependency line needs colon or double colon operator.
"Makefile", line 7971: make: 1254-055 Dependency line needs colon or double colon operator.
"Makefile", line 7973: make: 1254-055 Dependency line needs colon or double colon operator.
"Makefile", line 7974: make: 1254-055 Dependency line needs colon or double colon operator.
"Makefile", line 7975: make: 1254-055 Dependency line needs colon or double colon operator.
"Makefile", line 7976: make: 1254-055 Dependency line needs colon or double colon operator.
"Makefile", line 7977: make: 1254-055 Dependency line needs colon or double colon operator.
"Makefile", line 7978: make: 1254-055 Dependency line needs colon or double colon operator.
"Makefile", line 7979: make: 1254-055 Dependency line needs colon or double colon operator.
"Makefile", line 7982: make: 1254-055 Dependency line needs colon or double colon operator.
"Makefile", line 7983: make: 1254-055 Dependency line needs colon or double colon operator.
"Makefile", line 7984: make: 1254-055 Dependency line needs colon or double colon operator.
"Makefile", line 7986: make: 1254-055 Dependency line needs colon or double colon operator.
"Makefile", line 8022: make: 1254-055 Dependency line needs colon or double colon operator.
"Makefile", line 8058: make: 1254-055 Dependency line needs colon or double colon operator.
"Makefile", line 8059: make: 1254-055 Dependency line needs colon or double colon operator.
"Makefile", line 8060: make: 1254-055 Dependency line needs colon or double colon operator.
"Makefile", line 8061: make: 1254-055 Dependency line needs colon or double colon operator.
"Makefile", line 8062: make: 1254-055 Dependency line needs colon or double colon operator.
"Makefile", line 8063: make: 1254-055 Dependency line needs colon or double colon operator.
"Makefile", line 8079: make: 1254-055 Dependency line needs colon or double colon operator.
"Makefile", line 8081: make: 1254-055 Dependency line needs colon or double colon operator.
"Makefile", line 8083: make: 1254-055 Dependency line needs colon or double colon operator.
"Makefile", line 8087: make: 1254-055 Dependency line needs colon or double colon operator.
"Makefile", line 8093: make: 1254-055 Dependency line needs colon or double colon operator.
"Makefile", line 8095: make: 1254-055 Dependency line needs colon or double colon operator.
"Makefile", line 8109: make: 1254-055 Dependency line needs colon or double colon operator.
"Makefile", line 8115: make: 1254-055 Dependency line needs colon or double colon operator.
"Makefile", line 8117: make: 1254-055 Dependency line needs colon or double colon operator.
"Makefile", line 8120: make: 1254-055 Dependency line needs colon or double colon operator.
"Makefile", line 8126: make: 1254-055 Dependency line needs colon or double colon operator.
"Makefile", line 8128: make: 1254-055 Dependency line needs colon or double colon operator.
"Makefile", line 8131: make: 1254-055 Dependency line needs colon or double colon operator.
"Makefile", line 8137: make: 1254-055 Dependency line needs colon or double colon operator.
"Makefile", line 8139: make: 1254-055 Dependency line needs colon or double colon operator.
"Makefile", line 8142: make: 1254-055 Dependency line needs colon or double colon operator.
"Makefile", line 8148: make: 1254-055 Dependency line needs colon or double colon operator.
"Makefile", line 8150: make: 1254-055 Dependency line needs colon or double colon operator.
"Makefile", line 8153: make: 1254-055 Dependency line needs colon or double colon operator.
"Makefile", line 8159: make: 1254-055 Dependency line needs colon or double colon operator.
"Makefile", line 8161: make: 1254-055 Dependency line needs colon or double colon operator.
"Makefile", line 8163: make: 1254-055 Dependency line needs colon or double colon operator.
"Makefile", line 8166: make: 1254-055 Dependency line needs colon or double colon operator.
make: 1254-058 Fatal errors encountered -- cannot continue.

what should I do?

**Comment by bluca** [comment]
Looks like a problem in your build environment. I imagine xlC is some proprietary compiler? You should ask for support from the compiler vendor.

**Comment by zouaixu** [comment]
did you done test on AIX platform whit  the new edition?

**Comment by bluca** [comment]
No, nobody here has access to AIX

**Comment by zouaixu** [comment]
# gmake
Making all in doc
gmake[1]: Entering directory '/opt/dev/lib/zeromq-4.3.2/doc'
gmake[1]: Nothing to be done for 'all'.
gmake[1]: Leaving directory '/opt/dev/lib/zeromq-4.3.2/doc'
gmake[1]: Entering directory '/opt/dev/lib/zeromq-4.3.2'
  CXX      tests/tests_libtestutil_a-testutil.o
"/usr/include/stddef.h", line 59.25: 1540-0063 (S) The text "unsigned" is unexpected.
"/usr/include/stdio.h", line 79.32: 1540-0063 (S) The text ";" is unexpected.
Makefile:4169: recipe for target 'tests/tests_libtestutil_a-testutil.o' failed
gmake[1]: *** [tests/tests_libtestutil_a-testutil.o] Error 1
gmake[1]: Leaving directory '/opt/dev/lib/zeromq-4.3.2'
Makefile:6680: recipe for target 'all-recursive' failed
gmake: *** [all-recursive] Error 1

there is another  error

**Comment by bluca** [comment]
/usr/include is from the proprietary os/compiler you are using, you need to ask support from the vendor

**Comment by zouaixu** [comment]
I now use ./configure CC=xlclang   CXX=xlclang++  on AIX and whith zeromq-4.3.2.

# ./configure CC=xlclang   CXX=xlclang++
checking for a BSD-compatible install... config/install-sh -c
checking whether build environment is sane... yes
checking for a thread-safe mkdir -p... config/install-sh -c -d
checking for gawk... no
checking for mawk... no
checking for nawk... nawk
checking whether make sets $(MAKE)... yes
checking whether make supports nested variables... yes
checking whether UID '0' is supported by ustar format... yes
checking whether GID '0' is supported by ustar format... yes
checking how to create a ustar tar archive... plaintar
checking whether make supports nested variables... (cached) yes
checking for gcc... xlclang
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether xlclang accepts -g... yes
checking for xlclang option to accept ISO C89... none needed
checking whether xlclang understands -c and -o together... yes
checking for style of include used by make... GNU
checking dependency style of xlclang... gcc3
checking whether C compiler accepts -std=gnu11... yes
./configure[5189]: CFLAGS+= -std=gnu11:  not found
checking whether we are using the GNU C++ compiler... yes
checking whether xlclang++ accepts -g... yes
checking dependency style of xlclang++... gcc3
checking for a sed that does not truncate output... /usr/bin/sed
checking whether to build with code coverage support... no
checking for a sed that does not truncate output... (cached) /usr/bin/sed
checking for gawk... (cached) nawk
checking for pkg-config... no
checking for xmlto... no
checking for asciidoc... no
checking build system type... powerpc-ibm-aix7.1.0.0
checking host system type... powerpc-ibm-aix7.1.0.0
checking how to print strings... print -r
checking for a sed that does not truncate output... (cached) /usr/bin/sed
checking for grep that handles long lines and -e... /usr/bin/grep
checking for egrep... /usr/bin/grep -E
checking for fgrep... /usr/bin/grep -F
checking for ld used by xlclang... /bin/ld
checking if the linker (/bin/ld) is GNU ld... no
checking for BSD- or MS-compatible name lister (nm)... /usr/bin/nm -B
checking the name lister (/usr/bin/nm -B) interface... BSD nm
checking whether ln -s works... yes
checking the maximum length of command line arguments... 786432
checking whether the shell understands some XSI constructs... yes
checking whether the shell understands "+="... no
checking how to convert powerpc-ibm-aix7.1.0.0 file names to powerpc-ibm-aix7.1.0.0 format... func_convert_file_noop
checking how to convert powerpc-ibm-aix7.1.0.0 file names to toolchain format... func_convert_file_noop
checking for /bin/ld option to reload object files... -r
checking for objdump... objdump
checking how to recognize dependent libraries... pass_all
checking for dlltool... dlltool
checking how to associate runtime and link libraries... print -r --
checking for ar... ar
checking for archiver @FILE support... no
checking for strip... strip
checking for ranlib... ranlib
checking command to parse /usr/bin/nm -B output from xlclang object... ok
checking for sysroot... no
checking for mt... mt
checking if mt is a manifest tool... no
checking how to run the C preprocessor... xlclang -E
checking for ANSI C header files... yes
checking for sys/types.h... yes
checking for sys/stat.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for memory.h... yes
checking for strings.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for unistd.h... yes
checking for dlfcn.h... yes
checking for objdir... .libs
checking if xlclang supports -fno-rtti -fno-exceptions... yes
checking for xlclang option to produce PIC...  -DPIC
checking if xlclang PIC flag  -DPIC works... yes
checking if xlclang static flag -static works... no
checking if xlclang supports -c -o file.o... yes
checking if xlclang supports -c -o file.o... (cached) yes
checking whether the xlclang linker (/bin/ld) supports shared libraries... yes
checking dynamic linker characteristics... /opt/IBM/xlC/16.1.0/bin/.orig/xlclang: error: 1501-294 No input file specified. Please use -qhelp for more information.
aix7.1.0.0 ld.so
checking how to hardcode library paths into programs... immediate
checking whether stripping libraries is possible... no
checking if libtool supports shared libraries... yes
checking whether to build shared libraries... yes
checking whether to build static libraries... no
checking how to run the C++ preprocessor... xlclang++ -E
checking for ld used by xlclang++... /bin/ld
checking if the linker (/bin/ld) is GNU ld... no
checking whether the xlclang++ linker (/bin/ld) supports shared libraries... yes
checking for xlclang++ option to produce PIC...  -DPIC
checking if xlclang++ PIC flag  -DPIC works... yes
checking if xlclang++ static flag -static works... no
checking if xlclang++ supports -c -o file.o... yes
checking if xlclang++ supports -c -o file.o... (cached) yes
checking whether the xlclang++ linker (/bin/ld) supports shared libraries... yes
checking dynamic linker characteristics... aix7.1.0.0 ld.so
checking how to hardcode library paths into programs... immediate
checking for valgrind... no
checking linker version script flag... unsupported
checking for working posix_memalign... yes
checking whether xlclang++ supports C++11 features by default... yes
checking whether the C compiler works... yes
checking whether we are using Intel C compiler... no
checking whether we are using Sun Studio C compiler... no
checking whether we are using clang C compiler... yes
checking whether we are using gcc >= 4 C compiler... yes
checking whether the C++ compiler works... yes
checking whether we are using Intel C++ compiler... no
checking whether we are using Sun Studio C++ compiler... no
checking whether we are using clang C++ compiler... yes
checking whether we are using gcc >= 4 C++ compiler... yes
checking whether to enable debugging information... no
checking whether to enable code coverage... no
checking if TIPC is available and supports nonblocking connect... no
checking whether to enable ASan... no
checking for pthread_create in -lpthread... yes
checking for clock_gettime in -lrt... yes
checking whether C++ compiler supports -fvisibility=hidden... yes
checking whether C++ compiler supports dso visibility... yes
checking for asciidoc... no
checking for xmlto... no
checking whether to build documentation... no
checking whether to install manpages... yes
configure: Choosing I/O thread polling system from 'kqueue epoll devpoll pollset poll select'...
configure: Using 'pollset' I/O thread polling system
configure: Using 'poll' zmq_poll(er)_* API polling system
checking for getconf... getconf
configure: Using "64" bytes alignment for lock-free data structures
checking condition_variable usability... yes
checking condition_variable presence... yes
checking for condition_variable... yes
configure: Using "auto" condition variable implementation.
checking for ANSI C header files... (cached) yes
checking errno.h usability... yes
checking errno.h presence... yes
checking for errno.h... yes
checking time.h usability... yes
checking time.h presence... yes
checking for time.h... yes
checking for unistd.h... (cached) yes
checking limits.h usability... yes
checking limits.h presence... yes
checking for limits.h... yes
checking stddef.h usability... yes
checking stddef.h presence... yes
checking for stddef.h... yes
checking for stdlib.h... (cached) yes
checking for string.h... (cached) yes
checking arpa/inet.h usability... yes
checking arpa/inet.h presence... yes
checking for arpa/inet.h... yes
checking netinet/tcp.h usability... no
checking netinet/tcp.h presence... yes
configure: WARNING: netinet/tcp.h: present but cannot be compiled
configure: WARNING: netinet/tcp.h:     check for missing prerequisite headers?
configure: WARNING: netinet/tcp.h: see the Autoconf documentation
configure: WARNING: netinet/tcp.h:     section "Present But Cannot Be Compiled"
configure: WARNING: netinet/tcp.h: proceeding with the compiler's result
configure: WARNING:     ## ------------------------------------------ ##
configure: WARNING:     ## Report this to zeromq-dev@lists.zeromq.org ##
configure: WARNING:     ## ------------------------------------------ ##
checking for netinet/tcp.h... no
checking netinet/in.h usability... yes
checking netinet/in.h presence... yes
checking for netinet/in.h... yes
checking sys/socket.h usability... yes
checking sys/socket.h presence... yes
checking for sys/socket.h... yes
checking sys/time.h usability... yes
checking sys/time.h presence... yes
checking for sys/time.h... yes
checking ifaddrs.h usability... no
checking ifaddrs.h presence... no
checking for ifaddrs.h... no
checking sys/uio.h usability... yes
checking sys/uio.h presence... yes
checking for sys/uio.h... yes
checking sys/eventfd.h usability... no
checking sys/eventfd.h presence... no
checking for sys/eventfd.h... no
checking whether SO_PEERCRED is declared... no
checking whether LOCAL_PEERCRED is declared... no
checking for stdbool.h that conforms to C99... no
checking for _Bool... no
checking for an ANSI C-conforming const... yes
checking for inline... inline
checking for size_t... yes
checking for ssize_t... yes
checking whether time.h and sys/time.h may both be included... yes
checking for uint32_t... yes
checking for working volatile... yes
configure: Using tweetnacl for CURVE security
checking "with_norm_ext = no"... no
checking how to enable additional warnings for C++ compiler... -Wall
checking how to turn warnings to errors in C++ compiler... -Werror
checking how to enable strict standards compliance in C++ compiler... -pedantic
checking whether C++ compiler accepts -Wno-atomic-alignment... no
checking whether compiler supports __atomic_Xxx intrinsics... yes
checking return type of signal handlers... void
checking for perror... yes
checking for gettimeofday... yes
checking for clock_gettime... yes
checking for memset... yes
checking for socket... yes
checking for getifaddrs... no
checking for freeifaddrs... no
checking for fork... yes
checking for mkdtemp... yes
checking for accept4... no
checking alloca.h usability... yes
checking alloca.h presence... yes
checking for alloca.h... yes
checking whether strnlen is available... yes
checking whether signature of pthread_setname_np() has 1 argument... no
checking whether signature of pthread_setname_np() has 2 arguments... no
checking whether signature of pthread_setname_np() has 3 arguments... no
checking whether pthread_set_name_np() exists... no
checking whether pthread_setaffinity_np() exists... no
checking whether SOCK_CLOEXEC is supported... no
checking whether O_CLOEXEC is supported... no
checking whether SO_BINDTODEVICE is supported... no
checking whether SO_KEEPALIVE is supported... yes
checking whether TCP_KEEPCNT is supported... yes
checking whether TCP_KEEPIDLE is supported... yes
checking whether TCP_KEEPINTVL is supported... yes
checking whether TCP_KEEPALIVE is supported... no
checking whether getrandom is supported... no
checking for ./.git... no
configure: Building stable and legacy API (no draft API)
checking for LIBUNWIND... no
configure: WARNING: Cannot find libunwind
configure: Using mtree implementation to manage subscriptions
checking for clang-format... no
checking whether C compiler accepts -Wno-tautological-constant-compare... no
checking whether C++ compiler accepts -Wno-tautological-constant-compare... no
checking that generated files are newer than configure... done
configure: creating ./config.status
config.status: creating Makefile
config.status: creating src/libzmq.pc
config.status: creating doc/Makefile
config.status: creating builds/Makefile
config.status: creating builds/deprecated-msvc/Makefile
config.status: creating src/platform.hpp
config.status: executing depfiles commands
config.status: executing libtool commands
# cd /
# pwd  
/
# find ./ -name xlclang
./opt/IBM/xlC/16.1.0/bin/.orig/xlclang
./opt/IBM/xlC/16.1.0/bin/xlclang
