### ISSUE TITLE
Undefined references to (GSSAPI) functions using Ubuntu

### ISSUE THREAD

**Issue by ChrisCharrison** [zeromq/libzmq#4008]
# Issue description
Since updating to the most recent packages, I cannot build my program on Ubuntu 18/20.

I get a linkage error related to gssapi. The error seems related to libzmq/Ubuntu rather than our project.

# Environment
Non virtual machine, fresh install on ssd, tried two Linux installs with different ISOs
* libzmq version (commit hash if unreleased): 
newest version (4.3.2-2ubuntu1).
* OS: 
Ubuntu 18 or Ubuntu 20

The versions of the other dependencies of my program are below, incase you are aware of conflicts:
`Note, selecting 'libunwind-dev' instead of 'libunwind8-dev'

Note, selecting 'libreadline-dev' instead of 'libreadline6-dev'

build-essential is already the newest version (12.8ubuntu1).

cmake is already the newest version (3.16.3-1ubuntu1).

libexpat1-dev is already the newest version (2.2.9-1build1).

liblzma-dev is already the newest version (5.2.4-1).

libreadline-dev is already the newest version (8.0-4).

libsodium-dev is already the newest version (1.0.18-1).

libssl-dev is already the newest version (1.1.1f-1ubuntu2).

libunwind-dev is already the newest version (1.2.1-9build1).

pkg-config is already the newest version (0.29.1-0ubuntu4).

doxygen is already the newest version (1.8.17-0ubuntu2).

graphviz is already the newest version (2.42.2-3build2).

libboost-all-dev is already the newest version (1.71.0.0ubuntu2).
libldns-dev is already the newest version (1.7.0-4.1ubuntu1).

libpgm-dev is already the newest version (5.2.122~dfsg-3ubuntu1).

libzmq3-dev is already the newest version (4.3.2-2ubuntu1).

libunbound-dev is already the newest version (1.9.4-2ubuntu1.1).`

# Minimal test code / Steps to reproduce the issue
Recloning code, reinstalling operating system, reinstalling dependencies, containerisation etc 

# What's the actual result? (include assertion message & call stack if applicable)
`/usr/bin/ld: /usr/lib/gcc/x86_64-linux-gnu/9/../../../x86_64-linux-gnu/libzmq.a(libzmq_la-gssapi_client.o): in function `zmq::gssapi_client_t::~gssapi_client_t()':
(.text+0x5d): undefined reference to `gss_release_cred'
/usr/bin/ld: /usr/lib/gcc/x86_64-linux-gnu/9/../../../x86_64-linux-gnu/libzmq.a(libzmq_la-gssapi_client.o): in function `zmq::gssapi_client_t::process_next_token(zmq::msg_t*) [clone .part.0]':
(.text+0x246): undefined reference to `gss_release_name'
/usr/bin/ld: /usr/lib/gcc/x86_64-linux-gnu/9/../../../x86_64-linux-gnu/libzmq.a(libzmq_la-gssapi_client.o): in function `zmq::gssapi_client_t::~gssapi_client_t()':
(.text+0x780): undefined reference to `gss_release_cred'
/usr/bin/ld: /usr/lib/gcc/x86_64-linux-gnu/9/../../../x86_64-linux-gnu/libzmq.a(libzmq_la-gssapi_client.o): in function `zmq::gssapi_client_t::initialize_context()':
(.text+0x7fd): undefined reference to `gss_init_sec_context'
/usr/bin/ld: (.text+0x84d): undefined reference to `gss_import_name'
/usr/bin/ld: /usr/lib/gcc/x86_64-linux-gnu/9/../../../x86_64-linux-gnu/libzmq.a(libzmq_la-gssapi_client.o): in function `zmq::gssapi_client_t::produce_next_token(zmq::msg_t*)':
(.text+0x8a0): undefined reference to `gss_release_buffer'
/usr/bin/ld: (.text+0x8c2): undefined reference to `gss_release_buffer'
/usr/bin/ld: (.text+0x8ce): undefined reference to `gss_release_name'
/usr/bin/ld: (.text+0x8e2): undefined reference to `gss_release_name'
/usr/bin/ld: (.text+0x8f7): undefined reference to `gss_delete_sec_context'
/usr/bin/ld: /usr/lib/gcc/x86_64-linux-gnu/9/../../../x86_64-linux-gnu/libzmq.a(libzmq_la-gssapi_server.o): in function `zmq::gssapi_server_t::~gssapi_server_t()':
(.text+0x21c): undefined reference to `gss_release_cred'
/usr/bin/ld: (.text+0x230): undefined reference to `gss_release_name'
/usr/bin/ld: /usr/lib/gcc/x86_64-linux-gnu/9/../../../x86_64-linux-gnu/libzmq.a(libzmq_la-gssapi_server.o): in function `zmq::gssapi_server_t::~gssapi_server_t()':
(.text+0x36a): undefined reference to `gss_release_cred'
/usr/bin/ld: (.text+0x37e): undefined reference to `gss_release_name'
/usr/bin/ld: /usr/lib/gcc/x86_64-linux-gnu/9/../../../x86_64-linux-gnu/libzmq.a(libzmq_la-gssapi_server.o): in function `zmq::gssapi_server_t::send_zap_request()':
(.text+0x423): undefined reference to `gss_display_name'
/usr/bin/ld: (.text+0x44c): undefined reference to `gss_release_buffer'
/usr/bin/ld: /usr/lib/gcc/x86_64-linux-gnu/9/../../../x86_64-linux-gnu/libzmq.a(libzmq_la-gssapi_server.o): in function `zmq::gssapi_server_t::produce_next_token(zmq::msg_t*)':
(.text+0x4ae): undefined reference to `gss_release_buffer'
/usr/bin/ld: (.text+0x4c0): undefined reference to `gss_release_name'
/usr/bin/ld: (.text+0x4d5): undefined reference to `gss_delete_sec_context'
/usr/bin/ld: /usr/lib/gcc/x86_64-linux-gnu/9/../../../x86_64-linux-gnu/libzmq.a(libzmq_la-gssapi_server.o): in function `zmq::gssapi_server_t::process_next_token(zmq::msg_t*)':
(.text+0x5ca): undefined reference to `gss_release_name'
/usr/bin/ld: /usr/lib/gcc/x86_64-linux-gnu/9/../../../x86_64-linux-gnu/libzmq.a(libzmq_la-gssapi_server.o): in function `zmq::gssapi_server_t::accept_context()':
(.text+0x60a): undefined reference to `gss_accept_sec_context'
/usr/bin/ld: /usr/lib/gcc/x86_64-linux-gnu/9/../../../x86_64-linux-gnu/libzmq.a(libzmq_la-gssapi_mechanism_base.o): in function `zmq::gssapi_mechanism_base_t::~gssapi_mechanism_base_t()':
(.text+0x12a): undefined reference to `gss_release_name'
/usr/bin/ld: (.text+0x140): undefined reference to `gss_delete_sec_context'
/usr/bin/ld: /usr/lib/gcc/x86_64-linux-gnu/9/../../../x86_64-linux-gnu/libzmq.a(libzmq_la-gssapi_mechanism_base.o): in function `zmq::gssapi_mechanism_base_t::~gssapi_mechanism_base_t()':
(.text+0x17a): undefined reference to `gss_release_name'
/usr/bin/ld: (.text+0x190): undefined reference to `gss_delete_sec_context'
/usr/bin/ld: /usr/lib/gcc/x86_64-linux-gnu/9/../../../x86_64-linux-gnu/libzmq.a(libzmq_la-gssapi_mechanism_base.o): in function `zmq::gssapi_mechanism_base_t::encode_message(zmq::msg_t*)':
(.text+0x28d): undefined reference to `gss_wrap'
/usr/bin/ld: (.text+0x30c): undefined reference to `gss_release_buffer'
/usr/bin/ld: /usr/lib/gcc/x86_64-linux-gnu/9/../../../x86_64-linux-gnu/libzmq.a(libzmq_la-gssapi_mechanism_base.o): in function `zmq::gssapi_mechanism_base_t::decode_message(zmq::msg_t*)':
(.text+0x5b9): undefined reference to `gss_unwrap'
/usr/bin/ld: (.text+0x650): undefined reference to `gss_release_buffer'
/usr/bin/ld: (.text+0x8ac): undefined reference to `gss_release_buffer'
/usr/bin/ld: /usr/lib/gcc/x86_64-linux-gnu/9/../../../x86_64-linux-gnu/libzmq.a(libzmq_la-gssapi_mechanism_base.o): in function `zmq::gssapi_mechanism_base_t::convert_nametype(int)':
(.text+0xe47): undefined reference to `GSS_C_NT_USER_NAME'
/usr/bin/ld: (.text+0xe53): undefined reference to `GSS_C_NT_HOSTBASED_SERVICE'
/usr/bin/ld: /usr/lib/gcc/x86_64-linux-gnu/9/../../../x86_64-linux-gnu/libzmq.a(libzmq_la-gssapi_mechanism_base.o): in function `zmq::gssapi_mechanism_base_t::acquire_credentials(char*, gss_cred_id_struct**, gss_OID_desc_struct*)':
(.text+0xeb0): undefined reference to `gss_import_name'
/usr/bin/ld: (.text+0xecf): undefined reference to `gss_acquire_cred'
/usr/bin/ld: (.text+0xee0): undefined reference to `gss_release_name'
collect2: error: ld returned 1 exit status
make[3]: *** [src/daemon/CMakeFiles/daemon.dir/build.make:230: bin/electroneumd] Error 1
make[3]: Leaving directory '/home/chris/electroneum/build/Linux/andrefixes/release'
make[2]: *** [CMakeFiles/Makefile2:2866: src/daemon/CMakeFiles/daemon.dir/all] Error 2
make[2]: Leaving directory '/home/chris/electroneum/build/Linux/andrefixes/release'
make[1]: *** [Makefile:141: all] Error 2
make[1]: Leaving directory '/home/chris/electroneum/build/Linux/andrefixes/release'
make: *** [Makefile:140: release-static-linux-x86_64] Error 2
`

# What's the expected result?
Complete compilation. Compiling works fine on MacOS + Windows but not Ubuntu

**Comment by bluca** [comment]
You are doing static linking without all the required dependencies - use pkg-config in your project build system to get them

**Comment by ChrisCharrison** [comment]
@bluca this happens if we do a static build or non-static

**Comment by bluca** [comment]
are you using pkg-config?

**Comment by ChrisCharrison** [comment]
Yes we are, however we are not well accustomed to using it. Our project is:
https://github.com/electroneum/electroneum
Bear in mind this has built fine until just recently on any version of Ubuntu.
What is the first step? Many thanks

**Comment by bluca** [comment]
https://cmake.org/cmake/help/latest/module/FindPkgConfig.html
