### ISSUE TITLE
Question: How a publlisher know other peer is a subscriber?

### ISSUE THREAD

**Issue by zhurou603** [zeromq/libzmq#4036]
# Issue description
Hi!
Background:
 Recently, I want to learn libzmq's design and how it works, so I run a demo.
I simply use a pub to send messages to sub.
The Question is:
     In my system, also a MOM, if I use like `nc -v localhost pub's port` to connect my pub, the pub node will send message to this TCP channel even though pub doesn't know peer is a sub or other TCP connections, which I think it is "unsafe".
     But in 0mq, the same experiment, pub will not send message to this TCP connetion and only send to corresponding subscriber, I want to know how to implement this feature and its design.
    Thanks!

**Comment by bluca** [comment]
everything is explained in the guide http://zguide.zeromq.org/page:all
