### ISSUE TITLE
Error in define zmq.h

### ISSUE THREAD

**Issue by lhayet** [zeromq/libzmq#4037]
*Please use this template for reporting suspected bugs or requests for help.*

# Issue description
In the zmq.h file, on line 218 and 217, are defined context options.
Those 2 : ZMQ_SOCKET_LIMIT and ZMQ_THREAD_PRIORITY are defined with the same value, which leads when zmq_ctx_set or zmq_ctx_get to error, because 2 context options, refers to the same value : 3.

# Environment
Not really important

* libzmq version (commit hash if unreleased): 
4.3.2

* OS: 
Not really important

# Minimal test code / Steps to reproduce the issue

1.  
void *context = zmq_ctx_new ();
zmq_ctx_set (context, ZMQ_THREAD_SCHED_POLICY, SCHED_FIFO);
zmq_ctx_set (context, ZMQ_THREAD_PRIORITY, 89);

int thread_prio = zmq_ctx_get (context, ZMQ_THREAD_PRIORITY);
printf("Thread priority must be set at : %i \n", thread_prio);
 
# What's the actual result? (include assertion message & call stack if applicable)

Thread priority must be set at : 65535

# What's the expected result?

Expected result is 89.
Displayed result is 65535.

Cause is when ctx.cpp int zmq::ctx_t::get (int option_) is called, it returns ZMQ_SOCKET_LIMIT associated value.
Because  ZMQ_SOCKET_LIMIT and  ZMQ_THREAD_PRIORITY are defined equals
[zmq.zip](https://github.com/zeromq/libzmq/files/5202265/zmq.zip)

**Comment by bluca** [comment]
As the documentation says, ZMQ_THREAD_PRIORITY is set-only and ZMQ_SOCKET_LIMIT is get-only, so it doesn't matter what the value is.
