### ISSUE TITLE
ROUTER ERROR!

### ISSUE THREAD

**Issue by kandr-zg** [zeromq/libzmq#4039]
# Issue description

Error using router. Assertion failed: !_ current_ out (src/ router.cpp:193 )

# Environment

* libzmq version 4.3.3: 
* OS: Ubuntu16.04

# Minimal test code / Steps to reproduce the issue

This problem occurs occasionally when router receives data.

# What's the actual result? (include assertion message & call stack if applicable)

Error using router. Assertion failed: !_ current_ out (src/ router.cpp:193 )

# What's the expected result?

**Comment by kandr-zg** [comment]
I think I know why.I used send in multiple threads.

**Comment by bluca** [comment]
> I think I know why.I used send in multiple threads.

Ok, closing then
