### ISSUE TITLE
Sending custom tcp packet across STREAM socket

### ISSUE THREAD

**Issue by agjaeger** [zeromq/libzmq#4050]
I am trying to interface with a legacy IOT device and I need to send a TCP packet with the FIN flag set. I can talk to the device using a STREAM socket, however I have not seen any documentation on how to send a custom packet header across. 

I can also accept alternative solutions such restarting a socket as long as it does not interfere with other connected devices.

**Comment by bluca** [comment]
Sending custom packets is not supported. It sounds like what you need is just a plain TCP socket.

**Comment by agjaeger** [comment]
I was kinda of hoping to avoid that, but if its not supported, so be it. Thanks
