### ISSUE TITLE
How to subscribe dynamically and recv msg in same thread?

### ISSUE THREAD

**Issue by americaboy** [zeromq/libzmq#4062]
usually，we subscrie a topic at first,then to do recv action in same thread.
like this:
```
void* sub_client = zmq_socket(ctx, ZMQ_SUB);
zmq_setsockopt(sub_client, ZMQ_SUBSCRIBE, topic.c_str(), strlen(topic.c_str()));
zmq_recv(socket_, recv_buffer, MAX_BUFFER_SIZE, 0);
```
but,I want  to subscribe topics even after called zmq_recv(0), //if use ZMQ_NOBLOCK, will causes high CPU usage.

How to implement it in a thread(for threadsafe)?
thx!

**Comment by bluca** [comment]
use polling http://api.zeromq.org/4-3:zmq-poll
