### ISSUE TITLE
Deb package for Ubuntu 20.04 doesn't exist in the repository.

### ISSUE THREAD

**Issue by mortymacs** [zeromq/libzmq#4066]
*Please use this template for reporting suspected bugs or requests for help.*

# Issue description
Deb package for Ubuntu 20.04 doesn't exist in the repository:
http://download.opensuse.org/repositories/network:/messaging:/zeromq:/release-stable/xUbuntu_20.04/

Also the key: https://download.opensuse.org/repositories/network:messaging:zeromq:release-stable/xUbuntu_20.04/Release.key

# Environment

* libzmq version (commit hash if unreleased): 
* OS: Linux/Ubuntu

# Minimal test code / Steps to reproduce the issue

1.  

# What's the actual result? (include assertion message & call stack if applicable)

# What's the expected result?

**Comment by bluca** [comment]
It's now building, will be available in a few minutes.

**Comment by mortymacs** [comment]
Great, thanks! Is it possible that I contribute for the next time? I just want to contribute.

**Comment by mortymacs** [comment]
Great, thanks! Is it possible that I contribute for the next time? I want to contribute.

**Comment by bluca** [comment]
It requires admin privileges, so I'm afraid not. It's just a button to click anyway, it's not very interesting. If you want to work on packaging, the current issue to be solved is support for python2 for older distros without impacting newer distros which are removing it, in czmq and zyre for bindings. You can create your own account, "branch" a package and submit changes for review.
