### ISSUE TITLE
trie check function will match a non-subscribed message when a subscribed-to topic is a prefix of non-subscribed message's topic

### ISSUE THREAD

**Issue by philthoren** [zeromq/libzmq#4069]
# Issue description
trie check function will match a non-subscribed message when a subscribed-to topic is a prefix of non-subscribed message's topic
The loop in the check function processing the input string doesn't check that it has completely processed the topic string where the message was published 
As soon as the check function hits a node with a non-zero reference count it returns that it matched and the message is sent up the stack

# Environment
* libzmq version (commit hash if unreleased): 4.2.3
* OS: Linux

# Minimal test code / Steps to reproduce the issue
1. Subscribe to A in one process or thread
2. Publish to AB from another process or thread

# What's the actual result? (include assertion message & call stack if applicable)
The process subscribed to A will receive the AB message
This is the behavior I'm observing
I tracked the issue to trie.cpp check not processing the topic string of the message completely.

# What's the expected result?
The process subscribed to A should not receive the AB message up the stack

**Comment by bluca** [comment]
That's how it's supposed to work. The point of a trie is to do prefix matching. Read the guide https://zguide.zeromq.org
