### ISSUE TITLE
Should docs mention all possible errno values that a function can set?

### ISSUE THREAD

**Issue by ardrabczyk** [zeromq/libzmq#4078]
# Issue description

Currently docs do not mention than zmq_ctx_new() can set EMFILE and
that zmq_ctx_set_ext() can set EFAULT. The thing with zmq_ctx_new(),
and possibly other functions is that errno is not set explicitly in
libzmq code but is set by OS and therefore can be OS-specific.

# Environment

* libzmq version (commit hash if unreleased): v4.3.3-17-gb2a08420
* OS: Slackware x64 -current

# Minimal test code / Steps to reproduce the issue

```
#include <stdio.h>
#include <stdlib.h>
#include <zmq.h>

int main(void)
{
  void *context;
  for (int i = 0; i < 10000; i++)
    {
      context = zmq_ctx_new ();
      if (!context)
	{
	  if (errno)
	    perror("Reason");

	  fprintf(stderr, "zmq_ctx_new() failed at %d.\nExiting.\n", i);
	  return EXIT_FAILURE;
	}
    }

  return EXIT_SUCCESS;
}
```

# What's the actual result? (include assertion message & call stack if applicable)

```
$ ./test
Reason: Too many open files
zmq_ctx_new() failed at 1020.
Exiting.
```

# What's the expected result?

This could be documented in doc/zmq_ctx_new.txt but now it says:

> No error values are defined for this function.

**Comment by bluca** [comment]
Feel free to send a PR to improve the docs
