### ISSUE TITLE
Failing build on MacOS

### ISSUE THREAD

**Issue by squidgegmc** [zeromq/libzmq#4085]
I am trying to build v4.3.3, builds fine on Windows and Linux.
MacOS complains it cannot locate gnutls. I have installed this using `brew`

I am building using cmake v3.18.4, have tried 3.18.0 and 3.18.2 all the same

**Comment by bluca** [comment]
If you aren't able to install all build dependencies, you can disable TLS support with -DWITH_TLS=OFF
