### ISSUE TITLE
ZeroMQ 4.3.3 Unix Sockets Fill Temp Folder, Prevent Login (Windows)

### ISSUE THREAD

**Issue by agoeckner** [zeromq/libzmq#4086]
# Issue description

The temp directory, `%LOCALAPPDATA%\Temp`, is rapidly filled with folders containing a single "socket" file. These files are not deleted even after the ZeroMQ context is closed, causing the temp folder to fill. We believe that these are IPC sockets used for ZMQ internal communication.

Running for a long period of time (>30 minutes or so) produces so many files in the temp folder that after logging out or restarting the computer, the user will no longer be able to log in until the Temp folder has been cleared. (Windows hangs at the "Welcome" screen.) This issue knocked out 5+ development machines before it was discovered.

@sigiesec may be able to shed more light on this issue, since he appears to have worked the initial Unix sockets support for Windows.

# Environment

* libzmq version (commit hash if unreleased): 4.3.3
* OS: Windows 10 (various builds but confirmed on v1909)

# Minimal test code / Steps to reproduce the issue

1.  Create a ZMQ context in thread A, with a UDP DISH socket receiving in thread B and a UDP RADIO socket transmitting in thread C.
2. Monitor `%LOCALAPPDATA%\Temp` folder usage for appearance of hexadecimal-named folders containing a "socket" file.
3. Stop program before computer is nuked.

**Comment by bluca** [comment]
Are you saying Windows doesn't clean the temp folders automatically? That's kinda the point of /tmp...

**Comment by agoeckner** [comment]
Apparently not, or at least not quickly enough. However, this is definitely a ZMQ issue. It was creating hundreds to thousands of "socket" files per second.

**Comment by zedalaye** [comment]
Same issue for me. Temp files are not automatically deleted on Windows.
