### ISSUE TITLE
strerror(errno) after bind

### ISSUE THREAD

**Issue by xR3b0rn** [zeromq/libzmq#4087]
# Issue description
`errno` is set, after binding a socket to an ipc file.

# Environment

* libzmq version (commit hash if unreleased): HEAD
* OS: Linux

# Minimal test code / Steps to reproduce the issue
```C++
#include <iostream>
#include <zmq.h>
int main()
{
    auto ctx = zmq_ctx_new();
    if (ctx == ZMQ_NULLPTR) { std::cout << "ctx == nullptr\n"; return 1; }
    auto skt = zmq_socket(ctx, ZMQ_PUB);
    if (skt == ZMQ_NULLPTR) { std::cout << "skt == nullptr\n"; return 1; }
    if (zmq_bind(skt, "ipc:///tmp/signals.ipc")  != 0) { std::cout << "zmq_bind failed\n"; return 1; }
    std::cout << strerror(errno) << "\n";
}
```

# What's the actual result? (include assertion message & call stack if applicable)
Prints either: "No such file or directory" or "Resource temporarily unavailable" depending on if the file exists or not.

But everything else works fine, I can send over the socket without any problems.

# Expected result
`errno` should equals 0.

**Comment by bluca** [comment]
As the documentation says, errno is meaningful only if -1 is returned. If zmq_bind returns 0, ignore it as it's undefined.
