### ISSUE TITLE
Versioning out of wack?

### ISSUE THREAD

**Issue by squidgegmc** [zeromq/libzmq#4089]
I have built v4.3.2 and v4.3.3 using CMAKE across Win, Linux, and MacOS.

There are discrepancies across the versioning numbers of the lib

For example:
v4.3.2
- Windows = 4.3.2
- Linux = 5.2.2
- MacOS = 5.2.2

v4.3.3
- Windows = 4.3.3
- Linux = 5.2.3
- MacOS = 5.2.3

**Comment by bluca** [comment]
That's not the version you are looking at, it's the ABI. On Windows it's not really a thing, so it matches the version, but on *nix it does not, correctly.
