### ISSUE TITLE
Application using zmq poll is crashing with SIGABRT permission denied error

### ISSUE THREAD

**Issue by nithinsen** [zeromq/libzmq#4090]
*Please use this template for reporting suspected bugs or requests for help.*

# Issue description
I was using zmq push and pull sockets, on zmq server and client side.

I was observing a SIGABRT crash, in zmq poll operation. The error/exit log was "Permission denied (src/tcp_connecter.cpp:361)"
When debugged, I could see an ip6table rule in peer end (server end), which is causing client side zmq poll to crash. 
This rule was doing "reject with admin prohibited" in INPUT and forward chain.

The issue was raised and debugged as part of ticket https://github.com/zeromq/fszmq/issues/166. Please refer the same,

# Environment
Both server and client was running as k8s docker containers in different host. And ip6table rule in host table. The issue is not specific to container environment, and may observe between two host.

* libzmq version (commit hash if unreleased): 
* OS: 
Centos

# Minimal test code / Steps to reproduce the issue

1.  

# What's the actual result? (include assertion message & call stack if applicable)

SIGABRT with permission denied error. 

(gdb) bt
#0 0x00007ffff76d053f in raise () from /lib64/libc.so.6
#1 0x00007ffff76ba895 in abort () from /lib64/libc.so.6
#2 0x00007ffff7f59ace in zmq::zmq_abort(char const*) () from /lib64/libzmq.so.5
#3 0x00007ffff7f9ef36 in zmq::tcp_connecter_t::connect() () from /lib64/libzmq.so.5
#4 0x00007ffff7f9f060 in zmq::tcp_connecter_t::out_event() () from /lib64/libzmq.so.5
#5 0x00007ffff7f6bc2c in zmq::epoll_t::loop() () from /lib64/libzmq.so.5
#6 0x00007ffff7f9ffba in thread_routine () from /lib64/libzmq.so.5
#7 0x00007ffff75d058e in start_thread () from /lib64/libpthread.so.0
#8 0x00007ffff77956a3 in clone () from /lib64/libc.so.6

# What's the expected result?

Expecting zmq to return error code which can be handled in application code. Rather than exiting as part of SIGABRT.

**Comment by bluca** [comment]
> Expecting zmq to return error code which can be handled in application code. Rather than exiting as part of SIGABRT.

This cannot happen as connections are async. Even if it could, it shouldn't: this is a hard configuration error from an external environment, not a transient random fluctuation, so it's much better to abort immediately, so that the external problem can be fixed.

**Comment by nithinsen** [comment]
Thanks for your comments. 

But how can we conclude/narrow down the issue into a configuration error, if we have only a log of Permission denied.. Good to give more info .. 

And iptable configuration mistake is in the next hop. 
In real time runs, a dynamically added such configuration in one setup, can break the entire connectivity, and may break further functionalities running in different setup. Even a full system can go down in such cases. Assume it is a systemd process.

**Comment by bluca** [comment]
> But how can we conclude/narrow down the issue into a configuration error, if we have only a log of Permission denied.. Good to give more info ..

We don't know more than that, so there's really not much more that can be done
