### ISSUE TITLE
WebSocket transport not working with PUB/SUB sockets

### ISSUE THREAD

**Issue by YunYe-Pu** [zeromq/libzmq#4101]
# Issue description

I have a PUB socket listening and a SUB socket connecting to it. When using TCP everything is fine. When I switch to websocket, the SUB socket no longer receives messages. Packet capture shows connection established, handshake completed, and subscription request sent, but no message appear on wire.

Comparing data captured on wire with [ZWS RFC](https://rfc.zeromq.org/spec/45/), I found that subscription messages from the SUB socket might be malformed. If I manually add a `\1` byte before the subscription topic, messages would appear on wire; still no message is received from the socket(this makes sense since I am actually subscribing to a different topic now).

I also tested PUSH/PULL sockets with websocket, which worked as expected.

# Environment

* libzmq version: 4.3.3
* OS: CentOS 7.6

# Minimal test code / Steps to reproduce the issue

```C++
void wsTest(bool asPublisher)
{
	const std::string bindAddr("ws://*:10294");
	const std::string connAddr("ws://169.254.36.2:10294");
	std::unique_ptr<void, decltype(&zmq_ctx_destroy)> ctx(zmq_ctx_new(), zmq_ctx_destroy);

	if (asPublisher)
	{
		std::unique_ptr<void, decltype(&zmq_close)> sock(zmq_socket(ctx.get(), ZMQ_PUB), zmq_close);
		zmq_bind(sock.get(), bindAddr.c_str());
		while (true)
		{
			std::this_thread::sleep_for(std::chrono::seconds(1));
			zmq_send(sock.get(), "Hello world", 11, 0);
			std::cout << "Msg published" << std::endl;
		}
	}
	else
	{
		std::unique_ptr<void, decltype(&zmq_close)> sock(zmq_socket(ctx.get(), ZMQ_SUB), zmq_close);
		zmq_connect(sock.get(), connAddr.c_str());
		std::this_thread::sleep_for(std::chrono::seconds(1));
		zmq_setsockopt(sock.get(), ZMQ_SUBSCRIBE, "H", 1);
		while (true)
		{
			char buffer[32]{ 0 };
			zmq_recv(sock.get(), buffer, sizeof(buffer) - 1, 0);
			buffer[31] = 0;
			std::cout << buffer << std::endl;
		}
	}
}
int main(int argc, char** argv)
{
	wsTest(argv[1][0] == 's');
}
```

On the server:

```
./wstest.out s
```

On the client:

```
./wstest.out c
```

# What's the actual result? (include assertion message & call stack if applicable)

No output from client program.

If replace `zmq_setsockopt(sock.get(), ZMQ_SUBSCRIBE, "H", 1);` with `zmq_setsockopt(sock.get(), ZMQ_SUBSCRIBE, "\1H", 2);` messages would appear on wire, but client program still produces no output.

# What's the expected result?

Client should print "Hello world" every second.

**Comment by dpirly** [comment]
I have the same problem,  and found the xattach_pipe() do not add the pipe to subscriptions. Is there some parameter need to be set?
