### ISSUE TITLE
undefined variable _s in stream_engine_base.cpp cause build failure on kFreeBSD

### ISSUE THREAD

**Issue by jonassmedegaard** [zeromq/libzmq#4113]
libzmq fails to build on kFreeBSD: 
```
libtool: compile:  g++ -DHAVE_CONFIG_H -I. -I./src -I/usr/include/pgm-5.3 -isystem /usr/include/mit-krb5 -D__BSD_VISIBLE -D_REENTRANT -D_THREAD_SAFE -Wdate-time -D_FORTIFY_SOURCE=2 -fvisibility=hidden -pedantic -Werror -Wall -Wno-long-long -g -O2 -fdebug-prefix-map=/<<PKGBUILDDIR>>=. -fstack-protector-strong -Wformat -Werror=format-security -ffat-lto-objects -c src/stream_listener_base.cpp -o src/libzmq_la-stream_listener_base.o >/dev/null 2>&1
src/stream_engine_base.cpp: In function ‘std::string get_peer_address(zmq::fd_t)’:
src/stream_engine_base.cpp:87:26: error: ‘_s’ was not declared in this scope; did you mean ‘s_’?
   87 |         if (!getsockopt (_s, 0, LOCAL_PEERCRED, &cred, &size)
      |                          ^~
      |                          s_
src/stream_engine_base.cpp:94:13: error: ‘_peer_address’ was not declared in this scope; did you mean ‘peer_address’?
   94 |             _peer_address += buf.str ();
      |             ^~~~~~~~~~~~~
      |             peer_address
make[2]: *** [Makefile:5866: src/libzmq_la-stream_engine_base.lo] Error 1
```
([full build log](https://buildd.debian.org/status/fetch.php?pkg=zeromq3&arch=kfreebsd-amd64&ver=4.3.3-4&stamp=1608930571&raw=0))

It seems the cause is that in shuffling around some code 2 years ago variable `_s` was oddly and inconsistently (probably accidentally) renamed to `s_`: https://github.com/zeromq/libzmq/commit/091df743a81f3899bd70166060c2082ea0cbd57c

Fix seems to be to revert to use `_s` at its current locations:
https://github.com/zeromq/libzmq/blob/master/src/stream_engine_base.cpp#L66
https://github.com/zeromq/libzmq/blob/master/src/stream_engine_base.cpp#L70
https://github.com/zeromq/libzmq/blob/master/src/stream_engine_base.cpp#L77

...so that it is defined at https://github.com/zeromq/libzmq/blob/master/src/stream_engine_base.cpp#L87

**Comment by bigon** [comment]
Hello,

The patch here seems to address `_s` but not `_peer_address`, am I missing something?

**Comment by bluca** [comment]
Sigh, no I missed that, my bad. Can you send a PR?

**Comment by jonassmedegaard** [comment]
Quoting Laurent Bigonville (2021-01-08 16:07:38)
> The patch here seems to address `_s` but not `_peer_address`, am I missing something?

The issue I reported involved only _s vs. s_ and the patch I proposed only covered those.

...if that is what you are asking.

**Comment by bigon** [comment]
Well the initial build log also mention `_peer_address`

**Comment by jonassmedegaard** [comment]
Ohhh, indeed it does - and in Debian indeed it continues to fail with my proposed patch: https://buildd.debian.org/status/fetch.php?pkg=zeromq3&arch=kfreebsd-amd64&ver=4.3.3-5&stamp=1610053267&raw=0

I am so sorry that I didn't properly test :-(
