### ISSUE TITLE
Inquire about static link exception when dynamic linking libzmq.

### ISSUE THREAD

**Issue by soimsoim** [zeromq/libzmq#4117]
*Isn't static link exception applicable in case of dynamic linking?*

1. Can I dynamic link libzmq into my application/library if it is used for commercial purpose?
2. For commercial application/library, if dynamic link is performed, should I open my application/library source code, provided that the code of libzmq is not modified.
3. If dynamic link is performed, can I license for my application/library under other licenses?

- Answering issue on static link to the above question: https://github.com/zeromq/libzmq/issues/3884

**Comment by bluca** [comment]
Yes, of course, that's how the LGPL works

**Comment by soimsoim** [comment]
Dear @bluca ,

When dynamically linking the LGPL-3.0 library, I have to provide **Installation Information** for the LGPL-3.0 library.

-“Installation Information” for a User Product means any methods, procedures, authorization keys, or other information required to install and execute modified versions of a covered work in that User Product from a modified version of its Corresponding Source. The information must suffice to ensure that the continued functioning of the modified object code is in no case prevented or interfered with solely because modification has been made.

**If the executable created by dynamic linking libzmq, should the installation information be disclosed?**
(Of course, in this case, the source code related to the libzmq library must be disclosed.)

**Comment by bluca** [comment]
No, there's a specific exception to that in our license

**Comment by soimsoim** [comment]
Thank you for quick answer.
