### ISSUE TITLE
SEH for thread naming in Visual Studio build is not correct in 4.3.3

### ISSUE THREAD

**Issue by jakecobb** [zeromq/libzmq#4140]
# Issue description

Issue #3586 and PR #3601 introduced a regression by faulty [Structured Exception Handling (SEH)](https://docs.microsoft.com/en-us/cpp/cpp/structured-exception-handling-c-cpp?view=msvc-160) in Visual Studio / MSBuild environments.  The change was trying to remove the MS-specific `__try` and `__except` that are used to set the thread name for debugging.  This exception mechanism is the Microsoft way of setting the thread name, see:

https://docs.microsoft.com/en-us/visualstudio/debugger/how-to-set-a-thread-name-in-native-code?view=vs-2019#set-a-thread-name-by-throwing-an-exception

There is a newer `SetThreadDescription` API but it is not available in all supported versions of Windows.

The `__try`/`__except` form was replaced by a bunch of NT API calls that appear to be mimicking SEH.  Under most circumstances it seems ok, e.g. running and debugging seem to work without error and the thread names are set when debugging in Visual Studio.  However, in OpenCppCoverage it is triggering an unhandled SEH exception which leads to an abort:

OpenCppCoverage/OpenCppCoverage#141

Using ZeroMQ 4.3.2, no unhandled SEH exception is seen by OpenCppCoverage, so this change did not preserve the semantics of the `__try`/`__except` construct.

# Environment

* libzmq version: 4.3.3, 4.3.4
* OS: Windows 10
* Compiler: Visual Studio 2015

# Minimal test code / Steps to reproduce the issue

Run the following under any recent OpenCppCoverage (e.g. 0.9.9.0):

```cpp
#include <zmq.h>

int main(int argc, char**argv)
{
  void* context = zmq_ctx_new();
  void* socket = zmq_socket(context, ZMQ_PUB); // crash here with opencppcoverage

  zmq_close(socket);
  zmq_ctx_term(context);
  return 0;
}
```

# What's the actual result? (include assertion message & call stack if applicable)

An unhandled exception (in the SEH sense, not the C++ exception sense) is detected by OpenCppCoverage and the program is aborted with:

```
----------------------------------------------------
*** Your application has thrown an unhandled exception. Code: 1080890248: Unknown
----------------------------------------------------
```

# What's the expected result?

No error occurs and the program exits cleanly.

**Comment by bluca** [comment]
Can you send a PR?

**Comment by jakecobb** [comment]
Duplicate of #4128.

Sorry, should have checked the unreleased branch before submitting, already fixed.
