### ISSUE TITLE
zmq crash issue

### ISSUE THREAD

**Issue by cyforsr** [zeromq/libzmq#4165]
*Please use this template for reporting suspected bugs or requests for help.*

# Issue description
**we use pub-sub mode in linux-c with a very simple example:
but always crash down， it's issue messages:**
![微信图片_20210329224225 (2)](https://user-images.githubusercontent.com/37731329/112866907-e85ca780-90ec-11eb-8c8f-9e67c380e015.jpg)
![微信图片_20210329224233 (2)](https://user-images.githubusercontent.com/37731329/112866938-ef83b580-90ec-11eb-94a5-f4e81ee1ecd3.jpg)
![微信图片_20210329224241](https://user-images.githubusercontent.com/37731329/112866954-f3173c80-90ec-11eb-872c-18941cab8417.jpg)
![微信图片_20210329224250](https://user-images.githubusercontent.com/37731329/112866976-f7435a00-90ec-11eb-8fd9-5265f71d8adb.jpg)

``` 
#include <iostream>
#include "zhelpers.hpp"
#include "timer.h"
using namespace std;

#define within(num) (int) ((float) (num) * random () / (RAND_MAX + 1.0))

int main()
{
    int rst;
    void *context =zmq_init(1);
    void *publisher=zmq_socket(context,ZMQ_PUB);
    assert(publisher);
    zmq_bind(publisher,"tcp://*:5555");
    while(1)
    {
        sleep(5);
        zmq_msg_t msg;
        zmq_msg_init_size (&msg, 6);
        memcpy (zmq_msg_data (&msg), "hello", 6);
        rst=zmq_send (publisher, &msg,6, 0);
       cout<<"result==="<<rst<<endl;
    }
    zmq_close(publisher);
    zmq_term(context);
    return 1;
}

```

# Environment

* libzmq version (commit hash if unreleased): 4.3.2
* OS: linux

# Minimal test code / Steps to reproduce the issue

1.  

# What's the actual result? (include assertion message & call stack if applicable)

crash down

# What's the expected result?

efficient running

**Comment by bluca** [comment]
> memcpy (zmq_msg_data (&msg), "hello", 6);

You are overwriting the anonymous data structure. Use zmq_msg_data to get a pointer to the buffer to read/write http://api.zeromq.org/4-3:zmq-msg-data and most importantly read the guide https://zguide.zeromq.org/

**Comment by bluca** [comment]
> rst=zmq_send (publisher, &msg,6, 0);

This can fail, in which case you are responsible for closing it

**Comment by bluca** [comment]
> rst=zmq_send (publisher, &msg,6, 0);

zmq_send does not take a zmq_msg, it takes a buffer

http://api.zeromq.org/4-3:zmq-send
