### ISSUE TITLE
'platform.hpp' file not found , v4.2.3

### ISSUE THREAD

**Issue by i4apple** [zeromq/libzmq#4171]
*Please use this template for reporting suspected bugs or requests for help.*

# Issue description

pod get installed properly, while build In precompiled.hpp it gives error there is no file 'platform.hpp'.
<img width="969" alt="Screenshot 2021-04-08 at 23 02 58" src="https://user-images.githubusercontent.com/24771553/114071319-9c64ec00-98be-11eb-8b6a-beebed36b676.png">

# Environment

* libzmq version (4.2.3):

**Comment by bluca** [comment]
What's a "pod"? Did you build with cmake or autotools?

**Comment by godpp** [comment]
I found a solution. 😄
Before you execute `pod install`, you must install `cmake` first.

```
brew install cmake
pod cache clean --all
pod install
```
