### ISSUE TITLE
GCC-11.1.0 Support?

### ISSUE THREAD

**Issue by Legends0** [zeromq/libzmq#4178]
*Please use this template for reporting suspected bugs or requests for help.*

# Issue description

Unable to compile zeromq-4.3.4 with gcc-11.1.0 with the following configure:
./configure --with-libsodium --prefix=/opt/zeromq-4.3.4 --enable-drafts --with-tls

# Environment

* libzmq version (commit hash if unreleased): 4.3.4
* OS: CentOS 7.9

# Minimal test code / Steps to reproduce the issue

wget https://github.com/zeromq/libzmq/releases/download/v4.3.4/zeromq-4.3.4.tar.gz
tar xvfz zeromq-4.3.4.tar.gz
cd zeromq-4.3.4
./configure --with-libsodium --prefix=/opt/zeromq-4.3.4 --enable-drafts --with-tls
make

# What's the actual result? (include assertion message & call stack if applicable)
```
Making all in doc
make[1]: Entering directory `/root/zeromq-4.3.4/doc'
make[1]: Nothing to be done for `all'.
make[1]: Leaving directory `/root/zeromq-4.3.4/doc'
make[1]: Entering directory `/root/zeromq-4.3.4'
  CXX      src/libzmq_la-curve_client.lo
In file included from src/curve_client.hpp:37,
                 from src/curve_client.cpp:38:
src/curve_client_tools.hpp: In static member function ‘static int zmq::curve_client_tools_t::produce_initiate(void*, size_t, uint64_t, const uint8_t*, const uint8_t*, const uint8_t*, const uint8_t*, const uint8_t*, const uint8_t*, const uint8_t*, const uint8_t*, size_t)’:
src/curve_client_tools.hpp:183:16: error: ‘void* memcpy(void*, const void*, size_t)’ offset [0, 31] is out of the bounds [0, 0] [-Werror=array-bounds]
  183 |         memcpy (&initiate_plaintext[crypto_box_ZEROBYTES], public_key_, 32);
      |         ~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
src/curve_client_tools.hpp:186:16: error: ‘void* memcpy(void*, const void*, size_t)’ offset [0, 79] is out of the bounds [0, 0] [-Werror=array-bounds]
  186 |         memcpy (&initiate_plaintext[crypto_box_ZEROBYTES + 48],
      |         ~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  187 |                 vouch_box + crypto_box_BOXZEROBYTES, 80);
      |                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
cc1plus: all warnings being treated as errors
make[1]: *** [src/libzmq_la-curve_client.lo] Error 1
make[1]: Leaving directory `/root/zeromq-4.3.4'
make: *** [all-recursive] Error 1
```

# What's the expected result?
make succeeds in compilation.

**Comment by bluca** [comment]
PRs to fix the issue are welcome

**Comment by bluca** [comment]
Fixed by https://github.com/zeromq/libzmq/pull/4163

**Comment by Legends0** [comment]
This does not appear to be fixed by #4163 because the error still occurs in master.

**Comment by Legends0** [comment]
I do not have a PR to fix this. My workaround has been to compile with CXXFLAGS="-std=c++14".

**Comment by matzeri** [comment]
In Cygwin with   gcc (GCC) 11.2.0
the only pratical solution is configuring with "--disable-Werror" 
That is not really a nice one

**Comment by sigiesec** [comment]
I didn't look into whether the warning is legitimate. Instead of disabling all warnings as errors, one could just build with `-Wno-error=array-bounds`

**Comment by matzeri** [comment]
On 12.01.2022 09:18, Simon Giesecke wrote:
> I didn't look into whether the warning is legitimate. Instead of 
> disabling all warnings as errors, one could just build with 
> |-Wno-error=array-bounds|
> 

Thanks Simon

That works fine
