### ISSUE TITLE
Trouble installing libzmq3-dev on GitHub Actions Ubuntu runners

### ISSUE THREAD

**Issue by wlandau** [zeromq/libzmq#4184]
# Issue description

I am having trouble installing libzmq3-dev on the GitHub Actions Ubuntu 16.04 runner.

# Environment

* libzmq version (commit hash if unreleased): `libzmq3-dev` version `4.3.1-5+ubuntu16.04.1+deb.sury.org+1 ` (from the error message below)
* OS: Ubuntu 16.04 (via GitHub Actions)

# Minimal test code / Steps to reproduce the issue

I posted a minimal reproducible example at https://github.com/wlandau/libzmq-reprex. The latest workflow spec is at https://github.com/wlandau/libzmq-reprex/blob/89cd062f383e9612e1b45c961b26fdb0472e9d49/.github/workflows/reprex.yaml, and the result is at https://github.com/wlandau/libzmq-reprex/runs/2521101152.

# What's the actual result? (include assertion message & call stack if applicable)

Error message:

```bash
Run sudo apt-get install libzmq3-dev
Reading package lists...
Building dependency tree...
Reading state information...
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 libzmq3-dev : Depends: libzmq5 (= 4.1.4-7ubuntu0.1) but 4.3.1-5+ubuntu16.04.1+deb.sury.org+1 is to be installed
E: Unable to correct problems, you have held broken packages.
Error: Process completed with exit code 100.
```

# What's the expected result?

I expected `libzmq3-dev` to install without error. Before last week, there were no apparent issues on my end.

**Comment by bluca** [comment]
We don't maintain Github Actions, so can't really help you, you'll need to bring it up with the owners of the CI. Do note that Ubuntu 16.04 is EOL and should not be used anymore.
