### ISSUE TITLE
Problem: no downloads available for Windows builds

### ISSUE THREAD

**Issue by minrk** [zeromq/libzmq#4191]
# Issue description

bintray is [shutdown](https://jfrog.com/blog/into-the-sunset-bintray-jcenter-gocenter-and-chartcenter/), so all the Windows releases published from appveyor are inaccessible. They are still being built on appveyor, but can no longer be downloaded (and future uploads will presumably fail).

This is *not* a duplicate of https://github.com/zeromq/zeromq.org/issues/113 which was closed as a docs-only issue because the dead links are removed from the docs. This issue should only be closed when:

- a new destination is picked for Windows artifacts ([github packages](https://github.com/features/packages)?)
- Windows build [currently still configured to send to bintray](https://github.com/zeromq/libzmq/blob/04c37982b152945731188f8a149de99a72aef29c/appveyor.yml#L274-L28) is updated to use the new destination
- at least the current stable builds are uploaded to the new destination

pyzmq Windows releases rely on these builds, which means I can't make a pyzmq release until this is fixed or I find another source of libzmq builds.

# Environment

* libzmq version (commit hash if unreleased):  all
* OS: Windows

# Minimal test code / Steps to reproduce the issue

Try to download a Windows release, e.g. `wget https://dl.bintray.com/zeromq/generic/libzmq-v141-x64-4_3_2.zip`

# What's the actual result? (include assertion message & call stack if applicable)

403 forbidden

# What's the expected result?

Windows dll builds of libzmq

**Comment by bluca** [comment]
There's some stuff published on package managers like Conda, are you able to use those for pyzmq?

**Comment by minrk** [comment]
Interesting idea! I can try extracting libraries from the conda packages in the meantime, I'm not sure if that will work. Do you think libzmq should stop publishing releases for Windows? The infrastructure is all already in place, but needs a new host for the artifacts.

**Comment by bluca** [comment]
No opinion on the subject, I'm really not involved in that side - if anyone can find an alternative and make it work, it would be fine too

**Comment by minrk** [comment]
Looked into it for a bit and conda's a no go since they only do 64b builds on Windows, and pyzmq publishes 32b builds for Windows as well.

[cloudsmith](https://cloudsmith.com) seems to be the closest replacement. Doesn't have a built-in appveyor deploy plugin, but it does have a CLI so `cloudsmith-cli push ...` should be all that's needed.


Appveyor supports publishing to GitHub releases, which might work - I can't tell if the multiple artifacts from mutliple builds for one release is a problem, though.

**Comment by sigiesec** [comment]
FWIW, I think zeromq is already available via vcpkg, would that work for you?

**Comment by minrk** [comment]
Looks like appveyor with GitHub releases might work. I tested with [this change](https://github.com/zeromq/libzmq/compare/master...minrk:appveyor-gh-release), which made [this release](https://github.com/minrk/libzmq/releases/tag/v4.3.3.post0). I don't know if that would conflict with your release process because it seems to clobber the release text on each upload (it does remain as an unpublished draft). So to make a release, you would have to push a tag, wait for appveyor to finish uploading builds, then edit and publish the release. If that's acceptable, I think this is the simplest solution. Then pushing a `.post0` tag on 4.3.3 (or just copying over the artifacts from [here](https://github.com/minrk/libzmq/releases/tag/v4.3.3.post0) to 4.3.3) should work.

To get that ready for merge, we would need to get a github token for uploading releases (I used a personal access token for my fork). GitHub makes this unnecessarily tedious if you want to confine permissions to a single repo, which usually means creating a bot github account and granting the bot access to the repo.

**Comment by minrk** [comment]
@sigiesec it might! I'm not sure where vcpkg installs DLLs, but I'll see if I can find it.

**Comment by bluca** [comment]
We always edit the text manually to add the changeling, so that's not an issue - it must not remove existing artifacts though, which are created by Travis - that's the important part

**Comment by minrk** [comment]
Yeah, it seems to only add them (each artifact is an upload from a different build, so there would only be one if it removed existing artifacts). So it should be fine then, pending the credentials. What credentials are used for travis?

**Comment by bluca** [comment]
I'm not sure we can get it anymore, as it's encrypted for Travis - but I've created a new one and encrypted it for Appveyor, here it is:

```
vmAeVtN2qiQgFBCB2I5FDDRtADQ7GUdR9NwAJJyakbiV5OHzLHExDcC/D9Oh5r67
```

**Comment by minrk** [comment]
Thanks! #4192 should upload artifacts to releases now. You can see an example of its output [on my fork](https://github.com/minrk/libzmq/releases/tag/v4.3.3.post0)

**Comment by bluca** [comment]
PR merged and binaries uploaded to https://github.com/zeromq/libzmq/releases/tag/v4.3.4 - thanks!
