### ISSUE TITLE
pgm

### ISSUE THREAD

**Issue by jinyuttt** [zeromq/libzmq#4204]
*Please use this template for reporting suspected bugs or requests for help.*

# Issue description

I want to use PGM or epgm, but I don't support it.

Is this agreement still supported?

# Environment
 zmq4.3.4

# Minimal test code / Steps to reproduce the issue

1.  

# What's the actual result? (include assertion message & call stack if applicable)

# What's the expected result?

use PGM or epgm

**Comment by bluca** [comment]
pgm and epgm are supported yes

**Comment by jinyuttt** [comment]
openpgm_root，
How to set it？
