### ISSUE TITLE
cannot compile libzmq

### ISSUE THREAD

**Issue by Asmod4n** [zeromq/libzmq#4206]
# Issue description
when trying to compile libzmq (v4.3.4 or latest mater) i get the following error
```gcc
/home/asmod4n/code/mruby-zmq/libzmq/src/raw_engine.cpp: In member function ‘virtual void zmq::raw_engine_t::error(zmq::i_engine::error_reason_t)’:
/home/asmod4n/code/mruby-zmq/libzmq/src/raw_engine.cpp:127:17: error: ‘<anonymous>’ may be used uninitialized [-Werror=maybe-uninitialized]
  127 |         (this->*_process_msg) (&terminator);
      |                 ^~~~~~~~~~~~
```

# Environment

* libzmq version v4.3.4 or any later: 
* OS: Linux 5.12.8
* gcc 11.1.0

# Minimal test code / Steps to reproduce the issue

run make after configure

# What's the actual result? (include assertion message & call stack if applicable)
See description

# What's the expected result?
Have it compile without errors

**Comment by Asmod4n** [comment]
Building it without any additional warning or error flags gives me this next error message while trying to compile it.

/home/asmod4n/code/mruby-zmq/libzmq/src/curve_client_tools.hpp: In static member function ‘static int zmq::curve_client_tools_t::produce_initiate(void*, size_t, uint64_t, const uint8_t*, const uint8_t*, const uint8_t*, const uint8_t*, const uint8_t*, const uint8_t*, const uint8_t*, const uint8_t*, size_t)’:
/home/asmod4n/code/mruby-zmq/libzmq/src/curve_client_tools.hpp:183:16: error: ‘void* memcpy(void*, const void*, size_t)’ offset [0, 31] is out of the bounds [0, 0] [-Werror=array-bounds]
  183 |         memcpy (&initiate_plaintext[crypto_box_ZEROBYTES], public_key_, 32);
      |         ~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/asmod4n/code/mruby-zmq/libzmq/src/curve_client_tools.hpp:186:16: error: ‘void* memcpy(void*, const void*, size_t)’ offset [0, 79] is out of the bounds [0, 0] [-Werror=array-bounds]
  186 |         memcpy (&initiate_plaintext[crypto_box_ZEROBYTES + 48],
      |         ~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  187 |                 vouch_box + crypto_box_BOXZEROBYTES, 80);

**Comment by bluca** [comment]
False positives due to https://gcc.gnu.org/bugzilla/show_bug.cgi?id=99578

**Comment by Asmod4n** [comment]
Thanks 🙏
