### ISSUE TITLE
dgram socket fails to bind with NIC specification

### ISSUE THREAD

**Issue by sphaero** [zeromq/libzmq#4219]
Using an address string like udp://enx00143d0848ef;239.255.42.99:1511 results in failing bind.

# Environment

* libzmq version (master: fb9fb00eda5ade0725d8fd558dd861db800f1b5c): 
* OS: Linux 5.10 Debian

# Minimal test code / Steps to reproduce the issue

```
#include "zmq.h"
#include <assert.h>
#include <string.h>
#include <stdio.h>
#include <unistd.h>

int main (void)
{
  void *context = zmq_ctx_new ();
  void *data_socket = zmq_socket (context, ZMQ_DGRAM);

  int rc = zmq_bind(data_socket, "udp://enx00143d0848ef;239.255.42.99:1511");
  if (rc == -1) {
      printf ("E: bind failed: %s\n", strerror (errno));
      return 1;
  }
  assert (rc == 0);

  while (1) {
        char buffer [100];
        zmq_recv (data_socket, buffer, 100, 0);
        printf ("Received Hello %.*s\n", 100, buffer);
    }
    return 0;
}
``` 

It works with a different NIC but I haven't found why it fails here yet. Seems it doesn't like this NIC name?

**Comment by bluca** [comment]
what's the errno?

**Comment by sphaero** [comment]
strerror (errno) reports "No such device"

**Comment by sphaero** [comment]
updated the code as well

**Comment by sphaero** [comment]
Just tried on OSX as well but it works there like a simple interface name on linux.

**Comment by sphaero** [comment]
ah crap the nic had no carrier which results in this error, my bad
