### ISSUE TITLE
discussion: add ppoll

### ISSUE THREAD

**Issue by egpbos** [zeromq/libzmq#4220]
For the [ROOT project](https://github.com/root-project/root), I have built a `ppoll` (or rather pselect for macOS support) based alternative to `poll`. As you probably know, in POSIX, the `p*` variants of `poll`, `select`, and even possibly `recv` and `send`, allow for passing in a signal mask. This allows for easier interaction with POSIX signals, as I (somewhat incoherently, I must admit) [tried to motivate in this blog post](https://blog.esciencecenter.nl/combining-zeromq-posix-signals-b754f6f29cd6). I came by this idea from [a discussion on the blog of Martin Sustrik](https://250bpm.com/blog:12/); unfortunately the crucial comment with the original suggestion is missing from the blog since it was moved recently, but at the very bottom of the blogpost the idea is still mentioned in the second EDIT paragraph.

To recap, the basic idea is that by using `ppoll` (or any `p*` version of a blocking call), you can effectively use POSIX signals as an additional channel to poll. POSIX `ppoll` or `pselect` *atomically* unblocks the signals given by the mask, calls the poll and then blocks the signals again (i.e. these three operations are done atomically together). If you block the given signals outside of the `ppoll` call, this means that these signals are only handled during the blocking call. This means you are guaranteed to not be "bothered" by them in some hard to handle way outside of the blocking call.

The usecase for me is that I want to use a POSIX signal (SIGTERM) to kill child processes that also use ZeroMQ sockets, but don't want it to just cause random EINTRs that could also be caused by other things. However, this is just one particular usecase. I suspect that in general, people that do any kind of signal handling (probably for graceful shutdowns after CTRL-C mostly) may want to also switch to `p*` calls, because it eliminates the need for complicated time-out based handling to circumvent the race condition explained in [Sustrik's blog post](https://250bpm.com/blog:12/).

Long story short, I would love to submit this code to libzmq, but I would need some help/pointers getting it in full shape, because the current implementation is rudimentary. That is: I just got it to work in one particular way on Linux and macOS, but probably have missed many corner cases.

The `ppoll` code can be found in a couple of places (dev branches), but perhaps it's easiest to start from [the code I'm submitting in this PR right now](https://github.com/root-project/root/pull/8385). [The `ppoll` implementation file is here](https://github.com/root-project/root/blob/0c0dc78fbe78e198ace3814fd623802e79d9ea4c/roofit/roofitZMQ/src/ppoll.cpp) (please, don't mind the copyright/license statements, they can/will be removed/changed).

As you can see, it is more or less simply a copy-paste of the libzmq `poll` implementation, except:

1. I force it to build with `ZMQ_POLL_BASED_ON_SELECT`
2. I added the extra `sigmask_` parameter
3. [The signal mask is passed on to `pselect` on this line](https://github.com/root-project/root/blob/0c0dc78fbe78e198ace3814fd623802e79d9ea4c/roofit/roofitZMQ/src/ppoll.cpp#L238).

Since I myself do most of my development on a Mac, I did not try to implement an actual `ppoll` based version (unlike Linux, macOS doesn't have `ppoll`, only `pselect`), but I expect this would be desirable for a complete implementation. The alternative would be to rip out all the parts in the `ZMQ_POLL_BASED_ON_POLL` sections. Apart from this, I haven't tested at all on Windows, nor do I know anything about signals in Windows or whether any of this is relevant there, so I'd need some input there as well.

So, through this issue I hope I can gather your input on this, before I start doing a PR that may not even have a chance of success. Let me know what you think and of course I'd be happy to answer any questions.

**Comment by bluca** [comment]
Please add a new ZMQ_POLL_BASED_ON_PPOLL, and a CI job that builds with it to ensure it's tested, apart from that looks fine as an initial development

**Comment by egpbos** [comment]
Sorry for the late reply, but just to clear things up: are you sure we should add this as a compile-time alternative to `poll`? `ppoll` needs an extra parameter, so this would mean either the compile-time flag changes the `poll` signature, or the signature should have the extra parameter (the signal mask) always, but just inactive when not compiling with `ppoll`.

I was personally thinking more of a separate function `zmq_ppoll` next to `zmq_poll`. This would also allow use of `ppoll` in "normal" builds, like those shipped with all kinds of package managers.

**Comment by egpbos** [comment]
Maybe, the easiest way to go, is to change `zmq_poll`'s signature from

```c++
int zmq_poll (zmq_pollitem_t *items_, int nitems_, long timeout_);
```

to

```c++
int zmq_ppoll (zmq_pollitem_t *items_, int nitems_, long timeout_, const sigset_t *sigmask_ = nullptr);
```

and call the `p`-versions of `poll` and `select` (where available) if `sigmask_` is not `nullptr`.

The issue with that approach is that `ppoll` is only available on Linux and `pselect` on Linux and macOS, so e.g. when compiling with the default `-DPOLLER=poll` on macOS, the `sigmask_` option would not be used, even though it is available on that platform via `pselect`.

The other option (the one I originally envisioned) of just making a separate `zmq_ppoll` with only `p`-calls has a big code maintenance issue, though. It would be a copy-paste of almost the entire `zmq_poll` code, which is quite long, only switching out `poll` and `select` for `ppoll` and `pselect` and passing through the signal masks.

So, not sure what is the best design here. If you are up for discussing this issue further via some other channel on which we can iterate a bit faster, let me know, I'd be happy to chat or videocall.

**Comment by bluca** [comment]
We do not break backward compatibility, so changing the existing API is not an option. If it's really worth to add a new interface for this corner case feel free to send a PR to add a new draft function.
