### ISSUE TITLE
View License shows "GPL" instead of LGPL

### ISSUE THREAD

**Issue by kaplanlior** [zeromq/libzmq#4225]
On GitHub the view license (about section) shows GPL instead of LGPL.
This is somewhat misleading / confusing users who don't necessary scroll down to the end of the readme.

Examples and explanation is at https://github.com/zeromq/libzmq/pull/4224#issuecomment-869172028

**Comment by v-val** [comment]
Thanks for rising this, I nearly had heart attack when found GPL in this repository yesterday.

**Comment by bluca** [comment]
this is a problem in github's interface, please report it to them
