### ISSUE TITLE
building libzmq fails with error `src/clock.cpp:131:16: error: unused variable 'nsecs_per_usec' [-Werror,-Wunused-const-variable] const uint64_t nsecs_per_usec = 1000;`

### ISSUE THREAD

**Issue by sabotagebeats** [zeromq/libzmq#4231]
# Issue description
```
src/clock.cpp:131:16: error: unused variable 'nsecs_per_usec' [-Werror,-Wunused-const-variable]
const uint64_t nsecs_per_usec = 1000;
               ^
1 error generated.
```
https://github.com/dogecoin/dogecoin/pull/2236

# Environment

* libzmq version (commit hash if unreleased): 4.3.4 c593001a89f5a85dd2ddf564805deb860e02471171b3f204944857336295c3e5
* OS: unix based

# Minimal test code / Steps to reproduce the issue

1.  gitian build libzmq

# What's the actual result? (include assertion message & call stack if applicable)

```
Building zeromq...
make[1]: Entering directory `/home/ubuntu/build/dogecoin/depends/work/build/x86_64-apple-darwin11/zeromq/4.3.4-6bb1cdd33c6'
  CXX      src/src_libzmq_la-address.lo
  CXX      src/src_libzmq_la-channel.lo
  CXX      src/src_libzmq_la-client.lo
  CXX      src/src_libzmq_la-clock.lo
src/clock.cpp:131:16: error: unused variable 'nsecs_per_usec' [-Werror,-Wunused-const-variable]
const uint64_t nsecs_per_usec = 1000;
               ^
1 error generated.
make[1]: *** [src/src_libzmq_la-clock.lo] Error 1
make[1]: *** Waiting for unfinished jobs....
make[1]: Leaving directory `/home/ubuntu/build/dogecoin/depends/work/build/x86_64-apple-darwin11/zeromq/4.3.4-6bb1cdd33c6'
make: *** [/home/ubuntu/build/dogecoin/depends/work/build/x86_64-apple-darwin11/zeromq/4.3.4-6bb1cdd33c6/./.stamp_built] Error 2
make: Leaving directory `/home/ubuntu/build/dogecoin/depends'
```

https://github.com/dogecoin/dogecoin/pull/2236#issuecomment-872034426

# What's the expected result?
passes without error

**Comment by sabotagebeats** [comment]
similar error: https://github.com/zeromq/libzmq/issues/3919#issuecomment-631027643

**Comment by bluca** [comment]
I guess a `LIBZMQ_UNUSED (nsecs_per_usec);` at line 197 of src/clock.cpp would fix it - can you test it and send a PR if it works?

**Comment by sabotagebeats** [comment]
@bluca I don't have the error after putting that line but I also don't have the error before. I believe this is specific to OSX.  @rnicoll can you elaborate on the issue build platform?

**Comment by sabotagebeats** [comment]
It looks like this patch is passing our checks and may soon be merged if it passes Gitian Build. Thanks @bluca

**Comment by bluca** [comment]
Can you send a PR then?
