### ISSUE TITLE
How to exit ZMQbg gracefully

### ISSUE THREAD

**Issue by DinoStray** [zeromq/libzmq#4243]
*Please use this template for reporting suspected bugs or requests for help.*

# Issue description
If I not run server(zmq router), only run client(zmq dealer), and send some message, then exit client, there will be two thread can not exit:  
ZMQbg/IO/0 (strace result: sendto/recvmsg/close/connect/getsockname...)  
ZMQbg/Reaper (strace result: epoll_wait)  
I wonder how to exit all threads gracefully
 

# Environment

* libzmq version (commit hash if unreleased): 4.3.4
* OS: ubuntu 20.04

**Comment by DinoStray** [comment]
I guess it still try to resend message, I wonder how to abandon anything, just exit gracefully

**Comment by bluca** [comment]
close the context
