### ISSUE TITLE
Unable to compile libzmq-4.3.4  with libpgm-5.2.122

### ISSUE THREAD

**Issue by pi1ot** [zeromq/libzmq#4245]
*Please use this template for reporting suspected bugs or requests for help.*

# Issue description

I download and put libpgm-5.2.122~dfsg.tar.gz to {libzmq-src-path}/foreign/openpgm/
set CMakelists.txt option: option(WITH_OPENPGM "Build with support for OpenPGM" ON)

# Environment

* libzmq version (commit hash if unreleased): 4.3.4
* OS: ubuntu linux 18.04

# What's the actual result? (include assertion message & call stack if applicable)

run cmake and get error:
CMake Error at zmq/CMakeLists.txt:822 (message):
  openpgm-5.2" not found.  openpgm is searchd via `pkg-config openpgm-5.2`.
  Consider providing a valid OPENPGM_PKGCONFIG_NAME"

# What's the expected result?

Build libzmq-4.3.4 with libpgm-5.2

**Comment by pi1ot** [comment]
I try "./configure --with-pgm" and get another error:

checking for openpgm-5.3 >= 5.3... no
checking for openpgm-5.2 >= 5.2... no
checking for openpgm-5.1 >= 5.1... no
configure: error: Package requirements (openpgm-5.1 >= 5.1) were not met:

No package 'openpgm-5.1' found

Consider adjusting the PKG_CONFIG_PATH environment variable if you
installed software in a non-standard prefix.

Alternatively, you may set the environment variables pgm_CFLAGS
and pgm_LIBS to avoid the need to call pkg-config.
See the pkg-config man page for more details.

**Comment by bluca** [comment]
> {libzmq-src-path}/foreign/openpgm/
set CMakelists.txt option

What is this? This is not used anywhere, you need to install the library and ensure it is in the default systems path or add the various paths via the standard flags/options. Better yet use your distribution's packages.
