### ISSUE TITLE
ZeroMQ vs Unix Domain Socket

### ISSUE THREAD

**Issue by alexec** [zeromq/libzmq#4257]
Some context.

I’m building an Kubernetes app that feeds messages from Kafka to a function and then writes the result of that function to another topic. The feeder and the function are in two different containers. Initially I did the IPC using HTTP request/reply. I then, as an exercise, moved the function in process. That process 10x faster. I.e. 90% of the work was just moving message between the two containers. I then tested Unix Domain Sockets and found the at least 30% faster. Maybe more (testing incomplete).

There are faster ways to move message between processes than TCP, eg POSIX message queues. (SHM is not suitable for messages without much work). 

So to my actual question. 

Is ZeroMQ faster for my use case (I’m aware there are many other benefits). If so, how? Does it use SHM? SYS-V messages queues? How much faster? Are there benchmarks on this?

**Comment by bluca** [comment]
This is a bug tracker, use the mailing list for such help requests zeromq-dev@lists.zeromq.org

**Comment by alexec** [comment]
Does the mailing list require sign up? If so, I’ll ask on stackoverflow instead.
