### ISSUE TITLE
zsys_shutdown

### ISSUE THREAD

**Issue by jinyuttt** [zeromq/libzmq#4268]
Program exit error.
https://github.com/zeromq/libzmq/issues/1708.
I didn't find the API(zsys_shutdown).
version:4.3.4
![image](https://user-images.githubusercontent.com/13539621/136359810-587c6693-80f2-441b-8a7b-279aa83ff88e.png)

**Comment by bluca** [comment]
Wrong repository: https://github.com/zeromq/czmq
