### ISSUE TITLE
Send and receive UDP data from a non-ØMQ peer

### ISSUE THREAD

**Issue by CBtiger** [zeromq/libzmq#4295]
# Issue description
The 0MQ documentation contains ZMQ_STREAM saying
 "A socket of type ZMQ_STREAM is used to send and receive TCP data from a non-ØMQ peer"

I have the issue that I have legacy peers closed source peers sending standard UDP packets. I would like to have my application using 0MQ v4.2 to use these legacy peers and my own 0MQ peers using the same architecture, i.e. 0MQ. I want to use the same 0MQ thread to receive it, and pass it though to me in the same fashion like the other messages (using RADIO/DISH pattern) just from a "legacy" socket type with none of the 0MQ benefits. 

I did not find a direct support for this im linzmq. However, I wonder why ZMQ_STREAM has been added as feature for TCP, but not the same has been done for UDP - the movitation would be same? 

Questions
1) So this is either a Feature Request  or a request for information on why this is not feasible to do (technically or conceptual wise).  
2) Is there any workaround I can use to let my application use 0MQ to accesss standard/legacy UTP packets? I would expect they are already received by the UDP engine today for a given port. But since they not fit the ZMTP  protocol scheme the are sorted out or dismissed. That is the stream I would like to get access to. I am sure I am not the first person to come across this issue. Or is there a way that ZQM_STREAM allows this?

# Environment
Linux Ubuntu, Window 7/10

* libzmq version (commit hash if unreleased): 
0MQ4,3
* OS: Linux/Windows

# Minimal test code / Steps to reproduce the issue
like Standard DISH connection, but with a "legacy" socket, e.g. ZMQ_PACKET (analog to ZMQ_STREAM)

# What's the actual result? (include assertion message & call stack if applicable)
only 0MQ packets arrive and are sent. Applications could simplify their architecture using 0MQ, but they could not, because they still need to access legacy packets. With TCP that works, because access works through ZMQ_STREAM. 

# What's the expected result?
Plain UDP messages arrive and can be sent as well. Application architecture only uses 0MQ.

**Comment by bluca** [comment]
there's ZMQ_DGRAM as a new draft socket type that does exactly this (yes it's not documented, as it's new, PRs welcome)

**Comment by CBtiger** [comment]
That is absolutely fantastic! 
I went through the whole RFQ section. Quite impressive to learn what is already in there. Didn't think there are further goodies in the code ...
Thanks for your great work!

What version do I need to have it inluded, 4.3 stable? 
* I would expect I enable the DRAFTS during compilation like all other draft stuff. 

It there anything beside the source files themeselfs recommendable for info gathering?

**Comment by bluca** [comment]
yes, that will have it, and yes you need a draft build - unfortunately this option is not yet documented
