### ISSUE TITLE
License file is confusing

### ISSUE THREAD

**Issue by heathermeeker** [zeromq/libzmq#4304]
*Please use this template for reporting suspected bugs or requests for help.*

# Issue description

The licensing statement (.MD) says the library is under LGPL plus an exception, but one of the copying files is GPL.  Can you please clarify this in the licensing statement?

# Environment

N/A

# Minimal test code / Steps to reproduce the issue

N/A

# What's the actual result? (include assertion message & call stack if applicable)

N/A

# What's the expected result?

N/A

**Comment by bluca** [comment]
This is a legal requirement and it's how the licenses work:

https://www.gnu.org/licenses/gpl-howto.en.html

> If you are releasing your program under the Lesser GPL, you should also include the text version of the LGPL, usually in a file called COPYING.LESSER. Please note that, since the LGPL is a set of additional permissions on top of the GPL, it's crucial to include both licenses so users have all the materials they need to understand their rights.

From COPYING.LESSER second paragraph:

>   This version of the GNU Lesser General Public License incorporates
the terms and conditions of version 3 of the GNU General Public
License, supplemented by the additional permissions listed below.

**Comment by heathermeeker** [comment]
I understand. May I respectfully suggest that you clarify this in your .MD file? I would be happy to submit a PR for it.

**Comment by bluca** [comment]
It already is: https://github.com/zeromq/libzmq#license

**Comment by bluca** [comment]
if you want to improve the wording, feel free to send a pr
