### ISSUE TITLE
zmq_connect  return success in the case of invalid IP and port for client connection

### ISSUE THREAD

**Issue by hanzhihua112** [zeromq/libzmq#4306]
*Please use this template for reporting suspected bugs or requests for help.*

# Issue description
1、client zmq_connect  return success in the case of invalid IP and port for client connection 
2、server zmq_blind  return success in the case of invalid IP and port 

# Environment

* libzmq version (commit hash if unreleased): master
* OS: CentOS release 6.10

# Minimal test code / Steps to reproduce the issue

1.
#include "iostream"
#include "zmq.h"

#define IPC_PATH "tcp://0.0.0.1000000:8989100000000"

int main()
{
    void *context = zmq_ctx_new();
    void *requester = zmq_socket(context, ZMQ_REQ);
    int cnt_err = zmq_connect(requester, IPC_PATH);
    std::cout << "client:cnt_err err = " << cnt_err << std::endl;
    if (cnt_err != 0)
    {
        std::cout << "client:zmq_connect err" << std::endl;
        return -1;
    }

    char buffer[64] = {};

    int sd_err = zmq_send(requester, "I am client", 12, 0);
    std::cout << "client: sd_err=" << sd_err << std::endl;

   
    int rv_err = zmq_recv(requester, buffer, 64, 0);
    std::cout << "client: rv_err=" << rv_err << std::endl;
    
    std::cout << "client:received msg:" << buffer << std::endl;

    zmq_close(requester);
    zmq_ctx_destroy(context);
    return 0;

    return 0;
}

2.
#include "iostream"
#include "zmq.h"

#define IPC_PATH "tcp://100000.0.0.10000000:8989100000000"

int main()
{
    void *context = zmq_ctx_new();
    std::cout << "zmq ptr:" << context << std::endl;
    void *responder = zmq_socket(context, ZMQ_REP);
    int blind_err = zmq_bind(responder, IPC_PATH);
    std::cout << "server:blind_err  = " << blind_err << std::endl;
    if (blind_err != 0)
    {
        std::cout << "server:blind err" << std::endl;
        return -1;
    }

    for (int idx = 0; idx < 6; ++idx)
    {
        char buffer[64] = {};
        std::cout << "server:zmq_recv fuc" << std::endl;
        zmq_recv(responder, buffer, 64, 0);
        std::cout << "server:received msg:" << buffer << ",idx=" << idx << std::endl;
        std::cout << "server:zmq_send fuc" << std::endl;
        zmq_send(responder, "I am server", 11, 0);
    }

    zmq_close(responder);
    zmq_ctx_destroy(context);

    return 0;
}

# What's the actual result? (include assertion message & call stack if applicable)
client zmq_connect VS  server zmq_blind  return success in the case of invalid IP and port

# What's the expected result?
client zmq_connect VS  server zmq_blind  return fail in the case of  connect fail

**Comment by bluca** [comment]
These are asynchronous operations as the documentation says, only minimal validation is fine synchronously
