### ISSUE TITLE
How do I get the correct return value of "zmq_connect" and  "zmq_send"

### ISSUE THREAD

**Issue by hanzhihua112** [zeromq/libzmq#4307]
*Please use this template for reporting suspected bugs or requests for help.*

# Issue description
1、How do I get the correct return value of "zmq_connect" and  "zmq_send", because of asynchronous execution.
2、"zmq_connect" always returns 0 whether the connection succeeds or not.

# Environment

* libzmq version (commit hash if unreleased): new
* OS: centos 6.10

# Minimal test code / Steps to reproduce the issue

#include <iostream>
#include "zmq.h"
#include <assert.h>
#include <unistd.h>

#define IPC_PATH "tcp://0.0.0.0:8989"

int main()
{
    void *context = zmq_ctx_new();
    std::cout << "errno error:" << zmq_strerror(zmq_errno()) << std::endl;
    void *requester = zmq_socket(context, ZMQ_REQ);
    int cnt_err = zmq_connect(requester, IPC_PATH); //There is no server for this port, so the actual connection failed
    std::cout << "client:cnt_err err = " << cnt_err << std::endl;
    return 0;
}

# What's the actual result? (include assertion message & call stack if applicable)
Get the correct return value of "zmq_connect" and  "zmq_send"

# What's the expected result?
The return value of "zmq_connect" and  "zmq_send"  is correct

**Comment by bluca** [comment]
https://zguide.zeromq.org/
