### ISSUE TITLE
New tag? v4.3.5?

### ISSUE THREAD

**Issue by thxkiwi** [zeromq/libzmq#4315]
# Issue description

I'd like to update a downstream project (`vcpkg`) that uses `zeromq/libzmq` via cloning the repo from the tag `v4.3.4`.
```
vcpkg_from_github(
    OUT_SOURCE_PATH SOURCE_PATH
    REPO zeromq/libzmq
    REF v4.3.4
    SHA512 ad828b1ab5a87983285a6b44b08240816ed1c4e2c73306ab1a851bf80df1892b5e2f92064a49fbadc1f4c75043625ace77dd25b64d5d1c2a7d1d61cc916fba0b
    PATCHES fix-arm.patch
)
```

I'd like to update the downstream project to use a more recent ref and benefit from changes in PRs but as far as I can see the latest tag is still `v4.3.4`. 

What is the process for adding new tags/new releases?

**Comment by Adela0814** [comment]
@bluca Could you please release a new version/tag?

**Comment by themightyoarfish** [comment]
It appears this will not be forthcoming, as this topic is considered "spam": https://github.com/zeromq/libzmq/issues/4455

**Comment by oliverkurth** [comment]
There haven't been any new releases in 2.5 years, and it looks like there have been many changes since then. There are a few bug fixes that I can use. I'd prefer a release tag for packaging, instead of a random snapshot or cherry picking.

Any plans for a release?

**Comment by themightyoarfish** [comment]
@oliverkurth This won't happen, and is considered spam: https://github.com/zeromq/libzmq/issues/4455

**Comment by oliverkurth** [comment]
That's unfortunate. I wonder if there is a reason?

**Comment by thxkiwi** [comment]
@bluca why are requests for an official release after >2.5 years being considered spam? This feels like another way of saying that ZMQ is essentially no longer maintained.

**Comment by bluca** [comment]
Last time I checked you weren't paying our salaries, so either you do the required work, or pay to have the required work done by somebody else, or else it is just spam
