### ISSUE TITLE
Problems working on the arm Linux

### ISSUE THREAD

**Issue by PunkMax** [zeromq/libzmq#4316]
I‘m using arm platform imx6q (Cortex-A9) and linux 4.1.15, rootfs generated by busybox.
I cross compiled the libzmq4.3.4 and czmq4.2.1 successfully by cross compiler arm-poky-linux-gnueabi- (gcc version 5.3.0), and also the example programs.
I already add the lib files in to the system, and the program could running.
But it seems that the server program and the client program cannot connected to each other.
Is there any other programs that zmq based?

I noticed that the lib file libczmq.so relys on libsystemd.so, does zmq must running based on systemd?

**Comment by NingfoolRobert** [comment]
does czmq must running based on -Lsystemd ？  
finally , how to do it ?
