### ISSUE TITLE
coredown

### ISSUE THREAD

**Issue by famince** [zeromq/libzmq#4318]
*Please use this template for reporting suspected bugs or requests for help.*

# Issue description

#0  0x00007fd86d4f560b in raise () from /lib64/libc.so.6
#1  0x00007fd86d4f6931 in abort () from /lib64/libc.so.6
#2  0x00007fd86dab1fee in zmq::zmq_abort (errmsg_=errmsg_@entry=0x7fd86db057ab "check ()") at src/err.cpp:88
#3  0x00007fd86dabc192 in zmq::msg_t::size (this=0x7fd8680b21b8) at src/msg.cpp:414
#4  0x00007fd86daee574 in zmq::v3_1_encoder_t::message_ready (this=0x7fd8680b1820) at src/v3_1_encoder.cpp:53
#5  0x00007fd86dadfe58 in zmq::stream_engine_base_t::out_event (this=0x7fd8680b1bc0) at src/stream_engine_base.cpp:355
#6  0x00007fd86dab2f7c in zmq::io_thread_t::in_event (this=0x236d0f0) at src/io_thread.cpp:91
#7  0x00007fd86dab1414 in zmq::epoll_t::loop (this=0x236e8f0) at src/epoll.cpp:206
#8  0x00007fd86dae6b58 in thread_routine (arg_=0x236e948) at src/thread.cpp:257
#9  0x00007fd86db34f1b in ?? () from /lib64/libpthread.so.0
#10 0x00007fd86d5b4340 in clone () from /lib64/libc.so.6

# Environment

* libzmq version (commit hash if unreleased): 
* OS: debian 9.7

# Minimal test code / Steps to reproduce the issue

get data from rabbit mq, then send to 0mq

# What's the actual result? (include assertion message & call stack if applicable)
generate core file

# What's the expected result?

**Comment by bluca** [comment]
That means the message is no longer valid. This is usually an error in the application, for example data pointers not being suitable for async usage, or using the same socket/message from multiple threads.
