### ISSUE TITLE
undefined reference for poller

### ISSUE THREAD

**Issue by immerhart** [zeromq/libzmq#4333]
zmq_poller_new
zmq_poller_wait_all
zmq_poller_destroy
zmq_poller_add

All of these functions are undefined in libzmq3-dev for ubuntu 20 (installed via apt).

nm -D /usr/lib/x86_64-linux-gnu/libzmq.so|grep poll
U epoll_create1
U epoll_ctl
U epoll_wait
U poll
000000000007b1d0 T zmq_poll

**Comment by bluca** [comment]
they are draft and thus not enabled in distributions, use the packages repos linked in the readme
