### ISSUE TITLE
Ubuntu 21.10 ffmpeg 4.4 compile- libzmq3-dev *fail*

### ISSUE THREAD

**Issue by tvadi** [zeromq/libzmq#4337]
On Ubuntu 21.10 while compiling ffmpeg 4.4 and trying to include 
`--enable-libzmq`
FFmpeg cannot find libzmq and is specifically looking for: libzmq 4.2.1 even when I have
`sudo apt-get install libzmq3-dev`
This does not happen on Ubuntu 20.04.
The only way I could get libzmq to work was to use gcc 9, get zeromq-4.2.1.tar.gz
`./autogen.sh ./configure make sudo make install`
That let ffmpeg compile but it was messing everything else up so that is not a solution.  
Only other info I could find was here, looks like this has maybe happened before?
[https://github.com/conda-forge/zeromq-feedstock/issues/16](url)

**Comment by bluca** [comment]
Please direct ffmpeg support request toward ffmpeg's own channels
