### ISSUE TITLE
Question - limiting concurrent connections

### ISSUE THREAD

**Issue by mentaal** [zeromq/libzmq#4338]
Hi there, 
I'd like to expose a service using zeromq which can only be used by a single user at a time. I'm currently using the REQ-REP pattern. 
I am aware that there is exists the exclusive pair pattern but its documented as though it should only be used for inter thread communication within a process. 

Is there a way to limit the amount of concurrent peers to a REP socket at a time (and in my case down to 1)?
Howcome this isn't an issue for more applications? Maybe I'm just thinking about this wrong. Is it expected to build session semantics on top of zmq? I understand that REQ-REP is targeting RPC like services. When the number of concurrent connection > 1, how should the application manage state between the peers and how should the application distinguish between the peers?

Thanks

**Comment by bluca** [comment]
> I am aware that there is exists the exclusive pair pattern but its documented as though it should only be used for inter thread communication within a process.

You can use PAIR with any transport

**Comment by mentaal** [comment]
@bluca  sorry but this is not a helper answer.
> You can use PAIR with any transport

I wasn't asking about transport compatibility. I was asking about managing state between multiple connected peers on a socket.
Before just closing my query with a one liner, could you (or anyone else) please comment on my other question?

**Comment by bluca** [comment]
This is a bug tracker, not a help forum. Please direct such queries toward one of the resources listed on https://zeromq.org/our-community/
