### ISSUE TITLE
Install libzmq Go Windows

### ISSUE THREAD

**Issue by const97** [zeromq/libzmq#4339]
Hello! I would like to use **zmq4** (https://github.com/pebbe/zmq4) in **Go** Programming Language on a **Windows** system. This need to have **ZeroMQ (libzmq)** installed (https://zeromq.org/download/ or https://github.com/zeromq/libzmq). Unfortunately, I can not find a way to install libzmq on Windows. Can anyone help me?

**Comment by bluca** [comment]
This is a bug tracker, not a help forum. Please direct such queries toward one of the resources listed on https://zeromq.org/our-community/
