### ISSUE TITLE
Failing tests as Docker proxy uses tcp port 5555. Set test ports in env?

### ISSUE THREAD

**Issue by ghenry** [zeromq/libzmq#4341]
# Issue description

```
============================================================================
Testsuite summary for zeromq 4.3.5
============================================================================
# TOTAL: 133
# PASS:  112
# SKIP:  19
# XFAIL: 0
# FAIL:  2
# XPASS: 0
# ERROR: 0
============================================================================
```

I get failed tests due to Docker listening on tcp port 5555:

```
sudo netstat -tplun | grep 5555
tcp        0      0 0.0.0.0:5555            0.0.0.0:*               LISTEN      1281625/docker-prox 
tcp6       0      0 :::5555                 :::*                    LISTEN      1281631/docker-prox 
```

which is obviously set here:

    tests/testutil.hpp:#define ENDPOINT_0 "tcp://127.0.0.1:5555"

if I change this define to say, port 55555, all is OK:

```
============================================================================
Testsuite summary for zeromq 4.3.5
============================================================================
# TOTAL: 133
# PASS:  114
# SKIP:  19
# XFAIL: 0
# FAIL:  0
# XPASS: 0
# ERROR: 0
============================================================================
```

# Environment

* libzmq version (commit hash if unreleased): a01d259db372bff5e049aa966da4efce7259af67
* OS: Fedora 35 x86_64

# Minimal test code / Steps to reproduce the issue

1.  make check

# What's the actual result? (include assertion message & call stack if applicable)

Two tests fail due to:

    tests/test_req_relaxed.cpp:209:test_case_4:FAIL: zmq_bind (router, ENDPOINT_0) failed, errno = 98 (Address already in use)

# What's the expected result?

`make check` successful.

**Comment by bluca** [comment]
We need to have a handful of fixed ports to ensure full code coverage of all code paths by the test suite. This means picking a value, and there will always be some conflicts somewhere. Just skip that test in your environment.
