### ISSUE TITLE
Update Trademark Policy

### ISSUE THREAD

**Issue by brugr9** [zeromq/libzmq#4347]
Dear @bluca / @somdoron 

# Issue description

A.) The trademark policy as found on [http://wiki.zeromq.org/docs:trademark-policy](http://wiki.zeromq.org/docs:trademark-policy) and 
B.) the policy for ownership as found on [http://wiki.zeromq.org/docs:owners](http://wiki.zeromq.org/docs:owners) 

are outdated.

# Environment

Any.

# Steps to reproduce the issue

## A.) Trademark Policy

Citation from [http://wiki.zeromq.org/docs:trademark-policy](http://wiki.zeromq.org/docs:trademark-policy) (access date Feb. 10, 2022):

> *This is the official trademark policy for ZeroMQ, as defined by iMatix Corporation:*
>
> *1. "ØMQ", "ZeroMQ", "0MQ", and the ØMQ logo are registered trademarks of iMatix Corporation ("iMatix") and refers to either (a) the original libzmq C++ library, or (b) the community of projects hosted in the https://github.com/zeromq organization.*
>
> *[...]*
>
> *4. The intent of this trademark policy is to avoid confusion from inappropriate use of these marks, and to ensure that the ZeroMQ mark is an accurate indicator of the origin of the software.*
>
> *5. iMatix grants you the right to use the "ZeroMQ" marks in all their forms to discuss, describe, document, or refer to projects hosted in the ZeroMQ community, or projects that build on those projects.*
>
> *6. You may write "ZeroMQ" and "ØMQ"; other upper/lower case combinations such as "0mq" or "Zeromq" are not correct, and not allowed. The preferred written form is "ZeroMQ."*
>
> *[...]*
>
> *8. You may not use these trademarks in any other software project name except with prior consent of iMatix, not in any web site outside the zeromq.org domain, except as granted in (5).*
>
> *9. If you make products that build on top of libzmq, you may not call them "ZeroMQ" without prior consent of iMatix. The conventional naming scheme for language bindings, for example, is "abczmq" where "abc" is the abbreviation for the language.*

Notes:

* The company *iMatix Corporation* no longer exists, as its owner Pieter Hintjens unfortunately passed away years ago (2016)&mdash;no chance to get prior consent from iMatix.
* "The Protocol of Things" is **no longer a trademark anymore** as the registration was cancelled on Apr. 30, 2021 (cp. United States Patent and Trademark Office USPTO, [Case Number 86010471](https://tsdr.uspto.gov/#caseNumber=86010471&caseType=SERIAL_NO&searchType=statusSearch), access date Feb. 10, 2022).
* The name "0MQ" (mark literal elements), and the ØMQ logo from three stylised letters (mark drawing type) are **no longer a trademark anymore** as the registration was cancelled on Sep. 18, 2020. From United States Patent and Trademark Office USPTO, [Case Number 86004104](https://tsdr.uspto.gov/#caseNumber=86004104&caseType=SERIAL_NO&searchType=statusSearch), Mark Information (access date Feb. 10, 2022):
  * *Mark: 0MQ* <img src="https://user-images.githubusercontent.com/1733987/153427181-59cb41ca-823d-4e2f-8a52-519c8e413fa3.png" height="20">
  * *Mark Literal Elements: 0MQ*
  * *Standard Character Claim: No*
  * *Mark Drawing Type: 5 - AN ILLUSTRATION DRAWING WITH WORD(S) /LETTER(S)/ NUMBER(S) INSTYLIZED FORM*
  * *Description of Mark: The mark consists of the number zero next to the letters "MQ".*
  * *Color(s) Claimed: Color is not claimed as a feature of the mark.*
  * ***Status: Registration cancelled because registrant did not file an acceptable declaration ...***
  * *Date Cancelled: Sep. 18, 2020*
* A freestanding single letter "slashed O" or "Ø" never was a feature of the mark&mdash;not even as logo, not even the color red&mdash;and it would be good if this were explicitly described in this way, since to prevent misunderstandings.

## B.) Ownership Policy

Citation from [http://wiki.zeromq.org/docs:owners](http://wiki.zeromq.org/docs:owners) (access date Feb. 10, 2022):

> * *The ØMQ trademarks and zeromq.org domain are owned by iMatix Corporation.*

Notes:

The domain is owned by @somdoron :

```
whois zeromq.org
[...]
Registry Registrant ID: DS13960-GANDI
Registrant Name: Doron Somech
[...]
```

# What's the actual result?

After reading this policy Epic Games refused my project which is using the name "0MQ" and a self made 3D-logo from stylised letter "slashed O" or "Ø" (see [UEPluginBP0MQ](https://github.com/brugr9/UEPluginBP0MQ) and [README&mdash;Third Party Libraries](https://github.com/brugr9/UEPluginBP0MQ/blob/main/ThirdParty.md)).

# What's the expected result?

Please update the policies so that the library can be used without having to discuss trademark rights with customers, e.g. (to delete: ~~crossed out~~; new: [in square brackets]):

## Trademark Policy

This is the official trademark policy for ZeroMQ ~~, as defined by iMatix Corporation~~:

* 1.) ~~"ØMQ", "ZeroMQ", "0MQ", and the ØMQ logo are registered trademarks~~ [The name "ZeroMQ" is a registered trademark] of iMatix Corporation ("iMatix") and refers to either (a) the original libzmq C++ library, or (b) the community of projects hosted in the https://github.com/zeromq organization.
* [1.2.) The name "0MQ" and the "ØMQ" logo (logo from three stylised letters) was a trademark owned by iMatix Corporation until Sep. 18, 2020. The mark is now available for free use in connection with ZeroMQ software, the "ØMQ" logo (black or red colour RGB(255,0,0)) in particular is to be used in compliance with creative commons license [Attribution-NoDerivatives 4.0 International (CC BY-ND 4.0)](https://creativecommons.org/licenses/by-nd/4.0/) (reuse the work for any purpose, including commercially; however, it cannot be shared with others in adapted form, and credit must be provided).] 
* [1.3.) The freestanding single letter "slashed O" or "Ø" never was a feature of the mark&mdash;not even as logo, not even the color red. It is for free use in connection with ZeroMQ software.]
* 3.) "The Protocol of Things" ~~is a registered trademark of iMatix and~~ refers to the ZeroMQ Message Transfer Protocol, or ZMTP, as defined by http://rfc.zeromq.org/spec:37 and related documents.
* 5.) ~~iMatix grants you~~ [You are granted] the right to use the "ZeroMQ" marks in all their forms to discuss, describe, document, or refer to projects hosted in the ZeroMQ community, or projects that build on those projects.
* 8.) You may not use ~~these trademarks~~ [the name "ZeroMQ"] in any other software project name ~~except with prior consent of iMatix~~, not in any web site outside the zeromq.org domain, except as granted in (5).
* 9.) If you make products that build on top of libzmq, you may not call them "ZeroMQ" ~~without prior consent of iMatix~~. The conventional naming scheme for language bindings, for example, is "abczmq" where "abc" is the abbreviation for the language.

## Ownership Policy

* ~~The ØMQ trademarks and zeromq.org domain are owned by iMatix Corporation.~~
* The name "0MQ" and the "ØMQ" logo are marks available for free use in connection with ZeroMQ software ([CC BY-ND 4.0](https://creativecommons.org/licenses/by-nd/4.0/)).
* The domain zeromq.org is owned by Doron Somech.

**Comment by bluca** [comment]
Thanks for the report, updated as indicated

**Comment by brugr9** [comment]
Dear @bluca / @somdoron 

# Issue description

The trademark policy as found on [http://wiki.zeromq.org/docs:trademark-policy](http://wiki.zeromq.org/docs:trademark-policy) is outdated.

# Environment

Any.

# Steps to reproduce the issue

Trademark Policy, citation from [http://wiki.zeromq.org/docs:trademark-policy](http://wiki.zeromq.org/docs:trademark-policy) (access date July 15, 2022):

> *1. The name "ZeroMQ" is a registered trademark of iMatix Corporation ("iMatix") and refers to either (a) the original libzmq C++ library, or (b) the community of projects hosted in the https://github.com/zeromq organization.*

Notes: The name "ZeroMQ" (mark literal elements) is **no longer a trademark anymore** as the registration was cancelled on May 13, 2022. From United States Patent and Trademark Office USPTO, [Case Number 86575873](https://tsdr.uspto.gov/#caseNumber=86575873&caseType=SERIAL_NO&searchType=statusSearch), Status (access date July 15, 2022):

> Registration cancelled because registrant did not file an acceptable declaration under Section 8.

# What's the actual result?

--

# What's the expected result?

Please update the Trademark Policy so that the library can be used without having to discuss trademark rights with customers, e.g. (*to delete: ~~crossed out~~; new: [in square brackets])*:

> *1. The name "ZeroMQ" ~~is a registered trademark of iMatix Corporation ("iMatix")~~ [was a trademark owned by iMatix Corporation until May 12, 2022. The mark is now available for free use in connection with ZeroMQ software] and refers to either (a) the original libzmq C++ library, or (b) the community of projects hosted in the https://github.com/zeromq organization.*


Kind regards,
Roland Bruggmann aka brugr9

**Comment by bluca** [comment]
Thanks, updated
