### ISSUE TITLE
[false positive] Windows Defender reports Trojan:Win32/Mamson.A!ac in libzmq-v142-x64-4_3_4.zip

### ISSUE THREAD

**Issue by playaspec** [zeromq/libzmq#4349]
# Issue description
Attempting to install matlab-zmq, which requires libzmq. Downloaded libzmq-v142-x64-4_3_4.zip to match installed VS Studio environment. System waned of 'Trojan:Win32/Mamson.A!ac' trojan in 'benchmark_radix_tree.exe' while unzipping archive. To eliminate the possibility of a false positive, I downloaded the same zip on Linux and decompressed it. I then submitted the same binary to multiple online malware scanners, and and received positive hits from multiple sites.

While I did not test every binary release, I did test  v141, v120, and mingw64 of 4.3.4, none of which triggered an alert.

# Environment

* libzmq version (commit hash if unreleased): 4.3.4
* OS: Windows 10 Enterprise

# Minimal test code / Steps to reproduce the issue

1.  Download  libzmq-v142-x64-4_3_4.zip from releases section, and extract archive or pass through other AV product.

# What's the actual result? (include assertion message & call stack if applicable)

Operating system quaranteens 'benchmark_radix_tree.exe' by expunging it from zip file and warns of detected malware.

# What's the expected result?

Files are clean and virus free.

**Comment by playaspec** [comment]
Windows Defender was the first to complain. Considering that it might be a false positive, I searched for a web based checker.

I tried several sites that run samples through multiple AV engines. Digging deeper I've read that sites like Virustotal will produce some false positives, and that the ratio of positive to negative hits should be considered. In this case [Virustotal said 19 out of 68 engines](https://www.virustotal.com/gui/file/b730e776f383e972c631f3f8d3515cbd2001a679f010f3853920985817c81128) flagged the file. One of the bits of info provided as justification is 'invalid-rich-pe-linker-version'. There's post in [the forums on Malwarebytes](https://forums.malwarebytes.com/topic/272544-false-positive-on-exes-created-by-my-software/) talking about false positives from this cause. A post on [Reddit's /r/Visual Studio](https://www.reddit.com/r/VisualStudio/comments/qfdy2o/i_noticed_that_x86_vs2019_projects_are_flagged_as/) suggests that VS2019 quite often produces binaries that false positive. These may be an artifact of the engine used not being up to date with the semantics of newer linkers.

I also tried submitting the binary to [Jotti](https://virusscan.jotti.org/en-US/filescanjob/u2d6qpcz7x) as well. Microsoft [Security Intelligence](https://www.microsoft.com/en-us/wdsi/filesubmission) has a submission form for software developers to submit misclassified examples. Perhaps submitting that release will better train Windows Defender.

At any rate, Windows Defender scrubs benchmark_radix_tree.exe from the downloaded zip. I'm not sure if it's even necessary for libzmq to function, but I thought you should be aware.

**Comment by bluca** [comment]
thanks for the report, but considering they all show different things, and that it's built on a cloud provider, let's just mark it as a false positive and ignore it
