### ISSUE TITLE
Compile and run the demo of czmq, encounter error 22: Invalid argument, I don't know how to solve it

### ISSUE THREAD

**Issue by byrnexu** [zeromq/libzmq#4355]
*Please use this template for reporting suspected bugs or requests for help.*

# Issue description
I  just started to learn zmq and run the demo, but the following error is reported, please tell me what is the reason, the message.

# Environment
Ubuntu 20.04.3 LTS

* libzmq version (commit hash if unreleased): libzmq-4.3.4 
* OS: Ubuntu 20.04.3 LTS

# Minimal test code / Steps to reproduce the issue
  int main (void) {
       zsock_t *publisher = zsock_new (ZMQ_PUB);                                                                                                                                               
       printf("status: %d:%s\n", zmq_errno(), zmq_strerror(zmq_errno()));  
       zsock_set_curve_server (publisher, true);                                                                                                                                               
       puts ("Hello, Curve!");
       zsock_destroy(&publisher);
       return 0;
   }
1.  

# What's the actual result? (include assertion message & call stack if applicable)
22: Invalid argument

# What's the expected result?

**Comment by byrnexu** [comment]
Accidentally submitted, this is a supplementary [note：
I debugged the source code of zmq and found that the error is located in xpub.cpp

 int zmq::xpub_t::xsetsockopt (int option_,
                               const void *optval_,
                               size_t optvallen_)
The incoming option_ is ZMQ_LINGER, but the function has no code to handle this value, so there is an error, what could be the reason? The versions I use are libzmq-4.3.4 and czmq-4.2.1

[https://i.stack.imgur.com/YitD9.png](url)

**Comment by byrnexu** [comment]
The following is my question on stackoverflow with debugging screenshots
[https://stackoverflow.com/questions/71250149/compile-and-run-the-demo-of-czmq-encounter-error-22-invalid-argument-i-dont](url)

**Comment by bluca** [comment]
Use one of these resources for help requests: https://zeromq.org/our-community/
