### ISSUE TITLE
skipped tests register as failed with earlier versions of cmake

### ISSUE THREAD

**Issue by bill-torpey** [zeromq/libzmq#4375]
# Environment

* libzmq version (master): 
* OS: CentOS 7

# Minimal test code / Steps to reproduce the issue

1.  Run unit tests under CentOS 7

# What's the actual result? (include assertion message & call stack if applicable)

Skipped tests show up as failed

# What's the expected result?

Skipped tests should show up as passed

**Comment by bill-torpey** [comment]
Under CentOS 7 with default cmake (2.8.12), unit tests fail like so:

```
        Start 100: test_shutdown_stress_tipc
100/117 Test #100: test_shutdown_stress_tipc ........***Skipped   0.00 sec
...
91% tests passed, 11 tests failed out of 117

Total Test time (real) = 163.90 sec

The following tests FAILED:
	 73 - test_connect_null_fuzzer (Not Run)
	 74 - test_bind_null_fuzzer (Not Run)
	 75 - test_connect_fuzzer (Not Run)
	 76 - test_bind_fuzzer (Not Run)
	 93 - test_address_tipc (Not Run)
	 94 - test_pair_tipc (Not Run)
	 95 - test_reqrep_device_tipc (Not Run)
	 96 - test_reqrep_tipc (Not Run)
	 98 - test_sub_forward_tipc (Not Run)
	 99 - test_connect_delay_tipc (Not Run)
	100 - test_shutdown_stress_tipc (Not Run)
Errors while running CTest
make: *** [test] Error 8
[btorpey@bt-brix7 master]$ cmake -version
cmake version 3.7.1

CMake suite maintained and supported by Kitware (kitware.com/cmake).
[btorpey@bt-brix7 master]$ 
```

Skipped tests do not trigger failure with a more recent version of cmake (3.12.3) on CentOS 7, nor with the default (3.16.3) version of cmake on Ubuntu 20.04:

```
        Start 100: test_shutdown_stress_tipc
100/117 Test #100: test_shutdown_stress_tipc ........***Skipped   0.01 sec
...
100% tests passed, 0 tests failed out of 117

Total Test time (real) = 163.54 sec

The following tests did not run:
	 73 - test_connect_null_fuzzer (Skipped)
	 74 - test_bind_null_fuzzer (Skipped)
	 75 - test_connect_fuzzer (Skipped)
	 76 - test_bind_fuzzer (Skipped)
	 93 - test_address_tipc (Skipped)
	 94 - test_pair_tipc (Skipped)
	 95 - test_reqrep_device_tipc (Skipped)
	 96 - test_reqrep_tipc (Skipped)
	 98 - test_sub_forward_tipc (Skipped)
	 99 - test_connect_delay_tipc (Skipped)
	100 - test_shutdown_stress_tipc (Skipped)
btorpey@bt-brixu:~/work/libzmq/master$ cmake -version
cmake version 3.16.3

CMake suite maintained and supported by Kitware (kitware.com/cmake).
btorpey@bt-brixu:~/work/libzmq/master$ 
```

**Comment by bluca** [comment]
Looks like a cmake bug?

**Comment by bill-torpey** [comment]
For sure.  

I've updated our fork with `cmake_minimum_required(VERSION "3.12.3")` in tests -- curious if anyone has any thoughts about what the min version should be.  FWIW, I know that 3.7.1 is NG, and 3.12.3 is OK.  

I can submit a PR with 3.12.3, or do you have other thoughts?  (I'd prefer not to do a binary search on cmake versions to find the oldest OK version ;-)

**Comment by bill-torpey** [comment]
But that means the unit tests will fail in those environments.  What about overriding ZMQ_BUILD_TESTS if cmake version is NG?

**Comment by bill-torpey** [comment]
lmk if you're OK with this approach: https://github.com/zeromq/libzmq/pull/4376
