### ISSUE TITLE
add use external event loop  support

### ISSUE THREAD

**Issue by calvin2021y** [zeromq/libzmq#4393]
# Issue description

libzmq can not use with a event loop like libuv. 

# What's the expected result?

I expected libzmq can provide callback function to use with event loop. nats.c, curl or libwebsockets suppor this.

**Comment by sphaero** [comment]
Any example of this not working? It should work using filedescriptor polling.

**Comment by calvin2021y** [comment]
with filedescriptor polling, how to handle the auto reconnection if connection closed ?

**Comment by sphaero** [comment]
I have no idea, what issue do you have?

**Comment by calvin2021y** [comment]
I like zmq support work with exists event loop, so other login can work without lock in a single thread.

**Comment by cyanide-burnout** [comment]
> with filedescriptor polling, how to handle the auto reconnection if connection closed ?

Via monitoring socket

**Comment by bluca** [comment]
Already supported via ZMQ_FD, see for example https://funcptr.net/2012/09/10/zeromq---edge-triggered-notification/ or any other result when googling for ZMQ_FD
