### ISSUE TITLE
Add option for removing -Werror

### ISSUE THREAD

**Issue by imjelde** [zeromq/libzmq#4402]
*Please use this template for reporting suspected bugs or requests for help.*

# Issue description

-Werror is a too strict compiler option. Is it possible to remove -Werror as an option for “consumer” building, since it’s not a stable target for people who aren’t all using the same blessed-by-dev-team tool chain

# Environment

* libzmq version (commit hash if unreleased): 4.3.4
* OS: centos7

# Minimal test code / Steps to reproduce the issue

# What's the actual result? (include assertion message & call stack if applicable)

Failure building the tests of zmq

# What's the expected result?

**Comment by bluca** [comment]
https://github.com/zeromq/libzmq/blob/master/configure.ac#L204
