### ISSUE TITLE
libzmq aborted on ypipe.hpp::probe when invoking zmq_poll

### ISSUE THREAD

**Issue by Rensj** [zeromq/libzmq#4416]
*Please use this template for reporting suspected bugs or requests for help.*

# Issue description
When invoking function zmq_poll do poll a zmq dealer, it aborted and the program exited
# Environment

* libzmq version (commit hash if unreleased): 4.3.4
* OS:  CentOS Linux release 7.9.2009 (Core)

# Minimal test code / Steps to reproduce the issue

1.   not reproducible for now

# What's the actual result? (include assertion message & call stack if applicable)
and gave the following stack back trace:
(gdb) bt
#0  0xb7d0c2a0 in raise () from /lib/libc.so.6
#1  0xb7cf17ac in abort () from /lib/libc.so.6
#2  0x0f779d24 in zmq::zmq_abort (errmsg_=errmsg_@entry=0xf7fb1f8 "rc") at src/err.cpp:88
#3  0x0f7a9158 in zmq::ypipe_t<zmq::msg_t, 256>::probe (this=0x10efaaf0, fn_=0xf7a5af0 <zmq::pipe_t::is_delimiter(zmq::msg_t const&)>) at src/ypipe.hpp:172
#4  0x0f7a73f4 in zmq::pipe_t::check_read (this=0x10fb46d0) at src/pipe.cpp:186
#5  0x0f78f024 in zmq::fq_t::has_in (this=0x10fb4238) at src/fq.cpp:139
#6  0x0f78a128 in zmq::dealer_t::xhas_in (this=<optimized out>) at src/dealer.cpp:113
#7  0x0f7bdfdc in zmq::socket_base_t::has_in (this=0x10fb3d10) at src/socket_base.cpp:1433
#8  zmq::socket_base_t::getsockopt (this=0x10fb3d10, option_=option_@entry=15, optval_=optval_@entry=0x94dbc224, optvallen_=optvallen_@entry=0x94dbc220) at src/socket_base.cpp:488
#9  0x0f7dfff4 in zmq_getsockopt (s_=<optimized out>, option_=option_@entry=15, optval_=optval_@entry=0x94dbc224, optvallen_=optvallen_@entry=0x94dbc220) at src/zmq.cpp:288
#10 0x0f7e28e4 in zmq_poll (items_=0x94dbc450, nitems_=1, timeout_=5000) at src/zmq.cpp:999

# What's the expected result?

**Comment by bluca** [comment]
are you setting up/using the same socket from multiple threads?

**Comment by Rensj** [comment]
Thanks bluca for the reply. 
The same dealer client is used by multiple threads in this case.

**Comment by bluca** [comment]
As the documentation says, that is not supported and it's a bug in the application.

**Comment by Rensj** [comment]
Thank you bluca. Changed the code to seperate client as per the threads, and this issue was not observed any more.
