### ISSUE TITLE
Licensing mixup in display on github page

### ISSUE THREAD

**Issue by huberteff** [zeromq/libzmq#4423]
*Please use this template for reporting suspected bugs or requests for help.*

# Issue description

The github website says on the upper right that 0MQ is licensed under the GPL,
further down the website and also in the zmq.7 manpage, LGPL is stated.
I think LGPL is right, and the "GPL" on the upper right on the github page should be changed.

# Environment

[https://](https://github.com/zeromq/libzmq)

* libzmq version (commit hash if unreleased):  none - website as of Sep 13th 2022
* OS: Windows

# Minimal test code / Steps to reproduce the issue

1.  Goto https://github.com/zeromq/libzmq
2. See "About" on the upper right
3. See "GPL-3.0, Unknown licenses found"

# What's the actual result? (include assertion message & call stack if applicable)

Is: "GPL-3.0, Unknown licenses found"

# What's the expected result?

Expected: "LGPL-3.0"

**Comment by bluca** [comment]
This is under Github's control, we cannot change it, please file a bug with Github

**Comment by huberteff** [comment]
When I first looked at the 0mz license, I was confused by the presence of both a COPYING (=GPL) and COPYING.LESSER (=LGPL) file in the source code. Maybe GitHub was confused by this as well. 

Github documentation suggests adding a LICENSE.txt file to clarify things, so maybe this can be done for the 0mq repository as well: 
https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/licensing-a-repository

**Comment by bluca** [comment]
No, we will not add extra files, we are following the recommended scheme from the license authors (fsf), this is a Github UI bug that it doesn't take that into account, please file a bug with Github

**Comment by huberteff** [comment]
Hello bloca, thanks for explaining. I agree that there appears to be some magic picking up the wrong license.
Just for my own understanding: Can you please explain why is there a COPYING file at all, if 0MQ is under the LGPL?
