### ISSUE TITLE
ENABLE_DRAFTS being overridden by the presence of a .git directory

### ISSUE THREAD

**Issue by rikercd** [zeromq/libzmq#4440]
# Issue description

```
if (EXISTS "${CMAKE_SOURCE_DIR}/.git")
    OPTION (ENABLE_DRAFTS "Build and install draft classes and methods" ON)
else ()
    OPTION (ENABLE_DRAFTS "Build and install draft classes and methods" OFF)
endif ()
```

This block of CMake is problematic for those who want to use industry standard package management schemes like conan. Conan-center added the ability to enable drafts in the cppzmq package in [this PR](https://github.com/conan-io/conan-center-index/pull/8405), however the above block of CMake breaks that functionality, making it _impossible_ to get a draft build of cppzmq (and by extension libzmq) without building and installing manually from source, which is problematic in a number of ways in the modern software development landscape. 

One potential solution is for this block to be changed such that ENABLE_DRAFTS is only configured in this way **if it is not already turned on**, or for this to simply be removed all together. 

# Environment

* libzmq version (commit hash if unreleased): 4.3.4 (present in Master)
* OS: All

# Minimal test code / Steps to reproduce the issue

1. Import libzmq into a test project either via conan or downloading the source package through github (not cloning)
2. Build libzmq by providing CMake `-DENABLE_DRAFTS=ON` on the command line 
3. Verify via console output or other means of inspection that the draft API is **not built** and is not usable by the project importing libzmq 

# What's the actual result? (include assertion message & call stack if applicable)
ENABLE_DRAFTS is set to ON or OFF depending **solely** on whether or not there is a .git repository present

# What's the expected result?
ENABLE_DRAFTS should be able to be configured by an importer of this package regardless of whether or not they cloned the git repository. Conan pulls down the released source exactly as-is in the tag, sub the .git directory (because it is not cloning a git repository), yet is entirely unable to build some of the functionality present in the package it pulls down.

**Comment by bluca** [comment]
This is by design, and only affects the default, it can be overridden as needed

**Comment by rikercd** [comment]
How exactly, so that I can open an issue against conan-center? `ENABLE_DRAFTS` gets turned ON or OFF regardless what you tell CMake to set it to because of the above block.

**Comment by bluca** [comment]
No, that's the default if it is not set to anything

**Comment by gummif** [comment]
If you are building using conan then I believe you must specify the with_draft_api option in the recipe, not when invoking cmake.

**Comment by rikercd** [comment]
> If you are building using conan then I believe you must specify the with_draft_api option in the recipe, not when invoking cmake.

Right, and specifying with_draft_api simply turns ENABLE_DRAFTS on. Maybe there is something else going on under the hood with conan-center that is making this not work but the with_draft_api option does NOT build drafts - and the CMake logs indicate as such.
