### ISSUE TITLE
Fails build when using `--with-vmci`

### ISSUE THREAD

**Issue by oliverkurth** [zeromq/libzmq#4454]
# Issue description

Fails build when using `--with-vmci`

# Environment

* libzmq version (commit hash if unreleased): 4.3.4
* OS: Ubuntu 20.04

# Minimal test code / Steps to reproduce the issue

1.  `./configure --with-vmci && make`

# What's the actual result? (include assertion message & call stack if applicable)

```
  CXX      src/libzmq_la-vmci_connecter.lo
src/vmci_connecter.cpp:38:10: fatal error: stream_engine.hpp: No such file or directory
   38 | #include "stream_engine.hpp"
      |          ^~~~~~~~~~~~~~~~~~~
compilation terminated.
```

# What's the expected result?

successful build

**Comment by oliverkurth** [comment]
I forgot to mention: to reproduce, you also need to get the file https://github.com/vmware/open-vm-tools/blob/master/open-vm-tools/lib/include/vmci_sockets.h and copy it to `/usr/include`. Otherwise the build will fail sooner.

**Comment by bluca** [comment]
already fixed in main
