### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by themightyoarfish** [zeromq/libzmq#4455]
The current release is quite old and doesn't have essential bug fixes such as https://github.com/zeromq/libzmq/pull/4323 in it.

Any chance of a new release?

**Comment by boscosiu** [comment]
+1.  Please let us know if we can assist in any way.

**Comment by f18m** [comment]
I agree, a new release would be nice to have :)

**Comment by aminya** [comment]
`zeromq.js` also appreciates a new release. I am currently switching to the unreleased version, which is not ideal
https://github.com/zeromq/zeromq.js/pull/512

**Comment by mapi-ng** [comment]
Hello,

Is there a plan for new release?

Can I help in some way (e.g. testing)?

**Comment by DonCamillo72** [comment]
The last release v4.3.4 was published on 2021-01-17.
Many bugs and problems have since been fixed.
When is the next release planned?

**Comment by f18m** [comment]
Yeah honestly it would be really nice to get a new release..
I'm using latest "master" branch in all projects but having a tag would be
better for tracking purposes...

Luca any comment on this topic?

Thanks,
Francesco


Il giorno ven 10 feb 2023 alle ore 08:24 DonCamillo72 <
***@***.***> ha scritto:

**Comment by mapi-ng** [comment]
> I'm using latest "master" branch in all projects but having a tag would be
better for tracking purposes...

Same here. New version tag would be really great for traceability.

@bluca Tagging you in case you're not getting notifications for this thread.

Thanks!

**Comment by mitchellwrosen** [comment]
Friendly ping!
