### ISSUE TITLE
Does libzmq handler client/server mismatch on authentication ?

### ISSUE THREAD

**Issue by fbacchella** [zeromq/libzmq#4485]
The specifications for ZMTP 3.0 and 3.1 reserve a byte to indicate that one side is an authentication client or server:
```
;   The greeting announces the protocol details
greeting = signature version mechanism as-server filler
...
;   Is the peer acting as server for security handshake?
as-server = %x00 | %x01
```

Looking at the current git, it looks like it’s not handled, neither in writing or reading:

https://github.com/zeromq/libzmq/blob/bdd471fa17100fe84f64da348951dab3ee4780bb/src/zmtp_engine.cpp#L220

and

https://github.com/zeromq/libzmq/blob/bdd471fa17100fe84f64da348951dab3ee4780bb/src/zmtp_engine.cpp#L345

With Curve for example, when two clients are connected, they wait for the other side infinitely, without any warning or error.

I think it should by implemented but it needs two things:
* a socket option ZMQ_CLIENT_SERVER_STRICT, when two side implementing the strict conformance are communicating.
* a ZMQ_PROTOCOL_ERROR_ZMTP_CLIENT_SERVER_MISMATCH error, used by monitors.

I have neither the time or competences to implement that on C++, but plan to add that to jeromq. Is there a way to synchronized on names and constant values, to make code comparaison easier, and avoid class later ?

**Comment by bluca** [comment]
https://github.com/zeromq/libzmq/issues/2821
