### ISSUE TITLE
Licensing clarification request

### ISSUE THREAD

**Issue by Entropy512** [zeromq/libzmq#4495]
The ZMQ README states that it is LGPLv3 with a static linking exception, and https://github.com/zeromq/libzmq/issues/2376 also implies that the ZMQ developers believe that the license is LGPLv3 with a static linking exception.

If this is the case, why is standard GPL (and not LGPL) license text present at https://github.com/zeromq/libzmq/blob/master/COPYING in addition to COPYING.LESSER?

If I were to submit this to my legal team for approval in its current state, I would get a definitive NAK from them due to the existence of that file.

**Comment by bluca** [comment]
> If I were to submit this to my legal team for approval in its current state, I would get a definitive NAK from them due to the existence of that file.

Then get a better legal team which actually understands how licenses work https://www.gnu.org/licenses/gpl-howto.html
