### ISSUE TITLE
Asynchronous ROUTER/DEALER without loosing Request/Reply association

### ISSUE THREAD

**Issue by Placeblock** [zeromq/libzmq#4511]
*Please use this template for reporting suspected bugs or requests for help.*

# Issue description
I want to create a ROUTER Server that acts like an asynchronous REPLY Socket.
However I also want to create an client that acts like a asynchronous REQUEST Socket.
(Like described in the docs: [https://zguide.zeromq.org/docs/chapter3/#The-DEALER-to-ROUTER-Combination](https://zguide.zeromq.org/docs/chapter3/#The-DEALER-to-ROUTER-Combination))

The problem I am facing is that i still want to associate a Reply from the Server to a Request from the client. (Isn't that the reason why you use Req/Rep?)
It seems like the whole Request / Reply pattern gets lost, which is obvious as you can send as many requests as fast as you want and get responses in no meaningful order because everything is asynchronous.

I would have to implement some sort of request id which is contained in my response too. Then I could associate a response with the according request if I save the id in the client.
Is there a better solution or do I have to implement all this by myself?

In the same section in the docs it says (cite):

> Because both DEALER and ROUTER can work with arbitrary message formats, if you hope to use these safely, you have to become a little bit of a protocol designer. At the very least you must decide whether you wish to emulate the REQ/REP reply envelope. It depends on whether you actually need to send replies or not.

I am not sure if this describes another problem or if I've just not understood it correctly.

Have a great day 😃

**Comment by ljluestc** [comment]
```

import zmq
import uuid
import threading
import time

def dealer_client(client_id):
    context = zmq.Context()
    socket = context.socket(zmq.DEALER)
    socket.setsockopt_string(zmq.IDENTITY, client_id)
    socket.connect("tcp://localhost:5555")

    print(f"Client {client_id} connected.")

    # A dictionary to store pending requests
    pending_requests = {}

    # Function to send requests
    def send_requests():
        for i in range(5):
            request_id = str(uuid.uuid4())  # Generate a unique ID for the request
            request_body = f"Hello {i} from {client_id}"
            print(f"Sending request: {request_body} with ID: {request_id}")
            
            # Store the request in pending_requests
            pending_requests[request_id] = request_body
            
            # Send a multipart message
            # Format: [empty_frame, request_id, request_body]
            socket.send_multipart([b"", request_id.encode(), request_body.encode()])
            time.sleep(1)

    # Function to receive responses
    def receive_responses():
        while True:
            # Receive a multipart response
            # Format: [empty_frame, request_id, response_body]
            empty_frame, request_id, response_body = socket.recv_multipart()
            
            # Decode the received data
            request_id = request_id.decode()
            response_body = response_body.decode()

            # Match the response to the original request
            if request_id in pending_requests:
                original_request = pending_requests.pop(request_id)
                print(f"Received response: {response_body} for request: {original_request}")
            else:
                print(f"Received unknown response with ID: {request_id}")

    # Start threads for sending and receiving
    threading.Thread(target=send_requests, daemon=True).start()
    threading.Thread(target=receive_responses, daemon=True).start()

    # Keep the main thread alive
    while True:
        time.sleep(1)

if __name__ == "__main__":
    client_id = str(uuid.uuid4())  # Unique identity for the client
    dealer_client(client_id)
```

**Comment by Placeblock** [comment]
Looks promising! I will take a closer look when I have time, but thanks for your example 😃 !
