### ISSUE TITLE
Function not implemented (src/signaler.cpp:324)

### ISSUE THREAD

**Issue by mbasilSB** [zeromq/libzmq#4515]
*Please use this template for reporting suspected bugs or requests for help.*

# Issue description
Hi, I'm getting the following error when executing the C client example on the web on a buildroot based linux image and not finding which could be the reason for this:

Function not implemented (src/signaler.cpp:324)

Appreciate any help

Thanks in advance

# Environment

* libzmq version (commit hash if unreleased): 4.1.5
* OS: Buildroot Linux

**Comment by guill-delacourt** [comment]
I have a similar error message when there is a failure in a errno_assert in the code.
I find that ZMQ is not really explicit when a failure happens in an assertion. These assertions call abort() without any real explaination outside telling "go check the source code".

**Comment by mbasilSB** [comment]
Yes exactly, mine also appears in a errno_assert, did you find any solution to that?

**Comment by guill-delacourt** [comment]
My problem was elsewhere (epoll.cpp) and the system call the errno_assert was reporting was epoll_create, as the kernel on my target was not compiled with support for those. So the thing to do here is to update the kernel or recompile it with the right options. If you can rebuild your buildroot system, it's probably the thing to do.
You should check which call is done before the errno_assert, as this is what really fails. This will tell you what feature you need on your system.

**Comment by bluca** [comment]
These are detected at build time, if your build system and runtime environment are so different that core syscalls are missing then it's something you need to fix in your build system
