### ISSUE TITLE
Receive a few duplicated messages instead of all different with PUSH/PULL

### ISSUE THREAD

**Issue by ppolyanskiyy** [zeromq/libzmq#4536]
# Issue description
I receive a few duplicated messages instead of all different. 
The PUSH socket sends 5 different messages of the same size one by one.
The PULL socket receives exactly 5 messages but some of them are duplicated, and some of them are not received.

I attach the file with most important part of wrapper for libzmq.
[ZmqWrapper.zip](https://github.com/zeromq/libzmq/files/11138378/ZmqWrapper.zip)

# Environment
Windows 10 Enterprise. Version 22H2. OS build 19045.2728

* libzmq version (commit hash if unreleased): 4.3.4
* OS: Windows 10

# Minimal test code / Steps to reproduce the issue

1. Create a PUSH socket for client
2. Create a PULL socket for server
3. In server use while loop calling receive
4. In client send a few messages one by one

Important note: the context is create from one thread but send and receive is called from the different.
(Means send is called from one thread, but not the same where context and socket is created, and receive from it's own)

# What's the actual result? (include assertion message & call stack if applicable)
Receive same number of messages, but some of the are duplicated

# What's the expected result?
Receive all different messages

**Comment by bluca** [comment]
> Means send is called from one thread, but not the same where context and socket is created

sockets cannot be referenced from multiple threads

**Comment by mitchellwrosen** [comment]
@ppolyanskiyy could you make a new issue then, without a repro that involves using a socket from a different thread that the one in which it was created?
