### ISSUE TITLE
When is new version of libzmq getting released?

### ISSUE THREAD

**Issue by GauravAccGit** [zeromq/libzmq#4547]
*Please use this template for reporting suspected bugs or requests for help.*

# Issue description
Its been more than 2 years since libzmq release 4.3.4 is GAed. Kindly share if any plan to release any new version

# Environment

* libzmq version (commit hash if unreleased): 4.3.4
* OS: Linux

# Minimal test code / Steps to reproduce the issue

1.  

# What's the actual result? (include assertion message & call stack if applicable)

# What's the expected result?

**Comment by theodoregoetz** [comment]
I have a draft PR for releasing 4.4.0 here: #4550

**Comment by Mathsoum** [comment]
This issues follows a discussion from the mailing list  
https://lists.zeromq.org/pipermail/zeromq-dev/2023-May/thread.html

**Comment by bluca** [comment]
This is an issue tracker, not a discussion forum
