### ISSUE TITLE
New version?🤔

### ISSUE THREAD

**Issue by wuch-g2v** [zeromq/libzmq#4551]
https://github.com/zeromq/libzmq/compare/v4.3.4...master I shows +300 commits since last release which was in 2021.

Do you have any plans to release new version soon? 🤔

**Comment by bluca** [comment]
This is an issue tracker, not a discussion forum

**Comment by calvin2021y** [comment]
then maybe consider enable github discussions.  

If there is a roadmap in readme also may help
