### ISSUE TITLE
Old release license issues

### ISSUE THREAD

**Issue by VeryCoolVenkee** [zeromq/libzmq#4568]
Hello esteemed contributors of libzmq,

I have a couple of inquiries regarding the license, and I would greatly appreciate your insights:
1. It has come to my attention that the license on the master branch has been updated to MPL v2. May I kindly inquire if the same license applies to other tags as well? Specifically, if I were to utilize version 4.3.2.
2. I was wondering if there is an estimated timeline for the release of a stable version? We are eager to make use of your code, which is licensed under MPL v2, at the earliest convenience.

Thank you kindly for your time and assistance!

**Comment by bluca** [comment]
> It has come to my attention that the license on the master branch has been updated to MPL v2. May I kindly inquire if the same license applies to other tags as well? Specifically, if I were to utilize version 4.3.2.

Of course not, it cannot be retroactive, the license of the code you are using is defined in the code you are using
