### ISSUE TITLE
Simplify setsockopt

### ISSUE THREAD

**Issue by mrx23dot** [zeromq/libzmq#4583]
# Issue description
could we simplify this?

```
int relaxed = 1;
zmq_setsockopt (s, ZMQ_REQ_RELAXED, &relaxed, sizeof (relaxed));
```

e.g. to
`zmq_setsockopt (s, ZMQ_REQ_RELAXED, 1, NULL);`

in python it's so nicer
`zpub.setsockopt(zmq.IPV4ONLY, 1)`

# Environment
* libzmq version (commit hash if unreleased): 4.2
* OS: debian

**Comment by bluca** [comment]
No, as that's an API breaking change
