### ISSUE TITLE
Q: Can you share the design of libzmq?

### ISSUE THREAD

**Issue by cathaysia** [zeromq/libzmq#4585]
As the title says, can you share your experience with libzmq design? for example:

- What is the basic logic of libzmq code level design?
- Which designs of libzmq do you think are excellent? Is it something you are proud of?
- If you were to redesign libzmq, what do you think you would like to improve?

The issue of appeal is mainly around the codebase, not around the specification. (After all, the specification is very clear, isn’t it)

If you think my question shouldn't be here, please close it.

**Comment by bluca** [comment]
https://zguide.zeromq.org/

**Comment by cathaysia** [comment]
Hello, I am not new to zeromq. In fact, the software I wrote using zmq has been running stably on the server for a long time.
I'm asking because I've recently wished to implement zmq using rust. Although there is zmq.rs now, its architecture is not what I hoped it would be. So I wanted to ask if you guys could give me some advice.
