### ISSUE TITLE
ROUTER/DEALER mod restart DEALER only will cause Host unreachable Error, DEALER can't recv msg from ROUTER after restart DEALER only although there still extists tcp connect between them

### ISSUE THREAD

**Issue by betterlch** [zeromq/libzmq#4603]
*Please use this template for reporting suspected bugs or requests for help.*

# Issue description
ROUTER/DEALER mod restart DEALER only will cause Host unreachable Error
https://github.com/zeromq/pyzmq/issues/1899

# Environment

* libzmq version (commit hash if unreleased): 4.3.4
* OS: Centos
python version: Python 3.9.9
pyzmq version: 22.3.0 installed by pip
# Minimal test code / Steps to reproduce the issue
https://github.com/zeromq/pyzmq/issues/1899#issuecomment-1739001600

```
# send.py
import zmq
import time

ctx = zmq.Context()
send_sock = ctx.socket(zmq.ROUTER)
send_sock.bind('tcp://127.0.0.1:9002')
# send_sock.setsockopt(zmq.ROUTER_MANDATORY, 1)  # if set, will raise "zmq.error.ZMQError: Host unreachable" immediately

while 1:
    send_sock.send_multipart([b'1', b'ok'], zmq.NOBLOCK)
    time.sleep(2)
```
```
# recv.py
import zmq

ctx = zmq.Context()
recv_sock = ctx.socket(zmq.DEALER)
recv_sock.setsockopt_string(zmq.IDENTITY, '1')
recv_sock.connect('tcp://127.0.0.1:9002')

while 1:
    print(recv_sock.recv_multipart()[0])
```
By unbind socket and rebind in ROUTER recover without restart ROUTER if  restart DEALER only

# What's the actual result? (include assertion message & call stack if applicable)

```
File "/data/lib64/python3.9/site-packages/zmq/sugar/socket.py", line 595, in send_multipart
    self.send(msg, SNDMORE | flags, copy=copy, track=track)
  File "/data/lib64/python3.9/site-packages/zmq/sugar/socket.py", line 547, in send
    return super(Socket, self).send(data, flags=flags, copy=copy, track=track)
  File "zmq/backend/cython/socket.pyx", line 718, in zmq.backend.cython.socket.Socket.send
  File "zmq/backend/cython/socket.pyx", line 765, in zmq.backend.cython.socket.Socket.send
  File "zmq/backend/cython/socket.pyx", line 247, in zmq.backend.cython.socket._send_copy
  File "zmq/backend/cython/socket.pyx", line 242, in zmq.backend.cython.socket._send_copy
  File "zmq/backend/cython/checkrc.pxd", line 28, in zmq.backend.cython.checkrc._check_rc
zmq.error.ZMQError: Host unreachable
```

# What's the expected result?
Work well after restart DEALER only

**Comment by Andrey36652** [comment]
@betterlch You should set ZMQ_ROUTER_HANDOVER to 1 on send_sock (for details refer to ZMQ_ROUTER_HANDOVER description here https://zeromq.readthedocs.io/en/latest/zmq_setsockopt.html ).
```python
# send.py
import zmq
import time

ctx = zmq.Context()
send_sock = ctx.socket(zmq.ROUTER)
send_sock.setsockopt(zmq.ROUTER_HANDOVER, 1)
send_sock.bind('tcp://127.0.0.1:9002')

while 1:
    send_sock.send_multipart([b'1', b'ok'], zmq.NOBLOCK)
    print('sent')
    time.sleep(2)
```
```python
# recv.py
import zmq

ctx = zmq.Context()
recv_sock = ctx.socket(zmq.DEALER)
recv_sock.setsockopt_string(zmq.IDENTITY, '1')
recv_sock.connect('tcp://127.0.0.1:9002')

while 1:
    print(recv_sock.recv_multipart())
```
Now you should be able to restart recv.py multiple times without restarting send.py

**Comment by betterlch** [comment]
> ```python
> send_sock.setsockopt(zmq.ROUTER_HANDOVER, 1)
> ```

Thanks for your reply.
ROUTER_HANDOVER seems first release at version 4.x? I havn't see it since I was using zmq 3.x

**Comment by Andrey36652** [comment]
Yes, seems like it was added in 0MQ version 4.1.0 rc1, released on 2014/10/14
