### ISSUE TITLE
Build issue on macOS 14.0

### ISSUE THREAD

**Issue by xanadu6291** [zeromq/libzmq#4610]
# Issue description
I can't build libzmq on macOS 14.0

# Environment
* libzmq version (commit hash if unreleased):  Ver.4.3.5
* OS: macOS 14.0

# Minimal test code / Steps to reproduce the issue
1.  I configure the latest stable release (Ver.4.3.5) of libzmq as follows:
$ ./configure --prefix=${TARGET} --enable-static --disable-shared --without-documentation

2. Then type make

# What's the actual result? (include assertion message & call stack if applicable)
I get the following error:
src/proxy.cpp:502:26: error: suggest braces around initialization of subobject [-Werror,-Wmissing-braces]
    stats_proxy stats = {0};
                         ^
                         {}
src/proxy.cpp:502:26: error: suggest braces around initialization of subobject [-Werror,-Wmissing-braces]
    stats_proxy stats = {0};
                         ^
                         {}
2 errors generated.
make[1]: *** [src/libzmq_la-proxy.lo] Error 1
make: *** [all-recursive] Error 1

# What's the expected result?
Build correctly.

**Comment by xanadu6291** [comment]
I removed 0 based on compiler suggestion. Which mean:
stats_proxy stats = {0};
to
stats_proxy stats = {};

Then compiled zeromq successfully. But make check failed with 1 item, tests/test_zmq_poll_fd.

Is it OK to remove 0 from stats_proxy stats?

**Comment by devnullpointer** [comment]
Same issue here building 4.3.5 on Ubuntu.

`
  CXX      src/libzmq_la-poller_base.lo
  CXX      src/libzmq_la-polling_util.lo
  CXX      src/libzmq_la-pollset.lo
  CXX      src/libzmq_la-precompiled.lo
  CXX      src/libzmq_la-proxy.lo
src/proxy.cpp:502:26: error: suggest braces around initialization of subobject [-Werror,-Wmissing-braces]
    stats_proxy stats = {0};
                         ^
                         {}
src/proxy.cpp:502:26: error: suggest braces around initialization of subobject [-Werror,-Wmissing-braces]
    stats_proxy stats = {0};
                         ^
                         {}
2 errors generated.
make[1]: *** [Makefile:5869: src/libzmq_la-proxy.lo] Error 1
make[1]: Leaving directory '/home/kyriv/work/github
`

**Comment by devnullpointer** [comment]
Tried 4.3.4 on Ubuntu 22.04 LTS and it builds fine. Seems like an issue with 4.3.5

**Comment by rbebb** [comment]
Is this issue resolved when using the latest version on the master branch?

**Comment by xanadu6291** [comment]
Tried latest master branch with macOS 14.7.1 and it can build without error!!

**Comment by eric-silk** [comment]
I am still experiencing this version with both 4.3.5 and the latest commit on the master branch in an Ubuntu 24.04.1 LTS Docker image using Clang 18.1.3. Curiously, I am not seeing this for either version with the same compiler in my host environment (also Ubuntu 24.04.1 LTS).
