### ISSUE TITLE
Assertion failed: pfd.revents & POLLIN (/zmq/build/libzmq-src/src/signaler.cpp:265)

### ISSUE THREAD

**Issue by OSHINRAJ** [zeromq/libzmq#4644]
# Issue description
Assertion failed: pfd.revents & POLLIN (/zmq/build/libzmq-src/src/signaler.cpp:265)

# Environment

* libzmq version (commit hash if unreleased): v4.3.4
* OS: Ubuntu 22.04.2 LTS

# Minimal test code / Steps to reproduce the issue

This seems to be an occasional bug, when zmq_close () API is called while zmq_send() is in blocking stage.

# What's the actual result? (include assertion message & call stack if applicable)

An assertion is occured in libzmq in src/signaler.cpp:265.

# What's the expected result?

The zmq_send() should fail with a proper error code instead of the assertion.

**Comment by bluca** [comment]
> This seems to be an occasional bug, when zmq_close () API is called while zmq_send() is in blocking stage.

How is it possible that you call zmq_close while zmq_send is blocked?

**Comment by OSHINRAJ** [comment]
Then, what is the use of inproc transport?

**Comment by bluca** [comment]
sender on one side, receiver on the other, check the zguide
