### ISSUE TITLE
Platform.hpp not found issue on macOS Sonoma and Xcode 15.2 

### ISSUE THREAD

**Issue by Mumthasir-vp** [zeromq/libzmq#4654]
*Please use this template for reporting suspected bugs or requests for help.*

# Issue description
I have installed **libzmq** using cocoapod.
`pod 'libzmq'`
After pod installation tried the following `cmake` installation as per the suggestion on this [existing created issue](https://github.com/zeromq/libzmq/issues/1928#issuecomment-1067569139)

# Environment

* OS: macOS Sonoma 14.3.1
* Xcode: 15.2
* libzmq version: 4.0.4
* cmake: 3.28.3
* cocoapod: 1.15.2

# Minimal test code / Steps to reproduce the issue

1.  Try installing libzmq with the specified env on a new project. 
2.  Build the project.

# What's the actual result? (include assertion message & call stack if applicable)
Showing 'Plaform.hpp file not found'
<img width="317" alt="Screenshot 2024-02-11 at 1 38 08 PM" src="https://github.com/zeromq/libzmq/assets/134942402/4e3de96c-c721-4ee2-9ea6-4f38d228c40b">

# What's the expected result?
Should be able to run the project without any error.

**Comment by bluca** [comment]
> I have installed libzmq using cocoapod

This is an external project with no relationship with this, so please open an issue with the owner of that tool
