### ISSUE TITLE
NPM install failed for zeromq dependency while installing device farmer STF. NPM logs available in the description.

### ISSUE THREAD

**Issue by namanthapliyal** [zeromq/libzmq#4655]
OS:
PRETTY_NAME="Ubuntu 22.04.3 LTS"
NAME="Ubuntu"

Attaching the npm error logs in npm install command. I have already installed the libzmq using configure, make, install. And exported the library path using command: export LD_LIBRARY_PATH=/usr/local/lib:$LD_LIBRARY_PATH

[zeromq npm logs.txt](https://github.com/zeromq/libzmq/files/14233804/zeromq.npm.logs.txt)

**Comment by bluca** [comment]
NPM is a separate system, this is not a tracker for NPM problems
