### ISSUE TITLE
Why am I no longer on the contributor list?

### ISSUE THREAD

**Issue by americaboy** [zeromq/libzmq#4686]
A few years ago, I submitted some bug fixes,
I remember my name used to be on the contributor list, but now it's gone. What could be the reason for removing me?

**Comment by bluca** [comment]
No, you never were on that list as you can see in the git log: https://github.com/zeromq/libzmq/commits/master/AUTHORS

feel free to send a PR to add yourself if you want to

**Comment by americaboy** [comment]
Why? How can one become a contributor？
This is my previous modification submission, and it has also been accepted. 
https://github.com/zeromq/libzmq/pull/4053
