### ISSUE TITLE
what is the license of libzmq v4.3.4

### ISSUE THREAD

**Issue by lialin86** [zeromq/libzmq#4715]
*Please use this template for reporting suspected bugs or requests for help.*

# Issue description
License of Readme tells that the license is Lesser General Public License (LGPL), Is it wrong? should it be MPL-2.0 license?
link: [https://github.com/zeromq/libzmq/tree/v4.3.4](https://github.com/zeromq/libzmq/tree/v4.3.4)

**Comment by bluca** [comment]
The license was changed in the latest version, in previous versions it was LGPL3.0+ plus exceptions. Check the COPYING plus COPYING.LESSER files.
