### ISSUE TITLE
CI build android on ubuntu-latest failed

### ISSUE THREAD

**Issue by githejie** [zeromq/libzmq#4725]
# Issue description
## Error logs:
ld.lld: error: non-exported symbol '__aeabi_ldivmod' in '/usr/local/lib/android/sdk/ndk/27.0.12077973/toolchains/llvm/prebuilt/linux-x86_64/lib/clang/18/lib/linux/libclang_rt.builtins-arm-android.a(aeabi_ldivmod.S.o)' is referenced by DSO 'src/.libs/libzmq.so'
clang++: error: linker command failed with exit code 1 (use -v to see invocation)
make[1]: *** [Makefile:4155: perf/local_lat] Error 1
make[1]: Leaving directory '/home/runner/work/libzmq/libzmq/libzmq'
make: *** [Makefile:8442: install-recursive] Error 1
Error: Process completed with exit code 1.

More details: https://github.com/zeromq/libzmq/actions/runs/10338824667/job/28617425863

## Problem analysis:
The current project only supports android-ndk-r25, while ubuntu-latest provides android-ndk-r27 by default.

## Solution:
Fix the NDK version in the CI script to android-ndk-r25 before the project adapts to other NDK versions.

**Comment by benjdero** [comment]
```
LIBZMQ - Configured NDK_VERSION: android-ndk-r25 (2500).
LIBZMQ (arm) - Using existing NDK folder '/usr/local/lib/android/sdk/ndk/27.0.12077973'.
```

Those 2 lines are interesting as they show the scripts are set to use NDK version r25 but are actually using the NDK version r27 installed locally.

Right now, the build scripts are compatible with NDK up to r26d.

Are you sure the NDK r27 is installed by default on ubuntu:latest? It's located in `/usr/local/` so it must come from libzmq build scripts somehow.

**Comment by benjdero** [comment]
NDK version 27 is installed by default on Github action runner images:

https://github.com/actions/runner-images/blob/ubuntu22/20240804.1/images/ubuntu/Ubuntu2204-Readme.md#android

If you set ANDROID_NDK_ROOT (like you did in your pull request) to use the right NDK it should fix the problem.

**Comment by githejie** [comment]
Hi @benjdero, I think the existence of `ANDROID_NDK_ROOT` environment variable in CI environment and the value of this environment variable is `/usr/local/lib/android/sdk/ndk/27.0.12077973` caused this problem.

I suspect that the `ANDROID_NDK_ROOT` environment variable is set in the latest `ubuntu-latest` image provided by GitHub Actions.
