### ISSUE TITLE
what is the licence for the older version of libzmq?

### ISSUE THREAD

**Issue by robbietu** [zeromq/libzmq#4733]
*Please use this template for reporting suspected bugs or requests for help.*

# Issue description
As we know that libzmq moved to MPL2.0 from 4.3.5. So what is the license of older version now? As I found  the description "libzmq used to be licensed under a custom LGPLv3 + static link exception license. The relicensing to MPL-2.0 has been completed with explicit permissions from all relevant copyright holders where necessary." in the web http://wiki.zeromq.org/area:licensing, does it mean that the whole project is under MPL2.0  now including the older versions?

**Comment by bluca** [comment]
https://github.com/zeromq/libzmq/issues/4715
