### ISSUE TITLE
where is version 5.2.2 ?

### ISSUE THREAD

**Issue by kexiongwang** [zeromq/libzmq#4749]
*Please use this template for reporting suspected bugs or requests for help.*

# Issue description

# Environment

* libzmq version (commit hash if unreleased): 
* OS: 

# Minimal test code / Steps to reproduce the issue

1.  

# What's the actual result? (include assertion message & call stack if applicable)

# What's the expected result?

**Comment by bluca** [comment]
No such thing exists, releases are here https://github.com/zeromq/libzmq/releases
