### ISSUE TITLE
Request for New Release

### ISSUE THREAD

**Issue by rbebb** [zeromq/libzmq#4754]
I'm wondering if it'd be possible to get a new release of libzmq since support has been added for Android NDK 25 and macOS 14.0.

**Comment by bluca** [comment]
This is a bug tracker, not a forum

**Comment by rbebb** [comment]
@bluca Could you let me know the correct place to submit a request?

**Comment by frakman1** [comment]
> This is a bug tracker, not a forum

You might want to consider enabling the Discussions feature for this repository. You can do so by going to Settings -> Features -> Discussions. This will give people a space to ask questions and engage with the community. Here's how it looks:

<img width="754" alt="image" src="https://github.com/user-attachments/assets/92c2dcbc-1f5b-467a-b0c4-6d68b543ecdf">

@rbebb It seems like he is referring to one of these options for community discussions [here](https://zeromq.org/our-community/)
