### ISSUE TITLE
Low throughput performance of zmq_proxy (update: on MacOSX)

### ISSUE THREAD

**Issue by davipt** [zeromq/libzmq#757]
Update: tl;dr: after some tests with a similar Linux machine, the Linux machine shows only a slowdown of 2 to 4 times using the proxy, which is expected, whilst the Mac shows a 20 to 40 times slowdown as soon as poll is used.

Following the performance test pattern of the local_thr and remote_thr sample code, I've picked up the Streamer proxy example from the Code Connected 1 book and tried to apply it to the test. The results are awful. 

I've forked a branch of libzmq at https://github.com/davipt/libzmq/tree/fix-002-proxy_lat_thr which includes a changed version of local_thr and remote_thr to allow local_thr to connect instead of bind, and both to switch from PUSH-PULL to PUB-SUB, plus a flag to put a counter in each message and let the other verify if any message is lost.
It also contains a proxy.cpp from the book, with commented code to try the zmq_proxy(fe,be,null) (slow), the literal zmq_code loop (slow), a faked loop that only copies from frontend to backend (fast), and a failed attempt to split the copy be->fe and fe->be into different threads.

the perf/README.txt https://raw.github.com/davipt/libzmq/fix-002-proxy_lat_thr/perf/README.txt contains instructions on how to run the standard p2p throughput test, and then how to run it via the proxy.

On my machine I'm getting, for 500B messages, a throughput of 5Gbps. Going through the proxy I'd expect worst case half or one quarter of it, but still above 1Gbps. The proxy can't go above 300Mbps.

What I do see on the wire is that the tcp packets sent by the proxy are individual messages, not the big chunks seen on the remote_thr -> proxy side, so this must be something between the poller and the batching of outgoing messages.

**Comment by bluca** [comment]
Should be fixed by https://github.com/zeromq/libzmq/pull/2518 - please reopen if you still see the issue on the laster master code
