### ISSUE TITLE
Allow creation of zeromq socket with an external file descriptor

### ISSUE THREAD

**Issue by jpakkane** [zeromq/libzmq#777]
This issue is basically a writeup of this discussion thread:

http://lists.zeromq.org/pipermail/zeromq-dev/2013-July/022229.html

The main issue is that both systemd and upstart have a concept of socket based activation. That means that the init system only starts the daemon when someone tries to connect to its socket.

In pseudocode this is roughly what would happen:

fd = get_socket_fd_from_init_system();
addr = "fd:" + to_string(fd)
zmq_bind(socket, addr)

At this point zmq opens the fd, is bound to the given port and it can keep using it as if it were  a unix domain socket.

**Comment by nickbroon** [comment]
:+1:
