### ISSUE TITLE
router socket blocked

### ISSUE THREAD

**Issue by robinliouhu** [zeromq/libzmq#778]
version:zeromq 4.01  xp32  vs2008 

1.
use a router socket (set Identify to A) connect to another router socket  (set Identify to B)  through  tcp.

2.
i kill A  (simulate crash ) ,and restart it.  i cant send  msg from B to A any more .

is it a bug?
(
i tracked the code ,found this 
1. if A dead ,the pipe state set to wait_dilimiter in B,but not erased. 
2. A restart again,try register to b use identify "A". but the identify A is used because the last pipe_t which is disconnect have not been erased in step1
3. the send func keep block..
but i still dont know waht is the right way  to resolve it. 
)

**Comment by djelenc** [comment]
Try setting the `ROUTER_HANDOVER` socket option on the router socket. By default, it is set to `0` (disabled), which means that in the case when two clients -- who have the same identity -- connect to the router socket, the router will accept messages only from the client that connected the first.

If you set the `ROUTER_HANDOVER` to `1`, the router socket will -- when multiple clients connect with the same identity -- accept messages only from the most recent one. I believe that this is the behavior that you are looking for if recovering after client failure is your use case.

**Comment by sigiesec** [comment]
@robinliouhu I assume that the suggestion by @djelenc solves your problem. If you have still any issues, feel free to reopen this issue.
