### ISSUE TITLE
Crash with "Invalid argument (session_base.cpp:538)"

### ISSUE THREAD

**Issue by sublee** [zeromq/libzmq#784]
I'm using libzmq-4.0.3 and "epgm://127.0.0.1;224.0.0.0:11042" as a ØMQ socket address. Yes, I know that localhost is not a good address to use PGM. Anyway, the application runs well for a few minutes but it crashes with the assertion failure soon:

```
Invalid argument (session_base.cpp:538)
Aborted (core dumped)
```

**Comment by sigiesec** [comment]
The line causing the failing assertion is https://github.com/zeromq/zeromq4-x/blob/8b9a82476b196a200b9698c9345ae8ba50cccb1c/src/session_base.cpp#L538

**Comment by bjovke** [comment]
@sigiesec @sublee Hm, how are we going to test this, test program is in "Go"? Can anyone convert this to C++?

**Comment by sigiesec** [comment]
@bjovke I already started converting this to a C++ test case.

**Comment by bjovke** [comment]
@sigiesec :)
