### ISSUE TITLE
Windows installer for libzmq 4.0.1 only installs binaries for the v120 toolkit

### ISSUE THREAD

**Issue by tchappui** [zeromq/libzmq#806]
Hello,

I tried to install zeromq yesterday to experiment with this library. On the following webpage http://zeromq.org/distro:microsoft-windows, it is claimed that the windows installer provides x86 binaries built with v90, v100, v110, v110_xp, and v120 toolkits. I actually only get the v120 built version for zeromq v4.0.1.

Also, the main zeromq webpage claims v4.0.3 as being the last stable version of libzmq: http://gyazo.com/2bb3b02a6a3cc5c259cbd03f32cf43b0. However, when we click on the windows installers link, only v4.0.1 is proposed for download (not a big deal): http://gyazo.com/c80313b3254ac42df02a3492e7161d41. However, downloading the source code for provides a zip for 4.0.3.

I'll try to build my own binary for v90 and v100 toolkits.

Kind regards

Thierry

**Comment by bluca** [comment]
We don't provide Windows binaries directly anymore (other projects like Conda do it instead), so closing this issue.
