### ISSUE TITLE
STREAM disconnect notification only works on the binding side

### ISSUE THREAD

**Issue by mrvn** [zeromq/libzmq#831]
In zeromq 4.1 when a peer sends a zero message to a STREAM socket the socket is closed. The other side then generates a zero message to notify the application of the disconnect. This works if the connecting side disconnects, the binding side gets a zero message.

But if the binding side disconnects then no zero message is generated.

**Comment by sigiesec** [comment]
Could you provide some example / test case that you would expect to work?
