### ISSUE TITLE
Race condition within test_disconnect_inproc.cpp

### ISSUE THREAD

**Issue by horus42** [zeromq/libzmq#843]
There is a race condition between zmq_connect(subSocket, ...) and the first zmq_msg_send(...). For testing, We simply fixed that with a pragmatic Sleep/msleep call after zmq_connect. Here is an excerpt:

<pre>
        if (iteration == 1) {
            zmq_connect(subSocket, "inproc://someInProcDescriptor") && printf("zmq_connect: %s\n", zmq_strerror(errno));
//            zmq_connect(subSocket, "tcp://127.0.0.1:30010") && printf("zmq_connect: %s\n", zmq_strerror(errno));
#ifdef ZMQ_HAVE_WINDOWS
            Sleep( 3 );
#else
            msleep( 3000 );
#endif
</pre>

If you need more information, please feel free to ask.

**Comment by bluca** [comment]
Was fixed by https://github.com/zeromq/libzmq/pull/1341
