### ISSUE TITLE
Multi-platform inconsistency within test test_ctx_options.cpp

### ISSUE THREAD

**Issue by horus42** [zeromq/libzmq#844]
When the libzmq is build for Windows/x86 (cross-compiled from Linux to MinGW) and Linux/(x86/arm/ppc/x64) the test test_ctx_options.cpp will NOT succeed for Windows, because the FD_SETSIZE is set to 64, but the test asserts in line 31 against ZMQ_MAX_SOCKETS_DFLT, which is 1023. 

To get the test going and also to ensure that the assertion is given for the libzmq.dll We pragmatically called the ./configure script with

<pre>
    CXXFLAGS="-DFD_SETSIZE=1024".
</pre>

Now the following questions remain:
1) Was updating CXXFLAGS the right solution?
2) If Windows and Linux divert shouldn't the test cover this?

Thanks in advance for Your Help.

**Comment by bluca** [comment]
Closing as the FD_SETSIZE is no longer 64 in the Windows builds
