### ISSUE TITLE
How to build zeromq on AIX ?

### ISSUE THREAD

**Issue by AsakuraYo** [zeromq/libzmq#850]
Hello, this is my first time to use zeromq and I get a problem on building the zeromq on AIX.

I download the file `zeromq-4.0.3.tar.gz` and put it on AIX. Then I use the following command to build it.

`./configure CC=xlc CXX=xlC`
`make`

Compile is OK. But when I use `make check` to check it, I get a lot of fail as below.

PASS: test_system
./config/test-driver[95]: 819564 IOT/Abort trap
FAIL: test_pair_inproc
./config/test-driver[95]: 819568 IOT/Abort trap
FAIL: test_pair_tcp
./config/test-driver[95]: 819572 IOT/Abort trap
FAIL: test_reqrep_inproc
./config/test-driver[95]: 933932 IOT/Abort trap
FAIL: test_reqrep_tcp
./config/test-driver[95]: 933936 IOT/Abort trap
FAIL: test_hwm
./config/test-driver[95]: 393276 IOT/Abort trap
FAIL: test_reqrep_device
./config/test-driver[95]: 933942 IOT/Abort trap
FAIL: test_sub_forward
./config/test-driver[95]: 381338 IOT/Abort trap
FAIL: test_invalid_rep
./config/test-driver[95]: 381342 IOT/Abort trap
FAIL: test_msg_flags
./config/test-driver[95]: 1396790 IOT/Abort trap
FAIL: test_connect_resolve
./config/test-driver[95]: 933952 IOT/Abort trap
FAIL: test_immediate
./config/test-driver[95]: 1245618 IOT/Abort trap
FAIL: test_last_endpoint
./config/test-driver[95]: 1245622 IOT/Abort trap
FAIL: test_term_endpoint
./config/test-driver[95]: 463096 IOT/Abort trap
FAIL: test_monitor
./config/test-driver[95]: 381396 IOT/Abort trap
FAIL: test_router_mandatory
./config/test-driver[95]: 381400 IOT/Abort trap
FAIL: test_router_raw_empty
./config/test-driver[95]: 381404 IOT/Abort trap
FAIL: test_probe_router
./config/test-driver[95]: 1396814 IOT/Abort trap
FAIL: test_stream
./config/test-driver[95]: 381422 IOT/Abort trap
FAIL: test_disconnect_inproc
./config/test-driver[95]: 749688 IOT/Abort trap
FAIL: test_ctx_options
./config/test-driver[95]: 1396822 IOT/Abort trap
FAIL: test_ctx_destroy
./config/test-driver[95]: 1396826 IOT/Abort trap
FAIL: test_security_null
./config/test-driver[95]: 1396830 IOT/Abort trap
FAIL: test_security_plain
PASS: test_security_curve
./config/test-driver[95]: 1396836 IOT/Abort trap
FAIL: test_iov
./config/test-driver[95]: 1323084 IOT/Abort trap
FAIL: test_spec_req
./config/test-driver[95]: 1245686 IOT/Abort trap
FAIL: test_spec_rep
./config/test-driver[95]: 147774 IOT/Abort trap
FAIL: test_spec_dealer
./config/test-driver[95]: 393346 IOT/Abort trap
FAIL: test_spec_router
./config/test-driver[95]: 459114 IOT/Abort trap
FAIL: test_spec_pushpull
./config/test-driver[95]: 618732 IOT/Abort trap
FAIL: test_req_correlate
./config/test-driver[95]: 1396880 IOT/Abort trap
FAIL: test_req_relaxed
./config/test-driver[95]: 1396884 IOT/Abort trap
FAIL: test_conflate
./config/test-driver[95]: 893268 IOT/Abort trap
FAIL: test_inproc_connect
./config/test-driver[95]: 147850 IOT/Abort trap
FAIL: test_issue_566
./config/test-driver[95]: 934000 IOT/Abort trap
XFAIL: test_abstract_ipc
./config/test-driver[95]: 934002 IOT/Abort trap
FAIL: test_many_sockets
./config/test-driver[95]: 254212 IOT/Abort trap
FAIL: test_shutdown_stress
./config/test-driver[95]: 1396922 IOT/Abort trap
FAIL: test_pair_ipc
./config/test-driver[95]: 459152 IOT/Abort trap
FAIL: test_reqrep_ipc
./config/test-driver[95]: 459156 IOT/Abort trap
FAIL: test_timeo
./config/test-driver[95]: 749724 IOT/Abort trap
FAIL: test_fork

```
Testsuite summary for zeromq 4.0.3
# TOTAL: 43
# PASS:  2
# SKIP:  0
# XFAIL: 1
# FAIL:  40
# XPASS: 0
# ERROR: 0
```

I guess the issue is in the setting of `./configure`. So I want to know how to build it on AIX? Or how to execute `./configure` correctly on AIX?

In addition, the system information is as below.
`xlC -qversion`
C for AIX version 6.0.0.0
`oslevel`
5.3.0.0
#### Some core dump information is as below.

`dbx .libs/lt-test_pair_inproc core`
(dbx) where
pthread_kill(??, ??) at 0x90000000062781c
_p_raise(??) at 0x900000000627230
raise.raise(??) at 0x900000000063578
abort() at 0x90000000008eb04
zmq_abort(const char*)(errmsg_ = "Invalid argument"), line 74 in "err.cpp"
unnamed block in ctx.lock()(0x9001000a29ea970), line 99 in "mutex.hpp"
ctx.lock()(0x9001000a29ea970), line 99 in "mutex.hpp"
ctx.add(unsigned int)(0x9001000a29ea968, 0x100000001), line 111 in "atomic_counter.hpp"
zmq::ctx_t::create_socket(int)(this = 0x000000011000ddf0, type_ = 0), line 275 in "ctx.cpp"
zmq_socket(ctx_ = 0x000000011000ddf0, type_ = 0), line 254 in "zmq.cpp"
main(), line 28 in "test_pair_inproc.cpp"

`dbx .libs/lt-test_pair_tcp core`
(dbx) where
pthread_kill(??, ??) at 0x90000000062781c
_p_raise(??) at 0x900000000627230
raise.raise(??) at 0x900000000063578
abort() at 0x90000000008eb04
zmq_abort(const char*)(errmsg_ = "Invalid argument"), line 74 in "err.cpp"
unnamed block in ctx.lock()(0x9001000a29ea970), line 99 in "mutex.hpp"
ctx.lock()(0x9001000a29ea970), line 99 in "mutex.hpp"
ctx.add(unsigned int)(0x9001000a29ea968, 0x100000001), line 111 in "atomic_counter.hpp"
zmq::ctx_t::create_socket(int)(this = 0x000000011000db50, type_ = 0), line 275 in "ctx.cpp"
zmq_socket(ctx_ = 0x000000011000db50, type_ = 0), line 254 in "zmq.cpp"
main(), line 28 in "test_pair_tcp.cpp"

`dbx .libs/lt-test_hwm core`
(dbx) where
pthread_kill(??, ??) at 0x90000000062781c
_p_raise(??) at 0x900000000627230
raise.raise(??) at 0x900000000063578
abort() at 0x90000000008eb04
zmq_abort(const char*)(errmsg_ = "Invalid argument"), line 74 in "err.cpp"
unnamed block in ctx.lock()(0x9001000a29ea970), line 99 in "mutex.hpp"
ctx.lock()(0x9001000a29ea970), line 99 in "mutex.hpp"
ctx.add(unsigned int)(0x9001000a29ea968, 0x100000001), line 111 in "atomic_counter.hpp"
zmq::ctx_t::create_socket(int)(this = 0x000000011000da90, type_ = 7), line 275 in "ctx.cpp"
zmq_socket(ctx_ = 0x000000011000da90, type_ = 7), line 254 in "zmq.cpp"
test_defaults()(), line 33 in "test_hwm.cpp"
main(), line 262 in "test_hwm.cpp"

**Comment by bluca** [comment]
4.2.x has been confirmed to build on AIX, closing
