### ISSUE TITLE
Unable to bind to specific interface when IPv6 is enabled for socket on Win8.

### ISSUE THREAD

**Issue by Kentzo** [zeromq/libzmq#853]
By using pyzmq:

```
c = zmq.Context.instance()
s = zmq.socket(zmq.ROUTER)
s.ipv6 = True
s.bind_to_random_port('tcp://192.168.56.1')  # Throws the "No such device" exception. The interface exists.
s.bind_to_random_port('tcp://fe80::8d3b:c128:5077:b64d') # No exception
```

The same problem with a straight bind.

Note that both on Linux and Mac it works.
I'm using Win8 Pro with all updates installed.

**Comment by t-b** [comment]
Here is a failing test in C:

```c
#include "testutil.hpp"

int main (void)
{
    setup_test_environment();
    int ipv6 = is_ipv6_available ();
    void *ctx = zmq_ctx_new ();
    assert (ctx);

    void *sb = zmq_socket (ctx, ZMQ_REP);
    assert (sb);

    assert(ipv6);
    int rc = zmq_setsockopt(sb, ZMQ_IPV6, &ipv6, sizeof(int));
    assert(rc == 0);

    rc = zmq_bind (sb, "tcp://127.0.0.1:5555");
    assert (rc == 0);

    rc = zmq_ctx_term (ctx);
    assert (rc == 0);

    return 0;
}
```

**Comment by bluca** [comment]
When IPv6 is enabled, if a bind with an IPv4 address is requested the IPv4-in-IPv6 address format will be used.

Does Windows support that? If not, or if there are flags/syscalls to do to enable it, that will likely be the problem.

**Comment by t-b** [comment]
@bluca (I'm pretty new to socket programming on windows)

If I understand [1] correctly this ipv4in6 format is supported by windows.

Looking into the code the function `zmq::enable_ipv4_mapping` enables that. 

My test case above calls `zmq_bind`  and inside `zmq::tcp_listener_t::set_address (const char *addr_)`, but the latter does not call `enable_ipv4_mapping` as it immediately returns after calling address.resolve.

[1]: https://msdn.microsoft.com/en-us/library/windows/desktop/bb513665(v=vs.85).aspx

**Comment by bluca** [comment]
Yes you are right, and there is support for windows in enable_ipv4_mapping.
Then it will most likely be a problem in tcp_address.cpp resolve_interface(). If you can, running that through the debugger might shed some light on the exact error.

**Comment by t-b** [comment]
Here are my findings:
- The line `rc = getaddrinfo (interface_, NULL, &req, &res);` in tcp_address.cpp:L326 fails with rc 11001 (EAI_NONAME).
- Chaning line 312 from `req.ai_flags = AI_PASSIVE | AI_NUMERICHOST;` to `req.ai_flags = AI_PASSIVE;` does fix this particuluar bug. But I don't think this is the correct thing to do.

**Comment by bluca** [comment]
Yes we really don't want DNS lookups in there I think.

**Comment by soulik** [comment]
I've implemented draft solution for this.
Now you can bind to address: tcp://127.0.0.1:* under Windows.
Please, have a look if this resolved your issue.

Also, I've managed to push the commit instead of PR. That's the price for using GUI for Git.

**Comment by bluca** [comment]
@soulik - please be careful and set the git remote to your fork instead of the organization repository...
A push of a recursive merge node straight to the master branch with a diffstat of 513 file changes, with 9,323 additions and 4,016 deletions will cause quite a lot of a pain, and it will kill git bisect :-(

**Comment by soulik** [comment]
I promise I'll be careful.

**Comment by bluca** [comment]
Closing as it was fixed
