### ISSUE TITLE
Assertion Failure in stream engine constructor

### ISSUE THREAD

**Issue by amillerrhodes** [zeromq/libzmq#868]
I'm getting an assertion failure on a listening socket when I port scan it. 

To reproduce, use the hello world server example from the guide (http://zguide.zeromq.org/c:hwserver) and run a port scan on the listening port with the following command:

```
nmap -sT localhost -p5555
```

The result is:

```
Transport endpoint is not connected (ip.cpp:137)
Aborted (core dumped)
```

I believe the assertion that is failing is in `get_peer_ip_address` called from the `stream_engine_t` constructor (stream_engine.cpp:87).

Removing `ENOTCONN` (ip.cpp:136) from the `ernno_assert` check seems to fix the problem. I'm not sure if this fix causes any adverse effects, though.

**Comment by bluca** [comment]
Closing as it was fixed by https://github.com/zeromq/libzmq/pull/870
