### ISSUE TITLE
Assertion `rc == 0' failed with test_security_null.cpp and test_resource.cpp

### ISSUE THREAD

**Issue by brunoqc** [zeromq/libzmq#878]
I have `Assertion rc == 0' failed` with two unit tests.

``` bash
lt-test_security_null: test_security_null.cpp:87: int main(): Assertion `rc == 0' failed.
/bin/bash: line 5: 27965 Aborted                 (core dumped) ${dir}$tst
```

``` bash
lt-test_resource: test_resource.cpp:44: int main(int, char**): Assertion `rc == 0' failed.
/bin/bash: line 5: 27632 Aborted                 (core dumped) ${dir}$tst
XFAIL: test_resource
```

The `test_resource.cpp` one also happened on the last travis build: https://travis-ci.org/zeromq/libzmq/builds/18542339#L1070

libzmq e376ad2787ebef91748921f1fb4766ce2b49d6a7
Ubuntu 12.04.4 LTS (32-bits)

**Comment by bluca** [comment]
Tests were fixed in Travis by PR https://github.com/zeromq/libzmq/pull/881 and are now working on Ubuntu 12.04 32 and 64 bits
