### ISSUE TITLE
Reconnect due to ZAP authentication failure ignores ZMQ_RECONNECT_IVL_MAX.

### ISSUE THREAD

**Issue by hashstat** [zeromq/libzmq#883]
When a server performing ZAP authentication rejects a client with a 400 (or other non-200) error, the client will use ZMQ_RECONNECT_IVL to calculate the reconnect timeout but never performs the exponential backoff strategy according to the ZMQ_RECONNECT_IVL_MAX option. Contrast this with a client that cannot connect to the server at all. Therefore, failed authentication can cause an indefinite number of connection attempts, especially when considered with issue #882.

But don't worry. I have a fix.

**Comment by sigiesec** [comment]
I had a look at your changes, but I do not quite understand how they relate to ZAP errors. Aren't they related to any reconnects during handshaking?

Would you care to submit them as a PR?
