### ISSUE TITLE
signaler_t::wait() can hang w/ ZMQ_FORCE_SELECT

### ISSUE THREAD

**Issue by olafmandel** [zeromq/libzmq#893]
When compiling zeromq with `ZMQ_FORCE_SELECT` under Cygwin calls to `signaler_t::wait()` can hang forever. This is, e.g. apparent when issuing `zmq_ctx_destroy()`.

The problem is triggered in `signaler.cpp:201`: `FD_SET (r, &fds);`: if `r >= FD_SETSIZE`, this causes the `fds` structure to be invalid.

As for how `r >= FD_SETSIZE` can happen:
1. Apparently under Cygwin, FD_SETSIZE is not changed to be 1024 as for the MSVC build
2. The file descriptors are spaced by two under Cygwin: so even in a best case, only FD_SETSIZE/2 signalers are possible. Under Linux, this seems to not be a problem

Will add a test case to https://github.com/zeromq/issues .

**Comment by bluca** [comment]
Closing as FD_SETSIZE was fixed in Cygwin as well by https://github.com/zeromq/libzmq/pull/2035
