### ISSUE TITLE
ZeroMQ XPUB/XSUB - Why does this not work

### ISSUE THREAD

**Issue by vivekfantain** [zeromq/libzmq#897]
I was trying to understand XPUB/XSUB and was going through the espresso.py code.  I noticed that in the code the XSUB socket actually connects to the PUB socket instead of the other way around ie XSUB socket should bind on a well known port and the PUB socket should issue a connect() I changed the code according to that pattern and espresso.py stopped working.  

Code is here https://gist.github.com/vivekfantain/9021979

**Comment by bluca** [comment]
Closing as this is the same as #2267 and https://zeromq.jira.com/browse/LIBZMQ-270
