### ISSUE TITLE
inproc issue with: zmq_bind() and zmq_unbind()

### ISSUE THREAD

**Issue by horus42** [zeromq/libzmq#918]
Sample code:
zmq_bind( s, "inproc://XXX" );
zmq_unbind( s, "inproc://XXX" );

Issue: 
unbind will tell that the given inproc doesn't actually exist. This error is originating from socket_base.cpp:718. The inproc member variable does not contain the bound address. Size of the inproc container is 0.

Is this a bug or working as intended?

**Comment by calid** [comment]
@hintjens @hurtonm probably can close this as a duplicate of #949

**Comment by hintjens** [comment]
OK, closing as duplicate.
