### ISSUE TITLE
Problem: zmq_proxy in 4.0.x is unsteerable

### ISSUE THREAD

**Issue by hintjens** [zeromq/libzmq#929]
Lacking any API to control the proxy once started, it's pretty poor. 

Solution: backport  zmq_proxy_steerable from 4.1.x.

**Comment by rabinnh** [comment]
Could this be why, using  zmq.hpp, when I use:

		zmq_proxy(*zIngress, *zEgress, *zTap);

If "zTap" is not NULL I don't get output on the zEgress or zTap sockets, but when zTap is NULL zEgress works properly?
