### ISSUE TITLE
Cannot have autogen.sh working

### ISSUE THREAD

**Issue by MilesYM** [zeromq/libzmq#953]
when doing the following command:

./autogen.sh

here is what I get:

autoreconf: Entering directory `.'
autoreconf: configure.ac: not using Gettext
autoreconf: running: aclocal -I config --force -I config
main::scan_file() called too early to check prototype at /opt/lo/bin/aclocal line 617.
autoreconf: configure.ac: tracing
autoreconf: configure.ac: subdirectory foreign/openpgm/build-staging/openpgm/pgm/ not present
autoreconf: configure.ac: not using Libtool
autoreconf: running: /opt/lo/bin/autoconf --include=config --force
configure.ac:57: error: possibly undefined macro: AC_LIBTOOL_WIN32_DLL
      If this token and others are legitimate, please use m4_pattern_allow.
      See the Autoconf documentation.
configure.ac:58: error: possibly undefined macro: AC_PROG_LIBTOOL
configure:5242: error: possibly undefined macro: AC_DISABLE_STATIC
configure:5246: error: possibly undefined macro: AC_ENABLE_STATIC
autoreconf: /opt/lo/bin/autoconf failed with exit status: 1
autogen.sh: error: autoreconf exited with status 0

And I can't have it working.

Please help

Many Thanks

**Comment by bluca** [comment]
As the log suggested libtool is missing. A check has been added so closing this now
