### ISSUE TITLE
Perl ZeroMQ broker busy waits at 100% CPU.

### ISSUE THREAD

**Issue by chrestomanci** [zeromq/libzmq#955]
Using the Perl example code for how to run a ZeroMQ broker. (AKA Router), I have found that the broker process will consume 100% of one CPU. Debugging with strace suggests that the ZMQ process is busy waiting on a socket.

I am running on Ubuntu linux using the distro version of ZeroMQ: 3.2.3+dfsg-2 using a locally compiled version of ZMQ::LibZMQ3 (The perl bindings), and a locally complied perl at version 5.16.3

I have reproduced this issue using the perl example code from the ZeroMQ website:
http://zguide.zeromq.org/pl:rrbroker

When I run the broker code above with no clients connecting the broker will consume 100% CPU. If I connect clients and send messages the CPU usage reduces for a while and then goes back up when the messages stop.

**Comment by bluca** [comment]
Should be fixed by https://github.com/zeromq/libzmq/pull/2518 - please reopen if you still see the issue on the laster master code
