### ISSUE TITLE
sockets created by accept are leaked to child processes

### ISSUE THREAD

**Issue by jkryl** [zeromq/libzmq#956]
IPC and TCP sockets which originated from accept() don't have close-on-exec (CLOEXEC) flag set, hence if process spawns child processes those socket descriptors are leaked to the child processes.

I have a fix which sets CLOEXEC on socket after it is returned from accept(). The solution is not complete because there's still a window between accept and fcntl where socket can be leaked to child, but it's better than nothing and on platforms which don't have paccept() it's probably the best achievable solution. I will submit a pull request shortly.

**Comment by bluca** [comment]
Closing as it was fixed by https://github.com/zeromq/libzmq/pull/957
