### ISSUE TITLE
Add support for controlling TCP_USER_TIMEOUT socket option.

### ISSUE THREAD

**Issue by shlomosh** [zeromq/libzmq#976]
On some network problem issues TCP connection might hang until kernel tcp_retries2 timer expires (13-30 minutes) and release it. In order to allow fast-recovery for TCP sockets the TCP_USER_TIMEOUT option was added to Linux kernel as of 2.6.37.

The TCP_USER_TIMEOUT options allows controlling per-socket timeout by specifies the maximum amount of time that transmitted data may remain unacknowledged before TCP will forcibly close.

It will be very nice if ZMQ can add control over the TCP_USER_TIMEOUT socket option similar to how it allows control over TCP_KEEPALIVE option.

**Comment by bluca** [comment]
Closing as it was implemented by https://github.com/zeromq/libzmq/pull/1510 (ZMQ_TCP_MAXRT)
